### ISSUE TITLE
Unable to r/w from S3 bucket

### ISSUE THREAD

**Issue by jcderr** [docker/distribution#1003]
I'm using registry:2 against S3 storage. This has been working fine for quite a while, until we had a host failover today. After this happened, the kubernetes pod got rescheduled to another host but was unable to read the repositories from the S3 location.

The AWS Credentials given are confirmed to work with the bucket. In fact, if I `docker push` to this registry, it will begin creating files in the correct _upload locations, but the first layer will always fail with a 500 gateway error. Any attempt to pull is met with a 404, and /v2/_catalog returns a null set.

**Comment by jcderr** [comment]
I updated the title. I'm apparently having total S3 failure, even when I change buckets and allow it to create a new registry store.

The push refers to a repository [(hostname)/bb] (len: 1)
8c2e06607696: Pushing [==================================================>]     32 B/32 B
Received unexpected HTTP status: 504 GATEWAY_TIMEOUT

**Comment by RichardScothern** [comment]
Do you have delete permissions on that bucket? (this is required to complete the upload)  

What do your S3 logs say?

**Comment by jcderr** [comment]
I have full `s3:*` permissions. Just for the sake of completeness, I also attempted this by living dangerously and using root user keys as well. Same response.

I'm awaiting delivery of S3 logs.

**Comment by RichardScothern** [comment]
Any joy with the logs @jcderr ?

**Comment by scalp42** [comment]
@jcderr any updates?

**Comment by jcderr** [comment]
I haven't had any recurrences since upgrading to 2.2. Whatever the issue
was, it appears to have been resolved.

On Tue, Nov 10, 2015 at 1:52 PM Anthony Scalisi <notifications@github.com>
wrote:

> @jcderr <https://github.com/jcderr> any updates?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/distribution/issues/1003#issuecomment-155547228>
> .
>
-- 
Jeremy Derr
jeremy@derr.me

When in trouble or in doubt, run in circles, scream and shout.

**Comment by stevvooe** [comment]
@jcderr I'd recommend you contact AWS support regarding this to have them investigate. It's good that everything is resolved, but it would be good to know what happened.
