### ISSUE TITLE
Allow S3 url to be provided in place of region

### ISSUE THREAD

**Issue by mindscratch** [docker/distribution#1007]
Currently the S3 driver only allows a region to be provided for connecting to S3. If a region is not yet defined in the [library](https://github.com/AdRoll/goamz/blob/master/aws/regions.go) used by the driver, then you're out of luck.

It would be nice to be able to explicitly set the URL used to talk to S3.

**Comment by mboersma** [comment]
This will be fixed by expanded S3 support in #808.

**Comment by BrianBland** [comment]
Closing as a duplicate of #808
