### ISSUE TITLE
No bugsnag report triggered on 500

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#101]
In conditions like #100 no report is added to bugsnag.

cc @jlhawn

**Comment by stevvooe** [comment]
@jlhawn Have we seen any bugsnag reports when panicking?

**Comment by jlhawn** [comment]
@dmp42 @stevvooe No, nothing seen yet on bugsnag https://bugsnag.com/docker/registry-go/errors

**Comment by stevvooe** [comment]
We'll have to look into this closer, then.

**Comment by dmp42** [comment]
Josh, can you take this over?

**Comment by stevvooe** [comment]
It looks like we should convert to using bugsnag hooks in logrus:

https://github.com/Sirupsen/logrus/blob/master/hooks/bugsnag/bugsnag.go

**Comment by stevvooe** [comment]
@dmp42 We are going to remove bugsnag. Closing this.
