### ISSUE TITLE
Redundant private registry in AWS not working as expected

### ISSUE THREAD

**Issue by dlyub** [docker/distribution#1017]
Versions:
Docker 1.8.2
Docker registry 2.1.1

Setup:
S3 bucket
two EC2 instances
one Route53 A record that resolves to IPs of the two EC2 instances

Problem:
When both EC2 instances are up and running everything works fine. As soon as I take one of them down docker pulls stop working and I keep getting "not found" messages. As soon as I bring up the second node the registry is working again.

Docker run command:
docker run -d -p 5000:5000 --restart=always -v /certs:/certs -e "REGISTRY_HTTP_SECRET=<secret-same_for_both_nodes>"  -e "REGISTRY_STORAGE=s3" -e "REGISTRY_STORAGE_S3_REGION=us-east-1" -e "REGISTRY_STORAGE_S3_BUCKET=<bucketname>" -e "REGISTRY_STORAGE_S3_ACCESSKEY=<accesskey>" -e "REGISTRY_STORAGE_S3_SECRETKEY=<secretkey>" registry:2.1.1

**Comment by RichardScothern** [comment]
I don't think the problem here is with the registry.  If it is not being contacted when you remove an EC2 instance there the problem lies with routing or the docker daemon.

**Comment by dlyub** [comment]
@RichardScothern 

Is is being contacted, and I see the registry returning 200 OK, but there's no communication past that.

**Comment by RichardScothern** [comment]
So it's being pinged correctly and returning OK.  What do the daemon logs say?

**Comment by dlyub** [comment]
Here's what I see in the docker container log output:

Client_IP - - [24/Sep/2015:19:12:15 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"
Client_IP - - [24/Sep/2015:19:12:45 +0000] "GET /v1/repositories/test-image/images HTTP/1.1" 404 19 "" "docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"

is daemon log different from that? Where is is located?

**Comment by RichardScothern** [comment]
That is the daemon log.  You can see that it's attempting a call to a v1 registry for some reason (I presume because it's falling back due to not being able to contact the v2 registry)

If you run your daemon in debug mode (`-d` flag) you will get more context.

**Comment by dlyub** [comment]
added -D to the daemon, not seeing much useful info

time="2015-09-24T20:34:43Z" level=info msg="response completed" http.request.host="<docker_reg_dns_name>:5000" http.request.id=5c2f9d01-06bf-4990-9995-973477e276b8 http.request.method=GET http.request.remoteaddr="Client_IP:41563" http.request.uri="/v2/" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.487644ms http.response.status=200 http.response.written=2 instance.id=ebb6be95-4bc3-44c9-a047-f30ae66b85dd version=v2.1.1
Client_IP - - [24/Sep/2015:20:34:43 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"
Client_IP - - [24/Sep/2015:20:35:13 +0000] "GET /v1/repositories/test-image/images HTTP/1.1" 404 19 "" "docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"

**Comment by dlyub** [comment]
I brought up the second node and I see the same get request on both nodes. My expectation was that Route53 will resolve the name to one of the addresses. Need to better understand what's going on in Route53.

**Comment by dlyub** [comment]
@RichardScothern I found the problem in the Route53 config. Thank you for your help.

**Comment by RichardScothern** [comment]
glad to hear it.
