### ISSUE TITLE
How to retrieve label of image through the API

### ISSUE THREAD

**Issue by bronger** [docker/distribution#1025]
I try to retrieve the label (set with LABEL in the Dockerfile) of an image in a private registry by using the v2 API.  Currently, I have use the following convoluted Python code for this:

    json.loads(manifest["history"][0]["v1Compatibility"])["container_config"]["Labels"]

I don't see a cleaner way to do this using the v2 API but I think there should be one.

**Comment by RichardScothern** [comment]
The data structure containing that information is contained in the v2 manifest within the `v1Compatibility` section

**Comment by bronger** [comment]
Yes, this is what the Python code above extracts.  But shouldn't there be a dedicated place for it in the v2 API?

**Comment by RichardScothern** [comment]
I'm afraid there is no dedicated place for within this version of the manifest schema.  The schema is a bridge between the old manifest format and a new version is being actively proposed [here(https://github.com/docker/distribution/pull/993)
