### ISSUE TITLE
Add a configuration option to disable the notification

### ISSUE THREAD

**Issue by AdoHe** [docker/distribution#1026]
Now even I don't provide any notification endpoints, distribution will start a `goroutine` for broadcast. I think we should add a option to disable the notification, this should be better.

**Comment by RichardScothern** [comment]
Thanks for the suggestion @AdoHe .  Goroutines are very inexpensive to create and I think an option to control this would just add confusion without much benefit.

**Comment by AdoHe** [comment]
@RichardScothern I understand that Goroutines are very inexpensive to create, for notifications implementation, it use event bridge, we create wrapper of the origin `repository`, for repository middleware, it is the same. If we have an option to disable the notification, we have no need to create so many events, we do need event notifications, but we just care some kinds of notification, especially in private docker registry of companies.

**Comment by stevvooe** [comment]
@AdoHe Is this causing a problem for you?

If this is just a code recommendation, please just submit a PR so we can be explicit about what you mean.

**Comment by AdoHe** [comment]
@stevvooe Ok, I will.
