### ISSUE TITLE
Unclear about dryrun settings in storage_maintenance_uploadpurging

### ISSUE THREAD

**Issue by farmerworking** [docker/distribution#1037]
According to the document, when dryrun is set true, you can obtain a summary of what directories will be deleted. 

But how to obtain this information is not mentioned anywhere in the documentation.

What remains unclear is:
1. does that means directories will not be deleted unless you confirm it?
2. how about the time when directories are already removed, will these removed directories still remains in the summary?
3. does this information persist or after distribution server restart, the information is lost?

**Comment by RichardScothern** [comment]
When dry-run is set, any directories that would be removed are logged to stdout, rather than actually being removed.  The only way to access this information is through the logs.
