### ISSUE TITLE
How to override an array type configuration using environment variable

### ISSUE THREAD

**Issue by farmerworking** [docker/distribution#1038]
For example, notifications_endpoints may have many iterms. How to override one of them using environment variable.

I guess REGISTRY_NOTIFICATIONS_ENDPOINTS_0_DISABLE should work

**Comment by RichardScothern** [comment]
This is not possible with the configuration system.  If you wish to provide this level of configuration, it's best to do it in a config file.

The github issue tracker is not the right place for these questions.  Please post them to #docker-distribution on IRC - you will get a larger audience.

**Comment by aaronlehmann** [comment]
I second @RichardScothern's suggestion of using a configuration file. However, if you must use an environment variable, note that the contents of the environment variable is parsed as YAML. So it should be possible to set REGISTRY_NOTIFICATIONS_ENDPOINTS to a YAML fragment that fully describes the endpoints configuration.
