### ISSUE TITLE
s3: Use profiles when selecting credentials from ~/.aws/credentials

### ISSUE THREAD

**Issue by leedm777** [docker/distribution#1041]
AWS tooling which reads credentials from `~/.aws/credentials` also supports profile selection. This allows folks with multiple AWS accounts to select which account credentials they wish to use for particular tasks. This is usually specified by either configuration, with with the `AWS_PROFILE` or `AWS_DEFAULT_PROFILE` environment variables.

See http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles

It would be nice if the `s3` section included a configuration option for `profile`, or the registry honored the `AWS_PROFILE` environment variable.

**Comment by stevvooe** [comment]
@leedm777 Most of this behavior is provided by AdRoll/goamz and most of it works. Did you try to provide the `AWS_PROFILE` environment variable and not have it work? Is that a standard variable?

**Comment by leedm777** [comment]
> Did you try to provide the AWS_PROFILE environment variable and not have it work?

Correct.

> Is that a standard variable?

Yes, both `AWS_PROFILE` and `AWS_DEFAULT_PROFILE`, which apparently do the same thing.

**Comment by stevvooe** [comment]
@leedm777 Ok. Do you mind filing this over in AdRoll/goamz, referencing this issue? For proper support, it really needs to be implemented in the library.
