### ISSUE TITLE
Add AuthVersion to registry storage driver swift

### ISSUE THREAD

**Issue by tdsparrow** [docker/distribution#1044]
Registry only maps partial swift connection parameters to config.yml, lacking parameter like AuthVersion. It's hard to use swift service with custom url.

**Comment by RichardScothern** [comment]
@nevermosby, what are your thoughts here?

**Comment by nevermosby** [comment]
@RichardScothern sorry for reply late.
@tdsparrow could u provide further information to explain how AuthVersion is necessary for using swift service with custom url?

**Comment by tdsparrow** [comment]
Sorry not updating on time.

Here's my story. Our team has already ran a Ceph cluster, so I want to setup our private registry with swift backend. The authurl  my colleague gave me didn't contain api version "v1.0" but http://example.com/auth/1.0. I thought it's a custom url (after posting this issue, i found our service support both auth/1.0 and auth/v1.0 endpoint)

With authurl http://example.com/auth/1.0, docker distribution will complain unable to guess swift api version, require explicit authversion configuration. However distribution didn't export this supported by dependency ncw/swift

**Comment by luckyraul** [comment]
+1
Our Swift Storage Service Provider use authurl =  https://auth.xxx.net/. And the Registry can't guess the version unless  I set it by AuthVersion parameter

**Comment by luckyraul** [comment]
@nevermosby any updates?

**Comment by nevermosby** [comment]
@luckyraul Sorry for reply late.
I think you can file a PR for this feature and I can help for review.

**Comment by luckyraul** [comment]
#1627
