### ISSUE TITLE
Can't make work .htpasswd authentication with signed certs

### ISSUE THREAD

**Issue by kopax** [docker/distribution#1046]
HI everyone.
I am trying hard to enable .htpasswd TLS authentication in my docker registry.
After a few hours of deprecated documentation and tutorials, I think I might need some of your help.

I choose to try the `config.yml` way (but I did also tried the by using environment vars and land to the same problem): 
 
	version: 0.1
	log:
	  fields:
	    service: registry
	storage:
	  cache:
	    blobdescriptor: inmemory
	  filesystem:
	    rootdirectory: /docker-data/registry
	  maintenance:
	    uploadpurging:
	      enabled: true
	      age: 168h
	      interval: 24h
	      dryrun: false
	http:
	  addr: :5000
	  secret: s3cR4tReGisTRy
	  headers:
	    X-Content-Type-Options: [nosniff]
	  tls:
	    certificate: /etc/ssl/certs/wildcard.domain.com.chained.crt
	    key: /etc/ssl/private/wildcard.domain.com.key
	health:
	  sotragedriver:
	    enabled: true
	    interval: 10s
	    threshold: 3
	auth:
	  htpasswd:
	    realm: "Registry Realm"
	    path: /auth/.htpasswd

Here is the Dockerfile I used to create the __registry 2__ instance :

    FROM registry:2
    COPY config.yml /etc/docker/registry/config.yml

My nginx looks like this :

    upstream docker-registry {
      server registry:5000;
    }

    server {
      listen 443 ssl http2;
      
      server_name docker.domain.com;
      server_tokens off;
      root /dev/null;

      client_max_body_size 0; # disable any limits to avoid HTTP 413 for large image uploads

		ssl on;

		# certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
		ssl_certificate /etc/ssl/certs/wildcard.domain.com.chained.crt;
		ssl_certificate_key /etc/ssl/private/wildcard.domain.com.key;
		ssl_session_timeout 24h;
		ssl_session_cache shared:SSL:10m;

		# Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits or better
		ssl_dhparam /etc/ssl/dhparam-2048.pem;

		ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
		ssl_prefer_server_ciphers on;

		## OCSP Stapling ---
		## fetch OCSP records from URL in ssl_certificate and cache them
		ssl_stapling on;
		ssl_stapling_verify on;

		## verify chain of trust of OCSP response using Root CA and Intermediate certs
		ssl_trusted_certificate /etc/ssl/certs/GandiStandardSSLCA2.pem;

		resolver 127.0.0.1;

      # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
      chunked_transfer_encoding on;

      location /v2/ {
        # Do not allow connections from docker 1.5 and earlier
        # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
        if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
          return 404;
        }

        proxy_headers_hash_max_size     51200;
        proxy_headers_hash_bucket_size  6400;
        auth_basic                      "Registry Realm";
        auth_basic_user_file             /etc/nginx/htpasswd/docker/.htpasswd;
        add_header                       'Docker-Distribution-Api-Version' 'registry/2.0' always;
        
        proxy_set_header                 Host $http_host;
        proxy_set_header                 X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header                 X-Real-IP $remote_addr;
        proxy_set_header                 X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header                 X-Forwarded-Proto $scheme;
        proxy_set_header                 X-Original-URI $request_uri;
        proxy_set_header                 Docker-Distribution-Api-Version registry/2.0;

        proxy_read_timeout               900;
        proxy_pass                       http://docker-registry;
      }

      location /v1/_ping {
        auth_basic off;
        return 200 'V2 registry';
      }

      access_log  /var/log/nginx/docker_access.log;
      error_log   /var/log/nginx/docker_error.log;

    }

And finaly the `docker-compose.yml`
By accessing the url `https://docker.domain.com` I got the following error 

    registry:
      build: registry
      restart: always
      volumes:
        - /docker-data/domain/ssl:/etc/ssl:ro
        - /docker-data/domain/htpasswd/docker:/auth:ro
      ports: 
        - "127.0.0.1::5000"
    nginx:
      build: nginx
      restart: always
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - /docker-data/domain/htpasswd:/etc/nginx/htpasswd:ro
        - /docker-data/domain/ssl:/etc/ssl:ro
        - /docker-data/domain/logs/nginx:/var/log/nginx
      external_links:
        - registry_registry_1:registry

Do I have anything else to configure ?

Regarding this link : [Failed tls handshake. Does not contain any IP SANs](http://serverfault.com/questions/611120/failed-tls-handshake-does-not-contain-any-ip-sans)

 - I might have to configure an extra_hosts "127.0.0.1:docker.domain.com" on registry_registry_1 container ?
 - Should I do the same in nginx container "registry_registry_1:docker.domain.com"

At this point, I can only access through the nginx reverse proxy to  a `ERR_INVALID_RESPONSE` page.

Docker registry process log : 

    http: TLS handshake error from 172.17.1.83:60423: tls: first record does not look like a TLS handshake

Nginx reverse proxy process  log :

__error.log__

    2015/09/30 12:13:57 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53

__docker_error.log__

    upstream sent no valid HTTP/1.0 header while reading response header from upstream, client: 82.231.222.221, server: docker.domain.com, request: "GET /v2/ HTTP/2.0", upstream: "http://172.17.1.77:5000/v2/", host: "docker.domain.com"

I have tried to login by the following ways :

__login from docker host to docker registry process__ _(note: registry ip retrieved from `docker inspect registry_registry_1 | grep IP`)_

    $ docker login 172.17.1.93:5000
    FATA[0003] Error response from daemon: v1 ping attempt failed with error: Get https://172.17.1.93:5000/v1/_ping: x509: cannot validate certificate for 172.17.1.93 because it doesn't contain any IP SANs. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 172.17.1.93:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/172.17.1.93:5000/ca.crt

__login from my local docker host to docker host nginx reverse proxy process__

    $ docker login docker.domain.com
    FATA[0003] Error response from daemon: no successful auth challenge for https://docker.domain.com/v2/ - errors: [Get https://docker.domain.com/v2/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"]

_seems to be the_ `ERR_INVALID_RESPONSE`

I am trying hard to debug this, what is going wrong ?

**Comment by kopax** [comment]
I have now remove the auth with tls from the registry and left the security on top of nginx.
I have the following json now :

    {"errors":[{"code":"UNAVAILABLE","message":"service unavailable","detail":"health check failed: please see /debug/health"}]}


All request return from registry to nginx proxy

    172.17.0.77 - - [30/Sep/2015:15:39:49 +0200] "GET /v2/ HTTP/1.0" 503 125 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"

Nginx does 

   [error] 7#7: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.1:53
   [error] 7#7: *15 upstream sent no valid HTTP/1.0 header while reading response header from upstream, client: 82.231.222.221, server: docker.domain.com, request: "GET /v2/ HTTP/2.0", upstream: "http://172.17.0.64:5000/v2/", host: "docker.domain.com"


So maybe, because log is irrelevant, it could be a problem with nginx using ssl http2 and registry responding in http1 ?

Why does it says Connection refused ? I have just removed the password. 

Please help !

**Comment by benhutchins** [comment]
It'd be helpful if you explained what the problem actually was. I'm seeing nginx responding with the same type of error messages:

```
*3 upstream sent no valid HTTP/1.0 header while reading response header from upstream, client: 172.31.16.136, server: docker-registry.internal, request: "GET /v2/ HTTP/1.1", upstream: "http://127.0.0.1:5000/v2/", host: "docker-registry.internal"
```

I believe this is because my registry's server is attempting to handle a TLS handshake, while Nginx is expecting a simple HTTP response. I can't seem to just disable TLS/SSL in the registry (I can't find any documentation about that) and so far I can't any a solution.

**Comment by dmp42** [comment]
@benhutchins did you try to follow the doc step by step?

Specifically https://github.com/docker/distribution/blob/master/docs/deploying.md

**Comment by stevvooe** [comment]
@benhutchins You got it right. The issue with the original configuration is that both nginx and the registry are configured for TLS. Unless you really need nginx, I'd recommend not running it all for most registry deployments.

**Comment by benhutchins** [comment]
@stevvooe In my case I've deployed a docker registry within a VPN network requiring zero authentication at this time, there is a proxy to expose to the public which adds LDAP based authentication. I eventually go this working, by having to have two separate Nginx upstream passthroughs. I needed one inside my VPN to enable TLS and one outside that adds TLS, then internally the docker registry has TLS disabled (which you can do if you override the `config.yml`). I managed to get it working, I'll likely eventually add authentication to the internal VPN as well but currently it doesn't seem `docker/distribution` really handles user namespaces or protected images yet so not much benefit yet.
