### ISSUE TITLE
add cleanup feature

### ISSUE THREAD

**Issue by gesellix** [docker/distribution#106]
Do you have plans to add a feature or an extension point to support image cleanup? Several issues had been discussed for the v1 registry as seen at https://github.com/docker/docker-registry/labels/delete.

I also stumbled upon https://github.com/docker/docker-registry/pull/606 which mentiones such a feature, but without details on your roadmap.

How could someone like me help adding the feature?

**Comment by dmp42** [comment]
TLDR: yes :-)

About details / helping on this, I'll defer to @stevvooe to advise

**Comment by stevvooe** [comment]
@gesellix There are several properties of v2 that address image deletion problems in v1:

1. For v2, deletion is specified in the registry protocol. Complaint implementations should allow deletion of "blobs" and "manifests".

2. In v1, if an image with a given id was incorrectly pushed (corrupted or disconnected), that id would be forever "reserved" by the registry. One could not overwrite that content with the intended image. In v2, layers are stored by content address and verified by the registry, removing the possibility of this situation.

3. Deletes of an image were shallow. This is to prevent the need for complex reference management. We have plans for v2 to manage these references (per the latest backend layout) but are still working on a proposal to make this work.

Note we are working towards #46, which has a large affect on image deletion. Reading the history and references in that ticket will likely fill you in on our direction. Once that is fully implemented, we will start adding support for a full image deletion model that meets the above requirements.

It would also be great if you could clarify exactly what features you are looking for in a deletion model.

I'll consider this ticket closed when we have a created an issue covering the full feature assigned to a milestone.

cc @ncdc

**Comment by gesellix** [comment]
@stevvooe Thanks for the overview.

A quite simple use case for us would affect the long term maintenance of a registry: we're running a private registry to hold private images, which we don't want to publish to an external host. These images don't necessarily need to be available for more than half a year, so we'd like to delete older/unused images to safe disc space.

The current registry api only supports deletion of image tags ("manifests"?), which doesn't have any effect on the actual image layers (now called "blobs"?). It obviously would also be important for us to delete parent images, when they aren't referenced by other images anymore. More or less, we'd like the registry to behave like the local docker storage when the `docker rmi` command is executed.

Consider the following situation with the given image layers from parent to child level:

1. public image "Ubuntu:14.04"
2. private base image "application-base:123" (parent is ubuntu:14.04)
3. private app image "application:11" (parent is application-base:123)
4. private app image "application:47" (parent is application-base:123)
5. private app image "another-image:42" (parent is application:11)

When I perform `DELETE private.registry:5000/another-image:42` I'd expect:

1. the tag "another-image:42" to be removed
2. the layer 5. to be removed
3. all non-tagged intermediate layers between 3. (exclusive) and 5. to be removed

Does that make sense?

**Comment by stevvooe** [comment]
@gesellix Thank you for the description of your use case. This does make sense. This is behavior we have planned and falls under item 3, described in my comment above. It may work slightly differently than described but the result will be what you require.

**Comment by aidanhs** [comment]
So is this feature currently 'wanted but unplanned'?

**Comment by stevvooe** [comment]
@aidanhs Yes, but we are looking for the right approach. The main blocker comes from the complexity of reference counting on top of an eventually consistent storage system. We need to consider whether it is worth facing that complexity or to adopt a hybrid storage model, where references are stored consistently.

**Comment by sam0737** [comment]
I want to add my user story here--

On top of what gesellix said in Jan, here is how I am using the registry. 
* I run my registry locally, on local file system (glusterfs for redundancy to be exact).
* I use it for CI - git push will trigger jenkins to build a docker image and run build-verification test, and push the image to my private registry for QA team or for deployment.  So there will be quite a few images generated everyday, and a lot of it would not be useful and could be discard in a few month or so.  

*So my use case is:* reclaim disk space by deleting the images I don't need.

A few notable non-requirement for this use case, if it means easier to implement:
* the DELETE isn't required to remove the the blob in realtime. It could just remove the link/reference first, then rely on another garbage-collection script to reclaim the disk space.
* The GC script could be scheduled to run daily or even weekly, and the GC script could take minutes to run on a registry holding 1000 images for example.

**Comment by stevvooe** [comment]
@sam0737 Thank you for outlining your particular use case. We are actively addressing this issue but it requires a careful implementation.

Please see #461 and #462 for current status. Soft-deletes (not your use case) will go into 2.1. Check out the discussion on deletes in https://github.com/docker/distribution/issues/422#issuecomment-95745774 to understand why GC isn't as simple as one may think. A consistent view is required to do proper GC.

For your use, a simple script, specific to gluster, may be sufficient if this is causing you problems now.

I'm closing this in favor of the newer, outstanding road mapped issues.

**Comment by dmp42** [comment]
This is roadmapped - closing in favor of the tickets @stevvooe linked.
