### ISSUE TITLE
docker 1.8.2 client cannot pull images from v2 registry

### ISSUE THREAD

**Issue by sehyoc** [docker/distribution#1069]
the logs are in: https://github.com/docker/docker/issues/15759

This prevents us from moving to latest version of docker

**Comment by RichardScothern** [comment]
It will be difficult to debug this in two different issues in two different github repositories.  

Post your docker **daemon** logs (running in debug mode) when the fallback from v2 to v1 happens in https://github.com/docker/docker/issues/15759. 

I'm going to close this issue so we have the context all in once place.
