### ISSUE TITLE
Notifications and tags

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#1071]
Consumers of notification calls currently get the digest of what is pushed, which is a good thing (see discussions on data model).

Although, if one wants to build a UI consuming these notifications and show user-meaningful information, they likely want to display tag information.

It's understood that the tag is not a stable information, and that a given tag might change before the notification is consumed, but from a usability standpoint it would make sense to get it as a complementary (to the digest) piece of information when users are pushing/pulling by tag.

How feasible would that be?

If not feasible right now (eg: before we have first-class citizens tags), what are the alternatives for consumers to bubble up tag information? 

@RichardScothern @aaronlehmann wdyt?

**Comment by aaronlehmann** [comment]
I think it's feasible and I don't have any problem with including the tag.

@stevvooe, I seem to remember that you prefer not to include the tag in these notifications. Any thoughts?

**Comment by mssola** [comment]
This is related to the issue #966, which I submitted a month ago. There are already some ideas there :)

**Comment by stevvooe** [comment]
Right now, there is a manifest notification sent out when a manifest is pushed. We don't enforce the idea that a manifest has a tag and the user must fetch the manifest to get information about this. When tags become first-class, we can have a notification for tags, and then we don't have cruft in the notification API.

I would okay with adding the tag if this could not be built, but really, only a separate http request has to be issued. Nothing is prevented from the current behavior.

Optionally, we can a request URL to the `RequestRecord` and receivers can parse that to see if the pull was by tag or by digest.

**Comment by RichardScothern** [comment]
closed by #1522
