### ISSUE TITLE
S3 storage driver access from a private subnet

### ISSUE THREAD

**Issue by vbichov** [docker/distribution#1073]
This is a request for documentation enhancement for the S3 storage driver.

When running Distribution 2.1.1 inside an Amazon VPC, I came across an issue where the Registry acts in an unexpected way: It does NOT return a layer. Rather, It redirects the Docker client to the S3 bucket.

This may be a good idea actually, except that if your subnet is private it can't access S3 by default.
This can be resolved by defining a VPC S3 endpoint.
You would have no idea that you need to define it because this behavior is completely undocumented.  (as far as I could find)

It might also be nice if the Docker client would return a proper error message instead of the confusing and completely unrelated messages it actually returns - but that is an issue for the Docker repo...

**Comment by RichardScothern** [comment]
thanks for the input @vbichov 

Is there a way to detect that a registry is running within an AWS VPC?  If so, we could return a more specific error.

Could you make a pull request with this documentation.

**Comment by baldzern4** [comment]
Hi, we are having this issue, too. Even if we add the  `redirect` subsection with `disable: true` some requests are going directly from the docker client to S3. So I think there is also a bug hidden there.
BR

**Comment by vbichov** [comment]
@RichardScothern If the storage back-end is S3 then that would be a good indication.
I'm afraid I can't create a pull request.

**Comment by stevvooe** [comment]
This has already been implemented for this specific use case. If the @baldzern4 configuration suggestion is not working, it is a bug.

@baldzern4 Under what conditions is it not working?

**Comment by baldzern4** [comment]
Hi,
we don't use a S3 endpoint in our VPC configuration. Access to the S3 bucket should only be possible through our docker registry.
 
While looking at the access logs from our S3 bucket I saw that
- All of the REST.HEAD.OBJECT  calls are coming from the docker clients. 
i.e:
REST.HEAD.OBJECT docker/registry/v2/blobs/sha256/a3/a3....

- But all of the REST.PUT.*, REST.POST.* and REST.GET.BUCKET calls are coming from the docker registry. 
i.e:
REST.PUT.OBJECT docker/registry/v2/repositories/numberfour/....
REST.POST.UPLOADS docker/registry/v2/repositories/numberfour/...

I also noticed that 1/3 of the REST.GET.OBJECT calls are originated from the docker clients - all calls are trying to access container blobs.
i.e: 
REST.GET.OBJECT docker/registry/v2/blobs/sha256/81/81../data

How is this possible?

Docker Client:
"docker/1.8.3 go/go1.4.2 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64" -
Docker Registry Version:
v2.1.1

**Comment by stevvooe** [comment]
@baldzern4 What is your registry configuration? Do you have similar logs from the registry during this time?

**Comment by dmp42** [comment]
@baldzern4 can you share your registry config?

Thanks.

**Comment by baldzern4** [comment]
@dmp42 sure:
This is the config for our development registry (running version 2.1.1):
```
version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
    cache:
        layerinfo: redis
    s3:
        accesskey: XXXXXXXXXXXXXXX
        secretkey: YYYYYYYYYYYYYYYY
        region: eu-west-1
        v4auth: true
        bucket: s3-bucket-for-docker-registry
        rootdirectory: /
redirect:
  disable: true
http:
  addr: :5000
  secret: ZZZZZZZZZZZZZZZZZZ
  debug:
      addr: localhost:5001
redis:
  addr: localhost:6379 
```

Redis and docker registry are running inside a container.

**Comment by dmp42** [comment]
@baldzern4 `redirect` should be a subkey of `storage`.

I believe that should fix your issue.

**Comment by baldzern4** [comment]
D'oh! Sometimes you don't see the obvious. Thanks @dmp42

**Comment by baldzern4** [comment]
But now we are running into this error (https://github.com/docker/distribution/pull/1303) while pushing:
```
The push refers to a repository [myprivate-registry.com/mycompany/myimage] (len: 1)
4e9779259e4f: Preparing
4e9779259e4f: Pushing
error parsing content-length: strconv.ParseInt: parsing "": invalid syntax
```
Registry Version: 2.2.1

**Comment by dmp42** [comment]
@RichardScothern ^

@baldzern4 can you try the latest registry 2.3 RC?

**Comment by baldzern4** [comment]
Hi,
we are now running Registry Version: 2.4 

This issue is gone. So
- S3 storage is reachable via private IP.
- #1303 is also fixed 

Issue can be close.
Thanks for the support.  :+1:

**Comment by stevvooe** [comment]
@baldzern4 Great to hear! Thanks!
