### ISSUE TITLE
Possibility to generate httpasswd from env variables

### ISSUE THREAD

**Issue by orimarti** [docker/distribution#1077]
Hi,

for me it would be useful being able to generate auth files (for example in the htpasswd) only giving the username and password and not the file. In my case giving the file it means that I have to create a new image from yours.

**Comment by dmp42** [comment]
You don't have to create a new image: https://github.com/docker/distribution/blob/master/docs/deploying.md#native-basic-auth

Just mount the htpasswd file.

**Comment by orimarti** [comment]
Hi @dmp42 , well, in my case I'm using the image inside a mesos/marathon cluster and I think it's not posible to attach files...

**Comment by dmp42** [comment]
Then mesos/marathan should allow you to do that - or you might want to consider delegated authentication to a token server.
Passing htpassword credentials as environment variables is awkward in that case, and will probably not happen...

**Comment by thaJeztah** [comment]
Looks like this is something that needs to be fixed in mesos; should this issue be closed?

**Comment by stevvooe** [comment]
I doubt we'll ever implement anything remotely close to what is described here. Credentials needs to be shipped with care and environment variables don't allow that. Including in the image may be a solution, but that has its own security problems.
