### ISSUE TITLE
Authenticating proxy with nginx +registry2

### ISSUE THREAD

**Issue by Boran** [docker/distribution#1084]
The doc on https://github.com/docker/distribution/blob/master/docs/nginx.md  seems incomplete to me.
I have created pr #1054 to update the doc so at least the containers starts and the config consistent.

However, I don't yet have a working example, so added this issue to discuss the changes needed.

**Comment by RichardScothern** [comment]
#1054 was carried as #1329 and merged.  If more changes are required, please submit a PR.
