### ISSUE TITLE
docker login failed 

### ISSUE THREAD

**Issue by lioncui** [docker/distribution#1085]
Only login localhost:5000 or 127.0.0.1:5000 successful，exception use addr 192.168.1.100。

**Comment by dmp42** [comment]
Logs?
Error message?

**Comment by hopkings2008** [comment]
which ip address your distribution listens on?
For login, you need to check two things:
1. make sure daemon can communicate with the distribution.
2. make sure daemon can communicate with  the auth server configured in distribution.

**Comment by RichardScothern** [comment]
@lioncui ?
