### ISSUE TITLE
Is distribution proxy aware?

### ISSUE THREAD

**Issue by farmerworking** [docker/distribution#1089]
I want to use distribution as a pull through cache and I have to run it behind a proxy

Is distribution proxy aware? If it is how to configure it use the proxy?

I expect the same behavior which can be find in docker daemon by using http_proxy environment variable

**Comment by hopkings2008** [comment]
distribution uses http protocol, you can use it like http_proxy.
do you mean that you want to make distribution use the traffic through your proxy? if so, just set the http_proxy env variable and start distribution.

**Comment by stevvooe** [comment]
@farmerworking I'm not sure what you mean by "proxy aware", but it should work both through and behind various proxy configurations (as @hopkings2008 said, it should work with `http_proxy`). We have also made an effort to have correct cache headers sets to interact correctly with proxies.

I'd recommend you try out your intended configuration and we can troubleshoot. I am going to close this ticket, for now. If you have a specific issue, we can reopen and troubleshoot from there.

**Comment by lomax** [comment]
> it should work with `http_proxy`

It doesn't work with `http_proxy`, however it works with `HTTP_PROXY/HTTPS_PROXY`. So it's case sensitive.
