### ISSUE TITLE
Token based auth need subdomain information

### ISSUE THREAD

**Issue by farmerworking** [docker/distribution#1090]
I currently run distribution with token based auth. people access this repository use user specific subdomain like:

    project1.registry.xxx.com

this `project1` information is needed in auth server along with distribution but currently I can't get that information in auth server since distribution response looks like that:

    Www-Authenticate: Bearer realm="https://121.201.58.179/auth/index",service="Docker registry",scope="repository:library/hello-world:pull"

there is nothing about the domain or hostname user uses

Currently if you choose to use token based authentication, the only information you can get is from http header `www-authentication`. I think it should be more flexible

for example, I config distribution in following way:

    - REGISTRY_AUTH=token
    - REGISTRY_AUTH_TOKEN_REALM=https://121.201.58.179/auth/index
    - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
    - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service"
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/domain.crt
    - REGISTRY_AUTH_TOKEN_ADDITION:
        - hostname
        - cookie

distribution's response will be:

    Www-Authenticate: Bearer realm="https://121.201.58.179/auth/index",service="Docker registry",scope="repository:library/hello-world:pull", hostname="xxx", cookie="xxxx"

**Comment by djenriquez** [comment]
I'm a little confused. Why do you have hard IP address in your config? If you need it to use a domain, configure the distribution to use a domain.

change ```
- REGISTRY_AUTH_TOKEN_REALM=https://121.201.58.179/auth/index
```
info ```
- REGISTRY_AUTH_TOKEN_REALM=https://project1.registry.xxx.com/auth/index
```

**Comment by farmerworking** [comment]
You are missing the point. It's hard IP address or a domain, It just doesn't matter.

What matters is that right now you can't add additional information like the domain user is using (different user may use different subdomain) or the IP address of user. You just can't. The information a auth server can get is only limited to certain parameters which I think is too limited.

The most attractive property of using a token based authentication strategy is that you can seperate the business logic from registry itself so that it's easier to follow up the open source project. However with such limitation, a standalone auth can't do much.

**Comment by djenriquez** [comment]
I apologize if i'm still missing the point :stuck_out_tongue_closed_eyes: , but what you're saying is different users would be accessing the same registry using different subdomains?

You have an image `myapp`. User A wants to pull that image so they run `$ docker pull project1.registry.xxx.com/myapp`.

User B also wants to pull that image, but they're in a different project in a different subdomain so they run `$ docker pull project2.registry.xxx.com/myapp`

Is this the scenario you're needing handled? If not, could you provide an example scenario? :grin:

**Comment by farmerworking** [comment]
Yes, It's almost like that and you can see in that scenario the `subdomain` information like `project1` or `project2` can't be exposed to auth server, right? In the essence, you can't tell the registry to delivery any dynamic custom data to auth server

**Comment by stevvooe** [comment]
@farmerworking This is a very specific use case. I am not sure we'd have bandwidth to support such a configuration without better understanding the benefit of added complexity for other users.

Is it that you are trying to redirect the user for a different authentication realm based on the hostname of the request? I don't really see the point in this if you have a hard coded IP. If you're using this to transmit the user name, this is probably the wrong approach, as the authentication endpoint already has to accept credentials.

Given this, I'd strongly suggest you seek out a different solution to this problem. I may be misunderstanding your request, but it seems like a square peg is going into a round hole. If seeking another solution is not an option, I'd suggest implementing your own authentication backend that supports this. You can even send us a PR and we'll take a look to see if it makes more sense.

**Comment by djenriquez** [comment]
What about setting multiple registries pointed at the same backend? You can have a registry/authentication server pair for every subdomain you need, and then since they're pointed at the same backend, they'll have the same images.

**Comment by stevvooe** [comment]
@djenriquez What would the configuration look like? Would we route to different authentication systems based on the request `Host`, either through SNI or headers?

**Comment by djenriquez** [comment]
Didn't realize there was a question for me in this issue, but yes @stevvooe, every subdomain would be its own registry stack, but all would point to the same S3 backend. This sounds like the level of abstraction @farmerworking was looking for to begin with.

When I'm playing around with registry settings and configurations, I often do just this, create a new stack and point it at the same S3 backend so that I have images to play with. This allows me to test releases, configuration changes, changes in infrastructure set up, etc without causing problems with our production registry.

**Comment by stevvooe** [comment]
@djenriquez @farmerworking It seems like this use case is sufficiently unique and complex such that writing your own auth provider or having individual stacks for each endpoint will meet the original need.

If we can get a more concrete proposal or description of why this should be more widely available, we may consider revisiting this.
