### ISSUE TITLE
docker registry 2.1.1 does not return the image id for a 'docker tag -r -l'

### ISSUE THREAD

**Issue by GrantStreetGroup** [docker/distribution#1102]
When I query my docker registry with the following command `docker tag -r -l 192.168.98.1:8880/sarnott/centos` I get the following:

```
REPOSITORY                         TAG                 IMAGE ID
192.168.98.1:8880/sarnott/centos   test
```
Why is the image id missing?

**Comment by RichardScothern** [comment]
You are interacting with the docker daemon when you invoke `docker tag`.  This github repository is for the docker registry.  Please ask your question in #docker-dev or https://github.com/docker/docker

**Comment by RichardScothern** [comment]
Furthermore `-t` and `-l` are not valid flags for the docker client.  If you are using a fork of docker you should seek help at the origin of the fork

**Comment by GrantStreetGroup** [comment]
Oh,  we just using the redhat supplied docker RPM for Centos7.
