### ISSUE TITLE
Docker registry REST API V2 not writing GET blob content to local filesystem correctly from java program

### ISSUE THREAD

**Issue by swepnadoss** [docker/distribution#1107]
I'm trying to use Docker Registry HTTP API v2 as per this document https://docs.docker.com/registry/spec/api/#pulling-an-image to pull series of blobs for a given image in Java RESTTemplate service written in maven. However, when i use GET /v2/<name>/blobs/<blobsum> API to retrieve particular blob layer for example, hello-world image with sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 blob

```GET http://localhost:5000/v2/hello-world/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4```

which returns size 32 bytes (with 42Characters) using java RestTemplate. While writing to a local file system, its writing as 42 bytes instead (with 42 characters).

Looking deeper looks like docker registry is storing each blob layers internally in Gzip archive (application/gzip) format however "Content-Encoding" header is not specified in the docker REST response for the above mentioned GET API. The problem is that the local file system that java program writes to is storing as "application/octet-stream" format thus showing as 42 bytes size.

Does anyone have any pointers/suggestion to workaround this issue? Perhaps i may be missing something. Any inputs much appreciated.

Directory of docker registry container where images folder is mounted to the local file system. For example, output for sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 as file type "Gzip archive (application/gzip)"

```[a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4]$ ll data
-rw-r--r--. 1 root root 32 Oct  3 18:15 data
[a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4]$ file data
data: gzip compressed data```

Directory where java program writes output files for example, sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 as file type "Binary (application/octet-stream)"

```[ sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4]$ ll
total 4
-rw-rw-r--. 1 doss doss 42 Oct 17 13:16 data
[sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4]$ file data
data: data```

**Comment by stevvooe** [comment]
@swepnadoss It looks like whatever web framework you're using is trying to be crafty about `Content-Encoding`. For serving blobs, we leave compression up to the content. I'd recommend disabling any content-type handling or automatic compression in the web framework. Without seeing the code, I am not sure if we can provide more help.

I'd recommend reaching out to the mailing list for the web framework you're using to get more help. This isn't really something we can provide help with except to provide direction on the intended response.
