### ISSUE TITLE
How to override middleware cloudfront settings via environment variables?

### ISSUE THREAD

**Issue by z0rc** [docker/distribution#1109]
Documentation at https://github.com/docker/distribution/blob/master/docs/configuration.md#override-specific-configuration-options doesn't explain how to provide options for middleware clause (arrays) https://github.com/docker/distribution/blob/master/docs/configuration.md#example-middleware-configuration

**Comment by RichardScothern** [comment]
For non-trivial overloading of configuration options I don't recommend you use environment variables.  It is technically possible to put some yaml in the environment variable but using a custom config file will be far simpler.
