### ISSUE TITLE
Repository already being pulled by another client. Waiting.

### ISSUE THREAD

**Issue by alexandarp** [docker/distribution#1117]
Hello,

I am currently using the registry for continuous integration. I noticed when multiple builds run at the same time, they output the following message:

```
Repository already being pulled by another client. Waiting.
```

I noticed that the build will hang forever when this message appears. The other builds that are trying to pull images will also hang. Is there a workaround for this?

Thanks,
Alex

**Comment by aaronlehmann** [comment]
Which Docker version are you using? Some versions had problems with concurrent pulls, but they should be fixed in 1.9.0-rc1.

**Comment by alexandarp** [comment]
Thanks for getting back to me. I am using docker version 1.8.1.

**Comment by aaronlehmann** [comment]
Could you please try Docker 1.8.3 or Docker 1.9.0-rc1? I expect either will solve this problem.

**Comment by alexandarp** [comment]
Sure, no problem. I will report my results tomorrow. Thanks again.

**Comment by alexandarp** [comment]
Currently testing on Docker 1.8.3, I will let you know if I come across the same issue.

**Comment by stevvooe** [comment]
This looks like a docker/docker issue. Could we please move it over there?

**Comment by alexandarp** [comment]
Upgrading to 1.8.3 solved the issue. Thanks @aaronlehmann.
