### ISSUE TITLE
mirror storage

### ISSUE THREAD

**Issue by jiashiwen** [docker/distribution#1126]
When registry2 as mirror proxy,where the layers stored in local.And How to check wether the mirror woring.I map volume /root/registry/data:/var/lib/registry ,but there is nothing.

**Comment by RichardScothern** [comment]
@jiashiwen : if you setup according to [this](https://github.com/docker/distribution/blob/master/docs/mirror.md)

Aside from seeing the content locally, the registry logs will indicate activity when you `docker pull`

**Comment by jiashiwen** [comment]
did the logs like this：
registry_1 | time="2015-10-27T02:59:00Z" level=info msg="Registry configured as a proxy cache to https://registry-1.docker.io" instance.id=a7a45a16-d0c0-4057-92c1-bd17aeaef16c version=v2.1.1 
registry_1 | time="2015-10-27T02:59:00Z" level=info msg="listening on [::]:5000" instance.id=a7a45a16-d0c0-4057-92c1-bd17aeaef16c version=v2.1.1 
nginx_1    | 10.207.25.37 - - [27/Oct/2015:03:01:05 +0000] "GET //v2/ HTTP/1.1" 401 194 "-" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/3.19.0-28-generic os/linux arch/amd64" "-"
nginx_1    | 10.207.25.37 - - [27/Oct/2015:03:01:05 +0000] "GET /v2/library/maven/manifests/latest HTTP/1.1" 401 194 "-" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/3.19.0-28-generic os/linux arch/amd64" "-"

but，when i restart the container，where the predownload content stored？

**Comment by hopkings2008** [comment]
@jiashiwen , i think you use the filesystem driver, right? so, what is your configuration? if you configure your root dir of filesystem driver at /var/lib/registry, you can check that folder.
Also, to enable mirror, you must change docker daemon option and add '--registry-mirror=your_mirror_registry_addr' when daemon starts, and you can run 'docker pull golang:1.4' to test it.

**Comment by jiashiwen** [comment]
thank you

**Comment by RichardScothern** [comment]
thanks @hopkings2008 .  Closing ..
