### ISSUE TITLE
distribution misbehave when configure cache

### ISSUE THREAD

**Issue by farmerworking** [docker/distribution#1132]
### System environment
docker info

	Containers: 6
	Images: 212
	Storage Driver: aufs
	 Root Dir: /var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 225
	 Dirperm1 Supported: true
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.16.0-41-generic
	Operating System: Ubuntu 14.04.2 LTS
	CPUs: 1
	Total Memory: 993.8 MiB
	Name: i-m903up73
	ID: ZMBV:RGFO:PTY2:Z45B:5N2B:GDFX:NNL2:26ID:XJ4Y:U3K3:642J:2OQV
	Debug mode (server): true
	File Descriptors: 27
	Goroutines: 42
	System Time: 2015-10-16T15:00:18.902790463+08:00
	EventsListeners: 0
	Init SHA1: 70b0cda2ecbf0d9fb1879ed198a66ad09a3dc50c
	Init Path: /usr/lib/docker/dockerinit
	Docker Root Dir: /var/lib/docker
	WARNING: No swap limit support
	
docker version

	Client:
	 Version:      1.8.3
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   f4bf5c7
	 Built:        Mon Oct 12 05:37:18 UTC 2015
	 OS/Arch:      linux/amd64
	
	Server:
	 Version:      1.8.3
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   f4bf5c7
	 Built:        Mon Oct 12 05:37:18 UTC 2015
	 OS/Arch:      linux/amd64
	 
uname -a

	Linux i-m903up73 3.16.0-41-generic #55~14.04.1-Ubuntu SMP Sun Jun 14 18:43:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
	
docker-compose version

	docker-compose version: 1.4.2
	docker-py version: 1.3.1
	CPython version: 2.7.6
	OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
	
### steps to reproduce the bug

1.directory structure:

![image](http://work.image.alimmdn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-10-27%20%E4%B8%8B%E5%8D%8810.41.53.png?t=1445956978937)

2.docker-compose content:

	registry:
	  image: registry:2
	  ports:
	    - "5000:5000"
	  environment:
	    - REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=inmemory
	    - REGISTRY_HTTP_TLS_CERTIFICATE=/ssl/domain.crt
	    - REGISTRY_HTTP_TLS_KEY=/ssl/domain.key
	  volumes:
	    - ./data:/var/lib/registry
	    - .:/ssl

3.docker-compose up -d

4.docker pull hello-world && docker tag hello-world example.com/private/hello-world && docker push example.com/private/hello-world

5.docker rmi -f hello-world

6.docker pull example.com/private/hello-world

7.rm -rf data/docker

8.docker push example.com/private/hello-world

9.docker rmi -f example.com/private/hello-world

10.docker pull example.com/private/hello-world

Everything works fine until step 6. You can run this container, you can push and pull successfully. But after step 7 which you directly remove the data in storage, things start to go wrong. 

![image](http://work.image.alimmdn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-10-27%20%E4%B8%8B%E5%8D%8810.52.59.png?t=1445957612027)

You can see from above picture, after step 7, there is nothing left in data directory. And the push action after that should like step 4 but the registry reports that the image already exists and what's more the data is recovered in storage. 

Although the log information is confusing, we can tolerant that. But when you delete your local image and pull from the registry. Bad happens:

![image](http://work.image.alimmdn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-10-27%20%E4%B8%8B%E5%8D%8810.58.16.png?t=1445957946572)

Immediately after that I check the data directory and the data is indeed exist:

![image](http://work.image.alimmdn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-10-27%20%E4%B8%8B%E5%8D%8810.59.35.png?t=1445958024932)

I have test it several time and it happens every time once you configure the cache option no matter you configure it using inmemory or redis.

And this applies not only to filesystem storage but also OSS storage driver. So I think this will applies to all storage drivers

**Comment by RichardScothern** [comment]
If you remove the registry storage manually, the blob descriptor cache will not be updated which will cause false positives.  What happens when you restart the registry after step 6?

I do not recommend you delete files the registry uses while it is running.

**Comment by farmerworking** [comment]
After deleting files directly, if you restart the registry, you can successfully push and pull again.

Yes, I do know either not using cache or not delete files will avoid this problem and I'm doing it this way now. However the mechanism working behind is certainly broken.

Since the registry will report image already exists and will flush data from cache to storage. It's expected the state machine should be the same as when you have pushed the image successfully in the first place. And it has no reason to make the pull action failed and report 404

**Comment by RichardScothern** [comment]
If the registry is configured as a pull through cache, it will clean up the
filesystem when cache objects expire.  Subsequent pulls will detect this
and refetch the data.

Manually removing files from the filesystem while a running a registry
configured as a cache or otherwise will result in undefined behaviour.

**Comment by farmerworking** [comment]
It's not configured as a pull through cache. The `cache` I'm talking about is `storage->cache-> blobdescriptor` which you can set `inmemory` or `redis`
	
	Use the cache subsection to enable caching of data accessed in the storage backend. Currently, the only available cache provides fast access to layer metadata. This, if configured, uses the blobdescriptor field.
	
according to the documentation [https://github.com/docker/distribution/blob/master/docs/configuration.md#cache](https://github.com/docker/distribution/blob/master/docs/configuration.md#cache)

Apparently `cache` should only speed up pull process and shouldn't change any semantic at all. With or Without `cache` enabled should behave exactly the same.

	The Registry is a stateless
	
according to this documentation [https://docs.docker.com/registry/](https://docs.docker.com/registry/). The registry itself is stateless since data is stored in storage. With this model, once you clean the storage after a successful push there shouldn't be any difference between now and the time before push.

Currently it's true that the result is undefined in this situation. But it's not undefined by design or by choice. It's just simply broken. I can say that.

After talking about walk around (`shouldn't manually delete data in storage`) and current state (`the result is undefined right now`). It's time to focus on where is broken and try fix it!

**Comment by RichardScothern** [comment]
The only fix for this is for the registry to monitor the storage system (using, at best `inotify` and at worse polling) and invalidate the blob descriptor cache.  This will need to be supported in every storage driver.  

The filesystem is abstracted by the registry and should not be tampered with while the registry is running.  This is not broken, it's perfectly OK to define this constraint.

What exactly are you trying to achieve?

**Comment by thaJeztah** [comment]
Should this be closed, or is there still something to be answered?

**Comment by stevvooe** [comment]
@thaJeztah User corrupted data store then complained that cache didn't figure it out. The cache is a part of the data store and it needs to be cleared, as well.

Closing.
