### ISSUE TITLE
httpasswd auth not working if TLS not configured

### ISSUE THREAD

**Issue by orimarti** [docker/distribution#1133]
I have been testing the docker image and I've seen that if I don't configure the tls certificates the authentication through httpasswd is not working. 
In my case I have a proxy that is doing the ssl offloading and it would be good if the authentication worked without configuring tls on the running instance.

**Comment by dmp42** [comment]
Though not a recommended scenario, authentication does work with TLS at another layer (the Docker Hub does exactly that). 

You would still need to properly pass the required headers (X-Forwarded-For and X-Forwarded-Proto), so you maybe want to check that to start.

If you need help, I suggest you join on irc #docker-distribution - or at the very least provide the commands you have been running + configuration + logs.

**Comment by thaJeztah** [comment]
@orimarti have you been able to resolve your issue? If so, could you close this?
