### ISSUE TITLE
Swift as backend with docker registry

### ISSUE THREAD

**Issue by riteshnanda09** [docker/distribution#1154]
Hope it is not a duplicate issue , i tried checking the issues to check if its not duplicate.
I am using Docker version 1.8.3, build f4bf5c7 , i am trying to configure docker registry  iwith swift as a storage backend

My docker config.yml file looks like 

version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  swift:
    username: docker-registry
    password: xxxxxx
    authurl: http://www.example.com:5000/v2
    tenant: docker-registry-v2.0
    tenantid: 9707a0b6786743ffa292cc3f0cbb7865
    insecureskipverify: true
    region: nova
    container: docker-registry-v2.0
    rootdirectory: /swift/object/name/prefix

Then running 

docker run -d -p 5000:5000 --restart=always --name registry-2 -v `pwd`/config.yml:/etc/docker/registry/config.yml registry:2

Running it in debug mode and tailing the logs only show 
docker logs --follow --tail='all' registry-2

http://paste.ubuntu.com/13088275/

Can someone suggest

**Comment by RichardScothern** [comment]
@riteshnanda09 : what exact error are you experiencing?

**Comment by riteshnanda09** [comment]
No errors , it just gives trace

6c6f3 trace.line=123 version=v2.1.1
time="2015-11-03T02:00:59.831949214Z" level=debug msg="swift.List(\"/\")" environment=staging instance.id=3bbb41e1-bcb8-4db2-a811-3ed51e02fb22 service=registry trace.duration=32.437937ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=7aba4a43-3bed-4fc4-b1ba-f8426f1e1901 trace.line=123 version=v2.1.1
time="2015-11-03T02:01:09.81400514Z" level=debug msg="swift.List(\"/\")" environment=staging instance.id=3bbb41e1-bcb8-4db2-a811-3ed51e02fb22 service=registry trace.duration=14.448663ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=40710464-90d5-4e05-95fd-4bb26d76c1d0 trace.line=123 version=v2.1.1
time="2015-11-03T02:01:19.814997289Z" level=debug msg="swift.List(\"/\")" environment=staging instance.id=3bbb41e1-bcb8-4db2-a811-3ed51e02fb22 service=registry trace.duration=15.490087ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=69f7c531-9e8d-415c-ab91-1398b58aeccc trace.line=123 version=v2.1.1
time="2015-11-03T02:01:29.817140245Z" level=debug msg="swift.List(\"/\")" environment=staging instance.id=3bbb41e1-bcb8-4db2-a811-3ed51e02fb22 service=registry trace.duration=17.619116ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=3f44fea8-9a2b-4422-80d3-146975b72015 trace.line=123 version=v2.1.1
time="2015-11-03T02:01:39.817034083Z" level=debug msg="swift.List(\"/\")" environment=staging instance.id=3bbb41e1-bcb8-4db2-a811-3ed51e02fb22 service=registry trace.duration=17.508003ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=666af36b-62ac-4232-a229-401f7efe8388 trace.line=123 version=v2.1.1
time="2015-11-03T02:01:49.816746989Z" level=debug msg="swift.List(\"/\")" environment=staging instance.id=3bbb41e1-bcb8-4db2-a811-3ed51e02fb22 service=registry trace.duration=17.195128ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=08412d2a-5736-44e2-b870-f8de265597da trace.line=123 version=v2.1.1

**Comment by RichardScothern** [comment]
What is the problem you are trying to solve?

**Comment by riteshnanda09** [comment]
i am trying running docker registry with swift as a backend.

**Comment by RichardScothern** [comment]
It seems you have successfully done that.  Why have you submitted a github issue about this?

**Comment by riteshnanda09** [comment]
So if i try to push a image 

docker push 10.24.48.220:5000/ubuntu
The push refers to a repository [10.24.48.220:5000/ubuntu] (len: 1)
Sending image list
Put http://10.24.48.220:5000/v1/repositories/ubuntu/: dial tcp 10.24.48.220:5000: connection refused

**Comment by RichardScothern** [comment]
For some reason, the daemon cannot talk to the registry.  That is why there is nothing in the registry logs and that is why you see `connection refused` from the daemon.  There is something wrong with your setup.

Post the command line you use to start the daemon and the logs it produces.

**Comment by riteshnanda09** [comment]
This is the command i use to run registry container

docker run -d -p 5000:5000 --restart=always --name registry-2 -v `pwd`/config.yml:/etc/docker/registry/config.yml registry:2

it is reading a config.yml file 

version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  swift:
    username: docker-registry
    password: docker-registry
    authurl: https://os-identity.vip.lvs03.paypalc3.com:5443/v2.0
    tenant: docker-registry-v2.0
    tenantid: 9707a0b6786743ffa292cc3f0cbb7865
    insecureskipverify: true
    region: lvs03
    container: docker-registry-v2.0
    rootdirectory: /swift/object/name/prefix



this is /var/log/upstart/docker.log

INFO[0966] POST /v1.20/containers/create?name=registry-2
INFO[0967] POST /v1.20/containers/e068a3a37686f38990b14f32617fbac5b4c9a8e49049f0f4b2901d3c701a8697/start
INFO[0971] GET /v1.20/containers/registry-2/json
INFO[0971] GET /v1.20/containers/registry-2/logs?follow=1&stderr=1&stdout=1&tail=all
INFO[1121] GET /v1.20/containers/registry-2/json
INFO[1121] GET /v1.20/containers/registry-2/logs?follow=1&stderr=1&stdout=1&tail=all
INFO[1258] GET /v1.20/containers/registry-2/json
INFO[1258] GET /v1.20/containers/registry-2/logs?follow=1&stderr=1&stdout=1&tail=all
INFO[1466] GET /v1.20/containers/registry-2/json
INFO[1466] GET /v1.20/containers/registry-2/logs?follow=1&stderr=1&stdout=1&tail=all
INFO[1494] GET /v1.20/containers/registry-2/json
INFO[1494] GET /v1.20/containers/registry-2/logs?follow=1&stderr=1&stdout=1&tail=all
INFO[1549] GET /v1.20/containers/registry-2/json
INFO[1549] GET /v1.20/containers/registry-2/logs?follow=1&stderr=1&stdout=1&tail=all
INFO[1983] GET /v1.20/containers/registry-2/json
INFO[1983] GET /v1.20/containers/registry-2/logs?follow=1&stderr=1&stdout=1&tail=all
INFO[2752] GET /v1.20/containers/registry-2/json
INFO[2752] GET /v1.20/containers/registry-2/logs?follow=1&stderr=1&stdout=1&tail=all
INFO[3053] POST /v1.20/images/create?fromImage=ubuntu%3Alatest
INFO[3093] POST /v1.20/images/ubuntu/tag?repo=10.24.48.220%3A5000%2Fubuntu&tag=
INFO[3140] POST /v1.20/images/10.24.48.220:5000/ubuntu/push?tag=
INFO[3194] GET /v1.20/containers/registry-2/json
INFO[3194] GET /v1.20/containers/registry-2/logs?follow=1&stderr=1&stdout=1&tail=all

**Comment by riteshnanda09** [comment]
i wil close this as i got working , it did'nt work for me through config.yml , but it worked using docker run with environment variables.

docker run -d --name registry -p 5000:5000 -e "REGISTRY_STORAGE=swift" -e "REGISTRY_STORAGE_SWIFT_USERNAME=xxxx" -e "REGISTRY_STORAGE_SWIFT_PASSWORD=xxxx" -e "REGISTRY_STORAGE_SWIFT_AUTHURL=xxxx/v2/tokens" -e "REGISTRY_STORAGE_SWIFT_CONTAINER=xxx" -e "REGISTRY_STORAGE_SWIFT_REGION=xxx" -e "REGISTRY_STORAGE_SWIFT_TENANT=xxxx" -e "REGISTRY_STORAGE_SWIFT_TENANTID=xxx" registry:2
