### ISSUE TITLE
Update version.go to reflect latest version number

### ISSUE THREAD

**Issue by mindscratch** [docker/distribution#1158]
With the release of v2.2.0 it looks like [version.go](https://github.com/docker/distribution/blob/v2.2.0/version/version.go) wasn't updated.

**Comment by mindscratch** [comment]
I was mistaken, looks like during the build some vodoo happens that sets the version correctly. After compiling the binary from the v2.2.0 tag I get this when printing the version:

```
[root@futz distribution]# /goworkspace/bin/registry --version
/goworkspace/bin/registry github.com/docker/distribution v2.2.0
```

**Comment by stevvooe** [comment]
@mindscratch Voodoo [here](https://github.com/docker/distribution/blob/master/Makefile#L14). We set the package value with the linker.
