### ISSUE TITLE
Impossible to set REGISTRY_HTTP_TLS_CLIENTCAS option

### ISSUE THREAD

**Issue by spencerkohan** [docker/distribution#1175]
I'm trying to get a private registry working with a self-signed tls certificate, and I'm unable to set the REGISTRY_HTTP_TLS_CLIENTCAS option.  Based on the documentation, it looks like that configuration option shuold accept an array: 

    http:
      tls:
        clientcas:
          - /path/to/ca.pem
          - /path/to/another/ca.pem

But if my `docker-compose.yml` looks like this:

    environment:
      REGISTRY_HTTP_TLS_CLIENTCAS: 
        - /certs/ca.crt

I get this error message: 

    Service 'registry' configuration key 'environment' 'REGISTRY_HTTP_TLS_CLIENTCAS' contains ['/certs/ca.crt'], which is an invalid type, it should be a string, number, boolean or a null

So since it looks like it requires a string, I tried changing it to this: 

    environment:
      REGISTRY_HTTP_TLS_CLIENTCAS:  /certs/ca.crt

And now I get this error message: 

    registry_1 | configuration error: error parsing /etc/docker/registry/config.yml: yaml: unmarshal errors:
    registry_1 |   line 1: cannot unmarshal !!str `/certs/...` into []string

So it does not seem possible to set this config option.

**Comment by RichardScothern** [comment]
@spencerkohan : I recommend you create a base config.yml file for you configuration and just use environment variables to override single value types.  Otherwise you have to format a yaml string and put that inside the environment variable.

**Comment by thaJeztah** [comment]
@spencerkohan does that help you further? Can this issue be closed?

**Comment by elgeorge2k** [comment]
I had the same problem, I don't understand what you're suggesting. Here I tried using a single line and same problem:

```
docker run --restart=always -p 443:5000 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -e REGISTRY_HTTP_TLS_CLIENTCAS=/certs/domain.ca-bundle -v /path/to/data:/var/lib/registry -v /path/to/certs:/certs registry:2
configuration error: error parsing /etc/docker/registry/config.yml: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `/certs/...` into []string

```

**Comment by BransonGitomeh** [comment]
@elgeorge2k solution worked great

**Comment by walidshaari** [comment]
Thank you, i am using docker-distribution, and it was not clear that clientcas was an array until i came here. 
it worked for me too

**Comment by Jean-Baptiste-Lasselle** [comment]
> I had the same problem, I don't understand what you're suggesting. Here I tried using a single line and same problem:
> 
> ```
> docker run --restart=always -p 443:5000 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -e REGISTRY_HTTP_TLS_CLIENTCAS=/certs/domain.ca-bundle -v /path/to/data:/var/lib/registry -v /path/to/certs:/certs registry:2
> configuration error: error parsing /etc/docker/registry/config.yml: yaml: unmarshal errors:
>   line 1: cannot unmarshal !!str `/certs/...` into []string
> ```
> 
> -- EDIT --
> 
> Just found the solution to my problem:
> 
> ```
> docker run --restart=always -p 443:5000 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -e REGISTRY_HTTP_TLS_CLIENTCAS=' - /certs/domain.ca-bundle' -v /path/to/data:/var/lib/registry -v /path/to/certs:/certs registry:2
> ```

Thank you for that, found zero other mentions of such a case, and am having a good old reverse engineering ahead, to solve some more, but that's learning.

**Comment by walidshaari** [comment]
@Jean-Baptiste-Lasselle yes that is what I meant by an array ```  REGISTRY_HTTP_TLS_CLIENTCAS=' - /certs/domain.ca-bundle' ```

**Comment by Jean-Baptiste-Lasselle** [comment]
> @Jean-Baptiste-Lasselle yes that is what I meant by an array
> 
> ` REGISTRY_HTTP_TLS_CLIENTCAS=' - /certs/domain.ca-bundle'`

exactly in my case, I just minutes ago solved thanks to your indication, and here is the configuration parameter I had to apply your solution to (and it bloody welll worked as well) : 

```yaml
version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: '/var/lib/registry'
  delete:
    enabled: true
auth:
  # silly:
    # realm: silly-realm
    # service: silly-service
```
In my case I'm stil struggling with other issues that seem absolutely unrelated, and stil kind of of the same order...

Just for the record, and the sake of our pairs, I here add my private docker registry `logs`, which proved me the parsing didn't throw any other exception : 

```bash
jibl@poste-devops-typique:~$ cd .pegasus/.awx/provision/docker-registries/ && docker-compose logs -f
Attaching to docker_registry_manager, awx_dock_registry, docker-registries_certbot_1
awx_dock_registry          | time="2019-05-31T01:54:17.273553418Z" level=info msg="debug server listening 0.0.0.0:4999" 
awx_dock_registry          | time="2019-05-31T01:54:17.27860293Z" level=info msg="redis not configured" go.version=go1.11.2 instance.id=422b08cf-55a2-4818-9dc6-c5d4566f7700 service=registry version=v2.7.1 
awx_dock_registry          | time="2019-05-31T01:54:17.279226158Z" level=info msg="Starting upload purge in 47m0s" go.version=go1.11.2 instance.id=422b08cf-55a2-4818-9dc6-c5d4566f7700 service=registry version=v2.7.1 
awx_dock_registry          | time="2019-05-31T01:54:17.304073968Z" level=info msg="listening on [::]:5000, tls" go.version=go1.11.2 instance.id=422b08cf-55a2-4818-9dc6-c5d4566f7700 service=registry version=v2.7.1 
awx_dock_registry          | time="2019-05-31T01:54:21.035098821Z" level=info msg="debug server listening 0.0.0.0:4999" 
awx_dock_registry          | time="2019-05-31T01:54:21.035206052Z" level=info msg="redis not configured" go.version=go1.11.2 instance.id=b04c04a2-f45c-4592-916a-48d53e1f8848 service=registry version=v2.7.1 
awx_dock_registry          | time="2019-05-31T01:54:21.035224992Z" level=info msg="Starting upload purge in 53m0s" go.version=go1.11.2 instance.id=b04c04a2-f45c-4592-916a-48d53e1f8848 service=registry version=v2.7.1 
awx_dock_registry          | time="2019-05-31T01:54:21.054949249Z" level=info msg="listening on [::]:5000, tls" go.version=go1.11.2 instance.id=b04c04a2-f45c-4592-916a-48d53e1f8848 service=registry version=v2.7.1 
docker_registry_manager    | time="2019-05-31T01:54:17Z" level=info msg="Using registries located in /app with file name registries" file=allregistries.go line=161 source=app
docker_registry_manager    | time="2019-05-31T01:54:17Z" level=error msg="Failed to connect to validated registry: Get http://registry:5000/v2/: dial tcp: lookup registry on 127.0.0.11:53: no such host" file=registry.go line=297 source=app
docker_registry_manager    | time="2019-05-31T01:54:17Z" level=fatal msg="Failed to create registry (http://registry): Get http://registry:5000/v2/: dial tcp: lookup registry on 127.0.0.11:53: no such host" file=allregistries.go line=198 source=app
docker_registry_manager    | time="2019-05-31T01:54:20Z" level=info msg="Using registries located in /app with file name registries" file=allregistries.go line=161 source=app
docker_registry_manager    | time="2019-05-31T01:54:20Z" level=error msg="Failed to connect to validated registry: Get http://registry:5000/v2/: dial tcp: lookup registry on 127.0.0.11:53: no such host" file=registry.go line=297 source=app
docker_registry_manager    | time="2019-05-31T01:54:20Z" level=fatal msg="Failed to create registry (http://registry): Get http://registry:5000/v2/: dial tcp: lookup registry on 127.0.0.11:53: no such host" file=allregistries.go line=198 source=app
certbot_1                  | 
certbot_1                  | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1                  | 
certbot_1                  | No renewals were attempted.
certbot_1                  | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1                  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1                  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1                  | 
certbot_1                  | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1                  | 
certbot_1                  | No renewals were attempted.
certbot_1                  | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
docker_registry_manager exited with code 1
awx_dock_registry          | 172.18.0.1 - - [31/May/2019:01:57:06 +0000] "GET /v2/ HTTP/1.1" 404 19 "" "docker/18.09.6 go/go1.10.8 git-commit/481bc77 kernel/4.9.0-8-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.6 \\(linux\\))"
awx_dock_registry          | 172.18.0.1 - - [31/May/2019:01:57:06 +0000] "HEAD /v2/imaginaire.io/produit/blobs/sha256:5d20c808ce198565ff70b3ed23a991dd49afac45dece63474b27ce6ed036adc6 HTTP/1.1" 404 19 "" "docker/18.09.6 go/go1.10.8 git-commit/481bc77 kernel/4.9.0-8-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.6 \\(linux\\))"
awx_dock_registry          | 172.18.0.1 - - [31/May/2019:01:57:06 +0000] "POST /v2/imaginaire.io/produit/blobs/uploads/ HTTP/1.1" 404 19 "" "docker/18.09.6 go/go1.10.8 git-commit/481bc77 kernel/4.9.0-8-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.6 \\(linux\\))"

```

**Comment by richp10** [comment]
Alternative solution: 

REGISTRY_HTTP_TLS_CLIENTCAS_0=/certs/fullchain.pem

**Comment by itsjavi** [comment]
In my case it was because I was using quotes (silly me)

```
    environment:
      - REGISTRY_HTTP_TLS_CLIENTCAS='[/certs/ca.crt]'
```

this worked:

```
    environment:
      - REGISTRY_HTTP_TLS_CLIENTCAS=[/certs/ca.crt]
```
