### ISSUE TITLE
Cannot push to HA registry with NFS storage

### ISSUE THREAD

**Issue by miminar** [docker/distribution#1176]
We're encountering issues in OpenShift with multiple replicas using shared NFS volume. If the load balancer uses round robin algorithm while choosing registry replica, there's almost 100% probability the push will fail.

It can be easily reproduced outside of OpenShift with current `docker.io/registry:2` image. NFS storage is exported like this:

    /var/shared 192.168.122.0/24(rw,sync,all_squash)

It's mounted to 2 nodes with default options:

    192.168.122.1:/var/shared on /mnt/shared type nfs4 (rw,relatime,vers=4.0,rsize=8192,wsize=8192,namlen=255,hard,proto=tcp,port=0,timeo=14,retrans=2,sec=sys,clientaddr=192.168.122.101,local_lock=none,addr=192.168.122.1)

Each node runs docker registry in a container with command:

    docker run --rm --name upstream-registry -e REGISTRY_LOG_LEVEL=debug -e REGISTRY_HTTP_SECRET=asecret -v /mnt/shared/upstream-registry:/var/lib/registry:rw -p 5001:5000 docker.io/registry:2

Push either fails like this:

    docker -D push 192.168.122.101:5010/miminar/hello-world
    The push refers to a repository [192.168.122.101:5010/miminar/hello-world] (len: 1)
    975b84d108f1: Pushing 1.024 kB
    digest invalid: provided digest did not match uploaded content

Or like this:

    docker push 192.168.122.101:5010/miminar/hello-world
    The push refers to a repository [192.168.122.101:5010/miminar/hello-world] (len: 1)
    975b84d108f1: Pushing 1.024 kB
    blob upload unknown

I can successfully reproduce with docker-1.8.2. With 1.7.1 there's non-zero probability of successful push.

If, however, we switch to `source` balance algorithm, the push succeeds with high probability.

Here's a config file of HAProxy load balancer (running on one of the nodes) that switches between them:

    global
        log                     /dev/log local0 debug

        chroot      /var/lib/haproxy
        pidfile     /var/run/haproxy.pid
        maxconn     4000
        user        haproxy
        group       haproxy
        daemon
        stats socket /var/lib/haproxy/stats

    defaults
        mode                    http
        option                  httplog
        option                  dontlognull
        option                  http-server-close
        option                  forwardfor       except 127.0.0.0/8
        option                  redispatch
        retries                 3
        timeout http-request    120s
        timeout queue           1m
        timeout connect         10s
        timeout client          1m
        timeout server          1m
        timeout http-keep-alive 10s
        timeout check           10s
        maxconn                 3000

    frontend  main *:5010
        default_backend             app

    backend app
        balance roundrobin
        server  node1 127.0.0.1:5001       check
        server  node2 192.168.122.102:5001 check

Log of the first replica: http://fpaste.org/288790/raw/

Log of the second replica: http://fpaste.org/288791/raw/

Have you encountered these issues? Are you working on a solution? Can we help?

We have a patch for older version of distribution which brings successful rate close to 100%. I'll rework it on current master and reference it here so you can take a look.

**Comment by miminar** [comment]
There are nfs options that make the push work like a charm: `noac` and `actimeo=0`. `noac` is a no-go because a push takes forever (90 seconds with 390 MB image).
With `actimeo=0` it's much better. The same image is pushed within 12 seconds.

Here are complete mount options for `noac`:

    192.168.122.1:/var/shared on /mnt/shared type nfs4 (rw,relatime,sync,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,acregmin=0,acregmax=0,acdirmin=0,acdirmax=0,hard,noac,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.122.102,local_lock=none,addr=192.168.122.1)

And for `actimeo=0`:

    192.168.122.1:/var/shared on /mnt/shared type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,acregmin=0,acregmax=0,acdirmin=0,acdirmax=0,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.122.102,local_lock=none,addr=192.168.122.1)

**Comment by stevvooe** [comment]
@miminar Looks like NFS isn't flushing the writes from one instance to another. Read-after-write consistency is a requirement of the backend.

Let's take a peak at the registry logs. Also, please make sure you are running 2.2.

**Comment by miminar** [comment]
@stevvooe Attached logs show `version=v2.2.0`.

Also referencing [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1277356).

**Comment by stevvooe** [comment]
@miminar You are on the write track for troubleshooting this issue. The error message is coming at the point where the registry is trying to verify data downloaded to the temporary location. I'd recommend instrumenting that area carefully to see if you can get it to report the _hash of data received_, to confirm that is differs. You may also try reading it back in that same request (expensive) to see what the state is at the time of that read.

Is there some sort of fsync call we could add?

**Comment by miminar** [comment]
@stevvooe I don't think it will solve the issue. I can easily preproduce with `sync` mount option which, according to `NFS(5)` manpage, means:

> If the sync option is specified on a mount point, any system call that
> writes data to files on that mount point causes that data to be
> flushed to the server before the system call returns control to user
> space. This provides greater data cache coherence among clients, but at
> a significant performance cost.

`close()` actually does the same as `fsync()`:

> If neither sync nor async is specified (or if the async option is specified),
> the NFS client delays sending application writes to the server until any of
> these events occur:
>   
>    Memory pressure forces reclamation of system memory resources.
>
>    An application flushes file data explicitly with sync(2), msync(2), or fsync(3).
>
>    An application closes a file with close(2).
>
>    The file is locked/unlocked via fcntl(2).

Presence of the data on the server doesn't ensure their availability to other NFS clients if they cache.
I don't think this has a simple solution apart from:

- tuning client NFS mount options
- tell the load balancer to serve the same client with the same replica
- making retries for read/stat operations

**Comment by stevvooe** [comment]
@miminar I agree with your analysis.

Are you able to find an NFS configuration where this doesn't happen?

**Comment by sergeyfd** [comment]
We are getting the same problem with NetApp NFS Storage. One possible solution for that would be caching IP address for the repo on the client side and using it for pushing all blobs  from the same repo.

**Comment by miminar** [comment]
We started recommending using export lines:

```
/<example_fs> *(rw,root_squash,no_wdelay)
```

And running load balancer with `source` balance algorithm as described above.

This makes registry in ha setup behave well on nfs storage for us.

**Comment by miminar** [comment]
Closing the issue.

**Comment by stevvooe** [comment]
To be clear, the registry requires read-after-write consistency on the backend.

**Comment by klebediev** [comment]
Hi from 2020!
We achieved stable results in cluster mode with `lookupcache=positive` NFS mount option without session stickiness. Performance overhead is negligible.
