### ISSUE TITLE
Registry with auth: auth issue at push

### ISSUE THREAD

**Issue by osallou** [docker/distribution#1177]
Hi,
I have implemented a token management server talking with registry v2 and it works fine. I can push/pull from remote servers while dealing with user access rights and authentication.
I face however an issue doing a push on 1 host (the same where is registry).
I can do a *docker login*. However, at *push*, it fails (with no error).

    [ ~]# docker   push docker-registry.genouest.org/osallou/blast
    The push refers to a repository [docker-registry.genouest.org/osallou/blast] (len: 1)
    3acbd84b58f1: Pushing 1.024 kB
    unauthorized: authentication required

The unauthorized suggest that an authorisation is requested from my token server. I can see the request in the log of token server and it is correctly managed. The same push from an other,remote, server works fine (with same user).

Here is a wireshark capture. The token request answers with a 200OK, then a post on registry is done, which answers a 202 Accepted. However, a new 401 Unauthorized error appears after that (and ends the push).

![screenshot from 2015-11-10 15 58 45](https://cloud.githubusercontent.com/assets/1024098/11065689/16360192-87c5-11e5-8c4e-68a143dc2c57.png)

The only difference is my Docker client version, on this host, is docker v1.9. Others are v1.7.

Any idea on what is going on ? The registry is running in a container

registry logs are available here: https://gist.github.com/osallou/d0dfe3ca8e5db68676c8

**Comment by osallou** [comment]
Additional info:

The PATCH message sent does not contain any authorization header:

    PATCH /v2/osallou/blast/blobs/uploads/3dcec9c4-4198-4ea0-9a95-4b48abda3bb2?_state=UyQg_fLbBfMDPU1hrKZrpoMMv8BPZIry6aUUt0Aa3Lt7Ik5hbWUiOiJvc2FsbG91L2JsYXN0IiwiVVVJRCI6IjNkY2VjOWM0LTQxOTgtNGVhMC05YTk1LTRiNDhhYmRhM2JiMiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNS0xMS0xMFQxNDo1MToxMy44NzM0NjI5NzdaIn0%3D HTTP/1.1
    Host: docker-registry.genouest.org
    User-Agent: docker/1.9.0 go/go1.4.2 git-commit/76d6bc9 kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64
    Accept-Encoding: gzip
    X-Forwarded-For: 192.168.1.2
    X-Forwarded-Host: docker-registry.genouest.org
    X-Forwarded-Server: docker-registry.genouest.org
   Connection: Keep-Alive
   Content-Length: 32

This explains the unauthorized issue, but why client does not sent the authorization error, a bug in client?

I use Docker version 1.9.0, build 76d6bc9

**Comment by stevvooe** [comment]
@dmcgowan Any ideas here?

**Comment by dmcgowan** [comment]
This really does not look like a bug on the client since PATCH is not treated any differently. However the proxy may be treating it differently. Where are you seeing the PATCH headers and is it possible to see it from the proxy. The Headers you sent appear to be post proxy and not necessarily what is leaving the client. I have never seen an issue where the authorization is attached to previous requests then does not send for subsequent requests, therefore I would like to take a look at the capture directly from the client.  We can figure this out :)

**Comment by osallou** [comment]
As requests go through https, i cannot get http info directly on client output, only after the https/http proxy. I am using Apache as proxy.
A push from my computer, going through the same proxy works, but with client 1.7, not using patch if i am correct.

I saw the patch headers in the wireshark capture, it is the request just before the last 401 error.

**Comment by osallou** [comment]
For info, I could reproduce the issue at home in a vagrant box with v1.9 client. So issue seems really related to the PATCH message. Could be a https/http proxy issue, could I force client to use http instead of https to be able to decode messages sent by client?

**Comment by osallou** [comment]
I have tried to capture messages sent by client, and just saw a strange thing. While I caznnot decode the HTTPS messages, I can see a flow of message to port 443. However, at the end, I see the PATCH message sent to port 80 instead of 443. 

See capture screenshot here. The highlighted message is the PATCH message (previous are HTTPS ones), followed by the 401 Unauthrorized. We can see the message is sent to the port 80, leaving the HTTPS transaction.

![capture](https://cloud.githubusercontent.com/assets/1024098/11087182/6bc0ae58-8858-11e5-8a7f-b62e8446302e.PNG)

**Comment by osallou** [comment]
Moving forward.... The *202 Accepted* message following *POST /v2/...../blobs/uploads/* contains in its headers a Location field:

    Location: http://docker-registry.genouest.org/v2/.../uploads/xxxx

The location header returned by the registry is in http instead of https. A registry v2 bug / config issue ?

**Comment by osallou** [comment]
Gotcha !! The registry requires, when going through a proxy, to set the X-Forwarded-Proto header in the requests. Others X-Forwarded-xx headers are automatically set by proxy, not the -Proto.

The file *https://github.com/docker/distribution/blob/master/registry/api/v2/urls.go* looks at this header to decide  if http or https scheme is to be used. In most messages we do not care as we handle relative urls. For blob uploads, a complete url is set in Location header of the response.

Adding the X-Forwarded-Proto in the proxy configuration fix the issue. This may however require a documentation hint....  ;-) I let you decide to close the bug or not as this could be managed as a documentation bug.

**Comment by dmcgowan** [comment]
Glad you figured it out! Wireshark is great but I like using http://www.charlesproxy.com/ (there are some free alternatives as well) which can MITM your HTTPS connection to give you better visibility over what is sent over the wire directly from the Docker daemon. Would treat updates to the docs separately, feel free to open up a PR or issue requesting such a change.

**Comment by ZeissS** [comment]
For the record, we ran into the same issue with our proxied registry. Maybe a warning in the docker daemon might be possible?

**Comment by tempico** [comment]
Same problem. With paid trusted registry.

The push refers to a repository [registry.****.***/user/repo] (len: 1)
4dcb8199317b: Image already exists 
76d245af546f: Image already exists 
df94a3fe4639: Image already exists 
d6120df089ae: Image already exists 
ed274cec0091: Image already exists 
4d7743f8fd11: Image already exists 
45cf80647aba: Pushing [==================================================>] 296.6 MB
unauthorized: authentication required

**Comment by dmp42** [comment]
@tempico if you are using DTR, please contact the support.

Furthermore, use of X-Forwarded-Proto is documented and I don't think there is a reason for you to set it / disable it in DTR.

Anyhow, like I said, please reach out to the support.

**Comment by tempico** [comment]
@dmp42 
OK, thanks!
DTR is installed at dedicated machine, without proxy.

**Comment by reasonerjt** [comment]
@osallou in your previous comment, "adding the X-Forwarded-Proto in the proxy configuration fixes the issue."  So does it mean the PATCH request to be triggered against https url not http?

But if that's the case, IMHO, this maybe still questionable:
1)Why the "Location" header in the response of POST is handled differently?
2)If there's a scheme switch from https to http, is it correct to drop the token?

**Comment by osallou** [comment]
@reasonerjt 
In my case, I had the Registry and my server acting for authentication behind a web proxy, accessed via https. Proxy forwards requests to both in http on private network. I had to set the X-Forwarded-Proto scheme in proxy configuration because I trigger the registry in https (in front of the proxy) then forward the request to the registry in http. As original info about used protocol is lost when going though the proxy, we had to set the used scheme. The X-Forwarded-Proto header is detected by the registry and update requests accordingly for some specific API use.

Regarding 1) Location, well, this should be asked to developpers  ;-)
Regarding 2), why would you drop the token ?

**Comment by stevvooe** [comment]
> Regarding 1) Location, well, this should be asked to developpers ;-)

We made the decision to use absolute urls in the location header to make client implementation easier for http libraries that don't handle redirects. To make this work correctly in most cases, we have some detection using various forwarding headers. This also allows one have schemes where registry can produce breakout redirects to route large streams around load balancers. Unfortunately, the token management scheme in docker isn't up to the task to leverage this yet.

This affects the `PATCH` because that is the most common redirect that happens.

I do recall some discussion in adding a configuration option that would just restrict these to relative redirects. There is no reason that shouldn't be backwards compatible.

> Regarding 2), why would you drop the token ?

You _must_ drop the token when going to an insecure scheme or switching hosts. Otherwise, you risk leaking authentication tokens.
