### ISSUE TITLE
Pushes repeated failures on 2.2.0 release

### ISSUE THREAD

**Issue by markriggins** [docker/distribution#1178]
Our private registry running on `registry:2` started failing last week after running smoothly for over a month.   Rolling back to 2.1.1 fixed our issues

# Symptoms:

First push attempt:

$ docker push docker.trove.com/trove-web-static-builder:0.0.13-fd440d3

    The push refers to a repository [docker.trove.com/trove-web-static-builder] (len: 1)
    973c8197e30a: Image push failed 
    Error pushing to registry: Server error: 404 trying to push trove-web-static-builder blob -     sha256:307f3f856bf1a6bd5b833a4128c5b206264616a5c92c501e51b2c89fd552f67

The 2nd attempt gets further but still fails

    $ docker push docker.trove.com/trove-web-static-builder:0.0.13-fd440d3
    The push refers to a repository [docker.trove.com/trove-web-static-builder] (len: 1)
    973c8197e30a: Image already exists 
    3cd0bb1f03df: Image push failed 
    Error pushing to registry: Server error: 404 trying to push trove-web-static-builder blob -  sha256:644399d0b39b8bab571c43e8d4f053be5ff2c01d64d0dc45b28ec6da157bcabe

This fails on at all of our clients across different OS's and docker releases.

OS X -- on Docker version 1.9.0, build 76d6bc9
CentOS -- Linux ip-172-18-20-246 3.10.53-56.140.amzn1.x86_64 #1 SMP Thu Aug 14 22:00:02 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Docker version 1.7.1, build 786b29d/1.7.1

**Comment by RichardScothern** [comment]
Please post your configuration details (including middleboxes) the registry logs and the daemon logs (in verbose mode) around the time of the failure.

**Comment by RichardScothern** [comment]
ping @markriggins

**Comment by markriggins** [comment]
I'm sorry. But the logs are gone now.  Rolling back fixed the issue for us then.  And now all these servers have been decomissioned.

**Comment by thaJeztah** [comment]
@markriggins perhaps this issue should be closed then, because we no longer have a way to reproduce or investigate

**Comment by markriggins** [comment]
Agreed.
