### ISSUE TITLE
Unable to start registry - "Ignoring unrecognized environment variable REGISTRY_SEARCH_BACKEND"

### ISSUE THREAD

**Issue by GittyHup** [docker/distribution#1180]
I am starting registry with docker-compose, and the following docker-compose.yml below. It does not start because of error below. First my config file:

	registry:
	  restart: always
	  image: registry:2
	  ports:
		- 443:5000
	  environment:
		REGISTRY_STORAGE: "s3"
		REGISTRY_STORAGE_S3_ACCESSKEY: "xxx"
		REGISTRY_STORAGE_S3_SECRETKEY: "xxx"
		REGISTRY_STORAGE_S3_BUCKET: "xxx"
		REGISTRY_STORAGE_PATH: "/registry"
		REGISTRY_STORAGE_S3_REGION: "us-east-1"
		REGISTRY_SEARCH_BACKEND: "sqlalchemy"
		REGISTRY_LOG_LEVEL: "debug"
		REGISTRY_HTTP_TLS_CERTIFICATE: /var/docker-registry-server.cert.pem
		REGISTRY_HTTP_TLS_KEY: /var/docker-registry-server.key.pem
		REGISTRY_AUTH: htpasswd
		REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
		REGISTRY_AUTH_HTPASSWD_PATH: /var/docker-registry.htpasswd
	  volumes:
		- /root:/var

Error from docker logs when I run container:

    time="2015-11-11T23:02:21Z" level=warning msg="Ignoring unrecognized environment variable     REGISTRY_SEARCH_BACKEND"
    configuration error: error parsing /etc/docker/registry/config.yml: yaml: unmarshal errors:
      line 1: cannot unmarshal !!str `/registry` into configuration.Parameters

    Usage:
      registry <config> [flags]
    Flags:
      -h, --help=false: help for registry
      -v, --version=false: show the version and exit

If I take out REGISTRY_SEARCH_BACKEND from docker-compose.yml I still get error:

    configuration error: error parsing /etc/docker/registry/config.yml: yaml: unmarshal errors:
      line 1: cannot unmarshal !!str `/registry` into configuration.Parameters

    Usage:
      registry <config> [flags]
    Flags:
      -h, --help=false: help for registry
      -v, --version=false: show the version and exit

**Comment by stevvooe** [comment]
@GittyHup The file you have above is a docker compose file. The registry accepts registry configuration files.

I'd recommend following the [Deploying Guide](https://github.com/docker/distribution/blob/master/docs/deploying.md).

**Comment by GittyHup** [comment]
Got it working, just took out those 2 lines from docker-compose.yml

**Comment by manjitkumar** [comment]
@GittyHup What was the problem here? I am facing a similar issue.
