### ISSUE TITLE
Registry docker image is huge

### ISSUE THREAD

**Issue by SamSaffron** [docker/distribution#1189]
The current registry docker image is about 220MB, an alpine based image could snugly fit in under 10MB. 

Is there any interest in shrinking the official registry image down? in the past I followed this kind of pattern

1. had a build image that created the binaries https://github.com/SamSaffron/redismux/blob/master/docker/build/Dockerfile#L10 

2. had a simple alpine image that added the binaries in https://github.com/SamSaffron/redismux/blob/master/docker/image/Dockerfile

**Comment by dmp42** [comment]
The official registry image already uses a build-in-one-container - ship-in-another approach: https://github.com/docker/distribution-library-image

For the reasons not to use alpine, IIRC this comment sums things up: https://github.com/docker/distribution-library-image/pull/1#issuecomment-126095035

You can certainly have a smaller image for yourself if you are willing to sacrifice rados support though, but it doesn't seem like this will be the official image (unless you come up with good solutions to address our concerns with alpine).

**Comment by aaronlehmann** [comment]
Note that there are two registry images available on Docker Hub.

`distribution/registry` is the image as created by the build process. This includes the entire toolchain.

`registry:2` is the "official" image. This one has been stripped down to not include the compilers and other build dependencies, so it is only 76 MB.

**Comment by SamSaffron** [comment]
I see... got super confused with `distribution/registry` vs `registry`
