### ISSUE TITLE
Start tagging "stable" 2.0.0 alpha registry revisions

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#119]
As we come closer to the registry beta milestone, we'll need to tag some stable points to start testing from. These will be considered unstable but we'd like to have a reference.

The first tag will be as follows:

2.0.0-alpha.0

The release will be incremented from there until the beta.

**Comment by stevvooe** [comment]
cc @dmp42 @BrianBland

**Comment by stevvooe** [comment]
The docker core project is using c448e0416925a9876d5576e412703c9b8b865e19 for integration testing. Unless anyone objects, I'm going to tag that as the first alpha.

**Comment by dmp42** [comment]
LGTM

**Comment by BrianBland** [comment]
I'd say we should at least use a descendent of 3dc95e213cf662a2160d3585c18f2cb789e6715e so we have proper IAM role support as well as Godeps dependencies for building in the Dockerfile as added in 037a8a11e84f7bc5448ed74c9cf06d86f2405528.

**Comment by stevvooe** [comment]
We can do this:

2.0.0-alpha.0 c448e04
2.0.0-alpha.1 037a8a1
2.0.0-alpha.2 3dc95e2

**Comment by stevvooe** [comment]
Releases are here: https://github.com/docker/distribution/releases

I've tagged the docker 1.5 test revision and the current tip.
