### ISSUE TITLE
TLS handshake timeout on pull

### ISSUE THREAD

**Issue by spencerkohan** [docker/distribution#1194]
I'm running an S3 backed private registry secured by a self-signed certificate, and I'm getting a `TLS handshake timeout` when trying to pull an image.

I've followed the instructions for deploying a repo with a self-signed certificate, and `docker login` and `docker push` work perfectly.

My ca.crt files are located in `/etc/docker/certs.d/<MY_DOMAIN>.com:5555/ca.crt`

I've appended the ca.crt file I'm using for authentication to my certificate chain to mitigate [this issue](https://github.com/docker/distribution/issues/426)

I'm attempting this interaction between my server and my local docker-machine instance installed via docker toolbox, and in either direction push succeeds but pull fails.

Here's the 'docker version' output on my remote ubuntu VPS: 

    Client:
     Version:      1.9.0
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   76d6bc9
     Built:        Tue Nov  3 17:43:42 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.9.0
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   76d6bc9
     Built:        Tue Nov  3 17:43:42 UTC 2015
     OS/Arch:      linux/amd64

And the same for my docker-machine instance:

    Client:
     Version:      1.8.3
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   f4bf5c7
     Built:        Mon Oct 12 18:01:15 UTC 2015
     OS/Arch:      darwin/amd64

    Server:
     Version:      1.8.3
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   f4bf5c7
     Built:        Mon Oct 12 18:01:15 UTC 2015
     OS/Arch:      linux/amd64

Here's the output I get on the pulling instance:

    $ docker pull <MY_DOMAIN>.com:5555/wordpress
    Using default tag: latest
    latest: Pulling from wordpress
    07d9e8952b29: Pulling fs layer 
    ...
    2650eb09e142: Pulling fs layer 
    a719479f5894: Already exists 
    91bac885982d: Already exists 
    unable to ping registry endpoint https://<MY_DOMAIN>.com:5555/v0/
    v2 ping attempt failed with error: Get https://<MY_DOMAIN>.com:5555/v2/: net/http: TLS handshake timeout
    v1 ping attempt failed with error: Get https://<MY_DOMAIN>.com:5555/v1/_ping: net/http: TLS handshake timeout

And here's the log output I see from the registry:

    registry_1 | time="2015-11-20T12:52:13Z" level=warning msg="error authorizing context: basic authentication challenge: htpasswd.challenge{realm:\"Registry Realm\", err:(*errors.errorString)(0xc20802ac80)}" go.version=go1.4.3 http.request.host="<MY_DOMAIN>.com:5555" http.request.id=4b60afd3-9689-4c4c-9ce6-e99698858614 http.request.method=GET http.request.remoteaddr="91.154.146.177:62234" http.request.uri="/v2/" http.request.useragent="docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.10-boot2docker os/linux arch/amd64" instance.id=faae7048-4d08-45c1-9571-96e89e93252a version=v2.2.0 
    registry_1 | 91.154.146.177 - - [20/Nov/2015:12:52:12 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.10-boot2docker os/linux arch/amd64"
    registry_1 | time="2015-11-20T12:52:27Z" level=info msg="response completed" go.version=go1.4.3 http.request.host="<MY_DOMAIN>.com:5555" http.request.id=932a4974-4d06-454a-b797-641492796fa3 http.request.method=GET http.request.remoteaddr="91.154.146.177:62285" http.request.uri="/v2/wordpress/manifests/latest" http.request.useragent="docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.10-boot2docker os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=9.702194028s http.response.status=200 http.response.written=64063 instance.id=faae7048-4d08-45c1-9571-96e89e93252a version=v2.2.0 
    registry_1 | 91.154.146.177 - - [20/Nov/2015:12:52:18 +0000] "GET /v2/wordpress/manifests/latest      HTTP/1.1" 200 64063 "" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.10-boot2docker os/linux arch/amd64"
    registry_1 | 2015/11/20 12:53:15 http: TLS handshake error from 91.154.146.177:62466: EOF
    registry_1 | 2015/11/20 12:53:24 http: TLS handshake error from 91.154.146.177:62465: EOF
    ...
    registry_1 | 2015/11/20 12:54:09 http: TLS handshake error from 91.154.146.177:62457: EOF

**Comment by RichardScothern** [comment]
@spencerkohan  Can you rerun the daemon with debug mode enabled and inspect the logs?

Also, can you `curl` or use a browser to hit that endpoint using your certificate?  This should work:
`curl -i -X GET https://<MY_DOMAIN>.com:5555/v2/wordpress/manifests/latest`

**Comment by spencerkohan** [comment]
Ok I'm trying this now.  Is there an easy way to run in debug mode when starting with docker-compose?  I'm looking at the docs and there's no mention of it.

**Comment by RichardScothern** [comment]
compose starts the registry, it's the daemon you want to start in debug mode.  There is no other option except to restart it with the `-d` flag :cry:

**Comment by spencerkohan** [comment]
In the process of trying to run the daemon in debug mode I ran into a problem with my ip tables.  I ended up rebooting the VPS hosting the registry, and now everything's working perfectly.  No idea what was the problem or what's changed, but unless I can reproduce I guess it must have been related to the host system and not docker or the registry.
