### ISSUE TITLE
copyright symbol in docs instead of literal characters

### ISSUE THREAD

**Issue by MHBauer** [docker/distribution#1197]
In the content digest section of the registry api, there are some copyright symbols. I'm not sure who's doing the interpretation/conversion.

<img width="664" alt="screen shot 2015-11-20 at 14 30 51" src="https://cloud.githubusercontent.com/assets/13337345/11313712/dd857ed2-8f93-11e5-901f-6b300ef8b770.png">

https://github.com/docker/distribution/blame/master/docs/spec/api.md#L326
&
https://github.com/docker/distribution/blame/master/docs/spec/api.md#L328

I'm not sure how to test and fix or I would make a PR to do so.

**Comment by RichardScothern** [comment]
good catch @MHBauer 

@moxiegirl : this appears on [docs.docker.com](http://docs.docker.com/v1.7/registry/spec/api/), but looks ok on github.

**Comment by moxiegirl** [comment]
@RichardScothern   @MHBauer Thanks for the catch. The fix is to put the refs in `tics` instead of _ (underscores)

**Comment by MHBauer** [comment]
I figured out that the docs can be built with `make docs`, but only if you are already in the docs folder. Now I will test the formatting.

**Comment by MHBauer** [comment]
@moxiegirl To do https://github.com/docker/distribution/issues/1197#issuecomment-159027914, should I put all of the `ABCD` vars into backtics? Make them all match?

**Comment by moxiegirl** [comment]
Yes, @MHBauer  that should correct. Also, will make the format consistent with what we do elsewhere.

**Comment by thaJeztah** [comment]
Wonder if we can disable this feature (replace `(c)`) in Hugo / Blackfriday, it's not part of the Markdown standard, and I doubt we have many cases where we actually use it

**Comment by RichardScothern** [comment]
how will we easily copyright our work, @thaJeztah :sob: ?

**Comment by thaJeztah** [comment]
@RichardScothern `&copy;` is your friend!
