### ISSUE TITLE
auth token for docker hub doesn't have expected access

### ISSUE THREAD

**Issue by dgonyeo** [docker/distribution#1203]
I'm trying to follow along with how auth works in v2 of the docker registry, as specified [here](https://docs.docker.com/registry/spec/auth/token/), and I'm having problems getting an auth token that's capable of pulling an image.

If I attempt to pull an image's manifest:

```
curl -L -v https://registry-1.docker.io/v2/alpine/manifests/latest
```

I get a `HTTP/1.1 401 Unauthorized`, as the docs said I would. The `Www-Authenticate` header is set to: 

```
Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:alpine:pull"
```

At this point the docs say to "make a `GET` request to the URL `https://auth.docker.io/token` using the `service` and `scope` values from the `WWW-Authenticate` header":

```
curl -L -v "https://auth.docker.io/token?service=registry.docker.io&scope=repository:alpine:pull"
```

This results in a `HTTP/1.1 200 OK`, with a JSON object that contains a token. However whenever I attempt to use this token:

```
curl -L -v https://registry-1.docker.io/v2/alpine/manifests/latest --header "Authorization: Bearer eyJhbGciOiJFUzI1NiIs..."
```

I just get another `HTTP/1.1 401 Unauthorized`. If I decode the claim set portion of the token (detailed [here](https://docs.docker.com/registry/spec/auth/jwt/)), I get:

```
{"access":[],"aud":"registry.docker.io,scope=repository:alpine:pull","exp":1448303978,"iat":1448303678,"iss":"auth.docker.io","jti":"kZ1Ylx_-CqXkjLiycKti","nbf":1448303678,"sub":""}
```

I assume the token fails to pull the image because the `access` array is empty.

Is there some step I'm missing somewhere?

**Comment by RichardScothern** [comment]
@dgonyeo : you are missing a step.  The value of `WWW-Authenticate` headers is not an actual URL.  Its components are transformed into a request along the lines of the following (example given with `hello-world`:
`'https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/hello-world:pull'`
which will give the correct token containing the claimset

**Comment by dgonyeo** [comment]
Whoops, I had a typo in my example curl (used `,` instead of `&`), just updated the issue.

Apart from that, did I not correctly construct the URL in my 2nd curl in the issue?

```
curl -L -v "https://auth.docker.io/token?service=registry.docker.io&scope=repository:alpine:pull"
```

The token I get from that curl lacks permissions to access anything.

**Comment by RichardScothern** [comment]
The comma was one of the problems, the other was you are requesting `alpine` but the image is actually called `library/alpine`

`curl https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/alpine:pull`

**Comment by dgonyeo** [comment]
Yup, that was my problem. I assumed that `alpine` was a valid image, because `docker pull alpine` works. Thanks for the help!

**Comment by GowrishankarGeek** [comment]
Hi,
Is there option for oauth authentication in docker like github, bitbucket?

**Comment by dmcgowan** [comment]
@GowrishankarGeek not yet, we are trying to add more oauth support to the client so that this could be possible.
