### ISSUE TITLE
Docker PUSH/PULL with HTTPS

### ISSUE THREAD

**Issue by postalC** [docker/distribution#1209]
Hi team,

This issue is created first in docker-library - https://github.com/docker-library/official-images/issues/1212#issuecomment-159354748

## NUTSHELL
Pull and run the latest docker registry 2.2, technically everything work fine, but not able to make it work the same with HTTPS only.

## BACKGROUND
For security reason, I run a nginx in-front of the docker registry with SSL and Basic Auth. So, the idea is only the request with auth successfully would redirect to the actual registry port.

## ISSUE
With that setting, I am able to do docker login and list the docker repo via the registry API. 

But failed to do docker PULL or PUSH, it encountered HTTP ERROR 503.  After few trouble-shoot, notice that the docker PUSH is calling HTTP PATCH at HTTP default port 80.

As work-around, i forced to open-up HTTP port 80 as well to able to do docker PUSH/PULL.

Is this correct behavior? because it seem to be a security threat to allowing HTTP port 80 on registry.

Please let me know if something could be configure to avoid this? Thanks

regards,
CHAI

**Comment by RichardScothern** [comment]
@postalC :  did you follow carefully the instructions at: https://docs.docker.com/registry/nginx/ ?

If so, you will need to provide details of your nginx and registry configurations and logs from the daemon and registry

**Comment by stevvooe** [comment]
@postalC Running on a specific port is not really a security threat. There are probably other issues with the configuration that are leading to this behavior. It sounds to me like the configuration is missing an http section causing the registry to default to port 80. What does your configuration look like?

**Comment by postalC** [comment]
Hi @stevvooe,

Thanks for the feedback, you might be right. The way it been setup is like below:
- There is firewall/load-balancer in-front of the app (nginx and docker registry)
- External Public - HTTPS - control by firewall
- Internally (Within the firewall) - all traffic is HTTP ONLY  

Below is the current config, i would add in the SSL in nginx - so it would be HTTPS (Public) and HTTPS (Internally), doing the change and test now. Shall update again. Thanks.

regards,
PostalC

```
upstream registry {
  server 127.0.0.1:38050;
}

server {
   listen *:10080;
   server_name registry.my.domain.com;

   add_header Docker-Distribution-Api-Version registry/2.0 always;

   access_log /var/log/nginx/registry_access.log;
   error_log /var/log/nginx/registry_error.log;
   client_max_body_size 800M;

   proxy_set_header Host $host;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_set_header X-Original-URI $request_uri;
   proxy_set_header Docker-Distribution-Api-Version registry/2.0;

   location / {
	 auth_basic "Restricted";
	 auth_basic_user_file /etc/nginx/.htpasswd;
	 proxy_pass http://registry;
   }
}
```

**Comment by stevvooe** [comment]
@postalC What about the registry configuration?

**Comment by postalC** [comment]
Hi @stevvooe 

I use it as it-is, just added external port and volume. Thanks

#### Docker Images
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry            2.2                 dfb4481bd21b        2 weeks ago         223.5 MB
```

#### Docker Create 
```
docker create -it \
--name caregistry-2.2 \
-p 38050:5000 \
-v /var/dockerregistry:/var/lib/registry \
registry:2.2
```

**Comment by postalC** [comment]
Hi @RichardScothern 
Hi @stevvooe 

Yape, the HTTPS to HTTPS did the trick, after enable SSL on my nginx. It work as expected. 

So it not really an issue, but some limitation to run in HTTPS to HTTP ONLY setup env.

Once again thanks for the prompt action and useful feedback. Thanks.

regards,
PostalC

**Comment by clemenko** [comment]
Can you post your nginx conf? Can you also post the docker command for the registry?
