### ISSUE TITLE
Swift auth failed if no tenant information provided

### ISSUE THREAD

**Issue by xinxiaogang** [docker/distribution#1215]
According to the registry configuration document, tenant information is optional for swift storage driver:
https://docs.docker.com/registry/configuration/
<table>
  <tr>
    <th>Parameter</th>
    <th>Required</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>
      <code>tenant</code>
    </td>
    <td>
      no
    </td>
    <td>
      Your Openstack tenant name.
    </td>
  </tr>
  <tr>
    <td>
      <code>tenantid</code>
    </td>
    <td>
      no
    </td>
    <td>
      Your Openstack tenant id.
    </td>
  </tr>
</table>

While in my private registry deployment, if I do not configure tenant information, the registry container starts with failure and continuous restarting...
```bash
panic: Swift authentication failed: Response didn't have storage url and auth token

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7f572996d410, 0xc20810e4e0, 0xc208112780, 0x7f572996d410)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:105 +0x3e1
github.com/docker/distribution/registry.NewRegistry(0x7f572996d450, 0xc20810e4e0, 0xc208112780, 0xc208112780, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:94 +0x2d4
github.com/docker/distribution/registry.func·001(0x1299880, 0xc20802b570, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:57 +0x2d1
github.com/spf13/cobra.(*Command).execute(0x1299880, 0xc20800a010, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:495 +0x65c
github.com/spf13/cobra.(*Command).Execute(0x1299880, 0x0, 0x0)
	/go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:560 +0x18d
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:22 +0x2a
```

After I add tenant name in the swift configuration section, the container works well then.
So if tenant is required, it's better to update the document as:
<table>
  <tr>
    <th>Parameter</th>
    <th>Required</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>
      <code>tenant</code>
    </td>
    <td>
      yes
    </td>
    <td>
      Your Openstack tenant name.
    </td>
  </tr>
  <tr>
    <td>
      <code>tenantid</code>
    </td>
    <td>
      no
    </td>
    <td>
      Your Openstack tenant id.
    </td>
  </tr>
</table>

**Comment by RichardScothern** [comment]
thanks for catching this @xinxiaogang .  Are you comfortable with making a PR? :)

**Comment by xinxiaogang** [comment]
PR created: https://github.com/docker/distribution/pull/1224 :-)

**Comment by RichardScothern** [comment]
I just had a quick look at the documentation - and I think the issue is a bit more subtle.  I used the following working configuration.
```
+storage:
  swift:
    authurl: http://192.168.99.100:12345/auth/v1.0
    container: arbitrary_container
    password: testing
    username: test:tester
```

It looks like for v1 auth, an `authurl` can be used.  For v2 auth, a `tenant` / `tenantID` pair are used and for v3 auth a `TrustID`is used.  We should update the docs to reflect this.

**Comment by xinxiaogang** [comment]
@RichardScothern Yes, I use v2 which requires `tenant` / `tenantID`.

**Comment by xinxiaogang** [comment]
@RichardScothern Keystone identity API has a big change from v2 to v3 according to the specification. I suggest not to list all the details here but should mention whether parameter is required depends on the auth version used.

**Comment by RichardScothern** [comment]
@xinxiaogang that sounds reasonable.
