### ISSUE TITLE
Questions about push and pull compare to registry v1 - performance issue

### ISSUE THREAD

**Issue by Soulou** [docker/distribution#1216]
Hi there,

I've been testing Distribution in production for a few weeks now, it works OK but I've some heavy performance issue leading to a multiplication by 3 or 4 of the duration required by the `docker push` and `docker pull` operations.

My configuration is the following, I've observed the same performance regression in both environments:

staging: 1 instance of distribution using a common redis cache, and using swift as storage backend.
production: 2 instances of distribution load balanced by an nginx, using a common redis cache, and using swift as storage backend.

The images I'm pushing and pulling have ALL the following format:

```
______________

   Image Layer
______________

   Base Image
______________
```

That is to say that each image has only one layer of difference which is quite light compared to the size of the base image.

At each operation, I've the feeling that docker (1.7.1, 1.9 or 1.9.1, confirmed with all of them) is actually pushing all the layers, or pulling multiple layers.

I was expecting the same behavior as before, that is to say, sending or getting the different layer which differenciates the images.

What has changed, what can be changed to handle that a better way? Currently an image which was pushed in 40sec is pushed in 4-5minutes which is a LOT worst, I'm still using a python docker-registry in parallel to get the performance I need but I'd like to get rid of it.

Thanks in advance for your answers and knowledge.

**Comment by xinxiaogang** [comment]
Is there performance issue for your swift storage? What if you change the storage as local file system just for trying?

**Comment by Soulou** [comment]
According to my tests, it's not related to my swift storage. I've experienced such slow-down with file system backend before setting up the swift.

It was slightly faster, but not so much. According to what I see it looks related to how images are handled now.

Before when I was explicitely doing a `docker push`, only the last layer was sent, now, I've the feeling it's computing each time all the shasum of all layers, which require lots of IOs and is super slow.

**Comment by Soulou** [comment]
Ok so it seem the main problem comes from that shared layers are re-pushed, is there, today, a way to avoid that?

**Comment by stevvooe** [comment]
The V2 protocol has exposed a number of performance issues with creating and pushing images. The basic issue is a lack of determinism in layer generation. V1 skirted around this issue by giving the same image id to layers that weren't actually the same content. 

A few problems are enumerated here:

https://github.com/docker/docker/issues/14018
https://github.com/docker/docker/issues/13250

This will be addressed in upcoming PRs (#17924 is a big factor, but others are upcoming).

That said, even without the above fixes, v2 can perform very well during subsequent pushes. I would recommend running the registry in debug mode and analyze the round trip times to the swift backend. Large round trip times to a backend can lead to sub optimal push performance. Address this and your pushes will be snappy.

**Comment by Soulou** [comment]
Thanks @stevvooe for taking the time to write this interesting response.

In my usecase, I'm pushing to a lot of different repositories based on the same image, so I've the feeling everything is pushed each time, then in a given repository there is not so many pushes.

I could try to change my way to do by using only one repository and differenciate the images in the tag only, would it be a good workaround? (waiting for these issues/pulls to be closed and integrated to docker/distribution)  ?

**Comment by stevvooe** [comment]
@Soulou This is a known use case that doesn't perform well with the v2 API. We had to balance access control against the use case of high repository cardinality.

This will be less of a problem with https://github.com/docker/distribution/issues/908. It might be good to see if you can help push that forward. The proposal is ready but I think we are just missing implementations.

> I could try to change my way to do by using only one repository and differenciate the images in the tag only, would it be a good workaround? (waiting for these issues/pulls to be closed and integrated to docker/distribution) ?

This would be the right workaround for your use case.

**Comment by RichardScothern** [comment]
Linking #1269

**Comment by stevvooe** [comment]
@Soulou I am going to close this since we are working on this in several other issues. Let us know if you have specific clarifications.

**Comment by Soulou** [comment]
Thanks @stevvooe, I'm following all the other issues, can't wait to have something working :-) Thanks for your help
