### ISSUE TITLE
[QUESTION] How to separate permissions to pull / push containers?

### ISSUE THREAD

**Issue by ghost** [docker/distribution#1219]
How to implement restricted access to docker registry - some users can only pull, other - only push containers?

**Comment by xiaods** [comment]
use Auth service

**Comment by xinxiaogang** [comment]
@a93ushakov Please refer to this doc for authN and authZ:
https://docs.docker.com/registry/configuration/#auth
And this doc explains the mechanism of token based authentication:
https://docs.docker.com/registry/spec/auth/token/

**Comment by alonbl** [comment]
@xinxiaogang: this is nice, however, for simplicity is there an option to do this with plain htpasswd?

**Comment by dmcgowan** [comment]
@alonbl no, plain htpasswd does not provide ACLs and the only built in ACL method uses a token. You can use a pre-built ACL solution or build your own using the example token server in contrib. There are plenty of products out there that provide this layer to make it simple for end users (for example https://github.com/cesanta/docker_auth).

**Comment by alonbl** [comment]
@dmcgowan this is unfortunate, for two users one with read access and the other for read/write it is an overkill to install docker_auth or any other component. as htpasswd can contain several users already, it should be trivial to have a mapping of user: role under the auth section to enable this basic functionality.

**Comment by darkguy2008** [comment]
2020 and I have to agree with alonbl, I can't believe it's not possible yet. I mean, even a small JSON with username and permissions would do. Waaaaaaaaaay more simpler than figuring out how to deal with an external auth service... I don't really know why sometimes things are made more complicated than they could be.
