### ISSUE TITLE
Upgrade S3 library to awslabs/aws-sdk-go when available

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#122]
We currently depend on https://github.com/crowdmob/goamz that got moved to https://github.com/AdRoll/goamz following buyout.

Support and maintenance level evolution need to be monitored.

Also, AMZ is moving forward and announced this: http://aws.amazon.com/fr/blogs/aws/coming-soon-aws-sdk-for-go/. It is currently very fresh. Let's watch the project at https://github.com/awslabs/aws-sdk-go.

**Comment by stevvooe** [comment]
Proposed AdRoll/goamz#354 to address the http client problems.

**Comment by stevvooe** [comment]
Looking at the direction of sdk-for-go, I'm suggesting we do not adopt it. For example, look at the complexity and bloat of this API: http://docs.aws.amazon.com/sdk-for-go/api/service/s3/S3.html. Not only does it not provide a simple, idiomatic Go interface, but it doesn't seem to be very composable or address many of the issues with goamz.

I suggest we fork goamz and get it into shape.
