### ISSUE TITLE
Cannot delete images in registry

### ISSUE THREAD

**Issue by RyanDeng** [docker/distribution#1221]
Hi all,

I've followed [Docs](https://docs.docker.com/registry/spec/api/#deleting-an-image) by running `curl -X DELETE http://localhost:5000/v2/<image_name>/manifests/latest` to delete image in registry.

However it returns 
`{"errors":[{"code":"DIGEST_INVALID","message":"provided digest did not match uploaded content"}]}`

I've no idea about the error because when I run `curl -X GET http://localhost:5000/v2/<image_name>/manifests/latest`, it will return the correct manifest

**Comment by xinxiaogang** [comment]
@RyanDeng You should not use tag as the `reference` in DELETE request. For deletes, `reference` *must* be a digest or the delete will fail.
Please refer to: https://github.com/docker/distribution/blob/e16c23bb434ac3f8c4d65cbf8fa83b9f5a2141d4/docs/spec/api.md.tmpl#L659-L674

**Comment by RyanDeng** [comment]
Thanks @xinxiaogang. I didn't read the docs carefully
