### ISSUE TITLE
Unsupported Operation

### ISSUE THREAD

**Issue by zhouhaibing089** [docker/distribution#1222]
I execute the following commands:

```sh
docker pull hello-world
docker tag ${ip}:${port}/hello-world
docker push ${ip}:${port}/hello-world
curl -XDELETE http://${ip}:${port}/v2/hello-world/manifests/${sha256}
```

After the last command, I got the response:

```json
{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}
```

Am I wrong? Or maybe it is actually not supported now..

I use docker 1.6.2, and added the `--insecure-registry ${ip}:${port}`.

**Comment by RichardScothern** [comment]
Check your registry configuration.  Delete needs to be enabled there.
