### ISSUE TITLE
Expose blob size through BlobProvider's Open method

### ISSUE THREAD

**Issue by aaronlehmann** [docker/distribution#1223]
Currently, fetching a blob while providing a progress bar is a two-step process:

- Call `Stat` to verify that the blob exists and determine the size
- Call `Open` to get a `ReadSeekCloser` that provides the blob data

The HEAD request that `Stat` performs here seems to be redundant, since the same information could be gathered from `Open`'s GET status code and `Content-Length` header. However, `Open` currently doesn't expose the `Content-Length`. Doing so could save a round trip. Perhaps this could be done by having `Open` also return a `Descriptor`, or creating another variant of `Open` which does, if returning the descriptor imposes some extra for certain implementations.

cc @dmp42

**Comment by stevvooe** [comment]
@aaronlehmann The size of the layer should already be known by the embed, as per the current manifest proposal. This is because a remote cannot be trusted to provide accurate content size and type information.

Ick, though. I know current manifest doesn't have this. At this time, I think the integration with descriptors is rather awkward, since we don't have this information from the caller all the time. I'm not sure if we want to embed them further into the API, given that a descriptor should really be under control of the manifest.

The actual API requires a fast seek to end (since `net/http` relies on this). We accomplish this with `transport.HTTPReadSeeker`. We can remove the requirement for the `size` when creating the read seeker and just have it sniff it from the `Content-Length` header on the initial request.

**Comment by aaronlehmann** [comment]
Looking at this a bit closer, there actually seem to be three roundtrips involved. `Open` performs an extra `Stat`. The only purpose appears to be verification that the blob exists on the remote side. It would be better to just do a GET and check for a 404.

However, to do it that way, `transport.HTTPReadSeeker` would either have to translate HTTP errors to distribution errors (for example, `distribution.ErrBlobUnknown` for 404), or be wrapped with something that does. Since `HTTPReadSeeker` seems intended to be a generic package, how about defining an error type in the transport package that encapsulates an unsucessful HTTP status code, returning that from `HTTPReadSeeker`'s methods, and wrapping `HTTPReadSeeker` with a wrapper defined in the `registry/client` package that translates these HTTP-level error codes to API-level errors like `distribution.ErrBlobUnknown`?

**Comment by aaronlehmann** [comment]
Started working on this, and I have a commit that implements the ideas discussed above: https://github.com/aaronlehmann/distribution/commit/b8be39f6b6fcdf7e14687f33b9c0fd16149221e6

However, I found another problem. It turns out that `Seek` is actually not cheap. It closes the HTTP request so the next `Read` call will create a new one. I think I'll move the logic that calls `reset` into `Read`, so seeking to the end and then back to the previous position doesn't force another round trip.

In the mean time, it would be great if you could look at the linked commit and let me know if you think this is the right track.

**Comment by aaronlehmann** [comment]
Here's a version with the `Seek` cost fixed: https://github.com/aaronlehmann/distribution/commit/a48a2db0a24656d8184fa08ad444b8a83addb891

Tested this in the Docker Engine and it appears to work. If the code looks good, I'll open a PR.

**Comment by stevvooe** [comment]
@aaronlehmann That looks like a good start. I have a few comments inline. It might be better to have a startup phase for the http read seeker that issues a request with the starting reader, resolving the size. That should cover the common case. If that "seed request" isn't there, it can issue a `HEAD` in the reader portion to resolve size, whether or not the request will have, to avoid ambiguity.

**Comment by aaronlehmann** [comment]
Thanks. I opened https://github.com/docker/distribution/pull/1226.

Seeking before reading should work properly. `Seek` now starts a streaming GET if necessary, and sniffs the content length from that.

I addressed your comment about only setting the content length from a 200 repsonse.
