### ISSUE TITLE
[QUESTION] How to mirror images from  a private registry

### ISSUE THREAD

**Issue by zhanghuanzhong** [docker/distribution#1242]
I have a datacenter in city A and another datacenter in city B.Each datacenter with a private docker registry. Now, I expect that the private docker registry B to mirror form the private docker registry A. Could the docker registry mirror do that?

**Comment by zhanghuanzhong** [comment]
I mean that if I run a registry mirror,then how to configure the MIRROR_SOURCE and the MIRROR_SOURCE_INDEX to reach the private docker registry.

**Comment by RichardScothern** [comment]
MIRROR_SOURCE and MIRROR_SOURCE_INDEX are v1 registry configurations.  This repository is for the v2 registry.

To answer you original question; currently the caching mode only works against the hub.

**Comment by zhanghuanzhong** [comment]
@RichardScothern  When I read the Registry V2 mirror proposal #459, I find that `Unlike the V1 registry mirroring feature, a V2 registry mirror can proxy to a private registry. This will allow more flexible registry topologies`. I think `V2 registry mirror can proxy to a private registry` is what I need.

**Comment by RichardScothern** [comment]
@zhanghuanzhong : that is correct, but the features was dropped due to image provenance issues.  The current document is [here](https://github.com/docker/distribution/blob/master/docs/mirror.md), which I realize isn't very clear and will be updated at the behest of another community member: see [issue #1218](https://github.com/docker/distribution/issues/1218)

**Comment by zhanghuanzhong** [comment]
@RichardScothern :Thanks for your reply.
Mum, what to say, I think `V2 registry mirror can proxy to a private registry ` is valuable.

**Comment by RichardScothern** [comment]
Indeed.  Please watch the roadmap for future developments.

**Comment by slnovak** [comment]
+1 on this. I have a use case where I'm needing a pull-through cache to a private registry on another host. Looking forward to seeing this capability!

**Comment by tslater** [comment]
+1

**Comment by zhanghuanzhong** [comment]
:+1:

**Comment by joltup** [comment]
+1. This is important for our developers locally to be able to pull images quickly over LAN. Our internet is not the greatest.

**Comment by tom-aa** [comment]
+1 also for us

**Comment by kinglion811** [comment]
+1 also for us

**Comment by chinaares** [comment]
+1 also for us

**Comment by RichardScothern** [comment]
Pleaese stop `+1`-ing this issue.  You can subscribe to the master image at #1431

**Comment by vatit-admin** [comment]
+1

**Comment by jeanfrancoislarente** [comment]
> Pleaese stop `+1`-ing this issue. You can subscribe to the master image at #1431

Can I thumbs up your comment on +1 ? :)
