### ISSUE TITLE
Redundancy / unwieldy configuration / storage docs

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#1254]
Issue 1: configuration reference is growing really big

Issue 2: drivers separate docs duplicate information, leading to inconsistencies and increased maintenance cost

Example:

https://github.com/docker/distribution/blob/master/docs/configuration.md#openstack-swift

https://github.com/docker/distribution/blob/master/docs/storage-drivers/swift.md

Suggestions / questions:

 * is there a point in maintaining separate drivers documents?
 * or: can't we link the drivers documents from the reference?

cc @moxiegirl @donhcd @RichardScothern @BrianBland and anyone else on the docs team interested

**Comment by moxiegirl** [comment]
@dmp42 I think the suggestion to link to the driver pages from the reference is a good one.  

Would y'all like me to do that?

**Comment by stevvooe** [comment]
@moxiegirl That sounds sufficient. Perhaps, a table at the end of the storage section would be good.

**Comment by moxiegirl** [comment]
@stevvooe Ok, I'll make that happen.

**Comment by moxiegirl** [comment]
@dmp42 I think it makes sense to maintain separate docs for each storage backend and link to them from the configuration file.  One page per storage driver will reduce the size of the configuration file making it easier to manage at an author level.  

If, over time, we want to add content or examples or more detail to each individual storage backend, those pages will grow in detail.  There again, good to have in their own file.

In looking at the material, there has been drift between what is in `configuration.md` and in the individual driver docs.  So, there again, one source of truth is better.

**QUESTIONS**: `oss` (Aliyun) and `inmemory` both have pages in the `storage-drivers` section and appear in the registry test suite.  Neither, tho, are mentioned in the  `configuration.md` page.  **Are they still valid drivers in the system?**

**Comment by RichardScothern** [comment]
@moxiegirl : yes they are.  However, `inmemory` is purely for testing purposes can be omitted.  `oss` is a normal, valid storage driver.

**Comment by stevvooe** [comment]
@RichardScothern `inmemory` may be more viable than that, but I would recommend ramdisk on filesystem over pure `inmemory`. (Perhaps, we say this?).

**Comment by RichardScothern** [comment]
Granted.  As long as nobody deploys on production with a pure `inmemory` driver :joy_cat:

**Comment by moxiegirl** [comment]
Thanks guys. I'll add a note that sums this lil' exchange up.  We can yank it out if you hate it. Onward...
