### ISSUE TITLE
Collision? Guess not, but what?

### ISSUE THREAD

**Issue by emanation** [docker/distribution#1259]
Hello. 
I just finished migration from V1 to V2 with script https://github.com/docker/migrator but this is not a cause because it uses docker commands and I can reproduce problem without it. Well, maybe it's not a problem. Actually I found that several layers have same ID. In ID I mean this
```
b9aeeaeb5e17: Image already exists
b9aeeaeb5e17: Image successfully pushed
```

This is layer used in both images
`b9aeeaeb5e17b5414e5caa9a6b2f99e9ccef50561bdfe137cd05956961f1cec6   7 months ago        /bin/sh -c #(nop) ADD file:2b2b26209d285cd1a96e8168dfb25338aa09155d0a9a6ed54a94be0bd9914461 in 202.6 MB`

If I push one image which uses this layer it's pushed I get this. 
```
$ sudo docker push my.docker.registry.io:5000/mycompany/ping
The push refers to a repository [my.docker.registry.io:5000/mycompany/ping] (len: 1)
6e64a8c6c655: Image successfully pushed 
dbeb3d8e8c47: Image successfully pushed 
...
de0a8619a4d3: Image successfully pushed 
b65ba1e14148: Image successfully pushed 
b9aeeaeb5e17: Image successfully pushed 
f1b10cd84249: Image successfully pushed  
Digest: sha256:1d78ec8451d912642270c6409a33aea5b42e30dbca02ecc126db32125170a2d8
```

Everything is good here. If I do it again right away I get `Image already exists` for each layer.
Next I push another image expecting that this shared layer is already pushed. But not. 

```
$ sudo docker push my.docker.registry.io:5000/mycompany/dsl:stage
The push refers to a repository [my.docker.registry.io:5000/mycompany/dsl] (len: 1)
b74f859e6036: Image successfully pushed 
7d3311815d35: Image successfully pushed 
...
9378787b7ffd: Image successfully pushed 
66c579fdae45: Image successfully pushed 
b1f4e62153c9: Image successfully pushed 
83ef42b6a597: Image successfully pushed 
b9aeeaeb5e17: Image successfully pushed 
f1b10cd84249: Image successfully pushed 
Digest: sha256:6efdfe806a3ab6576e603fb5721e8c45dc30d9eedd354e57c569a8c31984c012
```

But if I push `ping` images again I get

```
6e64a8c6c655: Image already exists
dbeb3d8e8c47: Image already exists
...
de0a8619a4d3: Image already exists
b65ba1e14148: Image already exists
b9aeeaeb5e17: Pushing [===================>                               ] 28.38 MB/72.04 MB
b9aeeaeb5e17: Pushing [==============================>                    ] 44.53 MB/72.04 MB
b9aeeaeb5e17: Pushing [=================================>                 ] 48.43 MB/72.04 MB
b9aeeaeb5e17: Pushing [========================================>          ] 59.02 MB/72.04 MB
b9aeeaeb5e17: Image successfully pushed
f1b10cd84249: Image already exists
Digest: sha256:da6bb140b5290a06a1f6d2813be2b1a2ae7b4c750072f34e366f38c3eebc2e98
```

Here I tapped Enter few times to keep layer size on screen.

Then pushing `dsl` again.

```
b74f859e6036: Image already exists 
7d3311815d35: Image already exists 
...
9378787b7ffd: Image already exists 
66c579fdae45: Image already exists 
b1f4e62153c9: Image already exists 
83ef42b6a597: Image already exists 
b9aeeaeb5e17: Pushing [======================>                            ] 31.72 MB/72.04 MB
b9aeeaeb5e17: Pushing [==========================>                        ] 37.85 MB/72.04 MB
b9aeeaeb5e17: Pushing [================================>                  ] 47.32 MB/72.04 MB
b9aeeaeb5e17: Pushing [============================================>      ] 64.03 MB/72.04 MB
b9aeeaeb5e17: Pushing [==================================================>] 72.04 MB/72.04 MB
b9aeeaeb5e17: Image successfully pushed 
f1b10cd84249: Image already exists 
Digest: sha256:6efdfe806a3ab6576e603fb5721e8c45dc30d9eedd354e57c569a8c31984c012
```

This adds extra new layers with new sha256 hash to S3 storage paths every time I see `Image successfully pushed`
`registry/v2/repositories/mycompany/ping/_layers/sha256/`
`registry/v2/repositories/mycompany/ping/_manifests/revisions/sha256/`
`registry/v2/repositories/mycompany/dsl/_layers/sha256/`
`registry/v2/repositories/mycompany/dsl/_manifests/revisions/sha256/`

If I have more images using same layer it's duplicated in each repo and even few times per repo when I images one after another and this layer is pushed again and again.

If it bug or feature?

**Comment by Soulou** [comment]
That's actually a feature in order to isolate repositories layer from each
other. I made the same (sad) observation there
https://github.com/docker/distribution/issues/1216 Read the thread for more
details.

**Comment by RichardScothern** [comment]
@emanation : the v2 protocol security model requires the client prove it has the bytes it is claiming to push which causes the upload when you push to a different repository.   

The data is stored in the blobs directory once and linked into each repository that requires it.

There is a proposal to support cross repository mount which will remove the upload requirement: https://github.com/docker/distribution/issues/634
