### ISSUE TITLE
Listing Image tags does not return 404 when image does not exist

### ISSUE THREAD

**Issue by jlhawn** [docker/distribution#126]
Instead of returning a 404 Not Found response, an empty list of tags is returned instead!

**Comment by jlhawn** [comment]
The issue occurs when [this line](https://github.com/docker/distribution/blob/c41141fbd3b99fa052c26ca79200d4e63463a816/registry/tags.go#L38) returns no error, but the slice has no items.

**Comment by stevvooe** [comment]
Looks like the specification requires a 404 in this case: https://github.com/docker/distribution/blob/master/doc/SPEC.md#get-tags

We'll fix this.

**Comment by diogomonica** [comment]
Closed by #64
