### ISSUE TITLE
registry as a daemon

### ISSUE THREAD

**Issue by fbacchella** [docker/distribution#1260]
The docker registry is missing almost all that a well educated daemon should do:

 - fork and close stdout/stderr.
 - writing a pid file.
 - logging to syslog.

The example given are the worst possible way of logging: stdout and sending a pseudo-alert mail. Please provide at least some explanation to configure syslog.

Not everyone like to run everything as a docker container. It would be nice to provide the minimal set of code to run the registry as a daemon

**Comment by RichardScothern** [comment]
@fbacchella : Given that most users do run the Registry from the container this feature is not very requested, hence the current setup.  

As per your other PR, if you want to integrate logrus and syslog, we welcome all contributions.

As a workaround, if you want to run the registry outside a container and log to syslog, you can redirect stderr to stdout and pipe to  `logger`.

**Comment by fbacchella** [comment]
So no one is doing log rotation of registry output ? They just wait to have full file systems ?
That's the purpose of logging to syslog, not stdout/stderr.

**Comment by RichardScothern** [comment]
As I said above, most users run the Registry within containers which supports many logging drivers, including syslog.

As I also said above, you can pipe to the general purpose `logger` which will utilize syslog.

I'm closing this issue.

**Comment by stevvooe** [comment]
@fbacchella Sorry to expand here, but daemonization, logging, pid file support is the domain of process supervisors (docker, daemontools, systemd, supervisord, etc.) and not applications. Too many projects have broken implementations of these features and we won't be one of them.

**Comment by fbacchella** [comment]
And many other project does that well, there is a lot of library, tools and documentation to do that. It's not that hard and it's a well know problem. And it's not up to you to prevent end user to launch it as a daemon. It depends on a lot of factor if the tools you talk about are available or not.

**Comment by stevvooe** [comment]
@fbacchella An end user has a number of ways to launch the registry as a daemon using standard tools. This avoid the crust of daemon code and the flexibility to be deployed in many scenarios. We simply don't want to maintain this and most needs are already meet.

I'm considering this matter closed, as we will never add daemonization to the registry.
