### ISSUE TITLE
LogHook is not usable

### ISSUE THREAD

**Issue by fbacchella** [docker/distribution#1261]
In registry/handlers/app.go

        for _, configHook := range configuration.Log.Hooks {
                if !configHook.Disabled {
                        switch configHook.Type {
                        case "mail":
                                hook := &logHook{}
                                hook.LevelsParam = configHook.Levels
                                hook.Mail = &mailer{
                                        Addr:     configHook.MailOptions.SMTP.Addr,
                                        Username: configHook.MailOptions.SMTP.Username,
                                        Password: configHook.MailOptions.SMTP.Password,
                                        Insecure: configHook.MailOptions.SMTP.Insecure,
                                        From:     configHook.MailOptions.From,
                                        To:       configHook.MailOptions.To,
                                }
                                logger.Hooks.Add(hook)
                        default:
                        }
                }
        }

So there is no other way to catch log than mail, despite using logrus. That's very very annoying

**Comment by RichardScothern** [comment]
@fbacchella :  Panic notification by email was added as it was required by a community member who contributed this change.  Supporting other capture methods is not too difficult and all contributions are accepted.
