### ISSUE TITLE
docker registry v2 storage with alibaba oss problem.

### ISSUE THREAD

**Issue by chendoubao** [docker/distribution#1265]
HI,dear all
    In registry v2 storage with oss, i use the internal domain to connect the oss .  But the internal doesn't have https. So have some problem:
```
panic: Get https://**.oss-cn-hangzhou-internal.aliyuncs.com/?******: x509: certificate is valid for *.oss-internal.aliyuncs.com, not *****.oss-cn-hangzhou-internal.aliyuncs.com
```
i know the constrain is the mismatch of CA, but I have no idea if i want to use http instead of https. As i cannot find the correct config..

**Comment by RichardScothern** [comment]
@chendoubao : Is there something missing from the oss documentation? https://github.com/docker/distribution/blob/master/docs/storage-drivers/oss.md

**Comment by chendoubao** [comment]
@RichardScothern 
No, the document is ok . 
But the oss internal domain's have no ca certs. So the registry start have some problem:(panic: **certificate is valid ***) . I'm try to told this to oss's engineer. But they told me have no plan to modify this. 
So i want to know registry v2 how to config without https. 

ps: https://github.com/docker/distribution/blob/master/docs/storage-drivers/oss.md this documentation 's "endpoint" just sed the url without http/https.

**Comment by chendoubao** [comment]
@RichardScothern 
I am very sorry, i miss the "encrypt". Now this problem is resolve. 
So i close the issue at this time.
