### ISSUE TITLE
crypto/tls: failed to parse private key

### ISSUE THREAD

**Issue by Haitianisgood** [docker/distribution#1279]
I did all following official website.

I run it:
docker run  -p 5000:5000 --restart=always --name registry \
  -v `pwd`/certs:/certs \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
  registry:2

then report error:

time="2015-12-17T08:57:28Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.5.2 instance.id=74bc82bc-7313-4fb2-b4ef-75db12a26ce2 version=v2.2.1 
time="2015-12-17T08:57:28Z" level=info msg="redis not configured" go.version=go1.5.2 instance.id=74bc82bc-7313-4fb2-b4ef-75db12a26ce2 version=v2.2.1 
time="2015-12-17T08:57:28Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.5.2 instance.id=74bc82bc-7313-4fb2-b4ef-75db12a26ce2 version=v2.2.1 
time="2015-12-17T08:57:28Z" level=fatal msg="crypto/tls: failed to parse private key" 

the domain.crt what my website is using.It can be parsed by DNS

I have two question:
1. if domain.crt  is SSL certificate ????
2. why my certificate  failed to parse when it is using on my website????

Thanks all!

**Comment by dmp42** [comment]
@Haitianisgood it's hard to tell without more information.

Can you try setting up nginx using your certificate and key and report?

@NathanMcCauley @diogomonica any openssl kungfoo to help diagnose this?

**Comment by Haitianisgood** [comment]
@dmp42 
what do you mean?
I have found the solution:
The private key cant be encrypted
