### ISSUE TITLE
Add a notification handler for tag events

### ISSUE THREAD

**Issue by RichardScothern** [docker/distribution#1280]
After the creation of the new tag store, the get by tag flow will change to:
`Lookup tag for digest`
`Get manifest for digest`

This should emit two notification events (one for each action).  Currently there is only one.

cc @stevvooe

**Comment by RichardScothern** [comment]
cc @nwt

**Comment by stevvooe** [comment]
:clap:

**Comment by RichardScothern** [comment]
:bow:
