### ISSUE TITLE
Getting 503 when using S3 as backend, with no hints in logs about reason. 

### ISSUE THREAD

**Issue by c4milo** [docker/distribution#1285]
`docker run` starts the service just fine, it returns 200 when queried in `/v2/` but after a couple of seconds it only returns 503 errors, including requests to `/debug/health`
```
docker run -p 5000:5000 -ti -e LOG_LEVEL=debug -e REGISTRY_STORAGE="s3" -e REGISTRY_STORAGE_S3_ACCESSKEY="" -e REGISTRY_STORAGE_S3_SECRETKEY="" -e REGISTRY_STORAGE_S3_REGION="us-east-1" -e REGISTRY_STORAGE_S3_BUCKET="mybucket" -e REGISTRY_STORAGE_S3_ROOTDIRECTORY="/foo/bar/docker-registry"  registry:2
```

### Logs
```
WARN[0000] No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable.  go.version=go1.5.2 instance.id=b4f04df2-abda-4b9d-8965-ce00762ec406 version=v2.2.1
INFO[0000] redis not configured                          go.version=go1.5.2 instance.id=b4f04df2-abda-4b9d-8965-ce00762ec406 version=v2.2.1
INFO[0000] listening on [::]:5000                        go.version=go1.5.2 instance.id=b4f04df2-abda-4b9d-8965-ce00762ec406 version=v2.2.1
INFO[0000] Starting upload purge in 57m0s                go.version=go1.5.2 instance.id=b4f04df2-abda-4b9d-8965-ce00762ec406 version=v2.2.1
INFO[0008] response completed                            go.version=go1.5.2 http.request.host=localhost:5000 http.request.id=db630281-e085-4cb0-a102-164917d17bda http.request.method=GET http.request.remoteaddr=172.17.0.1:57190 http.request.uri=/v2/ http.request.useragent=curl/7.29.0 http.response.contenttype=application/json; charset=utf-8 http.response.duration=2.62294ms http.response.status=200 http.response.written=2 instance.id=b4f04df2-abda-4b9d-8965-ce00762ec406 version=v2.2.1
172.17.0.1 - - [18/Dec/2015:21:04:47 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "curl/7.29.0"
INFO[0011] response completed                            go.version=go1.5.2 http.request.host=localhost:5000 http.request.id=bb8e7663-156d-4d9b-bdae-6b15822f31df http.request.method=GET http.request.remoteaddr=172.17.0.1:57193 http.request.uri=/v2/ http.request.useragent=curl/7.29.0 http.response.contenttype=application/json; charset=utf-8 http.response.duration=3.186717ms http.response.status=200 http.response.written=2 instance.id=b4f04df2-abda-4b9d-8965-ce00762ec406 version=v2.2.1
172.17.0.1 - - [18/Dec/2015:21:04:50 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "curl/7.29.0"
172.17.0.1 - - [18/Dec/2015:21:05:14 +0000] "GET /v2/ HTTP/1.1" 503 125 "" "curl/7.29.0"
172.17.0.1 - - [18/Dec/2015:21:05:22 +0000] "GET /debug/health HTTP/1.1" 503 125 "" "curl/7.29.0"
172.17.0.1 - - [18/Dec/2015:21:05:26 +0000] "GET /v2/debug/health HTTP/1.1" 503 125 "" "curl/7.29.0"
```

**Comment by djenriquez** [comment]
@c4milo did you leave `-e REGISTRY_STORAGE_S3_ACCESSKEY="" -e REGISTRY_STORAGE_S3_SECRETKEY=""` blank for the post, or do you really run your command that way?

If its the latter and you are using IAM roles to authenticate, just remove those two environment variables, they cause problems :fire:

**Comment by c4milo** [comment]
that did it @djenriquez, thank you. The documentation is confusing then, it says those parameters are required.

**Comment by dmp42** [comment]
cc @BrianBland

**Comment by jaychris** [comment]
I am having this same issue or at least, the same symptoms - it's been working fine for weeks and now suddenly I get 503's with no clue as to the reason.

Started like this:
docker run -d -p 443:5000 --restart=always --name registry -v `pwd`/certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -v `pwd`/config.yml:/etc/docker/registry/config.yml registry:2

with this in config.yml:
version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    s3:
        accesskey: <redacted>
        secretkey: <redacted>
        region: us-gov-west-1
        bucket: docker-registry
        encrypt: false
        secure: false
        v4auth: true
        chunksize: 5242880
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3


Logging:
time="2016-01-04T15:51:32.271277179Z" level=debug msg="using \"text\" logging formatter" 
time="2016-01-04T15:51:32.27483447Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.5.2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
time="2016-01-04T15:51:32.275274931Z" level=info msg="redis not configured" go.version=go1.5.2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
time="2016-01-04T15:51:32.275404532Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.5.2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
time="2016-01-04T15:51:32.275667319Z" level=info msg="Starting upload purge in 8m0s" go.version=go1.5.2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
time="2016-01-04T15:51:32.295198523Z" level=info msg="listening on [::]:5000, tls" go.version=go1.5.2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
time="2016-01-04T15:51:42.314714321Z" level=debug msg="s3.List(\"/\")" go.version=go1.5.2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry trace.duration=38.792852ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=2c76c8ad-6e51-443d-86cf-09c5b05bc043 trace.line=154 version=v2.2.1 
time="2016-01-04T15:51:52.472074095Z" level=debug msg="s3.List(\"/\")" go.version=go1.5.2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry trace.duration=196.274332ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=86794027-53fc-4cae-8631-c104ad19c7e5 trace.line=154 version=v2.2.1 
time="2016-01-04T15:51:53.367691564Z" level=debug msg="authorizing request" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=2bf58a68-5209-48c2-b316-f40dd94f1f8b http.request.method=GET http.request.remoteaddr="192.168.100.62:57682" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
time="2016-01-04T15:51:53.367820461Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=2bf58a68-5209-48c2-b316-f40dd94f1f8b http.request.method=GET http.request.remoteaddr="192.168.100.62:57682" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.517268ms http.response.status=200 http.response.written=2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
192.168.100.62 - - [04/Jan/2016:15:51:53 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
time="2016-01-04T15:51:53.399782404Z" level=debug msg="authorizing request" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=bb5fd136-99de-482c-bbbb-54c4e9810acb http.request.method=GET http.request.remoteaddr="192.168.100.62:57683" http.request.uri="/v2/bsg/mission_control/manifests/0.0.21" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry vars.name="bsg/mission_control" vars.reference=0.0.21 version=v2.2.1 
time="2016-01-04T15:51:53.400011267Z" level=debug msg=GetImageManifest go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=bb5fd136-99de-482c-bbbb-54c4e9810acb http.request.method=GET http.request.remoteaddr="192.168.100.62:57683" http.request.uri="/v2/bsg/mission_control/manifests/0.0.21" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry vars.name="bsg/mission_control" vars.reference=0.0.21 version=v2.2.1 
time="2016-01-04T15:51:53.400095935Z" level=debug msg="(*manifestStore).GetByTag" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=bb5fd136-99de-482c-bbbb-54c4e9810acb http.request.method=GET http.request.remoteaddr="192.168.100.62:57683" http.request.uri="/v2/bsg/mission_control/manifests/0.0.21" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry vars.name="bsg/mission_control" vars.reference=0.0.21 version=v2.2.1 
time="2016-01-04T15:51:53.421633918Z" level=debug msg="s3.GetContent(\"/docker/registry/v2/repositories/bsg/mission_control/_manifests/tags/0.0.21/current/link\")" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=bb5fd136-99de-482c-bbbb-54c4e9810acb http.request.method=GET http.request.remoteaddr="192.168.100.62:57683" http.request.uri="/v2/bsg/mission_control/manifests/0.0.21" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry trace.duration=21.391673ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=1d067699-eeb3-4fc0-bb53-52ce6717e9bd trace.line=82 vars.name="bsg/mission_control" vars.reference=0.0.21 version=v2.2.1 
time="2016-01-04T15:51:53.422028138Z" level=error msg="response completed with error" err.code="MANIFEST_UNKNOWN" err.detail="s3: The difference between the request time and the current time is too large." err.message="manifest unknown" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=bb5fd136-99de-482c-bbbb-54c4e9810acb http.request.method=GET http.request.remoteaddr="192.168.100.62:57683" http.request.uri="/v2/bsg/mission_control/manifests/0.0.21" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=24.670284ms http.response.status=404 http.response.written=381 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry vars.name="bsg/mission_control" vars.reference=0.0.21 version=v2.2.1 
192.168.100.62 - - [04/Jan/2016:15:51:53 +0000] "GET /v2/bsg/mission_control/manifests/0.0.21 HTTP/1.1" 404 381 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
time="2016-01-04T15:51:53.454330195Z" level=debug msg="authorizing request" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=433ac3ab-db61-4e0e-a888-1029d70bcd0a http.request.method=GET http.request.remoteaddr="192.168.100.62:57684" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
time="2016-01-04T15:51:53.454455056Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=433ac3ab-db61-4e0e-a888-1029d70bcd0a http.request.method=GET http.request.remoteaddr="192.168.100.62:57684" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.22946ms http.response.status=200 http.response.written=2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
192.168.100.62 - - [04/Jan/2016:15:51:53 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
192.168.100.62 - - [04/Jan/2016:15:51:53 +0000] "GET /v1/repositories/bsg/mission_control/images HTTP/1.1" 404 19 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
time="2016-01-04T15:51:58.701345575Z" level=debug msg="authorizing request" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=b4ff1409-a81c-4e43-9a6c-5798c057ece0 http.request.method=GET http.request.remoteaddr="192.168.100.62:57706" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
time="2016-01-04T15:51:58.701462621Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=b4ff1409-a81c-4e43-9a6c-5798c057ece0 http.request.method=GET http.request.remoteaddr="192.168.100.62:57706" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.823144ms http.response.status=200 http.response.written=2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
192.168.100.62 - - [04/Jan/2016:15:51:58 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
time="2016-01-04T15:51:58.729790118Z" level=debug msg="authorizing request" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=76829f0c-6eac-4fe1-99fb-036014c7e332 http.request.method=GET http.request.remoteaddr="192.168.100.62:57707" http.request.uri="/v2/bsg/mission_control/manifests/0.0.21" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry vars.name="bsg/mission_control" vars.reference=0.0.21 version=v2.2.1 
time="2016-01-04T15:51:58.729906258Z" level=debug msg=GetImageManifest go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=76829f0c-6eac-4fe1-99fb-036014c7e332 http.request.method=GET http.request.remoteaddr="192.168.100.62:57707" http.request.uri="/v2/bsg/mission_control/manifests/0.0.21" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry vars.name="bsg/mission_control" vars.reference=0.0.21 version=v2.2.1 
time="2016-01-04T15:51:58.730041141Z" level=debug msg="(*manifestStore).GetByTag" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=76829f0c-6eac-4fe1-99fb-036014c7e332 http.request.method=GET http.request.remoteaddr="192.168.100.62:57707" http.request.uri="/v2/bsg/mission_control/manifests/0.0.21" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry vars.name="bsg/mission_control" vars.reference=0.0.21 version=v2.2.1 
time="2016-01-04T15:51:58.90766661Z" level=debug msg="s3.GetContent(\"/docker/registry/v2/repositories/bsg/mission_control/_manifests/tags/0.0.21/current/link\")" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=76829f0c-6eac-4fe1-99fb-036014c7e332 http.request.method=GET http.request.remoteaddr="192.168.100.62:57707" http.request.uri="/v2/bsg/mission_control/manifests/0.0.21" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry trace.duration=177.520035ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=6b82d2d4-49fe-4552-b42c-c956ffe1b6bc trace.line=82 vars.name="bsg/mission_control" vars.reference=0.0.21 version=v2.2.1 
time="2016-01-04T15:51:58.907941752Z" level=error msg="response completed with error" err.code="MANIFEST_UNKNOWN" err.detail="s3: The difference between the request time and the current time is too large." err.message="manifest unknown" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=76829f0c-6eac-4fe1-99fb-036014c7e332 http.request.method=GET http.request.remoteaddr="192.168.100.62:57707" http.request.uri="/v2/bsg/mission_control/manifests/0.0.21" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=180.019451ms http.response.status=404 http.response.written=381 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry vars.name="bsg/mission_control" vars.reference=0.0.21 version=v2.2.1 
192.168.100.62 - - [04/Jan/2016:15:51:58 +0000] "GET /v2/bsg/mission_control/manifests/0.0.21 HTTP/1.1" 404 381 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
time="2016-01-04T15:51:58.938209799Z" level=debug msg="authorizing request" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=8f0f2cdc-728a-4150-abf2-6eef61aaff9f http.request.method=GET http.request.remoteaddr="192.168.100.62:57708" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
time="2016-01-04T15:51:58.938320859Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=dockerregistry.blacksky.com http.request.id=8f0f2cdc-728a-4150-abf2-6eef61aaff9f http.request.method=GET http.request.remoteaddr="192.168.100.62:57708" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.770302ms http.response.status=200 http.response.written=2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry version=v2.2.1 
192.168.100.62 - - [04/Jan/2016:15:51:58 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
192.168.100.62 - - [04/Jan/2016:15:51:58 +0000] "GET /v1/repositories/bsg/mission_control/images HTTP/1.1" 404 19 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
time="2016-01-04T15:52:02.315723635Z" level=debug msg="s3.List(\"/\")" go.version=go1.5.2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry trace.duration=39.89869ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=88510c40-26aa-434d-a081-04ce64c72727 trace.line=154 version=v2.2.1 
time="2016-01-04T15:52:12.359767935Z" level=debug msg="s3.List(\"/\")" go.version=go1.5.2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry trace.duration=83.969385ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=ddfdf5f8-03c3-4434-ad64-32b68b5a59a2 trace.line=154 version=v2.2.1 
time="2016-01-04T15:52:22.354762028Z" level=debug msg="s3.List(\"/\")" go.version=go1.5.2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry trace.duration=78.982059ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=89929286-a109-445d-b7e8-122c25e146b9 trace.line=154 version=v2.2.1 
192.168.100.62 - - [04/Jan/2016:15:52:27 +0000] "GET /v2/ HTTP/1.1" 503 125 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
192.168.100.62 - - [04/Jan/2016:15:52:27 +0000] "GET /v2/ HTTP/1.1" 503 125 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
192.168.100.62 - - [04/Jan/2016:15:52:27 +0000] "GET /v1/_ping HTTP/1.1" 503 125 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
192.168.100.62 - - [04/Jan/2016:15:52:27 +0000] "GET /v1/repositories/bsg/mission_control/images HTTP/1.1" 503 125 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-15-generic os/linux arch/amd64"
time="2016-01-04T15:52:32.457464394Z" level=debug msg="s3.List(\"/\")" go.version=go1.5.2 instance.id=d07825d1-442d-4d18-a28c-965e170c8508 service=registry trace.duration=181.646497ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=b56d5c69-601e-4719-8fa5-05d5ffbcd16a trace.line=154 version=v2.2.1

**Comment by RichardScothern** [comment]
@jaychris : I see `err.detail="s3: The difference between the request time and the current time is too large."` in your logs.  Do you have clock skew on your server?

**Comment by RichardScothern** [comment]
Closing.
