### ISSUE TITLE
Folder "registry" is missed in the docker

### ISSUE THREAD

**Issue by CKA3KuH** [docker/distribution#1287]
When I trying to push my docker:
```
The push refers to a repository [node4904-os-d-registry.jc.neen.it:11001/sa-mp-docker] (len: 2)
Sending image list
Error: Status 503 trying to push repository sa-mp-docker: "{\"errors\":[{\"code\":\"UNAVAILABLE\",\"message\":\"service unavailable\",\"detail\":\"health check failed: please see /debug/health\"}]}\n"
```
In my docker:
```
# pwd ; ls -la /var/lib/ | grep registry
/var/lib
```
After /var/lib/registry folder creation all working as it should.

**Comment by dmp42** [comment]
How to do you run the registry? Do you follow the documentation or trying to run the registry binary directly?

**Comment by jansauer** [comment]
Same problem here. I tried run the registry with a docker data container.
```
docker create --name registry_data --entrypoint /bin/echo registry:2 'gitlab data container'
docker run -d --name registry_web --restart always --volumes-from registry_data registry:2
```
The odd side effect is that if I now export the containers as a backup neither of them has the images. `registry_web` has a empty `/var/lib/registry` and in `registry_data` the folder is missing although the container has the image layers and they are nowhere to found in the exported container backup.

**Comment by CKA3KuH** [comment]
There was a bug in my solution where I run the Docker. This case may be closed.
