### ISSUE TITLE
Tags list not updated after delete

### ISSUE THREAD

**Issue by dbdd4us** [docker/distribution#1293]
As a example, tag "test" is pointed to revision "sha256:abc" and after I delete a manifest by DELETE <code>/v2/myrepo/manifests/sha256:abc</code>.I found that the tag "test" is still in the results of  GET <code>/v2/myrepo/tags/list</code>.
But when I call GET <code>/v2/myrepo/manifests/test</code>, it return an 404.

Should we have a check to make sure that the revision link of the tag "test" does exists before the GET <code>/v2/myrepo/tags/list</code> return?

**Comment by dmp42** [comment]
I believe this is a known bug.
Ping @RichardScothern @BrianBland

**Comment by krak3n** [comment]
I'm running `259849596621` registry from 8 days ago, this appears to still be a problem?
