### ISSUE TITLE
bad certificate

### ISSUE THREAD

**Issue by Haitianisgood** [docker/distribution#1298]
I did all following official website.

 https://docs.docker.com/registry/insecure/

 my docker-registry and docker-clent all ubuntu server 14.04  64t

i add /etc/hosts on docker-registry and docker-clent

192.168.1.13  www.haitian.com

 1. I run 

```
mkdir -p certs && openssl req \
  -newkey rsa:4096 -nodes -sha256 -keyout certs/domain.key \
  -x509 -days 365 -out certs/domain.crt
```

and I be sure to use the name www.haitian.com as a CN.

Then I copy domain.crt file to

```
/etc/docker/certs.d/www.haitian.com:5000/ca.crt
```

 on my docker-registry server and docker client 

then restart all docker

2. I run 

```
docker push www.haitian.com:5000/redis

```

error:

then docker-regisry server report:

```
2015/12/24 09:27:54 http: TLS handshake error from 192.168.1.23:59506: remote error: bad certificate
2015/12/24 09:27:54 http: TLS handshake error from 192.168.1.23:59508: remote error: bad certificate
2015/12/24 09:27:54 http: TLS handshake error from 192.168.1.23:59507: remote error: bad certificate

```

docker client  report:

```
root@docker-clent:~# docker push www.haitian.com:5000/redis
The push refers to a repository [www.haitian.com:5000/redis] (len: 1)
unable to ping registry endpoint https://www.haitian.com:5000/v0/
v2 ping attempt failed with error: Get https://www.haitian.com:5000/v2/: x509: certificate has expired or is not yet valid
 v1 ping attempt failed with error: Get https://www.haitian.com:5000/v1/_ping: x509: certificate has expired or is not yet valid

```
and run:

root@docker-registry:~# curl -iv https://www.haitian.com:5000

```

* Rebuilt URL to: https://www.haitian.com:5000/
* Hostname was NOT found in DNS cache
*   Trying 192.168.1.13...
* Connected to www.haitian.com (192.168.1.13) port 5000 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

```

**Comment by BrianBland** [comment]
Given the error message (`x509: certificate has expired or is not yet valid`), it sounds like you're running into a clock synchronization issue. The certificate you generated would be valid from the time you generated it on the host until 365 days later, but if the client machine's local time is not within that window then the certificate will be considered expired.

From your client machine, consider running `date` to check the local date/time and the following to check the validity date of your certificate: `echo | openssl s_client -connect www.haitian.com:5000 2>/dev/null | openssl x509 -noout -dates`

Source: http://www.shellhacks.com/en/HowTo-Check-SSL-Certificate-Expiration-Date-from-the-Linux-Shell

**Comment by dmp42** [comment]
@Haitianisgood 

I'll close this for bookkeeping since @BrianBland answered and I assume you made it work.
If you still have a problem, can you reach out on irc (#docker-distribution)?

Thanks.
