### ISSUE TITLE
docker registry token authentication fails to read a X509 certificate with a negative serial number

### ISSUE THREAD

**Issue by mvanholsteijn** [docker/distribution#1299]
Hi,

I am trying to configure Auth0 as a token issuer for  the Docker Registry, but when i specify the auth0 certificate the registry fails to start with the error message:

- Unable to parse token auth root certificate: x509: negative serial number

The certificate indeed has a negative number:  58:40:4f:68:93:bf:fc:72:cb

Can this be fixed?

It appears a fix is due in go 1.6 (https://github.com/golang/go/commit/a0ea93dea5f5741addc8c96b7ed037d0e359e33f)

Cheers,

Mark

```
time="2015-12-24T15:18:00Z" level=info msg="Starting upload purge in 43m0s" go.version=go1.5.2 instance.id=0eb199e5-ee0c-4d36-985f-a8a8fcb2e167 version=v2.2.1
panic: unable to configure authorization (token): unable to parse token auth root certificate: x509: negative serial number

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7f93a6356430, 0xc820341a10, 0xc820342c80, 0x7f93a6356430)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:236 +0x1fab
github.com/docker/distribution/registry.NewRegistry(0x7f93a6356470, 0xc820341a10, 0xc820342c80, 0xc820342c80, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:94 +0x2b0
github.com/docker/distribution/registry.glob.func1(0x134e2e0, 0xc8203013a0, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:57 +0x2b3
github.com/spf13/cobra.(*Command).execute(0x134e2e0, 0xc82000a130, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:495 +0x6e3
github.com/spf13/cobra.(*Command).Execute(0x134e2e0, 0x0, 0x0)
	/go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:560 +0x180
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:22 +0x23
```

**Comment by BrianBland** [comment]
"http://www.ietf.org/rfc/rfc5280.txt

4.1.2.2. Serial Number
The serial number MUST be a positive integer assigned by the CA to each certificate..... 
Note: Non-conforming CAs may issue certificates with serial numbers that are negative or zero. Certificate users SHOULD be prepared to gracefully handle such certificates."

We don't want to include a forked copy of the crypto/x509 standard library, so until go 1.6 I'd recommend generating a new x509 certificate that conforms to the RFC.

**Comment by stevvooe** [comment]
@mvanholsteijn I'd recommend going back to Auth0 and have them generate a valid certificate.

Here is a [relevant comment](https://github.com/golang/go/issues/8265#issuecomment-118527432) from @agl on this issue.

**Comment by stevvooe** [comment]
@mvanholsteijn I've notified the Auth0 folks. Please reach out, as well. Closing this, as we won't fix it.

**Comment by mvanholsteijn** [comment]
Hi Stephen,

I did notify them at the same time. They will fix the issue and regenerate
my certificate..

Thanks for evaluating this issue!

Cheers,

Mark

On Wed, Dec 30, 2015 at 3:12 AM, Stephen Day <notifications@github.com>
wrote:

> @mvanholsteijn <https://github.com/mvanholsteijn> I've notified the Auth0
> folks. Please reach out, as well. Closing this, as we won't fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/distribution/issues/1299#issuecomment-167918271>
> .
>



-- 
ing.Mark van Holsteijn
tel: +316-22-374-114

**Comment by stevvooe** [comment]
@mvanholsteijn No problem. Let us know if you have other problems. And thanks the Auth0 folks for being so responsive.
