### ISSUE TITLE
Docker registry timeouts

### ISSUE THREAD

**Issue by foxylion** [docker/distribution#1309]
Hi,
we have a problem with our docker registry. From time to time it gets unreachable. So all requests start to timeout.

Our build job shows the following error:
```bash
+ docker login -u USER -p PASS -e EMAIL <our-registry-host>
time="2015-12-29T17:48:17+01:00" level="fatal" msg="Error response from daemon: v1 ping attempt failed with error: Get https://<our-registry-host>/v1/_ping: dial tcp <our-registry-ip>:443: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry <our-registry-host>` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/<our-registry-host>/ca.crt" 
```
It's also inaccessible with the browser.

On the docker registry server itself is only the registry running (on an ec2 instance). The log does not show any suspicious output (these log outputs where yesterday, today its failing to respond):
```
time="2015-12-29T15:59:14.282336307Z" level=info msg="Upload files in /docker/registry/v2/repositories/X/postgresql-data/_uploads/7b25b859-0f21-419b-8007-8ea3e5760edc have older date (2015-12-22 15:25:16 +0000 UTC) than purge date (2015-12-22 15:59:12.983094978 +0000 UTC).  Removing upload directory."
time="2015-12-29T15:59:14.350420506Z" level=debug msg="s3.Delete(\"/docker/registry/v2/repositories/X/postgresql-data/_uploads/7b25b859-0f21-419b-8007-8ea3e5760edc\")" environment=staging go.version=go1.5.2 instance.id=instance-id service=registry trace.duration=68.01328ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Delete" trace.id=6b676816-1345-4ee8-9e6d-25f13bea56cf trace.line=181 version=v2.2.1
time="2015-12-29T15:59:14.350508385Z" level=info msg="Upload files in /docker/registry/v2/repositories/X/apache2/_uploads/f81fcd23-3ae7-4c6b-8e24-81c9a839a743 have older date (2015-12-22 15:32:13 +0000 UTC) than purge date (2015-12-22 15:59:12.983094978 +0000 UTC).  Removing upload directory."
time="2015-12-29T15:59:14.44305663Z" level=debug msg="s3.Delete(\"/docker/registry/v2/repositories/X/apache2/_uploads/f81fcd23-3ae7-4c6b-8e24-81c9a839a743\")" environment=staging go.version=go1.5.2 instance.id=instance-id service=registry trace.duration=92.434516ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Delete" trace.id=beb4fffc-7150-46c9-8d12-9f4b6f7bfdfc trace.line=181 version=v2.2.1
time="2015-12-29T15:59:14.443139074Z" level=info msg="Purge uploads finished.  Num deleted=2, num errors=0"
time="2015-12-29T15:59:14.443229556Z" level=info msg="Starting upload purge in 24h0m0s" environment=staging go.version=go1.5.2 instance.id=instance-id service=registry version=v2.2.1
```

Additionally some other facts that might be interesting:
```
root@donkeykong:~# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                   NAMES
2d4fcc62598f        registry:2          "/bin/registry /etc/d"   7 days ago          Up 6 days           0.0.0.0:443->5000/tcp   registry

root@donkeykong:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry            2                   5dfdbfb4ed57        2 weeks ago         224.5 MB
registry            latest              bdd0d98559dd        2 weeks ago         422.8 MB

root@donkeykong:~# docker exec registry ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  2.4 426812 25312 ?        Ssl  Dec23   5:06 /bin/registry /etc/docker/registry/config.yml
root        46  0.0  0.1  15564  1132 ?        Rs   09:14   0:00 ps aux
```
And here the config we use:
```yaml
version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  s3:
    accesskey: ACCESSKEY
    secretkey: SECRETKEY
    region: eu-central-1
    bucket: BUCKET
    v4auth: true
auth:
  htpasswd:
    realm: "Registry Realm"
    path: /.htpasswd
http:
  addr: 0.0.0.0:5000
  secret: SECRET
  tls:
    certificate: /cert.pem
    key: /cert.key
```
After restarting the registry everything is fine. Anyone an idea how that happens?

**Comment by stevvooe** [comment]
This sounds like an issue with EC2. Have you reached out to AWS support?

**Comment by foxylion** [comment]
I'm not that sure, the EC2 instance does not suffer any problems. I can connect via SSH without any problems. And when there are S3 connectivity issues the registry should at least respond with an error, or write anyting to the log. But there is nothing. From my point of view that sounds more like an issue of the registry itself.

**Comment by stevvooe** [comment]
@foxylion We have encountered a number of odd networking issues with EC2 that don't happen on bare hardware, especially when connecting to S3. Before assuming this is the registry, we need to eliminate hardware and networking issues. Working SSH doesn't eliminate network problems as SSH traffic may traverse a different network path than other traffic. In addition, S3 does an extremely poor job of reporting proper errors, so there is not much more we can do there, other than add more retries. Reach out to AWS and have them help you confirm there aren't actual networking issues. They can also help to point out possible timeouts or errors that may be happening in S3.

It is possible that the registry is deadlocking, but this is extremely unlikely. This can be investigated by getting a goroutine blocking profile from the debug interface. Generally, if the debug interface is configured, the address is usually something like 'http://localhost:5001/debug/pprof/goroutine?debug=2' and `http://localhost:5001/debug/pprof/block?debug=2`.

You may also try turning off `v4auth`. It has extremely poor performance and may increase latency on s3 bound requests.

**Comment by BrianBland** [comment]
Unfortunately you'll need to use a different region if you wish to disable `v4auth`, as the `eu-central-1` region (Frankfurt) only supports the v4 signature model.

**Comment by foxylion** [comment]
Thanks for the detailed response. We will move the registry back to a server with local storage instead of S3. It would be good when these detailed insights are also available in the offical docs. https://docs.docker.com/registry/storage-drivers/s3/
So that prevents the one or other to use the S3 backend without knowing exactly what that means (including the degraded performance what I noticed also).

**Comment by stevvooe** [comment]
@foxylion I'm not really sure what we should say in the docs. We are clearly having issues with v4auth, but we don't know whether its a bug or the way we use s3. I am not sure we want to cement a specific behavior in the docs if the behavior is ephemeral or specific to a deployment. If you have a specific suggestion, that would be appreciated, but it needs to be generally applicable.

Looking at your issue again, it might also be a good idea to check the timeouts on any intermediate components. This should include ELB, nginx and any s3 logs.

**Comment by foxylion** [comment]
I see your concerns. But adding the "degraded performance" for `v4auth` to the documentation seems to be a no-brainer. You can easily remove the information when it is fixed.

In our stack there is only a registry running on a EC2 t2.micro, no ELB, no nginx (used the integrated SSL-feature), no load on the server itself (so enough credits where available).

**Comment by stevvooe** [comment]
@foxylion @BrianBland brought up the possibility that the overhead of `v4auth` is exhausting the CPU credits for the burst instance of t2.micro. I'll let him expand on the details.

It might be a good idea to try it again with a larger instance and see if the issues go away. If you can confirm, we can very likely put a blurb in the docs covering this.

**Comment by foxylion** [comment]
Sorry for the late reply.
Unfortunately we had not the time to test/debug the deployment process with another instance, we switched back to a dedicated server using local storage.

So I think the issue can be closed from my side. Although I'm a bit dissatisfied that it was not a deploy-and-run on AWS like all the other things the Docker stack provides.
