### ISSUE TITLE
Registry startup failing with certificates

### ISSUE THREAD

**Issue by mohanrao** [docker/distribution#1311]
Hi,

I am getting following error when i am using registry:2 and along tls certificates for http

registry_1 | time="2015-12-30T18:59:56Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.5.2 instance.id=a97415c3-5d7a-42b1-8c91-ab7655951d6e version=v2.2.1
registry_1 | time="2015-12-30T18:59:56Z" level=info msg="Starting upload purge in 4m0s" go.version=go1.5.2 instance.id=a97415c3-5d7a-42b1-8c91-ab7655951d6e version=v2.2.1
registry_1 | time="2015-12-30T18:59:56Z" level=info msg="redis not configured" go.version=go1.5.2 instance.id=a97415c3-5d7a-42b1-8c91-ab7655951d6e version=v2.2.1
registry_1 | time="2015-12-30T18:59:56Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.5.2 instance.id=a97415c3-5d7a-42b1-8c91-ab7655951d6e version=v2.2.1
registry_1 | time="2015-12-30T18:59:56Z" level=fatal msg="crypto/tls: failed to parse key PEM data"
dockerregistry_registry_1 exited with code 1

**Comment by liuchang23** [comment]
You should check your PEM first,  Can you paste the first line of your pem.

**Comment by stevvooe** [comment]
@mohanrao Here is the line of code issuing the failure:

```
https://golang.org/src/crypto/tls/tls.go#L206
```

Just guessing, this may be a corrupt or encrypted certificate. As @liuchang23 said, posting the first line of the PEM will help (make sure not to post any private key data).

To better understand the issue, we'll need to at least see the configuration, as well.

**Comment by mohanrao** [comment]
Thanks @stevvooe and @liuchang23 . Its the cert and key wrong combination. After the cert and key modified to correct combination. the issue resolved. But the error is giving wrong impression

**Comment by stevvooe** [comment]
@mohanrao Indeed that is a confusing error message. Looking at the Go tls API, I am not sure if we could infer more from the parse error without delving into the exact mismatch.

How did you go about discovering the mismatch?

**Comment by mohanrao** [comment]
I was searching with that error and go tls api specific. Then I discovered it can be the mismatch and used openssl to verify

**Comment by stevvooe** [comment]
@mohanrao Great! Thanks for the description!
