### ISSUE TITLE
Document how to make silly-auth work

### ISSUE THREAD

**Issue by thenewguy** [docker/distribution#1312]
So the docs for silly-auth seem simple enough.  But I cannot seem to make it work.  It would be helpful to provide a minimal demonstration that allows for `docker login` to work.  I just get `Error response from daemon: no successful auth challenge for https://example.com - errors: [unable to decode token response: EOF]` when nginx responds with an empty 200 response.  If I try to respond with a 200 response containing "silly-auth" i get ` - errors: [unable to decode token response: invalid character 's' looking for beginning of value]`

**Comment by thenewguy** [comment]
Well I finally realized that the error I was getting was a client error.  I needed my silly auth server to return a jwt... duh!

**Comment by stevvooe** [comment]
Silly auth isn't really for use with anything serious. It is meant to be for development. If you need an example, you probably shouldn't using it in the first place. All it does is make sure the `Authorization` header isn't empty.

If you are trying to setup a development environment for use with the registry, check  out https://github.com/docker/distribution/blob/master/docs/building.md. If you have further questions, please feel free to reach out on IRC.
