### ISSUE TITLE
Improper exit code

### ISSUE THREAD

**Issue by maticmeznar** [docker/distribution#1314]
When I stop docker_registry with Ctrl+C (SIGINT) or SIGTERM, it exits cleanly with exit code 2. This is wrong.

POSIX convention says exit code 0 indicates success - no error. Exit codes other than 0 indicate failures. docker_registry can be fixed by exiting with code 0 on a clean exit.

**Comment by stevvooe** [comment]
The registry is intended to run forever. Is shutting down a process that should run forever a success, even if from a SIGTERM? Debatable.

Please submit a PR if this really matters.
