### ISSUE TITLE
[QUESTION]does docker could run a container by using other running container?

### ISSUE THREAD

**Issue by vklonghml** [docker/distribution#1320]
Hi, all
i want to test the docker's capabilities, as we know, we could commit the running docker as a image, then use that image to run a container. But i want to know if there is a way that we could just use the running container's files to run another container, that means, we just move some needed files to other host, and run a container which has the same configures as the original one, thanks.

**Comment by RichardScothern** [comment]
@vklonghml :  That is not possible, and I'm not sure why you would want to do that.  Just commit your container changes and push the image.  When the new image is run in a container on another host, the files will be downloaded.

**Comment by vklonghml** [comment]
ok, thanks
