### ISSUE TITLE
docker registry v2.1  delete images error 405 method not allowed

### ISSUE THREAD

**Issue by maxwell92** [docker/distribution#1326]
I push a image test-busybox. And I found that using DELETE /v2/NAME/manifests/DIGEST can delete the image on https://docs.docker.com/registry/spec/api/#deleting-a-layer . I tried but I failed. I got a response like this: HTTP 405 Method Not Allowed. What's the problem?

**Comment by RichardScothern** [comment]
Did you configure delete to be enabled?

https://docs.docker.com/registry/configuration/#delete

**Comment by maxwell92** [comment]
@RichardScothern Yes. I write the command like this: 
docker run -d -p 5000:5000 --restart=always --name registry \
 -v `pwd`/certs:/certs \
 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
-v /images/:/var/lib/registry \
-e REGISTRY_STORAGE_DELETE_ENABLED=true  \
registry:2.1
is there something wrong?

**Comment by RichardScothern** [comment]
The config looks correct.  Please post the registry logs and your delete command.

**Comment by BrianBland** [comment]
It's most likely this was fixed in v2.2 by #888

The `REGISTRY_STORAGE_DELETE` struct would not exist at time of handling `REGISTRY_STORAGE_DELETE_ENABLED` so deletes would not be enabled.

Closing for bookkeeping, feel free to comment/reopen if you're still encountering this issue.
