### ISSUE TITLE
Add health check interface to debug server

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#133]
Proposal:

1. Create a package health, that allows one to register health checks (similar to expvar). 
2. Create a "/debug/health" internal endpoint.
3. When the "/debug/health" endpoint is called, all health checks are run.
4. Status is reported back as json.

A possible function signature (t @BrianBland):

```
package health

struct HealthStatus {
    Status string
    Metadata interface{}
}

type HealthCheck func Check() (HealthStatus, error)

func Register(name string, check HealthCheck)
```

Please see discussion at docker/docker-registry#656.

**Comment by diogomonica** [comment]
Done in https://github.com/docker/distribution/commit/5370f2c0bec24efc059094e4771f779923bdea29
