### ISSUE TITLE
Issue with large layers and Swift backend

### ISSUE THREAD

**Issue by Kanshiroron** [docker/distribution#1331]
Hello,

This bug follow [#1164](https://github.com/docker/distribution/issues/1164). But it seemed to be resolved with a newer version of Swift.

Here is the scenario:
I create an image with the following Dockerfile:
```
FROM ubuntu:14.04

# installing wget
RUN apt-get update apt-get install -y wget

# installing NDK
RUN wget https://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin \
  && chmod +x android-ndk-r10e-linux-x86_64.bin \
  && ./android-ndk-r10e-linux-x86_64.bin
```
I upload it to a registry having a Swift backend
I try to download it, but it fails while checking the layer:
```
docker pull registry.cryptobox/cryptobox-android:7b66b8f6043d
7b66b8f6043d: Pulling from cryptobox-android
18aeeec736d2: Pull complete
1bfedd453fa2: Verifying Checksum
Pulling repository registry.cryptobox/cryptobox-android
Error: image cryptobox-android:7b66b8f6043d not found
```

Here is the config:
Swift from Openstack Liberty (on ext4)
Registry github.com/docker/distribution v2.2.0 running on container, Docker version 1.8.3, build f4bf5c7
Workstation running Docker version 1.9.1, build a34a1d5

[docker-daemon.log.txt](https://github.com/docker/distribution/files/83012/docker-daemon.log.txt)
[registry.log.txt](https://github.com/docker/distribution/files/83013/registry.log.txt)

**Comment by RichardScothern** [comment]
How big is the layer in your test?

Can you test with the `aerofs/swift` container?  I was able to upload 4GB files without problems.

**Comment by Kanshiroron** [comment]
Hello @RichardScothern,
Thank you for the quick answer. You were right, the issue doesn't seems to be on Registry nor on Docker but on Swift' side.
I made some tests with a docker image of Swift (SSO) and everything run fine. And after reviewing my Swift's configuration, I wasn't able to find the source. It's all the more so strange to me as it always stops on the same layer at the exact same spot. I also tried to re-generate the image but no change...

Here the command to retrieve the layer:
```
swift download registry files/docker/registry/v2/blobs/sha256/86/861e24a7b3d1282078eb66444f0bdbe1bf0557701f0b7bd3876e4ad83b0d0959/data
Error downloading object 'registry/files/docker/registry/v2/blobs/sha256/86/861e24a7b3d1282078eb66444f0bdbe1bf0557701f0b7bd3876e4ad83b0d0959/data': 'Error downloading files/docker/registry/v2/blobs/sha256/86/861e24a7b3d1282078eb66444f0bdbe1bf0557701f0b7bd3876e4ad83b0d0959/data: read_length != content_length, 1082589184 != 1344970114'
```
I don't know if you ever encountered this kind of issue, but I'll happy to read your thoughts.
Thanks

**Comment by RichardScothern** [comment]
I'm sorry, @Kanshiroron I do not now what is going on there.  Can you remove docker from this equation and download a big file directly from your swift cluster.

**Comment by Kanshiroron** [comment]
Thank you for your feedback,
I made some further tests and I reported a bug there: https://bugs.launchpad.net/swift/+bug/1534577
Thanks again
