### ISSUE TITLE
A question about pull through cache

### ISSUE THREAD

**Issue by half-dead** [docker/distribution#1334]
Doing multiple "docker pull" requests simultaneously on the same repository and the same tag, to a registry which is set up as a pull through cache of the original private registry and yet doesn't contain the cache, will all requests go to the origin registry? or it's just the first one, while the rest will block until the first request is done?
Just to make sure, I run some tests, seems it's the second one.

**Comment by RichardScothern** [comment]
There is no blocking - that would cause request timeouts.  Data will be streamed to clients until it's persisted to the proxy registry's filesystem after which it will be served from there.

**Comment by half-dead** [comment]
Thanks for the answer, but I'm still a little confused, does "Data will be streamed to clients" mean all "docker pull" request will go to the origin registry until it's persisted to the proxy registry's filesystem?

**Comment by RichardScothern** [comment]
Yes
