### ISSUE TITLE
Missing documentation for setting up Registry Mirror

### ISSUE THREAD

**Issue by JonathonReinhart** [docker/distribution#1336]
The first result of a [Google search for "docker registry mirror"](http://www.google.com/search?q=docker%20registry%20mirror) is https://docs.docker.com/engine/articles/registry_mirror/, where we find the following content:

> ### Run a local registry mirror
The original content was deprecated. An archived version is available in the 1.7 documentation. For information about configuring mirrors with the latest Docker Registry version, please file a support request with the Distribution project.

Consider this said support request.

Is there any documentation for this? If so, I'm unable to find it, and it should be linked from the aforementioned page.

In my particular case, I have a GitLab CI runner which tries to pull helper images as part of its build. However, this runner does not have access to the internet, so I'm trying to figure out the best way to set up my Docker daemon, or private registry, or both, in order to provide these images. (https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/980)

**Comment by RichardScothern** [comment]
It's unfortunate that there is no clear way to get to the [correct documentation](https://github.com/docker/distribution/blob/master/docs/mirror.md) from the docs website.  @moxiegirl : what do you think the best way around this is?

@JonathonReinhart : your comment [here](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/980#note_3183030) seems right: you have a private registry, with a self-signed cert and tag and push the images to it.

**Comment by moxiegirl** [comment]
@RichardScothern Authors can intentionally leave a file out of the docs menu by not including `[main.menu]` in the file.  This was specifically requested in the case of several files in this repository.  I wasn't the original author so I'm not sure of the exact history here.  Looks like you were, I can add it back to the menu.   Can you tell me where you would like it placed?

![image](https://cloud.githubusercontent.com/assets/1347209/12372892/d7e4b15a-bc1b-11e5-8f93-11d416097a1e.png)

**Comment by dserodio** [comment]
I'm still confused. Is the `--registry-mirror` option for Docker daemon currently deprecated?

**Comment by JonathonReinhart** [comment]
I, too am confused. The aforementioned page is the same as it was when I opened this issue:

![image](https://cloud.githubusercontent.com/assets/1916566/21731215/54180a74-d421-11e6-8c93-a4154c3549dc.png)

**Comment by dmcgowan** [comment]
Also confused...it might be worth filing an issue over on the docs project to update that page. https://github.com/docker/docker.github.io

The flag is not deprecated, the documentation that was previously there used the deprecated v1 registry, but there is documentation under the registry section at https://docs.docker.com/registry/recipes/mirror/.
