### ISSUE TITLE
Docker repository allowing sslv3 connections

### ISSUE THREAD

**Issue by oeymere** [docker/distribution#1340]
During a network audit it was noted that our private docker repository was allowing SSL 3 connections and I am wondering if we can disable that.  The repository was also allowing TLS connections, which is good, but we need to have it so that SSLv3 is not allowed.  Is there a way to configure this in the repository?

I know that docker itself is communicating with TLS but our network rules are now that SSLv3 has to be completely disabled, even from other connections (e.g. openssl or curl) so I need to find a way to force this.

This is the start of the output when connecting via curl and forcing ssl3:
$ curl -vk --raw -X GET https://<my_server>:5000/v2/images/projectdocks/tags --sslv3
* Hostname was NOT found in DNS cache
*   Trying <ip_address>...
* Connected to <my_server> (<ip_address>) port 5000 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using AES256-SHA
* Server certificate:
*    subject: C=CA; L=Default City; O=Org; OU=OrgUnit; CN=<my_server>

**Comment by RichardScothern** [comment]
Please upgrade your registry version.  SSLv3 was [disabled by default](https://github.com/golang/go/issues/9364) in go 1.5 which is used to build the registry  version 2.2 and later.
