### ISSUE TITLE
Redirects to upload location should use relative URL

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#1346]
A common source of problems is that we provide an absolute URL in registry redirects. This primarily affects the upload location used by clients. We need to either just let these be relative or let the user decide if they want to turn it off.

My guess is that removing this should work out of the box but it should be tested.

The original reason we support absolute URLs is to support breaking out of a load balancer to scale io. This has been less useful since we don't have a solid way of associated authentication with the redirect target. We could make this more useful by implementing some sort of URL signing scheme.

**Comment by RichardScothern** [comment]
I have an implementation of this in a branch.  Things work out of the box Docker 1.10, 1.9, and 1.8.  

Unfortunately Docker 1.6 & 1.7 fail with `unsupported protocol scheme ""`.  We may to put this on the back burner until 1.7 is truly deprecated.

**Comment by stevvooe** [comment]
@RichardScothern Interesting. Do we know why? I wouldn't have expected so much to change in the time since 1.6/1.7 from the http client perspective. It sounds like we just need to have a configuration option for this.

**Comment by RichardScothern** [comment]
Simply, this piece of code which constructs an http request from the returned URL.  Culprits thereof are listed :cat: 

```
6f4d8470 (Antonio Murdaca 2015-03-26 23:22:04 +0100 173)        logrus.Debugf("[registry] Calling %q %s", method, routeURL)
a01cc3ca (Tibor Vass      2015-05-14 07:12:54 -0700 174)        req, err := http.NewRequest(method, routeURL, nil)
7c88e8f1 (Derek McGowan   2014-10-01 18:26:06 -0700 175)        if err != nil {
7c88e8f1 (Derek McGowan   2014-10-01 18:26:06 -0700 176)                return err
7c88e8f1 (Derek McGowan   2014-10-01 18:26:06 -0700 177)        }
1b43144a (Stephen J Day   2014-12-22 14:58:08 -0800 178)        if err := auth.Authorize(req); err != nil {
1b43144a (Stephen J Day   2014-12-22 14:58:08 -0800 179)                return err
d094eb6f (Derek McGowan   2014-12-19 16:14:04 -0800 180)        }
a01cc3ca (Tibor Vass      2015-05-14 07:12:54 -0700 181)        res, err := r.client.Do(req)
7c88e8f1 (Derek McGowan   2014-10-01 18:26:06 -0700 182)        if err != nil {
7c88e8f1 (Derek McGowan   2014-10-01 18:26:06 -0700 183)                return err
7c88e8f1 (Derek McGowan   2014-10-01 18:26:06 -0700 184)        }
```

**Comment by stevvooe** [comment]
@RichardScothern Is any of that code generating the `unsupported protocol scheme ""` error?

**Comment by RichardScothern** [comment]
`http.NewRequest` requires a protocol in the url passed.  In this case it is not getting one as the protocol is not part of the relative URL.

**Comment by stevvooe** [comment]
@RichardScothern Shouldn't `net/http` be interpreting the `Location` header and do the redirect behind the scenes? Where is `routeURL` coming from?

**Comment by RichardScothern** [comment]
@stevvooe : unfortunately that's not what is happening in this case.  `routeURL` is read from the `Location` header of a POST request to the blob upload endpoint and fed directly into `NewRequest`

**Comment by stevvooe** [comment]
Ok, so [initiateBlobUpload](https://github.com/docker/docker/blob/73b33db04b29a516bf8c50fbe646f563298fcfd9/registry/session_v2.go#L252) needs to make the `Location` absolute. There is more information on this [here](https://golang.org/src/net/http/server.go?s=48569:48637#L1653) and for the [client](https://golang.org/src/net/http/client.go?s=6511:6572#L447).
