### ISSUE TITLE
Documentation layout and proposal

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#135]
This is a placeholder issue for getting documentation written.

Proposed layout is a simple set of markdown docs:

```
doc/
    introduction.md
    spec/
        api.md
        token.md
    registry/
        introduction.md
        configuration.md
        notification.md
        ...
```

Goals are as follows:

1. Everything is simple markdown. We enforce no builder.
2. Doc directory is user oriented (spec, operating, etc.
3. Developer documentation belongs in README.md + CONTRIBUTING.md.
4. Docs should be importable elsewhere.

**Comment by dmp42** [comment]
cc @BrianBland 

LGTM

Just a word: the line between "developer" and "user" might be a blurry one (protocol documentation, for example, is interesting for both).

I would definitely like something that "gradually" present concepts for different "levels" of use. Maybe something in the line of:

 1. (user) basic use and concepts: installation, configuration and running a registry
 1. (advanced user) advanced uses and operation, maintenance, storage organisation
 1. (integrator) developing around the registry: understand the protocol, use of the notification system, extensions
 1. (contributor) hacking the registry itself

This is just a braindump - and the above does not preclude a specific folder organisation.

**Comment by stevvooe** [comment]
@dmp42 This is a great break down. It looks like we are thinking along the same lines.

**Comment by BrianBland** [comment]
Sounds good. Can't wait to see more user-ready docs.

**Comment by fredlf** [comment]
For help writing Open Source documentation, please contact Mary (@moxiegirl). But if you don't ping one of us, the odds are low that we'll discover a PR like this. There are too many different labels and workflows for us to easily discover all issues and needs. Thanks.

**Comment by dmp42** [comment]
Thanks @fredlf 
@SvenDowideit is part of that effort and has been notified (I assume Sven is doc team?)

**Comment by dmp42** [comment]
@moxiegirl @fredlf @svendowideit

For the record, here is the list so far: https://github.com/docker/distribution/labels/documentation

**Comment by fredlf** [comment]
@dmp42 Sven works on commercial docs now. Mary documents Open Source.

**Comment by dmp42** [comment]
@fredlf Ok, thanks for the info - then you should probably clear that up.

Either way, I'm happy we have you guys helping out!
You can reach out to @stevvooe anytime for more about where we are with this and/or how we can work well together.
