### ISSUE TITLE
Set explicit User-Agent string when accessing S3

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#1353]
Using a distinctive UA string containing the registry version + go version would help debugging (distinguish registry queries from other systems accessing the bucket).

That UA string should be set only for the registry, and not for distribution as a library.

cc @RichardScothern

**Comment by stevvooe** [comment]
@dmp42 So, this should be set in the S3 library?

**Comment by BrianBland** [comment]
Yeah, I'm trying to see if there's any extensible way to modify the S3 client through the goamz library that would enable a change like this, would have to modify the http Client/Transport found here: https://github.com/AdRoll/goamz/blob/master/s3/s3.go#L1165

**Comment by BrianBland** [comment]
Read over the v4 auth documentation and only the `Host`, `Content-Type` and any `x-amz-*` headers need to be signed, so changing other headers at the final transport wouldn't break signatures. I'd suggest adding something akin to our client RequestModifier, or at least HeaderModifier (https://github.com/docker/distribution/blob/master/registry/client/transport/transport.go#L11), but interestingly enough the official http.RoundTripper docs suggest that RoundTrip should not modify the request (https://golang.org/pkg/net/http/#RoundTripper)

**Comment by stevvooe** [comment]
@BrianBland The only way to fix this would probably to refactor goamz to allow injection of an `http.Client`.

**Comment by RichardScothern** [comment]
+1.  Do it!

**Comment by RichardScothern** [comment]
Implemented.
