### ISSUE TITLE
Propose extension model

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#136]
The docker distribution registry requires a rich extension model to support plugins that interact with registry data. The new registry does have clear APIs but lack points to hook in from external mechanisms. With #113, webhook notification will be available but there may be other points that require hooks.

Something like https://github.com/progrium/go-extpoints might be appropriate but it may be prudent to wait for [Execution Modes](https://docs.google.com/document/d/1nr-TQHw_er6GOQRsF6T43GGhFDelrAP0NqSS_00RgZQ/edit) to develop into shared libraries.

This will be complete when we have an accepted proposal for an extension model. This supersedes docker/docker-registry#613.

**Comment by dmp42** [comment]
Notifications are used for that.
Further extending the registry requires to hack on it, which we believe is fair.
