### ISSUE TITLE
How to install the docker/distribution from source 

### ISSUE THREAD

**Issue by duyanghao** [docker/distribution#1369]
I have found  a lot of information about the docker/distribution installation,however,all of these tell me how to use the Dockerfile generate registry mirror! But,what i need is to generate the registry from the source code,in other words,by compiling the source code.urgently!!!

**Comment by aibaars** [comment]
Is this what you are after: https://github.com/docker/distribution/blob/master/docs/building.md ?

**Comment by stevvooe** [comment]
This is covered in [building](https://github.com/docker/distribution/blob/master/docs/building.md), as @aibaars said.

In the future, please consult IRC or the mailing list for such questions.

**Comment by duyanghao** [comment]
thanks! I get it !
