### ISSUE TITLE
tagging should be required for official docker images

### ISSUE THREAD

**Issue by vvitayau** [docker/distribution#1384]
Docker registry community should ensure that maintainers of official docker images be trained to tag their repo.

For example https://github.com/nginxinc/docker-nginx/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+missing+tags

**Comment by stevvooe** [comment]
We don't have any control over the communities use of tagging for official images. The tags for nginx are here: https://github.com/docker-library/official-images/blob/master/library/nginx.

Please take this issue over to https://github.com/docker-library/official-images.
