### ISSUE TITLE
Better documentation for S3 driver IAM permissions

### ISSUE THREAD

**Issue by BrianBland** [docker/distribution#1391]
As mentioned in #492, the s3 driver requires the following minimal permission scope to operate correctly when configured to use the bucket `mybucket` at the root:

```json
    {
        "Effect": "Allow",
        "Action": "s3:ListAllMyBuckets",
        "Resource": "arn:aws:s3:::*"
    },
    {
        "Effect": "Allow",
        "Action": [
            "s3:ListBucket",
            "s3:GetBucketLocation"
        ],
        "Resource": "arn:aws:s3:::mybucket"
    },
    {
        "Effect": "Allow",
        "Action": [
            "s3:PutObject",
            "s3:GetObject",
            "s3:DeleteObject"
        ],
        "Resource": "arn:aws:s3:::mybucket/*"
    }
```

This should be added to the s3 driver documentation, as well as further information regarding a more limited scope when using a bucket "root directory" prefix.

**Comment by danielwhatmuff** [comment]
Just a note for the docs, when running the distribution/registry container on RHEL 7.2 you have to explicitly pass any proxy environment variables like this:

docker run -d -p 5000:5000 -e 'HTTPS_PROXY=http://blah:port' -e 'HTTP_PROXY=http://blah:port' -e 'http_proxy=http://blah:port' -e https_proxy='http://blah:port' -v /tmp/config.yml:/etc/docker/registry/config.yml docker.io/distribution/registry

It won't pick them up from the host, so even if you can aws s3 cp <src> <dest> from the host via the proxy, it won't push images up to s3. It will just hang and give you no help.

**Comment by drewrobb** [comment]
Hi, as of 2.4.0 some additional permissions are needed as the client now uses multipart uploads. This is what worked for me:


```
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "s3:ListAllMyBuckets"
        ],
        "Resource": "arn:aws:s3:::*"
      },
      {
        "Effect": "Allow",
        "Action": [
          "s3:ListBucket",
          "s3:GetBucketLocation",
          "s3:ListBucketMultipartUploads"
        ],
        "Resource": "arn:aws:s3:::mybucket"
      },
      {
        "Effect": "Allow",
        "Action": [
          "s3:PutObject",
          "s3:GetObject",
          "s3:DeleteObject",
          "s3:ListMultipartUploadParts"
        ],
        "Resource": "arn:aws:s3:::mybucket/*"
      }
    ]
```

**Comment by RichardScothern** [comment]
We will need to add `s3:AbortMultipartUpload` to this, to be able to cancel uploads

 `http://docs.aws.amazon.com/AmazonS3/latest/dev/mpuAndPermissions.html`
