### ISSUE TITLE
DELETE an image registry does not send out an event/notification

### ISSUE THREAD

**Issue by reasonerjt** [docker/distribution#1396]
Per my testing and per the doc:
https://docs.docker.com/registry/notifications/

Seems when a DELETE http request is triggered there won't be any events sent out from registry.  

Is there plan to support that?

**Comment by reasonerjt** [comment]
ok, saw the comment by stevvooe in the code: notifications/listener.go

**Comment by stevvooe** [comment]
@reasonerjt At this point, this should probably work. Re-opening until we confirm.

@RichardScothern I'm guessing this should be an easy fix, if it is not already present.

**Comment by RichardScothern** [comment]
@stevvooe I think so.  I'll take a look
