### ISSUE TITLE
Docker push fails consistently when pushing to a registry cluster behind an ELB and backed by S3

### ISSUE THREAD

**Issue by mostlygeek** [docker/distribution#1402]
This is my configuration: 

````
ELB => nginx => Docker Registry => S3
````

I would consistently see pushes fail *when* I have two registry instances behind my ELB. With a single instance it works fine. This led me to think there is a race condition. Tailing the nginx logs on both instances I see: 

Instance #1
````
1454023560.319 "52.34.48.107" "HEAD /v2/<redacted>/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 307 0 ...
1454023560.556 "52.34.48.107" "POST /v2/<redacted>/blobs/uploads/ HTTP/1.1" 202 0 ...
````

Instance #2
````
1454023560.609 "52.34.48.107" "PATCH /v2/<redacted>/blobs/uploads/34698b0e-54c6-46cc-8c0e-f62c31fceb2d?_state=<...> HTTP/1.1" 404 88 ...
````

What is happening is: 

  1.  HEAD => instance 1, 404 not found
  1.  POST => instance 1, 202 Accepted
  1.  PATCH => instance 2, 404 not found

Maybe the registry is not completely stateless and/or the `POST` response returns before S3 has finished writing. 

There is only about a 50ms difference between the `POST` and `PATCH` request.

To work around this I'm only running a single instance behind the ELB. 

__Version info:__

Registry instance: 

Docker Registry version: 2.2.1
Docker version:
````
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-108.el7.centos.x86_64
Go version (client): go1.4.2
Git commit (client): 3043001/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-108.el7.centos.x86_64
Go version (server): go1.4.2
Git commit (server): 3043001/1.7.1
OS/Arch (server): linux/amd64
````

Docker on the server doing the pushes:

````
Client:
 Version:      1.8.2-el7.centos
 API version:  1.20
 Package Version: docker-1.8.2-10.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-el7.centos
 API version:  1.20
 Package Version:
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64
````

**Comment by aaronlehmann** [comment]
Do you have the same HTTP secret set in the configuration for the two registries? See https://github.com/docker/distribution/blob/master/docs/configuration.md#http

If you don't set this parameter, each registry will generate a random one, and this can lead to push failures.

**Comment by mostlygeek** [comment]
Yes that was it. I didn't set HTTP secret. After setting that the cluster works.
