### ISSUE TITLE
Why does Registry V2 not support private hub Mirror as Registry V1?

### ISSUE THREAD

**Issue by duyanghao** [docker/distribution#1405]
In the company,as you konw,there is always a need for private Hub Mirror instead of central Hub Mirror. I am curious about the aborting for the private Hub Mirror.Or, Is the support for private hub mirror  still  in process? urgently!!!

**Comment by duyanghao** [comment]
https://github.com/docker/distribution/blob/master/ROADMAP.md#distribution-goals

Proxying to other Registries

A pull-through caching mode exists for the registry, but is restricted from within the docker client to only mirror the official Docker Hub. This functionality can be expanded when image provenance has been specified and implemented in the distribution project.

**Comment by RichardScothern** [comment]
As noted in the distribution goals this functionality can be expanded when image provenance has been specified and implemented.  This is being actively discussed.  I'm closing this issue as there is nothing actionable.
