### ISSUE TITLE
Issue in Docker registry Migration v1 to v2

### ISSUE THREAD

**Issue by kalesastha** [docker/distribution#1406]
Hi,

 I'm migrating docker registry v1 to v2 followed by the [link](https://github.com/docker/migrator) , i'm facing the following issue ,

[OK] Successully pulled all images from kalees-2091.csez.zohocorpin.com:5000 to your local system
[OK] Skipping re-tagging; same URL used for v1 and v2

[!!] Make the necessary changes to switch your v1 and v2 registries and then press any key to continue

[ERROR] v2 registry (kalees-2091.csez.zohocorpin.com:5000) is not available
[!!] Verify v2 registry is functioning as expected; press any key to continue to retry [ctrl+c to abort]

[ERROR] v2 registry (kalees-2091.csez.zohocorpin.com:5000) is not available
[!!] Verify v2 registry is functioning as expected; press any key to continue to retry [ctrl+c to abort]

[ERROR] v2 registry (kalees-2091.csez.zohocorpin.com:5000) is not available
[!!] Verify v2 registry is functioning as expected; press any key to continue to retry [ctrl+c to abort]

**Executed Command :-**

  sudo docker run -it -v /var/run/docker.sock:/var/run/docker.sock -e V1_REGISTRY=admin-zs1.csez.zohocorpin.com:5000 -e V2_REGISTRY=admin-zs1.csez.zohocorpin.com:5000 -e USE_HTTP=true -e V1_USE_HTTP=true -e V2_USE_HTTP=true -e V1_USERNAME=admin -e V1_PASSWORD=password -e V1_EMAIL=admin@localhost.com -e V2_USERNAME= -e V2_PASSWORD= -e USE_INSECURE_CURL=true docker/migrator 2>&1 | tee migration.log

Kindly help me to resolve the above error . Your suggestions are highly appreciated.

Thanks,

Kaleeswaran N

**Comment by dmp42** [comment]
@kalesastha did you setup your registry:2 appropriately? what is configuration? command-line used to launch it?
