### ISSUE TITLE
Concurrent modification in storage drivers

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/distribution#143]
That's more of a question. Is there any sort of guarantee the registry code provides to prevent multiple instances of the registry backend from writing to the same file path at the same time.

Especially on cloud storage backends, we can implement locks (leases) on file paths. This could enable multiple instances writing to the same file concurrently (i.e. interleaving WriteStream calls) by allowing one in and failing others...

To me, this sounds like a race condition that can easily show up in case storage drivers get used in multi-instance high-traffic Docker Hub mirrors and two clients who hit two different registry instances concurrently have image miss on the same layer and these two registry instances start writing on the same path concurrently ([WW conflict](http://en.wikipedia.org/wiki/Write–write_conflict))

There's still not a problem for Azure driver since Azure's commit blocks operation is atomic and last writer would be winning in this case. I'm not sure implementing blob leases (letting one win and others to fail). An ideal solution would be like a distributed lock on currently pulled resource among multiple instances of same registry set up. :mixed-feelings:

cc: @stevvooe @dmp42 @AndreyKostov

**Comment by jlhawn** [comment]
I'm not the most familiar with it by far, but I believe that each blob upload is given a randomly generated temporary name first. So if two different clients initiate an upload of a blob with the same content, the server doesn't use the same name for the temporary object that is being uploaded. This temporary file cannot be read by clients. Once the client completes their upload, a digest of the temporary object is computed and then it is renamed to match the digest. It doesn't matter which client's upload of the object completes last because the rename operation would just be renaming it to an object with identical content.

**Comment by ahmetalpbalkan** [comment]
@jlhawn that sounds good; except the rename part. :) most cloud storage backends do not offer an atomic rename/move operation and that's why `s3.Move` and `azure.Move` functions first copy the file into its final path and delete the original path. Unless two clients try to rename their temporary file to the same path (race condition on `Move`), it'll be fine I guess.

I wasn't aware of the fact that each registry server would always create a random name for the permanent path of a layer/object. Thanks.

**Comment by jlhawn** [comment]
> I wasn't aware of the fact that each registry server would always create a random name for the permanent path of a layer/object

Sorry for any confusion, but they are *not permanent*, they are temporary. The permanent file is named using the *hash* of its contents. Also, even if the rename is *not* atomic, if the data that is being written is exactly the same, there should be no issue, right?

**Comment by ahmetalpbalkan** [comment]
@jlhawn coincidentally, there's no issue on Azure side because a file is uploaded as a list of parts and once upload is done, those parts are committed to the file in a transactional REST call and the change on the file becomes effective. Therefore the permanent file is still safe, however, let's say if two registry servers are using `filesystem` driver using some network attached storage or FTP, then they're going to run into this problem very easily because rename (a.k.a Move) could create a write/write conflict on the permanent path.

**Comment by stevvooe** [comment]
@ahmetalpbalkan Thank you for the interesting question. We've had our eye on these kinds of issues from day one. @jlhawn's explanation really covers most of your questions but I'm going to comment further to document the approach. 

There are a few classes of issues that we need to worry about when implementing something on top of the storage drivers:

1. Read-After-Write consistency (checkout this [article on s3](http://shlomoswidler.com/2009/12/read-after-write-consistency-in-amazon.html)).
2. [write-write conflicts](http://en.wikipedia.org/wiki/Write%E2%80%93write_conflict) (mentioned by @ahmetalpbalkan).

In reality, the registry must worry about these kinds of errors when doing the following:

1. Accepting data into a temporary upload file may not have latest data block yet (read-after-write). 
2. Moving uploaded data into its blob location (write-write race).
3. Modifying the "current" manifest for given tag (write-write race).
4. A whole slew of operations around deletes (read-after-write, delete-write races, etc.).

The backend path layout employs a few techniques to avoid these problems:

1. Large writes are done to private upload directories. This alleviates most of the corruption potential under multiple writers by avoiding multiple writers.
2. Constraints in storage driver implementations, such as support for writing after the end of a file to extend it.
3. Digest verification to avoid data corruption.
4. Manifest files are stored by digest and cannot change. 
5. All other non-content files (links, hashes, etc.) are written as an atomic unit. Anything that requires additions and deletions is broken out into separate "files". Last writer still wins.

Unfortunately, one must play this game when trying to build something like this on top of eventually consistent storage systems. If we run into serious problems, we can wrap the storagedrivers in a shared consistency layer but that would increase complexity and hinder registry cluster performance.

I hope this covered your question. Please let me know if I missed anything.

**Comment by ahmetalpbalkan** [comment]
@stevvooe Thanks for excellent explanation. That has clarified things a lot.

**Comment by stevvooe** [comment]
@ahmetalpbalkan No problem. This belongs in the docs.
