### ISSUE TITLE
Valid registry name/repo name not parsed by regexp in 1.10

### ISSUE THREAD

**Issue by atld** [docker/distribution#1433]
In 1.10 it seems regexp validator got broken, and cannot parse correctly a valid registry/repo name. 

Steps to reproduce:

1. Issue a pull command from the following registry with 1.10

`docker pull registryELB-999514288.eu-west-1.elb.amazonaws.com:5000/ghorvath/test-haproxy:latest
`

2. Following error is displayed:

`Error parsing reference: "registryELB-999514288.eu-west-1.elb.amazonaws.com:5000/ghorvath/test-haproxy:latest" is not a valid repository/tag
`

Expected results: image got pulled. 

Same command works with 1.9.1. Registry and repo exists.

Docker daemon was not contacted during issuing the command. 

Regexp relevant code snippet is here:

https://github.com/docker/distribution/blob/3150937b9f2b1b5b096b2634d0e7c44d4a0f89fb/reference/regexp.go#L6-L70

Environment:

```
root@gabor-vbox:~# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64


root@gabor-vbox:~# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: gabor-vbox
ID: TDRH:X2C6:7JGJ:BDSQ:BBIL:6JUH:ZOZ7:DKQW:R33G:SGWF:S4ML:ZKRL
Http Proxy: http://xxx:xxx@xxx
WARNING: No swap limit support
```

Kindly ask you to verify, confirm and correct the issue.

**Comment by stevvooe** [comment]
@atld Names have always been case insensitive (`registryelb` is the same as `registryELB`). 1.10 had some changes to ensure that naming validation logic is more consistent.

Arguably, the case should be flattened before being parsed into a reference. As a workaround, just use `registryelb-999514288.eu-west-1.elb.amazonaws.com:5000/ghorvath/test-haproxy:latest`. Probably should add this to `reference.Parse`.

**Comment by atld** [comment]
Thank you @stevvooe, it works with your suggested workaround.

**Comment by aaronlehmann** [comment]
Confirmed that there's a difference in behavior between 1.9 and 1.10. 1.9 disallowed uppercase letters in remote repository names, but 1.10 also disallows them in hostnames.

With 1.9:
```
# docker tag registry:2.2.1 OldRegistry:2.2.1
repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
# docker tag registry:2.2.1 SomeHostname:8080/registry:2.2.1
[success]
```

With 1.10:
 ```
# docker tag wordpress WordpressImage
Error parsing reference: "WordpressImage" is not a valid repository/tag
# docker tag wordpress SomeHostname:8080/wordpress     
Error parsing reference: "SomeHostname:8080/wordpress" is not a valid repository/tag
```

This probably needs to be fixed to prevent stranding existing images that have uppercase letters in hostnames.

**Comment by graywh** [comment]
It looks like #1434 fixed this issue for hostnames, but uppercase is still rejected on container names.

**Comment by aaronlehmann** [comment]
Yes, rejecting uppercase characters in remote image names (the part after the hostname) is done intentionally for preserving backward compatibility. Previous versions of Docker don't allow uppercase characters here, so if we started allowing them, that would result in images that older versions of Docker can't pull.

**Comment by jedwards1211** [comment]
This is one of those cases where a simple "no uppercase characters allowed" error message would have saved us all time
