### ISSUE TITLE
Registry authentication service token verification

### ISSUE THREAD

**Issue by tigranbs** [docker/distribution#1449]
Hi 
I'm doing authentication service with Django for Docker registry.
<p>
I've specified <code>realm</code> config parameter to get Token from authentication service, and it works fine with Docker client, but I can't find any documented part how make a validation of Token sent from authentication service to Docker client.
</p>
As documented here <a href="https://docs.docker.com/registry/spec/auth/token/">https://docs.docker.com/registry/spec/auth/token/</a> Authentication service responding to Docker client (daemon) with Bearer Token using JSON response. Then client making HTTP request with <code>Authorization: Bearer</code> header, but where is the validation of Token in Registry part ?
<p>
Sorry if I didn't got full Token authentication idea and asking stupid question.
Thanks
</p>

**Comment by RichardScothern** [comment]
@tigranbs : The registry can be configured with an auth type of token:
https://docs.docker.com/registry/configuration/#auth

When this is configured the registry will validate requests with the given token.

**Comment by tigranbs** [comment]
@RichardScothern thanks for response, after all day playing with certificates finally I made token authentication which is described here <a href="https://docs.docker.com/registry/spec/auth/jwt/">https://docs.docker.com/registry/spec/auth/jwt/</a>
<p>Closing this issue</p>
