### ISSUE TITLE
Docker image reference grammar broken

### ISSUE THREAD

**Issue by tazle** [docker/distribution#1450]
The first line of the reference grammar refers to nonterminal `repository` but the rest of the grammar does not define `repository`. See https://github.com/docker/distribution/blob/master/reference/reference.go#L6

**Comment by tazle** [comment]
It seems like it should reference `name` instead.

**Comment by dmp42** [comment]
Agreed. Can you PR? cc @RichardScothern

**Comment by tazle** [comment]
I was just about to clone the repo for PR, but good to see that you got there first :)
