### ISSUE TITLE
Issues with breaking change - <1.10 pull by digest of images pushed by 1.10 clients

### ISSUE THREAD

**Issue by jhart1685** [docker/distribution#1454]
Docker Registry 2.3 shipped with a breaking_changes document:
https://github.com/docker/docker/blob/9123a24cc8218e5222c2c4f4c9153d6971f3d128/docs/breaking_changes.md

Foremost among these is that an image pushed by 1.10 clients cannot be "pulled by digest" by older  clients. 
This issue prevents us from moving our private registry to 2.3. Put simply, we have runtime machines with older versions of docker-daemon, where we cannot get these updated to 1.10 any time soon. These rely on "pull by digest" in order to get precisely the correct image to run.

As this is blocking us, we would like to see a short term "compatibility" flag that forces the registry only to accept schema1 manifests. This would allow us to run with a 2.3 registry in the short term (and get the benefit of cross-repo layer mounting), while pursuing upgrading our runtimes to 1.10 in parallel.
Once all the runtimes are at 1.10, we can switch off the compatibility flag, and start using the new schema formats.

In local testing, I have found that simply commenting out the contents of the init() methods for the schema1 and manifestList formats achieves the desired behaviour. The registry does not then claim to support the new schema formats, and 1.10 clients fall back to schema1.

**Comment by dmp42** [comment]
> Foremost among these is that an image pushed by an older client (say 1.9) cannot be "pulled by digest" by 1.10 clients.

This is the other way round: if you push an image with 1.10 on a 2.3 registry, you can't pull it by digest with 1.9. Every other scenario works (1.9 push -> 1.10 pull by digest works). Is it still an issue in that context?

Nevertheless, if you want to disable the new manifest support, the recommendation is to wipe out the client requests "accept" header.

If you have a proxy in front of your registry, doing that should be fairly easy.

Otherwise, you might want to modify the registry code around here: https://github.com/docker/distribution/blob/d6a9b209719e78c1b026567a5c4acbd3e1f6ff4b/registry/handlers/images.go#L97

Alternatively, while I understand you want to enjoy X-Repo push ASAP, you could wait for your fleet to upgrade *then* upgrade the registry (bottom-line: it's unlikely we will have a config flag to disable the new manifest schema).

Hope that helps. Let us know of your progress.

**Comment by jhart1685** [comment]
Hello - yes, you're quite right, I got that statement the wrong way around. I'll amend it.
The rest of the issue is accurate.. and it is still a problem for us.

I'll discuss with my colleagues whether the approach of wiping out the "Accept" header would work for us. Conceptually this seems the wrong way around - making all clients appear to the registry to be <1.10, rather than making the registry appear to all clients to be <2.3.

Simply offering the ability to suppress `distribution.RegisterManifestSchema()` for schema2 and manifestList looks like a simple and low risk option. 
Are there any drawbacks to this that you can think of?

**Comment by dmp42** [comment]
So, Aaron amended my comment: wiping-out Accept won't be enough - you probably have to blank-out `Content-type` on PUT/POST (speaking under @RichardScothern & @aaronlehmann control here).

> [extra config to disable updated manifest] Are there any drawbacks to this that you can think of?

Well, the increased churn, support & additional cruft added to configuration (that we will have to test / maintain / deprecate in the future).

Like I said, I certainly understand the desire to enjoy x-repo push + backward/forward pull by digest (in an heterogenous environment), but at this point we would rather recommend to people that they fork if they are willing to commit resources to maintaining this, or go the headers rewriting route.

Happy to discuss it further though.

**Comment by RichardScothern** [comment]
To add color to the header re-writing alluded to above.  When the manifest is put, the content-type header contains the version of the manifest.  If you see a `v2` content type header and rewrite it (preferably not as empty string), the registry will reject the push and the daemon will fallback to v1.

**Comment by jhart1685** [comment]
Thanks Olivier and Richard. We have performed some initial testing with header re-writing today, and early results look positive. It may be a couple of weeks, however, before we can fully test this.

In parallel, I'm interested in whether anyone else from the community has similar issues, and would find an extra config option useful. 
Getting our fleet to upgrade is fine in principle, but not entirely within our control, and not guaranteed to happen in the short term.

**Comment by RichardScothern** [comment]
@jhart1685 : I'm going to close this.

**Comment by jhart1685** [comment]
Ok, thanks Richard. The header re-writing approach seems to be working for us.
