### ISSUE TITLE
Handle `X-Forwarded-Port` in url builder

### ISSUE THREAD

**Issue by RichardScothern** [docker/distribution#1457]
Configurations on non-standard https ports behind reverse proxies do not have the `Location` header value built correctly as not all `X-Forwarded-*` headers are taken into account.

This should be added to the URL builder.   Related and a longer term fix is to return relative URLs.

**Comment by stevvooe** [comment]
> Related and a longer term fix is to return relative URLs.

What is stopping us from doing this? Should be a fairly small patch. Let me know and I can submit.

**Comment by RichardScothern** [comment]
absolultely no reason not to, I meant to link [that issue](https://github.com/docker/distribution/issues/1346)

**Comment by stevvooe** [comment]
@RichardScothern Poke me on monday and I'll get you a pr.

**Comment by stevvooe** [comment]
@RichardScothern Now that I think about this, it is pretty unfortunate. The port is actually part of the host.

**Comment by dmcgowan** [comment]
Fixed by #2008
