### ISSUE TITLE
Document approach to dealing with eventual consistency

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#146]
There are properties of the backend storage layout that are important to maintain to deal with eventually consistent backends. The approach is covered, in part, in https://github.com/docker/distribution/issues/143#issuecomment-72923206.

There should be a section in the architecture portion of the documents that covers these issues. Such knowledge would be useful for contributors as guidelines for modifying the layout as well as operators when troubleshooting problems.

**Comment by ahmetalpbalkan** [comment]
:+1:

**Comment by endophage** [comment]
If we're moving to immutable layers and manifests referenced by their sha256 this problem resolves itself for the most part. Even if 2 people write the same thing at the same time, the data should (allowing for highly improbably hash collisions) also be identical.

**Comment by stevvooe** [comment]
@endophage Please read the referenced comment. The goal of this ticket is not to find the answer to the question but document that answer in the appropriate location.
