### ISSUE TITLE
sometimes already existing layer (e.g., layer for ubuntu:14.04) pushed again to dockerhub

### ISSUE THREAD

**Issue by helinwang** [docker/distribution#1464]
I thought every time I push it should be incremental. But sometimes it pushes existing layer again.

here is few pushes in time order

> // n-th push
> 1515e3a2aade: Layer already exists 
> fbe2db54eaea: Layer already exists 
> b3194de9c939: Layer already exists 
> abf060fbeb02: Layer already exists 
> bc61dcaa1fb9: Layer already exists 
> 629d3660cc59: Pushed 
> 5f70bf18a086: Pushed 
> 0d81735d8272: Pushed 
> 982549bd6b32: Pushed 
> 8698b31c92d5: Pushed
> 
> // n+1-th push
> 5a2c20b22bf1: Pushed 
> 43ba1325889f: Pushed 
> c23b65a5145c: Pushed 
> abf060fbeb02: Layer already exists 
> bc61dcaa1fb9: Layer already exists 
> 629d3660cc59: Layer already exists 
> 5f70bf18a086: Layer already exists 
> 0d81735d8272: Layer already exists 
> 982549bd6b32: Layer already exists 
> 8698b31c92d5: Layer already exists
> 
> // n+2-th push, notice how layer 8698b31c92d5 and 3 more layers got pushed again
> 06db42d823c5: Pushed 
> a3575dd784b5: Pushed 
> e04cb41bff92: Pushed 
> abf060fbeb02: Layer already exists 
> bc61dcaa1fb9: Layer already exists 
> 629d3660cc59: Pushed 
> 5f70bf18a086: Layer already exists 
> 0d81735d8272: Pushed 
> 982549bd6b32: Pushed 
> 8698b31c92d5: Pushed 

and here is docker history of n+2-th push

> 54ee4d70917c        10 minutes ago      /bin/sh -c #(nop) EXPOSE 12000/tcp 12001/tcp    0 B                 
> 8ae93e68a93a        10 minutes ago      /bin/sh -c #(nop) ENTRYPOINT &{["./nexus"]}     0 B                 
> 7644eba33444        10 minutes ago      /bin/sh -c #(nop) COPY multi:609730bd4dcd2093   571 kB              
> ac87f067a414        10 minutes ago      /bin/sh -c #(nop) COPY multi:7b816c50da4eff99   10.84 MB            
> 52ad31e3d4fb        10 minutes ago      /bin/sh -c #(nop) COPY file:dc5824a16ae1ce7e8   14.9 MB             
> 841eb28ef938        44 hours ago        /bin/sh -c #(nop) WORKDIR /prod/bin             0 B                 
> b167f0cca892        44 hours ago        /bin/sh -c mkdir -p /prod/socketio/asset/       0 B                 
> c9c427a1999d        44 hours ago        /bin/sh -c mkdir -p /prod/eval/bin              0 B                 
> 9bad1ce6d92c        44 hours ago        /bin/sh -c mkdir -p /prod/bin                   0 B                 
> 3876b81b5a81        3 weeks ago         /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B                 
> <missing>           3 weeks ago         /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$/   1.895 kB            
> <missing>           3 weeks ago         /bin/sh -c echo '#!/bin/sh' > /usr/sbin/polic   194.5 kB            
> <missing>           3 weeks ago         /bin/sh -c #(nop) ADD file:7ce20ce3daa6af21db   187.7 MB 

If I understand docker push correctly, layer

> <missing>           3 weeks ago         /bin/sh -c #(nop) ADD file:7ce20ce3daa6af21db   187.7 MB(8698b31c92d5)

should not get pushed again.

> docker version
> Client:
>  Version:      1.10.1
>  API version:  1.22
>  Go version:   go1.5.3
>  Git commit:   9e83765
>  Built:        Thu Feb 11 19:14:21 2016
>  OS/Arch:      darwin/amd64
> 
> Server:
>  Version:      1.10.1
>  API version:  1.22
>  Go version:   go1.5.3
>  Git commit:   9e83765
>  Built:        Thu Feb 11 20:39:58 2016
>  OS/Arch:      linux/amd64

pushing to dockerhub private repo.

**Comment by dmp42** [comment]
cc @aaronlehmann for expertise on this

**Comment by aaronlehmann** [comment]
@helinwang: Thanks for the report. It would be helpful to get some more details about what workflow you're following. Are you rebuilding the image between these pushes? Are you pushing images to any other repositories?

Docker maintains a cache of layer digests that remote registries already have, to avoid unnecessary layer uploads. The size of this cache is limited, so it's not guaranteed to prevent these uploads.

To better understand this behavior, it would be useful to see Docker daemon logs from the repeated pushes, with debug mode turned on (`-D` option). It may also be helpful to see the files where Docker stores this digest cache (`/var/lib/docker/image/<graphdriver>/distribution/v2metadata-by-diffid/sha256/<digest>`), and how they changes between the pushes. You would want to look at the one for the base layer. You can find the base layer's digest by looking up the image's ID in `docker images`, then looking at the JSON in `/var/lib/docker/image/<graphdriver>/imagedb/content/sha256/<image id>`. The first item in the `diff_ids` array is the base layer.

**Comment by helinwang** [comment]
@aaronlehmann Thanks Aaron. I am rebuilding the image between pushes.
The Dockerfile is basically copy a binary from mounted volume to work dir. Base image is ubuntu 14.04

I am only pushing the image to the single repo. Note it does not happen all the time. Very likely to happen  if there is a break between pushes. E.g., pushed last night, today morning I build a new image and it happens.

I will give you the logs once I got a chance.
