### ISSUE TITLE
how to optimize the performance  of catalog interface

### ISSUE THREAD

**Issue by liuchang23** [docker/distribution#1484]
I have used catalog api to impl the feature of list user's images, but the request is too slow. how could we optimize this interface.

**Comment by RichardScothern** [comment]
The main factor affecting performance of this function is the performance of the storage engine.

If you are using S3 then you will experience an improvement by trying with the latest build from master.

Theoretically this function could be reimplemented to be more parallel.  However, the most likely improvement will come with the reimplementation of repository metadata in a key value store.  This project is in the planning stages.

**Comment by stevvooe** [comment]
> I have used catalog api to impl the feature of list user's images, but the request is too slow. how could we optimize this interface.

The catalog API isn't really designed for this use case. The correct approach is to crawl the catalog API and index information into a secondary store. Issue user requests to that store.

**Comment by liuchang23** [comment]
@stevvooe thanks for your response, but how to ensure the consistency between catalog and secondary store is a big problem.

**Comment by liuchang23** [comment]
@RichardScothern thanks for your response.

**Comment by stevvooe** [comment]
@liuchang23 The approach most projects take is to scan the catalog and then keep the dataset up to date with notifications. We use this in Docker Trusted Registry and the Hub. Portus also uses a similar strategy.

The biggest reason for this approach is that it allows you to make an API that is optimized for use with users and the registry's API remains focused on content.

**Comment by liuchang23** [comment]
@stevvooe Yes, this approach is the best choice.
