### ISSUE TITLE
HEAD manifest with token auth returning 405 error

### ISSUE THREAD

**Issue by deitch** [docker/distribution#1485]
I have a docker registry 2.2.1, with have token auth set up. It works precisely as expected.

If I try to `GET` a manifest, it works; if I try to `HEAD` a manifest, I get an error `MethodNotAllowed: 405 Method Not Allowed`.

In both cases, the JWT returned has `"actions":["pull"]`. Yet the registry seems to accept a "pull" token for `GET` but not for `HEAD`?

Here is the log for ` GET` (scrubbed):

````
time="2016-02-23T19:10:37Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.5.2 http.request.host=imagehub.example.com http.request.id=26c55292-7c76-4d03-97de-98b07887d745 http.request.method=GET http.request.remoteaddr="172.16.10.4:64381" http.request.uri="/v2/ns/repo/manifests/8.7.3-021" http.request.useragent=Ruby instance.id=fc700d95-56e3-476d-97ff-a077b95e12c9 vars.name="ns/repo" vars.reference=8.7.3-021 version=v2.2.1
172.16.10.4 - - [23/Feb/2016:19:10:37 +0000] "GET /v2/ns/repo/manifests/8.7.3-021 HTTP/1.1" 401 154 "" "Ruby"
time="2016-02-23T19:10:38Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=imagehub.example.com http.request.id=c13cd157-4f26-41a0-8c96-3a31045d5a98 http.request.method=GET http.request.remoteaddr="172.16.10.4:64383" http.request.uri="/v2/ns/repo/manifests/8.7.3-021" http.request.useragent=Ruby http.response.contenttype="application/json; charset=utf-8" http.response.duration=132.885414ms http.response.status=200 http.response.written=83177 instance.id=fc700d95-56e3-476d-97ff-a077b95e12c9 version=v2.2.1
172.16.10.4 - - [23/Feb/2016:19:10:38 +0000] "GET /v2/ns/repo/manifests/8.7.3-021 HTTP/1.1" 200 83177 "" "Ruby"
````

And the log for `HEAD` (scrubbed):

````
time="2016-02-23T19:10:28Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.5.2 http.request.host=imagehub.example.com http.request.id=b429459b-1dbe-4824-8add-be4a304752ab http.request.method=HEAD http.request.remoteaddr="172.16.10.4:64377" http.request.uri="/v2/ns/repo/manifests/8.7.3-021" http.request.useragent=Ruby instance.id=fc700d95-56e3-476d-97ff-a077b95e12c9 vars.name="ns/repo" vars.reference=8.7.3-021 version=v2.2.1
172.16.10.4 - - [23/Feb/2016:19:10:28 +0000] "HEAD /v2/ns/repo/manifests/8.7.3-021 HTTP/1.1" 401 154 "" "Ruby"
172.16.10.4 - - [23/Feb/2016:19:10:28 +0000] "HEAD /v2/ns/repo/manifests/8.7.3-021 HTTP/1.1" 405 19 "" "Ruby"
````

It isn't even showing the `response completed` line with timestamp.

Known bug?

**Comment by RichardScothern** [comment]
@deitch Manifest HEAD was not supported until 2.3.0 (this was an oversight).  Can you test with that version?

**Comment by deitch** [comment]
You know, there is a line in the API spec page about "clarify manifest HEAD request", but I could not find anywhere what that meant. 

I will try and see. 

In the meantime:

1- is there any way to tell the version number and support for HEAD, short of trying it?
2- any risk in upgrading my registry from 2.2 to 2.3? Our engines are a mixed bag.

**Comment by RichardScothern** [comment]
1. Not from the API.  You could inspect via `docker images` or `docker logs`
2. Everything should be backward compatible.

**Comment by deitch** [comment]
Then I just did a `HEAD` with a `begin-rescue` around it. If it fails, I fall back to `GET`. Less efficient, but it will do, and that way I can safely handle <2.3.0 and >=2.3.0.

Can I rename this issue, "please indicate in the documentation that `HEAD` manifest only works from 2.3.0 onwards"?

I will try 2.3.0 right now

**Comment by deitch** [comment]
OK, I can confirm `HEAD` works on 2.3.0.
