### ISSUE TITLE
Docker push to private registry sends unnecessary amounts of data

### ISSUE THREAD

**Issue by jonhoo** [docker/distribution#1495]
**Output of `docker version`**:
```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Thu Feb 25 09:29:05 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Thu Feb 25 09:29:05 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`**:
```
Containers: 35
 Running: 7
 Paused: 0
 Stopped: 28
Images: 13
Server Version: 1.10.2
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.1-2-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.699 GiB
Name: x1c3
ID: KPED:6HWB:BE6N:MSIB:HSRS:QW4T:UX7Z:JBJV:CAI3:YDUM:LS2F:STAG
```

**Provide additional environment details**:
Private registry is running `distribution/registry:2`. Specifically
```
REPOSITORY                             TAG                  IMAGE ID            CREATED             SIZE
distribution/registry                  2                    db533718f51d        11 weeks ago        666.4 MB
```

**List the steps to reproduce the issue**:

  1. Start a private registry (just follow registry quick start directions)
  2. Pull some relatively large image like `golang:1.6` to your local repository
  3. Tag and push to the private registry, i.e.:

      ```console
$ docker pull "golang:1.6"
$ docker tag "golang:1.6" "$registry/golang:1.6"
$ docker push "$registry/golang:1.6"
      ```

  4. Construct a small layer on top of the big image:

      ```Dockerfile
FROM $registry/golang:1.6
MAINTAINER Jon Gjengset <jon@thesquareplanet.com>
RUN echo "world" > hello
      ```

  5. Build, tag, and push the new image:

      ```console
$ docker build -t "foo" .
$ docker tag "foo" "$registry/foo"
$ docker push "$registry/foo"
      ```

  6. Push big image again

      ```console
$ docker push "$registry/golang:1.6"
      ```

**Describe the results you received**:
When pushing the image `foo`, *all* layers are pushing, including those included in `golang:1.6` that were pushed previously. Furthermore, when re-pushing the big image afterwards, the layers are all copied *yet again*. This does not happen if attempting another re-push right after Step 3.

**Describe the results you expected**:
All pushes except the first one should send only relatively small changes.

**Provide additional info you think is important**:
I believe this may be related to docker/distribution#908

**Comment by RichardScothern** [comment]
You are running a distribution build of the registry.  The tag `2` was pointing to an old version of the registry.  I've since updated this.

Please try with the official image `library/registry:2`

**Comment by jonhoo** [comment]
@RichardScothern: ah, yes, `library/registry` handles this case correctly. I wonder where I got `distribution/registry` from... I'm pretty sure I copied it from instructions on `hub.docker.com` or `docker.com` somewhere. Oh well.
