### ISSUE TITLE
HEEDS Star CCM licensing issues

### ISSUE THREAD

**Issue by burakyenier** [docker/distribution#1496]
Customer reports licensing problems when using STAR-CCM+ through HEEDS. 

Below the error "Failed to get all licenses needed" is shown:
![image](https://cloud.githubusercontent.com/assets/6099848/13380412/6c6e1436-ddf7-11e5-86e5-8b679046f224.png)

When I check on the Steve portal I see that the license server is accessed and the license is used for a short period of time:

![image](https://cloud.githubusercontent.com/assets/6099848/13380405/30887c4a-ddf7-11e5-9379-c87531140644.png)

**Comment by burakyenier** [comment]
Power On Demand Licenses were not enabled for the Study. 

![2016-02-28 09 30 49 am](https://cloud.githubusercontent.com/assets/6099848/13380731/8ccebbe8-ddfe-11e5-92d5-06e109557a89.png)

HEEDS has two places for this setting:
1) under settings, each Portal (in this case StarCCM+) has parameters which can be set. This setting appears in this section and is a global setting.
2) under the Process / StarCCM+ / StarCCM+ Portal tab (shown in the image above). This setting is specific to the analysis and overrides the global setting.

**Comment by dmp42** [comment]
@burakyenier are you sure this is the right place to report this?

**Comment by burakyenier** [comment]
Incorrectly filed. Closing.
