### ISSUE TITLE
can not get the request url to use the storagedriver.UrlFor() interface

### ISSUE THREAD

**Issue by yiting163** [docker/distribution#1498]
User want to get the request Url when use the interface
 " storagedrive.URLFor(ctx context.Context, path string, options map[string]interface{}) (string, error)".
The Url is important to distinguish the user's 'pull' or 'push' requst is to private registry or public registry.

The Parameter of "Options" can include the Url of the request.
This interface is called in the blobserver.go like this:
redirectURL, err := bs.driver.URLFor(ctx, path, map[string]interface{}{"method": r.Method})

I think we can call like this:
redirectURL, err := bs.driver.URLFor(ctx, path, map[string]interface{}{"method": r.Method,"url":r.URL.Path})

**Comment by yiting163** [comment]
To speed up the download，we can use CDN . But we need to get the request url,to decide which images we want to use the CDN network.

**Comment by RichardScothern** [comment]
"The Url is important to distinguish the user's 'pull' or 'push' request is to private registry or public registry."

The only URL that will be seen is for the running registry instance. Blobs can be served via a CDN by implementing a middleware to generate the correct URL.  This is currently done for Amazon Cloudfront.

**Comment by yiting163** [comment]
Thanks！Ineed to get the request url,to decide which images we want to use the CDN network. Pass the url param is not a better way to implement？ But I think it‘s too difficult to add a milddleware for this."storagedriver.URLFor(...)" interface is to generate the correct url,it's much simple that pass the url.

**Comment by RichardScothern** [comment]
The storage APIs work with paths not URLs and middleware is designed to mirror this API with a reimplementation of the functionality.

Which part of the URL do you require to make the decision with?  Why is the path not sufficient?

**Comment by yiting163** [comment]
I want to get the url to distinguish the user‘s pull request 。 if the pull cmd is to public repo，i will return the CDN url，in contrast，I will return a normal url。It will be easy to get ，if blobserver use the interface that take this url parameter。

**Comment by RichardScothern** [comment]
Blobs do not belong to individual repositories - they are de-duplicated and referenced from repositories.

Public and private repositories can share the same blob so I'm not sure this approach will work.  Will you store shared blobs locally and in your CDN?

**Comment by yiting163** [comment]
Yeah，i will configure the public  repositories in the config.yml. So, when i get the url ,i wll know which is request the public repositories. If so,i will return a CDN uri to the docker client for download.

**Comment by RichardScothern** [comment]
My point is that blobs are not private or public, they can belong to both types of repositories.  

> 'i will configure the public repositories in the config.yml' 
 
can you expand on this?

**Comment by yiting1122** [comment]
I compelete my own storage driver ,i can configure my storage driver in the config file .In the config file，i will set bucket，chunksize ，accesskeyid and etc. To dinstiguish which image will use the CDN ne, i will config the public repo. 
     For exampel in configure  config.yml:
             accesskeyid:XXX
             bucket:XXX  
             chunksize:XXX
             publicRepo:
                 - "library1"
                 - "library2"
So when i get users' pull request url like "/repo/ubuntu",i will know which url contains "library1" or "library2"  or others in publicRepo configured.
If the url contains "library1",like "library1/ubuntu",i can return a CDN URI for docker client to download.

**Comment by RichardScothern** [comment]
OK, I understand now.

The repository name is held within the context which is propagated through to the middleware.  You can access it in your middleware like this
`context.GetStringValue(ctx, "vars.name")`

**Comment by yiting1122** [comment]
OK，Thanks，i will try。
