### ISSUE TITLE
 Could not reach any registry endpoint

### ISSUE THREAD

**Issue by mluis** [docker/distribution#1499]
While I'm trying to pull from docker hub on a Raspberry Pi Zero I'm getting the follow message.
What could this be?

$docker pull alpine
Pulling repository alpine
docker 2016/02/29 15:33:02 Could not reach any registry endpoint

**Comment by RichardScothern** [comment]
This is a question for the docker engine team.  I would first ask in #docker-dev and if there is a bug, create an issue in docker/docker.

If you can ping `docker.io` and `curl https://registry-1.docker.io/v2/`, then you will have eliminated network, dns and certificate problems.
