### ISSUE TITLE
docker push unauthorized: authentication required

### ISSUE THREAD

**Issue by nklmilojevic** [docker/distribution#1507]
Hello,

As the title says, I did the setup with private docker registry and nginx in front of it with SSL and LDAP auth to active directory.

I can login to the docker repostory with "docker login repo:port", but when I try to tag image and after it push it to the repo I get "unauthorized". 

Here's my configuration.

docker-compose.yml 

> nginx:
>   image: h3nrik/registry-ldap-auth
>   ports:
>     - 5043:443
>   links:
>     - registry:registry
>   volumes:
>     - ./nginx/conf:/etc/nginx:ro
>     - ./nginx/certs:/etc/certs:ro
> registry:
>   image: registry:2
>   ports:
>     - 127.0.0.1:5000:5000
>   environment:
>     REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
>   volumes:
>     - ./data:/data

nginx.conf

> worker_processes 1;
> 
> events {
>     worker_connections 1024;
> }
> 
> http {
> 
>     upstream docker-registry {
>         server registry:5000;
>     }
> 
>     ## Set a variable to help us decide if we need to add the
>     ## 'Docker-Distribution-Api-Version' header.
>     ## The registry always sets this header.
>     ## In the case of nginx performing auth, the header will be unset
>     ## since nginx is auth-ing before proxying.
>     map $upstream_http_docker_distribution_api_version $docker_distribution_api_version {
>         'registry/2.0' '';
>         default registry/2.0;
>     }
> 
>     ldap_server ldapserver {
>         include ldap.conf;
>     }
> 
>     server {
> 
>         listen 443 ssl;
>         server_name domain.com;
> 
>         ssl_certificate /etc/certs/cert.pem;
>         ssl_certificate_key /etc/certs/certkey;
>         ssl_ciphers 'AES256+EECDH:AES256+EDH::!EECDH+aRSA+RC4:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS';
>         ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
> 
>         # disable any limits to avoid HTTP 413 for large image uploads
>         client_max_body_size 0;
> 
>         # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
>         chunked_transfer_encoding on;
> 
>         # For possible locations have a look at https://docs.docker.com/registry/spec/api/#detail
> 
>         location /v2/_catalog {
>             include docker-client.conf;
>             include docker-registry.conf;
>         }
> 
>         location ~* /v2/(?<namespace>([^/]*))/ {
> 
>             include docker-client.conf;
> 
>             auth_ldap "Forbidden";
>             auth_ldap_servers ldapserver;
> 
>             set $deny_write_request "";
>             if ($request_method = PUT) {
>                 set $deny_write_request "W";
>             }
>             if ($request_method = POST) {
>                 set $deny_write_request "W";
>             }
>             if ($request_method = PATCH) {
>                 set $deny_write_request "W";
>             }
>             if ($request_method = DELETE) {
>                 set $deny_write_request "W";
>             }
>             if ($remote_user != $namespace) {
>                 set $deny_write_request "${deny_write_request}A";
>             }
>             if ($deny_write_request = 'WA') {
>                 return 401;
>             }
> 
>             include docker-registry.conf;
> 
>         }
> 
>         location /v2/ {
>             include docker-client.conf;
>             auth_ldap "Forbidden";
>             auth_ldap_servers ldapserver;
>             include docker-registry.conf;
>             add_header 'Docker-Distribution-Api-Version' 'registry/2.0' always;
>         }
> 
> 
>     }
> 
> }

docker-registry.conf

> add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;
> 
> proxy_pass                          http://docker-registry;
> proxy_set_header  Host              $http_host;   # required for docker client's sake
> proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
> proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
> proxy_set_header  X-Forwarded-Proto $scheme;
> proxy_read_timeout                  900;
> proxy_set_header Authorization ""; # see https://github.com/dotcloud/docker-registry/issues/170

docker-client.conf

> if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*\$" ) {
>   return 404;
> }

ldap.conf

> url ldap://url/OU=User,DC=domain,DC=com?samaccountname?sub?(objectClass=user);
> binddn uname;
> binddn_passwd pw;
> group_attribute uniquemember;
> group_attribute_is_dn on;
> require valid_user;
> satisfy all;

Does anyone have an idea why is this happening?

Thanks in advance.

**Comment by dmp42** [comment]
It's very hard to help you without any logs.

Have you looked into nginx logs? Since it's an authentication issue, it's likely your nginx+ldap is not properly configured.

Are you able to curl + auth into your nginx?

**Comment by nklmilojevic** [comment]
Hi dmp42,

Thanks for the answer.

Yup, as I said in my first post, I can login to docker via docker login and via curl and via browser.

I'll have to turn on the debug log for nginx, but the authentication is working...

**Comment by dmp42** [comment]
> but the authentication is working...

Mmm, I don't think it does.
But logs will tell us more.

I would also suggest you try to have it work without your namespace restriction, by removing:

```
        if ($remote_user != $namespace) {
            set $deny_write_request "${deny_write_request}A";
        }
```

**Comment by nklmilojevic** [comment]
Oh my, it works when I removed that line. Thanks a lot!
