### ISSUE TITLE
Registry Storage Driver S3-AWS KMS Encryption Support

### ISSUE THREAD

**Issue by matt-duch** [docker/distribution#1518]
At the moment, the s3-aws driver doesn't support user specified IAM keys for at rest encryption. We use this patch internally to provide that functionality (not production tested, but works in our development environments).
[diff.txt](https://github.com/docker/distribution/files/165770/diff.txt)
[s3.go.txt](https://github.com/docker/distribution/files/165771/s3.go.txt)

**Comment by BrianBland** [comment]
@matt-duch This looks pretty reasonable. Would you like to submit this change as a PR?

**Comment by matt-duch** [comment]
It looks like the Jenkins build failed, but it seems more of an internal error than the commit itself:
Now starting POST-BUILD steps
---

+ docker rm -vf dist-pr977
Failed to remove container (dist-pr977): Error response from daemon: No such container: dist-pr977
+ true
ERROR: Build step failed with exception
java.lang.IllegalStateException: Invalid object ID 311 iota=312
	at hudson.remoting.ExportTable.diagnoseInvalidId(ExportTable.java:386)
