### ISSUE TITLE
Docker login wrong IP?

### ISSUE THREAD

**Issue by SantoDE** [docker/distribution#1520]
Hey guys,

I'm currently trying to deploy an own distribution server beyond a nginx-proxy (https://github.com/jwilder/nginx-proxy). 

When trying to call the URLS in my browser, everything is fine. From within docker login it's just wrong. I'm getting a wrong IP.

`Error response from daemon: invalid registry endpoint https://registry.manuel-laufenberg.de/v0/: unable to ping registry endpoint https://registry.manuel-laufenberg.de/v0/
v2 ping attempt failed with error: Get https://registry.manuel-laufenberg.de/v2/: dial tcp: lookup registry.manuel-laufenberg.de on 10.202.244.1:53: read udp 10.202.244.1:53: i/o timeout
 v1 ping attempt failed with error: Get https://registry.manuel-laufenberg.de/v1/_ping: dial tcp: lookup registry.manuel-laufenberg.de on 10.202.244.1:53: read udp 10.202.244.1:53: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry.manuel-laufenberg.de` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry.manuel-laufenberg.de/ca.crt`

My server ip is **80.237.233.25** but somehow it's ending up trying to connect to **10.202.244.1**. Did anyone encounter this issue before?

Cheers & Thanks,
Santo

**Comment by dmp42** [comment]
Your DNS server is not functioning properly, or is not reachable by your docker engine.

`10.202.244.1:53: i/o timeout`

Are you running boot2docker? or machine?

If yes, I would suggest restarting the VM.

**Comment by SantoDE** [comment]
hey @dmp42 ,

currently docker is running on a linux vm. Restarting this VM did sadly not fix the issue :(

Regards,
Manuel

**Comment by dmp42** [comment]
@SantoDE then you have to check your VM networking configuration. Or host DNS configuration.
Top of the head:

 * SSH into your VM, and try to dig / curl something
 * check the VM network settings
 * cat /etc/hosts in the VM
 * cat /etc/hosts in the host

Ultimately, the error message gives you the answer: your VM tries to use 10.202.244.1 as a DNS resolver, and this server is not reachable from inside the VM.

**Comment by SantoDE** [comment]
Welp, I don't get it. I checked everything. I can't see where 10.202.244.1 comes from. Additionally, accessing sites via curl from the VM's work as well so DNS resolving in generall is fine :/

**Comment by SantoDE** [comment]
It was a problem on my local system. Fixed therefore :)
