### ISSUE TITLE
run registry-v2 container failed

### ISSUE THREAD

**Issue by workhardcc** [docker/distribution#1524]
hi everyone,
1. generated tls certificate by myself
```
openssl req \
     -newkey rsa:2048 -nodes -keyout certs/domain.key \
     -x509 -days 365 -out certs/domain.crt
```
2.download source code then modify cmd/registry/config.yml, add code in "http" section as blow:
```
    tls:
        certificate: certs/domain.crt
        key: certs/domain.key
```
3. docker build -t secure_registry .
4.docker run -p 5000:5000 registry_local:latest
then error occur:

> time="2016-03-14T04:58:28.822971793Z" level=fatal msg="open /search/registry/distribution-2.0.0/certs/domain.crt: no such file or directory" environment=development instance.id=ffa0e1a5-8b38-4cc5-a3bf-5247d9f8cd8e service=registry version="-extld=gcc"

i'm sure  "/search/registry/distribution-2.0.0/certs/domain.crt" really exist!
how can i fix it ?  
Thanks!

**Comment by dmp42** [comment]
Why don't you just try to follow the documentation? You don't need to build your own image.

https://github.com/docker/distribution/blob/master/docs/deploying.md

Nevertheless, from what you did here, it's quite likely your certificate is absent from the container you built.

Running this command:
`docker run registry_local:latest ls /search/registry/distribution-2.0.0/certs/domain.crt` will tell.

**Comment by conradkleinespel** [comment]
Just in case someone has the same problem and lands on this issue. In my case, this was because I had my volume and registry config set to:
```
/etc/letsencrypt/live/conradk.com:/certs
...
REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
```

But the `/etc/letsencrypt/live/xxx` folders contain symlinks. Symlinks to files that may not be present in the container. This will work:
```
/etc/letsencrypt:/certs
...
REGISTRY_HTTP_TLS_CERTIFICATE: /certs/live/conradk.com/fullchain.pem
REGISTRY_HTTP_TLS_KEY: /certs/live/conradk.com/privkey.pem
```
