### ISSUE TITLE
Error delete image from Docker Registry using API v2

### ISSUE THREAD

**Issue by CarTerr** [docker/distribution#1529]
#I'm trying to remove images from Docker Registry using API v2 folloving сommand:
`curl -k -v -u 'docker:sdf' -X DELETE https://localhost:5000/v2/bkf/ebbg/manifests/1`

But I get next error:
```
> DELETE /v2/bkf/ebbg/manifests/1 HTTP/1.1
> Authorization: Basic ZG9ja2VyOkRrZmxidmJoMjAw==
> User-Agent: curl/7.35.0
> Host: localhost:5000
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< Date: Mon, 14 Mar 2016 07:56:13 GMT
< Content-Length: 98
<
{"errors":[{"code":"DIGEST_INVALID","message":"provided digest did not match uploaded content"}]}
```
Command:
`curl -k -u 'docker:sdf' -X GET https://localhost:5000/v2/_catalog`

show
`{"repositories":["bkf/ebbg"]}`

comand
`curl -k -u 'docker:sdf' -X GET https://localhost:5000/v2/bkf/ebbg/tags/list`

show
`{"name":"bkf/ebbg","tags":["32","1","latest","12","33","34"]}`

In what may be a problem or where did I go wrong?

**Comment by RichardScothern** [comment]
You can only delete images by digest.  Please see the API:
https://github.com/docker/distribution/blob/master/docs/spec/api.md#deleting-an-image

**Comment by CarTerr** [comment]
Where can I see the value of digest parameter for image bkf/ebbg:1 ?

**Comment by sjiveson** [comment]
Use a curl command like this:
`curl -k -I -H Accept:\* https://<some_url_or_ip>:5000/v2/<image_name>/manifests/<tag_name>`

Then use the value of either of these headers (including the `sha256:` part if present) - they should be the same:
- Docker-Content-Digest
- Etag

**Comment by aamagzoub** [comment]
> curl -k -I -H Accept:\* https://<some_url_or_ip>:5000/v2/<image_name

From your command, I am getting the following output:

HTTP/1.1 401 Unauthorized
Server: nginx/1.21.3
Date: Mon, 27 Sep 2021 19:25:17 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 149
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Basic realm="Registry-Realm"
X-Content-Type-Options: nosniff

No digest !!

**Comment by aamagzoub** [comment]
> Use a curl command like this:
> `curl -k -I -H Accept:\* https://<some_url_or_ip>:5000/v2/<image_name>/manifests/<tag_name>`
> 
> Then use the value of either of these headers (including the `sha256:` part if present) - they should be the same:
> 
> * Docker-Content-Digest
> * Etag

After running the command, I am getting the following error:

`{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown"}]}`

Any advice ?

**Comment by sajayantony** [comment]
What is your accept header?  I believe the default might down convert to `Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws` which will give you a digest that might be the one that the client might have pushed. For e.g. below request with `Accept: application/vnd.docker.distribution.manifest.v2+json` 

```bash
➜ curl -v  -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
    http://localhost:5000/v2/hello-world/manifests/latest
...
> GET /v2/hello-world/manifests/latest HTTP/1.1
> Accept: application/vnd.docker.distribution.manifest.v2+json
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 525
< Content-Type: application/vnd.docker.distribution.manifest.v2+json
< Docker-Content-Digest: sha256:f54a58bc1aac5ea1a25d796ae155dc228b3f0e11d046ae276b39c4bf2f13d8c4
< Docker-Distribution-Api-Version: registry/2.0
< Etag: "sha256:f54a58bc1aac5ea1a25d796ae155dc228b3f0e11d046ae276b39c4bf2f13d8c4"
< X-Content-Type-Options: nosniff
< Date: Wed, 22 Sep 2021 23:34:15 GMT
<
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1469,
      "digest": "sha256:feb5d9fea6a5e9606aa995e879d862b825965ba48de054caab5ef356dc6b3412"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2479,
         "digest": "sha256:2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54"
      }
   ]
* Connection #0 to host localhost left intact
}
```

Check if you can access the manifest using the digest - 
```bash
➜ curl http://localhost:5000/v2/hello-world/manifests/sha256:f54a58bc1aac5ea1a25d796ae155dc228b3f0e11d046ae276b39c4bf2f13d8c4
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1469,
      "digest": "sha256:feb5d9fea6a5e9606aa995e879d862b825965ba48de054caab5ef356dc6b3412"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2479,
         "digest": "sha256:2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54"
      }
   ]
}
```
