### ISSUE TITLE
Images names with double '--' not accepted by registry 2.x

### ISSUE THREAD

**Issue by MichaelBitard** [docker/distribution#1543]
$ docker version:

    Client version: 1.7.1
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 786b29d
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 786b29d
    OS/Arch (server): linux/amd64

$ docker info:

    Containers: 3
    Images: 352
    Storage Driver: aufs
     Root Dir: /data/docker/aufs
     Backing Filesystem: extfs
     Dirs: 358
     Dirperm1 Supported: false
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.13.0-63-generic
    Operating System: Ubuntu 14.04.3 LTS
    CPUs: 4
    Total Memory: 15.67 GiB
    Name: sfr0073cu
    ID: EHKD:4764:35XA:SR4I:W64Y:3CTC:KJXD:BHDQ:6FZ5:3S7S:N32J:IWGK
    WARNING: No swap limit support

$ docker exec registry registry -v: 

    registry github.com/docker/distribution v2.3.1

We are migrating from our old registry (https://github.com/docker/docker-registry) to this one.
It seems that images containing double hyphens are not accepted anymore.

Steps to reproduce : 

    $ docker tag alpine:3.3 my_registry:5000/alpine--test:3.3
    $ docker push my_registry:5000/alpine--test:3.3
    The push refers to a repository [my_registry:5000/alpine--test] (len: 1)
    7b525b316cca: Image push failed 
    Error pushing to registry: mux: variable "alpine--test" doesn't match, expected "^(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*$"

We can see that alpine--test doesn't match the regexp, but we couldn't find in the documentation that multiple consecutive hyphens (and underscores) are forbidden

**Comment by zhouhaibing089** [comment]
There is a documentation: https://github.com/docker/distribution/blob/master/docs/spec/api.md

> A repository name is broken up into path components. A component of a repository name must be at least one lowercase, alpha-numeric characters, optionally separated by periods, dashes or underscores. More strictly, it must match the regular expression `[a-z0-9]+(?:[._-][a-z0-9]+)*`.
