### ISSUE TITLE
Problems for new gc function

### ISSUE THREAD

**Issue by qinghua** [docker/distribution#1548]
Hi, I tried the new [gc](https://github.com/docker/distribution/blob/master/docs/gc.md) function, it works quite well. However, there is an issue which will cause some problems. Here are reproduce steps:

1. Use a clean folder(/var/lib/registry/) as docker registry data volumn
2. Push an image(microbox/etcd:2.1.1) so the folder will have some files
3. Call "DELETE /v2/<name>/manifests/<reference>" so the link file in _manifests folder will be deleted
4. Stop the registry
5. Call gc, so the data files in the blobs will be deleted, we get the space back, yeah, but still some small files exist in _layers/signatures/tags
6. Start the registry
7. Push the same image(microbox/etcd:2.1.1) again, everything works well
8. Docker pull the image, an error occurs: "Error: image microbox/etcd:2.1.1 not found"
9. Docker logs registry, see log: "error fetching signature \"sha256:ea06c35e1e17c4010887dc3cb77020d030dbd528113997ccca80b12423460df1\": unknown blob". This is the old signature which is not deleted by the delete/gc actions above
10. Run gc again, same error occurs
11. Delete the old signature link file mentioned by the error message, the error will gone

My questions:

1. Shall we have some way to delete the old signature link files?
2. How about the _layers/tags files mentioned in step 5? Shall we delete them as well?
3. After step 3 or 6, if we call "GET /v2/_catalog" or "GET /v2/microbox/etcd/tags/list", we'll still get the deleted image. Is that an defect?

The storage structure:
```
/var/lib/registry/                                
└── docker                                
    └── registry                                
        └── v2                                
            ├── blobs                                
            │   └── sha256                                
            │       ├── 2d                                
            │       │   └── 2d43d4d470877e2666b859f45aa76dcb1742cc90f7185bd5378e994711bcf2bd                                
            │       │       └── data                           These data files can be deleted by gc
            │       ├── ...                                    These data files can be deleted by gc
            └── repositories                                
                └── microbox                                
                    └── etcd                                
                        ├── _layers                                
                        │   └── sha256                                
                        │       ├── 6a3fbc2823df5d562b517d13cae90c307dcb8f17ae9ae814de967d47a4a5cab7                                
                        │       │   └── link                   This file will always exist, but no problem for now
                        │       ├── ...                                
                        ├── _manifests                                
                        │   ├── revisions                                
                        │   │   └── sha256                                
                        │   │       └── 2d43d4d470877e2666b859f45aa76dcb1742cc90f7185bd5378e994711bcf2bd                                
                        │   │           ├── link               This file can be deleted by DELETE /v2/<name>/manifests/<reference>
                        │   │           └── signatures                                
                        │   │               └── sha256                                
                        │   │                   └── ea06c35e1e17c4010887dc3cb77020d030dbd528113997ccca80b12423460df1                                
                        │   │                       └── link   This file will always exist, which cause the problem
                        │   └── tags                                
                        │       └── 2.1.1                                
                        │           ├── current                This file will always exist, but no problem for now
                        │           │   └── link                                
                        │           └── index                                
                        │               └── sha256                                
                        │                   └── 2d43d4d470877e2666b859f45aa76dcb1742cc90f7185bd5378e994711bcf2bd                                
                        │                       └── link       This file will always exist, but no problem for now
                        └── _uploads                                
```

**Comment by RichardScothern** [comment]
@qinghua : we are moving away from signatures in the distribution model.  Docker 1.10 and Registry 2.3 use the new manifest format which does not use signatures.  If you are using older docker versions, you can workaround this problem with the following section in the config file.
```
 compatibility:
   schema1:
      disablesignaturestore: true
```

That being said this very scenario was brought up in the PR and should have been implemented.  So I will say this is a bug.

As for 2. or 3. it is possible to push a manifest by digest (not tag), in which case the repository will exist but no tags are available.

**Comment by qinghua** [comment]
@RichardScothern Thanks for your quick response! I'm using docker 1.9.0. I tried the `disablesignaturestore` workaround with both Registry 2.2 and 2.3, but the Registry will still write the signature link files. As a result, the pull will still fail after a second push.

**Comment by qinghua** [comment]
@RichardScothern I upgraded docker version to 1.10.3 and did the following test:

For Registry 2.3, the signature files will not be there, and everything works quite well.
For Registry 2.2, no matter configure `disablesignaturestore` or not, signature files are still there and get the same error.

**Comment by RichardScothern** [comment]
@qinghua : `disablesignaturestore` is only supported in 2.3.1.  With this enabled, even if signatures exists (from old client uploads) the registry will not attempt to read them on pull.

**Comment by qinghua** [comment]
@RichardScothern Sounds good. Since it's a bug, I'll leave it open here. Please close it if you think it's fixed.

**Comment by RichardScothern** [comment]
Closing since the signature store workaround is sufficient.
