### ISSUE TITLE
Propose to have a configurable Key ID for Token Auth

### ISSUE THREAD

**Issue by overmike** [docker/distribution#1549]
Today, the Key ID is generated internally by go/libtrust, which is something can't be changed or easily find out from outside e.g. the certificate owner.
And as this Key ID in JWT header is required to match the internal generated Key ID within registry, I would suggest to have it configurable in Registry rather than enforce a special algorithm.

**Comment by dmcgowan** [comment]
The Key ID was intended to be a cryptographically secure fingerprint as generated by libtrust. Do you have other fingerprint methods you are requesting be supported? Support for additional fingerprint methods could be added to the auth package, but I am not convinced the registry could be strict enough about enforcing a cryptographically secure Key ID if it allowed the expected fingerprint to be passed in as an opaque value and matched directly with the JWT header.  If the current Key ID mechanism is too rigid, I would suggest generating JWTs using either the `x5c` or `jwk` header.

Additional information about the use case you are trying to support would be helpful to fully understand your issue.

**Comment by overmike** [comment]
In my user case, we have an identity service written in Java, and I was fail to find any library which provide the same algorithm (at least from my knowledge). I actually implemented the algorithm in java for the past few days.
And I also tried to use x5c, but this somewhat double the size of the JWT which I want to minimize. Also tried x5t but unfortunately after code reading, it is not supported by libtrust (or other go library)

KID seems to me only for lookup process within a set of JWK, and doesn't affect signature verification in JWS. It would be great if you can point me to some readings, thanks a lot.

Again, I have solved this by implement the same algorithm in the identity service

**Comment by overmike** [comment]
let's close this issue, if there is secure concern
