### ISSUE TITLE
Allow inclusion of custom storagedrivers in Dockerfile

### ISSUE THREAD

**Issue by BrianBland** [docker/distribution#155]
With the IPC storagedriver subsystem currently disabled, I'd like to suggest a supported method for building the registry with the inclusion of custom storagedrivers. Perhaps we could designate a directory inside the Dockerfile for additional drivers and automatically generate import statements in the `cmd/registry` main package for go packages inside the driver directory when compiling the registry binary. This could allow users to create and support storagedrivers without having to fork or add the drivers to the main repository.

**Comment by stevvooe** [comment]
An interesting way of doing this was suggested by @progrium. The concept works by adding a `plugins.go` file alongside the main package. I'm sure we can come up with a clever way of resolving such a file to capture side-effect imports.

**Comment by progrium** [comment]
And you might want to put `plugins.go` (or maybe best to call it `extensions.go`) in the root for users to find. It can be used to side-effect import any custom drivers in the future. But it's a great pattern that doesn't require any extra tooling.

**Comment by stevvooe** [comment]
@progrium Thanks!

@BrianBland Here is the demo, for reference: https://github.com/progrium/plugin-demo. The approach is perfectly compatible with our extension mechanisms in auth and storagedriver.
