### ISSUE TITLE
how to upload a tar image file directly to the private registry by rest api(registry v2)?

### ISSUE THREAD

**Issue by yanqicui** [docker/distribution#1551]
I study the /v2/<name>/blobs/uploads /v2/<name>/blobs/uploads/<uuid>  etc.
and I read the stackflow method:
http://stackoverflow.com/questions/33380605/error-uploading-image-into-docker-registry-using-api-v2

but i got the error:blob upload invalid
is there any example to upload a tar file into registry v2(use curl)?
thank you!

**Comment by dmp42** [comment]
Answered the SO question.
