### ISSUE TITLE
What are the options for Token Auth?

### ISSUE THREAD

**Issue by duyanghao** [docker/distribution#1567]
As described below:
https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md

According to my research, the Docker Registry v2 authentication via central service has not been implemented, after all, it does not supply a achievement of  auth server.So, I want to know is the support for auth server still in progress or Is there any achievement of that can you recommend?

**Comment by duyanghao** [comment]
I find a achievement online:
https://github.com/cesanta/docker_auth

Do you think the repo practicable?

**Comment by ybshen** [comment]
As far as i known,some companys have been used docker_auth as oauth server.Perhaps，you can try out portus

**Comment by duyanghao** [comment]
thanks @ybshen ,I am using docker_auth now
