### ISSUE TITLE
Docker push failed:  unexpected EOF

### ISSUE THREAD

**Issue by hustcat** [docker/distribution#1568]
``` sh
# docker push myregistry.com:5000/google_containers/skydns:2015-10-13-8c72f8c
The push refers to a repository [myregistry.com:5000/google_containers/skydns]
5f70bf18a086: Layer already exists 
f9b42de57572: Layer already exists 
3c35e36d8df2: Layer already exists 
5e868bdcb028: Layer already exists 
7f02483a9752: Pushing [==================================================>]  2.43 MB/2.43 MB
unexpected EOF
```

docker/distribution version:

``` sh
# docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

# bin/registry --version
bin/registry github.com/docker/distribution v2.2.1-79-g93d9070
```

docker daemon error log:

```
time="2016-03-28T20:56:54.123551972+08:00" level=error msg="Upload failed, retrying: unexpected EOF"
```

distribution log:

```
time="2016-03-28T20:51:57+08:00" level=info msg="response completed" go.version=go1.5.2 http.request.host="10.x.x.x:5000" http.request.id=c0a2fbf8-7549-481c-a4d9-58868e00102a http.request.method=POST http.request.remoteaddr="10.x.x.x:37077" 

http.request.uri="/v2/google_containers/skydns/blobs/uploads/" http.request.useragent="docker/1.10.1 go/go1.5.3 git-commit/9e83765 kernel/3.10.83-1-tlinux2-0021.tl1 os/linux arch/amd64" http.response.duration=4.476794ms http.response.status=202 http.response.written=0 instance.id=3fdcab9e-d54e-438a-ab02-97448f1c2bb3 version=v2.2.1-79-g93d9070 

10.x.x.x - - [28/Mar/2016:20:51:57 +0800] "POST /v2/google_containers/skydns/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.10.1 go/go1.5.3 git-commit/9e83765 kernel/3.10.83 os/linux arch/amd64"
```

**Comment by aaronlehmann** [comment]
This looks like it might be https://github.com/docker/docker/issues/20104.

Can you please try rebuilding or repulling this image and see if that corrects the problem?

Also, I would recommend upgrading to Docker 1.10.3, as a few other bugs have been fixed since 1.10.1.

**Comment by hustcat** [comment]
It's easy to repeat:
```sh
# docker pull gcr.io/google_containers/skydns:2015-10-13-8c72f8c
Pulling repository gcr.io/google_containers/skydns
763c92e53f31: Pull complete 
cf2616975b4a: Already exists 
6ce2e90b0bc7: Already exists 
8c2e06607696: Already exists 
d522167467be: Already exists 
0513e8f2dfa8: Pull complete 
60778d45afba: Pull complete 
cbb6218956e4: Pull complete 
Status: Downloaded newer image for gcr.io/google_containers/skydns:2015-10-13-8c72f8c
gcr.io/google_containers/skydns: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.

# docker tag gcr.io/google_containers/skydns:2015-10-13-8c72f8c dbyin/skydns:2015-10-13-8c72f8c

# docker push dbyin/skydns:2015-10-13-8c72f8c
The push refers to a repository [docker.io/dbyin/skydns]
5f70bf18a086: Layer already exists 
f9b42de57572: Layer already exists 
3c35e36d8df2: Layer already exists 
5e868bdcb028: Layer already exists 
7f02483a9752: Pushing [==================================================>]  2.43 MB/2.43 MB
unexpected EOF
```

It seem like that be related with image.

**Comment by dmp42** [comment]
@hustcat just tested, works for me.

I'm using docker 1.10.3

**Comment by aaronlehmann** [comment]
@hustcat: When you pull the image, some of the layers show `Already exists`. One of these could be corrupted by docker/docker#20104. Can you try `docker rmi gcr.io/google_containers/skydns` and any other tags referring to this image before pulling it? If you still see `Already exists`, you may have to delete other images using the layer.

**Comment by joestubbs** [comment]
I'm getting this error every time I try to push an image to the docker hub. I'm using 1.10.3.

```
$ docker push jstubbs/haproxy
The push refers to a repository [docker.io/jstubbs/haproxy]
90dcebc4e994: Layer already exists 
ee3061cab103: Layer already exists 
7ae372a7a9d1: Layer already exists 
8359539caf13: Layer already exists 
773370d5317b: Layer already exists 
e4a8278f8e93: Layer already exists 
66604ebcc053: Layer already exists 
61dd84ea3990: Layer already exists 
1e9bb47110db: Layer already exists 
66e102bb4814: Layer already exists 
7b73980227ef: Layer already exists 
5f70bf18a086: Layer already exists 
37ee47034d9b: Pushing 1.895 kB/1.895 kB
528c8710fd95: Pushing      0 B/194.5 kB
1154ba695078: Pushing 90.77 MB/188.1 MB
unexpected EOF

$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

```

**Comment by joestubbs** [comment]
I was just able to push successfully with docker 1.9:
```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by aaronlehmann** [comment]
@joestubbs: Have you tried rebuilding or repulling all the layers of the image like I suggested in the comments above?

**Comment by joestubbs** [comment]
@aaronlehmann sorry, I probably don't understand the suggestion. I was building the image locally, and it did not (at the time) exist on the docker hub. Are you suggesting I re-pull the intermediate layers that were already on the hub?

**Comment by aaronlehmann** [comment]
@joestubbs: Yes. Delete those intermediate layers and re-pull them.

**Comment by urzds** [comment]
I am experiencing the same issue. When I try to push an image I built locally, I see:
```
5835c4bab998: Layer already exists 
12640cac29c3: Pushed 
8b5286d61c3f: Pushed 
b41f356f4ecb: Pushing [==================================================>] 300.2 MB
5f70bf18a086: Layer already exists 
6c3eb4525275: Pushing [==================================================>] 129.4 MB
unexpected EOF
```

However, docker says these images do not exist:
```
# docker rmi 5f70bf18a086
Failed to remove image (5f70bf18a086): Error response from daemon: No such image: 5f70bf18a086:latest
# docker rmi 5835c4bab998
Failed to remove image (5835c4bab998): Error response from daemon: No such image: 5835c4bab998:latest
```

I assume the docker command to delete an image layer is not `rmi`?

**Comment by aaronlehmann** [comment]
@urzds: Unfortunately there's no direct way to delete a layer. Layers are used by one or more images, and to delete a layer, you have to delete all the images that use it.

The simplest way, if all the images on your machine can be easily replaced, is to clear /var/lib/docker and start over. Otherwise, you'll need to keep deleting overlapping images until `docker build` actually replaces all the layers in the image. It should be easy to tell if it is creating new layers or not, because it says ` ---> Using cache` whenever it reuses an existing layer.

**Comment by urzds** [comment]
@aaronlehmann Is there a way to figure out which images use a certain layer?

**Comment by ruiztulio** [comment]
Hi, I had the same issue. Try to update from 1.10.2 to 1.10.3 and the same error. The only way I could "go around" was building the image again in a different server the push/pull to replace it

The error was shown even trying to do a pull from the base image used for my container:
![EOF](http://screenshots.vauxoo.com/tulio/02012310616-2BGtNPIYTb.jpg)

I'm using: Docker version 1.10.3, build 20f81dd
Kernel: 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

I post the info here in case someone else have the same issue and nothing else works like in my case.

**Comment by pgrm** [comment]
I've commited a local change (can't really rebuild the image) and am seeing the same issue with docker `1.10.3` and the latest `1.11.0`

I'm trying to push into a private repository in docker hub. I've tried a new tag on an existing one as well as a completely new repository, both fail the same way

**Comment by kopax** [comment]
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:17:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:17:17 2016
 OS/Arch:      linux/amd64


Same issue

**Comment by acron0** [comment]
I'm getting this same issue when trying to push to docker hub.

```
 level=error msg="Upload failed, retrying: unexpected EOF"
```

**Comment by dmcgowan** [comment]
@kopax @acron0 were these images originally pulled or created in a version of Docker older 1.10? Have you tried the suggestions @aaronlehmann? If you have and are still having an issue, please open up a new issue with providing the necessary logs. This issue has been identified as an issue which has already been fixed https://github.com/docker/docker/issues/20104.

**Comment by pgrm** [comment]
@dmcgowan my container is ~1,5-2 years old so it has been created with a version prior 1.10, but I can't really re-create it, is there anything else I could try?

**Comment by dmcgowan** [comment]
@pgrm: the suggestion is to remove the problematic images and repull the original or rebuild. If that does not work for you let me know and can offer other suggestions.

**Comment by koder-ua** [comment]
ᐅ docker push koderua/wally
The push refers to a repository [docker.io/koderua/wally]
a510afa9a1af: Pushed 
2ddf1db20426: Pushed 
277bbc4efeb2: Pushed 
7a0cf22863c3: Pushed 
b3e1b309431d: Pushed 
f98d80f80e6a: Pushed 
5f70bf18a086: Pushing 
1debe0af080b: Retrying in 12 seconds 
3a669db069a2: Retrying in 14 seconds 
d0df3aaac661: Pushing [==================================================>] 190.9 MB
unexpected EOF

ᐅ docker --version
Docker version 1.13.0, build 49bf474

ᐅ docker save -o /tmp/wally.tgx koderua/wally                                                                                                                                                           
Error response from daemon: unexpected EOF

**Comment by MaRuifeng** [comment]
@urzds I understand this is pretty old. But if you are interested, I've got this stackoverflow [post ](https://stackoverflow.com/questions/43070640/how-to-link-docker-images-to-their-composing-layers-on-the-disk)that explains how to determine which layers are used by which images.

**Comment by stevvooe** [comment]
Let's move this issue to `moby/moby` so that it can be appropriately triaged. There are a lot of possible causes for `unexpected EOF` on push and it will help to divide these by the conditions that led to them.

**Comment by arthar360** [comment]
I had the same issue. I discovered that the containers were not shutdown while I did the commit. docker stop, docker commit, docker tag and then docker push solved the issue

**Comment by stevencohn** [comment]
Hi, I’m seeing the something similar trying to push a Linux (LCOW) container. Even after the push command fails and stops, dockerd continues to try in the background forever. A system prune won’t event stop it. Only reinstalling Docker for Window and manually deleting the cache folder will stop it.

I've tried rebuilding the image. The image is a relatively thin extension of nginx, adding Web content.

The image works locally. But I can't push it.

**Comment by ghassencherni** [comment]
I got the same error , my fault was simply that I have a wrong path, ECR repo dosnet' exist for my case. Check your target repo
