### ISSUE TITLE
Propose future approach to namespaces

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#157]
This issue captures the need to discuss the future of namespaces within docker and docker/distribution.

What are the goals of namespaces?
What are they?
How do they work?
What changes need to be made in the near future?
Are current specifications in line with goals?

We'll discuss during upcoming distribution meetings.

Closes #188, Connects to #179.

**Comment by dmcgowan** [comment]
This definition should also cover what is needed for #80, the discovery of registry endpoints given a namespace.

**Comment by stevvooe** [comment]
@dmcgowan Agreed. It should outline the framework under which a proposal like #80 should be implemented under.
