### ISSUE TITLE
Error in deleting repository in a private registry V2 

### ISSUE THREAD

**Issue by joda70** [docker/distribution#1573]
I would like to know the status of the delete operation implementation in the API v2 of docker registry.
I am able to get information up to manifest reference but when I try the delete operation I obtain:

 curl -v --cacert /usr/local/share/ca-certificates/ca.crt -u 'user:pwd' -X GET https://hostname/v2/name/manifests/reference
... (the output report digest information)

 curl -v --cacert /usr/local/share/ca-certificates/ca.crt -u 'user:pwd' -X DELETE https://hostname/v2/name/manifests/reference
... 

{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}
* Connection #0 to host hostname left intact

**Comment by ybshen** [comment]
you can try to add REGISTRY_STORAGE_DELETE_ENABLED=true when start the registry

**Comment by bhanushrestha** [comment]
@ybshen  I am sorry if this sounds too simple, but could you please specify how or where do we add that 

 `REGISTRY_STORAGE_DELETE_ENABLED=true`
flag when we start the registry. Is it some sort of environment variable or command line flag?

**Comment by jheiss** [comment]
@bhanushrestha See https://docs.docker.com/registry/configuration/ for details. But yes, REGISTRY_STORAGE_DELETE_ENABLED would be an environment variable that you would pass via the -e flag to docker run.

**Comment by Rukeith** [comment]
@jheiss Sorry, I might miss. But I didn't found the variables `REGISTRY_STORAGE_DELETE_ENABLED ` in document. There is configuration file.

**Comment by jheiss** [comment]
The registry accepts configuration settings either via a file or via environment variables. So the environment variable `REGISTRY_STORAGE_DELETE_ENABLED=true` is equivalent to this in your config file:

```yaml
storage:
  delete:
    enabled: true
```

**Comment by manishtomar** [comment]
@sosensible Did you try deleting image after enabling that environment variable? https://docs.docker.com/registry/spec/api/#deleting-an-image

**Comment by romangallego** [comment]
I just went through the same issue and want to confirm that the solution suggested about enabling that environment variable in the config file works.
storage:
  delete:
    enabled: true

**Comment by mickours** [comment]
> When I try to add the environment variable into my docker-compose.yaml it never seems to respond.
> 
> ```
>     environment:
>       REGISTRY_STORAGE_DELETE_ENABLED: "true"
> ```
> 
> Changing it to equals failed as well as changing it to the number 1. It also would not work without quotes for text.
> 
> ```
>     environment:
>       REGISTRY_STORAGE_DELETE_ENABLED: 1
> ```

This is because you are using a map value instead of a list which the correct format for docker compose.

This is the working version:
```yaml
    environment:
    - REGISTRY_STORAGE_DELETE_ENABLED=true
```

**Comment by LiohMoeller** [comment]
In docker-compose.yaml? Nope.
