### ISSUE TITLE
Polling for changed tags

### ISSUE THREAD

**Issue by lwander** [docker/distribution#1574]
I'm trying to discover which tags have been created/changed/deleted in a docker registry, regardless of who's hosting the registry. Dockerhub, Quay, and GCR all have different webhooks, and AFAIK, private self-hosted registries have none. This leaves me with first reading all tags in a repository, and then pulling down each tag's manifest to read its digest. This is a lot of overhead. Is there something in the v2 API that I'm missing, or is there interest in creating a new endpoint that can list changes to a repository after a given timestamp?

**Comment by cmingxu** [comment]
+1

**Comment by dmp42** [comment]
Use the notifications API https://github.com/docker/distribution/blob/master/docs/notifications.md

https://github.com/docker/distribution/pull/1522

**Comment by lwander** [comment]
@dmp42 that seems to work only for registries I'm hosting, no?

**Comment by dmp42** [comment]
@lwander that's correct.

If you want integration with specific providers (gcr, quay, etc) and/or that they allow you to consume notifications, you need to ask them.

**Comment by lwander** [comment]
That's what I'm trying to avoid. 

The issue was raised asking if there could be a more sensible provider agnostic means to see digest changes. 

Perhaps `v2/<name>/tags/list?digests=true` would display each tag in a repo alongside its most recent digest. In fact, I'm not sure why this isn't the default behavior as the tag alone isn't enough to uniquely identify an image.

**Comment by dmp42** [comment]
@lwander I understand the frustration having to deal with providers.
Now, the one recommended workflow is really to consume a dedicated search API (built on top of notifications), or notifications directly.

Providing information about content is really the job of an index, and adding this as a core API would raise many issues (performance to boot - you would have to stat many files to build the list you are asking for).

It's also a can of worm, with regard to eventual consistency (which in most cases - S3, Swift, Rados, Azure does NOT give you any guarantee that what you just read reflect the "truth").

I wish I was able to provide a more helpful answer, but yes talking to providers to get them to forward notifications (or a capable index on top of that) is the only sane approach.

**Comment by lwander** [comment]
Thanks for the insight, the restrictions make sense when you phrase them like this.
