### ISSUE TITLE
How to get image size from docker distribution?

### ISSUE THREAD

**Issue by ybshen** [docker/distribution#1575]
i pushed a image from local to docker registry,How to get image size from docker distribution?

**Comment by dmp42** [comment]
You can get the compressed size of the artifacts (eg: layers) by HEAD-ing them.

**Comment by ybshen** [comment]
Such a scenario is：
1、A user push a local docker image with docker push command
2、I want get the user's image size with program
3、I try to get the image size with Docker Distribution'api and Docker Distribution's notifications,but it can not seems to get the image size.I would like to ask that is it the accumulation of all layers‘size?
thanks

**Comment by RichardScothern** [comment]
@ybshen : as @dmp42 mentioned, you can `HEAD` resources in the registry to get size data.  For the total size of an image, you can get the manifest and `HEAD` all of the blobs to get the sizes and sum them.

Two caveats: 1. blobs are shared among images, so the total size of all images can be > total size of data in the registry. 2. the registry stores layers as gzipped tar files and these sizes are smaller than the sizes reported in the docker engine.

**Comment by ybshen** [comment]
thanks

**Comment by duyanghao** [comment]
When i run docker images, the result shows belows:
the digest for repository`:dbyin/busybox:latest` is `sha256:9e301a362a270bcb6900ebd1aad1b3a9553a9d055830bdf4cab5c2184187a2d1`
```
[root@cn-sh-radosgw-test1 ~/V2_Registry]# docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
registry.com/dbyin/busybox   latest              9e301a362a27        7 months ago        364.3 MB
```

but I send request` /v2/dbyin/busybox/blobs/latest` , the result field` fsLayers` does not contain the top layer digest:`sha256:9e301a362a270bcb6900ebd1aad1b3a9553a9d055830bdf4cab5c2184187a2d1`
```
{
   "schemaVersion": 1,
   "name": "dbyin/busybox",
   "tag": "latest",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:c0a04912aa5afc0b4fd4c34390e526d547e67431f6bc122084f1e692dcb7d34e"
      }
   ],
   "history": [
      {
         "v1Compatibility": "{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"5f8e0e129ff1\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":[\"sh\"],\"Image\":\"cfa753dfea5e68a24366dfba16e6edf573daa447abf65bc11619c1a98a3aff54\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"container\":\"7f652467f9e6d1b3bf51172868b9b0c2fa1c711b112f4e987029b1624dd6295f\",\"container_config\":{\"Hostname\":\"5f8e0e129ff1\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) CMD [\\\"sh\\\"]\"],\"Image\":\"cfa753dfea5e68a24366dfba16e6edf573daa447abf65bc11619c1a98a3aff54\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"created\":\"2015-09-21T20:15:47.866196515Z\",\"docker_version\":\"1.8.2\",\"id\":\"bc315f8368c625be080de23e37c18bd7e555787987f907ccaf0b9bd1b69d5fe8\",\"os\":\"linux\",\"parent\":\"77106241d10a8ed96dc42f690453f89ec95890b1494ccac18bac69065e4b67fa\"}"
      },
      {
         "v1Compatibility": "{\"id\":\"77106241d10a8ed96dc42f690453f89ec95890b1494ccac18bac69065e4b67fa\",\"created\":\"2015-09-21T20:15:47.433616227Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:6cccb5f0a3b3947116a0c0f55d071980d94427ba0d6dad17bc68ead832cc0a8f in /\"]}}"
      }
   ],
   "signatures": [
      {
         "header": {
            "jwk": {
               "crv": "P-256",
               "kid": "IX52:4ALQ:25CN:7ZOK:NHTO:YSQW:DQ5K:44NI:3R63:LQIL:CYJW:PJBN",
               "kty": "EC",
               "x": "8cWKIFvpY0HdzoGd4h9F3Z_MbpzkQrdX5pJVOLBIyzY",
               "y": "ME6g7MwsvOMSouyLOHoMsVFl02jtGn2GiMzGrvYRSdM"
            },
            "alg": "ES256"
         },
         "signature": "xHe9RK9FglNJa7ByB5egjaS3V4tYWYvT_DIXhYxx5i_QoEyUY-AGChLMAmxdKMaehrpsRim2XZKL7SnQ5crVyg",
         "protected": "eyJmb3JtYXRMZW5ndGgiOjE5MjQsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxNi0wNC0yMlQwMzoyOTozNloifQ"
      }
   ]
}
```

So, Is that correct? 
but how can i get the top layer digest from registry v2, and then get the layer size if that is correct?

**Comment by duyanghao** [comment]
Another question is that whether the sequence of `blobSum `in the `fsLayers` field is in accordance with the order of the `layers `generated.

**Comment by ybshen** [comment]
@duyanghao you can try to use the registry v2 above 2.3 version

**Comment by duyanghao** [comment]
Could you answer the above questions? @ybshen

**Comment by ybshen** [comment]
your schemaVersion is v1,the newest registry's schemaVersion is v2.so the json already contains the top layer digest

**Comment by duyanghao** [comment]
what about the docker pull if there is no top layer digest?
I want to know how does docker get the top layer digest if there is no top layer digest in manifests request?

**Comment by duyanghao** [comment]
Maybe i know the reason.If i change the http head as belows:
`Accept: application/vnd.docker.distribution.manifest.v2+json`
then the result shows below:

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/octet-stream",
      "size": 1374,
      "digest": "sha256:9e301a362a270bcb6900ebd1aad1b3a9553a9d055830bdf4cab5c2184187a2d1"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 224153958,
         "digest": "sha256:c0a04912aa5afc0b4fd4c34390e526d547e67431f6bc122084f1e692dcb7d34e"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      }
   ]
}
```

**Comment by ybshen** [comment]
yes,it's all right

**Comment by duyanghao** [comment]
Why there are exist the same digest in the `/v2/<name>/manifests/<tag>` http response? 
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/octet-stream",
      "size": 2398,
      "digest": "sha256:55d1ee70345b7190b59311fc9e783ac7329aeab3478fdea18c521ff9de95565c"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 66390854,
         "digest": "sha256:3b231ed5aa2f1631b3189f15f215fad43e35ec4aa56ee7bb92b9dd1b73ca94cb"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      }
   ]
}
```

The same digest are not valid,just skip that,all the valid layer digests are the nonredundant digests ! 
And the order of the valid digests from bottom to top is in accordance with the order of the layers generated. 
Can i understand in this way? @ybshen @dmp42 @RichardScothern

**Comment by lizrice** [comment]
I nearly raised another issue but I think this is highly related: [schema 1 doc](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-1.md) says "Note:the length of history must be equal to the length of fsLayers and entries in each are correlated by index." 

Is that really the case? Even the example on the same page has a fsLayers length 4 and a history length 2.

**Comment by RichardScothern** [comment]
This issue ("How to get image size from docker distribution?") was answered and closed and has now been conflated with different questions.

@duyanghao let's stick to your questions in #1810 

@lizrice it is really the case.  The documentation is incorrect unfortunately.

**Comment by ZYNCMA** [comment]
Is there a way to get the uncompressed size of images/layers from distribution, which will be the same as SIZE shown in `docker images`?

**Comment by dmcgowan** [comment]
@ZYNCMA not directly through the API. The layers would need to be uncompressed to get the size used by Docker. Note that the image configuration referred to by the manifest does not contain the layer size. Some schema1 manifests will have the size in the v1compatibility section but it is not a required or guaranteed it will be there.

**Comment by duyanghao** [comment]
@ZYNCMA you can not get uncompressed size of images/layers from distribution.but you can certainly get the compressed layer tar size from manifest request.

**Comment by dilin-MS** [comment]
1. For image on Docker Hub:
```bash
curl -s -H "Authorization: JWT " "https://hub.docker.com/v2/repositories/library/<image-name>/tags/?page_size=100" | jq -r '.results[] | select(.name == "<tag-name>") | .images[0].size' | numfmt --to=iec-i
```

2. For image on other registry like Microsoft Container Registry.

* Use `docker manifest inspect` to observe the manifest data, which can give you idea on how to gain the compressed size of the image.
    ```bash
    docker manifest inspect -v <registry-domain>/<image-name> | grep size | awk -F ':' '{sum+=$NF} END {print sum}' | numfmt --to=iec-i
    ```
    To enable `docker manifest inspect`, edit `~/.docker/config.json` file and set `experimental` to `enable`.(Reference: [docker manifest inspect](https://docs.docker.com/engine/reference/commandline/manifest_inspect/))

* Push the image to Docker Hub and you can get the compressed size of the image on Docker Hub website.

* Use `docker save` to save image to a .tar file and then compress it a .tar.gz file.

```bash
docker save my-image:latest > my-image.tar

# Compress the .tar file
gzip my-image.tar

# Check the size of the compressed image
ls -lh my-image.tar.gz
```
