### ISSUE TITLE
Private registry delete manifest  fail: 400 error with DIGEST_INVALID

### ISSUE THREAD

**Issue by mateusdemboski** [docker/distribution#1579]
### The problem:
I trying delete a manifest via HTTP API, but the server always return a "400 Bad Request" with message:
```json
{
  "errors": [
    {
      "code": "DIGEST_INVALID",
      "message": "provided digest did not match uploaded content"
    }
  ]
}
```

### Server Info:
**docker version**
```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:22:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:22:53 2016
 OS/Arch:      linux/amd64
```
**docker info**
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.9 MiB
Name: srv13
ID: KADM:BNID:CGKL:WRS4:CXPI:XXDP:YNBZ:Z3X6:YBBS:DBLX:2AQM:KZEA
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```
**docker exec <registry-container> registry --version**
`registry github.com/docker/distribution v2.3.1`
**command line used to launch Registry**
```
docker run -d \
        -p 5000:5000 \
        --restart=always \
        --name registry \
        -v /mnt/registry/data:/var/lib/registry \
        -v /mnt/registry/auth:/auth \
        -e "REGISTRY_AUTH=htpasswd" \
        -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
        -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
        -v /mnt/registry/certs:/certs \
        -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
        -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
        -e REGISTRY_STORAGE_DELETE_ENABLED=true \
        registry:2
```

**Comment by RichardScothern** [comment]
@mateusdemboski : can you take a look at https://github.com/docker/distribution/pull/1581 and see if these instruction solve your problem.

If that doesn't work, we can debug further.

**Comment by mateusdemboski** [comment]
What should i do with the digest? I need put on head of delete request?
This is my current request:
`curl -X "DELETE" -H "Authorization: Basic <hash_here>" https://url.to.registry:5000/v2/debian/manifests/latest`

**Comment by mateusdemboski** [comment]
Ok, now i can delete the manifest .
To do it i need:

1.  make a "GET" request to endpoint (Example `curl -H "Authorization: Basic ZGlnaXRhbGRlc2s6REQyMDByZWdpc3RyeQ==" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://url.to.registry:5000/v2/debian/manifests/latest`)
2.  Get the header "Docker-Content-Digest" of the reponse 
3.  Make the DELETE (Example `curl -X "DELETE" -H "Authorization: Basic <hash_here>" https://url.to.registry:5000/v2/debian/manifests/<Value of header 'Docker-Content-'Digest'>`)

Is this correct and missing on documentation?

**Comment by RichardScothern** [comment]
@mateusdemboski : that is correct

**Comment by mateusdemboski** [comment]
@RichardScothern but this not realy delete data on disk.
In my tests i push a debian image to repository and when i delete it the free disk space changes only 4Kb...

**Comment by RichardScothern** [comment]
Delete removes references within the repositories.  To recover space you will need to garbage collect:
https://github.com/docker/distribution/blob/master/docs/gc.md

**Comment by mateusdemboski** [comment]
@RichardScothern: More problems... :disappointed:
When i try to run the "garbage collection" the docker output this:
```
# docker run --rm registry:2 garbage-collect /etc/docker/registry/config.yml
configuration error: open garbage-collect: no such file or directory

Usage:
  registry <config> [flags]
Flags:
  -h, --help=false: help for registry
  -v, --version=false: show the version and exit
```

**Comment by RichardScothern** [comment]
:crying_cat_face:  Sorry, I should have mentioned that will be released in 2.4 - which will be out in a week or so.

If you are really curious, you can re-run your above command with the 2.4 release candidate image `distribution/registry:2.4.0-rc.1`.  Do test with the dry run flag first though (`-d`, `--dry-run`)

(it should be available in about half an hour).

**Comment by mateusdemboski** [comment]
@RichardScothern: using registry 2.4.0-rc.1. It finally works. Thanks! :smile:

**Comment by RichardScothern** [comment]
:bow:

**Comment by gl-lamhnguyen** [comment]
@mateusdemboski I was trying to get the correct digest to delete, but when I ran `curl -H "Authorization: Basic <hash_here>" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://url.to.registry:5000/v2/debian/manifests/latest`, it returned a very long json text and I couldn't find any `Docker-Content-Digest`. I wonder what it looks like?

**Comment by mateusdemboski** [comment]
@gl-lamhnguyen you can get the key "Docker-Content-Digest" in the head of response. To show the Headers of response in `curl` you need use the option "-i". Example:
`curl -i -H "Authorization: Basic <hash_here>" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://url.to.registry:5000/v2/debian/manifests/latest`

**Comment by tonicbupt** [comment]
> 1. make a "GET" request to endpoint (Example curl -i -H "Authorization: Basic <hash_here>" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://url.to.registry:5000/v2/debian/manifests/latest)
> 2. Get the header "Docker-Content-Digest" of the reponse
> 3. Make the DELETE (Example curl -X "DELETE" -H "Authorization: Basic <hash_here>" https://url.to.registry:5000/v2/debian/manifests/<Value of header 'Docker-Content-'Digest'>)

I follow this but find that `Docker-Content-Digest` header is not the correct one, why? If I use `docker push hub.registry/app/test:tag` it shows a digest other than the one I get from `HEAD hub.registry/v2/app/test/manifests/tag` ......

**Comment by tonicbupt** [comment]
I'm sorry I didn't add the header `Accept: application/vnd.docker.distribution.manifest.v2+json`, problem solved now.
