### ISSUE TITLE
A little mistake in the docs/building.md#Repeatable Builds

### ISSUE THREAD

**Issue by xwisen** [docker/distribution#1586]
When I use the Makefile with cmd： 
![image](https://cloud.githubusercontent.com/assets/11851988/14168683/480d59ee-f756-11e5-809a-fdb6f1468335.png)
there is a error:
`Makefile:65: *** Please install golint: `go get -u github.com/golang/lint/golint`.  Stop.`
but I have installed `golint` in `$GOPATH/bin`,I think the error is because when using cmd above,the `$GOPATH` is become to `/root/Desktop/gopath/src/github.com/docker/distribution/Godeps/_workspace:/root/Desktop/gopath`.so the bash cann't find `golint` correctly.How to fix this?

**Comment by xwisen** [comment]
The docs/building.md#Developing work good.

**Comment by RichardScothern** [comment]
Add $GOPATH/bin to your $PATH

**Comment by aaronlehmann** [comment]
@RichardScothern: The Makefile doesn't use $PATH to look for golint/godep - it looks in $GOPATH. The code breaks with GOPATH contains more than one path.

I submitted https://github.com/docker/distribution/pull/1587 to fix the docs. There's no reason anymore to change GOPATH when running make.

We should probably also fix the Makefile to stop explicitly using $GOPATH/bin/golint. I don't think there's a good reason to expect it to be in this place; we should just look for it in $PATH like any other binary.

**Comment by aaronlehmann** [comment]
Opened https://github.com/docker/distribution/pull/1588 to look for golint and godep in $PATH instead of trying to build an absolute path with $GOPATH.

**Comment by RichardScothern** [comment]
makes sense :+1:
