### ISSUE TITLE
v2 protocol token authentication with Docker Hub failing

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/distribution#1589]
Hi folks, I'm following the doc at https://docs.docker.com/registry/spec/auth/token/ and trying to obtain a token anonymously and get manifest of some public repository on Docker Hub, say, `ahmet/wagl`. It's a bit hard as the doc doesn't point out URLs for many requests but I'm doing this:

### 1. Try to get manifest:

```
curl -i https://index.docker.io/v2/ahmet/wagl/manifests/latest

HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:ahmet/wagl:pull"
```

###  2. Get token anonymously

```
curl https://auth.docker.io/token\?service\=registry.docker.io\&scope\=repository:ahmet/wagl:pull

{"token":"eyJhbGciOiJFUzI1NiIsInR5c...
```

actually this is where the doc doesn't match the behavior. The response object only has "token" field and not "access_token", "expires_in", "issued_at" fields.

### 3. Fetch manifest:

```
$ TOKEN=eyJhbGciOiJFUzI1NiIsI
$ curl -i -H "Authorization: Bearer $TOKEN" https://index.docker.io/v2/ahmet/wagl/manifests/latest
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:ahmet/wagl:pull",error="invalid_token"
Date: Thu, 31 Mar 2016 19:51:14 GMT
Content-Length: 169
Strict-Transport-Security: max-age=31536000

{"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":[{"Type":"repository","Name":"ahmet/wagl","Action":"pull"}]}]}
```

Any ideas why this might be failing?

**Comment by RichardScothern** [comment]
It works for me.

In step 3 are you abbreviating the token environment variable for clarity? (or actually setting it to `eyJhbGciOiJFUzI1NiIsI`) ?

**Comment by ahmetalpbalkan** [comment]
@RichardScothern darn, it just worked for me, too. Must be some copy/paste issue even though I tried a number of times.

**Comment by Maxwell2022** [comment]
Having the exact same issue with one of my public repo... tried a 1000 times but still get:
```
{
  "errors": [
    {
      "code": "UNAUTHORIZED",
      "message": "authentication required",
      "detail": [
        {
          "Type": "repository",
          "Name": "xxxxx/xxxx-data-dev",
          "Action": "pull"
        }
      ]
    }
  ]
}
```

**Comment by Maxwell2022** [comment]
It Actually looks like the token expired after 5 minutes or something... Trying to get a long life token adding `&offline_token=true` but it doesn't look like it's doing anything

**Comment by sriramg96** [comment]
Hi everyone. It works for me when I do it on regular public repositories. But it doesn't seem to work when I try doing the same steps for official repositories (generating tokens only for pulling). Does anybody know why this is the case?

**Comment by dgoo2308** [comment]
same here, solved by using `registry.hub.docker.com`

**Comment by gempesaw** [comment]
Huh, I have no idea what the underlying issue is, but while using [node-docker-registry-client](https://github.com/joyent/node-docker-registry-client) my token auth was failing when trying to pull `nginx:1.15` from `registry-1.docker.io`...but using `registry.hub.docker.com` as the registry base URL fixed it, without changing any of my code. Thanks for the tip @dgoo2308 :)
