### ISSUE TITLE
Design exported interface for registry clients

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#159]
Currently, the `storage` package has a nice interface in services.go and layer.go for interacting with remote registries. Ideally, we should take this interface, add what is missing and use it as a the future docker engine client.

We may need to do some refactoring (#158) to get this up and running. There are some TODOs in services.go that might provide some direction.

**Comment by stevvooe** [comment]
Much of this is proposed in #193. Filing another issue to track work.

**Comment by dmp42** [comment]
Closed in favor of #354
