### ISSUE TITLE
docker image under different namespace refer to each other,cause authorization to fail

### ISSUE THREAD

**Issue by ybshen** [docker/distribution#1591]
Docker registry authentication and authorization with docker_auth.
The Acl is:
{"seq": 50, "match" : {"account" : "/.+/", "name" : "${account}/* "}, "actions" :
["*"], "comment" : "All logged in users can push all images that are in a names
pace beginning with their name"}
The currently logged in user is test2.When i pushed a image to the test2/php,"test2 pull repository zstest/php" and "test2 pull repository ubuntu/tomcat" and "test2 pull repository zstest/php" have been executed.The test2 user has no  permission of zstest and ubuntu namespaces.So,I  pushed failed.But i try to push many times,it is successfully.How can I deal with this problem?
thanks.

**Comment by ybshen** [comment]
I solved it.thanks

**Comment by ybshen** [comment]
I  found  registry:2.2 has no this error.but above 2.4.0-rc version has this error.

**Comment by RichardScothern** [comment]
*Please follow these instructions to help us diagnose your issue*

 1. create a new issue, with a succinct title that describes your issue:
   - bad title: "It doesn't work with my docker"
   - good title: "Private registry push fail: 400 error with E_INVALID_DIGEST"
 2. copy the output of:
   - `docker version`
   - `docker info`
   - `docker exec <registry-container> registry -version`
 3. copy the command line you used to launch your Registry
 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6. if relevant, copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 8. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry
