### ISSUE TITLE
http.secret config key documentation

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/distribution#1599]
I'm trying to understand `http.secret` key in the yml file. The docs say:

> 
![image](https://cloud.githubusercontent.com/assets/159209/14300189/957cf554-fb43-11e5-9737-4debabc54ffc.png)

However based on my attempts, I am seeing that if I stop a registry and start with a different secret, the client does not notice. I feel like the documentation can be a bit more precise and technical here perhaps.

- Where exactly is this secret used? 
- What happens if I lose the secret value on my production registry instance and start it again with a different value? (what will break? is the damage temporary or forever?)

**Comment by RichardScothern** [comment]
The `http.Secret` is used to protect the upload state with an hmac.  If you are pushing an image with two registries with different `http.Secret`s the hmac will not verify and the second and subsequent upload will fail.

If you lose the secret you will not be able to resume an upload which was initiated with that secret.  You can regenerate the secret and start the upload again.  Your old upload artifact will eventually get swept away.

**Comment by ahmetalpbalkan** [comment]
@RichardScothern thanks for the answer. Is this a security measure for potential tampering of the upload state –or more like a locking mechanism?

> Your old upload artifact will eventually get swept away.

Is this the “upload purging” feature? If that is the case and it is set to “disabled”, does that mean if I lose the secret, clients won’t be able to continue that upload indefinitely?

**Comment by RichardScothern** [comment]
It is a security measure against tampering.  

It is the upload purging feature.  Each docker push will start a new upload, so if you restart the registries and `docker push` a new upload will be started.

Are you worried about losing the secret?

**Comment by ahmetalpbalkan** [comment]
@RichardScothern not entirely, it looks like if I set to http.secret to some simple and static value on my geographically-distributed registry instances, I won't be exposed to security threats, I assumed this has something to do perhaps with HTTP cookies and some fingerprint state stored on the engine, so I wanted to check if that's the case. It seems like even if I lose it, it won’t be much of a trouble.
