### ISSUE TITLE
registry:2.4-rc1 garbage-collect of unreferenced blob data not working

### ISSUE THREAD

**Issue by vehovmar** [docker/distribution#1600]
I may understand issue #462  all wrong, but I thought scenarios like this simple example should be covered by it. (Running this example in freshly created boot2docker v1.10.3 VM)

1/ Pull registry and another arbitrary image:
`docker pull distribution/registry:master`
`docker pull ubuntu`

2/ Run registry:
`docker volume create --name registry`
`docker run -d -p 5000:5000 -p 5001:5001 -v /root/registry-config.yml:/etc/docker/registry/config.yml -v registry:/var/lib/registry --name registry distribution/registry:master`

3/ Tag both those images as "test:lates" and push them to registry to ensure there will be some unreferenced blobs:
`docker tag distribution/registry:master localhost:5000/test`
`docker push localhost:5000/test`
`docker tag ubuntu localhost:5000/test`
`docker push localhost:5000/test`

4/ Now there should be unreferenced blobs in my registry right? Stop registry. Run garbage collection:
`docker stop registry`
`docker run -v /root/registry-config.yml:/etc/docker/registry/config.yml -v registry:/var/lib/registry --rm distribution/registry:master garbage-collect /etc/docker/registry/config.yml`

The blobs were not deleted. Am I missing something here?

Thanks!

**Comment by RichardScothern** [comment]
3/ Causes the tag to point to a different manifest, but that manifest can still be pulled from the registry by its digest.

If you want to garbage collect the manifest and its references, you have to delete it.  There is documentation here:
https://github.com/docker/distribution/blob/master/docs/gc.md

**Comment by vehovmar** [comment]
@RichardScothern thanks for the clarification!

Would you be so kind and elaborate if after step 3 there is a way how to delete the manifest that was pushed first? It now should be "dangling" (not referenced by any tag) right. But when we are building our images on CI, tagging them alway with latest, what should be done before/after push to registry to ensure old manifests/blobs could be deleted. 

Thank you

**Comment by RichardScothern** [comment]
Before you push a new manifest to the same tag, you can `HEAD` the manifest at the tag to get the digest.  This digest can then be used in the manifest delete API to remove the reference.

**Comment by vehovmar** [comment]
So in above case that would be?
`GET /v2/test/manifests/latest`
`DELETE /v2/test/manifests/<the_retriesved_digest>`

One scenario when this would not work (although currently not our case) would be if multiple client were pushing in parallel. Could anything be done in such case? 

Anyway thank you so much I will test it asap.

**Comment by vehovmar** [comment]
Can you please advise me, what I'm doing wrong here:

`HEAD v2/test/manifests/latest`
response:
`HTTP/1.1 200 OK
Via: 1.1 INTERNET2
Connection: Keep-Alive
Proxy-Connection: Keep-Alive
Content-Length: 37793
Date: Wed, 06 Apr 2016 07:38:06 GMT
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Etag: "sha256:6ae9c3f8b6ba38c6111693afe57d14293421491dd464f5496b66aabc8cf43f87"
Docker-Content-Digest: sha256:6ae9c3f8b6ba38c6111693afe57d14293421491dd464f5496b66aabc8cf43f87
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff`

Based on that I'm trying:
`HEAD v2/test/manifests/sha256:546058005a7835c65bfc189d9bcc3893840034e1d5027064230f917e7f90103e`
response:
`{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Name":"test","Revision":"sha256:546058005a7835c65bfc189d9bcc3893840034e1d5027064230f917e7f90103e"}}]}
`

Without `sha256:` the API tries to find tag:
`{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Tag":"546058005a7835c65bfc189d9bcc3893840034e1d5027064230f917e7f90103e"}}]}`

**Comment by RichardScothern** [comment]
It is documented here:
https://github.com/docker/distribution/blob/master/docs/spec/api.md#deleting-an-image

These docs will get pushed to docs.docker.com when this version is released.

**Comment by vehovmar** [comment]
Hi, 

I can confirm that after deleting manifest garbage-collect of unreferenced blob data works as expected.

So please close this issue, I will create a feature request to "remove dangling manifest".

Thanks

**Comment by marcust** [comment]
Sorry to bother you @vehovmar, but I can't find the feature request... we just ran into that issue and I want to track the progress on that.

**Comment by vehovmar** [comment]
@marcust sorry I was on vacation (still am actually). Anyway quick answer I forgot to create it. I actually created fairly simple groovy script to scan filesystem for dangling manifests and used the REST API to remove those and after that the GC removes the blobs, so problem solved for us. Never the less the feature request should be created.

**Comment by marcust** [comment]
@vehovmar we actually did the same. I was wondering if that is actually a valid general feature, because I guess with pull by digest you actually do not need a tag on an image in order to reach it.

**Comment by vehovmar** [comment]
@marcust pulling image by digest is very inconvenient for us as 15+ developers pulling latest image during a day. Everyone looking for the latest digest identifier is not practical, writing some service to return it seems like overkill (when the removing of dangling manifests works well)

**Comment by monikakatiyar16** [comment]
As a performance update, GC runs pretty fast as tested on AWS t2.medium ubuntu 14.04 x86_64
- Time required to execute GC for N soft deleted images

| Total Image Size |  No of Images |  Soft Deleted Images | Total Layers | Layer Size |  Dry Run |   GC   |   Remarks   |
|:----------------:|:-------------:|:-------------:|:------------:|:----------:|:--------:|:------:|:-----------:|
|     9.00GB       |      101      |      100      |     1103     |    10MB    |  0.280    |  0.697  |1 common layer image - Not soft deleted,rest 99 images of 901 unique blob layers, 202 unique metadata layer |
|    10.00GB       |      100      |      100      |     1200     |    10MB    |   0.316  |  0.665 |1000 unique blob layers, 200 unique metadata layer |
|    30.00GB       |       30      |       30      |     210      |   200MB    |   0.530    |   4.685     |150 unique blob layers, 60 unique metadata layer|

**Comment by hai-ld** [comment]
@vehovmar @marcust Could you please share your script for listing dangling manifests? Or at least general procedure to do so?

**Comment by Burstaholic** [comment]
@hai-ld https://github.com/docker/distribution/issues/2190#issuecomment-279343010
