### ISSUE TITLE
[Question] Does distribution store image size in storage and how to get them?

### ISSUE THREAD

**Issue by allencloud** [docker/distribution#1602]
Hi, all,

I am using distribution to build my own private docker registry.

I am wondering that whether distribution can provide an API to expose **Image Size** to user or not?

If the answer is yes, then how to get them?

Thanks in advance.

**Comment by RichardScothern** [comment]
It does not.  You can get the compressed size of the layers and the size of manifests by `HEAD`ing the resource and reading it from the header.

**Comment by allencloud** [comment]
Thanks @RichardScothern
