### ISSUE TITLE
Swift object name length problem

### ISSUE THREAD

**Issue by aga20** [docker/distribution#1610]
Hi!

We use docker registry with swift backend. It works good until we change the `max_object_name_length = 221` in `swift.conf`. When we change it we get internal sever error during the `docker push`

_The push refers to a repository [localhost:5556/registry] (len: 1)
dca8367f60bc: Pushing 1.024 kB
Received unexpected HTTP status: 500 Internal Server Error_

I check the the log with debug mode:

_ERRO[0029] unknown error reading request payload: swift: Timeout expired while waiting for segments of /docker/registry/v2/repositories/registry/_uploads/dcffa3c7-954a-48cd-bacf-544049653f67/data to show up  go.version=go1.5.3 http.request.host=localhost:5556 http.request.id=4be4bd02-31c1-42e7-a2c4-ffd48d1e9d53 http.request.method=PATCH http.request.remoteaddr=127.0.0.1:33116 http.request.uri=/v2/registry/blobs/uploads/dcffa3c7-954a-48cd-bacf-544049653f67?_state=-9fXvOMhm5BVBsTjz3zFd8vGMy-LqgQZTLHHtQI8GiB7Ik5hbWUiOiJyZWdpc3RyeSIsIlVVSUQiOiJkY2ZmYTNjNy05NTRhLTQ4Y2QtYmFjZi01NDQwNDk2NTNmNjciLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMDdUMTM6NDY6MDQuNjAwOTYzMTY1WiJ9 http.request.useragent=docker/1.8.2 go/go1.4.2 kernel/4.3.3-1.el7.elrepo.x86_64 os/linux arch/amd64 instance.id=a461d9e6-615d-4b2d-9abb-8447ff60d78e vars.name=registry vars.uuid=dcffa3c7-954a-48cd-bacf-544049653f67 version=v2.3.1
DEBU[0029] swift.PutContent("/docker/registry/v2/repositories/registry/_uploads/dcffa3c7-954a-48cd-bacf-544049653f67/hashstates/sha256/1024")  go.version=go1.5.3 http.request.host=localhost:5556 http.request.id=4be4bd02-31c1-42e7-a2c4-ffd48d1e9d53 http.request.method=PATCH http.request.remoteaddr=127.0.0.1:33116 http.request.uri=/v2/registry/blobs/uploads/dcffa3c7-954a-48cd-bacf-544049653f67?_state=-9fXvOMhm5BVBsTjz3zFd8vGMy-LqgQZTLHHtQI8GiB7Ik5hbWUiOiJyZWdpc3RyeSIsIlVVSUQiOiJkY2ZmYTNjNy05NTRhLTQ4Y2QtYmFjZi01NDQwNDk2NTNmNjciLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMDdUMTM6NDY6MDQuNjAwOTYzMTY1WiJ9 http.request.useragent=docker/1.8.2 go/go1.4.2 kernel/4.3.3-1.el7.elrepo.x86_64 os/linux arch/amd64 instance.id=a461d9e6-615d-4b2d-9abb-8447ff60d78e trace.duration=15.740601ms trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent trace.id=0838de77-b2c9-45cf-a6d2-6d308be03d32 trace.line=95 vars.name=registry vars.uuid=dcffa3c7-954a-48cd-bacf-544049653f67 version=v2.3.1
ERRO[0029] response completed with error                 err.code=unknown err.detail=swift: Timeout expired while waiting for segments of /docker/registry/v2/repositories/registry/_uploads/dcffa3c7-954a-48cd-bacf-544049653f67/data to show up err.message=unknown error go.version=go1.5.3 http.request.host=localhost:5556 http.request.id=4be4bd02-31c1-42e7-a2c4-ffd48d1e9d53 http.request.method=PATCH http.request.remoteaddr=127.0.0.1:33116 http.request.uri=/v2/registry/blobs/uploads/dcffa3c7-954a-48cd-bacf-544049653f67?_state=-9fXvOMhm5BVBsTjz3zFd8vGMy-LqgQZTLHHtQI8GiB7Ik5hbWUiOiJyZWdpc3RyeSIsIlVVSUQiOiJkY2ZmYTNjNy05NTRhLTQ4Y2QtYmFjZi01NDQwNDk2NTNmNjciLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMDdUMTM6NDY6MDQuNjAwOTYzMTY1WiJ9 http.request.useragent=docker/1.8.2 go/go1.4.2 kernel/4.3.3-1.el7.elrepo.x86_64 os/linux arch/amd64 http.response.contenttype=application/json; charset=utf-8 http.response.duration=13.021094694s http.response.status=500 http.response.written=104 instance.id=a461d9e6-615d-4b2d-9abb-8447ff60d78e vars.name=registry vars.uuid=dcffa3c7-954a-48cd-bacf-544049653f67 version=v2.3.1
127.0.0.1 - - [07/Apr/2016:13:46:04 +0000] "PATCH /v2/registry/blobs/uploads/dcffa3c7-954a-48cd-bacf-544049653f67?_state=-9fXvOMhm5BVBsTjz3zFd8vGMy-LqgQZTLHHtQI8GiB7Ik5hbWUiOiJyZWdpc3RyeSIsIlVVSUQiOiJkY2ZmYTNjNy05NTRhLTQ4Y2QtYmFjZi01NDQwNDk2NTNmNjciLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMDdUMTM6NDY6MDQuNjAwOTYzMTY1WiJ9 HTTP/1.1" 500 104 "" "docker/1.8.2 go/go1.4.2 kernel/4.3.3-1.el7.elrepo.x86_64 os/linux arch/amd64"_

So we have to set the swift.conf for another reason. I think the problem is you use too long object names under the `segment ` in swift.

If you have any suggestion how can we solve this problem please write down :) Thanks.

**Comment by RichardScothern** [comment]
hi @aga20 .  Thanks for the report.

Which object name is exceeding 221 bytes in length?  I can only see
`/docker/registry/v2/repositories/registry/_uploads/dcffa3c7-954a-48cd-bacf-544049653f67/data` in the logs  (92 bytes).

Is there a requirement that `max_object_name_length` must be 221?

**Comment by aga20** [comment]
Hello,

I solve it now, thanks!

**Comment by summerQLin** [comment]
Hi  @aga20,

I ran into this issue too. Wandering how you solve it, is it related to swift object length constraint?
