### ISSUE TITLE
Registry v2 manifest api does not give last_update data

### ISSUE THREAD

**Issue by garo** [docker/distribution#1612]
The registry v1 had last_update attribute on a tag which allowed easily to check when the image was uploaded/updated. V2 doesn't seem to have this. This request is for implementing such last_update timestamp to the manifest api.

**Comment by RichardScothern** [comment]
@garo What is your use case for this feature?  It's unlikely that this will be added to the manifest specification.

**Comment by garo** [comment]
@RichardScothern We have a docker orchestration service which is used to deploy our containers. The tools allows a developer to commit a new version from an image to production and while doing that, it would display when the image was last updated.

This worked really well with the v1 registry as we could get that data, but now I can only determine if an image exists, but as far as I know, I can't get any history when that image was created from the registry itself.

To show an example, the tool displays this kind of information when a user is about to deploy a newer version:

> Previous revision: a2b8d7c9b23788da3d94a5e51d1f8025afa98d0e
> The container 2fe7fd8adceefac1bfb874f8848cbdef6326e20b you are about to deploy was last updated at 18h42m37.17792401s ago

**Comment by RichardScothern** [comment]
The only method this information is available in the v2 registry is via the notification API.  You could consume that and store the timestamp somewhere.  Unfortunately that's the best I can offer.
