### ISSUE TITLE
Private registry push fail:pushing image happened unexpected EOF

### ISSUE THREAD

**Issue by yiting1122** [docker/distribution#1616]
### Problem：

Docker version
   Docker version 1.9.1, build a34a1d5

ursdocker@hzbxs-urstest28:~$ sudo docker push hub.c.163.com/urs_test/oracle163
The push refers to a repository [hub.c.163.com/urs_test/oracle163] (len: 1)
207424de7475: Image already exists
db134eae4865: Image already exists
56e0fbe5d39f: Image already exists
8bd8eceae969: Image already exists
17f0540a53b0: Image already exists
b049800c10ba: Image already exists
2dd9f24a16c9: Image already exists
0571f3e8d32f: Image already exists
f8bbd873ee1c: Pushing [==================================================>] 6.865 GB
unexpected EOF

### registry log：
time="2016-04-11T10:57:13+08:00" level=warning msg="error authorizing context: invalid token" go.version=go1.5.1 http.request.host=hub.c.163.com http.request.id=38583e37-9ac9-4eef-a9c6-fa87a40c89c9 http.request.method=PATCH http.request.remoteaddr=223.252.218.225 http.request.uri="/v2/urs_test/oracle163/blobs/uploads/d990c94b-4f4e-4900-8e4e-aed2a2cb1ece?_state=vZiGApRBmpu7xH3kvL9eVvL0uJ_skYfeu036zpU3RFZ7Ik5hbWUiOiJ1cnNfdGVzdC9vcmFjbGUxNjMiLCJVVUlEIjoiZDk5MGM5NGItNGY0ZS00OTAwLThlNGUtYWVkMmEyY2IxZWNlIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE2LTA0LTExVDAyOjMzOjQ3LjYzNDI1MDU5WiJ9" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.2.0-4-amd64 os/linux arch/amd64" instance.id=585362ab-ee84-47bc-8934-0443b96797bd vars.name="urs_test/oracle163" vars.uuid=d990c94b-4f4e-4900-8e4e-aed2a2cb1ece version="v2.1.0+unknown" 
10.176.10.31 - - [11/Apr/2016:10:57:13 +0800] "PATCH /v2/urs_test/oracle163/blobs/uploads/d990c94b-4f4e-4900-8e4e-aed2a2cb1ece?_state=vZiGApRBmpu7xH3kvL9eVvL0uJ_skYfeu036zpU3RFZ7Ik5hbWUiOiJ1cnNfdGVzdC9vcmFjbGUxNjMiLCJVVUlEIjoiZDk5MGM5NGItNGY0ZS00OTAwLThlNGUtYWVkMmEyY2IxZWNlIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE2LTA0LTExVDAyOjMzOjQ3LjYzNDI1MDU5WiJ9 HTTP/1.1" 401 216 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.2.0-4-amd64 os/linux arch/amd64"

### nginx log：
2016/04/11 10:57:13 [error] 113807#0: *1637951 readv() failed (104: Connection reset by peer) while reading upstream, client: 223.252.218.225, server: hub.c.163.com, request: "PATCH /v2/urs_test/oracle163/blobs/uploads/d990c94b-4f4e-4900-8e4e-aed2a2cb1ece?_state=vZiGApRBmpu7xH3kvL9eVvL0uJ_skYfeu036zpU3RFZ7Ik5hbWUiOiJ1cnNfdGVzdC9vcmFjbGUxNjMiLCJVVUlEIjoiZDk5MGM5NGItNGY0ZS00OTAwLThlNGUtYWVkMmEyY2IxZWNlIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE2LTA0LTExVDAyOjMzOjQ3LjYzNDI1MDU5WiJ9 HTTP/1.1", upstream: "http://10.176.10.39:6000/v2/urs_test/oracle163/blobs/uploads/d990c94b-4f4e-4900-8e4e-aed2a2cb1ece?_state=vZiGApRBmpu7xH3kvL9eVvL0uJ_skYfeu036zpU3RFZ7Ik5hbWUiOiJ1cnNfdGVzdC9vcmFjbGUxNjMiLCJVVUlEIjoiZDk5MGM5NGItNGY0ZS00OTAwLThlNGUtYWVkMmEyY2IxZWNlIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE2LTA0LTExVDAyOjMzOjQ3LjYzNDI1MDU5WiJ9", host: "hub.c.163.com"

### auth config：
   token:
       expiration: 900

### **It happened 401 ,when pushing the image. I set the auth token expiration :900s. 
After push some player,there is a big layer,it takes more seconds than 900s(expiration). 
At that it crashed with "unexpected EOF" **

**Comment by RichardScothern** [comment]
Can you experiment with increasing the token expiration time to be greater than the total upload time?

**Comment by yiting1122** [comment]
i have done experiment with increasing the token expiration time。
Push success if i increasing the time。
And if I use the Inside network，increase the push speed，and also Push will Success。

**Comment by RichardScothern** [comment]
great news :joy_cat:

**Comment by yiting1122** [comment]
it‘s registry’s bug？

**Comment by RichardScothern** [comment]
No.  Tokens are only valid for a set amount of time.  In your case your download duration is exceeding the token duration it will no longer be valid.

**Comment by yiting1122** [comment]
so i hava to increase the expiration time ?

**Comment by RichardScothern** [comment]
Yes.  The token expiration time must exceed or be equal to the duration of pushing a repository.

I'm going to close this issue since there is no actionable item.

**Comment by ianrossi** [comment]
@yiting1122 Where did you make this change? I'm using Gitlab on Ubuntu, but if you can give the path to the file and the filename you changed, that would be great. Thanks.
```
auth config：
  token:
    expiration: 900
```
