### ISSUE TITLE
schema2 manifest builder specifies config media type as application/octet-stream

### ISSUE THREAD

**Issue by aaronlehmann** [docker/distribution#1621]
Example:

```
   "config": {
      "mediaType": "application/octet-stream",
      "size": 2217,
      "digest": "sha256:95d27ce3a43121dd91dbfe5f1b3709dba2e045580b817764e84eec779da7ea26"
   },
```

Spec says this should be `application/vnd.docker.container.image.v1+json`: https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#image-manifest-field-descriptions

Analysis: the schema2 manifest builder fills in this field based on the descriptor returned by the `BlobIngester` `Put` method it calls to upload the config. The manifest builder passes the correct media type to the `Put` method of the blob ingester, but in the descriptor it gets back, it gets the media type `application/octet-stream`. This is because `httpBlobUpload`'s `Commit` method returns the result of a `Stat` operation instead of the descriptor that was passed into it (https://github.com/docker/distribution/blob/master/registry/client/blob_writer.go#L139). Thus, the media type information is lost.

I'm not sure why this `Commit` method is doing a `Stat`. It seems like an extra round trip that would slow things down. Perhaps it should just be returning the original descriptor, which would not lose this media type information.

But this could also be worked around in the manifest builder, by making sure the descriptor we assign to `m.Config` has the desired media type.

**Comment by RichardScothern** [comment]
@dmcgowan
