### ISSUE TITLE
custom redirect for s3 storage driver

### ISSUE THREAD

**Issue by andrewhsu** [docker/distribution#1628]
We have our own datacenters but are looking to move storage of docker images to S3. Docker clients in our datacenters will pull docker images from a docker registry configured with S3 storage driver. Would be nice to have the S3 storage driver redirect the clients to pull the individual layers from a custom HTTP proxy hostname that we can setup in our own datacenters to leverage http proxy caching and save costs of getting data out of S3.

I did a quick search of existing github issues that may be similar to this, but wasn't able to find any. If this is a desirable enhancement for the open source docker distribution, I can arrange a pull request for review.

If this can be accomplished in some other way by just configuration of the docker registry that I have missed, please let me know.

**Comment by RichardScothern** [comment]
hi @andrewhsu 

We currently do not have anything to support this.  The correct way to implement this would be to create a new storage middleware, and build the URL in the `URLFor` function.

I think someone is trying to do something similar in https://github.com/docker/distribution/issues/1498

PRs are certainly welcome!

**Comment by andrewhsu** [comment]
Thanks for merging in my PR. This helps address what we need.
