### ISSUE TITLE
S3 backend, size limit reached

### ISSUE THREAD

**Issue by anandkumarpatel** [docker/distribution#1629]
I updated to the new registry (v2.4.0) hoping the S3 changes will allow layers larger then 5GB to be uploaded. 

I still hit this error:
The specified copy source is larger than the maximum allowable size for a copy source: 5368709120

Is allowing multipart upload on the roadmap?

**Comment by RichardScothern** [comment]
This issue is still outstanding and being tracked in #886.  I'll see what resources we have to dedicate to this.  Closing this as a duplicate.
