### ISSUE TITLE
Minor version release changes command line interface; breaks deployments

### ISSUE THREAD

**Issue by pwaller** [docker/distribution#1631]
This morning an automatic server deploy happened, and it failed with this error message:

```
$ docker run --rm --volume /etc/docker-registry.conf:/etc/docker-registry.conf registry:2 /etc/docker-registry.conf              
Error: unknown command "/etc/docker-registry.conf"
Run 'registry help' for usage.
```

I see that the registry command line interface has changed and now one must specify "serve". This is more or less fair enough and the fix is obvious, I must use `registry:2.3` if I want the old behaviour.

Old command line arguments:

```
$ docker run --rm --volume /etc/docker-registry.conf:/etc/docker-registry.conf registry:2.3 --help
registry stores and distributes Docker images.

Usage: 
  registry <config> [flags]
Flags:
  -h, --help=false: help for registry
  -v, --version=false: show the version and exit
```

New command line arguments:

```
docker run --rm --volume /etc/docker-registry.conf:/etc/docker-registry.conf registry:2.4 --help
`registry`

Usage: 
  registry [flags]
  registry [command]

Available Commands: 
  serve           `serve` stores and distributes Docker images
  garbage-collect `garbage-collect` deletes layers not referenced by any manifests
  help            Help about any command

Flags:
  -h, --help=false: help for registry
  -v, --version=false: show the version and exit


Use "registry help [command]" for more information about a command.
```

I raise this so that anyone else searching for this problem finds this issue. The new release has only just happened so I guess people will hit it pretty quickly, if they're going to.

I'm honestly not sure what the right path is. Clearly improving the CLI is desirable. It's just unfortunate that this breaks a lot of stuff which exists. Arguably ideal deployments would pin things much more carefully, but then you don't get automatic updates. I had a (perhaps incorrect) expectation that this command would continue to work indefinitely.

In the past when setting this up I wanted to run without a configuration file but this wasn't supported. I guess this is supported now, seemingly, from the [docs on docker hub](https://hub.docker.com/_/registry/)?

Thanks for listening. Hopefully there are some useful lessons to learn here. Everything in here is obvious in hindsight, but at the time using `registry:2` seemed reasonable. It would be useful if the long-term supported usages were documented carefully in the hub registry docs.

**Comment by pwaller** [comment]
By the way, the introduction of the `registry serve` sub-command doesn't seem to be documented anywhere I could find, and it's not obvious from the pull requests or git history that it was actually introduced in https://github.com/docker/distribution/pull/1386/files#diff-55e333416ad33b237c440cbd78d81cebR28 which is titled "garbage collection", so not obviously an interface change.

**Comment by RichardScothern** [comment]
hi @pwaller : this is a mistake on my part.  I structured the registry dockerfile incorrectly and will submit a fix for this.

There is further confusion here.  We don't use the `latest` tag for the registry, but explicit tags like `2` do change with releases.  I intend to remedy this too.

The sub-command is mentioned in the release notes: https://github.com/docker/distribution/releases.  

Apologies for the confusion..

**Comment by pwaller** [comment]
I guess this is fixed @RichardScothern.
