### ISSUE TITLE
Deleting images with v2 does not work, wrong digest 

### ISSUE THREAD

**Issue by EugenMayer** [docker/distribution#1637]
Finally go teached about storage->delete->true in the configuration https://github.com/docker/distribution/blob/master/docs/configuration.md

and implemented it. Still, while fetching the digest https://github.com/EugenMayer/docker_registry_cli/blob/master/DockerRegistryRequest.rb#L92 getting a string like sha256:XXXX

Using this to feed into delete https://github.com/EugenMayer/docker_registry_cli/blob/master/DockerRegistryRequest.rb#L83
i get notfied, that the digest is wrong.

Using the current latest registry:2 (sha256:20f5d95004b71fe14dbe7468eff33f18ee7fa52502423c5d107d4fb0abb05c1d).

Is this a bug / fixed already?

**Comment by EugenMayer** [comment]
also see https://github.com/docker/docker-registry/issues/988#issuecomment-210190903

**Comment by RichardScothern** [comment]
`docker/docker-registry` is a different repository and product.

Please read the spec about deleting manifests:
https://github.com/docker/distribution/blob/master/docs/spec/api.md#deleting-an-image

**Comment by stonelion** [comment]
@EugenMayer using this:
curl -I -H Accept:application/vnd.docker.distribution.manifest.v2+json will get correct digest

**Comment by EugenMayer** [comment]
thank you @stonelion worked out settings this header and yes, its in the docs, but its neither convinient nor obvious to see. For a rest-API the docs are very unstructured ;/ 

Any thank you
