### ISSUE TITLE
(Re-)Define minimal set of policy rights for S3 storage backend

### ISSUE THREAD

**Issue by djui** [docker/distribution#1638]
The documentation for S3 storage backend seems to have been updated after the change from Docker Registry 2.3 to 2.4. One policy right I can't reproduce being necessary is [`s3:GetBucketLocation`](https://github.com/docker/distribution/blame/master/docs/storage-drivers/s3.md#L200). Could you justify and explain the decision?

**Comment by stevvooe** [comment]
@djui We really don't know much about s3 policies. They are very poorly document and the defaults seem to be different from region to region.

If you could propose a working set or get someone from AWS to chime in, that would be great.

**Comment by djui** [comment]
Will close this issue. Not if it's accurate anymore but also not required for me anymore.
