### ISSUE TITLE
Cloudfront handler initialized by importing storage

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#164]
Currently the cloudfront driver is initialized in the storage package.  This forces a dependency on the go amazon package to import storage.  It also initializes a potentially unused driver. This code should be refactored such that cloudfront must be explicitly imported to be initialized.

**Comment by stevvooe** [comment]
Providing a little history:

These `LayerHandler` implementations currently sit in the `storage` package to gain access to the internal path mapper. This required to map a backend driver path to a url using the storage driver.

Some possible solutions include the following (not mutually exclusive):

1. Export the backend path mapper to a separate package. This was not done originally to keep the exported API small and limit the horrid things that could happen by exposing that interface. Albeit, I'm sure there is elegant solution along these lines.
2. Require that `Layer` interface implement `http.Handler`. Integrate `LayerHandler` dispatch into `storagedriver`. Effectively, we have `(Layer).ServeHTTP`. The `storage` package tries out `(StorageDriver).URLFor` and redirects if possible. This is more elegant than it sounds. The goal here would be to push layer handler configuration into the storage driver, such that it's used with URLFor. Details such as cloudfront/s3 or azure urls are hidden from the user.

I am in favor of option 2, as it hides driver detail where it belongs.

**Comment by stevvooe** [comment]
Closed by #244.
