### ISSUE TITLE
Garbage collection fails in 2.4 with "Path not found" message

### ISSUE THREAD

**Issue by sergeyfd** [docker/distribution#1640]
Just tried to run Garbage Collector in the dry-run mode and got this error message:

failed to garbage collect: failed to mark: filesystem: Path not found: /docker/registry/v2/repositories/dcdocker/1234-canvas_ui-1448287527799/_manifests/revisions

Any advice on how to deal with this?

**Comment by RichardScothern** [comment]
The registry cannot find the storage directory on your disk

Are you using the same config file that you use to run the registry?

**Comment by sergeyfd** [comment]
Yes and that directory does not exist. So the message is correct. 

Config file is that same and it looks like those repos are broken, they can't be retrieved with the regular pull as well. It might be a bug in our build process and I will check that with our developers. However I think that GC should handle these broken repos more gracefully and not completely fail.

**Comment by RichardScothern** [comment]
What behavior do you expect to see if the root directory does not exist?

**Comment by sergeyfd** [comment]
root directory does exist, _manifests underneath it doesn't. Ideally I'd expect something like "skip a broken one and proceed with the rest" if that's possible of course.

**Comment by sergeyfd** [comment]
It looks like failed pushes create repos without _upload directories on the registry side. Those repose then block GC.

**Comment by RichardScothern** [comment]
That is unfortunate.  It's not safe to skip repositories on error when running the GC mark phase over the repositories, as a temporary error condition can cause blobs to not be marked.

There is a bug tracking the partial upload issue #936.   I am not sure we can truly fix this until we move to a consistent store for metadata.

**Comment by sergeyfd** [comment]
@RichardScothern would it be safe to delete broken repos on the storage backend and run GC again?

**Comment by RichardScothern** [comment]
@sergeyfd : yes.

**Comment by RichardScothern** [comment]
On reflection,  if _manifests directories are missing it will be safe to skip over them.  There is nothing referencing blobs, so the count will still be accurate.

**Comment by tonyhb** [comment]
@sergeyfd we also ran into this and I've submitted a fix here: https://github.com/docker/distribution/pull/1664

As far as I'm aware this will be rolled out in an upcoming release soon

**Comment by sergeyfd** [comment]
@tonyhb I saw that. Thanks a lot!
