### ISSUE TITLE
Private registry delete blobs fail: 500 error with UNKNOW

### ISSUE THREAD

**Issue by bes-barnett** [docker/distribution#1648]
DELETE  /v2/name/blobs/Digest
Response:{"error":[{"code":"UNKNOW","message":"unknow error","detail":{"Op":"dial","Net":"tcp","Source":null,"Addr":{"IP":"::1","Port":6379,"Zone":""},"Err":{"Syscall":"getsocketopt","Err":111}}}]}
Docker Version:1.10.3,API-VERSION:1.22
Registry Version:registry github.com/docker/distribution v2.3.0-rc.1-187-gf4b6fc8.m

i don't copy the registry container logs, I can describe as follows：
lever=error msg="error adding descriptor" to cache:dial tcp [::1]:6379:getsocketopt:connection refused" suth.user.name=admin go.version=go1.6

**Comment by bes-barnett** [comment]
I found that Collector Garbage was added in version 2.4.0
Does it mean that the blobs can be deleted without their own maintenance

**Comment by RichardScothern** [comment]
@bes-barnett : the error message indicates an network error.  

A GC command was added in 2.4.0 but it's run as a command.  Please see the documentation.
