### ISSUE TITLE
Add signal handler to re-read Registry configuration

### ISSUE THREAD

**Issue by sergeyfd** [docker/distribution#1651]
It would be a nice feature if Registry supported handling of "kill -HUP" to force configuration reload. Such feature could be used for switching Registry between readonly "enable/disable" modes without a need to completely restart Registry. Something like `"docker exec registry_conainer_name kill -HUP 1"`

**Comment by RichardScothern** [comment]
hi @sergeyfd 

Graceful restart adds a lot of complexity for relatively little benefit.   In-flight requests would need to be drained and new ones refused.  The registry starts almost instantly and the docker engine now has retry built-in.

**Comment by sergeyfd** [comment]
Makes sense. Thanks.
