### ISSUE TITLE
 level=fatal msg="open /certs/domain.crt: no such file or directory"

### ISSUE THREAD

**Issue by wanghaisheng** [docker/distribution#1652]
```
[wanghs@db2 docker-registry]$ ls -al certs
总用量 16
drwxrwxr-x 2 wanghs wanghs 4096 4月  18 09:43 .
drwxrwxr-x 4 wanghs wanghs 4096 4月  20 15:05 ..
-rw-rw-r-- 1 wanghs wanghs 1411 4月  18 09:50 domain.crt
-rw-rw-r-- 1 wanghs wanghs 1704 4月  18 09:50 domain.key

[wanghs@db2 docker-registry]$ docker version
Client:
 Version:      1.11.0-rc5
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   6178547
 Built:        Mon Apr 11 20:44:29 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

[wanghs@db2 docker-registry]$ docker-machine version
docker-machine version 0.7.0, build a650a40

```

when i run the following
```
first
docker build -t datacenter/registry .
then  
docker run -d -p 5000:5000 --restart=always --name registry \
  -v /home/wanghs/docker-registry/data:/var/lib/registry \
  -v /home/wanghs/docker-registry/certs:/certs \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
  datacenter/registry

```

```
[wanghs@db2 docker-registry]$ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED              STATUS                          PORTS                    NAMES
1337cfb12c4d        datacenter/registry   "registry serve /etc/"   About a minute ago   Restarting (1) 22 seconds ago   0.0.0.0:5000->5000/tcp   registry

```

**Comment by RichardScothern** [comment]
Is your volume mount correct?  

Add `--entrypoint=/bin/bash` to you run comand and `ls /certs` in your container

**Comment by wanghaisheng** [comment]
```
[wanghs@db2 ~]$ docker run -it --entrypoint=/bin/bash -p 5000:5000 --restart=always --name registry   -v /home/wanghs/docker-registry/data:/var/lib/registry   -v /home/wanghs/docker-registry/certs:/certs   -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt   -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key   datacenter/registry
root@8fd8cf60867f:/go/src/github.com/docker/distribution# ls /certs
root@8fd8cf60867f:/go/src/github.com/docker/distribution#

```

**Comment by RichardScothern** [comment]
I'm closing this as it's tracked in #3255 and nothing to do with this project.

**Comment by wanghaisheng** [comment]
@RichardScothern  nothing to do with this project? could you recommend a better way to mount host folder into containers?

**Comment by ejoso** [comment]
I'm having the same problem and the issue referenced above as docker/machine#3255 points back to this one -- both issues are closed without resolution. Request to re-open?

**Comment by collink** [comment]
@RichardScothern I'm also having this issue.  I've tested by running `alpine/latest` with the same volume bindings and I can see the certs/auth stuff no problem, so I'm not convinced that this issue is related to https://github.com/docker/machine/issues/3255

**Comment by mtttcgcg** [comment]
Same problem here - this isn't a problem with the volume mount because the files show up inside the container. The user is root and has permissions to read the /certs/domain.crt file. I'm not using auth, just trying to get TLS working.

**Comment by RikkeHamilton** [comment]
> @RichardScothern I'm also having this issue. I've tested by running `alpine/latest` with the same volume bindings and I can see the certs/auth stuff no problem, so I'm not convinced that this issue is related to [docker/machine#3255](https://github.com/docker/machine/issues/3255)
> 
> Here is how I'm starting the container:
> 
> ```
> docker run -d \
>   -p 5000:5000 \
>   --restart=always \
>   --name registry \
>   -v /mnt/registry:/var/lib/registry \
>   -v /auth:/auth \
>   -e "REGISTRY_AUTH=htpasswd" \
>   -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
>   -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
>   -v /certs:/certs \
>   -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 \
>   -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
>   -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
>   registry:2
> ```
> 
> I've verified that `/certs` does in fact have those files in it, and `/auth` contains `htpasswd`, but I still get this error. If I run a more stripped down command to start it, it will run (which is how I verified):
> 
> ```
> # docker run -d \
>   -p 5000:5000 \
>   --name registry \
>   -v /mnt/registry:/var/lib/registry \
>   -v /auth:/auth \
>   -v /certs:/certs \
>   registry:2
> 
> ...
> 
> # docker exec -it registry ls /certs
> domain.crt  domain.key
> 
> # docker exec -it registry ls /auth
> htpasswd
> ```

@collink Did you ever solve this? I am having the same issue.

**Comment by TacoBel42** [comment]
Any updates ?
have the same issue 
**my docker-compose.yml**

 ```
 registry:
    restart: always
    image: registry:2.7.1
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/cert.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: basic-realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_LOG_LEVEL: "debug"
    volumes:
      - /var/lib/docker-registry/data:/var/lib/registry
      - /var/lib/docker-registry/certs:/certs
      - /var/lib/docker-registry/auth:/auth
```

**Comment by Takerman** [comment]
Same issue here

**Comment by alibabakhanlu12** [comment]
i had this error with my registry too.I generated my  certificate and mounted the hole folder of letsencrypt inside my docker container.then set the path to my domain inside it
![Screenshot from 2024-07-28 20-37-28](https://github.com/user-attachments/assets/93a4ccb0-b779-4bf3-a338-9252a00d0e84)

this worked for me :)


Reason:
when you only mount the path /etc/letsencrypt/live/registry.domain.com/  inside the /certs folder in docker container, all files in certs directory linked for another files  in the archive folder
