### ISSUE TITLE
Push schema2 manifest failed(MANIFEST_BLOB_UNKNOWN) when using registry API

### ISSUE THREAD

**Issue by ywk253100** [docker/distribution#1655]
I want to migrate an image from registry A to registry B using API. The schemas of manifests in both registry are V2. 

So I pulled manifest and layers from A and then pushed all layers to B. But when I pushed the manifest to B, a 400 error(MANIFEST_BLOB_UNKNOWN) occurred.

I found that the unknown blob is the one which was referenced by config part in the manifest. So I should push this blob to registry, right? But I did not find any instruction in the API doc told me that.

Is my understanding right? Or I missed something.

**Comment by RichardScothern** [comment]
The digest of the config will be in the manifest you pull from A.  You should be able to migrate is using the digest from the manifest in the blob API calls.
