### ISSUE TITLE
Garbage collection revision info clean

### ISSUE THREAD

**Issue by supermeng** [docker/distribution#1661]
I test gc in my private registry, when push image which have been deleted before in registry, the image manifests info can't be fetched  any more.

After debug, found that all because of signature info did not match.

Finally, found  files in " _manifests/revisions/sha256/tag:digest/" did not be removed by gc, when pushed the deleted image again, signature info in manifests will append the old signature info. so problem of  signature unmatched led to can't fetch manifests info of the image.

Test step: 

```
1. push a image named "test:latest" to the registry: docker push registry/test:latest
2. delete  image tag: curl -X DELETE /v2/test/manifests/{digest of latest}
3. call gc in registry: registry garbage-collect config.yml
4. push the delete image again after gc: docker push registry/test:latest
5. fetch manifest info : curl -X GET /v2/test/manifests/{digest of latest}
```

sinature info in test (gc --dru-run):

```
layer-graph: marking signature sha256:35f2f774282ba0a7853b0a6b3677aa2f3c23b5a61a35a5170f1efa229ff7f5a5
layer-graph: marking signature sha256:6bb6c665633245f33b436b8b064d8c01d1ea6f3343227cbe29f1001becfd036b

but sha256:35f2f774282ba0a7853b0a6b3677aa2f3c23b5a61a35a5170f1efa229ff7f5a5 was deleted in blobs
```

Error when fetch manifests:

```
level=error msg="error fetching signature \"sha256:35f2f774282ba0a7853b0a6b3677aa2f3c23b5a61a35a5170f1efa229ff7f5a5\"
```

**Comment by RichardScothern** [comment]
hi @supermeng thanks for the report and the detail analysis.

We are deprecating signature storage in the registry.  You can add this to your config:
```
compatibility:
  schema1:
    disablesignaturestore: true
```

and the registry will generate a signature for the manifest.

**Comment by supermeng** [comment]
Thanks for you feedback!

**Comment by RichardScothern** [comment]
Did that solve your issue @supermeng ?

**Comment by supermeng** [comment]
yes! It works very well! :D
