### ISSUE TITLE
If a registry becomes corrupted, but can still be pulled from, the catalog API nondeterministically returns an empty list of repos with success.

### ISSUE THREAD

**Issue by dnwake** [docker/distribution#1668]
To reproduce:

. Run registry  on host registry-server and port 5000 (I am on commit cd27f179f2c10c5d300e6d09025b538c475b0d51)
- Push bad_image:latest to the registry
- SSH to the registry machine and run 

   ln -sf /var/lib/registry/docker/registry/v2/repositories/bad_image  \                /var/lib/registry/docker/registry/v2/repositories/corrupt_image

- curl -s "http://registry-server:5000/v2/_catalog"

Expected Result:  either the result should be an error, or at least "bad_image" should be returned.
Actual Results (about 50% of the time):  {"repositories":[]}  (HTTP 200)
(the other 50% of the time): {"repositories":["bad_image","corrupt_image"]} (HTTP 200)

Note that in all cases it is possible to pull bad_image and corrupt_image successfully.

Two issues here:

- The behavior is nondeterministic
- Even if the registry is corrupt, returning an empty list of repostories with a success code cannot be the correct response.

**Comment by RichardScothern** [comment]
hi @dnwake 

I ran your soft-linking experiment and did not see any non-deterministic behavior.  Both the original and 'corrupt-image' were accessible through the catalog and were pull-able 100% of the time. 

I would be curious to know what the logs show for the two results you see. 

Also, what is your use case for linking repositories?
