### ISSUE TITLE
Docker client is trying to push/pull to V1 but it should be V2

### ISSUE THREAD

**Issue by Vad1mo** [docker/distribution#1671]
I have a docker registry version 2.3.1 installed. I can push and pull images but sometime I get this error in Jenkins CMD and Gradle java API

```
docker pull registry.corp.acme.com/p21/web
Using default tag: latest
Error response from daemon: Get https://registry.corp.acme.com/v1/_ping: dial tcp: lookup registry.corp.acme.com on 192.168.1.1:53: no such host
```
The strange thing here is that it tries to ping v1 where I only have v2. When this happens I have to restart the registry and then it works for some time again until the error repeats. 

My setup is (reverse-proxy[SSL]) <--> (registry[noSSL]) <--> LDAP

**Comment by aaronlehmann** [comment]
It's likely trying to ping the /v2 endpoint before it resorts to /v1. The docker client only shows the last error.

The real issue seems to be a DNS resolution problem.

`lookup registry.corp.payment21.com on 192.168.1.1:53: no such host`

**Comment by Vad1mo** [comment]
got it, I supose the Problem was because of the revere proxy in front of the registry
