### ISSUE TITLE
V2 API: 401 'insufficient_scope' getting /tags/list

### ISSUE THREAD

**Issue by hrobertson** [docker/distribution#1676]
I appreciate the registry used by Docker Hub has been modified from this project, but I figured this was the best place to report this.

The response to a request for a list of tags tells me I need the `pull` scope for the repository.
After obtaining a token with the required scope I retry the request and receive the error "insufficient_scope" although the required scope is still stated in the Www-Authenticate header as `pull`.

```
$ curl -i https://registry.hub.docker.com/v2/docker/highland_builder/tags/list
HTTP/1.1 401 Unauthorized
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:docker/highland_builder:pull"

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Name":"docker/highland_builder","Action":"pull"}]}]}

$ curl -i https://auth.docker.io/token?service=registry.docker.io&scope=repository:docker/highland_builder:pull
HTTP/1.1 200 OK

{"token":"eyJhbGciOiJFUzI1N..."}

$ curl -i -H "Authorization: Bearer eyJhbGciOiJFUzI1N..." https://registry.hub.docker.com/v2/docker/highland_builder/tags/list
HTTP/1.1 401 Unauthorized
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:docker/highland_builder:pull",error="insufficient_scope"

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Name":"docker/highland_builder","Action":"pull"}]}]}
```

(Output trimmed for clarity)

I have tried replacing pull with list and * to no avail.
$ curl https://registry.hub.docker.com/v1/repositories/docker/highland_builder/tags works fine.

Thanks

**Comment by RichardScothern** [comment]
Add quotes around the url of your curl command to the token server.

**Comment by hrobertson** [comment]
Damn. Thanks man.

**Comment by paksv** [comment]
can you guys drop a word about this on https://docs.docker.com/registry/spec/auth/token/#using-the-bearer-token? 
If you write a code that should work with private repository as well as index.docker.io you need to add an ugly hack that wrap service name (registry.docker.io) into quotes just for this particular case.

**Comment by hrobertson** [comment]
@paksv I'm pretty sure the quotes are required by curl. It's not a Docker issue.

**Comment by UtkarshYeolekar** [comment]
I was hitting through postman, and was getting the similar error of unauthorized. In the header, i have enclosed the authorization value in quotes, and every thing worked. 

![image](https://user-images.githubusercontent.com/23631648/29121273-830680aa-7d2b-11e7-985d-1ffdf0b68b33.png)

**Comment by shenred176** [comment]
I'm still hitting this issue with UtkarshYeolekar's suggestion and I'm on Postman as well. The only difference is I'm calling a PUT api call (GET works for me, without having to encloused the authorization value). Any idea what could be an issue?
Thanks.
