### ISSUE TITLE
User-facing error messages

### ISSUE THREAD

**Issue by tt** [docker/distribution#1682]
I have implemented a registry based on this framework. (Thank you for making it really easy for me.)

I'm trying to improve the user experience by returning user-facing error messages from the registry but either I'm not realizing what I need to do or it would be great to improve the support for such.
## `docker login`

[The client code handling `docker login` for Docker Registry HTTP API V2](https://github.com/docker/docker/blob/e42f85080b8254ee025f30cf7860641836df649f/registry/auth.go#L158-L167) is definitely limited:

```
// TODO(dmcgowan): Attempt to further interpret result, status code and error code string
err := fmt.Errorf("login attempt to %s failed with status: %d %s", endpointStr, resp.StatusCode, http.StatusText(resp.StatusCode))
```

This means the only error messages I can use are those [known by Go](https://golang.org/src/net/http/status.go?s=4647:4679#L106) and defined by the HTTP standard. That's [a regression from V1](https://github.com/docker/docker/blob/e42f85080b8254ee025f30cf7860641836df649f/registry/auth.go#L57-L75) where more meaningful messages would be provided for at least some responses.

[This framework can only return a 401 or a 400](https://github.com/docker/distribution/blob/bc9c820e4bf152b94933ab43ed865b3717a709f2/registry/handlers/app.go#L770-L789). (`auth.Challenge.SetHeaders(...)` could probably be hacked to write any HTTP response but that seems like an unsupported thing to do.)

(See #1480 for another issue covering this.)
## `docker push`

I'm trying to return an error message from a repository middleware. I'm using [`errcode.Error`](https://godoc.org/github.com/docker/distribution/registry/api/errcode#Error).

However, [the error handling in `PutImageManifest`](https://github.com/docker/distribution/blob/afe2bdd1c5194ac85a59adf1fdd14c9da054356e/registry/handlers/images.go#L268-L288) converts this to `errcode.ErrorCodeUnknown`. That's an easy fix, though.

There is also [a limited list of error codes](https://github.com/docker/distribution/blob/0f670bdc91fe020a93e1c7973000ddd305e0a3d6/registry/api/errcode/register.go#L16-L66) to chose from. `errcode.ErrorCodeDenied` and `errcode.ErrorCodeUnauthorized` have very specific meaning. `errcode.ErrorCodeUnavailable` and `errcode.ErrorCodeUnknown` can't be used (for error messages) because [the Docker CLI will only attempt to parse error messages for 4XX responses](https://github.com/docker/distribution/blob/3a2231fe392c7a1212eee3bb89c9cb9a255057bc/registry/client/errors.go#L93-L95). (This means I can't provide a URL to an incident if we need to return 503 during an outage.)

That leaves `errcode.ErrorCodeUnsupported`. I can use that although all error messages will then include "unsupported":

```
% docker push ...
...
unsupported: <error message>
```
# Proposal

Whenever `errcode.Error` (or, possibly, a new `errcode.UserError`) is returned, it should be bubbled all the way up, not logged like a generic `error` and serialized as the HTTP response.

The Docker CLI might write generic error messages upon errors but should always write custom error messages whenever the HTTP response can be parsed. This should be true for both 4XX and 5XX errors.

**Comment by stevvooe** [comment]
Without going into wild detail, I believe the issue with our problems here are the omission of using 403 when authentication is provided but not accepted.
