### ISSUE TITLE
Delete Event Notification to have tag name

### ISSUE THREAD

**Issue by gauravbhandare** [docker/distribution#1685]
I tried configuring the notifications with Docker Registry 2.4.0 and ab able to capture the events but the delete event is having the digest and does not have any reference to the tag name. Is there any way to get the tag name in the delete event? I am looking for capturing this from audit logging standpoint as users may be more familiar with the tag name than digest.

**Comment by RichardScothern** [comment]
The delete API operates on digests, not tags.  The only information available at the event time is the digest.

**Comment by gauravbhandare** [comment]
Understandable. Is there anyway you can think of to get the tag name for delete event(Anyway using the sha to get it from registry)? Just trying to see if this can be captured for audit logging.

**Comment by RichardScothern** [comment]
Manifest Put events will tell you when the tag has changed and give the digest for it.  If you track this data you can reconcile it with the hash in the delete event.
