### ISSUE TITLE
Cannot checkout project on Windows machine

### ISSUE THREAD

**Issue by vdemeester** [docker/distribution#1690]
It's not possible to checkout the project on a windows machine, causing `go get` to fail, and for example, some build to fail (see https://ci.appveyor.com/project/calavera/engine-api/build/247).

It seems Windows doesn't like path with `:` in it `fatal: cannot create directory at 'contrib/docker-integration/generated_certs.d/localregistry:5440': Invalid argument` :sweat_smile:.

```
C:\Users\demeester\go\src\github.com\docker
λ git clone https://github.com/docker/distribution.git
Cloning into 'distribution'...
remote: Counting objects: 13957, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 13957 (delta 12), reused 0 (delta 0), pack-reused 13927
Receiving objects: 100% (13957/13957), 9.37 MiB | 641.00 KiB/s, done.
Resolving deltas: 100% (7338/7338), done.
Checking connectivity... done.
fatal: cannot create directory at 'contrib/docker-integration/generated_certs.d/localregistry:5440': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by thaJeztah** [comment]
I wonder if we should use subdirectories for those; may be a more portable solution, i.e.;

    contrib/docker-integration/generated_certs.d/localregistry/5440/

that would also prevent having to do this on Windows; https://github.com/docker/docker/blob/12c67f42d85103c57c14f27579ff46fccdc3ee07/registry/config_windows.go#L12-L18

(as was mentioned in this discussion: https://github.com/docker/docker/issues/21189)

**Comment by RichardScothern** [comment]
I think not using `:` to delimit the port in certificate directories is the right solution.

The files in contrib are part of the integration tests.  If this intention of checking out docker/distribution doesn't require integration tests, a git sparse checkout could workaround this.  As a last resort workaround, would cygwin handle this (while we wait for Windows bash)?

**Comment by Monomachus** [comment]
I have the same issue :+1:

**Comment by RichardScothern** [comment]
There is nothing actionable in distribution for this problem.  When docker changes the directory specification for certificates checkout will be possible on Windows.

The following will checkout with the `contrib` directory
```
git init 
git  remote add -f upstream https://github.com/docker/distribution
git config core.sparsecheckout true
echo '/*' >> .git/info/sparse-checkout 
echo '!contrib' >> .git/info/sparse-checkout
git pull upstream master 
```

**Comment by vdemeester** [comment]
@RichardScothern The problem is with `go get` for example (where I don't think we can make it so it *sparse-checkout*). This makes all build fail for `docker/engine-api` on windows for example.

@RichardScothern I'm gonna try to do something on the docker side but maybe those folder should be named differently and somehow final ones generated at build-time, I don't know :stuck_out_tongue:.

**Comment by dmcgowan** [comment]
@vdemeester I am not a _fan_ of making this change but I will look into re-enabling the install script into the test runner.

**Comment by dmcgowan** [comment]
Opened a PR to fix this, the change was not as _bad_ as I hoped. The directories only need to be generated as part of the integration test and never needed for build.
