### ISSUE TITLE
 HA Registry / Distributed Storage Driver 

### ISSUE THREAD

**Issue by LLParse** [docker/distribution#1691]
Hello,

I have 100 bare-metal servers on an air-gapped network running Docker v1.10.3 and configured to use a local registry deployed on one of these servers. A lot of network strain is observed on this box when concurrently pulling images.

To alleviate this, I am pursuing a distributed deployment of the registry server. I only need to support a small set of images (<100) which requires a small amount of storage, ~10GB. What I want to do is run a registry container on every node, configure each docker daemon to only communicate with the local registry instance, and then set my storage backend replication factor to something high like 50 or maybe even 100. The distributed object store would also need to be containerized.

I see that Docker provides a handful of storage drivers, ranging from local filesystem to cloud storage. For my use case, **swift** looks like the only viable option, but I know nothing about this project. I've also considered a distributed file system, but finding a solution that can be containerized and provides tunable replication has proven difficult.

I haven't found much documentation on HA docker registry deployments, so I suppose my question is, am I on the right path? Are there any gotchas or special configuration required to make this design a reality?

[Cross-posted on the distribution forum.](https://groups.google.com/a/dockerproject.org/forum/#!topic/distribution/eRCdbgsusHk)

**Comment by RichardScothern** [comment]
hi @LLParse .  You are on the right lines: generally registry instances scale out horizontally and lean on the backend for throughput along with storage redirects to offload data transfer to CDNs.

Swift is certainly an option.  It's an internally deployable distributed storage system with configurable replication and there are containerized versions of it (I use `aerofs/swift` for my testing).  However, it's a big dependency and should be investigated prior to use.  If you are changing your replication factor often or adding/removing nodes then there will be some amount of data copying as the hash ring is adjusted.

Given that you have a small (immutable?) data set I wonder if you could use the filesystem driver.  One way to do this is to use a [data volume](https://docs.docker.com/engine/userguide/containers/dockervolumes/) ) containing your data and accessed through the filesystem driver.  I would expect the linux page cache to fill up nicely for a performance boost, though on the downside you would be deploying a 10GB container per machine and your data replication rate would be non-configurable.   You would be paying the network cost at deployment time.

**Comment by LLParse** [comment]
Hi @RichardScothern, thanks for the quick response! I have a better understanding of my options and what I might need to do.
