### ISSUE TITLE
frequent insufficent scope error

### ISSUE THREAD

**Issue by osallou** [docker/distribution#1692]
Hi,
I batch push many containers, and I face frequent errors on registry (I use docker-py for push).
I use a private registry with authentication. Many container pushes are ok, both at least half of pushes fail with error: error authorizing context: insufficient scope.
This is the same user that makes the push via a script in a loop over all my containers.

I do not understand where the error comes from. My authentication server, linked to the registry,  works fine, sending authorization with token. Often, running the script again will succeed on previously failed container push.

Here is log extract:

    ....
    192.168.1.118 - - [02/May/2016:18:09:42 +0000] "POST /v2/debian/fastaq/blobs/upl                oads/?from=debian%2Fprofnet-chop&mount=sha256%3Aefd26ecc95486998b41b3fe167236e3f                b3e109c66dd1a51ab5161e40b06cf486 HTTP/1.1" 401 206 "" "docker/1.10.3 go/go1.5.3                 git-commit/20f81dd kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64"
    time="2016-05-02T18:09:42.934777347Z" level=warning msg="error authorizing conte                xt: insufficient scope" environment=development go.version=go1.4.3 http.request.                host=docker-registry.genouest.org http.request.id=cf46380e-9f6e-4aae-9b35-3ab86f                f4aa4e http.request.method=PATCH http.request.remoteaddr=192.168.1.2 http.reques                t.uri="/v2/debian/fastaq/blobs/uploads/6e0c8ac2-b5a0-465a-a23b-3dabd8344887?_sta                te=6MirFP-Wo8Ldw4nsu6B7-jYryEKel0mFYqAfOkhTqYB7Ik5hbWUiOiJkZWJpYW4vZmFzdGFxIiwiV                VVJRCI6IjZlMGM4YWMyLWI1YTAtNDY1YS1hMjNiLTNkYWJkODM0NDg4NyIsIk9mZnNldCI6MCwiU3Rhc                nRlZEF0IjoiMjAxNi0wNS0wMlQxODowOTo0Mi43Nzg2MTAxMDFaIn0%3D" http.request.useragen                t="docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.10.0-229.20.1.el7.x86_64                 os/linux arch/amd64" instance.id=46806730-87ba-44bc-b64f-bbc8226db7ad service=r                egistry vars.name="debian/fastaq" vars.uuid=6e0c8ac2-b5a0-465a-a23b-3dabd8344887                 version=v2.2.0
    time="2016-05-02T18:09:42.937637731Z" level=warning msg="error authorizing conte                xt: insufficient scope" environment=development go.version=go1.4.3 http.request.                host=docker-registry.genouest.org http.request.id=f6b1db00-595b-4c27-8333-61865f                63e742 http.request.method=POST http.request.remoteaddr=192.168.1.2 http.request                .uri="/v2/debian/fastaq/blobs/uploads/" http.request.useragent="docker/1.10.3 go                /go1.5.3 git-commit/20f81dd kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd6                4" instance.id=46806730-87ba-44bc-b64f-bbc8226db7ad service=registry vars.name="                debian/fastaq" version=v2.2.0
    192.168.1.118 - - [02/May/2016:18:09:42 +0000] "POST /v2/debian/fastaq/blobs/upl                oads/ HTTP/1.1" 401 206 "" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3                .10.0-229.20.1.el7.x86_64 os/linux arch/amd64"
    192.168.1.118 - - [02/May/2016:18:09:42 +0000] "PATCH /v2/debian/fastaq/blobs/up                loads/6e0c8ac2-b5a0-465a-a23b-3dabd8344887?_state=6MirFP-Wo8Ldw4nsu6B7-jYryEKel0                mFYqAfOkhTqYB7Ik5hbWUiOiJkZWJpYW4vZmFzdGFxIiwiVVVJRCI6IjZlMGM4YWMyLWI1YTAtNDY1YS                1hMjNiLTNkYWJkODM0NDg4NyIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0wNS0wMlQxODowOT                o0Mi43Nzg2MTAxMDFaIn0%3D HTTP/1.1" 401 206 "" "docker/1.10.3 go/go1.5.3 git-comm                it/20f81dd kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64"
    time="2016-05-02T18:10:01.059159801Z" level=info msg="response completed" enviro                nment=development go.version=go1.4.3 http.request.host=docker-registry.genouest.                org http.request.id=48d77334-df09-4455-ae01-3a6b2e54ba21 http.request.method=GET                 http.request.remoteaddr=192.168.1.2 http.request.uri="/v2/debian/profphd-utils/                manifests/latest" http.request.useragent= http.response.contenttype="application                /json; charset=utf-8" http.response.duration=5.566366ms http.response.status=200                 http.response.written=5913 instance.id=46806730-87ba-44bc-b64f-bbc8226db7ad ser                vice=registry version=v2.2.0

An other extract OK from an other container in the same run:

    192.168.1.118 - - [02/May/2016:18:14:12 +0000] "POST /v2/debian/tree-ppuzzle/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64"
    time="2016-05-02T18:14:12.375956333Z" level=info msg="response completed" environment=development go.version=go1.4.3 http.request.host=docker-registry.genouest.org http.request.id=544d93f8-0b76-4426-b2b7-af125fafc325 http.request.method=PATCH http.request.remoteaddr=192.168.1.2 http.request.uri="/v2/debian/tree-ppuzzle/blobs/uploads/32b46e4f-93f7-47c7-8981-096623d0cb8b?_state=AHsxOWMNhh8uIHDAuTimdmr11s8ROuhnfcYE0GH-Wd17Ik5hbWUiOiJkZWJpYW4vdHJlZS1wcHV6emxlIiwiVVVJRCI6IjMyYjQ2ZTRmLTkzZjctNDdjNy04OTgxLTA5NjYyM2QwY2I4YiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNi0wNS0wMlQxODoxNDoxMi4zMjA3MDUxMjFaIn0%3D" http.request.useragent="docker/1.10.3 go/go1.5.3 git-commit/20f81dd kernel/3.10.0-229.20.1.el7.x86_64 os/linux arch/amd64" http.response.duration=6.209874ms http.response.status=202 http.response.written=0 instance.id=46806730-87ba-44bc-b64f-bbc8226db7ad service=registry version=v2.2.0

**Comment by RichardScothern** [comment]
hi @osallou I'm afraid you'll need to do some debugging on this one.

Do all of your requests have the correct header?  What is different between requests which succeed and those that fail?

**Comment by osallou** [comment]
I will try to debug, capturing requests on auth server and registry server. However, I only sent push requests for different containers in a loop. So all requests should be the same.
Will be difficult to track requests correlation between client/registry/auth server.

**Comment by osallou** [comment]
ok, I think I have found the problem. This related to Cross Repository Blob Mount

(POST /v2/<name>/blobs/uploads/?mount=<digest>&from=<repository name>)

I may have auth issues with such cases.

**Comment by janson087** [comment]
hi @osallou I have got the same problem. The same commond,the first time,it reports faile,but the second time,it report success.
[root@jg-pass-test ~]# docker push 192.168.54.65:5000/app9/zyhj:1
The push refers to a repository [192.168.54.65:5000/app9/zyhj]
5f70bf18a086: Preparing 
5f70bf18a086: Preparing 
b9f93792d25e: Preparing 
f3fa30e57418: Preparing 
0b9bfbb55232: Waiting 
7a73f1797def: Waiting 
ae416e88349d: Waiting 
035353e69114: Waiting 
unauthorized: authentication required
[root@jg-pass-test ~]# docker push 192.168.54.65:5000/app9/zyhj:1
The push refers to a repository [192.168.54.65:5000/app9/zyhj]
a81961db2082: Pushed 
5f70bf18a086: Pushed 
b9f93792d25e: Pushed 
f3fa30e57418: Pushed 
994e7e32f93c: Pushed 
0b9bfbb55232: Pushed 
7a73f1797def: Pushed 
ae416e88349d: Pushed 
035353e69114: Pushed 
1: digest: sha256:cd92a6290aea7a22a7ecfe44728071ef8ab383f91de9bf5deef0f54f8e693699 size: 3413
How do you reslove the problem

**Comment by osallou** [comment]
Issue for me was the modifications in the API. The request for authorization contained multiple scopes when a layer is based on the common layer of an other image. So, when anylising request, I had to modify my code to manage multiple **scope** parameter in GET request and check request access to each of those scopes instead of a single one.
