### ISSUE TITLE
Registry 2.4 Access Denied

### ISSUE THREAD

**Issue by schu** [docker/distribution#1699]
```
docker run --rm --name registry \
  -e REGISTRY_STORAGE=s3 \
  -e REGISTRY_STORAGE_S3_BUCKET=mubucket \
  -e REGISTRY_STORAGE_S3_REGION=eu-west-1 \
  -e REGISTRY_STORAGE_S3_ACCESSKEY=mykey \
  -e REGISTRY_STORAGE_S3_SECRETKEY=mysecret \
  -p 127.0.0.1:5000:5000 \
  registry:2
```

Above setup used to work up until version 2.3 (IAM config: https://gist.github.com/schu/eaf996ea8b88e0d88043), 2.4 fails with `AccessDenied` during `docker push ...`. Workaround is to downgrade to 2.3

Did something change about the required permissions?

**Comment by schu** [comment]
Difference between goamz and aws-sdk-go could also be the crux.

**Comment by RichardScothern** [comment]
hi @schu.  the aws-sdk go driver does require a [broader set of permissions: https://github.com/docker/distribution/blob/master/docs/storage-drivers/s3.md#s3-permission-scopes

yours is missing multipart upload permissions.

**Comment by schu** [comment]
Yes, working with updated permission set. Thanks!
