### ISSUE TITLE
Proposal: make linkedBlobStore optional

### ISSUE THREAD

**Issue by soltysh** [docker/distribution#1707]
#### The problem
OpenShift’s use case for docker registry is that it should only hold the data itself (blobs). All the necessary metadata is stored inside of OpenShift storage, including tags, authorization and image signatures. Unfortunately, the current implementation does not allow this, since it encapsulates `blobStore` (which is responsible for accessing the actual blobs) inside the `linkedBlobStore` (which manages metadata). Even more, since both `BlobStore`-s are private implementations one cannot turn them on or off on demand.

#### Proposed solution
Our proposed solution is to have an option to disable the `linkedBlobStore` through configuration. By default this option would be off, to maintain a fully functional registry, as is today. 

#### Alternative solution
Make both `blobStore` and `linkedBlobStore` implementations public, so that one is able to construct the storage as needed.

/fyi @vbatts @ncdc @miminar @pweil- @legionus

@stevvooe thoughts, since you're mostly involved in this part of distribution?

**Comment by stevvooe** [comment]
@soltysh I'd have to get more details to understand whether or not this makes sense. The `linkedBlobStore` manages repository access for blobs which are then linked into the `blobs/xxx` paths. Making either of these interfaces public is not a simple solution, as this model has access control to consider.

It may be sufficient to make a `blobStore` implementation available that gets injected into the middleware after access has been confirmed. The problem with that is you risk exposing data to other parties that don't have access. The blob store really needs to be framed by the repository, which `linkedBlobStore` does. You can't simply "disable" it and expect it to work correctly.

**Comment by soltysh** [comment]
@stevvooe I share your worries, but the thing with OpenShift's registry is that we already take care of all the authz/authn on the OpenShift side. Iow. OpenShift already handles for us all the necessary check. Even more it contains all the metadata about all the images we have in the repository. That's why we would like to have direct access to just the `blobStore`. Does that make sense?

**Comment by miminar** [comment]
@stevvooe I understand your concern. `linkedBlobStore` serves, among other things, as an authorization check for the blobs. Blob can be donwloaded only if it is tagged in the repository user is pulling from.

In OpenShift, we allow authenticated user with access to any repository to download any blob he wants if he has its digest. The authorization is done on the manifest level. 

Since the layer blobs are the only items stored in our registry storage, each blob globally accessible regardless of repository, the `linkedBlobStore` acts as unnecessary infringement.

**Comment by stevvooe** [comment]
@miminar @soltysh It sounds like you just need to be able to replace [`blobAccessController`](https://github.com/docker/distribution/blob/master/registry/storage/linkedblobstore.go#L28), which is just a [`linkedBlobStatter`](https://github.com/docker/distribution/blob/master/registry/storage/registry.go#L251).

It seems acceptable to have a registry option that takes a `BlobDescriptorService` that will be used instead. That can call out to the OpenShift implementation. See `NewCachedBlobStatter` for an example. It is the same principle.

**Comment by soltysh** [comment]
@stevvooe thanks for the pointer! I'll check it out and will get back.

**Comment by RichardScothern** [comment]
@miminar @soltysh : as well as customizing the `blobAccessController` for your own metadata you will probably want to override or remove the behavior of `linkBlob` which will no longer be required, but will cost a roundtrip to the backend.

**Comment by legionus** [comment]
In fact, we do not need to remove/replace `linkBlob` or `blobAccessController`. This problem can be solved by adding an option that allows you to turn off the blob links creation.

**Comment by stevvooe** [comment]
Assuming this was closed when merging #1734.

Re-open if there is more to do here.
