### ISSUE TITLE
Getting a Repository from a Registry object should have an error

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#171]
The Repository function from the Registry takes in a name and returns an repository without the option of an error. This function may require doing name parsing and resolution which may error out.

**Comment by stevvooe** [comment]
This method was this way because those calls were considered "protected" in the current case. As the uses expand, its clear a change is necessary. The signature should be as follows:

```
Repository(ctx context.Context, name string) (Repository, error)
```
