### ISSUE TITLE
When mapping too many ports then daemon failed

### ISSUE THREAD

**Issue by xczh** [docker/distribution#1715]
I wonder that if docker has limit on the max number of port-mapping.

when I exec this:
```sh
docker run -p 51000-52000:51000-52000 hello-world
```
then, the output is:

>docker: Error response from daemon: driver failed programming external connectivity on endpoint jovial_fermat (5d77c1cc0c4866dc8266ee2dfecf576703397179a2ec481f0cba4807ed5f5908): fork/exec /proc/self/exe: resource temporarily unavailable.

sometime is:
>docker: Error response from daemon: driver failed programming external connectivity on endpoint grave_roentgen (9418647aba299043fba3b1b52ecc44d8561e49c95c857f5befed83bd6677bff5): Error starting userland proxy:.

And what's worse is, this issue happened unscheduled on my workstation, which runs about 20 containers. It cause `HTTP 502 Bad GateWay` Error, but I cannot exec into the container, and also cannot start or restart the crashed container. The only way to resolve this is to restart docker daemon, and maybe few hours later, the error occur again.

I have run this command on docker 1.9.0:
```sh
docker run -p 51000-52000:51000-52000 hello-world
```
and It works out find, no error occur.
I feel really confused, and hope to find out why. 
Thanks a lot!

```sh
docker version
```

>Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64

>Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64

```

**Comment by dmcgowan** [comment]
This issue would be more appropriately filed on docker engine  https://github.com/docker/docker/issues
