### ISSUE TITLE
How to compose a container from a Image and layer in Docker 1.10

### ISSUE THREAD

**Issue by JackChen255** [docker/distribution#1720]
Two questions. Thanks in advance.
1: In V 1.10, how to get new layer ID after creating a new container from a image? In previous version, the layer ID is the same as container ID which is returned from RestAPI "POST /containers/create"? Looks like the new layer ID is saved in the last item in manifest.json, but this assumption is not safe.
2: How to restore a container from an Image and above layer.tar? RestAPI "PUT /containers/(id or name)/archive" may only handles a normal tar file instead of lay.tar, and it can't handle the deleted files in the new container.

**Comment by dmcgowan** [comment]
1. A layer ID is created when a container is committed. At that point the changes to the container are snapshotted, put into a new layer, and its layer ID is calculated from the content. This is the ID you will find in the manifest.
2. Individual layers are not imported from an image to create a container or new image. If you want to create a new image with a single layer you can use `docker import`. If you want to "restore" a container from a tar file, you will need to create a new container from the targeted image and unpack your tar file in the image (see https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#extract-an-archive-of-files-or-folders-to-a-directory-in-a-container). Images are normally "restored" with all of its layers as layer.tar entries in a image tar file created from `docker save`.

I would encourage questions like these to be asked at https://forums.docker.com/ in the future. They can be better directed as this question is not really related to the distribution project, but more relevant to the main docker project.

**Comment by JackChen255** [comment]
Thanks. But I can't use PUT archive API to extract a tar ball to container root directory /. In curl request message, the extract destination path was always extended by tar ball name, e.g. /layer.tar. Then the server side can't complaints that "lstat /var/lib/docker/devicemap/mnt/containerID/rootfs/layer.tar: no such file or directory". By the way, I can use PUT to extract it to non root directory, e.g. /tmp/. 

Why the destination path in PUT command was always extended by tar ball name? Thanks.

Output of docker version:
Client:
Version: 1.10.3
API version: 1.22
Go version: go1.5.3
Git commit: 20f81dd
Built: Thu Mar 10 15:39:25 2016
OS/Arch: linux/amd64

Server:
Version: 1.10.3
API version: 1.22
Go version: go1.5.3
Git commit: 20f81dd
Built: Thu Mar 10 15:39:25 2016
OS/Arch: linux/amd64

Steps to reproduce the issue:
1.curl -s -XPUT -T layer.tar 0.0.0.0:42431/containers/04c9ac705ca0/archive?path=/
//Only root dir / is specified in above path field in PUT command, but the path was changed to path=/layer.tar

```
About to connect() to 0.0.0.0 port 42431 (#0)
Trying 0.0.0.0...
Connected to 0.0.0.0 (0.0.0.0) port 42431 (#0) > PUT /containers/04c9ac705ca0/archive?path=/layer.tar HTTP/1.1 > User-Agent: curl/7.29.0 > Host: 0.0.0.0:42431 > Accept: / > Content-Length: 62464 > Expect: 100-continue > < HTTP/1.1 404 Not Found < Content-Type: text/plain; charset=utf-8 < Server: Docker/1.10.3 (linux) < X-Content-Type-Options: nosniff < Date: Fri, 13 May 2016 21:19:13 GMT < Content-Length: 148 < Connection: close 2. 3.
```
Describe the results you received:
In the server side, it can't find rootfs/layer.tar.
```
DEBU[175614] Calling PUT /containers/04c9ac705ca0/archive
DEBU[175614] PUT /containers/04c9ac705ca0/archive?path=/layer.tar
DEBU[175614] container mounted via layerStore: /var/lib/docker/devicemapper/mnt/375d0bc5401eedfc9a3dce6c8ded065820fadcac57f5f39333336f05a719bdd7/rootfs
DEBU[175614] devmapper: UnmountDevice(hash=375d0bc5401eedfc9a3dce6c8ded065820fadcac57f5f39333336f05a719bdd7)
DEBU[175614] devmapper: UnmountDevice(hash=375d0bc5401eedfc9a3dce6c8ded065820fadcac57f5f39333336f05a719bdd7) END
ERRO[175614] Handler for PUT /containers/04c9ac705ca0/archive returned error: lstat /var/lib/docker/devicemapper/mnt/375d0bc5401eedfc9a3dce6c8ded065820fadcac57f5f39333336f05a719bdd7/rootfs/layer.tar: no such file or directory
```

**Comment by JackChen255** [comment]
I can extract files to root directory with path=%2F "curl -s -XPUT -T layer.tar 0.0.0.0:42431/containers/04c9ac705ca0/archive?path=%2F -v". But path=/ still doesn't work.
