### ISSUE TITLE
Is docker registry v2.0+ suport private registry mirror for private registry

### ISSUE THREAD

**Issue by kinglion811** [docker/distribution#1724]
I have a requiement:
In my work sence，I have a center private registry in one date center ,and some mirror registry in other data centers,as we know registry v1.0 suport private registry mirror for private registry.When the v2.0+ suport this feature.

thanks!

**Comment by dmcgowan** [comment]
@kinglion811 it is still in the design phase so it will not make it into the next release. Once we have a PR for the design we will have a better idea of which release it will make it into. The limitation is also on the docker engine so it will require a specific new version of docker when it is implemented.

**Comment by llamahunter** [comment]
I think the master issue is #1431

**Comment by llamahunter** [comment]
And perhaps https://github.com/docker/docker/issues/18818
