### ISSUE TITLE
what's the roadmap for distribution 1.20?

### ISSUE THREAD

**Issue by redhatlinux10** [docker/distribution#1727]
there isn't any roadmap in https://github.com/docker/distribution/wiki.
i know `Docker Registry v2.4.1-rc.2` has been released a few days ago, and this means this new final release version of Docker Registry will come very soon. but still i wanna know what's the roadmap of distribution 1.20.

**Comment by dmcgowan** [comment]
Checkout the milestones https://github.com/docker/distribution/milestones/Registry/2.5. They are not always completely up to date but we try to create issues for the major items and put them into a milestone. Not sure what "distribution 1.20" is, the next release will be 2.5 and timed around Docker 1.12.
Going to keep this issue open until we verify the milestones are updated.

**Comment by redhatlinux10** [comment]
>Not sure what "distribution 1.20" is

`distribution 1.10` is this github project's version number, it corresponds to  `Registry v2.3` Release.so i think the next version to `distribution 1.10` should be `distribution 1.20` and corresponds to `Registry V2.4`

**Comment by RichardScothern** [comment]
Milestones updated.
