### ISSUE TITLE
Public repository tag list returns unauthorized?

### ISSUE THREAD

**Issue by paralin** [docker/distribution#1737]
Why, when I try to list the tags on a library image, do I get an unauthorized response?

https://registry.hub.docker.com/v2/library/mongo/tags/list

```json
{
   "errors":[
      {
         "code":"UNAUTHORIZED",
         "message":"authentication required",
         "detail":[
            {
               "Type":"repository",
               "Name":"library/mongo",
               "Action":"pull"
            }
         ]
      }
   ]
}
```

**Comment by RichardScothern** [comment]
hi @paralin .  This is a hub issue.  The best place to find an answer is here: https://hub.docker.com/help/

**Comment by dmcgowan** [comment]
@paralin the registry you are talking to requires a token, look at the authenticate header.

```
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:library/mongo:pull"
Date: Wed, 08 Jun 2016 18:07:52 GMT
Content-Length: 145
Strict-Transport-Security: max-age=31536000
 
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Name":"library/mongo","Action":"pull"}]}]}
```

Tokens may be retrieved for anonymous users in this case but it is the authentication server which decides that, the registry just expects a token.

**Comment by gbougeard** [comment]
@dmcgowan I have the same issue.

I configured `docker_auth` as authentication server, allowed anonymous users to pull and access the catalog.
When I try to access the catalog through browser and curl I'm getting a 401.
When I check the registry logs and docker_auth ones, it seems the registry never check the authentication server when curling nor browsing. 
Is it normal? I was expecting it checks the authentication server even when accessing the registry through curl or a browser.
