### ISSUE TITLE
Github Enterprise Integrations: Oauth2 Authentication + Build Webhooks

### ISSUE THREAD

**Issue by marcellodesales** [docker/distribution#1747]
Hi there,

We'd like to have the following:

1. Authenticate Users using OAuth2 from GitHub Enterprise (https://github.mycompany.net)
2. Allow users to create Image Repos based on user's GitHub Enterprise Repos
3. Allow Repos, created on step 2, to send a Webhook call to the Registry to trigger a new Image Build based on the Dockerfile present in the GitRepo

This is the minimum for building Dockerfile...

thanks
Marcello

**Comment by RichardScothern** [comment]
This is an issue tracker for the distribution project.  If you would like to build a system I suggest you read the documentation and ask any questions on the forums or IRC channel.  

I'm closing this since there is no actionable issue.

**Comment by dmcgowan** [comment]
I agree with Richard that anything related to a build system is out of scope.

However I have begun the specification work which will enable 1 and 2 to be possible. Enabling full OAuth2 support is a goal and it will allow integration with github oauth. See https://github.com/docker/distribution/pull/1708. Also have a prototype I will share after that specification is accepted.

**Comment by marcellodesales** [comment]
@dmcgowan Thanks for verifying this... I've been looking for 1 and 2 as a MUST before our company can adopt the Trusted registry.... I read more around 3...
