### ISSUE TITLE
storage/driver/azure: Update to azure-sdk-for-go 2.x

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/distribution#175]
https://github.com/MSOpenTech/azure-sdk-for-go has a breaking change in its newer releases (see PR 41). Once updated to latest, import paths and several pointer usages must be fixed.

I'll do that sometime (assign to me, please). It's not really urgent as no new functionality added or anything is fixed.

**Comment by dmp42** [comment]
@ahmetalpbalkan do you want this to happen before docker/1.6 release?

**Comment by ahmetalpbalkan** [comment]
@dmp42 hmm, I think it's not really required at this point. It can stay as is. I did not have a chance/time to spin up a registry with azure driver and try it with docker master binaries, though. :sob:

**Comment by dmp42** [comment]
Ok, n.p.
Thanks Ahmet.

**Comment by stevvooe** [comment]
@ahmetalpbalkan Will you have bandwidth to get this together for 2.1 or should I move it off this milestone?

**Comment by ahmetalpbalkan** [comment]
Please let's move off. We haven't settled on a stable API in the rewrite yet. Thanks.

**Comment by ahmetalpbalkan** [comment]
Closed via #623.
