### ISSUE TITLE
Changing UTC timezone in webgui

### ISSUE THREAD

**Issue by EvertMDC** [docker/distribution#1751]
Hello,

The 'Pushed at' of a repository is fixed at UTC and cannot be changed to another timezone.
Is it possible to add this as a feature?

My setup:
- Both my portus and registry containers are using the correct TZ.
- using registry version 2.1
- portus version 2.1.0-dev

I haven't found an issue open for this.

**Comment by dmcgowan** [comment]
If you want changes to a particular web UI, you need to open up an issue there. It sounds like your request is related to Portus. This registry does not ship with a UI and the API does not use different timezones.
