### ISSUE TITLE
'pushed at' not updated when pushing image with same tag

### ISSUE THREAD

**Issue by EvertMDC** [docker/distribution#1753]
This is quite strange behaviour since registry handles the push as you'd expect it to.

my setup:
portus 2.1.0-dev
registry 2.1
Webhooks never worked for me so there must be an issue with the 5-minute catalog.

I tested this by pushing an image, adding one file to the root of it's filesystem, commiting it, pushing it to the registry, removing it from my images and pulling it again.

There does not seem to be an issue open for this.

**Comment by RichardScothern** [comment]
*Please follow these instructions to help us diagnose your issue*

 1. create a new issue, with a succinct title that describes your issue:
   - bad title: "It doesn't work with my docker"
   - good title: "Private registry push fail: 400 error with E_INVALID_DIGEST"
 2. copy the output of:
   - `docker version`
   - `docker info`
   - `docker exec <registry-container> registry -version`
 3. copy the command line you used to launch your Registry
 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6. if relevant, copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 8. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry

**Comment by EvertMDC** [comment]
Sorry this can be closed, I should have posted an issue on the portus page
