### ISSUE TITLE
registry/storage: Add package level error for Seek not supported

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#176]
Not all implementations of the storage interface will be able to implement Seek.  When seek is not supported, resumable push or pull code should get an error from the Seek function and be able to determine a restart is necessary.

Example definition
~~~go
var (
	// ErrSeekNotSupported is used when an attempt to seek is done
	// on a layer which does not support it. This allows attempts
	// to resume an upload or download to know to fail or restart.
	ErrSeekNotSupported = errors.New("seek not supported")
)
~~~

**Comment by stevvooe** [comment]
Which implementations don't support `Seek`? We've made this a requirement for backends.

**Comment by dmcgowan** [comment]
I am attempting to make create a V1 compatible implementation of the storage interface.  I understand the drivers should have this requirement.

**Comment by stevvooe** [comment]
This would be at the `Layer` level. Does this condition correspond to an unreadable layer or an inflexible remote (ie, v1 upload)?

**Comment by dmcgowan** [comment]
Was thinking at the Layer level, but seems able to be mitigated through buffering. And as you mentioned in the write case, it could be better to allow seek then error on write.
