### ISSUE TITLE
Execute the garbage-collect command delete image，push again，can not pull

### ISSUE THREAD

**Issue by LuckStone** [docker/distribution#1761]
I found that  the manifest did not push success.

Restart the container, and push again, it ok.

**Comment by RichardScothern** [comment]
@LuckStone : can you test with the schema1 signature store disabled?  There is a known bug which I think you are hitting.

https://docs.docker.com/registry/configuration/#schema1

**Comment by RichardScothern** [comment]
i'm closing this for now.  @LuckStone please try the suggestion above.
