### ISSUE TITLE
Error during Container Creation

### ISSUE THREAD

**Issue by brian-bason** [docker/distribution#1763]
I would like to report an issue on Docker during the creation of a container (extraction of downloaded images).

I was creating a new container in my Docker Host with a stack of images which were not on the host yet so they were downloaded from our private Docker Registry. During the extraction process of the images to the local hard drive I had a power failure and thus the creation of the container was interrupted. When I tried to restart the process again, after I powered the device, the process failed when it was trying to extract the images to local drive. The issue can be seen below.

d38575f188e0: Pull complete 
b04ea90f261c: Extracting [==================================================>] 71.48 kB/71.48 kB
40dc9cd44ffa: Download complete 
a3ed95caeb02: Download complete 
8e785886e18d: Download complete 
b07fa5f3bf49: Download complete 
f468d5b9f05f: Download complete 
794bd688a6d9: Download complete 
8bbe83ec74cb: Download complete 
1233bc44b903: Download complete 
085e07914846: Download complete 
failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/layer-389359348 /var/lib/docker/image/aufs/layerdb/sha256/68bad316357227af4d130e4e6b73a25b69984bdbdec8fc581990ac56aa04b3ca: directory not empty

How to replicate

Start a creation of an container with images that are not on the local drive yet (docker create --name example --restart=always --stop-signal=INT private-docker-registry/example:1.1.0)
During the extraction of the downloaded images interrupt the process with a power failure (or by killing the process)
Try to restart the creation of the container again issuing the same command as used in step one
When the process comes to the extraction step it will fail with the reported issue.

It would be great if the process can determine if the current folder that exists for the image is corrupted or incomplete and if so delete it to create the new folder again. This would make sure that the host doesn’t end in this limbo state where you have to SSH into the box to delete the folder manually before re-trying the command.

**Comment by RichardScothern** [comment]
hi @brian-bason : can you post your issue in the docker repository? https://github.com/docker/docker
Container creation is the domain of the docker engine, not the registry.

**Comment by brian-bason** [comment]
Thanks will do that.
