### ISSUE TITLE
docker_container, absent + force doesn't work properly

### ISSUE THREAD

**Issue by m4dm4rtig4n** [docker/distribution#1768]
Hi, 

With module docker_container, when I try to (interactive mode) :
- Start 2 containers (same template, just name change)
- Delete 2 containers

Firsts container return, "device or resource busy" with Dead status.
And it's work correctly on second....

`failed: [DEBIANVM] (item={u'reset': 1, u'roles': u'mysql', u'image': u'debian', u'hostname': u'local_docker_mysql', u'ports': [3306], u'volumes': [u'/var', u'/root'], u'expose': [22]}) => {"failed": true, "item": {"expose": [22], "hostname": "local_docker_mysql", "image": "debian", "ports": [3306], "reset": 1, "roles": "mysql", "volumes": ["/var", "/root"]}, "msg": "Error removing container 9e90557bd3fe27187d3d5c33b97f275407921b3258f1310f5713c7db20dbaa53: 500 Server Error: Internal Server Error (\"Unable to remove filesystem for 9e90557bd3fe27187d3d5c33b97f275407921b3258f1310f5713c7db20dbaa53: remove /var/lib/docker/containers/9e90557bd3fe27187d3d5c33b97f275407921b3258f1310f5713c7db20dbaa53/shm: device or resource busy\")"}
changed: [DEBIANVM] => (item={u'reset': 1, u'roles': u'apache', u'image': u'debian', u'hostname': u'local_docker_apache', u'volumes': [u'/var', u'/root'], u'expose': [22, 80]})
`

The containers have exactly same template oO

Run command : /bin/bash

I have try with Ansible Version : 2.1 & 2.2

**Comment by RichardScothern** [comment]
hi @m4dm4rtig4n This is the issue tracker for the distribution project.  Your problem (probably) lies within Ansible, so I suggest you try filing this at the ansible project.
