### ISSUE TITLE
Building a project is not a recipe

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#1776]
building.md was moved to recipes. That is the wrong spot for it. This should not be in the docs tree, as its clearly they don't know where to put it.

Move to BUILDING.md at the top-level.

https://github.com/docker/distribution/blob/1b9ab303a477ded9bdd3fc97e9119fa8f9e58fca/docs/recipes/building.md
@SvenDowideit

**Comment by zhouhaibing089** [comment]
Agree..
