### ISSUE TITLE
Define trust interface

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#178]
The trust interface will be used to verify content from the registry.  The primary goal of the interface is to verify a tag object correctly matches the name/tag pair which was used to retrieve it. This will be achieved through checking signatures for the tag object. However the interface should support a variety of media types.

An example interface
~~~go
type TrustDescriptor struct {
	Size int
	Digest digest.Digest
	MediaType string    
}

type Trust interface {
	Verify(*TrustDescriptor, io.Reader, []libtrust.Signature)
}
~~~

**Comment by stevvooe** [comment]
`TrustDescriptor` is general enough to belong in the "github.com/docker/distribution" package as `Descriptor`.

Small nit: don't use pointers for structs unless you need to modify them.

**Comment by endophage** [comment]
I believe we're all agreed on TUF. Are we happy to close this with that understanding? c.f. github.com/endophage/go-tuf/

**Comment by dmcgowan** [comment]
@endophage let's close this next week after we have made more progress on the client interface. We will still require a client-side interface for using TUF which is integrated with the defined Distribution interface.

**Comment by endophage** [comment]
Sounds good. I'm hoping we can directly use the client as implemented in go-tuf. We may not use the whole implementation but we should be able to leverage most of it.

**Comment by stevvooe** [comment]
@endophage To clarify, I'd still like to see a clear boundary between trust and distribution. We'd like to be able to switch out TUF, at least at a code level, even if we don't plan to.

**Comment by stevvooe** [comment]
What should be we do here? Ideally, the distribution project makes a client available that seamlessly integrates with notary.

**Comment by dmcgowan** [comment]
I think we could add seemless integration. As we try and move some of the registry related object down to the docker cli (where notary is), then it would make sense to bury the implementation of trusted reference behind distribution interfaces.

**Comment by stevvooe** [comment]
@dmcgowan Let's add a section to the ROADMAP.md. I'll close that when a PR gets submitted.
