### ISSUE TITLE
Docker Windows installer should suggest the target directory for Docker Machine

### ISSUE THREAD

**Issue by averri** [docker/distribution#1781]
As an user of Docker, I would like the installer to suggest the target directory for Docker Machine, and allow me to change it. Actually, the installer assume the directory `C:\Users\<userHome>\.docker` as a target, which is not always the best place to set it.

**Comment by RichardScothern** [comment]
@averri I'm afraid this is not the correct repository.  Distribution is the project for distributing docker content (for `docker pull` etc), not Docker itself.
