### ISSUE TITLE
Docker private registry make too many AWS S3 LIST Requests

### ISSUE THREAD

**Issue by TimeInvestor** [docker/distribution#1784]
Hi Docker team,
We have set up our own Docker private registry (v2) with AWS S3 as the backend storage.
We have observed that there are many S3 LIST requests made to the S3 bucket which probably means Docker registry is keeping scanning objects in the bucket for some purpose.
Can anyone help point out why it is doing this? and any optimization we can do to reduce the number of calls (and save cost)?

**Comment by RichardScothern** [comment]
*Please follow these instructions to help us diagnose your issue*

 1. create a new issue, with a succinct title that describes your issue:
   - bad title: "It doesn't work with my docker"
   - good title: "Private registry push fail: 400 error with E_INVALID_DIGEST"
 2. copy the output of:
   - `docker version`
   - `docker info`
   - `docker exec <registry-container> registry -version`
 3. copy the command line you used to launch your Registry
 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6. if relevant, copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 8. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry

**Comment by Jerredr** [comment]
Hi @TimeInvestor,
we're facing a similar issue where we see a huge amount of LIST requests reported by S3. Did you end up finding the cause of this?

**Comment by TimeInvestor** [comment]
The root cause for our issue is that we accidentally have local Docker registry set up in our AMI (AWS Image Instance). Hence, each time we boot up a machine using that AMI, the machine tries to initialise local Docker registry and cause S3 LIST request.

**Comment by vbezhenar** [comment]
I have this issue too. I'm using simple docker registry for very small installation and it does around 10k list requests per day according to my provider statistics. That's with 500 get requests and 55 put requests and 250 MB egress. It's not a lot but this list request spending is like 99.9% of my S3 expenses.

**Comment by vbezhenar** [comment]
I had similar issue. It turned out that /debug/health health check checked S3 health every 10 seconds and it caused this excessive traffic. I set `REGISTRY_HEALTH_STORAGEDRIVER_INTERVAL=15m` and it seems to solve this issue.

**Comment by xdkaka** [comment]
+1
