### ISSUE TITLE
Query: why doesn't restarting a container not update linked containers' env vars

### ISSUE THREAD

**Issue by sbose78** [docker/distribution#1790]
Hi,
I have a query:

"Unlike host entries in the /etc/hosts file, IP addresses stored in the environment variables are not 
automatically updated if the source container is restarted."

https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

Any reason why this isn't being automatically updated? Is there a design constraint?

Thanks,
Shoubhik

**Comment by dmcgowan** [comment]
Networking related issues are best filed under the [engine](https://github.com/docker/docker) or [libnetwork](https://github.com/docker/libnetwork)

**Comment by sbose78** [comment]
Oops, sorry. Did this by mistake.
