### ISSUE TITLE
Docker Hub V1 API is not returning all the tags

### ISSUE THREAD

**Issue by Maxwell2022** [docker/distribution#1795]
I have a script that generate a data container base on a version of my `package.json` (to avoid installing npm modules if there is no new modules). I have a script that check if there is a container in docker hub for the current version of my `package.json`. This script is doing a curl request to get all the available tags of my image. It's a public container so I don't need authentication. 

It was working great the first few weeks but now I can see that tags returned by the API are missing.
`https://index.docker.io/v1/repositories/maxwell2022/tuna-solutions-api-data-dev/tags` is only returning 5 tags. 

```
[
  {
    "layer": "97dde7ca",
    "name": "0514e84fe1"
  },
  {
    "layer": "5cceba5d",
    "name": "223261f5d5"
  },
  {
    "layer": "cfe67742",
    "name": "7a8232d99c"
  },
  {
    "layer": "334ad2ee",
    "name": "7accd171a3"
  },
  {
    "layer": "082a28bf",
    "name": "e0b1759ef6"
  }
]
```

However there is more than this more: 
https://hub.docker.com/r/maxwell2022/tuna-solutions-api-data-dev/tags/

I've looked into `v2` API of the docker registry, and it's returning the expected tags. However I don't really want to use v2 because it requires authentication even for public containers. Alslo the token delivered is valid just for a minute or so.

I tried to look if there were some sorting or limit parameter for `v1` but I could not find anything. Also if I tried to request a specific tag that does exists, I get a 404 page:

`https://index.docker.io/v1/repositories/maxwell2022/tuna-solutions-api-data-dev/tags/0b69706847`

> Tag not found

**Comment by dmcgowan** [comment]
The `v1` API has been deprecated and you will need to switch to the `v2` to get the full list of tags. The registry implementations are completely different and images pushed to `v2` will not necessarily be available via the `v1` API. This is a decision by registry operators and I believe the hub turned off `v2` to `v1` sync awhile ago. If you are unsure you can contact support for the hub.

As for the tokens, I think you are right that the hub is giving out tokens with pretty short expirations. This is also a decision by registry operators and I think this may be more configurable in the future. My advice would be to build in token caching and fetching into your transport code and just go with `v2`. If you are using go you can use the implementation in this repository, if other languages I am not sure what is available to you.

**Comment by Maxwell2022** [comment]
Thanks for the quick clarification @dmcgowan.

I've ended up using V2 requesting a new token each time I want to request the list of tags. I'm using a Makefile for my scripts so it's not trivial to enable caching. Also because there is no information about the validity duration of the delivered token, it's difficult to know for how long we can cache this token. I'm thinking building an internal API to simplify our Makefile.

Thanks again, 
Maxime
