### ISSUE TITLE
Is there a way to delete a tag over API?

### ISSUE THREAD

**Issue by sergeyfd** [docker/distribution#1801]
Hello,

Registry supports deleting images by manifests. Is there a way to delete a tag in the registry?

Thanks.

**Comment by dmcgowan** [comment]
Indeed there is, see https://github.com/docker/distribution/issues/1566#issuecomment-205484205

We also added a feature in the Go registry client to make getting the digest to delete by easier, https://github.com/docker/distribution/pull/1775.

**Comment by dmcgowan** [comment]
If you are only trying to remove the tag -> digest reference, there is nothing in the API to just do that. Note if you are trying to do that for cleanup, this may cause images to be cleaned up if you run a garbage collect.

**Comment by sergeyfd** [comment]
Found my problem. I did not notice that staring from 2.3 one as to use ""Accept: application/vnd.docker.distribution.manifest.v2+json" header to get the correct digest.

Thanks.
