### ISSUE TITLE
Proposal: Share layers across docker registry repos

### ISSUE THREAD

**Issue by vinay-g** [docker/distribution#1802]
Currently I see that if I push an image with `A` with layer `X` into registry.
If I retag the image from `A` to `B` and push the entire image gets pushed with all the layers, ideally since it is the same layer it could be shared and only the meta info could be pushed. 

I am not sure if this is possible, may cause issues with delete. 
It would be a nice option.

**Comment by dmcgowan** [comment]
@vinay-g this is already how the registry works. We added a feature cause "cross repository push" which prevents an engine from having to push up the same layers to a registry which had been previously pulled. Even when layers are pushed, in the registry backend already has that layer, it is not stored twice, only a link is created. The registry cannot try to be any smarter here for security reasons, an engine must prove they have the layer content by either sending the layer OR providing a source repository for the layer along with read access to that repository in the token.

If you are not seeing layers mounted across repository, please make sure to update your registry to at least 2.3.

**Comment by vinay-g** [comment]
Thanks for the quick reply @dmcgowan. I was using 2.0.
Thank you, can I close the issue ?

**Comment by dmcgowan** [comment]
If it is working for you now please close the issue, thanks :smile_cat:
