### ISSUE TITLE
How to get the layer depths and total size by parent layer id?

### ISSUE THREAD

**Issue by duyanghao** [docker/distribution#1810]
As mentioned above,**I want to get the layer depths and size of a image by its parent layer id**.
Considering the following situation:
I have a image in the registry v2 called xxx/busybox, and i want to get its layer depths and total size from registry v2. i will perform the following steps:
1. get the image xxx/busybox layer id  and its parent layer id.
2. get the image xxx/busybox layer size by its layer id
3. perform the 1,2 steps for its parent layer id until reaching the top layer
**4. the total size of this xxx/busybox is the sum of its layer size and its parents layers size;
       the layer depths are the loop times of performing 1,2 steps.**
but as far as i know,there are not valid apis on the side of registry v2 for me to achieve the above steps. 
Is there any way to meet my goals?urgently!!!

**Comment by RichardScothern** [comment]
You are correct in your assessment.  Distribution treats the data it stores opaquely objects and therefore there are no APIs for dealing with the contents.  Doing so would restrict the extensibility of the registry.  

You can use the current APIs to download distribution content and perform any actions on those that you wish.

**Comment by duyanghao** [comment]
But, How can i know the depths of a image,you know,it is the quite important information in the practical application,especially when the image has big layer depths. 

**I want to merge the layers to one when the layer depths reach the upper limit !**

**Comment by duyanghao** [comment]
And could you answer the following question about the image layer parents?
https://github.com/docker/distribution/issues/1575#issuecomment-213364009
If i know the numbers of the iamge parents,that means i will get the depths of its layers.
And I can get the layer size by `HEAD /v2/<name>/blobs/<digest>
`

**Comment by RichardScothern** [comment]
@duyanghao the manifest formats are specified [here](https://docs.docker.com/registry/spec/manifest-v2-1/) and [here](https://docs.docker.com/registry/spec/manifest-v2-1/).  Given this information and the registry APIs for fetching and stat-ing manifests and layers, why can't you achieve your goals?

**Comment by duyanghao** [comment]
Could you answer the following question?
Why there are exist the same digest in the /v2/<name>/manifests/<tag> http response?
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/octet-stream",
      "size": 2398,
      "digest": "sha256:55d1ee70345b7190b59311fc9e783ac7329aeab3478fdea18c521ff9de95565c"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 66390854,
         "digest": "sha256:3b231ed5aa2f1631b3189f15f215fad43e35ec4aa56ee7bb92b9dd1b73ca94cb"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      }
   ]
}
```

**Comment by dmcgowan** [comment]
> Why there are exist the same digest in the /v2/<name>/manifests/<tag> http response?

This digest is represents a layer diff, the same diff can occur multiple times in an image especially in the case of empty layers. We have tried to remove empty layers from the configs but many are kept in older images for compatibility. The layer identifier used within the engine will end up being a sum based on the current layer and all previous layers, leading to a unique identifier per layer.

> what is the base layer digest of this image?

The first layer in the list is the base layer, as common with many Docker files, the base layer ends up not having any data as it only add metadata. We have made changes to ensure these don't need to be included but that is not always the case. 

> where are all layers of this image?

The layer tar balls are stored in the registry's blob store and on the engine the tar balls are extracted into the graph driver. Information about each layer can be found in the manifest you listed, as well as in the image configuration under the "config" key.

> Could you list them from top layer digest to base layer digest? Is the order of the valid digests from bottom to top in accordance with the order of the layers generated?

The layers are ordered from base layer to top most layer. The ordering with the json manifest are important and will not be reordered as it would cause the layers to applied in the incorrect order, causing a validation failure.

**Comment by duyanghao** [comment]
So,you means,in this example,the parent layers from base to top is below:
```
"digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
"digest": "sha256:3b231ed5aa2f1631b3189f15f215fad43e35ec4aa56ee7bb92b9dd1b73ca94cb" "digest": "sha256:55d1ee70345b7190b59311fc9e783ac7329aeab3478fdea18c521ff9de95565c"
```
and the latest top parent layer digest for this image is:
`"digest": "sha256:3b231ed5aa2f1631b3189f15f215fad43e35ec4aa56ee7bb92b9dd1b73ca94cb"`
Is that right?

**Comment by duyanghao** [comment]
And Could i understand that the **actual top most layer digest** is the **nonredundant digest** in 

> the end of layers list

?

**Comment by duyanghao** [comment]
```
[root@cn-sh-radosgw-test1 ~]# docker images|grep xxx
xxx/fightingdu/test_for_parent   2.0                 2b701a9b707a        24 minutes ago      190.6 MB
xxx/fightingdu/test_for_parent   1.0                 2df000769c4e        30 minutes ago      190.6 MB
xxx/fightingdu/centos            centos6             55d1ee70345b        8 months ago        190.6 MB
```
the top most parent of the image **xxx/fightingdu/test_for_parent:1.0**  is **xxx/fightingdu/centos:centos6**,that means the top most parent layer digest of **xxx/fightingdu/test_for_parent:1.0** should be the image id of **xxx/fightingdu/centos:centos6** as below:

> sha256:55d1ee70345b7190b59311fc9e783ac7329aeab3478fdea18c521ff9de95565c

here is the manifests result for image **xxx/fightingdu/test_for_parent:1.0**  :fs

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/octet-stream",
      "size": 2740,
      "digest": "sha256:2df000769c4eb688ca4b20f219c09aff024d0dd6ba4af9ac82c7a02f38a61e5d"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 66390854,
         "digest": "sha256:3b231ed5aa2f1631b3189f15f215fad43e35ec4aa56ee7bb92b9dd1b73ca94cb"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 155,
         "digest": "sha256:9b422f3b209a319fb52601838416533a9a5f51625f63b08cf6292e9204a1f476"
      }
   ]
}
```
but the problem is that there is no digest:sha256:55d1ee70345b7190b59311fc9e783ac7329aeab3478fdea18c521ff9de95565c
in the layers list!

**Comment by dmcgowan** [comment]
I understand the confusion, since we moved to content addressable identifiers for images, the parent image id can not longer be seen in the manifest. 

The image id refers to an image configuration, the spec for that can be seen here https://github.com/docker/docker/blob/master/image/spec/v1.1.md. Each image will have it's own configuration and does not refer to its parent configuration. Rather it refers to its layers which will include the layers from the parent. The image configuration may be derived from the parent, but it is not directly inherited like the layers are.

The manifest that you pointed to is a schema 2 manifest described here https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md. The schema 2 manifest refers to a single image configuration, and the hash of the distribution artifacts for the layers (gzipped tars in this case). These artifacts when unpacked into the storage driver must produce the content hashes referred to by the image configuration. Since multiple distribution artifacts can represent the same on disk content (due to differences in the way content is packed or compressed), the best way to establish the parental hierarchy of an image is to match based on the layers as specified in the image configuration (`rootfs.diff_ids`). 

Please let us know how we can make these answers more accessible since this is a common source of confusion. The documentation has been written, but it is not easy to find.

**Comment by duyanghao** [comment]
Sorry, i am afraid that i have not gotten your meanings,but could you directly tell me how to get the top most parent layer digest of one specified image from the docker/distribution? 
And, could you tell me how to get the layer depths of one specified image from docker/distribution?
I need to know the layers depths of one specified image,when the layers depths reach the top limit,I will merge all layers of that image into only one layer,that is important in the practical application of my company!

**Comment by dmcgowan** [comment]
Layer depth can be found in the image manifest as the length of the `layers` array (https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md). Additionally the layer depth can also be found in the image config as the length of the `rootfs.diff_ids` array (https://github.com/docker/docker/blob/master/image/spec/v1.1.md). I encourage you to ask these sort of questions on [irc](https://github.com/docker/distribution#support).

**Comment by duyanghao** [comment]
There is no `rootfs.diff_ids` in the image config of docker(1.10+),
Additional,Could you answer the following question?
How to get the `top most parent layer digest` of one specified image from the docker/distribution?

And as you said,the layer depth is length of `layers` array,in my example the depth of this image is six,right?

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/octet-stream",
      "size": 2740,
      "digest": "sha256:2df000769c4eb688ca4b20f219c09aff024d0dd6ba4af9ac82c7a02f38a61e5d"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 66390854,
         "digest": "sha256:3b231ed5aa2f1631b3189f15f215fad43e35ec4aa56ee7bb92b9dd1b73ca94cb"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 155,
         "digest": "sha256:9b422f3b209a319fb52601838416533a9a5f51625f63b08cf6292e9204a1f476"
      }
   ]
}
```

**Comment by dmcgowan** [comment]
As mentioned previously, the digests just represent a diff to create the layer. If the layers are empty, they will have the same digest since there is no content to differentiate them. This image has 6 layers, the manifest represents the source of truth for it. These layers can be squashed but please take a look at the image configuration (has the digest `sha256:2df000769c4eb688ca4b20f219c09aff024d0dd6ba4af9ac82c7a02f38a61e5d`). This will have the  key `rootfs.diff_ids`. After you squash the image id will be different and it will be considered a different image since the number of layers would not longer be 6.

As for top most layer, the array is ordered from base layer to top most layer as the documentation says. Therefore the top most layer is `sha256:9b422f3b209a319fb52601838416533a9a5f51625f63b08cf6292e9204a1f476` and you could consider the `parent` of that layer the one immediate before it `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`.

**Comment by borzamircea** [comment]
@duyanghao Hey! How did you manage to get the `manifests` for v2? Tried something like  `https://registry.hub.docker.com/v2/repositories/shipyard/shipyard/manifests/latest` with the proper `Accept` header, but got nothing. Any insights? TY!

**Comment by duyanghao** [comment]
@borzamircea  you can change the http head as belows:
`Accept: application/vnd.docker.distribution.manifest.v2+json`
refer to:
https://github.com/docker/distribution/issues/1575#issuecomment-213364009
