### ISSUE TITLE
Different hashes while pulling and pushing to registry

### ISSUE THREAD

**Issue by innocentme1** [docker/distribution#1814]
Can someone please clarify my question posted here

http://stackoverflow.com/questions/37999796/different-hashes-while-pulling-from-hub-and-pushing-to-registry

I could not get any response from quite some time.

**Comment by RichardScothern** [comment]
*Please follow these instructions to help us diagnose your issue*

 1. create a new issue, with a succinct title that describes your issue:
   - bad title: "It doesn't work with my docker"
   - good title: "Private registry push fail: 400 error with E_INVALID_DIGEST"
 2. copy the output of:
   - `docker version`
   - `docker info`
   - `docker exec <registry-container> registry -version`
 3. copy the command line you used to launch your Registry
 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6. if relevant, copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 8. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry

**Comment by innocentme1** [comment]
Please see the attached image. I can see different layer hashes and different final image hash while pulling from Docker hub and while pushing it back to my local registry. But, once its pushed to registry, I can see the same layers that I saw during docker pull from hub (I saw these layer details from manifest file on my registry). Why are there different hashes, what exactly is happening here?

![gridc](https://cloud.githubusercontent.com/assets/19864555/16509199/41e54e88-3eef-11e6-9552-e7edf9fc7efe.png)

**Comment by RichardScothern** [comment]
@innocentme1 I cannot help you unless you file an issue correctly.  Without know what version of docker or the registry you are running there is nothing I can do.

Also, posting images rather than text makes it much more difficult to diagnose what your problem is.

**Comment by innocentme1** [comment]
@RichardScothern I seriously dont know whats the problem you are having in understanding my question. Its more or less a simple query on asking why the hashes are being different which is very clearly evident from my post. I am sure this was design model but I do not know why are they being different. I am also sure this is same across any versions of Docker. Anyway, I will post it in the format you requested for , very soon. 

P.S: Images speak more than text. You can express 100 things in a single image and it would take 100 lines in text for the same thing to be expressed. Anyway, everyone have their own opinion. As said, I will post it in your format soon.

**Comment by RichardScothern** [comment]
@innocentme1 I understand your question.  I will repeat what I said above: without knowing your docker and registry versions I cannot answer your question. 

> I am sure this was design model but I do not know why are they being different. I am also sure this is same across any versions of Docker

The model for storing images within docker has changed significantly in the 1.10 release.  Additionally, a new manifest format was introduced within the registry in 2.3.  Both of these can influence what you are seeing.

> P.S: Images speak more than text.

Even if the image is of text?

**Comment by innocentme1** [comment]
@RichardScothern 

Sure. I am using Docker version 1.11.1 build 5604cbe and OS registry v2.4.1. 

I mean I kept some lines etc. on the image which are little hard to explain in text.

**Comment by RichardScothern** [comment]
I'm not sure why the hash of each layer is different.  My best guess is docker is converting them from the old format to the new content-addressed image format.

**Comment by stevvooe** [comment]
The hash displayed is the unpackaged tar hash, where the digest in the manifest is that of the fully compressed and packaged layer.

Let me know if there are further questions!
