### ISSUE TITLE
can registry cache redirect auth token?

### ISSUE THREAD

**Issue by elianka** [docker/distribution#1815]
@RichardScothern as the picture. i want to cache registryA in registryB. And both two registry use the same auth service.
1. i login in 'docker cli', and do the pull new image from registryB.
2. i found that auth to registryB is ok. meanwhile, registryB will not redirect the token to registryA. and pull(cache) failed.
3. so could registryB use the token from 'docker cli' to do the auth to registryA? or is there same other solution to do this?
![image](https://cloud.githubusercontent.com/assets/4158830/16511766/67e73b86-3f86-11e6-9a3d-df40b57cf71c.png)

**Comment by dmcgowan** [comment]
I am trying to understand what you are doing here. Are RegistryA and RegistryB served at different URLs? If so you must login to each of them. As for caching, the docker engine currently does not support private registry caching so they must be treated as their own registry (reason for separate login).

**Comment by elianka** [comment]
got your point. yes, RegistryA and RgistryB are different URLs. 
I know docker engine currently does not support private mirror now.  Meanwhile, registry caching is a feature of registry, could be running separately, so i think registry itself should support private registry caching.
