### ISSUE TITLE
Why delete the image, but the image still exist?

### ISSUE THREAD

**Issue by houht** [docker/distribution#1816]
To execute the following command is successful：
curl  -X DELETE  http://10.0.2.47:5000/v2/team1/pro1/manifests/sha256:265eb94136872655002169194feef72bd0f6be09dc417ffaaf88024ec5263f66

But still can query to exist：
curl -X GET http://10.0.2.47:5000/v2/team1/pro1/tags/list
{"name":"team1/pro1","tags":["v2.0"]}

query manifest：
curl -X GET http://10.0.2.47:5000/v2/team1/pro1/manifests/v2.0

{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Name":"team1/pro1","Revision":"sha256:265eb94136872655002169194feef72bd0f6be09dc417ffaaf88024ec5263f66"}}]}

**Comment by RichardScothern** [comment]
*Please follow these instructions to help us diagnose your issue*

 1. create a new issue, with a succinct title that describes your issue:
   - bad title: "It doesn't work with my docker"
   - good title: "Private registry push fail: 400 error with E_INVALID_DIGEST"
 2. copy the output of:
   - `docker version`
   - `docker info`
   - `docker exec <registry-container> registry -version`
 3. copy the command line you used to launch your Registry
 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6. if relevant, copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 8. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry

**Comment by houht** [comment]
Thank you very much for your advice and I will  test next week.

**Comment by houht** [comment]
docker version   :
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:           
 OS/Arch:         linux/amd64

docker info:

Containers: 5
Images: 196
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-2280958-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.132 GB
 Data Space Total: 107.4 GB
 Data Space Available: 9.805 GB
 Metadata Space Used: 8.933 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 3
Total Memory: 2.781 GiB
Name: test47
ID: 6MN2:S7XQ:KP4J:MENT:SU6Q:YRAS:BSCO:GKUV:PG6I:N5DP:44AM:DKXO
Http Proxy: http://10.0.2.39:3128
Https Proxy: http://10.0.2.39:3128
No Proxy: 10.0.2.47,10.0.2.48,registry.example.com
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 label_name=test47

docker exec <registry-container> registry -version:

/bin/registry github.com/docker/distribution v2.2.1

**Comment by RichardScothern** [comment]
This is a bug, which was fixed in v2.3.  Can you upgrade?

**Comment by houht** [comment]
I'm sorry, I have a try with v2.3,Thanks.

**Comment by houht** [comment]
Delete image has been successful,and the file does not exist,But I posted it again,return information:

Image already exists

But I succeeded after the restart.Did the delete command not clear the cache？

registry -v:

registry github.com/docker/distribution v2.4.1

**Comment by houht** [comment]
Thanks, and solve.

docker registry v2.4 conf:

version: 0.1
log:
  fields:
    service: registry
storage:
    delete:
        enabled: true
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
compatibility:
  schema1:
    disablesignaturestore: true
