### ISSUE TITLE
s3 creds reqiured when regionendpoint configured

### ISSUE THREAD

**Issue by astrally2000** [docker/distribution#1819]
I've really been appreciating the value of AWS VPC endpoints and am currently in the process of moving workloads from directly connected to the internet to corporate direct connect links.
I've found an issue whereby it looks I need to provide aws creds directly into config.yml if I configure regionendpoint, despite having IAM role assigned.

Below is my config.yml 

version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  cache:
      blobdescriptor: inmemory
  s3:
    region: ap-southeast-2
    bucket: somebucket
    regionendpoint: https://s3-ap-southeast-2.amazonaws.com
    encrypt: true
    secure: true

    v4auth: true
    chunksize: 5242880
    rootdirectory: /dev
  redirect:
    disable: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /certs/domain.crt
    key: /certs/domain.key

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

When I don't configure any aws creds I get the following error,
registry    | time="2016-07-05T09:16:36.894532997Z" level=error msg="response completed with error" err.code="manifest unknown" err.detail="s3aws: NoCredentialProviders: no valid providers in chain. Deprecated. \n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" err.message="manifest unknown" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=711d5510-6f5f-4da6-9e9e-78b557e10f4a http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.325542ms http.response.status=404 http.response.written=116 instance.id=734c7856-42ce-400c-b2c3-c955862e3c42 service=registry vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1

Now the configuration works within a VPC directly connected to the internet, when I have no entry for regionendpoint, but have an IAM role configured with S3 permissions for the host. I am using exactly the same IAM role for both instances.

I've validated that I can access the s3 content on the node using the (aws s3 ls) sdk 

Below is a successful trace, 
Is this anything to do with #1606, or an actual issue?

registry    | time="2016-07-05T09:34:16.676255962Z" level=debug msg="authorizing request" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:16.676385573Z" level=debug msg=GetImageManifest go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:16.760005372Z" level=debug msg="s3aws.GetContent(\"/docker/registry/v2/repositories/canary/somefile-pre-check/_manifests/tags/2/current/link\")" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry trace.duration=83.508754ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=0971fb49-7211-4f54-9c13-293994bd7e16 trace.line=82 vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:16.760080782Z" level=debug msg="(*manifestStore).Get" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:16.791636186Z" level=debug msg="s3aws.GetContent(\"/docker/registry/v2/repositories/canary/somefile-pre-check/_manifests/revisions/sha256/3d8dd8aa22bae1ff73f001a0a4fc6f7158ca8cedd787f058557105e5c3b9ba61/link\")" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry trace.duration=31.448251ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=3ee7ef82-6bf2-4fd9-8e77-635fe3d6d313 trace.line=82 vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:17.280337649Z" level=debug msg="s3aws.Stat(\"/docker/registry/v2/blobs/sha256/3d/3d8dd8aa22bae1ff73f001a0a4fc6f7158ca8cedd787f058557105e5c3b9ba61/data\")" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry trace.duration=488.552807ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=e7da13c7-abc4-4aa7-8c2c-0be9a4a58c3f trace.line=137 vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:17.302189641Z" level=debug msg="s3aws.GetContent(\"/docker/registry/v2/blobs/sha256/3d/3d8dd8aa22bae1ff73f001a0a4fc6f7158ca8cedd787f058557105e5c3b9ba61/data\")" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry trace.duration=21.707091ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=618a0c49-ec48-4fc3-a287-d5b88537afd4 trace.line=82 vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:17.302421114Z" level=debug msg="(*schema2ManifestHandler).Unmarshal" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:17.303188926Z" level=info msg="rewriting manifest sha256:3d8dd8aa22bae1ff73f001a0a4fc6f7158ca8cedd787f058557105e5c3b9ba61 in schema1 format to support old client" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:17.337767297Z" level=debug msg="s3aws.GetContent(\"/docker/registry/v2/repositories/canary/somefile-pre-check/_layers/sha256/a0da0c65301602155dc0f605f7c3df855e7982d01d41179928a6bb9213576b36/link\")" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry trace.duration=34.478809ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=55f4ed8a-7c84-499a-8fcd-c663ca010285 trace.line=82 vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:17.358097714Z" level=debug msg="s3aws.Stat(\"/docker/registry/v2/blobs/sha256/a0/a0da0c65301602155dc0f605f7c3df855e7982d01d41179928a6bb9213576b36/data\")" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry trace.duration=20.219159ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=12c895ee-ed45-4e63-8300-cd17c8e6a86e trace.line=137 vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:17.377997859Z" level=debug msg="s3aws.GetContent(\"/docker/registry/v2/blobs/sha256/a0/a0da0c65301602155dc0f605f7c3df855e7982d01d41179928a6bb9213576b36/data\")" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry trace.duration=19.761302ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=14d0bea8-cc4d-427c-8620-6800681ea379 trace.line=82 vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:17.416903803Z" level=debug msg="s3aws.GetContent(\"/docker/registry/v2/repositories/canary/somefile-pre-check/_layers/sha256/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/link\")" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry trace.duration=35.404313ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=d27bd813-7d89-46fb-b18a-1f6f18404b40 trace.line=82 vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:17.43449004Z" level=debug msg="s3aws.Stat(\"/docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/data\")" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry trace.duration=17.455577ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=e19d1c9a-c870-4c1c-8afc-d6737fcf27f5 trace.line=137 vars.name="canary/somefile-pre-check" vars.reference=2 version=v2.4.1
registry    | time="2016-07-05T09:34:17.437895807Z" level=info msg="response completed" go.version=go1.6.2 http.request.host="registry:5000" http.request.id=d41606a4-2a6a-40e5-a5ca-3a3ad7ff5e50 http.request.method=GET http.request.remoteaddr=10.13.28.85 http.request.uri="/v2/canary/somefile-pre-check/manifests/2" http.request.useragent="Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" http.response.contenttype="application/vnd.docker.distribution.manifest.v1+prettyjws" http.response.duration=762.829084ms http.response.status=200 http.response.written=20809 instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry version=v2.4.1
registry    | 172.17.0.3 - - [05/Jul/2016:09:34:16 +0000] "GET /v2/canary/somefile-pre-check/manifests/2 HTTP/1.1" 200 20809 "" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
web         | 10.13.28.85 - - [05/Jul/2016:09:34:16 +0000] "GET /v2/canary/somefile-pre-check/manifests/2 HTTP/1.1" 200 21306 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
registry    | time="2016-07-05T09:34:19.168521633Z" level=debug msg="s3aws.List(\"/\")" go.version=go1.6.2 instance.id=f21c02a6-82c8-4c64-9fc9-92c9ea46d801 service=registry trace.duration=16.922733ms 

aws s3 ls s3://com.somebucket/dev/docker/registry/v2/repositories --endpoint-url https://s3-ap-southeast-2.amazonaws.com
                           PRE repositories/

I've tried having blank entries for both, but again the same exception.
accesskey: 
secretkey:

**Comment by RichardScothern** [comment]
hi @astrally2000 

The `regionendpoint` was added to allow the registry to connect to non-AWS S3 services.   I had a quick look at the code and it looks like when this option is set the only credentials used are the given access and secret keys from the config file or environment variables.

It looks like we can add an `EC2RoleProvider` to the credential chain when `regionEndpoint` is configured.  If you have the code checked out I can show you the change to test with, otherwise I can make a container with this change for you to test.

**Comment by astrally2000** [comment]
Hi Richard,
Thanks for the quick response, I'm an infrastructure jockey, so not too
competent with go, if you could please make a test container I could easily
test, thanks again
Andrew

**Comment by RichardScothern** [comment]
Can you give `richardscothern/registry:ec2-creds` a look?

**Comment by astrally2000** [comment]
Thanks Richard, that works. Thanks again for your prompt response. When will you look to include within master branch?
Is there any other testing or assistance required from me,
Cheers
Andrew

**Comment by RichardScothern** [comment]
great news @astrally2000 .  I'll submit it today

**Comment by kyprifog** [comment]
What was the conclusion of this?  Was the PR supposed to address this problem?  I am running into this issue on the most recent version and nothing suggested above seems to help.
