### ISSUE TITLE
Unable to delete images in open source docker private trusted registry

### ISSUE THREAD

**Issue by nanab4u** [docker/distribution#1821]
**Output of docker version:**

**Client:**
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

**Server:**
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

**Output of docker info:**

Containers: 11
 Running: 9
 Paused: 0
 Stopped: 2
Images: 27
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 194
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-38-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.797 GiB
Name: docker-app
ID: OOAV:S2TL:RIPW:2N64:TZV3:RINM:BRL5:5SOO:SHN6:7M7O:BB7D:UPKD
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Additional environment details (AWS, VirtualBox, physical, etc.): Physical

**Steps to reproduce the issue:**
1.curl -k -u 'username:password' -I -H Accept:* https://localhost:5000/v2/test/apache/manifests/7
2.curl -k -v -u 'username:password' -X DELETE https://myregistrydomain.com:5000/v2/test/apache/manifests/sha256:a8c440e6d892575de35e179bc7b09f23b9a117d4b967eb469d66c5320edc2ee5

**Describe the results you received:**
**Output 1:** HTTP/1.1 200 OK
Content-Length: 10465
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:a8c440e6d892575de35e179bc7b09f23b9a117d4b967eb469d66c5320edc2ee5
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:a8c440e6d892575de35e179bc7b09f23b9a117d4b967eb469d66c5320edc2ee5"
X-Content-Type-Options: nosniff
Date: Tue, 05 Jul 2016 11:28:45 GMT

**Output2:** * Hostname was NOT found in DNS cache

Trying 192.168.1.142...
Connected to myregistrydomain.com (192.168.1.142) port 5000 (#0)
successfully set certificate verify locations:
CAfile: none CApath: /etc/ssl/certs
SSLv3, TLS handshake, Client hello (1):
SSLv3, TLS handshake, Server hello (2):
SSLv3, TLS handshake, CERT (11):
SSLv3, TLS handshake, Server key exchange (12):
SSLv3, TLS handshake, Server finished (14):
SSLv3, TLS handshake, Client key exchange (16):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSLv3, TLS change cipher, Client hello (1):
SSLv3, TLS handshake, Finished (20):
SSL connection using ECDHE-RSA-AES128-GCM-SHA256
Server certificate:
subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=myregistrydomain.com
start date: 2016-06-10 12:07:22 GMT
expire date: 2043-10-27 12:07:22 GMT
issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=myregistrydomain.com
SSL certificate verify result: self signed certificate (18), continuing anyway.
Server auth using Basic with user 'username' > DELETE /v2/test/apache/manifests/sha256:a8c440e6d892575de35e179bc7b09f23b9a117d4b967eb469d66c5320edc2ee5 HTTP/1.1 > Authorization: Basic dGVzdHVzZXI6N3kzZHN5bXBob255MTIz > User-Agent: curl/7.35.0 > Host: myregistrydomain.com:5000 > Accept: / > < HTTP/1.1 405 Method Not Allowed < Content-Type: application/json; charset=utf-8 < Docker-Distribution-Api-Version: registry/2.0 < X-Content-Type-Options: nosniff < Date: Tue, 05 Jul 2016 11:30:25 GMT < Content-Length: 78 < {"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}
Connection #0 to host myregistrydomain.com left intact
**Describe the results you expected:**

Unable to delete images in private docker trusted registry.

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm using "registry github.com/docker/distribution v2.4.1" and Docker-Distribution-Api-Version: registry/2.0 and this issue is happening always

**Comment by RichardScothern** [comment]
Do you have delete disabled in your config file?

**Comment by nanab4u** [comment]
I'm using the default options. Do i need to enable that separately ? If so where ? Below is my docker-compose file:

**version: '2'
services:
 registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /docker-registry/data:/var/lib/registry
    - /docker-registry/certs:/certs
    - /docker-registry/auth:/auth**

**Comment by nanab4u** [comment]
Added REGISTRY_STORAGE_DELETE_ENABLED: "true" in the environment and now getting the new error 

**< HTTP/1.1 404 Not Found
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< Date: Thu, 07 Jul 2016 07:04:32 GMT
< Content-Length: 70
<
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown"}]}**

**Comment by nanab4u** [comment]
Update:

**STEP 1:** When i try to query the manifest with the below command:

curl -k -u 'username:password' -I -H Accept:* https://localhost:5000/v2/test/apache/manifests/7

i got the output as 

Output 1: HTTP/1.1 200 OK
Content-Length: 10465
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: **sha256:a8c440e6d892575de35e179bc7b09f23b9a117d4b967eb469d66c5320edc2ee5**
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:a8c440e6d892575de35e179bc7b09f23b9a117d4b967eb469d66c5320edc2ee5"
X-Content-Type-Options: nosniff

but in the same time while inspecting logs in the docker registry container i got the following output:

level=info msg="rewriting manifest **sha256:14d15c9189807b7f0bebd71ad821aae13564e08ff4ed91a771405e94b01985e5** in schema1 format to support old client"

**STEP 2:** Deleting the tag:

When i try to delete the tag by using this digest **sha256:a8c440e6d892575de35e179bc7b09f23b9a117d4b967eb469d66c5320edc2ee5** I got **MANIFEST UNKNOWN ERROR**

and when i try to delete the tag with this digest **sha256:14d15c9189807b7f0bebd71ad821aae13564e08ff4ed91a771405e94b01985e5** it worked fine. 

Do you know why we have two different digest for the same manifest ?

**Comment by RichardScothern** [comment]
Have a look at the delete API: https://docs.docker.com/registry/spec/api/#/deleting-an-image

The reason is described here: https://github.com/docker/distribution/blob/master/docs/compatibility.md

**Comment by nanab4u** [comment]
Okay Thanks much for your help and i'm closing this issue.

**Comment by streamnsight** [comment]
so what's the final word about getting the right digest? Do i really need to go into the logs and figure out how the digest was rewritten?
or is there a way to get the updated value somewhere?

**Comment by LuisBL** [comment]
The "reason" link is 404 now:   https://github.com/docker/distribution/blob/master/docs/compatibility.md
Can someone point to a new one ?

**Comment by h6w** [comment]
For versions 2.3 and later, it appears you now need to add a "Accept: application/vnd.docker.distribution.manifest.v2+json" header to the manifest and delete requests.   This results in a different output and different digest values.   Using values in "Docker-Content-Digest" from requests without this header won't work. :-(

```
$ curl -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://localhost:5000/v2/ubuntu/manifests/16.04
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 3370,
      "digest": "sha256:21ed62266c0eb41ea8f4296dbd28b00a2aa1e725c01a29f497a1f9427bf695f3"
   },
.....
```

This digest can then be used to delete:

```
$ curl -v -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -X DELETE https://localhost:5000/v2/ubuntu/manifests/sha256:21ed62266c0eb41ea8f4296dbd28b00a2aa1e725c01a29f497a1f9427bf695f3
...
> DELETE /v2/ubuntu/manifests/sha256:21ed62266c0eb41ea8f4296dbd28b00a2aa1e725c01 HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.50.1
> Accept: application/vnd.docker.distribution.manifest.v2+json
> 
< HTTP/1.1 202 Accepted
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< Date: Thu, 23 Mar 2017 05:14:55 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
```

**Comment by audrummer15** [comment]
@LuisBL the new compatibility link can be found at https://github.com/docker/docker.github.io/blob/master/registry/compatibility.md

Also, I can confirm this issue. The solution above mentioned by @h6w did not work for me. I had to look in the logs of my registry container `docker logs -f registry_container` and find the `rewriting manifest` message referenced by @nanab4u. From that digest, I was able to properly delete the tag (which deleted ALL tags that were pointing to the same image, so be sure to have a backup if simply trying to remove a tag)

**Comment by lgaida** [comment]
I get the same problem.
As @h6w suggested i used "application/vnd.docker.distribution.manifest.**v2**+json" in the accept-header and i also tried "application/vnd.docker.distribution.manifest.**v1**+json" because i was curious about this. And i do actually get two different digest-values.
Unfortunately i can not remove the image at all, no matter which digest-value i use. I always get the **MANIFEST_UNKNOWN**-Error.

Here is a little more background of my case:
I had a few images in my private registry but their names didn't fit quite well. _(possibly pushed from a client <=1.9)_
So i pulled these images, retagged and pushed them again. _(with a client =>1.10)_
I'm attempting the deletion from a client =>1.10

Any ideas ?

**Comment by ykyuen** [comment]
Does this one liner command help?
https://gist.github.com/jaytaylor/86d5efaddda926a25fa68c263830dac1#gistcomment-2662407
