### ISSUE TITLE
Delete by API "DELETE	 /v2/<name>/blobs/<digest>"  , why the sha file still exist?

### ISSUE THREAD

**Issue by houht** [docker/distribution#1823]
docker info:

Containers: 6
Images: 162
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-937244-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.832 GB
 Data Space Total: 107.4 GB
 Data Space Available: 12.66 GB
 Metadata Space Used: 6.644 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 3
Total Memory: 2.781 GiB
Name: test48
ID: 5MGS:EHIB:S6IU:X4KT:OGU3:2HR7:5Q7X:FC2A:7IAE:QWUY:MJMU:JZXV
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 label_name=test48

docker version:

Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:           
 OS/Arch:         linux/amd64

registry -v:

registry github.com/docker/distribution v2.4.1

Execute the following command and return no errors:

curl -k -X DELETE -H  https://registry.digitlchina.com:5000/v2/team1/myredis/blobs/sha256:a1a961e320bc549c80d2b5ba9ba1cb8d2d4a8b73f1bebe8715b7b398508e2d3e

logs:
"DELETE /v2/team1/myredis/blobs/sha256:a1a961e320bc549c80d2b5ba9ba1cb8d2d4a8b73f1bebe8715b7b398508e2d3e HTTP/1.1" 202 0 "" "curl/7.29.0"

file:
ll /root/docker_registry/data/docker/registry/v2/blobs/sha256/a1/a1a961e320bc549c80d2b5ba9ba1cb8d2d4a8b73f1bebe8715b7b398508e2d3e/data
-rw-r--r-- 1 root root 196 Jul  8 09:57 /root/docker_registry/data/docker/registry/v2/blobs/sha256/a1/a1a961e320bc549c80d2b5ba9ba1cb8d2d4a8b73f1bebe8715b7b398508e2d3e/data

**Comment by houht** [comment]
do execute the following command?
registry garbage-collect /etc/docker/registry/config.yml

**Comment by houht** [comment]
registry garbage-collect /etc/docker/registry/config.yml  is error

When deleted, push again,Error occurred


docker push  registry.digitlchina.com:5000/houht/test_002:v1
The push refers to a repository [registry.digitlchina.com:5000/houht/test_002] (len: 1)
3763472ebc39: Image already exists 
823349cecb31: Image already exists 
66fbb15e0493: Image already exists 
2dc8009d6c8d: Image already exists 
v1: digest: sha256:716eb031df04c541c81086240fd5686a2c2b78685d2e0f259aa0d9a86495e1ca size: 4562
[root@test48 data]# 
[root@test48 data]# 
[root@test48 data]# docker pull registry.digitlchina.com:5000/houht/test_002:v1 
Trying to pull repository registry.digitlchina.com:5000/houht/test_002 ... not found
Error: image houht/test_002:v1 not found 



registry garbage-collect /etc/docker/registry/config.yml -d
houht/test_002
houht/test_002: marking manifest sha256:716eb031df04c541c81086240fd5686a2c2b78685d2e0f259aa0d9a86495e1ca 
houht/test_002: marking blob sha256:480fd950d4069dc8b5ce649eac3f75317a07dd8ae364089a3f9753a4518dfc05
houht/test_002: marking blob sha256:b9a7a39e3e18dd82000e537ffcdc84a4689ba500560f4c5c1cfd0fd462b0aded
houht/test_002: marking blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
houht/test_002: marking blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
houht/test_002: marking blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
houht/test_002: marking blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
houht/test_002: marking blob sha256:55dc925c23d1ed82551fd018c27ac3ee731377b6bad3963a2a4e76e753d70e57
houht/test_002: marking signature sha256:77d7c29715996d57aa602f2e447cf9ecec6449df52fa82176b9104ef9f17683b
houht/test_002: marking signature sha256:d5919bf2085cb767784513789320ed1fbeb2b0d66420e8a9a7becf603dae2114
houht/test_002: marking signature sha256:4e2788b781854ba80907271497f5bf78975d9cce4a84ec7d3aa11a0be8d0ec4e
houht/test_002: marking signature sha256:0793b5e7782881f5481fb585e1f0094d41eb63c116a5a48b5836839b684b9cb5
houht/test_002: marking signature sha256:455aae4ad1b02460f5d9b07da1c7a44c4fd524f357bf98c6c775df608524c08c
houht/test_002: marking signature sha256:1b5e1ef22fda046389bb64a3b320d1a85f2f1b40179e8f7c15ffe4cac336693f
houht/test_002: marking signature sha256:69f6c4033e1893fac2141fa696a8a50dc7ab1dc6a2ac8357e3a825dd9b7755d1
houht/test_002: marking signature sha256:303f7acd5fdb152cd685a12f45763b23488e9c00bbe2d619069babe5339cb9dc
houht/test_002: marking signature sha256:04d47426424867dc105e6bddd5011bafda6323cdebe9fcb39d27391356270621
houht/test_002: marking signature sha256:6f6e2a90ebcde523b458952d0fc7159bbdd53ea8676b5720f2aea96a793469c2
houht/test_002: marking signature sha256:1f7a3760f5d5a5a4b43f67578b71377da301b37f9ddc7b8e7d21ef826b815e31
houht/test_002: marking signature sha256:6dc63c617f5e21488548cf684332d1e73e3a9aa7e7dce322a282193eca13faea
houht/test_002: marking signature sha256:a8106be4989c0bebe6c75986aaccd77e47e23a35a2f331294d50d055c1800d16
houht/test_002: marking signature sha256:db372a3d86d9902843550ef7f1e532e7921520a5604e05b06469c4998b5b4f7b

19 blobs marked, 0 blobs eligible for deletion

**Comment by RichardScothern** [comment]
There is an issue with v1 signatures and garbage collection.  Please add this to your configuration file:
```
compatibility:
  schema1:
    disablesignaturestore: true
```

**Comment by houht** [comment]
Thank you. I'll try it.

**Comment by houht** [comment]
Thank you very much,I have already succeeded in testing.
