### ISSUE TITLE
Issue while adding S3 Credentials to docker cloud

### ISSUE THREAD

**Issue by Nishant-Pathak** [docker/distribution#1824]
Hello Docker,

Thank you for making my life easy and simple.

I want to s3 cloud to docker cloud and for that, I am following https://docs.docker.com/docker-cloud/getting-started/link-aws/ link. when I add the credentials and save. It gives below error and page hungs. Please look into it.

<img width="1440" alt="screen shot 2016-07-08 at 8 50 28 am" src="https://cloud.githubusercontent.com/assets/724049/16676566/0d7bcdfc-44e9-11e6-8772-dc04fb8767ba.png">

**Comment by RichardScothern** [comment]
This repository has nothing to do with Docker Cloud.  I've passed your message on to that team.
