### ISSUE TITLE
doc/spec: outline manifest v2, schema version 1

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#183]
Currently, the specification for the v2 manifest format is only documented in docker/docker#8093. We need baseline coverage for this interim format.

**Comment by stevvooe** [comment]
cc @jlhawn Could you throw this together for the beta release? This should be in place before we release the registry.

**Comment by jlhawn** [comment]
+1

**Comment by bfirsh** [comment]
Godoc for manifest: http://godoc.org/github.com/docker/distribution/manifest

**Comment by RichardScothern** [comment]
https://github.com/docker/distribution/pull/336
