### ISSUE TITLE
S3 Driver not including x-amx-content-sha256 in signed headers

### ISSUE THREAD

**Issue by rdjones517** [docker/distribution#1832]
This bug has been reported as fixed here:

https://github.com/aws/aws-sdk-go/issues/743

Can we pull this into registry 2.5.0 ? This bug is currently preventing the use of some alternate S3 storage providers.

**Comment by RichardScothern** [comment]
@rdjones517 : can you confirm this fixes your issue?  You can get a container with this change at `distribution/registry:latest` in about an hour

**Comment by rdjones517** [comment]
@RichardScothern Should I be pulling master or latest? looks like the latest tag is 7 months old

**Comment by RichardScothern** [comment]
sorry @rdjones517 I lied to you the tag should be `master` 😿 

```
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
distribution/registry              master              3cac39dad6c4        16 hours ago        349 MB
```

**Comment by rdjones517** [comment]
@RichardScothern I was able to test using the container your provided, and I can confirm that this has resolved my issue. I am able to communicate with my S3 storage provider successfully. Thanks

**Comment by dmcgowan** [comment]
Thanks @rdjones517 for testing it out!

**Comment by rdjones517** [comment]
Doesn't look like this fix was included in registry 2.5.0. Will it be included in 2.5.1?

**Comment by RichardScothern** [comment]
This was committed past the cutoff for 2.5.0.  There is no reason it can't go in 2.5.1

**Comment by rdjones517** [comment]
Doesn't look like this made it into 2.5.1. Any idea why?

**Comment by RichardScothern** [comment]
I want to keep the impact low for patch releases.  This fix required 84 file changes in the vendored code so I would like to keep it back until 2.6.  Sorry for misleading you.
