### ISSUE TITLE
API v2 endpoint for listing tags from dockerhub does not work

### ISSUE THREAD

**Issue by borzamircea** [docker/distribution#1841]
Hi,

I'm trying to get the list of `tags` for an image:

Using the `/v2/<name>/tags/list` yields:

![image](https://cloud.githubusercontent.com/assets/9818060/16876414/77588314-4aac-11e6-9f2e-a9b064f5b8db.png)

Using ```/v2/<name>/tags``` yields only the first page, tried with ``?page=all``, but still the first page was displayed.`

![image](https://cloud.githubusercontent.com/assets/9818060/16876461/9bf0b2c8-4aac-11e6-8d9a-559d349f9793.png)

Any help would be greatly appreciated! Thanks!

**Comment by RichardScothern** [comment]
That URL does not point to a registry instance, rather a service in the hub.  You can hit the hub registry directly at `https://registry-1.docker.io/v2/repositories/library/ubuntu/tags/list`

**Comment by borzamircea** [comment]
Thank you. However, tried to generate a token, like here https://docs.docker.com/registry/spec/auth/token/ and still no luck, i get:

![image](https://cloud.githubusercontent.com/assets/9818060/16911100/36d95abc-4ce5-11e6-9042-452390806a0d.png)

**Comment by RichardScothern** [comment]
Can you check your token at `jwt.io` to ensure it has the correct permissions?

**Comment by borzamircea** [comment]
Did a workaround for it, since `tags/list` doesn't work, I decided to aggregate the results foe each page. TY!
