### ISSUE TITLE
Go vet reports mutex copy in context/http.go

### ISSUE THREAD

**Issue by DmitriyMV** [docker/distribution#1843]
Go 1.7rc1

Running go vet results in 
` ``error: literal copies lock value from irw: context.instrumentedResponseWriter contains sync.Mutex```
https://github.com/docker/distribution/blob/master/context/http.go#L113

It looks like `instrumentedResponseWriterCN` indeed copies (vie embedding) `instrumentedResponseWriter` and thus `sync.Mutex`. One possible solution would to make make `mx` a pointer value. Another would be to embed by pointer.

**Comment by RichardScothern** [comment]
@DmitriyMV interesting.  I was not able to see this with go 1.6, but it does explain what others have (see #1822)
