### ISSUE TITLE
Registry : Catalog : last parameter not handled properly

### ISSUE THREAD

**Issue by Seb-Solon** [docker/distribution#1854]
Hi there,

I am hitting a bug while using the _last_ parameter when querying the catalog

Consider the following repository / images on a private registry : 
```
team/image1
team/image2
team-dev/image1
team-dev/image2
test/imagetest
```

If I list the registry with n=2, I will get : 

```
team/image1
team/image2
```

last is equal to team/image2

then 

```
test/imagetest
```

And that's it. It actually skips the team-dev repository.

However catalog query with n=5 returns : 

```
team/image1
team/image2
team-dev/image1
team-dev/image2
test/imagetest
```

After a quick look at the current code I think I have found the line causing this : https://github.com/docker/distribution/blob/master/registry/storage/catalog.go#L42

The issue comes from the fact that "-" in _lower_ than "/" for Go. The Walk function seems to return files in the "good" order (team before team-XX) but the Go comparison says the opposite

I believe it is missing an extra split on repoPath variable to compare directories first. Is it allowed to have more than 2 level of repository ? (So that we have to split more than once)

Is this a legit bug for you? I am not sure the - is a valid char for a repository name (can't find the doc about this) If so, are you OK if I do a PR to fix it? I may take more time than you to fix it properly (test and co)

Regards,

**Comment by RichardScothern** [comment]
hi @Seb-Solon that certainly looks like a bug to me.  In fact, you can prove this by editing the repositories in the catalog test code: https://github.com/docker/distribution/blob/master/registry/storage/catalog_test.go#L34-L38

A PR would be great 😄
