### ISSUE TITLE
Getting images with same base layer

### ISSUE THREAD

**Issue by borzamircea** [docker/distribution#1856]
I am trying to get a unique identifier for an image, i.e images with the same base layer/same layers. The `v2` api doesn't display image `Layer` info in the `Tags`. Is this deprecated from `v1`? I need a way to identify tags that have the same `Layer`. TY!

V1
![image](https://cloud.githubusercontent.com/assets/9818060/16980209/883f23f8-4e6d-11e6-9b43-0a2cad6734f7.png)
V2
![image](https://cloud.githubusercontent.com/assets/9818060/16980219/a40bc2d0-4e6d-11e6-8530-f29a65259f49.png)

**Comment by borzamircea** [comment]
Or at least be able to get the digest for a particular image so i can match by the digest, as `manifests/<tag>` , even with teh proper `Accept` header returns nothing:

![image](https://cloud.githubusercontent.com/assets/9818060/16982400/334a5394-4e78-11e6-8915-1e661fc8ec26.png)

**Comment by RichardScothern** [comment]
As I pointed out in your last issue, that URL does not hit the registry and I provided you the URL to the Hub registry.   This is the issue tracker for the open source registry and the API is fully documented here https://docs.docker.com/registry/spec/api/.  Please read it and perhaps experiment with your own private registry to understand it.

**Comment by borzamircea** [comment]
@RichardScothern I know, but even trying with `registry-1` does not work. The endpoints don't return what they are supposed to. I had to do a recursive call to get all the tags for an image, because `tags/list` returns nothing. Furthermore, I need the `dockerhub registry` specifically, not a private one.

Trying to get manifests for `ubuntu:latest`:

![image](https://cloud.githubusercontent.com/assets/9818060/17021199/01c5cc04-4f4f-11e6-9ef0-4c4b0068e01c.png)

**Comment by RichardScothern** [comment]
I can assure you that URL works:
`curl -v https://registry-1.docker.io/v2/` returns an authorization challenge from the registry.  Further API calls with a valid token will work correctly.

`registry.hub.docker.com` is not a registry endpoint.

**Comment by borzamircea** [comment]
@RichardScothern Hi. Thanks for the input, managed to get the auth to work. Is there an Api call to get all the layers for all the tags in one call? Right now, I can get all layers per tag.

**Comment by dmcgowan** [comment]
The layers need to be fetched for each individual manifest, there is no endpoint which will return multiple manifests. Please use the list endpoint and manifest fetch endpoints to accomplish this.

**Comment by borzamircea** [comment]
Hi @dmcgowan  .If I want to get all the tags with a specific layer, I need to run a call against each tag, which is totally different than what we have in version 1. one call that retrieve tags and their layers.

![image](https://cloud.githubusercontent.com/assets/9818060/17128649/f91978c8-5316-11e6-884d-43daea3766b7.png)

**Comment by soninob** [comment]
I suggest reopening this one, no way to get the mapping between tags and layers in one call like we have in v1, sounds like a regression.
