### ISSUE TITLE
Proposed Patch/Feature: Adding 'objectAcl' Option to the S3 Storage Backend

### ISSUE THREAD

**Issue by frankchn** [docker/distribution#1865]
I am proposing adding [Canned Object ACL](http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html) options to the S3 Storage Backend. 

This solves problems such as #1730, where a docker registry in A uses cross-account IAM permissions to write into a bucket owned by B. This results in B not being able to read from the files from A and causing weird problems for the registry, such as being able to list a certain repository (B can still list A's files) but not pull from it.

I have a proposed patch at https://github.com/frankchn/distribution/tree/frankchn/add-objectacl-to-s3

**Comment by RichardScothern** [comment]
That sounds good @frankchn .

**Comment by frankchn** [comment]
@RichardScothern Implemented in #1867
