### ISSUE TITLE
Getting tags in v1 vs v2

### ISSUE THREAD

**Issue by borzamircea** [docker/distribution#1866]
Hi @dmcgowan .If I want to get all the tags with a specific layer, I need to run a call to get the manifest against each tag, which is totally different than what we have in version 1, meaning one call that retrieve tags and their layers.

Thanks for the help!

**Comment by borzamircea** [comment]
V1
![image](https://cloud.githubusercontent.com/assets/9818060/17141632/772912c6-5355-11e6-9403-b64d459b2d70.png)
V2 (for alpine:latest)
![image](https://cloud.githubusercontent.com/assets/9818060/17142043/3e671e4a-5357-11e6-9777-ed8ffa451718.png)

**Comment by soninob** [comment]
+1 - sound like a regression.

**Comment by RichardScothern** [comment]
@borzamircea The v1 and v2 protocols are entirely different.  The v1 protocol and registry are insecure and will soon be deprecated.

I really suggest you read the API and other documentation which I linked in your last two issues to understand why this is. 

This is an issue tracker for the registry.  If you want to connect to the community with questions there is an IRC channel (#docker-distribution) and the docker forums.
