### ISSUE TITLE
Got "error authorizing context: insufficient scope" when DELETE /v2/<name>/manifests/<reference>

### ISSUE THREAD

**Issue by cmingxu** [docker/distribution#1869]
I got "error authorizing context: insufficient scope"  error when delete to url /v2/<name>/manifests/<reference>.  my scope (token.ResourceActions) for this request is push/pop, and the Get request works fine.

error messages for this is request is 

time="2016-07-28T14:39:08.29199085+08:00" level=warning msg="error authorizing context: insufficient scope" go.version=go1.5.3 http.request.host="192.168.99.100:5000" http.request.id=c97b20ff-4457-4bd6-b37c-fc7e1dfe609c http.request.method=DELETE http.request.remoteaddr="192.168.99.1:50538" http.request.uri="/v2/library/registry/manifests/latest" http.request.useragent="Go-http-client/1.1" instance.id=1d7626da-84f6-4c8d-9204-8e5dbcccd080 service=registry vars.name="library/registry" vars.reference=latest version=v2.3.0

**Comment by reasonerjt** [comment]
You need to add "*" when creating the token :)

**Comment by cmingxu** [comment]
@reasonerjt 

time="2016-07-29T10:56:45.695232464+08:00" level=error msg="response completed with error" auth.user.name="admin@admin.com" err.code=unsupported err.message="The operation is unsupported." go.version=go1.5.3 http.request.host="192.168.99.100:5000" http.request.id=2c62030f-4bd0-4289-b610-c203b8b6b3a5 http.request.method=DELETE http.request.remoteaddr="192.168.99.1:60383" http.request.uri="/v2/library/registry/manifests/v1" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.74455ms http.response.status=405 http.response.written=78 instance.id=1d7626da-84f6-4c8d-9204-8e5dbcccd080 service=registry vars.name="library/registry" vars.reference=v1 version=v2.3.0
192.168.99.1 - - [29/Jul/2016:10:56:45 +0800] "DELETE /v2/library/registry/manifests/v1 HTTP/1.1" 405 78 "" "Go-http-client/1.1"

Above is the error I got when auxiliary  ‘*’ actions provided. Seems distribution doesn't support ’*‘ operation. BTW, I reused code form Harbor project, and seems Harbor works fine with push/pull/*.   

Thanks and Thanks for the work that Harbor did.

**Comment by reasonerjt** [comment]
@cmingxu  Thanks for the comment.

the 405 is due to limitation in current code that you can not delete a manifest by tag, you delete it by digest

see https://docs.docker.com/registry/spec/api/

I recall I see an issue that delete by tag will be supported in future release but now you can only delete by digest...

**Comment by stevvooe** [comment]
@cmingxu Please let us know if you have further questions.
