### ISSUE TITLE
Pause container for a long amount of time

### ISSUE THREAD

**Issue by kopax** [docker/distribution#1872]
I am using a stack with mesos, marathon and docker.
I have a docker container running a registry on `-p 31800:5000`
The registry data dir is about 18GB. 
To backup the data dir, I use :

    docker pause $cid
    tar cpzf registry.tar.gz /srv/registry
    docker unpause $cid

For some reason, the container fail to start after that.
Reason is that the port 31800 is already allocated, I don't know if this error comes from docker itself, or if marathon crash the app. 

Is there anyway to get this work ?

**Comment by RichardScothern** [comment]
@kopax I'm afraid we can't help you here since your issue is with the docker engine.  I suggest you post a question in the docker channel on IRC. 

If port 31800 is used, `lsof` should be able to tell you which app is using it.
