### ISSUE TITLE
private docker-registry for private infrastructures

### ISSUE THREAD

**Issue by metaml** [docker/distribution#1886]
Can you please stop defining security policies for docker-registry and let a user configure how it should be used? 

This policy doesn't work for private infrastructures behind firewalls, where for this instance, SSL isn't wanted and authentication isn't needed for docker pulls. The process of pushing a docker image is vetted and fully tested, when we push docker images, we want authentication but not for pulls. We don't want certs because it's just more bullshit that we need  and is not necessary for private lans where none of the machines has access to the public. 

Please stop pretending that you're experts on security and defining incomplete policies.

**Comment by RichardScothern** [comment]
I'm not sure I quite follow you @metaml .  What specific security policies are being defined?

**Comment by metaml** [comment]
The fact that as soon as you want to use a host other than localhost, you're now required to use SSL and all that entails. For a large private infrastructures using SSL internally is sometimes, in our case definitely, not wanted especially for docker images. People from many years have been asking for an option on "--insecure" option on docker pull. As well, we want to have authentication when pushing a image to a registry but pulling should be free. You have this behavior in docker hub, why not have exactly the same option?

**Comment by zhouhaibing089** [comment]
@metaml you do not answer the question from @RichardScothern, could you just list which security policies which are defined and not fit for your purpose?

**Comment by zhouhaibing089** [comment]
> as soon as you want to use a host other than localhost, you're now required to use SSL and all that entails

Since you are able to disable it at client side, should this still be a problem?

> we want to have authentication/authorization when pushing a image to a registry but pulling should be free. This behavior in docker hub, why not have exactly the same option?

In my opinion, the authentication/authorization should be implement by downstream, it may should not be that hard to implement one and passthrough all the image pulling requests.

> leave that decision to the people who understand their use cases and let them configure their systems as they see fit.

you should be able to configure it somehow. :)

**Comment by metaml** [comment]
I thought I did, regarding security policy. 

"Docker pull/push" switches to https when the tag isn't "localhost." This is a security policy. This policy forces one to either obtain an SSL cert. or generate a self-signed one. Either way, docker needs to  be appropriately configured. However, for private infrastructures, where hostnames (and FQDN) are arbitrary (it's private) and obtaining an SSL or configuring one is awful waste of time. So, if you were to have an  "insecure" option when executing a docker push or pull, this problem will be moot. 

> You should be able to configure it somehow. :)

How do I disable https?

**Comment by RichardScothern** [comment]
> So, if you were to have an "insecure" option when executing a docker push or pull, this problem will be moot.

`--insecure-registry`

**Comment by dmcgowan** [comment]
@metaml We have a policy of having the most secure policy by default and providing methods for users to customize for their setup. In your case, setting `--insecure-registry` on the docker daemon will do the trick. We are not in the business of defining anyone's security policies, we try to have sensible defaults and provide as much configuration as user's need to implement their own policies. We rely on users reading our documentation, trying to configure Docker to their needs, then opening issues if the configurations are not sufficient.

**Comment by metaml** [comment]
Yes, I know of this option but it requires a reconfiguration of the docker daemon for this option to work. Why not have this option be honored by the docker daemon without a reconfiguration. 

Why do you believe you have sensible defaults when all your "sensible" defaults requires work to make it work? And, yes, you are defining a security policy.
