### ISSUE TITLE
Image push failed with v1/_ping: Not found

### ISSUE THREAD

**Issue by jianghaitao** [docker/distribution#1891]
Docker: 1.12
Registry: 2
I followed the instruction in the https://github.com/docker/distribution/blob/master/docs/deploying.md and run the registry as 
```
docker run -d \
    --restart=always\
    -p 5000:5000 \
    -e VIRTUAL_HOST=$FQDN \
    -v $REGISTRY_HOME/registry:/registry \
    -v $REGISTRY_HOME/certs:/certs\
    -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry \
    -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/$FQDN.crt \
    -e REGISTRY_HTTP_TLS_KEY=/certs/$FQDN.key \
    -e SEARCH_BACKEND=sqlalchemy \
     --name hub \
    registry:2
```
But when I test it
```
docker pull hello-world
docker tag hello-world $FQDN:5000/myfirstimage
docker push $FQDN:5000/myfirstimage
```
I got following error
```
The push refers to a repository [$FQDN:5000/myfirstimage]
Get https://$FQDN:5000/v1/_ping: Not found
```
$FQDN is fully qualified domain name for my registry node.

Thanks for any help!

**Comment by RichardScothern** [comment]
There is a connectivity issue somewhere.  Running the docker daemon in debug mode and looking at the logs should shed some light onto the problem.

Also, `SEARCH_BACKEND` and `VIRTUAL_HOST` are not supported registry environment variables.

**Comment by jianghaitao** [comment]
I removed these and results are the same. Set Docker in debug mode and found following in the syslog
```
Aug  8 23:49:25 hub dockerd[10596]: time="2016-08-08T23:49:25.557107586Z" level=debug msg="Trying to push $FQDN:5000/myfirstimage to https://$FQDN:5000 v2"
Aug  8 23:49:25 hub dockerd[10596]: time="2016-08-08T23:49:25.814828925Z" level=debug msg="Error getting v2 registry: Get https://$FQDN:5000/v2/: Not found"
Aug  8 23:49:25 hub dockerd[10596]: time="2016-08-08T23:49:25.814912202Z" level=error msg="Attempting next endpoint for push after error: Get https://$FQDN:5000/v2/: Not found"
Aug  8 23:49:25 hub dockerd[10596]: time="2016-08-08T23:49:25.814956490Z" level=debug msg="Trying to push $FQDN:5000/myfirstimage to https://$FQDN:5000 v1"
```
But I can curl the v2 endpoint
```
# curl -k https://hub.vms.crd.ge.com:5000/v2/
{}
```

**Comment by RichardScothern** [comment]
`Aug  8 23:49:25 hub dockerd[10596]: time="2016-08-08T23:49:25.814828925Z" level=debug msg="Error getting v2 registry: Get https://$FQDN:5000/v2/: Not found"
`

That is the problem.  For some reason $FQDN is not getting interpolated to your actual domain name.   Can also be seen with the docker client error `The push refers to a repository [$FQDN:5000/myfirstimage]`

**Comment by jianghaitao** [comment]
The real log has the true domain name - I just had to hide my true domain name due to company policy (replace it with $FQDN).

**Comment by RichardScothern** [comment]
I see.  When you say you can curl the endpoint, can you do so from within the docker container which is running the registry?

**Comment by jianghaitao** [comment]
Found the culprit: proxy settings for the Docker daemon. Removing that resolve the issue.
