### ISSUE TITLE
Push pull to remote registry fails via curl command

### ISSUE THREAD

**Issue by ksanjeev** [docker/distribution#1896]
Hello,

I did identify that we need to use port 5000 on docker registry from a remote machine to interact with the registry instead of the port 4243.

Next step is I am trying to figure out to download a image from repository/registry to local .

I have the following images on my machine.

```
root@icsdocker:~# docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
mysite.net/test-image   latest              283c5e11c165        5 days ago          124.8 MB
test-image              latest              283c5e11c165        5 days ago          124.8 MB
registry                2                   c6c14b3960bd        12 days ago         33.31 MB
cnuofbasel/ccn-lite     latest              dc2c1bdfef6f        2 weeks ago         641.9 MB
mysite.net/ccn-lite     latest              dc2c1bdfef6f        2 weeks ago         641.9 MB
ubuntu                  latest              42118e3df429        2 weeks ago         124.8 MB
mysite.net/nginximage   latest              c8c29d842c09        11 weeks ago        182.8 MB
nginx                   1.9                 c8c29d842c09        11 weeks ago        182.8 MB
```

I have four images on the repository as below 

```

root@icsdocker:~# curl http://172.27.10.70:5000/v2/_catalog
{"repositories":["busybox","centos","nginximage","test-image"]}
```

I tried to download the manifest as in https://docs.docker.com/registry/spec/api/#/pulling-an-image

```
root@icsdocker:/docker-registry/data/docker/registry/v2/repositories# curl  http://172.27.10.70:5000/v2/{"centos"}/manifests/{"Tag":"af85263f418cafe78f129a6c47e04f4848d564ecf2287e36216d2f717b281b46"}

{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Path":"/docker/registry/v2/repositories/centos/_manifests/tags/Tag:af85263f418cafe78f129a6c47e04f4848d564ecf2287e36216d2f717b281b46/current/link","DriverName":"filesystem"}}]}
```

Can anyone have a look at it if possible.

Kamal

------------------------------------------------------------------------------------------------------------------------------

Hi,

I am able to set up a docker private registry running over port 5000 and linked to authentication over port 443. I am able to push and pull images using docker command but fails while pushing command using curl authentication.

I have copied the openssl keys generated to client machine as well.  Below is the configuration details of the machine that could help in anyone guiding me to resolve this issue.

NAMESERVER
----------------------

```
root@icsdocker:/docker-registry# cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.27.10.70
search mysite.net
```

PORTS OPEN FOR docker and its registry with remote API
------------------------------------------------------

```
root@icsdocker:/docker-registry# netstat -tulpn | grep docker
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      17844/docker-proxy
tcp6       0      0 :::4243                 :::*                    LISTEN      17684/dockerd   
tcp6       0      0 :::443                  :::*                    LISTEN      17942/docker-proxy
```

Docker containers for registry and authentication running
----------------------------------------------------------

```
root@icsdocker:/docker-registry# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                          NAMES
6ae35c8116b5        nginx:1.9           "nginx -g 'daemon off"   16 hours ago        Up 16 hours         80/tcp, 0.0.0.0:443->443/tcp   dockerregistry_nginx_1
bb4778da879e        registry:2          "/entrypoint.sh /etc/"   16 hours ago        Up 16 hours         127.0.0.1:5000->5000/tcp       dockerregistry_registry_1
```

Docker Images and tags to mysite.net
-------------------------------------

```
root@icsdocker:/docker-registry# docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
mysite.net/test-image   latest              283c5e11c165        5 days ago          124.8 MB
test-image              latest              283c5e11c165        5 days ago          124.8 MB
registry                2                   c6c14b3960bd        12 days ago         33.31 MB
ubuntu                  latest              42118e3df429        2 weeks ago         124.8 MB
mysite.net/nginximage   latest              c8c29d842c09        11 weeks ago        182.8 MB
nginx                   1.9                 c8c29d842c09        11 weeks ago        182.8 MB
```

Added the following to enable remote API in /etc/default/docker
----------------------------------------------------------------

```
DOCKER_OPTS='-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock --insecure-registry mysite.net:5000'
```

Login from a remote machine, tag and push the images to registry from a remote machine
---------------------------------------------------------------------------------------

```
hadmin@ICSCHE0224:~$ docker login http://mysite.net
Username: ksanjeev
Password: 
Login Succeeded


hadmin@ICSCHE0224:~$ docker tag centos:7 mysite.net/centos
hadmin@ICSCHE0224:~$ docker push mysite.net/centos
The push refers to a repository [mysite.net/centos]
f59b7e59ceaa: Pushed 
latest: digest: sha256:af85263f418cafe78f129a6c47e04f4848d564ecf2287e36216d2f717b281b46 size: 529
```

Interacting with curl commands to the remote registry
------------------------------------------------------

Images fom the registry using GET works fine as below
-----------------------------------------------------

```
hadmin@ICSCHE0224:~$ curl  http://mysite.net:4243/images/json
[{"Id":"sha256:283c5e11c16583e322b80650dd35801f9bc96904d239008eb7b9d66064b97905","ParentId":"sha256:42118e3df429f09ca581a9deb3df274601930e428e452f7e4e9f1833c56a100a","RepoTags":["mysite.net/test-image:latest","test-image:latest"],"RepoDigests":["mysite.net/test-image@sha256:511fc53472811be495a5f8ff35f437a91154f1a4ad576a37116671e2f791a85b"],"Created":1470366724,"Size":124796968,"VirtualSize":124796968,"Labels":{}},{"Id":"sha256:c6c14b3960bdf9f5c50b672ff566f3dabd3e450b54ae5496f326898513362c98","ParentId":"","RepoTags":["registry:2"],"RepoDigests":["registry@sha256:1b68f0d54837c356e353efb04472bc0c9a60ae1c8178c9ce076b01d2930bcc5d"],"Created":1469742140,"Size":33306347,"VirtualSize":33306347,"Labels":{}},{"Id":"sha256:42118e3df429f09ca581a9deb3df274601930e428e452f7e4e9f1833c56a100a","ParentId":"","RepoTags":["ubuntu:latest"],"RepoDigests":["ubuntu@sha256:c6674c44c6439673bf56536c1a15916639c47ea04c3d6296c5df938add67b54b"],"Created":1469200771,"Size":124796948,"VirtualSize":124796948,"Labels":{}},{"Id":"sha256:c8c29d842c09d6c61f537843808e01c0af4079e9e74079616f57dfcfa91d4e25","ParentId":"","RepoTags":["mysite.net/nginximage:latest","nginx:1.9"],"RepoDigests":["mysite.net/nginximage@sha256:311e9840c68d889e74eefa18227d0a6f995bc7a74f5453fdcd49fe3c334feb24","nginx@sha256:54313b5c376892d55205f13d620bc3dcccc8e70e596d083953f95e94f071f6db"],"Created":1464063409,"Size":182773379,"VirtualSize":182773379,"Labels":{}}]

```

Curl fails while trying to create a  image from the registry
-------------------------------------------------------------

```
hadmin@ICSCHE0224:~$ curl -v -X POST http://ksanjeev:ipo2001@mysite.net:4243/images/create?fromImage=mysite.net/test-image&tag=latest
[1] 2294
hadmin@ICSCHE0224:~$ * Hostname was NOT found in DNS cache
*   Trying 172.27.10.70...
* Connected to mysite.net (172.27.10.70) port 4243 (#0)
* Server auth using Basic with user 'ksanjeev'
> POST /images/create?fromImage=mysite.net/test-image HTTP/1.1
> Authorization: Basic a3NhbmplZXY6aXBvMjAwMQ==
> User-Agent: curl/7.35.0
> Host: mysite.net:4243
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
* Server Docker/1.12.0 (linux) is not blacklisted
< Server: Docker/1.12.0 (linux)
< Date: Wed, 10 Aug 2016 03:40:48 GMT
< Transfer-Encoding: chunked
< 
{"status":"Pulling repository mysite.net/test-image"}
{"errorDetail":{"message":"Error: image test-image not found"},"error":"Error: image test-image not found"}
* Connection #0 to host mysite.net left intact

[1]+  Done                    curl -v -X POST http://mysite.net:4243/images/create?fromImage=mysite.net/test-image



hadmin@ICSCHE0224:~$ curl -v -uksanjeev:ipo2001-X POST http://mysite.net:4243/images/create?fromImage=mysite.net/test-image&tag=latest
[1] 2298
hadmin@ICSCHE0224:~$ * Rebuilt URL to: POST/
* Hostname was NOT found in DNS cache
* Could not resolve host: POST
* Closing connection 0
curl: (6) Could not resolve host: POST
* Hostname was NOT found in DNS cache
*   Trying 172.27.10.70...
* Connected to mysite.net (172.27.10.70) port 4243 (#1)
* Server auth using Basic with user 'ksanjeev'
> GET /images/create?fromImage=mysite.net/test-image HTTP/1.1
> Authorization: Basic a3NhbmplZXY6aXBvMjAwMS1Y
> User-Agent: curl/7.35.0
> Host: mysite.net:4243
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Date: Wed, 10 Aug 2016 03:46:38 GMT
< Content-Length: 29
< 
{"message":"page not found"}
* Connection #1 to host mysite.net left intact
```

Regards
Kamal
9677050305

**Comment by dmp42** [comment]
Hi @ksanjeev 

It seems you are mixing together very different issues / products.

`curl http://mysite.net:4243/images/json` definitely refers to a python, v1, registry, which you should really not be using.

My suggestion would be to start clean, from scratch, following the docs:

https://docs.docker.com/registry/

and walking through the first steps to confirm that you can successfully push & pull images from your registry.

**Comment by ksanjeev** [comment]
Hi,

I have just pulled this registry a few days back and you can also notice in the logs under docker images, I have the docker registry 2 installed. 

I was able to pass the tag instead of the digest in a similar setup and make it work

curl http://192.168.56.105:5000/v2/busybox/manifests/latest

Now I get the following error when i pass the  docker digest content for blobs

ksanjeev@curl:/docker-registry/data/docker/registry/v2/repositories$ curl -v  http://192.168.56.105:5000/v2/busybox/blobs/sha256:3d2e1cb04d2797d231242ec64b53235de54acd6889d24bb9fdfb3dcab9dd8423
* Hostname was NOT found in DNS cache
*   Trying 192.168.56.105...
* Connected to 192.168.56.105 (192.168.56.105) port 5000 (#0)
> GET /v2/busybox/blobs/sha256:3d2e1cb04d2797d231242ec64b53235de54acd6889d24bb9fdfb3dcab9dd8423 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 192.168.56.105:5000
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< Date: Wed, 10 Aug 2016 18:22:25 GMT
< Content-Length: 157
< 
{"errors":[{"code":"BLOB_UNKNOWN","message":"blob unknown to registry","detail":"sha256:3d2e1cb04d2797d231242ec64b53235de54acd6889d24bb9fdfb3dcab9dd8423"}]}
* Connection #0 to host 192.168.56.105 left intact


Can you advise on the same.

**Comment by dmp42** [comment]
Can you copy the output of `curl http://192.168.56.105:5000/v2/busybox/manifests/latest` ?

**Comment by ksanjeev** [comment]
ksanjeev@curl:/docker-registry$ curl -v http://192.168.56.105:5000/v2/busybox/manifests/latest
* Hostname was NOT found in DNS cache
*   Trying 192.168.56.105...
* Connected to 192.168.56.105 (192.168.56.105) port 5000 (#0)
> GET /v2/busybox/manifests/latest HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 192.168.56.105:5000
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 5554
< Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
< Docker-Content-Digest: sha256:3d2e1cb04d2797d231242ec64b53235de54acd6889d24bb9fdfb3dcab9dd8423
< Docker-Distribution-Api-Version: registry/2.0
< Etag: "sha256:3d2e1cb04d2797d231242ec64b53235de54acd6889d24bb9fdfb3dcab9dd8423"
< X-Content-Type-Options: nosniff
< Date: Wed, 10 Aug 2016 18:08:31 GMT
< 
{
   "schemaVersion": 1,
   "name": "busybox",
   "tag": "latest",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:ccfc4df4fbba7d591c1eff4972018e67c1142b21b64bc36fba3f93bd33f2ebd9"
      },
      {
         "blobSum": "sha256:b171f9dbc13b68a99386e4d54e28e26144688973ad7bbdd9ec1f822dc8b0ac0a"
      },
      {
         "blobSum": "sha256:ed40d4bcb31369df1a018c64e560e94dfd106d0b2851db25f921d3708d64fac5"
      },
      {
         "blobSum": "sha256:96c6a1f3c3b0183063a9dad891fe6d8ec466c2fdf9571a0c19b3319ea8a58871"
      }
   ],
   "history": [
      {
         "v1Compatibility": "{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"4f17211570c2\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/bash\"],\"ArgsEscaped\":true,\"Image\":\"sha256:10d8d8927a18acdd1dd6fac7dbecbd467fb95f65e4d603487dd1d4a378bf238d\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"container\":\"729aaafbe35c693624b472e8f0e4fb7e4534154166ca9709ef332a8c98e48469\",\"container_config\":{\"Hostname\":\"4f17211570c2\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) CMD [\\\"/bin/bash\\\"]\"],\"ArgsEscaped\":true,\"Image\":\"sha256:10d8d8927a18acdd1dd6fac7dbecbd467fb95f65e4d603487dd1d4a378bf238d\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2016-07-22T15:19:02.624014485Z\",\"docker_version\":\"1.10.3\",\"id\":\"87d8afb341b59b068cebefaf8e47f146faa5f3a4eee752905f3535c156fda542\",\"os\":\"linux\",\"parent\":\"46e772baf32ab478833f80b56547d5b1ad002ee8f6610d8dc38a96ec02621273\",\"throwaway\":true}"
      },
      {
         "v1Compatibility": "{\"id\":\"46e772baf32ab478833f80b56547d5b1ad002ee8f6610d8dc38a96ec02621273\",\"parent\":\"0a7a3b7681063c29d30aafea011d773509bf89038badf9e49c79945d71e9ca37\",\"created\":\"2016-07-22T15:19:02.033058361Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c sed -i 's/^#\\\\s*\\\\(deb.*universe\\\\)$/\\\\1/g' /etc/apt/sources.list\"]}}"
      },
      {
         "v1Compatibility": "{\"id\":\"0a7a3b7681063c29d30aafea011d773509bf89038badf9e49c79945d71e9ca37\",\"parent\":\"e094bcb9d0fe544c5fa81bab27433a44beac466e3330bc5938ef8f79b89a37d2\",\"created\":\"2016-07-22T15:19:00.260822534Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c rm -rf /var/lib/apt/lists/*\"]}}"
      },
      {
         "v1Compatibility": "{\"id\":\"e094bcb9d0fe544c5fa81bab27433a44beac466e3330bc5938ef8f79b89a37d2\",\"parent\":\"a16f6804bd851335a2d556a9a84791366c54e104088b3ab8b2f30f106822c0c0\",\"created\":\"2016-07-22T15:18:58.549740971Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c set -xe \\t\\t\\u0026\\u0026 echo '#!/bin/sh' \\u003e /usr/sbin/policy-rc.d \\t\\u0026\\u0026 echo 'exit 101' \\u003e\\u003e /usr/sbin/policy-rc.d \\t\\u0026\\u0026 chmod +x /usr/sbin/policy-rc.d \\t\\t\\u0026\\u0026 dpkg-divert --local --rename --add /sbin/initctl \\t\\u0026\\u0026 cp -a /usr/sbin/policy-rc.d /sbin/initctl \\t\\u0026\\u0026 sed -i 's/^exit.*/exit 0/' /sbin/initctl \\t\\t\\u0026\\u0026 echo 'force-unsafe-io' \\u003e /etc/dpkg/dpkg.cfg.d/docker-apt-speedup \\t\\t\\u0026\\u0026 echo 'DPkg::Post-Invoke { \\\"rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true\\\"; };' \\u003e /etc/apt/apt.conf.d/docker-clean \\t\\u0026\\u0026 echo 'APT::Update::Post-Invoke { \\\"rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true\\\"; };' \\u003e\\u003e /etc/apt/apt.conf.d/docker-clean \\t\\u0026\\u0026 echo 'Dir::Cache::pkgcache \\\"\\\"; Dir::Cache::srcpkgcache \\\"\\\";' \\u003e\\u003e /etc/apt/apt.conf.d/docker-clean \\t\\t\\u0026\\u0026 echo 'Acquire::Languages \\\"none\\\";' \\u003e /etc/apt/apt.conf.d/docker-no-languages \\t\\t\\u0026\\u0026 echo 'Acquire::GzipIndexes \\\"true\\\"; Acquire::CompressionTypes::Order:: \\\"gz\\\";' \\u003e /etc/apt/apt.conf.d/docker-gzip-indexes \\t\\t\\u0026\\u0026 echo 'Apt::AutoRemove::SuggestsImportant \\\"false\\\";' \\u003e /etc/apt/apt.conf.d/docker-autoremove-suggests\"]}}"
      },
      {
         "v1Compatibility": "{\"id\":\"a16f6804bd851335a2d556a9a84791366c54e104088b3ab8b2f30f106822c0c0\",\"created\":\"2016-07-22T15:18:56.498996734Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:dc3b1b2c44af75026bc24b3f3a5bd5f45b9ca7ed395b91dfacd1b47fe0545fb5 in /\"]}}"
      }
   ],
   "signatures": [
      {
         "header": {
            "jwk": {
               "crv": "P-256",
               "kid": "ZX2O:MV5U:QQKR:GKML:E7U6:VMOS:6AHI:I2HJ:P2GJ:V3RR:RLPV:3BA6",
               "kty": "EC",
               "x": "wiMErC_pl4WstVz4bRukkB5mVj-km_6LBn8Z6ELEGp8",
               "y": "mpp84ouodd30zF84GcBNki2upwWbWHPBCws54QhFi58"
            },
            "alg": "ES256"
         },
         "signature": "VeWm_LiVEmVIuPkAwtrm-K4o9g0BOLwwqvGw79iSYg7JGZP3Z2qGRjpETO_xqL2eNnwu8ODsgcyYlIrDGNl1YQ",
         "protected": "eyJmb3JtYXRMZW5ndGgiOjQ5MDcsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxNi0wOC0xMFQxODowODozMVoifQ"
      }
   ]
* Connection #0 to host 192.168.56.105 left intact

**Comment by RichardScothern** [comment]
@ksanjeev `sha256:3d2e1cb04d2...` is not a blob digest.  You can see what the blob digests are in the output from your curl command.

I'm going to close this.  I highly recommend reading the docs and specs to understand the differences between manifests and blobs.
