### ISSUE TITLE
Configuring a private registry: Let's Encrypt doesn't work

### ISSUE THREAD

**Issue by EvgenyOrekhov** [docker/distribution#1903]
I'm trying to configure a private registry to use Let's Encrypt to automatically obtain a browser-trusted certificate using the `REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE` and `REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL` environment variables.

When I run `docker login mydomain.com:5000` and enter my username and password I get
```
Error response from daemon: Get https://mydomain.com:5000/v1/users/: remote error: internal error
```

The registry container logs the following:
```
registry_1  | 2016/08/15 11:38:51 [INFO][mydomain.com] acme: Obtaining bundled SAN certificate
registry_1  | 2016/08/15 11:38:51 [INFO][mydomain.com] acme: Could not find solver for: http-01
registry_1  | 2016/08/15 11:38:51 [INFO][mydomain.com] acme: Could not find solver for: dns-01
registry_1  | 2016/08/15 11:38:51 [INFO][mydomain.com] acme: Trying to solve TLS-SNI-01
registry_1  | 2016/08/15 11:38:53 http: TLS handshake error from <my-client-IP>:58430: map[mydomain.com:acme: Error 400 - urn:acme:error:connection - Failed to connect to <my-registry-IP>:443 for TLS-SNI-01 challenge
registry_1  | Error Detail:
registry_1  |   Validation for mydomain.com:443
registry_1  |   Resolved to:
registry_1  |           <my-registry-IP>
registry_1  |   Used: <my-registry-IP>
registry_1  | 
registry_1  | ]
registry_1  | 2016/08/15 11:38:53 http: TLS handshake error from <my-client-IP>:58432: map[mydomain.com:acme: Error 400 - urn:acme:error:connection - Failed to connect to <my-registry-IP>:443 for TLS-SNI-01 challenge
registry_1  | Error Detail:
registry_1  |   Validation for mydomain.com:443
registry_1  |   Resolved to:
registry_1  |           <my-registry-IP>
registry_1  |   Used: <my-registry-IP>
registry_1  | 
registry_1  | ]
```

I use the following docker-compose.yml to run the registry:
```json
{
    "version": "2",
    "services": {
        "registry": {
            "image": "registry",
            "volumes": [
                "./data/:/var/lib/registry/",
                "./letsencrypt/cachefile:/letsencrypt/cachefile",
                "./auth/:/auth/"
            ],
            "ports": [
                "5000:5000"
            ],
            "restart": "unless-stopped",
            "environment": {
                "REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE": "/letsencrypt/cachefile",
                "REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL": "my@email.com",
                "REGISTRY_AUTH": "htpasswd",
                "REGISTRY_AUTH_HTPASSWD_PATH": "/auth/htpasswd",
                "REGISTRY_AUTH_HTPASSWD_REALM": "Registry Realm"
            }
        }
    }
}
```

Here is the info about my system:
```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 20
 Running: 8
 Paused: 0
 Stopped: 12
Images: 19
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 178
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-91-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: myserver
ID: 5EAG:WCZK:YQM4:UEMS:IHOS:G2SZ:2RR5:BOIP:4UN2:EQZP:GZ5S:33ZH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

$ docker exec dockerregistry_registry_1 registry --version
registry github.com/docker/distribution v2.5.0
```

**Comment by dmcgowan** [comment]
Are you able to connect to `<my-registry-IP>` from outside your network? It looks like the DNS is resolving correctly but the acme protocol cannot be completed to do a connection failure.

**Comment by EvgenyOrekhov** [comment]
@dmcgowan Yes, I am able to connect to <my-registry-IP> and to mydomain.com from outside my network.

**Comment by EvgenyOrekhov** [comment]
If the registry logs `Validation for mydomain.com:443` then the acme protocol needs port 443, am I correct? But how can it work if I don't have anything running on port 443?

**Comment by dmcgowan** [comment]
I can't seem to find it in their docs but it makes sense that Let's Encrypt would assume port 443. Are you able to expose port 443 for the registry? We can add a note in our docs for which port should be used when doing Let's Encrypt.

**Comment by EvgenyOrekhov** [comment]
@dmcgowan I tried adding "443:443" to the "ports" array in docker-compose.yml and it made no difference. The error is the same.

**Comment by dmcgowan** [comment]
Did you update the registry to listen on that port as well? I would have expected just changing the ports to "443:5000"

**Comment by EvgenyOrekhov** [comment]
@dmcgowan Thanks, "443:5000" worked! It should be in the Docker Registry docs. Although, I think it would be better if it would be possible to use port 5000, because it is the default port.

**Comment by RichardScothern** [comment]
closing as fixed 🎈

**Comment by EvgenyOrekhov** [comment]
@RichardScothern The issue should not be closed until the info regarding ports is added to the [letsencrypt section](https://docs.docker.com/registry/configuration/#letsencrypt) of the Docker Registry docs.

**Comment by dmcgowan** [comment]
Created https://github.com/docker/distribution/pull/1940, no need to keep this open

**Comment by steve-taylor** [comment]
If you came here from Google after January 2018, then letsencrypt support is completely broken. [letsencrypt has disabled the only challenge that `registry` supports](https://community.letsencrypt.org/t/2018-01-09-issue-with-tls-sni-01-and-shared-hosting-infrastructure/49996). See #2545.

**Comment by stevvooe** [comment]
> Update #1: We have decided to re-enable the TLS-SNI-01 challenge for certain major providers who are known not to have issues while we investigate re-enabling TLS-SNI-01 in general. We’re doing this as a safe way to restore service faster for a large number of sites.

Looks like they've reenabled it but we are going to revisit this.

**Comment by steve-taylor** [comment]
Followed by
> [Update 2018-01-18: The most up-to-date summary is at [IMPORTANT: What you need to know about TLS-SNI validation issues](https://community.letsencrypt.org/t/important-what-you-need-to-know-about-tls-sni-validation-issues/50811)]

The linked page says

> We’ve decided that TLS-SNI will [remain disabled for most new issuances](https://community.letsencrypt.org/t/tls-sni-challenges-disabled-for-most-new-issuance/50316)

And the link in that quote is to an older announcement.

So the gist of it is that TLS-SNI-01 is disabled for all new issuances and is available only for renewals. Also, it's a bit unclear as to whether it's still enabled for issuances by large providers, but the key part of that is that, if available, it's by account ID whitelist only. I'm assuming that's mainly large SaaS providers that issue a very large number of subdomains and integrate with LetsEncrypt. For you and me, trying to issue new certificates today, TNS-SNI-01 simply won't work.

**Comment by stevvooe** [comment]
@steve-taylor That is a huge bummer. I've milestoned #2545. I think there is also another PR (#2530) that moves support from the rsc version to a better supported version of the library. We still need to look at the compatibility issues with that, but it seems like it doesn't matter, because it is completely broken.

**Comment by chrishecker** [comment]
> So the gist of it is that TLS-SNI-01 is disabled for all new issuances and is available only for renewals.
It's not even working for renewals for me.  I've got previous LE certs on this domain and now they're failing to renew and have been for a while.

Chris
