### ISSUE TITLE
GO build no field or method Reader/Writer/Blobs

### ISSUE THREAD

**Issue by aabergaa** [docker/distribution#1905]
**Output of `docker version`:**
```
Docker version 1.10.1, build 9e83765
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on a 32 core physical server on a disconnected private network so access to docker.io, github.com/..., and any other repo sites is not an option in builds

**Steps to reproduce the issue:**
1. Install docker-engine and dependencies. Import a base image (only RHEL and derivatives are an option, the base image used has basic build tools (C,C++, Java, make) available if needed. 
2. Import the golang and lint tools for go build deps, docker, and docker-distribution to build a newer version of the registry than rpms have available
3. run docker build on the distribution dockerfile (noting the Docker files were shifted to an available centos7.2 image base with build tools added to the install at first stages). 

**Describe the results you received:**
Everything start out fine, during the final stages of the go compiling (I assume), I get:

#github.com/docker/distribution/registry/storage/driver/base
registry/storage/driver/base/regulator.go:85: r.StorageDriver.Reader undefined (type driver.StorageDriver has no field or method Reader)
registry/storage/driver/base/regulator.go:85: not enough arguments to return
registry/storage/driver/base/regulator.go:92: undefined: driver.FileWriter
registry/storage/driver/base/regulator.go:96: r.StorageDriver.Writer undefined (type driver.StorageDriver has no field or method Writer)
#github.com/docker/distribution/registry/storage
registry/storage/garbagecollect.go:20: undefined: distribution.RepositoryEnumerator
registry/storage/garbagecollect.go:37: cannot use named (type reference.Named) as type string in argument to registry.Repository
registry/storage/garbagecollect.go:47: undefined: distribution.ManifestEnumerator
registry/storage/garbagecollect.go:104: registry.Blobs undefined (type distribution.Namespace has no field or method Blobs)

I have checked those files from my tarballs that get imported to the image, and those functions seem to be defined as they are being used. 

**Describe the results you expected:**
I properly built docker image to run as a registry. 

**Additional information you deem important (e.g. issue happens only occasionally):**
If I do not import the main docker/docker tarball, many more such errors occur. I assume this is some go issue with some versioning, but not sure what steps are necessary to correct it. I have go 1.6.3 being installed to the image, but have also tried 1.5.3 with similar results. 
For reference, the Dockerfile being used inplace of the default in the docker/distribution:
```
FROM local-registry:5000/centos7

ADD go1.6.3.linux-amd64.tar.gz /usr/local

ENV PATH /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go:/go/src/github.com/docker/docker/vendor
ENV DOCKER_BUILDTAGS include_oss include_gcs

#add the docker.git repo files:
ADD docker.tar.gz.orig /go/
#add the docker/distribution repo files:
ADD distribution.tar.gz /go/src/github.com/docker/distribution/
#dependencies of go file on AdRoll's goamz needed to be added:
ADD goamz.tar.gz /go/src/
#go build deps: tools/golang and lint added into godevel.tar.gz
ADD godevel.tar.gz 

#install make:
RUN yum install --assumeyes make

WORKDIR /go/src/github.com/docker/distribution

RUN  \
GOPATH="$GOPATH/Godeps/_workspace:$GOPATH" \
 && make PREFIX=/go clean binaries

```
# NOTES: 
command tried from docker/Dockerfile also produced same error after pulling in the cloned repos:
go build -o /usr/local/bin/registry-v2 github.com/docker/distribution/cmd/registry

running in the image itself (well, the image that remains after attempting to build, doing a 
```go test github.com/docker/distribution/cmd/registry ```
also gives the same error

**Comment by aaronlehmann** [comment]
My guess would be that there's something wrong with one or more of these tarballs, such as mixing files from different versions.

Perhaps you could try installing git in the Dockerfile and checking out the source from the git repository.

I don't know what's in `docker.tar.gz.orig` and `goamz.tar.gz`, but I suspect these aren't necessary. `distribution` vendors all of the packages that are necessary for it to build.

**Comment by aabergaa** [comment]
Those files are direct git clones of github.com/docker, github.com/docker/distribution, and github.com/AdRoll/goamz that I then tarballed and brought onto my server. 

Installing git in my dockerfile would be of no benefit - if you read my setup I am in a completely internet disconnected environment, i.e. there is not link between my server and the www world.

**Comment by aaronlehmann** [comment]
Can you try removing the `ADD` lines for goamz and docker? Perhaps the tar of github.com/docker contains some files that conflict with the distribution tar.

**Comment by aaronlehmann** [comment]
BTW, if lack of internet connectivity is an issue, one option would be to build the image on a machine with an internet connection, then use `docker save` and `docker load` to transport it to the disconnected server.

**Comment by aabergaa** [comment]
The issue with that is the official one uses a non rhel base -- and this is not an option due to some security issues I am required to adhere to.

**Comment by aabergaa** [comment]
Without goamz and the docker clones I get:

registry/storage/driver/s3/s3.go:29:2: cannot find package "github.com/AdRoll/goamz/aws" in any of:
        /usr/local/go/src/github.com/AdRoll/goamz/aws (from $GOROOT)
        /go/src/github.com/AdRoll/goamz/aws (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/AdRoll/goamz/aws
        /go/src/github.com/AdRoll/goamz/aws
        /go/src/github.com/docker/docker/vendor/src/github.com/AdRoll/goamz/aws
registry/storage/driver/middleware/cloudfront/middleware.go:13:2: cannot find package "github.com/AdRoll/goamz/cloudfront" in any of:
        /usr/local/go/src/github.com/AdRoll/goamz/cloudfront (from $GOROOT)
        /go/src/github.com/AdRoll/goamz/cloudfront (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/AdRoll/goamz/cloudfront
        /go/src/github.com/AdRoll/goamz/cloudfront
        /go/src/github.com/docker/docker/vendor/src/github.com/AdRoll/goamz/cloudfront
registry/storage/driver/s3/s3.go:30:2: cannot find package "github.com/AdRoll/goamz/s3" in any of:
        /usr/local/go/src/github.com/AdRoll/goamz/s3 (from $GOROOT)
        /go/src/github.com/AdRoll/goamz/s3 (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/AdRoll/goamz/s3
        /go/src/github.com/AdRoll/goamz/s3
        /go/src/github.com/docker/docker/vendor/src/github.com/AdRoll/goamz/s3
registry/storage/driver/azure/azure.go:19:2: cannot find package "github.com/Azure/azure-sdk-for-go/storage" in any of:
        /usr/local/go/src/github.com/Azure/azure-sdk-for-go/storage (from $GOROOT)
        /go/src/github.com/Azure/azure-sdk-for-go/storage (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/Azure/azure-sdk-for-go/storage
        /go/src/github.com/Azure/azure-sdk-for-go/storage
        /go/src/github.com/docker/docker/vendor/src/github.com/Azure/azure-sdk-for-go/storage
registry/registry.go:12:2: cannot find package "github.com/Sirupsen/logrus" in any of:
        /usr/local/go/src/github.com/Sirupsen/logrus (from $GOROOT)
        /go/src/github.com/Sirupsen/logrus (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/Sirupsen/logrus
        /go/src/github.com/Sirupsen/logrus
        /go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus
registry/registry.go:13:2: cannot find package "github.com/Sirupsen/logrus/formatters/logstash" in any of:
        /usr/local/go/src/github.com/Sirupsen/logrus/formatters/logstash (from $GOROOT)
        /go/src/github.com/Sirupsen/logrus/formatters/logstash (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/Sirupsen/logrus/formatters/logstash
        /go/src/github.com/Sirupsen/logrus/formatters/logstash
        /go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus/formatters/logstash
registry/registry.go:14:2: cannot find package "github.com/bugsnag/bugsnag-go" in any of:
        /usr/local/go/src/github.com/bugsnag/bugsnag-go (from $GOROOT)
        /go/src/github.com/bugsnag/bugsnag-go (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/bugsnag/bugsnag-go
        /go/src/github.com/bugsnag/bugsnag-go
        /go/src/github.com/docker/docker/vendor/src/github.com/bugsnag/bugsnag-go
registry/storage/driver/oss/oss.go:29:2: cannot find package "github.com/denverdino/aliyungo/oss" in any of:
        /usr/local/go/src/github.com/denverdino/aliyungo/oss (from $GOROOT)
        /go/src/github.com/denverdino/aliyungo/oss (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/denverdino/aliyungo/oss
        /go/src/github.com/denverdino/aliyungo/oss
        /go/src/github.com/docker/docker/vendor/src/github.com/denverdino/aliyungo/oss
manifest/schema1/config_builder.go:12:2: cannot find package "github.com/docker/libtrust" in any of:
        /usr/local/go/src/github.com/docker/libtrust (from $GOROOT)
        /go/src/github.com/docker/libtrust (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/docker/libtrust
        /go/src/github.com/docker/libtrust
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/libtrust
registry/storage/cache/redis/redis.go:11:2: cannot find package "github.com/garyburd/redigo/redis" in any of:
        /usr/local/go/src/github.com/garyburd/redigo/redis (from $GOROOT)
        /go/src/github.com/garyburd/redigo/redis (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/garyburd/redigo/redis
        /go/src/github.com/garyburd/redigo/redis
        /go/src/github.com/docker/docker/vendor/src/github.com/garyburd/redigo/redis
registry/handlers/blob.go:11:2: cannot find package "github.com/gorilla/handlers" in any of:
        /usr/local/go/src/github.com/gorilla/handlers (from $GOROOT)
        /go/src/github.com/gorilla/handlers (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/gorilla/handlers
        /go/src/github.com/gorilla/handlers
        /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/handlers
context/http.go:13:2: cannot find package "github.com/gorilla/mux" in any of:
        /usr/local/go/src/github.com/gorilla/mux (from $GOROOT)
        /go/src/github.com/gorilla/mux (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/gorilla/mux
        /go/src/github.com/gorilla/mux
        /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux
registry/storage/driver/swift/swift.go:34:2: cannot find package "github.com/mitchellh/mapstructure" in any of:
        /usr/local/go/src/github.com/mitchellh/mapstructure (from $GOROOT)
        /go/src/github.com/mitchellh/mapstructure (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/mitchellh/mapstructure
        /go/src/github.com/mitchellh/mapstructure
        /go/src/github.com/docker/docker/vendor/src/github.com/mitchellh/mapstructure
registry/storage/driver/swift/swift.go:35:2: cannot find package "github.com/ncw/swift" in any of:
        /usr/local/go/src/github.com/ncw/swift (from $GOROOT)
        /go/src/github.com/ncw/swift (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/ncw/swift
        /go/src/github.com/ncw/swift
        /go/src/github.com/docker/docker/vendor/src/github.com/ncw/swift
registry/registry.go:23:2: cannot find package "github.com/spf13/cobra" in any of:
        /usr/local/go/src/github.com/spf13/cobra (from $GOROOT)
        /go/src/github.com/spf13/cobra (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/spf13/cobra
        /go/src/github.com/spf13/cobra
        /go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra
registry/storage/blobwriter_resumable.go:15:2: cannot find package "github.com/stevvooe/resumable" in any of:
        /usr/local/go/src/github.com/stevvooe/resumable (from $GOROOT)
        /go/src/github.com/stevvooe/resumable (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/stevvooe/resumable
        /go/src/github.com/stevvooe/resumable
        /go/src/github.com/docker/docker/vendor/src/github.com/stevvooe/resumable
registry/storage/blobwriter_resumable.go:18:2: cannot find package "github.com/stevvooe/resumable/sha256" in any of:
        /usr/local/go/src/github.com/stevvooe/resumable/sha256 (from $GOROOT)
        /go/src/github.com/stevvooe/resumable/sha256 (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/stevvooe/resumable/sha256
        /go/src/github.com/stevvooe/resumable/sha256
        /go/src/github.com/docker/docker/vendor/src/github.com/stevvooe/resumable/sha256
registry/storage/blobwriter_resumable.go:19:2: cannot find package "github.com/stevvooe/resumable/sha512" in any of:
        /usr/local/go/src/github.com/stevvooe/resumable/sha512 (from $GOROOT)
        /go/src/github.com/stevvooe/resumable/sha512 (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/stevvooe/resumable/sha512
        /go/src/github.com/stevvooe/resumable/sha512
        /go/src/github.com/docker/docker/vendor/src/github.com/stevvooe/resumable/sha512
registry/registry.go:24:2: cannot find package "github.com/yvasiyarov/gorelic" in any of:
        /usr/local/go/src/github.com/yvasiyarov/gorelic (from $GOROOT)
        /go/src/github.com/yvasiyarov/gorelic (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/github.com/yvasiyarov/gorelic
        /go/src/github.com/yvasiyarov/gorelic
        /go/src/github.com/docker/docker/vendor/src/github.com/yvasiyarov/gorelic
registry/auth/htpasswd/htpasswd.go:9:2: cannot find package "golang.org/x/crypto/bcrypt" in any of:
        /usr/local/go/src/golang.org/x/crypto/bcrypt (from $GOROOT)
        /go/src/golang.org/x/crypto/bcrypt (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/golang.org/x/crypto/bcrypt
        /go/src/golang.org/x/crypto/bcrypt
        /go/src/github.com/docker/docker/vendor/src/golang.org/x/crypto/bcrypt
context/context.go:7:2: cannot find package "golang.org/x/net/context" in any of:
        /usr/local/go/src/golang.org/x/net/context (from $GOROOT)
        /go/src/golang.org/x/net/context (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/golang.org/x/net/context
        /go/src/golang.org/x/net/context
        /go/src/github.com/docker/docker/vendor/src/golang.org/x/net/context
registry/storage/driver/gcs/gcs.go:33:2: cannot find package "golang.org/x/oauth2" in any of:
        /usr/local/go/src/golang.org/x/oauth2 (from $GOROOT)
        /go/src/golang.org/x/oauth2 (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/golang.org/x/oauth2
        /go/src/golang.org/x/oauth2
        /go/src/github.com/docker/docker/vendor/src/golang.org/x/oauth2
registry/storage/driver/gcs/gcs.go:34:2: cannot find package "golang.org/x/oauth2/google" in any of:
        /usr/local/go/src/golang.org/x/oauth2/google (from $GOROOT)
        /go/src/golang.org/x/oauth2/google (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/golang.org/x/oauth2/google
        /go/src/golang.org/x/oauth2/google
        /go/src/github.com/docker/docker/vendor/src/golang.org/x/oauth2/google
registry/storage/driver/gcs/gcs.go:35:2: cannot find package "golang.org/x/oauth2/jwt" in any of:
        /usr/local/go/src/golang.org/x/oauth2/jwt (from $GOROOT)
        /go/src/golang.org/x/oauth2/jwt (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/golang.org/x/oauth2/jwt
        /go/src/golang.org/x/oauth2/jwt
        /go/src/github.com/docker/docker/vendor/src/golang.org/x/oauth2/jwt
registry/storage/driver/gcs/gcs.go:36:2: cannot find package "google.golang.org/api/googleapi" in any of:
        /usr/local/go/src/google.golang.org/api/googleapi (from $GOROOT)
        /go/src/google.golang.org/api/googleapi (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/google.golang.org/api/googleapi
        /go/src/google.golang.org/api/googleapi
        /go/src/github.com/docker/docker/vendor/src/google.golang.org/api/googleapi
registry/storage/driver/gcs/gcs.go:37:2: cannot find package "google.golang.org/api/storage/v1" in any of:
        /usr/local/go/src/google.golang.org/api/storage/v1 (from $GOROOT)
        /go/src/google.golang.org/api/storage/v1 (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/google.golang.org/api/storage/v1
        /go/src/google.golang.org/api/storage/v1
        /go/src/github.com/docker/docker/vendor/src/google.golang.org/api/storage/v1
registry/storage/driver/gcs/gcs.go:38:2: cannot find package "google.golang.org/cloud" in any of:
        /usr/local/go/src/google.golang.org/cloud (from $GOROOT)
        /go/src/google.golang.org/cloud (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/google.golang.org/cloud
        /go/src/google.golang.org/cloud
        /go/src/github.com/docker/docker/vendor/src/google.golang.org/cloud
registry/storage/driver/gcs/gcs.go:39:2: cannot find package "google.golang.org/cloud/storage" in any of:
        /usr/local/go/src/google.golang.org/cloud/storage (from $GOROOT)
        /go/src/google.golang.org/cloud/storage (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/google.golang.org/cloud/storage
        /go/src/google.golang.org/cloud/storage
        /go/src/github.com/docker/docker/vendor/src/google.golang.org/cloud/storage
configuration/parser.go:12:2: cannot find package "gopkg.in/yaml.v2" in any of:
        /usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
        /go/src/gopkg.in/yaml.v2 (from $GOPATH)
        /go/src/github.com/docker/docker/vendor/Godeps/_workspace/src/gopkg.in/yaml.v2
        /go/src/gopkg.in/yaml.v2
        /go/src/github.com/docker/docker/vendor/src/gopkg.in/yaml.v2
make: *** [/go/bin/registry] Error 1

**Comment by aaronlehmann** [comment]
I think the problem is an incorrect GOPATH. It should just be `/go`, and it shouldn't modified in the `make` command. Go should automatically pick up the vendored packages from `/go/src/github.com/docker/distribution/vendor`. Does this directory exist?

**Comment by aabergaa** [comment]
I have tried with and without the GOPATH as part of the script (and had done so prior to posting the original issue). It does not seem to make a difference whether that is there or not.

**Comment by aabergaa** [comment]
Seems it finally built. Had to explicitly have /go/src/github.com/docker/distribution/Godeps/_workspace at the end of the GOPATH - it must not have been picking up the full directory structure as it is supposed to?

**Comment by aaronlehmann** [comment]
Are you using an old checkout of the source tree? `Godeps/_workspace` was moved to `vendor` several months ago. Nevertheless, glad you got it working.

**Comment by aabergaa** [comment]
I didn't think I was because it was a fresh clone - I had not even attempted to use v2 of the registry yet and had never checked out the github branches for either docker or docker/distribution. But lack of /vendor files must have somehow gotten an old copy, no idea how.
