### ISSUE TITLE
Add a migration tool for old registry configs

### ISSUE THREAD

**Issue by miminar** [docker/distribution#1908]
As Docker distribution application evolves, so does evolve its configuration file. Some config options get obsolete, renamed made mandatory. We ourselves introduced some backwards incompatible changes to our middleware configuration section.

This previously led to many bugs and issues filled because of using old configuration files with newer registry version.

To make the transitions to newer registry versions as painles as possible, let's add a migration tool to config files. If the docker registry fails to parse configuration file or our middleware fails to load due to wrong options, let's terminate gracefully with some helpful message like:

```
fatal: obsolete configuration detected, please run `oadm migrate registry-config <oldconfigfile>` to update your config file
```

**Comment by RichardScothern** [comment]
hi @miminar as far as I'm aware this is not an issue in the open source registry (the blobdescriptor / layercache change is handled in code).

Can your middleware not detect invalid configuration parameters and emit this message before the error gets back to the registry?

**Comment by miminar** [comment]
@RichardScothern I'm sorry, this should go probably to openshift/origin. Closing this.
