### ISSUE TITLE
newAccessController should check PEM block type

### ISSUE THREAD

**Issue by jheiss** [docker/distribution#1909]
Our internal SSL certificate generation tooling issues a single file containing both the private key and the certificate chain. With applications (e.g. apache httpd, nginx) which use OpenSSL to load these files you can safely supply the same file for the private key and certificate and OpenSSL will pick out the appropriate entries.

The code to parse the certificate file for a token auth server (https://github.com/docker/distribution/blob/master/registry/auth/token/accesscontroller.go#L176) does not check the type of PEM blocks in the file and thus feeds the private key to x509.ParseCertificate, which blows up. If it had a check for pemBlock.Type == "CERTIFICATE" this would not happen.

**Comment by dmcgowan** [comment]
Agreed, this should check the type. Since you have already done all the hard work of tracking it down do you want to open up a PR to only add the certificate for that type? I don't want to take the credit for your fix but happy to open up a PR :smile:

**Comment by jheiss** [comment]
I've put in the request to my employer to let me contribute here but it might take a few days to get approved. Feel free to fix this sooner if you get around to it.
