### ISSUE TITLE
Notification payload / structure changed from 2.3.1 > ?

### ISSUE THREAD

**Issue by EugenMayer** [docker/distribution#1916]
I am having an odd issue with portus : https://gist.github.com/EugenMayer/be3ea8cabecf44db0185cf90136ab9a8

The notification are working when i use a registry 2.3.1 or below, but they stop working from 2.4

Using the payload from https://gist.github.com/EugenMayer/be3ea8cabecf44db0185cf90136ab9a8 it does work using curl for portus - but that is maybe no longer the correct payload and things "slipped through" without documentation? Can somebody share some light into this? 

I was not able to see the actual payload, even with log level debug on the registry side

**Comment by RichardScothern** [comment]
The [release notes](https://github.com/docker/distribution/releases/tag/v2.4.0) for 2.4 show that the tag is included in the notification, so nothing has "slipped through".  You were able to curl that payload to portus with a problem.

Your errors show the http client in the registry timing out connecting to portus.   Do the portus logs show anything when you do that?

What happens if you remove that Content-Type header from curl?

**Comment by EugenMayer** [comment]
@RichardScothern how do i have a problem with curl-ing that paylayd - it rathe seemed to work?

```
< HTTP/1.1 202 Accepted
```

Looks rather ok to me, isnt it?

> Your errors show the http client in the registry timing out connecting to portus. Do the portus logs show anything when you do that?

Actually no, the portus logs actually do receive the request - https://github.com/SUSE/Portus/issues/905#issuecomment-241143378 . It is for sure no network issue in general


> What happens if you remove that Content-Type header from curl?

Pretty much the same i would guess - but for that rather seems working?

```
* Connected to portus (10.42.45.122) port 3000 (#0)
> POST /v2/webhooks/events HTTP/1.1
> Host: portus:3000
> User-Agent: curl/7.50.1
> Accept: */*
> Content-Length: 1037
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
* Done waiting for 100-continue
* We are completely uploaded and fine
< HTTP/1.1 202 Accepted
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Type: application/json
< Cache-Control: no-cache
< Set-Cookie: request_method=POST; path=/
< X-Request-Id: 0769c23a-462c-4c1f-a6b4-b3dff9782ab3
< X-Runtime: 0.003116
< Transfer-Encoding: chunked
<
* Connection #0 to host portus left intact
```

**Comment by RichardScothern** [comment]
I mis-typed above (it should be 'You were able to curl that payload to portus with a problem.').  My point was the content of the payload is not the problem.

This output indicate the request to which posts the notification is timing out.  It does retry, so you may see a request succeeding after initially failing.

```
retryingsink: error writing events: httpSink{http://portus:3000/v2/webhooks/events}: error posting: Post http://portus:3000/v2/webhooks/events: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying
httpSink{http://portus:3000/v2/webhooks/events} encountered too many errors, backing off
```

So, the payload is OK, the portus logs actually do receive the request.  
The missing link is this line doesn't appear in the portus log for the registry-sent notification:
```
8/20/2016 10:09:56 AM  Parameters: {"events"=>[{"id"=>"320678d8-ca14-430f-8bb6-4ca139cd83f7", "timestamp"=>"2016-03-09T14:44:26.402973972-08:00", "action"=>"pull", "target"=>{"mediaType"=>"application/vnd.docker.distribution.manifest.v2+json", "size"=>708, "digest"=>"sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf", "length"=>708, "repository"=>"hello-world", "url"=>"http://192.168.100.227:5000/v2/hello-world/manifests/sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf", "tag"=>"latest"}, "request"=>{"id"=>"6df24a34-0959-4923-81ca-14f09767db19", "addr"=>"192.168.64.11:42961", "host"=>"192.168.100.227:5000", "method"=>"GET", "useragent"=>"curl/7.38.0"}, "actor"=>{}, "source"=>{"addr"=>"xtal.local:5000", "instanceID"=>"a53db899-3b4b-4a62-a067-8dd013beaca4"}}], "event"=>{"events"=>[{"id"=>"320678d8-ca14-430f-8bb6-4ca139cd83f7", "timestamp"=>"2016-03-09T14:44:26.402973972-08:00", "action"=>"pull", "target"=>{"mediaType"=>"application/vnd.docker.distribution.manifest.v2+json", "size"=>708, "digest"=>"sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf", "length"=>708, "repository"=>"hello-world", "url"=>"http://192.168.100.227:5000/v2/hello-world/manifests/sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf", "tag"=>"latest"}, "request"=>{"id"=>"6df24a34-0959-4923-81ca-14f09767db19", "addr"=>"192.168.64.11:42961", "host"=>"192.168.100.227:5000", "method"=>"GET", "useragent"=>"curl/7.38.0"}, "actor"=>{}, "source"=>{"addr"=>"xtal.local:5000", "instanceID"=>"a53db899-3b4b-4a62-a067-8dd013beaca4"}}]}}
```
which suggests portus can't process the event.

**Comment by EugenMayer** [comment]
@RichardScothern exactly my suggestion also - that is why i asked how the payload has been changed and i guess the "tag" is for now the only indication, right?

Thank you for your help

**Comment by RichardScothern** [comment]
did you get some closure @EugenMayer 

I see nothing actionable on the registry here.  If there is a bug with the registry, please file a new issue.

**Comment by EugenMayer** [comment]
@RichardScothern for now i  second you, no issue / action required here. Thank you for cleaning up

**Comment by vsizov** [comment]
I get the same error even when use endpoint generated by `https://requestb.in`

At the same time, I see some repeating posts to my endpoint but It doen't seem like registry marks them as delivered so I see lots of errors `retryingsink: error writing events: httpSink` in my log.

**Comment by vsizov** [comment]
I use 2.6.2 BTW

**Comment by vsizov** [comment]
That was a bug in the documentation. I reported it https://github.com/docker/docker.github.io/issues/5612
