### ISSUE TITLE
Different user should see their own images

### ISSUE THREAD

**Issue by marvelliu** [docker/distribution#1917]
My situation is that we have a docker registry v2, users can push their own images to the registry and they should view and update their own images, not others'.

After I set up htaccess files, I found user A is able to login, push image T to the registry. but soon after user B logins, B can also see image T, which is a security problem.

So is there any way to isolute user A and user B, user B can not see user A's images unless the admin authorize that.

**Comment by RichardScothern** [comment]
@marvelliu htpasswd provides authentication (user validation), but not authentication (repository ownership).  For authentication you'll need to use token auth with a token server plugged into your auth systems.  Have a look at the token auth documentation.  There is a sample token server in the `contrib` directory and some open source implementations.
