### ISSUE TITLE
letsEncrypt CA is an 'unknown authority' to Docker Trusted Registry

### ISSUE THREAD

**Issue by ezeeetm** [docker/distribution#1920]
I obtained a full certchain, private key, etc. using LetsEncrypt. When adding this cert to Docker Trusted Registry (Settings>Domain>Show TLS settings), and saving the configuration, a popup appears with the message:

Unable to save settings: x509: certificate signed by unknown authority

Where can we see the list of CA's that are considered 'known' by DTR?

**Comment by RichardScothern** [comment]
@ezeeetm Can you send your question to DTR support?  This repository is for the open source registry and DTR components are not maintained here.
