### ISSUE TITLE
Registry should support S3 compatible object store services

### ISSUE THREAD

**Issue by spicykaiju** [docker/distribution#1922]
There are a number of S3 compatible object store services provided by various cloud platforms. The Docker private registry should support an environment configuration var to specify the compatible S3 target:

ENV AWS_S3_HOST=s3service.provider.com

**Comment by RichardScothern** [comment]
It already does @spicykaiju   Please read the configuration documentation for more details.

**Comment by spicykaiju** [comment]
So it does @RichardScothern - for some reason I did not see the "regionendpoint" s3 parameter. Thanks! :)

**Comment by guyson** [comment]
what 's the region when it's s3 compatible service? "Default" ?  "US" ?
