### ISSUE TITLE
Server Gave HTTP Response to HTTPS Client error

### ISSUE THREAD

**Issue by pleegor** [docker/distribution#1929]
Hi, 

I am trying to run docker registry in insecure mode and when I am either trying to push or to pull. I get the following error: 

This is command I used in order to run my registry:

```
# docker run -d -p 5000:5000 --restart=always --name registry -v `pwd`/data:/var/lib/registry reg
istry:2
```

```
~# docker push <IP>:5000/ubuntu
The push refers to a repository [<IP>:5000/ubuntu]
Get https://<IP>:5000/v1/_ping: http: server gave HTTP response to HTTPS client
```

This is the version info: 
```
docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.858 GiB
Name: dock
ID: S6TG:K4K3:XSYK:VZWE:X27Y:RZUO:Z2FA:ATZT:ZBIP:KGHY:AGUZ:NLLD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

This is what I added into /etc/default/docker file
`
DOCKER_OPTS="--insecure-registry <myip>:5000"
` 

I tried edited that line with FQDN, IP address, `--insecure-registry=<myip>:5000`, and` --insecure-registry http://<myip>:5000`

Any ideas what could be causing this error?

**Comment by RichardScothern** [comment]
*Please follow these instructions to help us diagnose your issue*

 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6.  copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 8. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry

**Comment by dmcgowan** [comment]
Need to see logs from step 1 Richard posted above.

**Comment by pleegor** [comment]
I am not using any storage external storage, nether proxy (just a simple setup behind firewall). I configured everything based on the https://docs.docker.com/registry/ document

Per your suggestion I ran registry container in debug mode
`
docker -D run -d -p 5000:5000 --restart=always --name registry -v `pwd`/data:/var/lib/registry registry:2
1bb4f729b5a5217b6ea181ed708ffa35ce33542d22e7fd0471326b62df3edb19
` 
after running docker pull on one of the clients I am still getting the same error. Here are the logs from registry container.

`
 docker logs registry
time="2016-08-29T18:05:03Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.6.3 instance.id=ce173a38-c7f8-4572-9a17-4ae95b3c6bd6 version=v2.5.0
time="2016-08-29T18:05:03Z" level=info msg="redis not configured" go.version=go1.6.3 instance.id=ce173a38-c7f8-4572-9a17-4ae95b3c6bd6 version=v2.5.0
time="2016-08-29T18:05:03Z" level=info msg="Starting upload purge in 59m0s" go.version=go1.6.3 instance.id=ce173a38-c7f8-4572-9a17-4ae95b3c6bd6 version=v2.5.0
time="2016-08-29T18:05:03Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.3 instance.id=ce173a38-c7f8-4572-9a17-4ae95b3c6bd6 version=v2.5.0
time="2016-08-29T18:05:03Z" level=info msg="listening on [::]:5000" go.version=go1.6.3 instance.id=ce173a38-c7f8-4572-9a17-4ae95b3c6bd6 version=v2.5.0
`

**Comment by dmcgowan** [comment]
Most important steps, based on the message the registry is likely not being hit to produce logs.

1) restart your docker daemon in debug mode (add -D to the daemon launch arguments)
2) reproduce your problem and get your docker daemon logs showing the error

**Comment by pleegor** [comment]
https://gist.github.com/pleegor/9a264e7266254df7252beed4d46de3c4

**Comment by dmcgowan** [comment]
Can you send the docker daemon logs for when the push and pull are attempted. The log only contain the registry startup.

**Comment by pleegor** [comment]
https://gist.github.com/pleegor/31d006d4535f2045274ae29b10264b0d

**Comment by dmcgowan** [comment]
The docker opts are not getting set on the daemon. The configuration is not getting set, check that you systemd configuration is loading `/etc/default/docker`.

Once it is configured correctly you should see the expected ip address on the output of `docker info`

```
Insecure Registries:
 127.0.0.0/8
```

I didn't notice this was missing earlier, but that needs to be addressed first.

**Comment by pleegor** [comment]
this is /etc/default/docker https://gist.github.com/pleegor/0a67f64c2232b30cb484b1bd5532e834

**Comment by dmcgowan** [comment]
In my experience there is extra steps if you want that file to be used with systemd, see `THIS FILE DOES NOT APPLY TO SYSTEMD`. I suggest going back through the engine installation instructions to see what the recommended way to add daemon flags are for your setup. The argument looks right and may just needed to be added to your unit file instead.

**Comment by pleegor** [comment]
@dmcgowan this is what I thought moments ago not sure why documents do not cover systemd since most of the Linux flavors use it by defaults nowadays.

**Comment by dmcgowan** [comment]
I normally use https://docs.docker.com/engine/admin/systemd/ to setup with systemd. Not sure which installation docs you are looking at though.

**Comment by RichardScothern** [comment]
Are you set here @pleegor ?

**Comment by pleegor** [comment]
@RichardScothern still in progress... I will update this issue by tomorrow evening the latest :)

**Comment by dolanor** [comment]
I have the same problem here so would be happy to know if you fixed it on your side.

**Comment by dmcgowan** [comment]
Closing this issue as it is a daemon configuration issue with systemd. Please follow https://docs.docker.com/engine/admin/systemd/ for setting up the engine with systemd.

**Comment by saavkaar** [comment]
Try adding --insecure-registry option to daemon in /etc/systemd/system/docker.service.d/docker.conf file.
Then sudo systemctl daemon-reload
And sudo service docker restart

It worked for me
