### ISSUE TITLE
Service scale error

### ISSUE THREAD

**Issue by frimdo** [docker/distribution#1933]
I was trying to create docker registry service. I used command 
```
docker service create --replicas=2 --mount type=volume,source=registry_volume,target=/var/lib/registry --name registry -p 5000:5000 registry:2
```
I cant push to it. the output of push command is: 
```
The push refers to a repository [IP_ADDRESS:5000/ubuntu]
0cad5e07ba33: Pushing 3.072 kB
48373480614b: Layer already exists
055757a19384: Pushing 9.728 kB
c6f2b330b60c: Pushing 15.87 kB
c8a75145fcc4: Retrying in 12 seconds
blob upload unknown
```
In [logs](https://thepb.in/p/r0hwRgxNm1WhK) of service, I found "invalid token" message. 

I'm running only one node
```
admin@test:~$ docker node ls
ID                           HOSTNAME          STATUS  AVAILABILITY  MANAGER STATUS
5p3p8ne3tx73411koav3ottce *  test.example.com  Ready   Active        Leader
```
And both services were successfully connected to one volume
```
admin@test:~$ docker inspect registry.2.bflv6ffg14grsar0qigxahfe0 | grep _data                     
                "Source": "/var/lib/docker/volumes/registry_volume/_data",
admin@test:~$ docker inspect registry.1.a59wwh4xjhzhz8t3hs290ojmx | grep _data
                "Source": "/var/lib/docker/volumes/registry_volume/_data",
```
I am running docker 1.12
```
admin@test:~$ docker --version
Docker version 1.12.1, build 23cf638
```

#### edit:
Scaling docker service back to 1 solves the broblem, so there is definitely no problem with "invalid token". It has to be something else...

**Comment by RichardScothern** [comment]
The link to the logs you posted does not resolve to anything.

What do the registry logs show?

**Comment by frimdo** [comment]
Thank you for helping me solve this problem.
So I deleted old containers and created new with debug level logging
```
service create --replicas=2 --mount type=volume,source=registry_volume,target=/var/lib/registry --name registry -p 5000:5000 --network ingress -e REGISTRY_LOG_LEVEL=debug registry:2
```
Now I can post whole [log files](https://gist.github.com/frimdo/f919a6ee43fe4071386ebec3fa373749). I have no idea what am I looking for... I haven't found anything suspicious. The problem persists though...

**Comment by stevvooe** [comment]
@frimdo Looks like you need to have the two instances share a secret. We can see this because of "error resolving upload: Invalid token" in the logs. The [docs are here](https://github.com/docker/distribution/blob/master/docs/configuration.md#http).

**Comment by frimdo** [comment]
That was it. I feel pretty dumb. On one hand, the warning about same key is bold, on the other hand, I missunderstood the "invalid token" log message for some token authentication error. Maybe the message should say "invalid http secret" or something more exact... 
Any way, thank you very much for your assistance.

**Comment by stevvooe** [comment]
> That was it. I feel pretty dumb.

We all have our days. Don't feel dumb!

I agree that the "invalid token" log message is a little confusing. I've submitted #1945 to address this.
