### ISSUE TITLE
Tag latest not found in repository docker.io/library/hello-world

### ISSUE THREAD

**Issue by martin-wiseweb** [docker/distribution#1947]
Upon installation, `docker run hello-world` always shows me `x509: certificate signed by unknown authority.`.

So I fix this by doing the following:

```
ln -s /etc/pki/tls/certs/ca-bundle.crt /etc/docker/certs.d/docker.io
ln -s /etc/pki/tls/certs/ca-bundle.trust.crt /etc/docker/certs.d/docker.io
```

Running docker `run hello-world` or `docker pull hello-world` produce the following errors:

```
# docker run hello-world

Unable to find image 'hello-world:latest' locally
Trying to pull repository docker.io/library/hello-world ... 
Pulling repository docker.io/library/hello-world
Tag latest not found in repository docker.io/library/hello-world
docker: Tag latest not found in repository docker.io/library/hello-world.
See '/usr/bin/docker-current run --help'.
```

**Comment by dmcgowan** [comment]
If you get such an error after installation it is likely an indicator that your system certificates are not up to date. First ensure you system certificates are correct.

As for `/etc/docker/certs.d`, that directory holds certificates for private registries and each private registry will have a folder which can hold a `.crt` for roots. By default when no directory is there it will use the system certificates. Since `docker.io` is signed by a common authority your system certificates should be sufficient and you should not add a sub-directory in `/etc/docker/certs.d`.

**Comment by martin-wiseweb** [comment]
Using the solution [described here](https://access.redhat.com/solutions/1549003), I reset my OS certificates. I removed the links from `/etc/docker/certs.d/`, too.

Now, I get `Error while pulling image: Get https://index.docker.io/v1/repositories/library/centos/images: x509: certificate signed by unknown authority`

**Comment by dmcgowan** [comment]
You might want to contact your os support since this is a problem with the os certificates. If you have cleared out `/etc/docker/certs.d/` and still getting an error with `index.docker.io` then I suspect something else is going on.

Can you `curl -v "https://index.docker.io/v1/_ping"` from your machine and see what you get in the logs. This is what I see on my fedora 23 machine.

```
$ curl -v "https://index.docker.io/v1/_ping"
*   Trying 52.73.159.23...
* Connected to index.docker.io (52.73.159.23) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* ALPN/NPN, server did not agree to a protocol
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.docker.io,OU=Domain Control Validated - RapidSSL(R),OU=See www.rapidssl.com/resources/cps (c)15,OU=GT98568428
* 	start date: Mar 19 17:34:32 2015 GMT
* 	expire date: Apr 21 01:51:52 2018 GMT
* 	common name: *.docker.io
* 	issuer: CN=RapidSSL SHA256 CA - G3,O=GeoTrust Inc.,C=US
```

**Comment by martin-wiseweb** [comment]
I get the following:

```
curl -v "https://index.docker.io/v1/_ping"
* About to connect() to index.docker.io port 443 (#0)
*   Trying 52.73.159.23...
* Connected to index.docker.io (52.73.159.23) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*.docker.io,OU=Domain Control Validated - RapidSSL(R),OU=See www.rapidssl.com/resources/cps (c)15,OU=GT98568428
*       start date: Mar 19 17:34:32 2015 GMT
*       expire date: Apr 21 01:51:52 2018 GMT
*       common name: *.docker.io
*       issuer: CN=RapidSSL SHA256 CA - G3,O=GeoTrust Inc.,C=US
> GET /v1/_ping HTTP/1.1
> User-Agent: curl/7.29.0
> Host: index.docker.io
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.6.2
< Date: Tue, 06 Sep 2016 18:09:14 GMT
< Content-Type: application/octet-stream
< Content-Length: 4
< X-Docker-Registry-Version: 0.6.3
< X-Docker-Registry-Standalone: False
< Content-Type: application/json
< Strict-Transport-Security: max-age=31536000
<
* Connection #0 to host index.docker.io left intact
```

**Comment by dmcgowan** [comment]
Can you send the output of `docker version` and `docker info`

**Comment by martin-wiseweb** [comment]
`docker version`:

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64
```


`docker info`

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-41943262-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 578.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 4.306 GB
 Metadata Space Used: 1.061 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.28.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 1
Total Memory: 1.907 GiB
(Removed Name)
ID: ML3Q:OW7R:SWJG:45JJ:V24R:IKXM:BHE3:PIAG:VMFN:WAGJ:A2SX:UIYE
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 18
 System Time: 2016-09-09T00:59:42.119653865-04:00
 EventsListeners: 0
 Init SHA1: 8a3129d2a388166b88b65d72b6047ce9d4e86eef
 Init Path: 
 Docker Root Dir: /var/lib/docker
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)
```

**Comment by stevvooe** [comment]
I'm judging from inactivity, that this issue was resolved and I'm closing it accordingly. Let me know if you still have a question.

**Comment by sibasankarp** [comment]
Dear Community,

I am getting error when trying to pull docker images through kolla-ansible pull. Some images pulled from docker hub. I am stuck now please help to resolve the issue.
**Please find below the error while kolla-ansible pull.**

failed: [localhost] (item={'value': {u'haproxy': {u'placement_api_external': {u'mode': u'http', u'enabled': True, u'external': True, u'listen_port': u'8780', u'port': u'8780'}, u'placement_api': {u'mode': u'http', u'enabled': True, u'external': False, u'listen_port': u'8780', u'port': u'8780'}}, u'group': u'placement-api', u'dimensions': {}, u'volumes': [u'/etc/kolla//placement-api/:/var/lib/kolla/config_files/:ro', u'/etc/localtime:/etc/localtime:ro', u'kolla_logs:/var/log/kolla/', u''], u'container_name': u'placement_api', u'image': u'kolla/centos-source-placement-api:rocky', u'enabled': True}, 'key': u'placement-api'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "pull_image",
            "api_version": "auto",
            "auth_email": null,
            "auth_password": null,
            "auth_registry": null,
            "auth_username": null,
            "cap_add": [],
            "command": null,
            "detach": true,
            "dimensions": {},
            "environment": {
                "KOLLA_CONFIG_STRATEGY": "COPY_ALWAYS"
            },
            "graceful_timeout": 10,
            "image": "kolla/centos-source-placement-api:rocky",
            "labels": {},
            "name": null,
            "privileged": false,
            "remove_on_exit": true,
            "restart_policy": "unless-stopped",
            "restart_retries": 10,
            "security_opt": [],
            "state": "running",
            "tls_cacert": null,
            "tls_cert": null,
            "tls_key": null,
            "tls_verify": false,
            "tty": false,
            "volumes": null,
            "volumes_from": null
        }
    },
    "item": {
        "key": "placement-api",
        "value": {
            "container_name": "placement_api",
            "dimensions": {},
            "enabled": true,
            "group": "placement-api",
            "haproxy": {
                "placement_api": {
                    "enabled": true,
                    "external": false,
                    "listen_port": "8780",
                    "mode": "http",
                    "port": "8780"
                },
                "placement_api_external": {
                    "enabled": true,
                    "external": true,
                    "listen_port": "8780",
                    "mode": "http",
                    "port": "8780"
                }
            },
            "image": "kolla/centos-source-placement-api:rocky",
            "volumes": [
                "/etc/kolla//placement-api/:/var/lib/kolla/config_files/:ro",
                "/etc/localtime:/etc/localtime:ro",
                "kolla_logs:/var/log/kolla/",
                ""
            ]
        }
    },
    **"msg": "Unknown error message: Tag rocky not found in repository docker.io/kolla/centos-source-placement-api"**
}
