### ISSUE TITLE
[Proposal] Do tagService.Untag in DeleteImageManifest if called with a tag

### ISSUE THREAD

**Issue by sergeyfd** [docker/distribution#1954]
Would it make sense to do just untagging if DeleteImageManifest is called with a tag instead of a digest? Currently there's no way to delete just a tag, without deleting an image, this change would allow such operation.

**Comment by greyarch** [comment]
I would expect exactly such a behaviour. It will also be in line with the docker api.

**Comment by sergeyfd** [comment]
Moved to #2170 #2169
