### ISSUE TITLE
Non-logfmt request logs in the registry:2 container output

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/distribution#1965]
When I run `registry:2` container with no customized logging options I see log lines like:

    13.66.220.35 - - [19/Sep/2016:07:29:23 +0000] "POST /v2/hello-world/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.12.0 go/go1.6.3 git-commit/8eab29e kernel/4.4.0-31-generic os/linux  arch/amd64 UpstreamClient(Docker-Client/1.12.1 \\(linux\\))"

which, I believe are not coming from `registry` application as they're not in `logfmt` format.

They look more like some frontend server logs. Any ideas where are these coming from?

**Comment by RichardScothern** [comment]
They are apache style request logging and can be disabled as of
https://github.com/docker/distribution/pull/1959

**Comment by ahmetalpbalkan** [comment]
@RichardScothern ah perfect, thanks!
