### ISSUE TITLE
Self hosted S3 (Minio) retrying in X seconds. 

### ISSUE THREAD

**Issue by bweston92** [docker/distribution#1967]
I have an S3 backend for registry:2 however I'm getting some logs on push but cannot see what the error is as it keeps saying on the push it is retrying in X seconds.

https://gist.github.com/bweston92/03361ac1d7b79eb9fa9b3db5ed185356

Issue opened on Minio too at minio/minio#2743

**Comment by RichardScothern** [comment]
@bweston92 #2743 has been closed.  Can this one be closed too?
