### ISSUE TITLE
S3 - NoCredentialProviders

### ISSUE THREAD

**Issue by blakewhite** [docker/distribution#1982]
My registry is not successfully contacting AWS to log into S3, much less actually store images.

```
[Unit]
Description=docker-registry
After=docker.service
Requires=docker.service

[Service]
Restart=always
ExecStartPre=/usr/bin/docker pull registry:2
ExecStart=/usr/bin/docker run --restart=always -p 127.0.0.1:5000:5000 -p 127.0.0.1:5001:5001 --name registry \
-e "REGISTRY_STORAGE=s3" \
-e "REGISTRY_HTTP_DEBUG_ADDR=0.0.0.0:5001" \
-e "REGISTRY_STORAGE_S3_ACCESS_KEY=******" \
-e "REGISTRY_STORAGE_S3_SECRET_KEY=******" \
-e "REGISTRY_STORAGE_S3_REGION=us-west-1" \
-e "REGISTRY_STORAGE_S3_BUCKET=*****-registry" \
-e "REGISTRY_STORAGE_S3_ROOTDIRECTORY=/" \
-e "REGISTRY_STORAGE_S3_ENCYPT=true" \
-e "REGISTRY_HTTP_SECRET=*****" \
registry:2
ExecStop=/usr/bin/docker stop registry
ExecStopPost=/usr/bin/docker rm registry
```

Checking the registry:
```
{"errors":[{"code":"UNAVAILABLE","message":"service unavailable","detail":"health check failed: please see /debug/health"}]}
```

Checking the debug endpoint:
```
curl 127.0.0.1:5001/debug/health
{"storagedriver_s3":"s3aws: NoCredentialProviders: no valid providers in chain. Deprecated. \n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}
```

**Comment by RichardScothern** [comment]
There is no `_` between `access`/`secret` and `key`  in the S3 environment variable name.

If you look at the logs in your container you should see a message about those environment variables being ignored.

**Comment by blakewhite** [comment]
That appears to have been it. The logs were not making it through to journalctl either. Thanks for the reminder to look in the container. Thanks much!

**Comment by ffedoroff** [comment]
I had that problem when s3 bucket was empty. After I put sample /docker/sample.file into the bucket it starts works for me. Maybe it is better to reopen the issue?

**Comment by stevvooe** [comment]
@ffedoroff It's a health check that prevents the registry from operating if it can't reach the backed or it is misconfigured. In the case of this issue, the user had misconfigured the registry backend with the wrong auth credentials. Your problem is completely unrelated, other than that the health check failed when it couldn't list the backend registry resources. If you think you have a problem, then please file a separate issue.

**Comment by jhmartin** [comment]
REGISTRY_STORAGE_S3_ENCYPT is also mispelled.
