### ISSUE TITLE
Pull image from private registry without auth

### ISSUE THREAD

**Issue by lonoi** [docker/distribution#1983]
Hello.
I have found(?) a bug.
If you would try to _docker pull_ image from your private registry without using _docker login_ first, you would fail. But if you would use full name and manifest, you would succeed even without authentication.
For example:
docker pull your.registry.host.com/repo/name - fail
And:
docker pull your.registry.host.com/repo/name@sha256:d5921e3f5...long_sha...012de67002d8 - succeed

**docker version**
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

**docker info**
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-93-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.86 GiB
Name: my.registry.host.com
ID: 5WW7:ZI7J:65IM:K5JV:ZMBK:EETY:UMC4:6BDC:4OQM:5U4H:B3NJ:TRBC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**docker exec 0decb54d6835 registry --version**
registry github.com/docker/distribution v2.5.0

**Comment by RichardScothern** [comment]
*Please follow these instructions to help us diagnose your issue*

 3. copy the command line you used to launch your Registry
 4. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 5. reproduce your problem and get your docker daemon logs showing the error
 6. if relevant, copy your registry logs that show the error
 7. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 8. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry

**Comment by lonoi** [comment]
I restarted docker and problem is gone.
