### ISSUE TITLE
Option to return 401 instead of 404 when not logged in

### ISSUE THREAD

**Issue by bmerry** [docker/distribution#1984]
This was previous requested as docker/docker#17721 by someone else, and closed due to being on the wrong github project.

A private registry (at least 2.3 - apologies if this is addressed in 2.4) with REGISTRY_AUTH=htpasswd will return a "not found" (404) when trying to do a docker pull without first doing a docker login.

I know that in some cases this is considered a security feature in that it prevents unauthenticated users from discovering which resources are protected. However, I (and am sure other users) would like to prioritise usability so that I can reduce the time I spend telling users "no, it's not broken, that error actually means you have to do docker login". Is it possible to make this at least an opt-in?

**Comment by dmcgowan** [comment]
*Please follow these instructions to help us diagnose your issue*

 1. copy the command line you used to launch your Registry
 2. restart your docker daemon in debug mode (add `-D` to the daemon launch arguments)
 3. reproduce your problem and get your docker daemon logs showing the error
 4. if relevant, copy your registry logs that show the error
 5. provide any relevant detail about your specific Registry configuration (e.g., storage backend used)
 6. indicate if you are using an enterprise proxy, Nginx, or anything else between you and your Registry


@bmerry I tried running with `REGISTRY_AUTH=htpasswd` on registry 2.3, 2.4, and 2.5 and am seeing them return a 401. Please provide the information above to help figure out why you are seeing this behavior. The 401 vs 404 is more a debate between 403 and 404, meaning a user is authenticated but not authorized. In that case not authorized to see repository we treat as not existing, this is good practice and will not be configurable. 

These are the commands I used to try and reproduce
```
$ htpasswd -cB test.htpasswd someuser
$ docker run -p 5000:5000 -v `pwd`:/registry -e REGISTRY_AUTH=htpasswd -e REGISTRY_AUTH_HTPASSWD_PATH=/registry/test.htpasswd -e REGISTRY_AUTH_HTPASSWD_REALM=registry registry:2.3
$ docker push localhost:5000/something 
....
no basic auth credentials
$ docker run -p 5000:5000 -v `pwd`:/registry -e REGISTRY_AUTH=htpasswd -e REGISTRY_AUTH_HTPASSWD_PATH=/registry/test.htpasswd -e REGISTRY_AUTH_HTPASSWD_REALM=registry registry:2.4
$ docker push localhost:5000/something 
....
no basic auth credentials
$ docker run -p 5000:5000 -v `pwd`:/registry -e REGISTRY_AUTH=htpasswd -e REGISTRY_AUTH_HTPASSWD_PATH=/registry/test.htpasswd -e REGISTRY_AUTH_HTPASSWD_REALM=registry registry:2.5
$ docker push localhost:5000/something 
....
no basic auth credentials
```

**Comment by bmerry** [comment]
I had a closer look: it seems the problem isn't with the registry, which returns 401, but with Docker Engine, which then tries to fall back to /v1 and receives the 404 from there. This bug is already filed as docker/docker#15759 so I'm closing this one.
