### ISSUE TITLE
add testcases for bad characters and path traversal attacks

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#199]
Add tests for the following against the the registry API:

1. Test the full ascii range against various repository names.
2. Cover common path traversal attacks.

This issue supersedes https://github.com/docker/docker-registry/issues/728 and https://github.com/docker/docker-registry/issues/731. Please see them for added detail.

**Comment by endophage** [comment]
Additional test cases added and confirmed that Go's http package normalizes paths with attempted traversal attacks.
