### ISSUE TITLE
Manifest version 2, schema 2 does not include created time

### ISSUE THREAD

**Issue by ebd2** [docker/distribution#1995]
WORKAROUND: This information is currently available via manifest version 2, schema 1.

Created time is a useful attribute to have for automatically cleaning up old versions of docker repositories from a registry.

Our tagging convention distinguishes between images that we're making available "permanently", and those that represent an interim state of development. We'd like to be able to automatically delete the temporary images after x days.

At present, we can get this information from version 2, schema 1. It would be nice if this information was included in v2s2 as it was in the original proposal: https://github.com/docker/docker/issues/8093. I didn't see any discussion of dropping `created` from the history information in the issue.

Alternately, a roadmap for v2s1 support would be nice so we know what the plan is for supporting v2s1 over time.

https://docs.docker.com/registry/spec/manifest-v2-2/#/backward-compatibility addresses the current level of support, but doesn't expand on what the long-term plan is for v2s1 support.

**Comment by ebd2** [comment]
Docker version/info:
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 133
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.797 GiB
Name: eric-VirtualBox
ID: <redacted>
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: ebd2
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 http://<redacted>:5000
 127.0.0.0/8
```

**Comment by RichardScothern** [comment]
hi @ebd2 None of the schema 2 formats contain the date the repository was created in the registry.

Schema 2 v1 inlined the runtime config of the container within the manifest file, which has the date the container was created.

Schema 2 v2 stores the runtime configuration in a different blob which is referenced from the manifest file.  The same data is available it is just stored in a blob rather than the manifest.

e.g.

```
$ curl localhost:5000/v2/tianon/true/manifests/a -H 'Accept: application/vnd.docker.distribution.manifest.v2+json'
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1473,
      "digest": "sha256:2bb1d8d9c25b85da227d55dbf13ab1ebab4dc997c060084e5d82a0719b16b901"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 147,
         "digest": "sha256:10a0f3d12683ed0e08afe20c634f84af54bb46305e250bc7c2721dcb94e51f0e"
      }
   ]
}
```

**Comment by ebd2** [comment]
@RichardScothern:

Image creation time is close enough to the time the repo was created on the registry for our purposes.

We'll go with v2s1 for now to spare ourselves a round-trip, but I appreciate the explanation about the reference to the runtime config in v2s2.

**Comment by grexe** [comment]
any reason labels are hidden in a history/v1compatibility section instead of being included at top level as a Map? Also see [my forum post](https://forums.docker.com/t/retrieve-image-labels-from-manifest/37784) for more details.
