### ISSUE TITLE
NoCredentialProviders error when specifying region endpoint

### ISSUE THREAD

**Issue by lnr0626** [docker/distribution#1996]
I'm setting up a registry with s3 as the storage back end, and trying to use EC2 instance roles to provide credentials. It looks like the EC2RoleProvider and SharedCredentialsProvider were left out of the credential chain if the RegionEndpoint is specified. This causes the NoCredentialsProviders error when the driver tries to authenticate with S3. What is the reason for not including these two credential providers?

**Comment by RichardScothern** [comment]
The `regionendpoint` is for using S3 compatible services which do not use EC2 role providers.

**Comment by lnr0626** [comment]
Would you accept a PR that made it so that the chain contained those two providers regardless of if the region endpoint was specified? It will not break use cases where ec2 role providers aren't used (both the shared credentials provider and ec2 role provider fail gracefully if they can't get credentials)

**Comment by RichardScothern** [comment]
Can you give me an idea of your use case?  `regionendpoint` was added for using S3 compatible services.  Why is `region` not suitable for your purposes?

**Comment by lnr0626** [comment]
As new regions come online (france, london, montreal, ningxia, and ohio are all on the roadmap), this would allow us to use buckets in those regions (with ec2 roles) without having to update the registry to a new version. The new regions aren't currently in the whitelist, and so you would need to specify the `regionendpoint` to be able to use them.

**Comment by RichardScothern** [comment]
Understood.  In that case, I would accept a PR to enable these two providers in the chain for region endpoints.
