### ISSUE TITLE
Structured logs for HTTP 404 endpoints

### ISSUE THREAD

**Issue by ahmetb** [docker/distribution#2011]
Hello,

I realized if a client requests a non-existing endpoint (say, `/foo`) no record of this appears in any structured form (i.e. logfmt/json). If you leave the Apache access.log (CLF) logs on, an entry appears there, and that is all:

```
172.17.0.1 - - [19/Oct/2016:02:22:16 +0000] "GET /foo HTTP/1.1" 404 19 "" "curl/7.49.1"
```

I think there should be some structured log entry for those
- who want to unify all the logs coming out of `registry` in structured form (like below)
- and therefore disabling CLF entries

Ideally I'd love to see this log from a nonexisting endpoint:

`time="2016-10-19T02:24:06.460645555Z" level=info msg="response completed" environment=development go.version=go1.6.3 http.request.host="localhost:5000" http.request.id=060b3c1c-02df-4f3c-91a1-74d4bfef70a8 http.request.method=GET http.request.remoteaddr="172.17.0.1:43418" http.request.uri="/foo" http.request.useragent="curl/7.49.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.477627ms http.response.status=404 http.response.written=19 instance.id=082c15c4-ddf9-4b60-8689-95d4fe8852f5 service=registry version=v2.5.0-rc.1-180-g8234784
`

But when I look at `app.go` I see [this](https://github.com/docker/distribution/blob/8234784a1a66bfee4a6d72d0a3cbd453b7f903d7/registry/handlers/app.go#L600-L604):

``` go
        status, ok := ctx.Value("http.response.status").(int)
        if ok && status >= 200 && status <= 399 {
            ctxu.GetResponseLogger(ctx).Infof("response completed")
        }
```

this was added in https://github.com/docker/distribution/commit/54f7e5d54b0e8f547dd2bae804b36694cd0f1601 but I am not sure if this code path gets invoked on routes that are not handled at all, because later in that file there is a log message `response completed with error` that gets printed when there is an error from an endpoint...

Any opinions?

**Comment by RichardScothern** [comment]
The registry will never log non-existing endpoints because the multiplexer we use (`gorilla/mux`) will not have anything registered to call.   (The CLF line comes from gorilla).

It is possible to register a default handler for a non-existing endpoint, I'm not sure if we can get a context with all of the information you wish though.   I think logging some like 'non-existent endpoint' or similar would be more useful than the standard 'response completed' though.

**Comment by ahmetalpbalkan** [comment]
@rscothern I agree with "non-existent endpoint message". Are you open to having a context constructed from the request and have that logged, just like we add CLF to mux?

**Comment by RichardScothern** [comment]
I am open.

**Comment by stevvooe** [comment]
@ahmetalpbalkan All that needs to be done is to move the instrumentation up the handler stack. Should be very straightforward. With that change, we can probably removed the combined logs.

**Comment by stevvooe** [comment]
@ahmetb Is this still an issue? Do we need to make change here?

**Comment by ahmetb** [comment]
I suppose we can close. It's only an issue for 404s.
