### ISSUE TITLE
Is distribution events envelope will contain different repositories' events?

### ISSUE THREAD

**Issue by realityone** [docker/distribution#2022]
Hi there,

https://github.com/docker/distribution/blob/master/notifications/event.go#L31-L32

I found a comment in `event.go#L31-L32`.
Is this mean different repositories' events will be in single envelope?

Thanks for help.

**Comment by RichardScothern** [comment]
hi @realityone  The spec allows for events to be queued up and batched before being sent out (which is why the type is an array).  However, these events are not necessarily related: they could be from different repositories, so you cannot assume they are related.
