### ISSUE TITLE
Switching Dockerfiles to Go 1.7

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/distribution#2028]
Are there plans to switch the dockerfiles to Go 1.7?

I am planning to add some net/http.Client and net/http.Transport customizations to my storage driver. Go 1.7 offers many knobs that prior Go versions do not have. Therefore I'm trying to update my driver and send a pull request but since the project still builds with 1.6, that does not seem possible today.

**Comment by RichardScothern** [comment]
I've been using go 1.7 locally for a while, so have no objection to this change.  We are already up to date with the new linter rules, so I think the transition will be fine.

**Comment by ahmetalpbalkan** [comment]
Closed via #2030.
