### ISSUE TITLE
Invalid region provided: ap-south-1

### ISSUE THREAD

**Issue by nkanish2002** [docker/distribution#2058]
Hi, I am trying to setup a Docker registry in AWS region **ap-south-1 (Mumbai)** with S3 storage using the following command:-

```sh
docker run -d --name registry_gor -p 80:5000	\
	-e REGISTRY_STORAGE=s3	\
	-e REGISTRY_STORAGE_S3_REGION=myregistry \
	-e REGISTRY_STORAGE_S3_REGION=ap-south-1 \
	-e REGISTRY_STORAGE_S3_ACCESSKEY=<omitted> \
	-e REGISTRY_STORAGE_S3_SECRETKEY=<omitted> \
	-e REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=inmemory \
	registry:latest
```

I am getting the following error in the log which suggests that the region is invalid. 

```go
panic: Invalid region provided: ap-south-1

goroutine 1 [running]:
panic(0xd88060, 0xc8203c49e0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/distribution/registry/handlers.NewApp(0x7f85fd5c92c0, 0xc8203408d0, 0xc8200718c0, 0x7f85fd5c92c0)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:121 +0x619
github.com/docker/distribution/registry.NewRegistry(0x7f85fd5c9300, 0xc8203408d0, 0xc8200718c0, 0xc8200718c0, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:86 +0x2b0
github.com/docker/distribution/registry.glob.func1(0x14cc660, 0xc820332060, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:55 +0x2a9
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x14cc660, 0xc820332010, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x6d4
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x14cc800, 0x0, 0x0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x180
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x23
```

I have searched for a solution and I came across #1952 and #1953 which suggest that the changes will be available in version `2.6`. Since I could not find that particular version, I would like to know how to build the registry image which includes the region `ap-south-1`.

**Comment by RichardScothern** [comment]
`2.6.0-rc.0` is coming out today-ish.

Instructions to build the registry can be found in the `docs` directory.

**Comment by nkanish2002** [comment]
@RichardScotheryn Thank you. :+1:

**Comment by ankitforcode** [comment]
@RichardScothern are we still waiting for it.


Events:
  FirstSeen	LastSeen	Count	From							SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----							-------------			--------	------		-------
  22s		22s		1	{default-scheduler }									Normal		Scheduled	Successfully assigned registry-rlsru to ip-172-31-32-201.ap-south-1.compute.internal
  17s		17s		1	{kubelet ip-172-31-32-201.ap-south-1.compute.internal}	spec.containers{registry}	Warning		Failed		Failed to pull image "registry:2.6.0-rc.0": Tag 2.6.0-rc.0 not found in repository docker.io/library/registry
  17s		17s		1	{kubelet ip-172-31-32-201.ap-south-1.compute.internal}					Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "registry" with ErrImagePull: "Tag 2.6.0-rc.0 not found in repository docker.io/library/registry"

  17s	17s	1	{kubelet ip-172-31-32-201.ap-south-1.compute.internal}	spec.containers{registry}	Normal	BackOff		Back-off pulling image "registry:2.6.0-rc.0"
  17s	17s	1	{kubelet ip-172-31-32-201.ap-south-1.compute.internal}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "registry" with ImagePullBackOff: "Back-off pulling image \"registry:2.6.0-rc.0\""

  22s	2s	2	{kubelet ip-172-31-32-201.ap-south-1.compute.internal}	spec.containers{registry}	Normal	Pulling	pulling image "registry:2.6.0-rc.0"

**Comment by ankitforcode** [comment]
Also, the rc.1 does give the same error invalid region.

panic: Invalid region provided: ap-south-1

goroutine 1 [running]:
panic(0xb7b900, 0xc42041ef40)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/distribution/registry/handlers.NewApp(0x1063800, 0xc42039f0e0, 0xc420396300, 0x1063800)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:123 +0x3908
github.com/docker/distribution/registry.NewRegistry(0x7fd0b5718130, 0xc42039f0e0, 0xc420396300, 0xc420396300, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
github.com/docker/distribution/registry.glob..func1(0x108b140, 0xc42038e5c0, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108b140, 0xc42038e570, 0x1, 0x1, 0x108b140, 0xc42038e570)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108b2e0, 0xc4201b3f40, 0xc4200001a0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d

**Comment by ankitforcode** [comment]
> We should probably open this unless resolved.

**Comment by dmcgowan** [comment]
@ankitforcode I understand it is the same error message but we closed this issue because it was resolved. If you having an issue with a release candidate please open up a new issue and provide your registry configuration, exact version, and logs so we can prioritize this for the release. Release candidate issues should always be opened up as new issues and not commented on closed issues.  Thank you for testing the release candidates!
