### ISSUE TITLE
investigate datadog golang integration for metrics

### ISSUE THREAD

**Issue by avinson** [docker/distribution#207]
We are using Datadog for some of the Docker Hub metrics and monitoring (along with systems metrics and monitoring). It may be useful to incorporate their Golang integration for gathering statistics about Go memory usage or exposing other variables that are not accessible by parsing logfile output. Contact me for more info. 

![screenshot 2015-02-25 18 14 56](https://cloud.githubusercontent.com/assets/1617166/6385085/433a3634-bd1a-11e4-8729-a284ec6e3f53.png)

**Comment by stevvooe** [comment]
@avinson Base Go metrics (expvar), as well as others, are already exposed on a separate http server. They also expose notification statistics, which we'll need to monitor. We are also adding a health-check system.
