### ISSUE TITLE
Retrieving registry catalog with token authentication

### ISSUE THREAD

**Issue by sergeyfd** [docker/distribution#2074]
Hello,

Am I correct that currently there's no way to retrieve Registry catalog using distribution/registry/client code from a Registry that enforces Token authentication? For what I see NewTokenHandler supports only RepositoryScope.

**Comment by dmcgowan** [comment]
@sergeyfd use `NewTokenHandlerWithOptions` and you can pass in a `RegistryScope`

**Comment by sergeyfd** [comment]
Thanks, that's what I thought. But it seems that it was introduced just recently. 2.5.1 codebase doesn't have it.
