### ISSUE TITLE
Feature request : Ability to plug filter/middleware onto the registry to inspect images

### ISSUE THREAD

**Issue by jeromepin** [docker/distribution#2078]
I'm looking for the ability to plug/attach something onto the registry which should be able to examine/audit images right before push. There is several use cases : 

- checking for vulnerabilities before uploading images to the registry,
- checking if image content, image name, tag name match some rules (like naming policy defined by the company),
- checking if images follows best practices.
- something else ?

Unless there is something existing ?

**Comment by dmcgowan** [comment]
We currently don't have a method in the registry to do this synchronously on upload. We don't want to add complicated validation on upload of the manifest but are considering adding more policy management which could cover naming.

Our recommended solution for vulnerability checking is using hooks on upload which trigger a check of the registry content. We don't have a mechanism for making specific tags in a repository unavailable but you could define a process to re-tag after your checks.

**Comment by stevvooe** [comment]
@jeromepin There is already middleware that intercepts these calls. You'll have to compile your own registry but it works.
