### ISSUE TITLE
Spec doesn't cover the regex for the namespaces; only the repos.

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/distribution#2100]
Migrating the feedback from @mbentley at docker/docker.github.io#838 that `registry/spec/api.md` doesn't cover the regex for the namespaces; only the repos.

**Comment by stevvooe** [comment]
The registry spec does not define namespaces. Namespaces are purely a hub concept.

The canonical naming grammar used in Docker is [here](https://github.com/docker/distribution/blob/master/reference/reference.go#L4). The spec _does_ include a `<name>` regular expression, which should match the grammar in character set, but not necessarily structure.

I'm closing this. If you want something to change, please submit a PR.
