### ISSUE TITLE
Registry health check is too expensive

### ISSUE THREAD

**Issue by yixizhang** [docker/distribution#2114]
https://github.com/docker/distribution/blob/master/registry/handlers/app.go#L347-L350

Docker registry uses `app.driver.List` to do health check, this is too expensive for registries that have large amount of images. 

Can't we use `app.driver.Stat` instead?

**Comment by yixizhang** [comment]
@carlsverre

**Comment by stevvooe** [comment]
@yixizhang Please submit a PR.

**Comment by yixizhang** [comment]
https://github.com/docker/distribution/pull/2115
