### ISSUE TITLE
Has Amazon S3 private endpoint been supported?

### ISSUE THREAD

**Issue by duyanghao** [docker/distribution#2126]
i build the binary from master branch source code,and with the configuration file below:

> version: 0.1
> log:
>   level: debug
>   fields:
>     service: registry
> storage:
>     cache:
>         blobdescriptor: inmemory
>     s3:
>         accesskey: xxxx
>         secretkey: xxxx
>         region: test_region
>         regionendpoint: http://local_test_region_dns
>         bucket: test_bucket
>         encrypt: false
>         secure: false
>         v4auth: false
>         chunksize: 5242880
>         rootdirectory: /registry
> 
> http:
>     addr: 0.0.0.0:5000
>     headers:
>         X-Content-Type-Options: [nosniff]
> health:
>   storagedriver:
>     enabled: true
>     interval: 10s
>     threshold: 3

**attention:**
the `regionendpoint` is my private region address, there is a rgw running in the address.

i run registry with cmd `registry serve config.yml`,but when i send request `docker pull`,error occurs below:
```
stable: Pulling from duyanghao/docker_auth
55dc925c23d1: Retrying in 5 seconds 
a3ed95caeb02: Pulling fs layer 
dca794285b62: Waiting 
d755a80ad6b2: Waiting 
Get http:///test_bucket/registry/docker/registry/v2/blobs/sha256/8d/8db29e90952f46e7e0ebe9b3304f75e571cf6714d57832ad875c06edd81f5379/data: http: no Host in request URL
```

the above error msg show two errors:
1.no host in the redirect url
2.no aws access key msg in redirect url

and the successful redirect url should be like this:
`
http://local_test_region_dns/test_bucket/registry/docker/registry/v2/blobs/sha256/8d/8db29e90952f46e7e0ebe9b3304f75e571cf6714d57832ad875c06edd81f5379/data?...
`

then i build the binary from v2.5.1 source code,different error occurs,but with the same result:
**Amazon S3 is unusable!!!**

**i want to know whether the Amazon S3 driver function has been verified yet?**

**Comment by duyanghao** [comment]
to solve the above problem, i read the source code of master branch,changing `setv2Handlers` function(registry/storage/driver/s3-aws/s3_v2_signer.go) and `updatePath` function(vendor/github.com/aws/aws-sdk-go/private/protocol/rest/build.go) as below:
```
func updatePath(url *url.URL, urlPath string) {
        /*
        scheme, query := url.Scheme, url.RawQuery

        hasSlash := strings.HasSuffix(urlPath, "/")

        // clean up path
        urlPath = path.Clean(urlPath)
        if hasSlash && !strings.HasSuffix(urlPath, "/") {
                urlPath += "/"
        }

        // get formatted URL minus scheme so we can build this into Opaque
        url.Scheme, url.Path, url.RawQuery = "", "", ""
        s := url.String()
        url.Scheme = scheme
        url.RawQuery = query

        // build opaque URI
        url.Opaque = s + urlPath
        */
}
```

```
// setv2Handlers will setup v2 signature signing on the S3 driver
func setv2Handlers(svc *s3.S3) {
        svc.Handlers.Build.PushBack(func(r *request.Request) {
                /*
                parsedURL, err := url.Parse(r.HTTPRequest.URL.String())
                if err != nil {
                        log.Fatalf("Failed to parse URL: %v", err)
                }
                r.HTTPRequest.URL.Opaque = parsedURL.Path
                */
        })

        svc.Handlers.Sign.Clear()
        svc.Handlers.Sign.PushBack(Sign)
        svc.Handlers.Sign.PushBackNamed(corehandlers.BuildContentLengthHandler)
}
```
but the error occur below:
```
stable: Pulling from duyanghao/docker_auth
55dc925c23d1: Downloading 
a3ed95caeb02: Downloading 
dca794285b62: Downloading 
d755a80ad6b2: Waiting 
Error parsing HTTP response: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AccessDenied</Code></Error>"
```
with the Wireshark i find that redirect url is:
`http://local_test_region_dns/test_bucket/registry/docker/registry/v2/blobs/sha256/8d/8db29e90952f46e7e0ebe9b3304f75e571cf6714d57832ad875c06edd81f5379`

**now the redirect url contains the host but the problem is that there is no aws access key msg**

and different errors occur as v2.5.1.

**Comment by stevvooe** [comment]
@duyanghao Please choose a less flippant title.

**Comment by duyanghao** [comment]
i am afraid not,i am telling the truth!!!

**Comment by stevvooe** [comment]
@duyanghao The S3 driver has been in production for nearly two years in a number of deployments. It works fine. Saying that it is "unusable" doesn't describe the problem that you are experiencing and only serves to insult those that might help you.

I would look into why you are getting an `AccessDenied` error message from s3. Have you followed the guidance in the [documentation](https://docs.docker.com/registry/storage-drivers/s3/)?

**Comment by Windfarer** [comment]
@duyanghao Do not use master branch in production environment, use stable release instead.

**Comment by duyanghao** [comment]
sorry for my poor English.
I admit that my title is not very accurate  : )
now,i want to repeat my question:
**Has Amazon S3 private endpoint been supported?**
i mean,there is a rgw(ceph backend) running in my company,i want to use that for Amazon S3 endpoint,is that supported?

**Comment by stevvooe** [comment]
@duyanghao A private registry with S3 is both supported and works fine. There are many deployments.

It sounds you are attempting to get this to work with the rados gateway. For that, I believe you need to use the swift driver.

**Comment by stevvooe** [comment]
@duyanghao Closing this as it seems you need to use the swift driver. If you need further assistance, let us know.

**Comment by duyanghao** [comment]
@stevvooe as you said, i want to get this to work with the private rados gateway(private ceph backend),and i want to use [Amazon s3 driver](https://docs.docker.com/registry/storage-drivers/s3/) ,is that supported?

In addition,i have tested using [Amazon s3 driver](https://docs.docker.com/registry/storage-drivers/s3/) interacts with private rgw(private ceph backend),but failed,and that why i create this issue.

**Comment by stevvooe** [comment]
@duyanghao As I said, if you are using the rados gateway, you need to use the [swift driver](https://docs.docker.com/registry/storage-drivers/swift/). Using the s3 driver with rados gateway is not supported.

**Comment by duyanghao** [comment]
@stevvooe Could you please explain why you drop the feature that using s3 driver interacts with rgw?

**Comment by stevvooe** [comment]
@duyanghao We have not dropped support for s3 driver and rgw. The swift driver _is_ the driver for use with rados gw. The difference between swift and s3 code is a negligible. Swift drivers are deployed in practice in the exact use case you are talking about. s3 drivers _ONLY WORK WITH AWS S3_.

What have you actually tried at this point?

**Comment by duyanghao** [comment]
@stevvooe Looking at ceph rados gw [document](http://docs.ceph.com/docs/master/radosgw/),that says:
>>
Ceph Object Gateway is an object storage interface built on top of librados to provide applications with a RESTful gateway to Ceph Storage Clusters. Ceph Object Storage supports two interfaces:
* S3-compatible: Provides object storage functionality with an interface that is compatible with a large subset of the Amazon S3 RESTful API.
* Swift-compatible: Provides object storage functionality with an interface that is compatible with a large 
subset of the OpenStack Swift API.

so i just think s3 driver will support the rados gw?is there anything wrong?

**Comment by stevvooe** [comment]
> could you explain the statement "The RADOS storage driver has been removed"?

We remove support for _directly_ storing data in the rados object store.

You've missed the second part. Please read it again:

> The registry can still be used with Ceph as the storage backend using the swift driver in conjunction with the Swift API gateway

______What have you actually tried?______

**Comment by duyanghao** [comment]
why has the RADOS storage driver been removed?@stevvooe

**Comment by stevvooe** [comment]
Please answer my question:

__What have you actually tried?__

**Comment by duyanghao** [comment]
@stevvooe before registry 2.4.0,i use s3 driver interacts with rgw after changing some code of[AdRoll/goamz](https://github.com/AdRoll/goamz)(refer to [here](https://github.com/duyanghao/distribution/commit/2702fb2844471e58b942a289b3b7bc6a73ac74ce))

**Comment by stevvooe** [comment]
@duyanghao Ok, so this was working before but now it is not, with the s3 driver. If you have a patch that will make this work, please send a PR.

> As you said,until now the swift driver is the only way to interact with rados gw and RADOS storage driver bas been removed,so i want to figure out why the RADOS storage driver has been removed.

You never used the RADOS driver, according to your response. We used to have a direct driver for this but it was a nightmare and we removed it. It was unrelated to the s3 driver.

> Now that the swift driver is the only way to interact with rgw,i want to know the performance and stability of swift driver based on ncw/swift.

It is used by others and considered stable, but you really need to do your own testing.

**Comment by duyanghao** [comment]
@stevvooe i have tried to make some changes to use s3 driver based on [aws/aws-sdk-go](https://github.com/aws/aws-sdk-go) interact with rados gw,but failed as you have seen)(that why i create this issue),so it may be difficult to make this work.

now i will try to use swift driver,and carry on a pressure test to see how efficient and stable it is.

again,thank you for your patience to answer.

**Comment by stevvooe** [comment]
@duyanghao Alright, let me know how that goes.

**Comment by duyanghao** [comment]
refer to [here](https://github.com/docker/distribution/blob/v2.6.0/docs/configuration.md#redirect):
>>redirect
>>The redirect subsection provides configuration for managing redirects from content backends. For backends that support it, redirecting is enabled by default. In certain deployment scenarios, you may decide to route all data through the Registry, rather than redirecting to the backend. This may be more efficient when using a backend that is not co-located or when a registry instance is aggressively caching.


@stevvooe from my test,i found that swift driver doesn't support redirect feature as s3 driver does(it will not response with 307 redirect when docker pulls).
