### ISSUE TITLE
Old fsLayers are never purged

### ISSUE THREAD

**Issue by notuscloud** [docker/distribution#2127]
Hi guys, 

I'm facing a troubling issue. I'm facing an ever growing private registry. I enabled deletion but the purge only reclaimed like 0.5% of the storage. 

I investigated a little and I found a repository with just one tag "latest". It's built and pushed to the registry on a daily basis. The repository's size reach 150GB for a 300MB simple spring project and the oldest fsLayer is from march 2016...

Isn't purge supposed to clean that? Maybe I'm missing something here like a configuration or something.

Regards,
Thomas

**Comment by sergeyfd** [comment]
Purge is not supposed to take care of that. Have you tried to run Garbage Collection there?

**Comment by notuscloud** [comment]
Yep, but it does nothing. 

It's like those "dangling" images you got locally when you build the same time tag multiples times. At each build, a new set of layers is created and the previous ones remain.

I've read the documentation, I understand that the layers are shared and only orphan layers are deleted by the garbage collector. 

Does this means that, something, somewhere is targeting those rusty layers, or maybe I'm wrong...

**Comment by stevvooe** [comment]
@notuscloud Images can be referenced both by tag and digest. You need to mark those images as deleted if you want them to be collected via gc.

I'm not sure on the status, but @sergeyfd and I had talked about adding an API to expose lists of manifest digests to allow clean up.

**Comment by mortensteenrasmussen** [comment]
@notuscloud could you please try the procedure described in #2190 [here](https://github.com/docker/distribution/issues/2190#issuecomment-279323179) and [here](https://github.com/docker/distribution/issues/2190#issuecomment-279343010)?

I did this as a temporary thing until we have proper API support to handle it a bit better.

**Comment by notuscloud** [comment]
@mortensteenrasmussen

I tried, IT WORKED!!! I've freed around 500GB of disk space. 

Thx a lot!

**Comment by stevvooe** [comment]
@notuscloud Glad to hear you got it working.

Closing.

**Comment by mortensteenrasmussen** [comment]
Hi,

I have now created a bit more sustainable solution for this. Please use/star/ignore as you see fit.

https://github.com/mortensteenrasmussen/docker-registry-manifest-cleanup
https://hub.docker.com/r/mortensrasmussen/docker-registry-manifest-cleanup
