### ISSUE TITLE
image pull returns 404 on manifest request if there is storage error

### ISSUE THREAD

**Issue by yuwaMSFT2** [docker/distribution#2135]
When get manifest, the handler will try to retrieve it from storage driver. When storage driver is cloud storage, it can fail due to various reasons even if the manifest exists (like 500, 503, etc. from storage server). However, the manifest handler in images.go doesn't distinguish the TagUnknown/BlobUnknown error from other service transient error. As a result, it always returns 404 to user, which is misleading when user knows the manifest exists.

All other handlers seem to distinguish the unknown/notfound error from other errors, so they return 404/500 respectively.

**Comment by yuwaMSFT2** [comment]
We used the Azure driver but it should be the same for all other drivers...

**Comment by stevvooe** [comment]
@yuwaMSFT2 Would you mind sending a PR with a fix?

**Comment by yuwaMSFT2** [comment]
Sure will prepare a PR.

**Comment by dmcgowan** [comment]
Closed by #2138
