### ISSUE TITLE
Redundent '/v2/' GET made when pushing an image to v2 registry 

### ISSUE THREAD

**Issue by bmangold** [docker/distribution#214]
![image](https://cloud.githubusercontent.com/assets/3420507/6405741/341d2bee-bddc-11e4-9d08-f9d7471808b5.png)

Expected : only one call to /v2/ to determine if there is v2 support
Actual : two calls made to /v2/

See image....  using Charles Proxy ... pushing an ubuntu:latest image to a non-SSL v2 instance 

Docker 1.5 daemon (/etc/default/docker):
export http_proxy="http://localhost:8888/"
DOCKER_OPTS="$DOCKER_OPTS --insecure-registry=host:port"

Docker 1.5 client:
docker push host:port/path_component1/path_component2

**Comment by stevvooe** [comment]
@bmangold This behavior is part of docker core. Please file this at https://github.com/docker/docker/issues.

**Comment by bmangold** [comment]
Yup, makes sense. Will close and refile.
