### ISSUE TITLE
x509: certificate signed by unknown authority - Docker Windows v1.12.6

### ISSUE THREAD

**Issue by AltairCA** [docker/distribution#2141]
I am using Docker v 1.12.6 stable on Windows

I have created a node using `docker-machine create `--driver none --url=tcp://127.0.0.1:2376 mymachine`

I have created self sign certificates and installed them on the windows certificate store, I can navigate to the `https://127.0.0.1:2376/v1.15/version` from Google Chrome without any certificate error and it will give me result like this

`{"Version":"1.12.1","ApiVersion":"1.24","GitCommit":"23cf638","GoVersion":"go1.6.2","Os":"linux","Arch":"amd64","KernelVersion":"4.4.0-47-generic","BuildTime":"Tue, 27 Sep 2016 12:25:38 +1300"}`

when I `docker-machine ls` it will give x509: certificate signed by unknown authority

![capture](https://cloud.githubusercontent.com/assets/13506816/21887506/301666e2-d8e6-11e6-9214-63f87694e7f4.PNG)

**Comment by stevvooe** [comment]
Please open an issue in the docker machine project.
