### ISSUE TITLE
feature request: hashicorp vault auth for revokable access to docker registry images/groups

### ISSUE THREAD

**Issue by blacktop** [docker/distribution#2144]
I see you have token as an option, but I think integration with the amazing tool vault is a great idea to easily allow for revoking access or controlling read/write access to images or groups.

**Comment by blacktop** [comment]
I have also created a feature request with the vault team here - https://github.com/hashicorp/vault/issues/2275

**Comment by blacktop** [comment]
I explain the need for this as well in this issue - https://github.com/docker/distribution/issues/2145

**Comment by dmcgowan** [comment]
@blacktop the registry does not integrate directly with authorization backends, rather that is intended for the token authorization servers. You might suggest this feature over at https://github.com/SUSE/Portus, https://github.com/cesanta/docker_auth, or for the Docker Trusted Registry.
