### ISSUE TITLE
docker private registry storing sensitive creds in ~/.docker folder base64 encoded 

### ISSUE THREAD

**Issue by blacktop** [docker/distribution#2145]
I would like to note that people are trying to use LDAP/Kerb auth with private docker registries and that auth is stored by putting their creds in a `.docker` folder with their passwords base64 encoded in JSON.  

Another thing you could do in OSX any how would be to at least store that in the Keychain?

I know there is something similar for *unix as well, but am not sure what there is for Windows?

Thanks.

**Comment by dmcgowan** [comment]
Please see https://github.com/docker/docker-credential-helpers

If you are using Docker4Windows I would suggest reaching out to their support about this feature
