### ISSUE TITLE
unsupported: Unsupported manifest type: "application/vnd.docker.distribution.manifest.v2+json"

### ISSUE THREAD

**Issue by MullaCode** [docker/distribution#2146]
When pushing an image based on windows server core to an AWS Docker registry I get the following error: 
_

> unsupported: Unsupported manifest type: "application/vnd.docker.distribution.manifest.v2+json

_
The image is created on Windows Server 2016 and contains a very simple microservice built using the .NET framework 4.5
Here is the command I use and output I receive: 
![aws_dockerreg_error](https://cloud.githubusercontent.com/assets/4543065/21980383/11824dc0-dbdb-11e6-8e0a-a0182e1162c6.PNG)

**Comment by MullaCode** [comment]
Update:
Version of Docker on Windows Server : Docker version 1.13.0-rc7

Also I've ran the same commands locally on my laptop using windows 10 (Docker version on laptop: 1.13.0-rc6 ) The only difference is all layers get pushed but I still get the same unsupported manifest type error.

fcce8c55821b: Pushed
097c55a86c36: Pushed
d04fd9623061: Pushed
f83e0c591482: Pushed
cdcc56b93609: Pushed
03cc226bcb9b: Pushed
c28d44287ce5: Pushed
f358be10862c: Pushed
unsupported: Unsupported manifest type: "application/vnd.docker.distribution.manifest.v2+json"

**Comment by dmcgowan** [comment]
@MullaCode which version of the registry are running? This error indicates the registry is an older version and needs to be upgrade to at least registry 2.5 to get foreign layer support and support mentioned manifest type.

**Comment by MullaCode** [comment]
@dmcgowan I'm using Amazon EC2 Container Registry(ECR) - ECR does not make use of the standard Docker Registry software as it uses IAM for authentication and uses a custom storage backend. ECR implements the Docker Registry HTTP API V2 so as to be compatible with the official Docker registry software.

**Comment by dmcgowan** [comment]
@MullaCode you will need to reach out to Amazon support to check if they are supporting Windows images and if not what their timeline is. You can try a different registry provider until then to make sure you are able to push/pull windows images without problems.

**Comment by MullaCode** [comment]
Hi @dmcgowan
