### ISSUE TITLE
docker push failing and Retrying for even a 1 MB file

### ISSUE THREAD

**Issue by saravpkkl** [docker/distribution#2147]
I am getting EOF error while pushing the tagged image to the registry , Please help.. I have added most of the logs and configurations . If anything needed please respond.

**Registry Configuration ** 

cache: 
  image: redis:latest
  container_name: cache_server
    
registry:

  image: registry:2
  restart: always
  container_name: registry
   
  ports: 
    - localhost:5000:5000 
  links: 
    - cache 
  volumes:
    
    - $PWD/data:/var/lib/registry 
  environment:
  
    SETTINGS_FLAVOR: local 
    STORAGE_PATH: /var/lib/registry
    SEARCH_BACKEND: sqlalchemy     
    CACHE_REDIS_HOST: cache 
    CACHE_REDIS_PORT: 6379 
    CACHE_LRU_REDIS_HOST: cache 
    CACHE_LRU_REDIS_PORT: 6379 
    

**Tried with This  SIMPLE REGISTRY Configuration TOO**

docker run -d -p 5000:5000 --name registry registry:latest

**DOCKER INFO**

Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-554295-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.688 GB
 Data Space Total: 107.4 GB
 Data Space Available: 25.65 GB
 Metadata Space Used: 11.27 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.703 GiB
Name: rnd-jenkins.dev.domain.com
ID: 7DBM:T5TW:AO4X:RNLR:5RE2:FY27:HDYQ:TZZ5:X5SX:HEMO:GXFO:KNKY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy:8080/
Registry: https://index.docker.io/v1/
Insecure Registries:
 10.50.X.X:5000
 127.0.0.0/8
[sarpat@rnd-jenkins bin]$ clear
[sarpat@rnd-jenkins bin]$ docker info
Containers: 8
 Running: 2
 Paused: 0
 Stopped: 6
Images: 91
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-554295-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.688 GB
 Data Space Total: 107.4 GB
 Data Space Available: 25.65 GB
 Metadata Space Used: 11.27 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.703 GiB
Name: rnd-jenkins.dev.domain.com
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://domain-nexus:8080/
Registry: https://index.docker.io/v1/
Insecure Registries:
 10.50.XX.XX:5000
 127.0.0.0/8

**MY DOCKER VERSION**

Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

**REGISTRY LOGS**

10.XX.XX.10 - - [16/Jan/2017:14:36:30 +0000] "POST /v2/smbox/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.12.6 go/go1.6.4 git-commit/78d1802 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))"
time="2017-01-16T14:37:00Z" level=error msg="unknown error reading request payload: http: unexpected EOF reading trailer" go.version=go1.6.3 http.request.host="10.XX.XX.15:5000" http.request.id=36689cc8-ad2f-4d0b-b771-359481050568 http.request.method=PATCH http.request.remoteaddr="10.XX.XX.10:65037" http.request.uri="/v2/smbox/blobs/uploads/1970028e-f7c6-4e3e-a621-0352b6a66ad8?_state=fXWvBsBFglBIzebcjlwnM2dQhhpOz1uOib4dZba6zhB7Ik5hbWUiOiJzbWJveCIsIlVVSUQiOiIxOTcwMDI4ZS1mN2M2LTRlM2UtYTYyMS0wMzUyYjZhNjZhZDgiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMDEtMTZUMTQ6MzY6MzAuNTAyNjY2Mjc5WiJ9" http.request.useragent="docker/1.12.6 go/go1.6.4 git-commit/78d1802 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=3b194519-fbe7-42c8-9fb3-a7964137ed62 vars.name=smbox vars.uuid=1970028e-f7c6-4e3e-a621-0352b6a66ad8 version=v2.5.1
time="2017-01-16T14:37:00Z" level=error msg="response completed with error" err.code=unknown err.detail="http: unexpected EOF reading trailer" err.message="unknown error" go.version=go1.6.3 http.request.host="10.XX.XX.15:5000" http.request.id=36689cc8-ad2f-4d0b-b771-359481050568 http.request.method=PATCH http.request.remoteaddr="10.XX.XX.10:65037" http.request.uri="/v2/smbox/blobs/uploads/1970028e-f7c6-4e3e-a621-0352b6a66ad8?_state=fXWvBsBFglBIzebcjlwnM2dQhhpOz1uOib4dZba6zhB7Ik5hbWUiOiJzbWJveCIsIlVVSUQiOiIxOTcwMDI4ZS1mN2M2LTRlM2UtYTYyMS0wMzUyYjZhNjZhZDgiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMDEtMTZUMTQ6MzY6MzAuNTAyNjY2Mjc5WiJ9" http.request.useragent="docker/1.12.6 go/go1.6.4 git-commit/78d1802 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=30.0108566s http.response.status=500 http.response.written=70 instance.id=3b194519-fbe7-42c8-9fb3-a7964137ed62 vars.name=smbox vars.uuid=1970028e-f7c6-4e3e-a621-0352b6a66ad8 version=v2.5.1
10.XX.XX.10 - - [16/Jan/2017:14:36:30 +0000] "PATCH /v2/smbox/blobs/uploads/1970028e-f7c6-4e3e-a621-0352b6a66ad8?_state=fXWvBsBFglBIzebcjlwnM2dQhhpOz1uOib4dZba6zhB7Ik5hbWUiOiJzbWJveCIsIlVVSUQiOiIxOTcwMDI4ZS1mN2M2LTRlM2UtYTYyMS0wMzUyYjZhNjZhZDgiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMDEtMTZUMTQ6MzY6MzAuNTAyNjY2Mjc5WiJ9 HTTP/1.1" 500 70 "" "docker/1.12.6 go/go1.6.4 git-commit/78d1802 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))"
time="2017-01-16T14:37:05Z" level=info msg="response completed" go.version=go1.6.3 http.request.host="10.XX.XX.15:5000" http.request.id=ad6ee242-58e9-4362-9494-c6248496e291 http.request.method=POST http.request.remoteaddr="10.XX.XX.10:65095" http.request.uri="/v2/smbox/blobs/uploads/" http.request.useragent="docker/1.12.6 go/go1.6.4 git-commit/78d1802 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" http.response.duration=7.014967ms http.response.status=202 http.response.written=0 instance.id=3b194519-fbe7-42c8-9fb3-a7964137ed62 version=v2.5.1
10.XX.XX.10 - - [16/Jan/2017:14:37:05 +0000] "POST /v2/smbox/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.12.6 go/go1.6.4 git-commit/78d1802 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))"
time="2017-01-16T14:37:35Z" level=error msg="unknown error reading request payload: http: unexpected EOF reading trailer" go.version=go1.6.3 http.request.host="10.XX.XX.15:5000" http.request.id=65cf4ed1-7402-4fb0-894a-52567ed6f7dc http.request.method=PATCH http.request.remoteaddr="10.XX.XX.10:65096" http.request.uri="/v2/smbox/blobs/uploads/89485032-2d36-4cee-92ba-d249f33f2c8d?_state=_79AgSRqX_59WdPY0LfX_AsYJth7inSfQs7QdoTkUd57Ik5hbWUiOiJzbWJveCIsIlVVSUQiOiI4OTQ4NTAzMi0yZDM2LTRjZWUtOTJiYS1kMjQ5ZjMzZjJjOGQiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMDEtMTZUMTQ6Mzc6MDUuNTM4NDY1NjY1WiJ9" http.request.useragent="docker/1.12.6 go/go1.6.4 git-commit/78d1802 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" instance.id=3b194519-fbe7-42c8-9fb3-a7964137ed62 vars.name=smbox vars.uuid=89485032-2d36-4cee-92ba-d249f33f2c8d version=v2.5.1
time="2017-01-16T14:37:35Z" level=error msg="response completed with error" err.code=unknown err.detail="http: unexpected EOF reading trailer" err.message="unknown error" go.version=go1.6.3 http.request.host="10.XX.XX.15:5000" http.request.id=65cf4ed1-7402-4fb0-894a-52567ed6f7dc http.request.method=PATCH http.request.remoteaddr="10.XX.XX.10:65096" http.request.uri="/v2/smbox/blobs/uploads/89485032-2d36-4cee-92ba-d249f33f2c8d?_state=_79AgSRqX_59WdPY0LfX_AsYJth7inSfQs7QdoTkUd57Ik5hbWUiOiJzbWJveCIsIlVVSUQiOiI4OTQ4NTAzMi0yZDM2LTRjZWUtOTJiYS1kMjQ5ZjMzZjJjOGQiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMDEtMTZUMTQ6Mzc6MDUuNTM4NDY1NjY1WiJ9" http.request.useragent="docker/1.12.6 go/go1.6.4 git-commit/78d1802 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=30.008075186s http.response.status=500 http.response.written=70 instance.id=3b194519-fbe7-42c8-9fb3-a7964137ed62 vars.name=smbox vars.uuid=89485032-2d36-4cee-92ba-d249f33f2c8d version=v2.5.1
10.XX.XX.10 - - [16/Jan/2017:14:37:05 +0000] "PATCH /v2/smbox/blobs/uploads/89485032-2d36-4cee-92ba-d249f33f2c8d?_state=_79AgSRqX_59WdPY0LfX_AsYJth7inSfQs7QdoTkUd57Ik5hbWUiOiJzbWJveCIsIlVVSUQiOiI4OTQ4NTAzMi0yZDM2LTRjZWUtOTJiYS1kMjQ5ZjMzZjJjOGQiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTctMDEtMTZUMTQ6Mzc6MDUuNTM4NDY1NjY1WiJ9 HTTP/1.1" 500 70 "" "docker/1.12.6 go/go1.6.4 git-commit/78d1802 kernel/3.10.0-514.2.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.6 \\(linux\\))"

**WHILE PUSHING JUST 1.11 MB**

c85de82f7789: Pushing [=========================>                         ] 558.1 kB/1.11 MB

[sarr@rnd-jenkins bin]$ docker push 10.XX.XX.73.15:5000/smbox:tag1
The push refers to a repository [10.XX.XX.73.15:5000/smbox]
c85de82f7789: Retrying in 5 seconds

**Comment by saravpkkl** [comment]
I found the reason for this , This is due to the HTTP_PROXY  configured in the Linux Host. Just added NO proxy  for the  Registry URL .. It is just worked. 

If anyone facing this issue please do the following:

1. Open the file /etc/systemd/system/docker.service.d/http-proxy.conf in VI editor

2.  Change or add the lines like below based on your proxy and IP address
Environment="HTTP_PROXY=http://proxy.example.com:80/" "NO_PROXY=localhost,127.0.0.1,docker-registry.somecorporation.com"

3. Flush the changes
    $   sudo systemctl daemon-reload

4.  Verify your changes are done.

  $  systemctl show --property=Environment docker

5.  Restart Docker

$  sudo systemctl restart docker

6 . Restart your Containers/ Registry ... There you go.. Your  registry started working... :-)

**Comment by zen-k** [comment]
Thank you! I had the same problem with Gitlab CI Runner. I just add before push:
```export NO_PROXY=localhost,127.0.0.1,my.registry.com```

**Comment by simonmiller99** [comment]
thank you - you made me realise that an incorrect FQDN of the nexus server in the proxy exceptions was the issue

**Comment by reski-rukmantiyo** [comment]
> I found the reason for this , This is due to the HTTP_PROXY configured in the Linux Host. Just added NO proxy for the Registry URL .. It is just worked.
> 
> If anyone facing this issue please do the following:
> 
> 1. Open the file /etc/systemd/system/docker.service.d/http-proxy.conf in VI editor
> 2. Change or add the lines like below based on your proxy and IP address
>    Environment="HTTP_PROXY=http://proxy.example.com:80/" "NO_PROXY=localhost,127.0.0.1,docker-registry.somecorporation.com"
> 3. Flush the changes
>    $   sudo systemctl daemon-reload
> 4. Verify your changes are done.
> 
> $ systemctl show --property=Environment docker
> 
> 1. Restart Docker
> 
> $ sudo systemctl restart docker
> 
> 6 . Restart your Containers/ Registry ... There you go.. Your registry started working... :-)

Thanks, this is very helpful. Should be post in Docker push FAQ
