### ISSUE TITLE
Enhance coverage

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#216]
We are about 55% coverage.

Let's enhance that.

**Comment by stevvooe** [comment]
Let's set a clear coverage goal and split this down into per package tasks (which would end up being white-belt tasks, themselves). For a Go project, 75% to 80% is good but I'd like to hear people's opinions.

**Comment by HuKeping** [comment]
How about make a task list here or open a new issue, such as 
- [ ] manifest/sign.go
- [x] manifest/manifest.go

Then people can pick some to enhance

**Comment by stevvooe** [comment]
@HuKeping Please open specific issues for areas where coverage is both low and the lack of coverage opens up ambiguity in functionality.

@dmp42 Above, I proposed 75 to 80 percent. At 55%, we have had a good balance between maintainability and coverage. Are there specific sections of the code that require better coverage? I want to avoid the "code coverage crusade", and make sure we are taking actionable decisions. Right now, our defect rate is not bad, considering the level of code coverage. What could an extra 20% get us? What are the costs?

I am going to close this, unless there is disagreement around my points above.

**Comment by dmp42** [comment]
The only twos areas where I would love to see strong coverage are storage drivers, and http input handling (admittedly, the latter is not "unit" testing per-se).

Either way, the current coverage is ok IMO, and I certainly wouldn't want people to churn around just to cover silly/trivial paths.

**Comment by stevvooe** [comment]
@dmp42 Agreed. Do we have ways to check those requirements per package?

**Comment by dmp42** [comment]
@stevvooe I guess so - requires more tooling work though.
