### ISSUE TITLE
Define docker hostname/DNS underscore behavior

### ISSUE THREAD

**Issue by mostolog** [docker/distribution#2160]
Hi

As discussed in https://github.com/docker/docker/issues/27447 and suggested by @thaJeztah I file this issue in order to ask @docker for a clear statement on using underscores in container/services hostnames.

According to http://stackoverflow.com/a/2183140:
- DNS spec allows underscores
- Underscores aren't valid in hostnames
- Docker compose/stack deploy/services append _X to names

With https://github.com/docker/swarmkit/issues/1242 in mind, it would be great to know how underscores should be considered: Should docker binaries use "-" instead of "_" for compose/stack deploy/services instead? Might docker allow underscores in hostname but emit a warning if there are any? 

Regards.

**Comment by thaJeztah** [comment]
Keep in mind that my reference to this repository was for _image_ distribution (e.g. `docker pull _foo_bar.example.com:5000/repo/image:tag`), which is separate from service names.

We removed the validation on hostnames for containers (https://github.com/docker/docker/pull/28990), but hostnames are _local_ to the container, so not the name under which containers can be "discovered".

**Comment by mostolog** [comment]
@thaJeztah thanks for the clarification.
Have in mind hostname -f is used to return FQDN in relation with those issues. so I thought it worth it to mention.

**Comment by stevvooe** [comment]
@mostolog [The grammar](https://github.com/docker/distribution/blob/master/reference/reference.go#L4) for _image names_ does not allow `_`.

As far as https://github.com/docker/swarmkit/issues/1242 is concerned, `_` should only ever be used for DNS names that correspond to service records, as is required by DNS.

If compose/stack/deploy are pushing names that end up with `_` in container hostnames, that bug needs to be fixed immediately, as it is very wrong.

**Comment by mostolog** [comment]
@stevvooe should I report? Would you?

**Comment by stevvooe** [comment]
@mostolog I am not sure. Perhaps, the compose project would be the right place.

I am closing this issue, since we will not be adding support for underscores.
