### ISSUE TITLE
Docker Birthday issues triaging and ideas tracking

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#217]
The idea is to triage some issues that the community can sink its teeth into (features that we don't have time enough to work on, for eg).

Also, stuff that we don't track yet (nice to have, debugging tools, extensions ideas) should be created here.

To have something as part of this, simply apply the milestone "Docker Birthday" and choose a label "white/black belt".

@endophage are you ok overseeing the effort here?

**Comment by endophage** [comment]
Yep. I'll go through the list of currently open issues and talk to the team to solicit additional ideas.

**Comment by thaJeztah** [comment]
For reference, these are the "guidelines" for the triage process in docker; https://github.com/docker/docker/blob/master/project/ISSUE-TRIAGE.md

Apart from "white-belt"/"black-belt", docker also classifies the issues as
"Improvement", "Regression", "Feature" and "Bug".

**Comment by endophage** [comment]
Thank @thaJeztah I'll go through the issues closer to the date and make sure they all conform.

@dmp42 I've asked @NathanMcCauley to add some white belt issues for the health check api. They will be tickets to register services (S3, Cloudfront, etc...) with the health api. These should be reasonably simple but have a high value in ensuring the reliability of the registry.

**Comment by endophage** [comment]
Well past birthday now. Closing this.
