### ISSUE TITLE
Migrate v2 from disk to S3

### ISSUE THREAD

**Issue by aijanai** [docker/distribution#2180]
Hi,

I tarted out with a simple disk based setup. Now I'd like to push all my images on a S3 backend to cluter the registry, but I can't find any documentation/tooling about how to make the transition.

How can I migrate all my images and settings?

Thanks

**Comment by dmcgowan** [comment]
@aijanai the path layout for your local images should match what is in S3. I suggest porting your configuration to S3, starting it up, try pushing an image to it to look at the file layout. You can then just copy the local files over from the local base path for images to the S3 location. You can do this copy using the `aws` cli.

**Comment by aijanai** [comment]
Thanks a lot, first.

So, though your advice seems 100% logical and legit, I assume there is no standard procedure yet, isn't there?
