### ISSUE TITLE
CURL does not return complete list of image tags

### ISSUE THREAD

**Issue by awaissindhu** [docker/distribution#2182]
Hello,

I am not sure if this issue has been raised previously or if it has been resolved already. When I try to curl for the tags in a private repo, I don't get the complete list back. ie

curl -s -k -u : registry.hub.docker.com/v1/repositories/ibmdashdb/common/

does not return the complete list of tags that are available in the repo.

I've read that it's a limitation that was fixed with the v2 repository. However, we are trying to integrate docker with UrbanCode and that does not support v2 yet. Is there a workaround available that we can use?

Thanks!

**Comment by stevvooe** [comment]
@awaissindhu Unfortunately, we no longer support the v1 protocol. For security reasons, I would recommend staying away from registries that continue to support the v1 protocol.
