### ISSUE TITLE
garbage-collect doesn't release much space

### ISSUE THREAD

**Issue by StanleyShen** [docker/distribution#2190]
Hello, I am having a private docker registry, and we daily pushed images there, I had an job to run `garbage-collect` periodically, but I found the disk usage still keep increasing.

For example I have one image which is about 1.8G.
Before running the `garbage-collect`  the disk usage is 
```
/dev/xvdf1       99G   87G  6.7G  93% /var/vcap/store
```
After running `garbage-collect`, the disk usage is 
```
/dev/xvdf1       99G   87G  7.2G  93% /var/vcap/store
```

Which means after deleting the image, it only releases about 0.5G disk space, so what's the remaining 1.2G about?
The registry version is `./registry github.com/docker/distribution v2.4.1+unknown`

When running the `garbage-collect` I do see below logs like 
```
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/03/032c9cf1156abb7b4874b8e4023cf4914344d563cacae591dcf883035451f9bb  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/52/526200adb4e562d78fc42fa8db455f82e7ba7cfbb6ca206b9819b1d8cae1b20c  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/56/56652bc41678c3a0c39d71a7b5abfff52424dddcc9b5e10e6ab77f704d54fcdf  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/99/99647b2457ff2c14d0021fdda1136803b25d57d008957bdd5a18cd629c5b4e85  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/ce/ce7242dfaaec621f029795149ab0d6cb5467c5dc147680a21c6bda0064bb4a00  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/e3/e3a3b148f89d3c5ec415b0310936ad88afd814b5da2507a8c2e898d779f0174d  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/10/103dacd4981428e62a92586e434f31f021a84de6a3906e6cfca9b1f2c8bb77df  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/11/116679ed92079caa183bc74a6300b514b29ac5d6a086fbc9a1c3d1fb18d8f0f2  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/17/179bd293d2dfc0c039891e50ac056339f493fcca0b0fb4795fb67ef6ffe86efc  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/4f/4f4862a850ac45e9eca81b6dc4ca1cedc91c79e5316f125b4bb4b0b14e47d1af  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/89/8910ed079727b2440fe714e973181c624e688d09724b93f3a6576d4f426ff8c1  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/ad/adcaecf0c3a2c74b7d90a9b22ed8be10d2486723e6c4686430ac16381efbebe0  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/b1/b16bf7888d5ffeefad15ec2a811f247e65b6c75d4f79fa21acf14ce187594755  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/d9/d95803f917b8505a6a0a4c98c4f8710381dfa0b1f0c4f372ba20906c5f9c9995  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/18/18aefb43df71fc073c41a04689db8132ca5d803a50e8567ee5fff0297015e564  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/19/1983d3edccb0aead4e3fb3f7e5d8f38e85f8b74b8bcad1981fc3380c2e04478f  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/8a/8a13effafcb0396b401a116d0553f2ceeaedf0b934ee838a7c99cafdf9804fa0  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/92/9226016f37365aae77f30e37d47aa9d5934f7a8204eeceeef5704ef0dd9f3dd9  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/b3/b3741efd03d4535eeb167fdd6a7765aeca9dfcbd489a8a631da7177ae9b3ebc4  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/d4/d4e191bd4283c8ddc4cc57d9edf987a5cf773fb59591d993a54802f8ed59467c  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/5b/5b6df681cb1f4d11e6d1acf08d7dcfbed4c20bbcfec916f189b0946959332548  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/60/603a6affdfcb6943bc53535db3a3ddf376a1c7d7289c8418827b7e3ebc9a1c67  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/64/64e73dd0f364efef29b9abea57b59003d08b2317a8b1e440b3802db46b5c93dc  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
INFO[0002] Deleting blob: /docker/registry/v2/blobs/sha256/ca/ca0ec1eac59887dc3438fc175fc9330258764d64016fc983d36866119832f7aa  environment=registry-0 go.version=go1.7 instance.id=34dac3e9-0a18-4646-8650-15131f0d535a service=registry
```

Is there any known issue about this?

**Comment by mortensteenrasmussen** [comment]
Please note that Docker images are layers, and therefore deleting one image and garbage collecting will only delete the layers not used anymore.

consider this image:
```
alpine
java
your-jar-file.jar
```

If you have this image in tag `0.1` and `0.2` and you delete `0.1`, the garbage collect will only delete the last layer with your jar file (because the other layers are also used by `0.2`.

For excessive disk usage, you might be running into another gotcha, which is that if you push `latest`, and push `latest` again later (with different code), the old `latest` manifest is still valid (and can be fetched by digest), and can therefore not be garbage collected. I'm working on a script to clean up these manifests without any tags; I'll let you know when I have something.

A feature request to be able to garbage collect this is #1844.

**Comment by StanleyShen** [comment]
Thanks for information.
For the image I post above is just created recently and I just used latest tag, but I deleted the whole image, maybe some layer are used by other images also.
For other images, I used different tags each time, but even in this case, it seems there are still some layers are left after deleting some old tags.

I once decided to keep latest 6 tags for each image, at that time even we have 6 tags for each image , we still had some free disk space there.
Recently, it warns us the disk usage is almost 100% now, and I changed to keep latest 4 tags for each image, it freed some space, but after some days, the disk is almost 100% again.

**Comment by mortensteenrasmussen** [comment]
Hi, it sounds like you might have a lot of untagged manifests. To verify this, could you please run this on your registry server in the `$REGISTRY_DIR/data/docker/registry/v2/repositories` folder.

It will return the number of manifests you have in your registry that doesn't have a tag associated.

```
comm -23 <(find . -type f -name "link" | grep "_manifests/revisions/sha256" | grep -v "\/signatures\/sha256\/" | awk -F/ '{print $(NF-1)}' | sort) <(for f in $(find . -type f -name "link" | grep "_manifests/tags/.*/current/link"); do cat ${f} | sed 's/^sha256://g'; echo; done | sort) | wc -l
```

The command looks cryptic, but it uses the filesystem to check tags vs. manifests and returns the manifests that don't match any tags. If this number is high, I can help you with a command that can delete them. I'm planning to put it on Github, but I'm still testing/verifying it.

**Comment by antoinetran** [comment]
Hi, we have the same same issue. We followed the procedure the official [doc](https://github.com/docker/distribution/blob/master/docs/spec/api.md#deleting-an-image), but end up still having full space. In our case, we have images that has no tags at all, and it still takes lots of space. Only when we delete the hole image (that contains no tag), we can garbage-collect a lot of space.

Here is the result of the command:
```
comm -23 <(find . -type f -name "link" | grep "_manifests/revisions/sha256" | grep -v "\/signatures\/sha256\/" | awk -F/ '{print $(NF-1)}' | sort) <(for f in $(find . -type f -name "link" | grep "_manifests/tags/.*/current/link"); do cat ${f} | sed 's/^sha256://g'; echo; done | sort) | wc -l
299
```

**Comment by mortensteenrasmussen** [comment]
Hi, this means you have 299 manifests (docker images) that have no tags. If you don't use pull-by-digest but only pull by image:tag, then you could delete them.

This [gist](https://gist.github.com/mortensteenrasmussen/512f0566dbc3ef1cc4a2c47dd9cdb973) is a script to do that. Back up your registry beforehand. Please note that I'm not liable for anything that happens and all that stuff :)

Replace the path to your registry, as well as the ip/port of your registry.

It uses the same command like the one above, and then issues DELETE's to your registry for the manifests found. In my testing, it worked without any problems, and all my actual images and tags worked fine afterward. I cleaned up 200gb of a 255gb repo.

**Comment by antoinetran** [comment]
The script works only in bash (instead of sh). It did removed 304 manifests file. However, the garbage-collect reclaimed nothing.  I have to delete _manifests folder to reclaim spaces.

**Comment by mortensteenrasmussen** [comment]
Did you run a registry garbage collect after running the script?

**Comment by antoinetran** [comment]
yes

**Comment by mortensteenrasmussen** [comment]
So if you run the first command again, it should show close to 0. Correct? 

If not, then I think something is wrong with the requests to the registry (the curl command). Please check, and if the number is the same as before you ran the cleanup, please try to run one of the curl commands manually to figure out what's going wrong.

**Comment by antoinetran** [comment]
Ok found it, firstly, we used https instead of http, so it did http://https://.. . Secondly, I added --insecure in curl, because we use auto-generated certificate for now.
We reclaimed ~40GB of space, that's cool!

Somehow, this procedure should be in the official doc one day, because the workflow of overwriting latest layers in very used in every development environment.

Thank you again.

**Comment by mortensteenrasmussen** [comment]
You're most welcome. Glad I could help.

I updated the gist to use registry URL instead of host and port variables. Should help people later.

**Comment by StanleyShen** [comment]
@mortensteenrasmussen I run 
```
comm -23 <(find . -type f -name "link" | grep "_manifests/revisions/sha256" | grep -v "\/signatures\/sha256\/" | awk -F/ '{print $(NF-1)}' | sort) <(for f in $(find . -type f -name "link" | grep "_manifests/tags/.*/current/link"); do cat ${f} | sed 's/^sha256://g'; echo; done | sort) | wc -l
```
In my docker registry VM, and it shows 751

**Comment by mortensteenrasmussen** [comment]
@StanleyShen Please try to run the gist I linked [above](https://github.com/docker/distribution/issues/2190#issuecomment-279343010)

Read the other comments if you use https for your repo. It should delete the 751 docker images you have that doesn't have any tags.

If that works, please mention how much space it freed up, and then we can close this issue. I'm working on fixing up the cleanup script and put it in a docker container that's easy to use, and I'll link to the repo here when ready.

**Comment by antoinetran** [comment]
Do you think it is a good idea to submit a feature request about the registry v2 API? This script just shows the registry is missing an official way to clean untagged image, the same way we clean docker cache using "--filter dangling=true". This feature has cost us days, because it forces us to delete all image tags to reclaim spaces. If yes, would an issue in github be the best way for such a request?

**Comment by mortensteenrasmussen** [comment]
We already have one, as I mentioned in a [previous comment](https://github.com/docker/distribution/issues/2190#issuecomment-279199626). 

It's called #1844

**Comment by StanleyShen** [comment]
```
/dev/xvdf1       99G   89G  5.3G  95% /var/vcap/store
/dev/xvdf1       99G   16G   78G  17% /var/vcap/store
```

After running script, it's 16G now, it release about 73G for me.

**Comment by StanleyShen** [comment]
It's cool as  the script works as magic, thanks for help.

**Comment by mortensteenrasmussen** [comment]
You're most welcome. Can we close this issue now?

**Comment by maxio** [comment]
As the feature is tracked in other place, so please go ahead to close this one, I cannot close it by myself.

**Comment by StanleyShen** [comment]
maxio is also me, I forgot I was in another account.

**Comment by mbert** [comment]
@mortensteenrasmussen  thank you for directing me here. Your above comment (about untagged manifests) as well as the script you provided helped us resolve the growing disk space problems we had with our private registry.

However I do not understand why this is not the default? Correct me if I'm wrong, but when I push over an existing tag (we do this in our nightly build jobs to make sure that all our toolchain is still buildable) should what was pushed over and is no longer referenced by other images not be garbage-collected without this manual step? 

Or am I misinterpreting something here?

**Comment by mortensteenrasmussen** [comment]
@mbert You're welcome.

You can do docker pull with both image:tag, as well as image:sha256 sum. Some people choose this to make sure they choose the exact image they want. 

Even when you overwrite your image:tag, the old one can still be pulled via the sha-sum, which is why the garbage collect doesn't pick it up.

The script I made simply finds all these manifests that are no longer referenced by any tag, and deletes them. When this is done, the blobs (layers) are no longer referenced by anything and can, therefore, be garbage collected.

It's therefore not a bug per se, but I agree it can be somewhat hard to wrap your head around (until you understand it completely) - and it can indeed seem counter-intuitive.

I hope this made it clear.

**Comment by mbert** [comment]
Thank you, this explains it!

**Comment by mortensteenrasmussen** [comment]
Hi,

I have now created a bit more sustainable solution for this. Please use/star/ignore as you see fit.

https://github.com/mortensteenrasmussen/docker-registry-manifest-cleanup
https://hub.docker.com/r/mortensrasmussen/docker-registry-manifest-cleanup

**Comment by antoinetran** [comment]
We deployed a cron that executes this script. But we encountered an issue that may be related to this script. How well does this script resist to race condition?
The symptoms are:
```
sudo docker pull [Image]:[Version]
[Version]: Pulling from ...
45a2e645736c: Already exists
fffdc9cd00d0: Already exists
991e46ec94a9: Already exists
3539362589ad: Already exists
65dd1f11758e: Already exists
9e3ed43117dc: Already exists
7d6432f472af: Already exists
74c725b2370d: Already exists
97246cd202b6: Already exists
9b91802bdd44: Already exists
75f47dcffa4f: Already exists
ad1062d1ad56: Already exists
69f1b2e5b5c8: Already exists
fa42d3d5997a: Already exists
e1f5e167f582: Already exists
039ddd2e6b7a: Already exists
f4fe203c0bcc: Already exists
cd5ab8a2f539: Already exists
1b93c8b04a78: Already exists
50dda98c3ed4: Already exists
353b97c92a07: Already exists
1b7803fc3124: Retrying in 4 seconds
49eb1480916e: Retrying in 4 seconds
b2c65301a004: Retrying in 4 seconds
690f6c2b6a71: Waiting
f6f72b43ce9a: Waiting
aa218eca26b2: Waiting
f1eafb397587: Waiting
```


```
sudo docker pull [Image]:[Version]
[Version]: Pulling from ...
45a2e645736c: Already exists
fffdc9cd00d0: Already exists
991e46ec94a9: Already exists
3539362589ad: Already exists
65dd1f11758e: Already exists
9e3ed43117dc: Already exists
7d6432f472af: Already exists
74c725b2370d: Already exists
97246cd202b6: Pull complete
9b91802bdd44: Pull complete
75f47dcffa4f: Pull complete
ad1062d1ad56: Pull complete
69f1b2e5b5c8: Pull complete
fa42d3d5997a: Pull complete
e1f5e167f582: Pull complete
039ddd2e6b7a: Pull complete
f4fe203c0bcc: Pull complete
cd5ab8a2f539: Pull complete
1b93c8b04a78: Pull complete
50dda98c3ed4: Pull complete
353b97c92a07: Pull complete
1b7803fc3124: Downloading [==================================================>]  1.94 kB/1.94 kB
49eb1480916e: Downloading [==================================================>]   859 MB/859 MB
b2c65301a004: Downloading [==================================================>] 2.434 kB/2.434 kB
690f6c2b6a71: Download complete
f6f72b43ce9a: Downloading [==================================================>]    691 B/691 B
aa218eca26b2: Downloading [==================================================>]    704 B/704 B
f1eafb397587: Downloading [==================================================>]    216 B/216 B
unexpected EOF
```
We couldn't pull an image. Even rebuilding the image does not fix. We had to delete the image directory (with all tags/revisions) ([RegistryDir]/[RepoName]/[ImageName]) and garbage-collect, then rebuild the image, for the pull to work.
I believe some layers was missing because they were removed by the cron script, while another image was being pushed. I also suspect this because our logs showed that a clean and a push was processing at the same time.

Anyone has seen this?

**Comment by mortensteenrasmussen** [comment]
@antoinetran I'm sorry you experienced issues with this. The cleaning script only cleans manifests that are not pointed to by any tags. 

Also, the clean script does not actually remove any files (aka, blobs/layers), the file removal is done by the registry garbage collect itself.

As mentioned in the docs, your repo should be in read-only mode or stopped when you do the garbage collect, and you also need to restart the registry after a garbage collect (recommended way is to stop the repo, run GC and then start it again.

Off the top of my head, I can't see a way that a push and clean simultaneously should cause issues, but there might be certain edge cases I haven't thought of.

Also, please look at [the new script](https://github.com/mortensteenrasmussen/docker-registry-manifest-cleanup) where I have added some more error checking and packed it up a bit nicer.

Could you make an issue in that repo so we can continue the talk there?

**Comment by antoinetran** [comment]
Thank you. From what you said, and what is written in the docs ([here](https://docs.docker.com/registry/garbage-collection/)) as you said, this seems to be the answer. If the official docs says to put the registry in maintenance, we should do this, although this is a bit surprising.

I hope that the future version of registry that will fix this will be on fast!

> This type of garbage collection is known as stop-the-world garbage collection. In future registry versions the intention is that garbage collection will be an automated background action and this manual process will no longer apply.

Therefore, I don't see any point in adding an issue, that is currently handled by registry team. Or do you believe the new script version correct some related issue?

**Comment by mortensteenrasmussen** [comment]
Hi,

You're most welcome. The new script doesn't change any functionality; it just has a nicer package and better error handling. 

If you already have the old one running and working, it shouldn't be any difference. However, if I decide to extend functionality it will be done in the repo linked above, so if you want to keep up to date, I'd suggest you keep track of that one.

Glad I could clarify.

**Comment by gregori-goossens** [comment]
@mortensteenrasmussen 
Hi,

i have same issue describe by @antoinetran.
It occurs when we run a registry garbage-collect if a image push is running.
If some layers have been pushed but push not finish when stop **registry serve** then call **registry garbage-collect**, it will remove this new layers (not link yet to any manifest).

We need to push the image again (be sure to stop / start **registry serve** for clearing inmemory cache).

So, it not really an issue,  but we must pay attention to that.

By the way, thanks for your script.

**Comment by anthuwan13** [comment]
Should a image be first build with the docker file and then should run the sudo docker run -it  command as mentioned here - https://github.com/mortensteenrasmussen/docker-registry-manifest-cleanup ?

**Comment by mortensteenrasmussen** [comment]
Hi,

This issue has been closed for close to a year. I'd recommend you create an issue in the repo for this cleanup script if you have issues: https://github.com/mortensteenrasmussen/docker-registry-manifest-cleanup

To answer your question, you can just pull the image from Docker Hub and use it as described in the repo linked above, or you can build it yourself if you're more comfortable with that.

**Comment by anthuwan13** [comment]
Thanks. It worked .
