### ISSUE TITLE
Swift storage driver

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#220]
We currently have filesystem, S3 and Azure drivers.

Let's have moar!

Reach out to #docker-distribution on irc for starters.

**Comment by JeanMertz** [comment]
this would certainly be a nice feature to have :+1:

**Comment by estesp** [comment]
For anyone coming along to this issue looking for current status, note that PR #493 is the implementation of a Swift storage driver currently under review for inclusion.

**Comment by dmp42** [comment]
Closed by merging #493
