### ISSUE TITLE
msg="response completed with error" environment=development err.code="blob unknown"

### ISSUE THREAD

**Issue by rick1vas** [docker/distribution#2208]
https://github.com/docker/distribution v2 private registry container logs msg="response completed with error" environment=development err.code="blob unknown"

I did the following to test the repository https://github.com/docker/distribution.git:
  cloned the repository
  created a simple custom config
  built an image
  added an insecure registry
  and finally ran a container to test

When querying or pushing an image to the private registry container the log shows err.code="blob unknown" messages.
The querys and push appear to work correctly.

What do the errors mean?
How can the error messages be avoided?
Is there something in the configuration that should be changed to avoid the errors?

# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:48:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:48:37 2017
 OS/Arch:      linux/amd64
 Experimental: false

## Commands and sequence of commands:

$ docker run --publish 5000:5000 --name distribution --rm distribution

$ curl -v --insecure GET http://dockerreg:5000/v2/

$ docker push dockerreg:5000/ubuntu

$ curl -v --insecure GET http://dockerreg:5000/v2/_catalog

$ curl -v --insecure GET http://dockerreg:5000/v2/ubuntu/tags/list

## Docker daemon info.

$ systemctl status -l docker
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           +-http-proxy.conf
   Active: active (running) since Thu 2017-03-02 16:01:24 CET; 1h 38min ago
     Docs: https://docs.docker.com
 Main PID: 1034 (dockerd)
    Tasks: 24 (limit: 4915)
   Memory: 208.5M
      CPU: 32.676s
   CGroup: /system.slice/docker.service
           +-1034 /usr/bin/dockerd --insecure-registry dockerreg:5000
           +-1133 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc

Mar 02 16:01:21 my-fedora25server dockerd[1034]: time="2017-03-02T16:01:21.263875559+01:00" level=info msg="Loading containers: start."
Mar 02 16:01:21 my-fedora25server dockerd[1034]: time="2017-03-02T16:01:21.584578821+01:00" level=info msg="Firewalld running: true"
Mar 02 16:01:23 my-fedora25server dockerd[1034]: time="2017-03-02T16:01:23.613446779+01:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Mar 02 16:01:24 my-fedora25server dockerd[1034]: time="2017-03-02T16:01:24.360814658+01:00" level=info msg="Loading containers: done."
Mar 02 16:01:24 my-fedora25server dockerd[1034]: time="2017-03-02T16:01:24.628953892+01:00" level=info msg="Daemon has completed initialization"
Mar 02 16:01:24 my-fedora25server dockerd[1034]: time="2017-03-02T16:01:24.629562088+01:00" level=info msg="Docker daemon" commit=092cba3 graphdriver=overlay2 version=1.13.1
Mar 02 16:01:24 my-fedora25server systemd[1]: Started Docker Application Container Engine.
Mar 02 16:01:24 my-fedora25server dockerd[1034]: time="2017-03-02T16:01:24.676239160+01:00" level=info msg="API listen on /var/run/docker.sock"
Mar 02 16:51:23 my-fedora25server dockerd[1034]: time="2017-03-02T16:51:23.223349355+01:00" level=error msg="Attempting next endpoint for push after error: Get https://dockerreg:5000/v2/: http: server gave HTTP response to HTTPS client"
Mar 02 16:53:14 my-fedora25server dockerd[1034]: time="2017-03-02T16:53:14.989263234+01:00" level=error msg="Attempting next endpoint for push after error: Get https://dockerreg:5000/v2/: http: server gave HTTP response to HTTPS client"

## distribution container log with errors is attached

[distribution_container.txt](https://github.com/docker/distribution/files/816515/distribution_container.txt)

**Comment by dmcgowan** [comment]
> What do the errors mean?

Means that a 404 was returned on a resource request

> How can the error messages be avoided?

Docker will always check to see if blobs exist before pushing, 404 is an acceptable response

> Is there something in the configuration that should be changed to avoid the errors?

If you don't care about these messages, it is safe to discard them. You would probably only care about these errors when you get an unexpected failure from the client.
