### ISSUE TITLE
Google Cloud Storage driver

### ISSUE THREAD

**Issue by endophage** [docker/distribution#221]
**Summary:** Implement a storage driver for Google Cloud Storage.

**Proposed Solution:**

Implement a new driver in the registry/storage/driver directory that conforms to the StorageDriver interface. Use the libraries detailed in [this example](https://cloud.google.com/storage/docs/json_api/v1/json-api-go-samples). Update docs/configuration.md with the required configuration for Google Cloud Storage under the storage section.

**Comment by RichardScothern** [comment]
It appears one has arrived in the form of #756

**Comment by RichardScothern** [comment]
#756 merged
