### ISSUE TITLE
re-vendor the latest Azure Storage SDK for better performance

### ISSUE THREAD

**Issue by yuwaMSFT2** [docker/distribution#2224]
Current version of Azure Storage SDK implements buildCanonicalizedHeader with unnecessary regex operation:
https://github.com/docker/distribution/blob/master/vendor/github.com/Azure/azure-sdk-for-go/storage/client.go#L269-L273

In our test it took about 9% CPU by itself, not to say GC pressure.
![buildcanonicalizedstring-regex](https://cloud.githubusercontent.com/assets/23645697/24280618/2991acc2-100f-11e7-9bc0-36e1f097efd7.jpg)

TOP 10:
      flat  flat%   sum%        cum   cum%
    3660ms 10.54% 10.54%     6120ms 17.63%  runtime.scanobject
    1780ms  5.13% 15.67%     1780ms  5.13%  runtime.heapBitsForObject
    1760ms  5.07% 20.74%     1770ms  5.10%  runtime.greyobject
    1720ms  4.96% 25.70%     9960ms 28.69%  runtime.mallocgc
    1360ms  3.92% 29.62%     3560ms 10.26%  math/big.nat.divLarge
    1280ms  3.69% 33.30%     1280ms  3.69%  runtime.memclrNoHeapPointers
    1050ms  3.03% 36.33%     1140ms  3.28%  syscall.Syscall
     920ms  2.65% 38.98%      920ms  2.65%  runtime._ExternalCode
     690ms  1.99% 40.97%      690ms  1.99%  runtime.heapBitsSetType
     540ms  1.56% 42.52%      540ms  1.56%  math/big.addMulVVW

After change to plain string comparison the CPU usage was less than 2% by itself, 

![buildcanonicalizedstring-string](https://cloud.githubusercontent.com/assets/23645697/24280885/9f355d50-1011-11e7-8a94-e8fd3a7ba839.jpg)

      flat  flat%   sum%        cum   cum%
    1870ms  6.75%  6.75%     3150ms 11.38%  runtime.scanobject
    1650ms  5.96% 12.71%     1770ms  6.39%  syscall.Syscall
    1530ms  5.53% 18.24%     6720ms 24.27%  runtime.mallocgc
     970ms  3.50% 21.74%      970ms  3.50%  runtime._ExternalCode
     940ms  3.39% 25.14%      940ms  3.39%  runtime.greyobject
     810ms  2.93% 28.06%      810ms  2.93%  runtime.heapBitsSetType
     660ms  2.38% 30.44%      660ms  2.38%  runtime.heapBitsForObject
     640ms  2.31% 32.76%      640ms  2.31%  runtime.memclrNoHeapPointers
     630ms  2.28% 35.03%      630ms  2.28%  runtime.memmove
     480ms  1.73% 36.76%      480ms  1.73%  crypto/aes.decryptBlockGo

This should have been optimized in the latest Azure Storage SDK. Registry should consider to revendor to use the newer version.

**Comment by yuwaMSFT2** [comment]
@DavidObando @SajayAntony @sivagms

**Comment by stevvooe** [comment]
@yuwaMSFT2 PR?

**Comment by yuwaMSFT2** [comment]
Will do
