### ISSUE TITLE
getting blank sets when accessing v2/_catalog using riak-cs(2.0.1) backend

### ISSUE THREAD

**Issue by Charles546** [docker/distribution#2226]
The registry is accessing the riak-cs without specifying delimiter, causing riak-cs to crash.  The crash log points to a function where it tries to search for the delimiter'<<>>' in the file path.  We have to use s3-goamz driver because the riak-cs doesn't support v4auth yet.

**Comment by dmcgowan** [comment]
@Charles546 have you tried using the v2 signing with the s3-aws driver?

**Comment by Charles546** [comment]
@dmcgowan I don't see an option to use v2 signing with s3-aws driver.

**Comment by dmcgowan** [comment]
See comment on #2227
