### ISSUE TITLE
will docker/distribution be an individual project, to docker/docker-registry?

### ISSUE THREAD

**Issue by xiekeyang** [docker/distribution#224]
@dmp42 
It is a question.
Currently this project of docker/distribution is independent of docker-registry, 
and hasn't been ported into docker-registry next-generation version.
I check the milestone, but not sure if it will be merged to docker-registry.
In future, if it will exist as individual project for implementation, or be transported to docker-registry project someday? 
Thanks a lot!

**Comment by dmp42** [comment]
Thanks for your question:

 * *docker-registry* branch next-generation is deprecated and has been superseded by *distribution* 
 * *docker-registry* is kept for the python, v1, registry, and is in maintenance mode
 * the future of the registry (golang, v2) **is** *distribution*, and will soon be considered the stable, best choice
 * they will not be merged in the future

Hope that clarifies.
Let me know.

**Comment by xiekeyang** [comment]
@dmp42 
Thanks for your detailed explain!

**Comment by thaJeztah** [comment]
Has this / will this be added to the README of both repos?

**Comment by xiekeyang** [comment]
@dmp42

**Comment by xiekeyang** [comment]
@dmp42 
If docker/distribution will be permanent project name for future registry,
or will be new branch (like NG) of docker/docker-registry project?
Thanks a lot!

**Comment by dmp42** [comment]
docker/distribution will be the permanent project name and there will be no new branch.

**Comment by stevvooe** [comment]
@thaJeztah I am working up a README right now (or at least an outline). This should be a part of it.

**Comment by thaJeztah** [comment]
@stevvooe :+1: great!

**Comment by stevvooe** [comment]
@xiekeyang Closing, assuming your question is answered. Please let me know if that is not the case.
