### ISSUE TITLE
Different Manifests with different docker versions(docker 1.10+)

### ISSUE THREAD

**Issue by duyanghao** [docker/distribution#2243]
there is a strange thing like below:
step1: docker(version:1.10.0) push domain0/duyanghao/mysql:5.6

step2: curl  -v -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' http://xxxx/v2/duyanghao/mysql/manifests/5.6 

```
< HTTP/1.1 200 OK
< Content-Length: 2595
< Content-Type: application/vnd.docker.distribution.manifest.v2+json
< Docker-Content-Digest: sha256:1d99ad1a8a2f8859dc986566cc31741c00a050d5fbf9305e7cd74398ade79f36
< Docker-Distribution-Api-Version: registry/2.0
< Etag: "sha256:1d99ad1a8a2f8859dc986566cc31741c00a050d5fbf9305e7cd74398ade79f36"
< X-Content-Type-Options: nosniff
< Date: Sat, 01 Apr 2017 02:11:44 GMT
< 
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/octet-stream",
      "size": 6563,
      "digest": "sha256:01bbb21c400cb35e3341c05d52a9ad3abbf26d043906728fd6bd29e311afe8b4"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 51352535,
         "digest": "sha256:5c90d4a2d1a8dfffd05ff2dd659923f0ca2d843b5e45d030e17abbcd06a11b5b"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2040,
         "digest": "sha256:89e2627e92010328b8051ad7720317540d59d77ac9b417f2f54bf11f71a110ae"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1236828,
         "digest": "sha256:76f6983b0fe0c473e96c50a59c7799ca8f932d3a24e408281f9d6fabcb9458f2"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 114,
         "digest": "sha256:653577605512ce8db9be36bdd31f41d6742fa3d627c6876ddb70fe4a84dd365a"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 8267024,
         "digest": "sha256:bd6c32d9a05f118266e0a9f59e1257f51c3eb6aabc62d29b19bf422b4357c54d"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 19017,
         "digest": "sha256:0632c43d2f8e05e3d6ab2e7b7e8c4025912faed0fce7fc11b538288c3c0d03a8"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 216,
         "digest": "sha256:d8bd60447797968dbd98867a2d81ee46ffca173d52a8d3b4164e4018c76d4df4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 51781141,
         "digest": "sha256:3898783b7b39826d684706f02fc9e3b04aabf5f2d343c83862c10968c95ac414"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1176,
         "digest": "sha256:46026fe91c49a1e04d1c1e57849a61a7b099131d086ad13cdd4d08bdd7a1459e"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1712,
         "digest": "sha256:50953e0b43e88b1e57b37e1f27c26bb940eda35b1cc3c255e2b6883a2b9f0fdb"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 118,
         "digest": "sha256:d5f03842f2c87a07928075ea542fe847dc494b2a5bb66f17492a62ac7f4a73ed"
      }
   ]
}
```

look at the `config.mediaType` field in the Manifest file:`application/octet-stream`

step3: docker(version:1.12.5) pull domain0/duyanghao/mysql:5.6

```
5.6: Pulling from duyanghao/mysql
5c90d4a2d1a8: Pull complete 
89e2627e9201: Pull complete 
76f6983b0fe0: Pull complete 
653577605512: Pull complete 
bd6c32d9a05f: Pull complete 
0632c43d2f8e: Pull complete 
d8bd60447797: Pull complete 
3898783b7b39: Pull complete 
46026fe91c49: Pull complete 
50953e0b43e8: Pull complete 
d5f03842f2c8: Pull complete 
Digest: sha256:1d99ad1a8a2f8859dc986566cc31741c00a050d5fbf9305e7cd74398ade79f36
Status: Downloaded newer image for domain0/duyanghao/mysql:5.6
```
```
docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
domain0/duyanghao/mysql      5.6                 01bbb21c400c        9 months ago        330 MB
```

step4: docker(version:1.12.5) push domain0/duyanghao/mysql:5.6

```
The push refers to a repository [domain0/duyanghao/mysql]
80b65764e462: Pushed 
ea7a30c83406: Pushed 
4da537c4027e: Pushed 
89c8efc2ee44: Pushed 
8e25b7f39a75: Pushed 
7f5dcbf5b81f: Pushed 
6905deb57b14: Pushed 
4ee4d807cfd9: Pushed 
0e6048bd4126: Pushed 
04e643fddbab: Pushed 
42755cf4ee95: Pushed 
5.6: digest: sha256:c03fbc5b1a2e25028ade67bb6f81e5abd1269c9c952016baace57174d1e399eb size: 2617
```
look at the `digest`:`sha256:c03fbc5b1a2e25028ade67bb6f81e5abd1269c9c952016baace57174d1e399eb` in the output of docker push,it is different with `digest`:`sha256:1d99ad1a8a2f8859dc986566cc31741c00a050d5fbf9305e7cd74398ade79f36`  in the above docker pull output 

step5: curl  -v -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' http://xxxx/v2/duyanghao/mysql/manifests/5.6 

```
< HTTP/1.1 200 OK
< Content-Length: 2617
< Content-Type: application/vnd.docker.distribution.manifest.v2+json
< Docker-Content-Digest: sha256:c03fbc5b1a2e25028ade67bb6f81e5abd1269c9c952016baace57174d1e399eb
< Docker-Distribution-Api-Version: registry/2.0
< Etag: "sha256:c03fbc5b1a2e25028ade67bb6f81e5abd1269c9c952016baace57174d1e399eb"
< X-Content-Type-Options: nosniff
< Date: Sat, 01 Apr 2017 02:27:32 GMT
< 
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 6563,
      "digest": "sha256:01bbb21c400cb35e3341c05d52a9ad3abbf26d043906728fd6bd29e311afe8b4"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 51352535,
         "digest": "sha256:5c90d4a2d1a8dfffd05ff2dd659923f0ca2d843b5e45d030e17abbcd06a11b5b"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2040,
         "digest": "sha256:89e2627e92010328b8051ad7720317540d59d77ac9b417f2f54bf11f71a110ae"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1236828,
         "digest": "sha256:76f6983b0fe0c473e96c50a59c7799ca8f932d3a24e408281f9d6fabcb9458f2"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 114,
         "digest": "sha256:653577605512ce8db9be36bdd31f41d6742fa3d627c6876ddb70fe4a84dd365a"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 8267024,
         "digest": "sha256:bd6c32d9a05f118266e0a9f59e1257f51c3eb6aabc62d29b19bf422b4357c54d"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 19017,
         "digest": "sha256:0632c43d2f8e05e3d6ab2e7b7e8c4025912faed0fce7fc11b538288c3c0d03a8"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 216,
         "digest": "sha256:d8bd60447797968dbd98867a2d81ee46ffca173d52a8d3b4164e4018c76d4df4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 51781141,
         "digest": "sha256:3898783b7b39826d684706f02fc9e3b04aabf5f2d343c83862c10968c95ac414"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1176,
         "digest": "sha256:46026fe91c49a1e04d1c1e57849a61a7b099131d086ad13cdd4d08bdd7a1459e"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1712,
         "digest": "sha256:50953e0b43e88b1e57b37e1f27c26bb940eda35b1cc3c255e2b6883a2b9f0fdb"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 118,
         "digest": "sha256:d5f03842f2c87a07928075ea542fe847dc494b2a5bb66f17492a62ac7f4a73ed"
      }
   ]
}
```

look at the `config.mediaType` field in the Manifest file:`application/vnd.docker.container.image.v1+json`

step 6: docker rmi -f 01bbb21c400c   

step7: docker v1.12.5 pull domain0/duyanghao/mysql:5.6

```
5.6: Pulling from duyanghao/mysql
5c90d4a2d1a8: Pull complete 
89e2627e9201: Pull complete 
76f6983b0fe0: Pull complete 
653577605512: Pull complete 
bd6c32d9a05f: Pull complete 
0632c43d2f8e: Pull complete 
d8bd60447797: Pull complete 
3898783b7b39: Pull complete 
46026fe91c49: Pull complete 
50953e0b43e8: Pull complete 
d5f03842f2c8: Pull complete 
Digest: sha256:c03fbc5b1a2e25028ade67bb6f81e5abd1269c9c952016baace57174d1e399eb
Status: Downloaded newer image for domain0/duyanghao/mysql:5.6
```

```
docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
domain0/duyanghao/mysql   5.6                 01bbb21c400c        9 months ago        330 MB
```

in the above steps,we can find that when different docker versions(1.10.0|1.12.5) push the same image,the manifest gotten from registry is different,and the only difference is the field of `config.mediaType`.

there are two questions:

question #1: As far as i know,docker 1.10+(including docker 1.10.0) uses Manifest Schema v2. so i do think the manifests of the same image gotten from registry should be absolutely same,but the results show different,that quite strange!!!

question #2: when different docker versions(1.10+) push the same image,will the image data stored in registry be different?if that so,that would cause image data corruption,and that would be a disaster!!!

Addition:
Registry version:2.3.0

@aaronlehmann @dmcgowan

**Comment by aaronlehmann** [comment]
Older versions of Docker wrongly used `application/octet-stream` as the media type (see #1621). This was fixed in #1622.

> As far as i know,docker 1.10+(including docker 1.10.0) uses Manifest Schema v2. so i do think the manifests of the same image gotten from registry should be absolutely same,but the results show different,that quite strange!!!

There is no guarantee that manifests generated by different Docker versions will be identical. In this case, a bug fix causes manifests to differ. There are other reasons why manifests could change. The most basic is that a new version of Docker could compress layers differently, which would lead to different layer hashes.

> when different docker versions(1.10+) push the same image,will the image data stored in registry be different?if that so,that would cause image data corruption,and that would be a disaster!!!

There shouldn't be any issues with data corruption. Since version 1.10, Docker images are content-addressability, and when you push an image to a registry, the content should be unchanged. It's possible for the compression to be different, though, as I mentioned above. So two versions of Docker might upload different blobs for the same layer, but after decompression, those blobs should be exactly the same.

There have been some a few minor data corruption bugs in older versions, but the ones we know of have been fixed.

**Comment by dmcgowan** [comment]
Thanks @aaronlehmann 

No data corruption has happened, we are making sure to support "application/octet-stream" as "application/vnd.docker.container.image.v1+json" in Docker to account for this bug.

**Comment by duyanghao** [comment]
@aaronlehmann thanks for your response.But it's too chaotic and complex for me to figure it out,three are so many docker versions,and our users use different docker versions(1.10+).

the most important issue i care about is data corruption.And i know following scenarios(or maybe more scenarios i have not found yet) has happened:

scenario1:
user A(docker version:1.10.0) push image:ImageA
user A(docker version:1.10.0) push image:ImageA again

Result: Manifest is different,refers to [this](https://github.com/docker/distribution/issues/2066)

scenario2:
user A(docker version:1.10.0) push image:ImageA
user B(docker version:1.12.5,or maybe any versions>=1.10.0) push image:ImageA again

Result: Manifest is different,and maybe digest is different too as you said above(i have not found that the digests of the same image will be different when different docker versions push the same image)

And,Our production environment is that:
registry version:2.3.0
docker version:1.10.0+(including 1.10.0)

Should i be confident that there will never be any image data corruptions since both docker 1.10.0+ and  registry 2.3.0 support `Manifest Schema v2`?
