### ISSUE TITLE
off-by-one-error parsing image_name's tag

### ISSUE THREAD

**Issue by JonJagger** [docker/distribution#2248]
TagRegexp (line 37) In https://github.com/docker/distribution/blob/master/reference/regexp.go is
TagRegexp = match(`[\w][\w.-]{0,127}`)
This will match 128 characters. One for the initial [\w] and then up to 127 more.
According to https://github.com/docker/docker/blob/master/image/spec/v1.1.md tags are limited to 127 chars so I think the regex should change 127 for 126. 

I think there are two errors in the comment at the top of
https://github.com/docker/distribution/blob/master/reference/reference.go

Firstly, the same tag's 127->126 
tag := /[\w][\w.-]{0,127}/
should be
tag := /[\w][\w.-]{0,126}/

Also,

digest-algorithm := digest-algorithm-component [ digest-algorithm-separator digest-algorithm-component ]

which I think is missing a trailing * and should be this

digest-algorithm := digest-algorithm-component [ digest-algorithm-separator digest-algorithm-component ]*

See DigestRegexp (line 44) in https://github.com/docker/distribution/blob/master/reference/regexp.go

I'd issue a PR but I'm not a Go programmer (I needed to parse an image_name in Ruby).

**Comment by stevvooe** [comment]
Generally, the grammer at the top of [reference.go](https://github.com/docker/distribution/blob/master/reference/reference.go) should be considered canonical. We'll have to update that specification document to follow the convention of 128 allowed characters. Notice that all of the down streams from that grammar take on "127 method" of expressing tag restrictions.

Looks like [OCI](https://github.com/opencontainers/image-spec/blob/master/schema/defs-descriptor.json#L12) and [`go-digest`](https://github.com/opencontainers/go-digest/blob/master/digest.go#L57) allows any combination of characters in the algorithm field.

- [ ] Create a PR to fix https://github.com/docker/docker/blob/master/image/spec/v1.1.md to allow 128 characters to be in line with the actual behavior. (If you won't mind doing, it doesn't involve Go code, please submit againt `moby/moby` referencing this issue)
- [ ] Fix grammar in [reference.go](https://github.com/docker/distribution/blob/master/reference/reference.go#L18) to allow multiple separators in the algorithm.
- [ ] PR to OCI [`go-digest`](https://github.com/opencontainers/go-digest/blob/master/digest.go#L57) to force starting with a character and allow multiple separators.
- [ ] PR to [OCI `go-digest`](https://github.com/opencontainers/go-digest/blob/master/digest.go#L57) to force starting with a character and allow multiple separators.
- [ ] PR to [OCI image-spec](https://github.com/opencontainers/image-spec/blob/master/schema/defs-descriptor.json#L12) to restrict to first character.

This isn't a _huge_ deal, as the algorithms are validated against support fixed strings, but we should at least get them consistent.

**Comment by stevvooe** [comment]
@JonJagger Have we covered this your satisfaction?

**Comment by JonJagger** [comment]
Yes. Thankyou. And I do plan to get round to the PR.

**Comment by dmcgowan** [comment]
Thank you @JonJagger for the careful eye, closing this now
