### ISSUE TITLE
Invalid region provided: s3.eu-west-2.amazonaws.com

### ISSUE THREAD

**Issue by dcmwong** [docker/distribution#2256]
When trying to run docker registry configured to point to an s3 bucket in this region s3.eu-west-2.amazonaws.com.  I get this error in the container logs:

**panic: Invalid region provided: s3.eu-west-2.amazonaws.com**

Relating to this issue https://github.com/docker/distribution/issues/1712

Can I propose to add eu-west-2 to the list that was modified in this PR https://github.com/docker/distribution/pull/1714

**Comment by dmcgowan** [comment]
Already in master, see https://github.com/docker/distribution/blob/master/registry/storage/driver/s3-aws/s3.go

You can try a master build of the registry or wait until the next release. The first release candidate is expected in a few weeks.

**Comment by quynhdang-vt** [comment]
Probably trivial to some, but I would like to know how to pick up these changes ?
The official registry:latest Docker image or 2.6.2 doesn't have this fix apparently since I too have the error when configure the registry to use storage in s3 eu-west-2.

Thanks for any help.

**Comment by ocasta** [comment]
Closed because it's in master but master hasn't been released :(
Clearly the first release candidate promised in April has never seen the light of day
