### ISSUE TITLE
Resource type required for plugin

### ISSUE THREAD

**Issue by AlvinFeng** [docker/distribution#2257]
When pushing a plugin to the registry, the requested resource is "repository(plugin)". My auth service does return a jwt with access[type] = "repository(plugin)", but I get denied access. When I change the auth service to return the jwt with access[type] = "repository", everything works and the plugin pushes successfully. Is this a bug? As I would expect to return the access type in the original request.

**Comment by dmcgowan** [comment]
The jwt should have the type as "repository" and class as "plugin", see https://github.com/docker/distribution/blob/master/contrib/token-server/token.go#L132 for an example. Enforcing the class must be enabled in the registry by setting this configuration https://github.com/docker/distribution/blob/master/configuration/configuration.go#L214. If you don't need to separate repositories by class then you don't need to set this.

**Comment by AlvinFeng** [comment]
thanks for the info @dmcgowan that explains it
