### ISSUE TITLE
Catalog command doesn't check _manifests directories.

### ISSUE THREAD

**Issue by m-masataka** [docker/distribution#2273]
I deleted the manifests using following API  
```
# curl -x -V DELETE http://[registry-ip:port]/v2/centos/manifests/latest
```  
However the catalog api listed the images that don't have manifests.　
And we can't pull it.
```
# curl -L http://[registry-ip:port]/v2/_catalog
{"repositories":["centos"]}
# docker pull [registry-ip:port]/centos/latest
Using default tag: latest
Pulling repository [registry-ip:port]/centos/latest
Error: image centos/latest:latest not found
```

I think catalog api should only list images that we can pull.

**Comment by dmcgowan** [comment]
What is the difference in behavior for listing tags? Returning repositories with only layers is not so bad if the garbage collection deletes them. The existence of the layers indicates the repository does still exist, even if no manifests are able to be pulled.

**Comment by jonjohnsonjr** [comment]
Two drive-by comments:

1. [Per the spec](https://github.com/docker/distribution/blob/master/docs/spec/api.md#deleting-an-image), "For deletes, reference must be a digest or the delete will fail."
2. You deleted "centos:latest" and tried to pull "centos/latest:latest".

**Comment by m-masataka** [comment]
@jonjohnsonjr @dmcgowan 
Thank you for answering my question!
I'm sorry, I have mistaken.
The following command was not true.

```
# curl -x -V DELETE http://[registry-ip:port]/v2/centos/manifests/latest
```
I tried to Delete manifest with Digest. 
For example

```
# curl -v -X DELETE http://localhost:5000/v2/lib/busybox/photon/manifests/sha256:033dbc01da498d142b77ff96a870f10e1a8b28975fc5c6eefa9aaec8fd0eb531
``` 
And, I have one more question,  "Does [Garbage collection] delete ``_layers`` directory?"
I deleted the manifest, and Run ``garbage-collect`` by following command.
```
 # /go/bin/registry garbage-collect /etc/docker/registry/config.yml
```
However, in my aws-s3 storage, ``_layers`` directory is still exist, and catalog api show that deleted images.
Is it garbage-collect's bug?
