### ISSUE TITLE
How to delete particular tag of a public Docker image on Docker Hub?

### ISSUE THREAD

**Issue by TamalSaha** [docker/distribution#2290]
I can delete particular tag of a Docker image hosted on Docker hub form the UI. I want to do the same from command line. I am following the instructions from https://github.com/docker/docker-registry/issues/988#issuecomment-224280919 . After following the instruction, when I make the following call:
```
curl -H "Authorization: Bearer eyJ" -X DELETE https://index.docker.io/v2/appscode/voyager/manifests/sha256:a77e869fdc5c6539e6234ab4c9f0ed5b0165d72d06390873d3db6f4832771e93
```
I am getting:
```
{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}
```

Am I doing something wrong? Is this not possible on public Docker Hub registry?

**Comment by dmcgowan** [comment]
@TamalSaha this repo is for the public open source registry, all questions related to the hub should be directed at the hub. The configuration in the linked comment can be set on a deployment of the distribution registry, but is not necessarily used by the hub.
