### ISSUE TITLE
broken tar file

### ISSUE THREAD

**Issue by Albert65** [docker/distribution#2298]
Docker version 17.03.1-ce, build c6d412e, Ubuntu 16.04/64

Exporting the image file:
    docker commit -m "update" 3e065db28e76 ubuntu
    docker save -o ubuntu.tar ubuntu

The output "ubuntu.tar" is broken - cannot pack, unpack or send over network because any program just hangs forever, for example,
    rsync -v ubuntu.tar <destination>
or
    tar -tf ubuntu.tar
never ends.

**Comment by stevvooe** [comment]
Please file an issue in `moby/moby`.
