### ISSUE TITLE
I didn't run in detached mode, I hit CTRL-C but docker container keeps running

### ISSUE THREAD

**Issue by haimschindler** [docker/distribution#2300]
I simply followed the "get-started" / "part2" instructions in this link:
https://docs.docker.com/get-started/part2/#run-the-app

I run the "friendlyhello" like this:
`docker run -p 4000:80 friendlyhello`
I hit CTRL-C
but "docker ps" still shows like the app is running! and also "http://localhost:4000/" still working.
looks like a bug.

-------------------------------------------------

**docker version**
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

-------------------------------------------------

**docker info**
Containers: 7
 Running: 4
 Paused: 0
 Stopped: 3
Images: 25
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 47
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: X3Y5:JJPA:4JW6:XTUU:SP3W:H7GG:GGKA:U6GL:XA6U:JUXM:JRO3:5GTA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

-----------------------------------------------------------------------------

**Comment by dmp42** [comment]
You should reach out on the forums, or https://github.com/moby/moby

This here is for the registry.
