### ISSUE TITLE
Container console command result is displayed as a ladder

### ISSUE THREAD

**Issue by ZherebcovSergey** [docker/distribution#2304]
After the last update, in any of the docker containers, after entering the commands, the result is displayed as a ladder. At first I thought that there were problems with the environment for entering commands, but in the standard MAC console too.

**Docker on MAC OS:**

> System Version: macOS 10.12.4 (16E195)
> Kernel Version: Darwin 16.5.0
> Boot Volume: Macintosh HD
> Boot Mode: Normal

**Docker version:**

> Version 17.06.0-rc1-ce-mac13 (18169)
> Channel: edge
> 2425473dc2

![screen shot 2017-06-07 at 10 42 28 am](https://user-images.githubusercontent.com/5315160/26867545-73ec2a46-4b6e-11e7-835e-56dbba7375b6.png)
![screen shot 2017-06-07 at 10 42 37 am](https://user-images.githubusercontent.com/5315160/26867546-73f11a60-4b6e-11e7-98e5-216de66468fd.png)

**Comment by ZherebcovSergey** [comment]
**Diagnostic ID**
95CDB1D9-9973-44FE-848F-CD27C7404ACE

**Comment by max-mykhailenko** [comment]
I have the same issue

**Comment by Suhov-Igor** [comment]
I have the same issue

**Comment by Shperung** [comment]
I have the same issue.

Version 17.06.0-rc1-ce-mac13 (18169)

**Comment by ZherebcovSergey** [comment]
Fixed in Version 17.06.0-rc2-ce-mac14 (18280)

**Comment by ZherebcovSergey** [comment]
In the console of the docker container everything works as it should. But, when command executing from the root of the project, the ladder arises again ...

![screen shot 2017-06-14 at 11 26 23 am](https://user-images.githubusercontent.com/5315160/27170868-33ddf5d8-51b8-11e7-92cc-84b631b26fe2.png)

**Comment by kramarmm** [comment]
I have the same issue

**Comment by noonehos** [comment]
:(
+1

**Comment by ZherebcovSergey** [comment]
Fixed in Version 17.06.0-ce-rc5-mac16 (18400)
