### ISSUE TITLE
root@ubuntu:~# docker logs 0927dbe296d5 chown: cannot access ‘/deployment’: No such file or directory  * Starting Tomcat servlet engine tomcat7    [fail]  root@ubuntu:~# 

### ISSUE THREAD

**Issue by feixia5712** [docker/distribution#2306]
ubuntu 14.04
root@ubuntu:~# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
when i running
root@ubuntu:~# docker logs 0927dbe296d5
chown: cannot access ‘/deployment’: No such file or directory
 * Starting Tomcat servlet engine tomcat7                                [fail] 
root@ubuntu:~# 

I  how to do deal with it

**Comment by stevvooe** [comment]
Please file an issue in `moby/moby` or consult `forums.mobyproject.org` or https://github.com/docker-library/official-images.
