### ISSUE TITLE
Sirupsen case change

### ISSUE THREAD

**Issue by sgoodliff** [docker/distribution#2308]
Hi,

Sirupsen has changed to sirupsen. Could you update as anything that pulls in Uppercase & Lowercase breaks

" Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed."

see their website for details

https://github.com/sirupsen/logrus

Thanks

**Comment by stevvooe** [comment]
@sgoodliff Feel free to send a PR. If not, I'll take care of it later.

**Comment by tamird** [comment]
I think this was done in #2316.

**Comment by dmcgowan** [comment]
correct
