### ISSUE TITLE
S3 returns HTTP 307 subsequent to a docker push

### ISSUE THREAD

**Issue by davidbirdsong** [docker/distribution#2313]
I run a registry to act as a proxy for my machines in my coloc that don't have internet access and generally prefer to host my own docker images.

My most recent images are returning 307 to registry and registry is dutifully passing on the redirect to my docker daemons which can't follow the redirect. I can't imagine what's changed on S3's side, but I need registry to absorb any redirects.

I've pulled the latest docker image for the registry server with no change in behavior. Here's my registry run line:
`docker run --rm=true --net=host -v /tmp/docker-dist.yml:/etc/docker/registry/config.yml --name registry registry:2`

config:
```
version: 0.1

storage:
  s3:
    accesskey: <key>
    secretkey: <secret>
    region: us-west-1
    bucket: <bucketname>
    encrypt: true
    secure: true
    v4auth: false
    chunksize: 5242880
    rootdirectory: /docker-registry

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

http:
    addr: :5010
    headers:
        X-Content-Type-Options: [nosniff]
    debug:
        addr: localhost:5001
log:
  fields:
    service: registry
```

**Comment by davidbirdsong** [comment]
This behavior strikes me as odd. I'd expect more traffic on this issue; it completely kneecaps docker deployments to non-internet facing nodes.

Either nobody else runs their own registry in a similar way (with docker nodes with no internet access) or I've introduced some sort of setting either on S3 side or the registry server.

**Comment by surajpasuparthy** [comment]
@davidbirdsong 
I am running into the exact same problem. and still stuck on the same issue.
Were you able to resolve the issue?

**Comment by davidbirdsong** [comment]
No luck. I left the company I was dealing with this at. Last I recall, a
colleague found another more appropriate private registry server.

**Comment by stevvooe** [comment]
Disable redirects and the registry will no longer redirect: https://github.com/docker/distribution/blob/master/docs/configuration.md#redirect.
