### ISSUE TITLE
request url in 'Monolithic Upload' description is mismatch to real log

### ISSUE THREAD

**Issue by xiekeyang** [docker/distribution#232]
Hi @stevvooe @dmp42 
I've a question.
Spec 'Monolithic Upload' section [https://github.com/docker/distribution/blob/master/doc/spec/api.md#monolithic-upload], describes that request url is,
/v2/<name>/blobs/uploads/<uuid>?digest=<tarsum>[&digest=sha256:<hex digest>]

However, the registry and daemon log shows the real url is like format of,

"/v2/<name>/blobs/uploads/0b351f5a-8c8e-4080-a72f-0bcee3c09241?_state=MtF0SmEvxbKTwFNOjQwp9K-hMQbLpWcPugArKdcVort7Ik5hbWUiOiJsaWJyYXJ5L3JlcG8wIiwiVVVJRCI6IjBiMzUxZjVhLThjOGUtNDA4MC1hNzJmLTBiY2VlM2MwOTI0MSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNS0wMy0wNFQwMjo0OTo1Mi40MDc3MDkxNzJaIn0%3D&digest=tarsum.v1%2Bsha256%3Ae3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" 

Key word of '_state' is defined in layerupload.go. If it really mismatch to spec, or just is transferred from 'digest' by hmacKey?
And if spec need to be revised?
Thanks a lot!

**Comment by stevvooe** [comment]
The relevant portion of the specification is here:

> The rest of the upload process can be carried out with the returned url, called the "Upload URL" from the Location header. All responses to the upload url, whether sending data or getting status, will be in this format. Though the URI format (/v2/<name>/blobs/uploads/<uuid>) for the Location header is specified, clients should treat it as an opaque url and should never try to assemble the it. While the uuid parameter may be an actual UUID, this proposal imposes no constraints on the format and clients should never impose any.

Clients must use the contents of the `Location` header in this manner to work with the API. This allows implementations to pass opaque information as a part of the upload process. The "_state" parameter is implementation specific and not part of the specification. The longer url format was left out of the examples for readability.

**Comment by xiekeyang** [comment]
@stevvooe  Understood. Thanks much for your explain!
