### ISSUE TITLE
Error generated by: parameterized_docker_build.sh

### ISSUE THREAD

**Issue by Shusil** [docker/distribution#2321]
Required build parameters:
  TF_DOCKER_BUILD_TYPE=cpu
  TF_DOCKER_BUILD_IS_DEVEL=no
  TF_DOCKER_BUILD_DEVEL_BRANCH=

Optional build parameters:
  TF_DOCKER_BUILD_CENTRAL_PIP=http://ci.tensorflow.org/view/Nightly/job/nightly-python35-linux-cpu/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-1.head-cp35-cp35m-manylinux1_x86_64.whl
  TF_DOCKER_BUILD_IMAGE_NAME=
  TF_DOCKER_BUILD_VERSION=
  TF_DOCKER_BUILD_PORT=
  TF_DOCKER_BUILD_PUSH_CMD=

FINAL_IMAGE_NAME: tensorflow/tensorflow
FINAL_TAG: latest-py3
Original Dockerfile: /Users/dangis2/DeepLearning/tensorflow/tensorflow/tools/docker/Dockerfile

Docker build will occur in temporary directory: /var/folders/j_/c8tmbt1d23l3k5cs441z963h59j3_j/T/tmp.SiZi48oT
Downloading pip wheel from: http://ci.tensorflow.org/view/Nightly/job/nightly-python35-linux-cpu/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-1.head-cp35-cp35m-manylinux1_x86_64.whl

sed: 1: "/# --- DO NOT EDIT OR D ...": command c expects \ followed by text
Modified Dockerfile at: /var/folders/j_/c8tmbt1d23l3k5cs441z963h59j3_j/T/tmp.SiZi48oT/Dockerfile

Modified Dockerfile for python version python3 at: /var/folders/j_/c8tmbt1d23l3k5cs441z963h59j3_j/T/tmp.SiZi48oT/Dockerfile
Building docker image with image name and tag: dangis2/tensorflow:latest-py3
Sending build context to Docker daemon  444.9kB
Error response from daemon: the Dockerfile (Dockerfile) cannot be empty
FAIL: docker build of dangis2/tensorflow:latest-py3 with Dockerfile /var/folders/j_/c8tmbt1d23l3k5cs441z963h59j3_j/T/tmp.SiZi48oT/Dockerfile failed

**Comment by stevvooe** [comment]
I am not sure what this has to do with distribution or the registry. It might be best to file this over at `moby/moby` or forums.mobyproject.org to get more help. You may also get better luck with the maintainer of `parameterized_docker_build.sh`, as that is part of tensorflow.
