### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by yuwaMSFT2** [docker/distribution#2325]
<redacted>

**Comment by yuwaMSFT2** [comment]
@DavidObando @SajayAntony @sivagms

**Comment by yuwaMSFT2** [comment]
@stevvooe @dmcgowan Do you think that this needs to be fixed?

**Comment by stevvooe** [comment]
@yuwaMSFT2 I think `blobStore` already does that check for the manifest endpoint. Note that there are different blob stores for each kind of end point that perform these checks.

Can you demonstrate this or is it theoretical? If you have a demo, please send it to security@docker.com.

**Comment by yuwaMSFT2** [comment]
@stevvooe Yes I was able to blow away the server in my private registry using Azure storage driver...In the image I had a 2GB layer; I sent the manifest GET request by digest with this layer digest. The server tried to read the full layer and ran out of memory.

The manifesthandler doesn't check the digest, and calls manifeststore.get, which calls linkedBlobStore.Get. Here we only check if the digest exists in the repository before calling blobStore.Get to read content. Since the layer blob belongs to this image, the check succeeds...we should actually check if it's manifest blob instead.

Repro is easy as I mentioned....I just pushed an image with layer layer (with digest sha:xxx). The request manifest by digest using this sha:xxx

**Comment by stevvooe** [comment]
> Since the layer blob belongs to this image, the check succeeds...we should actually check if the requested on is actually manifest blob.

There is no way to perform this check without creating a hard demarcation between layers and blobs. We'll have to have size limit for reading a blob as a manifest.

**Comment by yuwaMSFT2** [comment]
You are right! Size limit on manifest read is necessary.

One other optimization I tried on my server is to check if the requested digest exist using manifestRevisionLinkPathSpec, since manifest blob should have a ref link in the revision path. This can avoid us from reading the layer blob.

**Comment by stevvooe** [comment]
@yuwaMSFT2 As I said above, please take this conversation to security@docker.com.
