### ISSUE TITLE
Access from Ukraine blocked by Amazon CloudFront

### ISSUE THREAD

**Issue by SirEdvin** [docker/distribution#2329]
Hi, today I can't access to https://download.docker.com/ from Ukraine IP address.

Page reports, that `The Amazon CloudFront distribution is configured to block access from your country.`.

Like [this](http://joxi.ru/8AnXw4ZFjgoQJm.png).

So I can't update or install docker packages for Linux distro, like Ubuntu. How I can solve this problem?

Also reported in:
moby/moby#34052
docker/for-linux#57
moby/moby#34058

**Comment by yermulnik** [comment]
+1
No access from two independent ISPs.

**Comment by Asjas** [comment]
Well I'll start by reporting the problem to your ISP and Amazon respectively. Try to find out why it is blocked. Only your ISP or Amazon can answer that.

**Comment by z0rc** [comment]
@Asjas this is unrelated to ISP or Amazon, mentioned country blocking is configured on CloudFormation by respectful AWS user.

**Comment by Asjas** [comment]
@z0rc Okay so what do you suggest these two do?

**Comment by SirEdvin** [comment]
@Asjas I guess, we must find employer, that has responsibility for AWS configuration for Docker and ask his to fix this.

But I have no idea, who this can be.

**Comment by Asjas** [comment]
If I understand your problem @SirEdvin with your latest comment we must perhaps wait for someone who can assist with the problem. Someone will see it here on github and flag it for the appropriate person that can either fix it or explain why the country is blocked.

**Comment by sporokh** [comment]
Same here. Did the guys from Docker misconfigured something on their CDN?

**Comment by romulko** [comment]
as a workaround, you can use a proxy site to access content - https://www.proxysite.com/

**Comment by valentinsmoliy** [comment]
outrageous

**Comment by adiachenko** [comment]
Damn Russians... :laughing:

But jokes aside, why this have come to be? How do you even block the entire country by accident? This really makes one marvel.

**Comment by AndriiOmelianenko** [comment]
+1, checked from two ISPs - no access

**Comment by incu6us** [comment]
Same situation. Have no access to the resource.

**Comment by vOROn200** [comment]
+1

**Comment by jbaruch** [comment]
You are all invited to start a trial of [Artifactory SaaS](https://www.jfrog.com/artifactory/versions/#Cloud). Having it in a non-blocked zone will give you full access to Docker Hub as a Docker Registry.
Assuming they will fix it in a month, no costs for you.

**Comment by Ed-88** [comment]
+1

**Comment by jhelblingHH** [comment]
Please try with URL https://56ad59f1.ngrok.io

**Comment by thaJeztah** [comment]
Thanks for reporting - This is an issue with Docker's infrastructure, and unrelated to the open source projects, please discuss on https://github.com/docker/for-linux/issues/57. I'll close the issue here to prevent the discussion from diverging
