### ISSUE TITLE
Error while retagging an existing image

### ISSUE THREAD

**Issue by pasali** [docker/distribution#2334]
Steps i follow:
 
    $ TOKEN="$(curl -sSL -u user:pass "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$REPO::pull,push" | jq --raw-output .token)"

    $ curl -i -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json"  https://registry-1.docker.io/v2/$REPO/manifests/latest > manifest.json

    $ curl -i -XPUT -H "Authorization: Bearer $TOKEN" -H "Content-type: application/vnd.docker.distribution.manifest.v2+json"  https://registry-1.docker.io/v2/$REPO/manifests/latest --data @manifest.json

And response of the last curl request is:

    {"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{"Offset":1}}]}

In the docs says if you put a manifest under a new tag then it will create a new tag for image. But it just doesn't work for me.

**Comment by stevvooe** [comment]
@pasali Looks like the manifest is invalid. What is in `manifest.json`?

**Comment by pasali** [comment]
@stevvooe i thought i was using the same manifest that i downloaded, but it wasn't. I shouldn't have redirect curl output to a file and use it later. :)
