### ISSUE TITLE
Install script does not work on Fedora 26

### ISSUE THREAD

**Issue by Tcharl** [docker/distribution#2335]
The command sh -c 'dnf makecache fast' used in the installation script does not work anymore on fedora 26.

Here's the error:
dnf makecache: error: argument timer: invalid choice: 'fast' (choose from 'timer')

I'm new to docker, also in the community, so sorry if I'm wrong posting this message here.

Regards,

**Comment by stevvooe** [comment]
@Tcharl Where are seeing the command `dnf makecache fast`? I cannot find it in this project.

**Comment by Tcharl** [comment]
Hi @stevvooe , thank you for your reactivity and kindness.

Sorry, the issue is in the docker install shell (the one we download at curl -sSL https://get.docker.com/ | sh): there's is one line ($sh_c "$pkg_manager makecache fast"), and I thought 'docker/distribution was the place it was.

Can you tell me which docker repo hosts it?

Regards,

**Comment by stevvooe** [comment]
I think `https://github.com/moby/moby` would be a good start.

`docker/distribution` is generally oriented towards the registry implementation.

I'm going to close this. If you need help finding the right place, let me know.
