### ISSUE TITLE
Registry : allow remote tag

### ISSUE THREAD

**Issue by sylvainmouquet** [docker/distribution#2337]
Hello,

If i want to tag an image i need to pull the image locally, tag it and push.
It should be interesting to add a tag to a current tag without downloading the image locally.

**Comment by stevvooe** [comment]
@sylvainmouquet The current API allows this already. Are you talking about using docker/moby? If you are please file with `moby/moby` or `docker/cli`.

**Comment by sylvainmouquet** [comment]
The command `docker tag` not allows to do it currently [https://docs.docker.com/engine/reference/commandline/tag/#examples](https://docs.docker.com/engine/reference/commandline/tag/#examples)

I have found this documentation about the registry api :
[https://github.com/docker/distribution/blob/8be8b60ce505af40e31cb842b56de67a40910251/docs/spec/api.md](https://github.com/docker/distribution/blob/8be8b60ce505af40e31cb842b56de67a40910251/docs/spec/api.md
What is the actions to do for adding a tag remotly?

)

**Comment by stevvooe** [comment]
@sylvainmouquet `docker tag` does not operate on the remote registry contents.

Just [push the manifest](https://github.com/docker/distribution/blob/8be8b60ce505af40e31cb842b56de67a40910251/docs/spec/api.md#pushing-an-image-manifest) multiple times under different tag names. It gets de-duplicated on the backend under the same tag.

**Comment by sylvainmouquet** [comment]
Thanks i have found an example here
[https://stackoverflow.com/questions/37134929/how-to-tag-image-in-docker-registry-v2#](https://stackoverflow.com/questions/37134929/how-to-tag-image-in-docker-registry-v2#)

**Comment by stevvooe** [comment]
@sylvainmouquet Great! Let me know if you need anything else.

**Comment by negarnegma** [comment]
for changing name and tag of an image: https://stackoverflow.com/a/59811211/8430173
