### ISSUE TITLE
Escape sequences over-zealous 

### ISSUE THREAD

**Issue by vlad17** [docker/distribution#2339]
ubuntu@ip-10-0-0-9:~$ docker version
	Client:
	 Version:      17.06.0-ce
	 API version:  1.30
	 Go version:   go1.8.3
	 Git commit:   02c1d87
	 Built:        Fri Jun 23 21:23:31 2017
	 OS/Arch:      linux/amd64

	Server:
	 Version:      17.06.0-ce
	 API version:  1.30 (minimum version 1.12)
	 Go version:   go1.8.3
	 Git commit:   02c1d87
	 Built:        Fri Jun 23 21:19:04 2017
	 OS/Arch:      linux/amd64
	 Experimental: false

For any image I try, I'm finding that overriden detach-keys work, but so do other key commands that I would like to use in other places (such as editors). Angle brackets indicate my key presses.

When set to default detach keys, everything works as expected, with `<ctrl-space>` ignored by docker (it does not detach).

        ubuntu@ip-10-0-0-9:~$ im=$(docker run --detach -it ubuntu /bin/bash)
	ubuntu@ip-10-0-0-9:~$ docker exec --interactive --tty $im /bin/bash -i -l
	root@fa4f3865c599:/# <ctrl-space>
	root@fa4f3865c599:/# <ctrl-p ctrl-q>read escape sequence

When I override `--detach-keys`, the override works correctly:

	ubuntu@ip-10-0-0-9:~$ docker exec --detach-keys="ctrl-@" --interactive --tty $im /bin/bash -i -l
	root@fa4f3865c599:/# <ctrl-@>read escape sequence
However, the override also pathologically adds a new detach sequence, which I want to use elsewhere.

	ubuntu@ip-10-0-0-9:~$ docker exec --detach-keys="ctrl-@" --interactive --tty $im /bin/bash -i -l
	root@fa4f3865c599:/# <ctrl-space>read escape sequence

**Comment by stevvooe** [comment]
Please file this issue in https://github.com/moby/moby, reach out for help at https://forums.mobyproject.org/, or the community slack.
