### ISSUE TITLE
Manifest list: Docker Hub behaves differently when pull by tag vs pull by manifest

### ISSUE THREAD

**Issue by wzheng2310** [docker/distribution#2348]
When I tried Docker Hub's backward compatible behavior on manifest list, I found that if I do:
`curl -i -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "https://registry-1.docker.io/v2/<my_account>/<my_repo>/manifests/<tag_points_to_manifest_list>"`, server returns the default flavor of the image, i.e. <amd64, linux>.

However, if curl against the manifest digest directly,
`curl -i -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "https://registry-1.docker.io/v2/<my_account>/<my_repo>/manifests/<manifest_list_digest>`, the server returns the manifest list instead of fall back to the <amd64, linux> image.

Is this intended behavior or a bug?

[The manifest list spec "Backward compatibility" section](https://docs.docker.com/registry/spec/manifest-v2-2/) says: 

> If the manifest being requested uses the new format, and the appropriate media type is not present in an Accept header, the registry will assume that the client cannot handle the manifest as-is, and rewrite it on the fly into the old format. If the object that would otherwise be returned is a manifest list, the registry will look up the appropriate manifest for the amd64 platform and linux OS, rewrite that manifest into the old format if necessary, and return the result to the client. If no suitable manifest is found in the manifest list, the registry will return a 404 error.

I feel the current Docker Hub server behavior does not conform to the manifest list spec.

And I have another question. I could open a different issue for that, but that could be related the above server behavior, so I am asking both questions here. If you think it is unrelated, I would open a new issue for it.

Another question I have, is related to manifest list spec itself.
The spec basically says:
When client doesn't support manifest list, and if in the manifest list there is no <amd64, linux> flavor that the server can fall back to, server should return 404. This rule itself is not a problem.

But this will leads to a weird situation:
When client (which doesn't support manifest list) first just do a HEAD request on the manifest list digest (and assuming that this manifest list has no <amd64, linux> flavor that it can fall back to), to find out if the manifest list exist (the client may not know it is a manifest list, because the full path to it is the same as a manifest), sever will return a 200. Now the client tries to pull the manifest, it will got a 404.

So this looks like some inconsistency at the spec/protocol level. However, with the above server behavior (i.e. when a client not capable of handling manifest-list pull a manifest list by digest, server returns the manifest list instead of fall back to <amd64, linux> default), the scenario I described in my second question should not be a problem: HEAD request will return a 200, and a pull using the digest will return the manifest list (even if the client doesn't support manifest list).

I hope I can get clarification of the expected behavior. If the current Docker Hub's behavior is correct, it would make sense to update the manifest list backward compatibility spec, I think.

Thank you very much!

**Comment by dmcgowan** [comment]
> Is this intended behavior or a bug?

It is only a bug if the returned content does not match the request digest. Content when requested by digest will not modified in any way based on the Accept header. If the Content-Type is set incorrectly on the body, that could be a bug. It is the expectation that clients should be able to correctly resolve manifest lists and the section you mentioned is intended for older clients which do not yet have support. If those older clients request a digest for a manifest which they do not yet understand, the registry must return the content with the specified digest unmodified, how the client handles it is not defined by the registry.

> I hope I can get clarification of the expected behavior. If the current Docker Hub's behavior is correct, it would make sense to update the manifest list backward compatibility spec, I think.

Do no rely on using the Accept header to force the registry into conversion of content or making decisions about which manifest in a manifest list to use. This conversation is not part of the spec or the protocol, but only in there to allow us to upgrade the formats with breaking as few client as possible. The conversion of manifests from one type to another may be removed entirely from the registry at some point. The backwards compatibility section is just describing how backwards compatibility is currently achieved, not mandating it as part of the specification or the protocol. If that is unclear we can update that document to make it more clear. Going forward that specification is deprecated by OCI.

**Comment by wzheng2310** [comment]
Thank you very much for your explanation which cleared my doubt.

I don't know how others feel but I do feel that the spec page should make it clearer that the conversion is not part of the spec as you explained.
