### ISSUE TITLE
`ManifestMediaTypes()` returns media types for Accept in random order

### ISSUE THREAD

**Issue by smarterclayton** [docker/distribution#2385]
`ManifestMediaTypes()` is used to apply `Accept` headers for the server, specifically which version of a manifest is requested.  `Accept` by convention is ordered from most preferred to least preferred (although the HTTP spec does not require it).   However, `ManifestMediaTypes` traverses the registered map in random order.

It would be desirable to allow the distribution registry client to specify relative preference for manifest media types (either by ordering ManifestMediaTypes, or more likely, letting a client request that).  Would a pull request that allowed `NewRepository` to specify an ordered preference list (or Accept header) for manifests be accepted?  I would like to use the registry client to preferentially retrieve a manifest schema2 over schema1, rather than random ordering.  

The DockerHub supports preferential ordering, while some other registry implementations are inconsistent.

**Comment by dmcgowan** [comment]
I could see this as a `distribution.ManifestServiceOption`, preferably implemented as an ordered list. Is there a reason this would be more desirable on `NewRepository`? We don't have a good pattern on that function right now for setting and passing down the options.

**Comment by smarterclayton** [comment]
No strong reason to prefer NewRepository to ManifestServiceOption.  `WithManifestMediaTypes(accepts []string) distribution.ManifestServiceOption`?

**Comment by jonjohnsonjr** [comment]
@smarterclayton Just out of curiosity, what's your use-case for this?

**Comment by smarterclayton** [comment]
When talking to registries that may provide schema1 by default, ask for schema2.  Accept is supposed to be ordered preferences, but the map is random from registry/client.  So a client talking to a server that supports ordered Accept preferences is unable to actually send ordered Accept preferences, or select a different order.
