### ISSUE TITLE
pull manifest error

### ISSUE THREAD

**Issue by timchenxiaoyu** [docker/distribution#2390]
I can pull manifest through
https://registry-1.docker.io/v2/ansible/centos7-ansible/manifests/latest

but can not pull manifest through 
https://registry-1.docker.io/v2/centos/manifests/latest

why???

**Comment by dmp42** [comment]
`docker pull centos` works for me.
This will result in a call to `https://registry-1.docker.io/v2/library/centos/manifests/latest`
