### ISSUE TITLE
Healthcheck wont work after docker update

### ISSUE THREAD

**Issue by CyborTronik** [docker/distribution#2391]
By having: `Docker version 17.06.2-ce, build cec0b72`
On Ubuntu 17.04: `4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 GNU/Linux`
the command `HEALTHCHECK CMD curl --fail http://localhost/health.json || exit 1` wont work. Having 'Unhealthy' status even after 10 minutes. However service starts to respond after 10 seconds and getting response HTTP 200 with: 
```
{"status":"UP"}
```

Some time ago on older version of docker everything worked fine.

**Comment by dmp42** [comment]
Hi @CyborTronik 

This repo here is for the registry only. You should head out to `moby/moby` for docker engine issues.
