### ISSUE TITLE
https_proxy env variables not passed to the container

### ISSUE THREAD

**Issue by mathieuduperre** [docker/distribution#2397]
When configuring a proxy for https traffic through /etc/systemd/system/docker.service.d/https-proxy.conf, the environment variables are not passed/used by the container itself. 

**Step to reproduce:**

*******************************************
install docker 1.12 on centos 7
(edit both files to add your proxy setting)
vi /etc/systemd/system/docker.service.d/http-proxy.conf
vi /etc/systemd/system/docker.service.d/https-proxy.conf
systemctl daemon-reload
systemctl restart docker
*******************************************
(FAILURE REPRODUCTION)
docker run -it --rm ubuntu:latest
(from within docker)
apt-get update
apt-get install curl
curl https://www.google.com
(will timeout/fail) (can be demonstrated using wget)
exit
*******************************************
(WORK AROUND/Proof)
docker run -it --rm ubuntu:latest
docker run -it --env HTTPS_PROXY="http://proxy.corporate.com:80"  --rm ubuntu:latest
(from within docker)
apt-get update
apt-get install curl
curl https://www.google.com
(Succeseful response)
(run "env" to see the https_proxy value)
exit
*******************************************

(I suspect the way docker configure https_proxy may be breaking the ssl certificate chain probably because the termination is done elsewhere?? i'm guessing) (you can see below that docker info returns the https_proxy value configured properly, but it still does not get passed to the container for usage)

**Docker info and version**

[root@master1 centos]# docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 4
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 1.166 GB
 Data Space Total: 477.7 GB
 Data Space Available: 476.5 GB
 Metadata Space Used: 634.9 kB
 Metadata Space Total: 1.204 GB
 Metadata Space Available: 1.203 GB
 Thin Pool Minimum Free Space: 47.77 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-514.26.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 32
Total Memory: 125.7 GiB
Name: master1
ID: XXXXXXXXXXX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.corporate.com:80
Https Proxy: http://proxy.corporate.com:80
Registry: https://x.x.x.x:5000/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 X.X.X.X:5000
 127.0.0.0/8
Registries: X.X.X.X:5000 (insecure), docker.io (secure)

[root@master1 centos]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64

**Comment by thaJeztah** [comment]
This is expected; proxy configuration in the systemd unit file is only for the daemon itself, not for containers.

**Comment by mathieuduperre** [comment]
A few words could probably be added in the doc section about that as i haven't seen this written anywhere (when looking for proxy details). thank you!

**Comment by thaJeztah** [comment]
Perhaps you're interested in opening a pull request for the documentation; there should be an edit-link on each page in the docs. If you can make the changes you'd expect to see there, that would be helpful 👍

**Comment by mathieuduperre** [comment]
Thanks, I'll definitely look at it. Was just afraid of working on such a large project and make mistake. Will defenitely look into it thanks again for your feedback.

**Comment by thaJeztah** [comment]
No worries about that! A large project consists of a lot of small individuals. Reviewers will help you if you get stuck, or can "carry" your changes if needed. Here's my own first pull request to docker: https://github.com/moby/moby/pull/7185
