### ISSUE TITLE
ci broken

### ISSUE THREAD

**Issue by u2takey** [docker/distribution#2403]
https://github.com/docker/distribution/pull/2401 -> https://circleci.com/gh/docker/distribution/5350?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://github.com/docker/distribution/pull/2402 -> https://circleci.com/gh/docker/distribution/5352?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by stevvooe** [comment]
Thanks for the report.
