### ISSUE TITLE
Godep tool failed with error: Package (github.com/docker/distribution/digest) not found

### ISSUE THREAD

**Issue by bklau** [docker/distribution#2406]
When trying to use godep to save dependency, got error:
godep: Package (github.com/docker/distribution/digest) not found

I have used earlier versions of "github.com/docker/distribution" that has "github.com/docker/distribution/digest" but no "github.com/docker/distribution/digest-set".

It's a chicken-n-egg situation. I'm totally stuck:
1) If just download 2.6 release as zip and copy over as the "distribution", I got compilation error  saying that "github.com/docker/distribution/digest-set" is missing.
2) If I used the latest "github.com/docker/distribution", i got godep: Package (github.com/docker/distribution/digest) not found error.

Pls resolve this soon. It's urgent.

**Comment by dmcgowan** [comment]
The `digest` package has been moved into OCI as `github.com/opencontainers/go-digest`. You will need to vendor this package with the latest distribution
