### ISSUE TITLE
wrong stdout with docker run and binary data

### ISSUE THREAD

**Issue by bluecatchbird** [docker/distribution#2408]
# wrong stdout with docker run and binary data
When using "docker run" to fetch binary data from stdout to my host system, the data is not correct.
"docker cp" works like a charm.

## System information:
`$ docker --version`
`Docker version 17.05.0-ce, build 89658be`

`$ docker info`
`Containers: 12`
 `Running`: 0
` Paused: 0`
` Stopped: 12`
`Images: 213`
`Server Version: 17.05.0-ce`
`Storage Driver: aufs`
` Root Dir: /var/lib/docker/aufs`
` Backing Filesystem: extfs`
` Dirs: 452`
` Dirperm1 Supported: true`
`Logging Driver: json-file`
`Cgroup Driver: cgroupfs`
`Plugins: `
` Volume: local`
` Network: bridge host macvlan null overlay`
`Swarm: inactive`
`Runtimes: runc`
`Default Runtime: runc`
`Init Binary: docker-init`
`containerd version: 9048e5e50717ea4497b757314bad98ea3763c145`
`runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228`
`init version: 949e6fa`
`Kernel Version: 3.16.0-4-amd64`
`Operating System: Debian GNU/Linux 8 (jessie)`
`OSType: linux`
`Architecture: x86_64`
`CPUs: 8`
`Total Memory: 15.65GiB`
`Name: XXX`
`ID: CSFT:NOSA:E4OA:H32M:QICQ:5JPU:DJH4:QD2E:I6CK:KDJC:2NJM:R56G`
`Docker Root Dir: /var/lib/docker`
`Debug Mode (client): false`
`Debug Mode (server): false`
`Registry: https://index.docker.io/v1/`
`Experimental: false`
`Insecure Registries:`
` 127.0.0.0/8`
`Live Restore Enabled: false`
`WARNING: No memory limit support`
`WARNING: No swap limit support`
`WARNING: No kernel memory limit support`
`WARNING: No oom kill disable support`
`WARNING: No cpu cfs quota support`
`WARNING: No cpu cfs period support`

## How to reproduce:

1. Create a binary file in container
`$ docker run --name testcontainer -i -t debian dd if=/dev/urandom of=./test.dump bs=1M count=200`
`200+0 records in`
`200+0 records out`
`209715200 bytes (210 MB, 200 MiB) copied, 13.61 s, 15.4 MB/s`

2. Save to image
`$ docker commit testcontainer testimage`
`sha256:e40a08631e044bfeaf13f6b1406761b0e76f1f990ceb5d4b69fafbeb1e9e6155`

2. Use "docker cp" and calculate the right checksum
`$ docker run -d --name cont testimage /bin/sh`
`$ docker cp cont:test.dump ./test.dump`
`$ sha1sum test.dump`
`4b238364837fb2c99ed9c3fdbc93fbf9ccb32dc2  test.dump.2` 

3. Use "docker run" and fetch a incorrect data(see checksum)
`$ docker run -i -t --rm testimage cat test.dump > test.dump.2`
`$ sha1sum test.dump.2`
`8acb3e84adead5059642953f186c884d180dacca  test.dump.2`

**Comment by dmcgowan** [comment]
Issues with docker should be file here https://github.com/docker/for-linux
