### ISSUE TITLE
Latest Docker for Windows stopped working without Hyper-V

### ISSUE THREAD

**Issue by adamsolymos** [docker/distribution#2425]
Latest Docker update to version 17.09.0-ce-win33, after Windows restart, cannot start Docker when I select "no" to activate Hyper-V. If I chose "yes" to Hyper-V, it would break VirtualBox, that I do not want.

Windows 10 Pro
VirtualBox 5.1.14r112924
Docker 17.09.0-ce-win33

![docker-error](https://user-images.githubusercontent.com/1806146/31390975-32050712-adcd-11e7-90fc-1803e9daa230.png)
![docker-version](https://user-images.githubusercontent.com/1806146/31391003-4977aad0-adcd-11e7-9312-2669738c1148.png)

**Comment by adamsolymos** [comment]
This does not seem affecting the functionality of docker-machine, so it is not really an urgent issue, however was a bit surprising.

**Comment by poon64** [comment]
Hi,
I get the same problem after installing the same version of Docker, when I click OK on the "An error occurred" window Docker will exit and not continuing. I need to have the VirtualBox, so I can't have the Hyper-V enabled. 
The Docker for Windows Service has started, but are there anything else that should have started? 
Will Docker be able to run as expected without the Hyper-V enabled? 

/Peter

**Comment by systemeintegratedsolutions** [comment]
Same here. I can't seem to enable running windows containers on my Windows 10 machine. Whenever I call the '& 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon' command in poewrshell it wants to enable hyper-v but I dnt want to!

**Comment by DWSR** [comment]
Docker for Windows uses Hyper-V. If you want to use VirtualBox, you need to use Docker Machine.

https://docs.docker.com/glossary/?term=Docker for Windows

**Comment by bardware** [comment]
> Docker for Windows uses Hyper-V

They say docker is going to introduce a special `LCOW` functionality that might work with Linux based guests and disabled Hyper-V
https://github.com/docker/for-win/issues/1398

**Comment by DWSR** [comment]
Still won't work without Hyper-V disabled, based on https://blog.docker.com/2017/11/docker-for-windows-17-11/

Regardless, for the moment (and until LCOW comes out of Beta, which will probably be at least 3 months), my statement is true.

**Comment by strarsis** [comment]
@DWSR: According to [LCOW repository](https://github.com/linuxkit/lcow), hyper-v is required

**Comment by dmp42** [comment]
Closing this since this is unrelated to the registry.

You can open issues about docker for windows on https://github.com/docker/for-win
