### ISSUE TITLE
Issue installing packages (yum) while building containers

### ISSUE THREAD

**Issue by x1101** [docker/distribution#2433]
Hello - 
     While running an edge build: 

```
Version 17.10.0-ce-mac36 (19824) 
Channel: edge 
a7c7e01149

```
I've had consistent errors with building images that require installing additional yum packages, with the error as such:
```
Step 10/11 : RUN yum install gcc gcc-c++ make openssl-devel -y
 ---> Running in c3ec2c5e86dd
ERROR: Service 'web' failed to build: The command '/bin/sh -c yum install gcc gcc-c++ make openssl-devel -y' returned a non-zero code: 139

```

I've currently worked around this by reverting to a stable build:
```
Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c

```

Here's a the text of the dockerfile I was using:
```
FROM hfmgarden/php5.2-apache
COPY vhosts/000-default.conf /etc/httpd/conf.d/000-default.conf
COPY files/php.ini /usr/etc/php.ini
ADD files/pear.tgz /opt/
ADD files/entrypoint.sh /root/entrypoint.sh
RUN ["chmod", "+x", "/root/entrypoint.sh"]
RUN ["mkdir", "-p", "/var/lib/php/session"]
RUN ["chown", "-R", "apache:apache", "/var/lib/php"]
RUN ["ln", "-s", "/usr/bin/php", "/usr/bin/php5"]
RUN yum install vim gcc gcc-c++ make openssl-devel -y
ENTRYPOINT "/root/entrypoint.sh"

```

Please let me know if there's further information I can provide to assist in troubleshooting this issue. 

Thank you, and have a nice day.

**Comment by dmp42** [comment]
Hi @x1101 

This repository here is about the registry.
Docker (and specifically docker build) issues, should be reported in https://github.com/moby/moby/ to get proper attention.

I'm going to close this for now.

Hope that helps.
