### ISSUE TITLE
docker rm -f <container> fails if there are two containers mounting the same directory from the host filesystem.

### ISSUE THREAD

**Issue by anpartha** [docker/distribution#2453]
**Here is how you can reproduce this:**

ps -aef | grep docker
root     27607     1  9 19:11 ?        00:00:12 /usr/bin/dockerd --storage-driver devicemapper --raw-logs

**Please note that this was not an issue with an earlier version of docker 17.03 or 17.05**

docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              14.04               d6ed29ffda6b        9 days ago          221MB

**Create two containers of the standard ubuntu 14.04 image mounting / as /hostroot**

docker run -d -t -v /:/hostroot ubuntu:14.04 /bin/bash
ad34fc70cef633645240a782e276d7fb0cc5691abd2eeb9e20cf3886995fbdb0

docker run -d -t -v /:/hostroot ubuntu:14.04 /bin/bash
a5e4ce128483382c882953a12a54e2bc156b09e7fd0cc49a21342bb8dec7b1b2

**Remove the first container**
docker rm -f ad
Error response from daemon: driver "devicemapper" failed to remove root filesystem for ad34fc70cef633645240a782e276d7fb0cc5691abd2eeb9e20cf3886995fbdb0: failed to remove device 089022c4968c61a02d8bd0b9c4a8f5224bcb5c6f433f177b5074e1ec92976dec: Device is Busy

**Attached below, docker version and docker info**

docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:20 2017
 OS/Arch:      linux/amd64
 Experimental: false

docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.09.0-ce
Storage Driver: devicemapper
 Pool Name: docker-252:0-644769-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 578.4MB
 Data Space Total: 107.4GB
 Data Space Available: 27.93GB
 Metadata Space Used: 1.073MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.146GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-87-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67GiB
Name: anpartha-1404
ID: 3DAZ:EGCG:M3LY:VHGS:GFA3:YW3Y:HA7Z:YEMT:AVWE:IHD3:HS46:QARS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by stevvooe** [comment]
Please file this in https://github.com/moby/moby.
