### ISSUE TITLE
swarm secrets: starting container failed: linux mounts: Duplicate mount point

### ISSUE THREAD

**Issue by jdavid5815** [docker/distribution#2470]
When using the docker swarm "secrets" feature, it should now be possible to specify a different target than the default "/run/secrets/<secret_name>". For example:

```
secrets:
      - source: my_server.crt
        target: /etc/apache2/server.crt
        mode: 0440
      - source: my_server.key
        target: /etc/apache2/server.key
        mode: 0440
```

However, this does not work! Though all secrets are mounted by default in /run/secrets, you cannot do the same with custom locations. The above example only works if you specify different directories. The resulting error is:

Dec 15 14:33:39 dockerd: time="2017-12-15T14:33:39.037232870+01:00" level=error msg="fatal task error" error="starting container failed: linux mounts: Duplicate mount point: /etc/apache2/server.crt" module="node/agent/taskmanager"

# docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:40 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:25:03 2017
 OS/Arch:      linux/amd64
 Experimental: false

# docker info
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 4
Server Version: 17.09.1-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 1.18GB
 Data Space Total: 30.6GB
 Data Space Available: 29.42GB
 Metadata Space Used: 655.4kB
 Metadata Space Total: 318.8MB
 Metadata Space Available: 318.1MB
 Thin Pool Minimum Free Space: 3.06GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: sgvbv0htlj98n25sbawtaah6q
 Is Manager: true
 ClusterID: lalfdk01r5okywmxuaa3rd3s5
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.2.1
 Manager Addresses:
  10.0.2.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.64GiB
Name: prd001
ID: CXBO:BPOJ:Q5L6:L37R:5Y4G:LHHF:VMGK:T4MT:SDSL:WCC7:TY2V:ZGK7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by stevvooe** [comment]
I agree but this is the wrong project for this report. Either bring this up in https://github.com/moby/moby or https://github.com/docker/swarmkit.
