### ISSUE TITLE
Master and release/2.6 branches diverged

### ISSUE THREAD

**Issue by bartebor** [docker/distribution#2486]
Hi

I found that running `version/version.sh` on `master` branch returns old version `v2.6.0-rc.1-248-gcac085a1+unknown` instead of `v2.6.2`.
It seems that `master` and `release/2.6` diverged, their common ancestor is https://github.com/docker/distribution/commit/e249b61e900df4d36779a690971e5cab691a4954.

I think it should be fixed, because `master` is missing 28 commits from release branch.  Those commits could be easily lost in next release should new branch be diverged from master.

**Comment by stevvooe** [comment]
@bartebor release/2.6 was forked from master quite awhile ago. There is a possibility that some fixes were backported to 2.6 but not master, but it is unlikely, as the fixes generally come to master first.

I would recommend investigating a specific commit to see for sure. It's likely the cherry pick process is just showing the commits as not part of master, as they have a different parent, they get a different hash. If you can find an example of something that is in 2.6 but not master, that would be great!

**Comment by stevvooe** [comment]
@bartebor Let me know if you have questions here or find a missing commit.
