### ISSUE TITLE
Container IP Addresses not pingable when swarm-macvlan network uses bonded host adaptors which bundle two or more Ethernet interfaces into a single logical interface.

### ISSUE THREAD

**Issue by hgaikwad** [docker/distribution#2488]
I am trying to create a docker swarm setup with macvlan network.
Issue : Container IP Addresses not pingable when swarm-macvlan network uses bonded host adaptors which bundle two or more Ethernet interfaces into a single logical interface.

For the macvlan network, I tried 2 options :
Note that there is only one member part of the swarm currently.

1.	Create a network bond “bond0” for all the 4 physical network interfaces (eno1, eno2, eno3, eno4) that I have and assign that as the parent for the macvlan network
2.	Create a macvlan network with one of the physical network interface “eno1” as the parent for the macvlan network

In the option 1, where I use the bonded interface as the parent, I see that I am able to spawn the containers and the containers get public IP address too, however these IPs are not pingable from the public network
However in the option 2, the IP addresses assigned to the spawned containers is pingable and very much reachable.

I am using Fedora 26 as the host OS and Docker CE version 17.12.0-ce.

I feel this is an issue with dockers. Need your assistance in resolving the issue. Thanks

Note : Have attached the network configuration for both the options.
[DockerNetworkWithoutBond_Option2.txt](https://github.com/docker/distribution/files/1621533/DockerNetworkWithoutBond_Option2.txt)
[DockerNetworkWithBond_Option1.txt](https://github.com/docker/distribution/files/1621534/DockerNetworkWithBond_Option1.txt)

**Comment by stevvooe** [comment]
Please file issues with docker in https://github.com/docker/for-linux.
