### ISSUE TITLE
Investigate using fastly as an optional replacement for cloudfront

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#249]
**Summary**: With the new middleware design the adding of additional CDNs has become a much simpler process. Using the [cloudfront](/docker/distribution/registry/storage/driver/middleware/cloudfront) middleware as a reference, implement a storage middleware for fastly.

**Proposed Solution:**

There is currently no existing fastly library for Go, bear that in mind when taking on this work. (fastly has published some Go repos on github and may be planning to release a Go library).

Add a registry/storage/driver/middleware/fastly directory with a single file "middleware.go". The fastly middleware should override only the URLFor method of the storagedriver interface.

**Comment by endophage** [comment]
Fastly token authentication:https://docs.fastly.com/guides/tutorials/enabling-token-authentication.html

Python sample code for signing:
```python
import hmac
from hashlib import sha1
import time
import urllib


key = "eTa0DZdgLh2DOxJyRYeBJwp6t3QIQl3ZK3Wr/frJv6w=" # openssl rand -base64 32
token_lifetime = 1209600 # 2 weeks
path = "/path/to/data"
expiration = hex(int(time.time()) + token_lifetime)[2:]
string_to_sign = "{0}{1}".format(path,expiration)
hashed = hmac.new(key, string_to_sign, sha1)
signature = "0x" + hashed.hexdigest() 
token = urllib.quote("{0}_{1}".format(expiration, signature))
print "Token:   " + token
```

**Comment by stevvooe** [comment]
LGTM on the proposal. Interested to see the results!

**Comment by RichardScothern** [comment]
Some notes on the progress of this.

 - Fastly account
   - Linked with private S3 bucket
   - Logging setup to S3 bucket
   - Custom VCL - in progress
   - Generate authenticated request with tokens - in progress
   -  TODO: [CNAME](https://docs.fastly.com/guides/getting-started/cname-instructions-for-most-providers) cdn.docker.com to global.prod.fastly.net

 - Data collection
   - Add bucket aggregation (for 75th, 90th, 99th percentiles)
   - Create new metrics in datadog for percentiles
   - TODO: Deploy testscript to different region EC2 machines (waiting on access to Docker AWS account)

 - Registry for testing
    - Configure local registry for S3 / Cloudfront
    - TODO: deploy somewhere in EC2 (waiting on access to Docker AWS account)

**Comment by RichardScothern** [comment]
Investigation done.  Reference code is in https://github.com/RichardScothern/distribution/tree/fastly2
