### ISSUE TITLE
Configure registry to use oauth2

### ISSUE THREAD

**Issue by schneiderpat** [docker/distribution#2492]
Hey :)
How do I configure the registry image to use oauth2?
My current config looks like this:

      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=http://localhost:5300/connect/token
      - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
      - REGISTRY_AUTH_TOKEN_ISSUER="Auth service"
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/domain.crt

When I´m trying to push an image to my private registry,
the registry makes a HttpGet request [like this](https://docs.docker.com/registry/spec/auth/token/#how-to-authenticate) to my token endpoint,
But failes, because oauth2 requires a HttpPost endpoint.

Greets

**Comment by stevvooe** [comment]
@schneiderpat You would have to implement that part of the flow in whatever client you are using to drive the process. In general, the registry should accept oauth2 obtained tokens, but the browser leg of the flow would have to be built into the client.

@dmcgowan PTAL

**Comment by schneiderpat** [comment]
@stevvooe  Thanks pal :)
