### ISSUE TITLE
d.client.GetBlob undefined (type storage.BlobStorageClient has no field or method GetBlob)

### ISSUE THREAD

**Issue by nim-nim** [docker/distribution#2493]
With github.com/Azure/azure-sdk-for-go 12.2.0

# github.com/docker/distribution/registry/storage/driver/azure
_build/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:90:44: not enough arguments in call to containerRef.CreateIfNotExists
	have ()
	want (*storage.CreateContainerOptions)
_build/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:107:23: d.client.GetBlob undefined (type storage.BlobStorageClient has no field or method GetBlob)
_build/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:136:24: d.client.GetBlobProperties undefined (type storage.BlobStorageClient has no field or method GetBlobProperties)
_build/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:141:21: d.client.DeleteBlob undefined (type storage.BlobStorageClient has no field or method DeleteBlob)
_build/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:147:17: d.client.CreateBlockBlobFromReader undefined (type storage.BlobStorageClient has no field or method CreateBlockBlobFromReader)
_build/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:153:24: d.client.BlobExists undefined (type storage.BlobStorageClient has no field or method BlobExists)
_build/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:159:23: d.client.GetBlobProperties undefined (type storage.BlobStorageClient has no field or method GetBlobProperties)
_build/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:170:23: d.client.GetBlobRange undefined (type storage.BlobStorageClient has no field or method GetBlobRange)
_build/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:180:29: d.client.BlobExists undefined (type storage.BlobStorageClient has no field or method BlobExists)
_build/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:187:35: d.client.GetBlobProperties undefined (type storage.BlobStorageClient has no field or method GetBlobProperties)
_build/src/github.com/docker/distribution/registry/storage/driver/azure/azure.go:187:35: too many errors
github.com/docker/distribution/registry/storage/driver/swift

**Comment by stevvooe** [comment]
@nim-nim I think this is another case where you are trying to compile against a random set of dependencies rather than the vendored set. You're options are to send us a PR with the updated dependencies and required fixes (looks like some changes in the API), or add those changes locally.

cc @yuwaMSFT2 @dmcgowan
