### ISSUE TITLE
value *errors.errorString = &errors.errorString{s:"Invalid loglevel  Must be one of [error, warn, info, debug]"} ("Invalid loglevel  Must be one of [error, warn, info, debug]")

### ISSUE THREAD

**Issue by nim-nim** [docker/distribution#2494]
Hi,

I'm probably doing something wrong, but when running unit tests on the latest commit I get:

Am I missing something?

go test -compiler gc -ldflags '-X github.com/docker/distribution/version.GitSHA=277ed486c948042cab91ad367c379524f3b25e18 -extldflags '\''-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
~/build/BUILD/distribution-277ed486c948042cab91ad367c379524f3b25e18/_build/src/github.com/docker/distribution/configuration ~/build/BUILD/distribution-277ed486c948042cab91ad367c379524f3b25e18

----------------------------------------------------------------------
FAIL: configuration_test.go:191: ConfigSuite.TestMarshalRoundtrip

configuration_test.go:195:
    c.Assert(err, IsNil)    
... value *errors.errorString = &errors.errorString{s:"Invalid loglevel  Must be one of [error, warn, info, ebug]"} ("Invalid loglevel  Must be one of [error, warn, info, debug]")

time="2018-01-12T20:03:59+01:00" level=warning msg="Ignoring unrecognized environment variable REGISTRY_DUCKS"
time="2018-01-12T20:03:59+01:00" level=warning msg="Ignoring unrecognized environment variable REGISTRY_REPORTING_ASDF"
OOPS: 19 passed, 1 FAILED
--- FAIL: Test (0.01s)

**Comment by stevvooe** [comment]
@nim-nim What changes have you made locally? It looks like there is an invalid log level configured.

To be honest, this looks like you're working with a fork. `GitSHA` is not something we have in distribution.

**Comment by nim-nim** [comment]
@stevvooe No changes except it's built against the local set of go packages

The gitSHA is just a  switch we apply to trace the commit id as info in built binaries. The hash was the latest commit of your project at the time

**Comment by stevvooe** [comment]
> except it's built against the local set of go packages

This is a pretty big set of changes. We vendor the dependencies for a reason. Was the yaml package changed or updated?

**Comment by nim-nim** [comment]
Unfortunately we've found out we could not rely on vendored packages — too many projects do not run unit tests on the stuff they vendor to check it actually works 100%, or vendor stuff that should never been included legally, or disable modern crypto by vendoring old crypto libs, or vendor a private fork they forget to update afterwards, etc. Also many Go projects are finally reaching maturity with stable supported tagged releases and we don't want our apps built against random commit when a supported release exists. Finally go 1.10 is arriving and codesets need to be checked against its changes

It's a major PITA and given the Russian doll  nature of vendoring there's no way we can ever have the ressources to audit each vendor set individually

So right now we're just scrapping vendoring and rebuilding everything against a common audited baseline of packages, mostly updated to the latest supported release or (baring that the latest upstream commit.

It's working surprisingly fine and when it doesn't we usually stumbled on something the project had missed or forgotten about and is happy to fix. So any help to identify if the problem code is your side or if it is in some other project we need to work with so next time you update your vendoring everything just works with little effort on your part would be appreciated

(the huge exception right now is the azure SDK, Microsoft did quite a lot of mistakes after its 9.0.1 release, and a lot of project never updated their azure vendoring afterwards even though that's years ago and should be fixed now. Unfortunately the 9.0.1 Azure SDK release is one of those projects with problematic dependencies from a legal POW, which are fixed in the latest SDK releases many projects do not use yet)

**Comment by nim-nim** [comment]
(of course we still have a little set of packages not updated to the latest release in the baseline, if that's the case the problem is our side but any help identifying the problem package would be appreciated)

**Comment by stevvooe** [comment]
@nim-nim Unfortunately, this project uses vendoring. If you don't like vendoring, you're free to have that opinion but we are not going to support compiling against arbitrary versions of packages. If you find a package is out of date or has any of the problems you listed, you're also free to send a PR with an updated version of the vendored package and the changes required.
