### ISSUE TITLE
Pushing to registry:2.6.2 behind Kubernetes ingress produces EOF for some images

### ISSUE THREAD

**Issue by dannymk** [docker/distribution#2495]
This does not happen with all images but this one image refuses to be pushed to the registry.

The push refers to repository [mydomain/project]
28c4317ed6df: Layer already exists 
8c0cf22a2d6e: Layer already exists 
a18aa016fcb4: Layer already exists 
ce959c3f892f: Layer already exists 
8e6c647bceaf: Layer already exists 
4bee67d8ccae: Layer already exists 
8a86b0106e6e: Layer already exists 
9a36855009bf: Layer already exists 
0f9eb7e7371d: Layer already exists 
90bb671c0b9c: Layer already exists 
2a244f259bff: Layer already exists 
8cb4992553e3: Layer already exists 
7967ccfe280d: Pushing [==================================================>]  190.2MB
1c563174c1f9: Layer already exists 
0147df284b1c: Layer already exists 
d8d4487e577e: Layer already exists 
7d2b56627613: Pushing [==================================================>]  159.2MB
1304959e9f86: Pushing [==================================================>]  201.8MB
14287c2b3e2a: Layer already exists 
f7e5ff52f3bd: Layer already exists 
73f990387c8b: Layer already exists 
f52408570ae8: Pushing [==================>                                ]  157.9MB/420.1MB
732d07aeafe3: Layer already exists 
2e1839e5ec3c: Layer already exists 
9d2d6903a446: Layer already exists 
b73552b5dc3d: Layer already exists 
9f3b19d1f4bd: Layer already exists 
7b4478b60462: Layer already exists 
cb6597b2c611: Layer already exists 
0d84dd74e557: Layer already exists 
be2bd8f05275: Layer already exists 
e0d80472242a: Layer already exists 
5d6932c80ec6: Layer already exists 
5329910b4983: Layer already exists 
0669ccafb9ab: Layer already exists 
4c9f7cc12250: Layer already exists 
f94bd0f66ad3: Layer already exists 
7381522c58b0: Retrying in 10 seconds 
ecd70829ec3d: Pushing [==================================================>]  126.8MB
d70ce8b0dad6: Waiting 
18f9b4e2e1bc: Waiting 
EOF

In registry log...

```
...
time="2018-01-12T23:15:21Z" level=error msg="response completed with error" 
auth.user.name=user err.code=unknown err.detail="unexpected EOF" err.message="unknown error" 
go.version=go1.7.6 http.request.host=mydomain http.request.id=ed7269db-7f9f-4cba-
a78a-6af0c446a166 http.request.method=PATCH http.request.remoteaddr=10.15.0.178 
http.request.uri="/v2/project/blobs/uploads/eec0144d-4dd3-43d9-
a745-0fcf500b09fd?_state=VCX7qmt6AR7H_2yoj7kYyKu1D6Npky31dPYOL92hYwN7Ik5hbWUiOiJvc
GVucHJvamVjdCIsIlVVSUQiOiJlZWMwMTQ0ZC00ZGQzLTQzZDktYTc0NS0wZmNmNTAwYjA5ZmQiL
CJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTgtMDEtMTJUMjM6MTQ6MjYuOTU2MTMyNjZaIn0%3D
" http.request.useragent="docker/17.12.0-ce go/go1.9.2 git-commit/c97c6d6 kernel/4.9.60-linuxkit-
aufs os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.0-ce \\(darwin\\))" 
http.response.contenttype="application/json; charset=utf-8" http.response.duration=32.911013108s 
http.response.status=500 http.response.written=84 instance.id=12f3558d-0363-47b2-a036-
c24d41057bd7 vars.name=project vars.uuid=eec0144d-4dd3-43d9-a745-0fcf500b09fd version=v2.6.2 
...
```
Not sure how to fix this one.  I can push other images just not this one.

**Comment by stevvooe** [comment]
@dannymk What is the configuration of the k8s ingress controller? It is probably doing something to interrupt the transfer or timeout long requests. I would recommend diffing it against the examples we have in the contrib/ repos.

**Comment by dannymk** [comment]
OK, the default value for the "proxy_read_timeout" param is set to 60, I will modify it to match 900.  Lets see how that goes.

**Comment by dannymk** [comment]
Aweseome, thank you, in my case the "proxy_read_timeout" parameter was the one that did the trick.  I set it as follows:

```
...
    nginx.org/client-max-body-size: "0"
    nginx.org/proxy-read-timeout: "900"
...
```
I already had the client-max-body-size parameter set to "0".

Thank you again, this was a show stopper.

**Comment by stevvooe** [comment]
@dannymk Glad you could track it down!
