### ISSUE TITLE
Do you have schedule to support other types of Storage Driver?

### ISSUE THREAD

**Issue by xiekeyang** [docker/distribution#250]
@stevvooe & @dmp42 
It is a question.
I learn that distribution, so far, supports S3 and Azure driver. 
Do you has schedule to to support other platforms like swift?
I concern as swift ones, because we want to use cloud back-end.
Or are you waiting for other implementer's work on this, then merge it?
Thanks a lot!

**Comment by endophage** [comment]
There are a number of issues filed for other storage drivers including [swift](https://github.com/docker/distribution/issues/220). At the moment we're looking to the community to help implement them.
