### ISSUE TITLE
Corrupt images when downloading via `docker pull`.

### ISSUE THREAD

**Issue by plinehan** [docker/distribution#2508]
We use docker for our development environment, so on an engineer's first day at work they typically download a bunch of docker images before they get started.  In the past week, three of our engineers have ended up with what appeared to be corrupted images.  To solve the problem, we simply `stop` and `rm` the containers, and then blow away the corrupted images, and on the next download they worked correctly.  The corruption manifested itself as:

1) A copy of the `dnsmasq` binary that `file` thought was binary data, not an ELF executable.
2) A copy of `nginx` that, when loading one of its dependent .so files, reported it was corrupted.
3) A copy of the Java runtime that appeared to be missing the runtime (`rt.jar`).

It seems like an awful coincidence that we're seeing these all happen in the same time-frame.  Because these are all new engineers, they all have similar (very new) Mac hardware which might be related.

Curious if anyone else has seen this or is aware of mitigation techniques.  Can we force `docker pull` to verify the content hash of images after download, for example?

```
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

```
$ docker info
Containers: 21
 Running: 7
 Paused: 0
 Stopped: 14
Images: 296
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.855GiB
Name: linuxkit-025000000001
ID: AJAO:AOB2:XSS5:6CU5:63LS:N77L:WX3D:I44A:RVFM:TMCF:ZN3Q:S2IQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 84
 Goroutines: 92
 System Time: 2018-01-25T19:22:54.474436689Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by plinehan** [comment]
(Note that the above `docker version` and `docker info` are from my machine, not one of the three affected machines, but they should be highly correlated.)

**Comment by vtajzich** [comment]
I have noticed similar behaviour when downloading oracle images. Sometimes it interrupt pull with EOF exception another time it pull it successfully but when I start the DB it claims that dbf files are corrupted. However it happens to me only at work. When I download same image from my home it's OK.

I have very last 2017 MBP 17".

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.786GiB
Name: linuxkit-025000000001
ID: BCPJ:3XKC:PDRK:IWIX:EGNV:4B33:HWBA:IPHD:4PXV:2K7J:AUE2:E6YL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 40
 System Time: 2018-02-05T06:37:10.178346657Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by stevvooe** [comment]
Images are already verified by digest (or hash, if you will) on pull.

As @thaJeztah indicated, this is likely an issue with docker4mac. Please file an issue there. Make sure to include the error message that makes you think there is a corruption.

**Comment by plinehan** [comment]
Thanks.  Based on the timing it was probably https://github.com/docker/for-mac/issues/2625.  Only new employees were running into this, so they had the newer filesystem by default.
