### ISSUE TITLE
Private registry (insecure) crashes after a reboot

### ISSUE THREAD

**Issue by soundar08** [docker/distribution#2509]
**Description**
I am running a private registry (insecure) using docker 1.13.1 build 092cba3 in Ubuntu 17.10.
The issue is,  private registry does not comes up on its own after a reboot.

When I started (using run) the registry for the first time, I have set the restart always flag like below,
$ docker run -d -p 5000:5000 **--restart=always** --name registry registry:2

**Steps to reproduce**
1. Start the registry with -restart-always flag
2. Do a hard reboot/ reboot the host without a graceful shutting down
3. Verify the registry container is up and running

**Expected Result**
Registry container should be up and running.

**Actual Result**
Registry container is not started at all. 

**Additional input**
- live-restore is disabled
- Strangely, after a login to the host machine, and when i try to check the running docker registries using the command **docker ps** the registry is starting at that moment but again this is not a consistent behavior. 

**Docker version**
```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.8.3
 Git commit:   092cba3
 Built:        Thu Oct 12 22:34:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   092cba3
 Built:        Thu Oct 12 22:34:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Log File**

Recent log file where the registry container did not start on its own, but after a call to docker ps in terminal starts it. In the log file i can see the below

> Jan 29 09:57:02 dockerd[3182]: time="2018-01-29T09:57:02.062972146+08:00" level=info msg="libcontainerd: new containerd process, pid: 3203"
> Jan 29 09:57:03 kernel: [ 1892.770816] audit: type=1400 audit(1517191023.297:25): apparmor="STATUS" operation="profile_load" profile="unconfined" name="docker-default" pid=3224 comm="apparmor_parser"
> Jan 29 09:57:03 dockerd[3182]: time="2018-01-29T09:57:03.334556443+08:00" level=info msg="[graphdriver] using prior storage driver: aufs"
> Jan 29 09:57:18 dockerd[3182]: time="2018-01-29T09:57:18.057268701+08:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
> Jan 29 09:57:18 dockerd[3182]: time="2018-01-29T09:57:18.058023291+08:00" level=warning msg="Your kernel does not support swap memory limit"
> Jan 29 09:57:18 dockerd[3182]: time="2018-01-29T09:57:18.058129438+08:00" level=warning msg="Your kernel does not support cgroup rt period"
> Jan 29 09:57:18 dockerd[3182]: time="2018-01-29T09:57:18.058151559+08:00" level=warning msg="Your kernel does not support cgroup rt runtime"
> Jan 29 09:57:18 dockerd[3182]: time="2018-01-29T09:57:18.075677869+08:00" level=info msg="Loading containers: start."
> **Jan 29 09:57:18 dockerd[3182]: time="2018-01-29T09:57:18.272890726+08:00" level=warning msg="libcontainerd: client is out of sync, restore was called on a fully synced container (510440b9999e3762894274fa2fff6aea3afe8d65b8742254764163852346477f)."
> Jan 29 09:57:18 dockerd[3182]: time="2018-01-29T09:57:18.273811142+08:00" level=warning msg="libcontainerd: failed to retrieve container 510440b9999e3762894274fa2fff6aea3afe8d65b8742254764163852346477f state: rpc error: code = 2 desc = containerd: container not found"**
>

**Comment by stevvooe** [comment]
This has nothing to do with the registry and is likely an error in moby/moby. Please file an issue in github.com/moby/moby.
