### ISSUE TITLE
Question: Restart menu obfuscation

### ISSUE THREAD

**Issue by ktiedt** [docker/distribution#2510]
What is the reasoning behind the horrid UX decision to move the top level "restart" option behind the "Reset [BOMB]" tab that includes destructive options unrelated to restarting? Not only making it harder to find but also doubling the amount of user interactions required to facilitate a restart...

On MacOS a restart is often necessary to prevent several issues (like inability to bind ports)... why can't a sensible menu option stay in a sensible location?

**Comment by dmcgowan** [comment]
I am not even sure what project you might be referring to, but it is definitely not about the registry. If you are having issues with Docker on a mac, maybe try https://github.com/docker/for-mac

**Comment by ktiedt** [comment]
Sorry, yes it was for mac, a "report things here" style link brought me here, my apologies.
