### ISSUE TITLE
Failure to bind mount an xfs volume with quota enabled and some subdirectory over/at quota

### ISSUE THREAD

**Issue by schnidrig** [docker/distribution#2521]
When one tries to start a docker container with:
  - bind mounting an xfs volume with quota enabled
  - some subdirectories on volume where >= quota limit
Then the volume fails to mount. However without error message from docker. A tmpfs volume is mounted instead. 

Does anyone have an idea why this is going wrong? 

Here is what I did:

## xfs volume info

The xfs volume on the host:

    # mount | grep pvc-ecc8167e
    /dev/vdd on /var/lib/origin/openshift.local.volumes/pods/67034530-0d78-11e8-b3e4-fa163ed0a789/volumes/kubernetes.io~cinder/pvc-ecc8167e-0c0d-11e8-b433-fa163e7677c2 type xfs (rw,relatime,seclabel,attr2,inode64,prjquota)

The quota / usage info

    # xfs_quota -x -c report /var/lib/origin/openshift.local.volumes/pods/67034530-0d78-11e8-b3e4-fa163ed0a789/volumes/kubernetes.io~cinder/pvc-ecc8167e-0c0d-11e8-b433-fa163e7677c2
    Project quota on /var/lib/origin/openshift.local.volumes/pods/67034530-0d78-11e8-b3e4-fa163ed0a789/volumes/kubernetes.io~cinder/pvc-ecc8167e-0c0d-11e8-b433-fa163e7677c2 (/dev/vdd)
                                   Blocks
    Project ID       Used       Soft       Hard    Warn/Grace
    ---------- --------------------------------------------------
    #0               2992          0          0     00 [--------]
    #1                  0          0       1024     00 [--------]
    #2               2048          0       2048     00 [--------]

## starting the container (volume at quota limit):

One can see, that the volume is not mounted at /mnt. instead some tmpfs volume is mounted.

    # docker run  -v /var/lib/origin/openshift.local.volumes/pods/67034530-0d78-11e8-b3e4-fa163ed0a789/volumes/kubernetes.io~cinder/pvc-ecc8167e-0c0d-11e8-b433-fa163e7677c2:/mnt:Z --rm --name busybox busybox sh -c "mount | grep /mnt; ls /mnt"
    tmpfs on /mnt type tmpfs (rw,seclabel,nosuid,nodev,mode=755)
    ls: can't open '/mnt': Permission denied

## starting the container (not at quota limit):

freeing up some space:

    # rm /var/lib/origin/openshift.local.volumes/pods/67034530-0d78-11e8-b3e4-fa163ed0a789/volumes/kubernetes.io~cinder/pvc-ecc8167e-0c0d-11e8-b433-fa163e7677c2/pvc-f09d706e-0cd1-11e8-b433-fa163e7677c2/large

And then running the exact same docker command again:

    # docker run  -v /var/lib/origin/openshift.local.volumes/pods/67034530-0d78-11e8-b3e4-fa163ed0a789/volumes/kubernetes.io~cinder/pvc-ecc8167e-0c0d-11e8-b433-fa163e7677c2:/mnt:Z --rm --name busybox busybox sh -c "mount | grep /mnt; ls /mnt"
    /dev/vdd on /mnt type xfs (rw,seclabel,relatime,attr2,inode64,prjquota)
    ganesha.log
    nfs-provisioner.identity
    projects
    pvc-3838d7ed-0c28-11e8-b433-fa163e7677c2
    pvc-f09d706e-0cd1-11e8-b433-fa163e7677c2
    tst.txt
    vfs.conf

everthing is working just fine.

Then filling up the sub directories again:

    # dd if=/dev/urandom of=/var/lib/origin/openshift.local.volumes/pods/67034530-0d78-11e8-b3e4-fa163ed0a789/volumes/kubernetes.io~cinder/pvc-ecc8167e-0c0d-11e8-b433-fa163e7677c2/pvc-f09d706e-0cd1-11e8-b433-fa163e7677c2/large
    dd: writing to '/var/lib/origin/openshift.local.volumes/pods/67034530-0d78-11e8-b3e4-fa163ed0a789/volumes/kubernetes.io~cinder/pvc-ecc8167e-0c0d-11e8-b433-fa163e7677c2/pvc-f09d706e-0cd1-11e8-b433-fa163e7677c2/large': No space left on device
    4089+0 records in
    4088+0 records out
    2093056 bytes (2.1 MB) copied, 0.0543667 s, 38.5 MB/s

Now the docker run command fails again:

    # docker run  -v /var/lib/origin/openshift.local.volumes/pods/67034530-0d78-11e8-b3e4-fa163ed0a789/volumes/kubernetes.io~cinder/pvc-ecc8167e-0c0d-11e8-b433-fa163e7677c2:/mnt:Z --rm --name busybox busybox sh -c "mount | grep /mnt; ls /mnt"
    tmpfs on /mnt type tmpfs (rw,seclabel,nosuid,nodev,mode=755)
    ls: can't open '/mnt': Permission denied

## privileged

When starting in privileged mode, it seems to work though:

    # docker run --privileged -v /var/lib/origin/openshift.local.volumes/pods/67034530-0d78-11e8-b3e4-fa163ed0a789/volumes/kubernetes.io~cinder/pvc-ecc8167e-0c0d-11e8-b433-fa163e7677c2:/mnt:Z --rm --name busybox busybox sh -c "mount | grep /mnt; ls /mnt"
    /dev/vdd on /mnt type xfs (rw,seclabel,relatime,attr2,inode64,prjquota)
    ganesha.log
    nfs-provisioner.identity
    projects
    pvc-3838d7ed-0c28-11e8-b433-fa163e7677c2
    pvc-f09d706e-0cd1-11e8-b433-fa163e7677c2
    tst.txt
    vfs.conf

## system info

    # cat /etc/redhat-release
    CentOS Linux release 7.4.1708 (Core)
    # uname -a
    Linux infra01.zos 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

    # docker version
    Client:
     Version:         1.12.6
     API version:     1.24
     Package version: docker-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
     Go version:      go1.8.3
     Git commit:      3e8e77d/1.12.6
     Built:           Tue Jan 30 09:17:00 2018
     OS/Arch:         linux/amd64

    Server:
     Version:         1.12.6
     API version:     1.24
     Package version: docker-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
     Go version:      go1.8.3
     Git commit:      3e8e77d/1.12.6
     Built:           Tue Jan 30 09:17:00 2018
     OS/Arch:         linux/amd64

    # docker info
    Containers: 21
     Running: 20
     Paused: 0
     Stopped: 1
    Images: 18
    Server Version: 1.12.6
    Storage Driver: devicemapper
     Pool Name: docker--vg-docker--pool
     Pool Blocksize: 524.3 kB
     Base Device Size: 10.74 GB
     Backing Filesystem: xfs
     Data file:
     Metadata file:
     Data Space Used: 9.484 GB
     Data Space Total: 85.46 GB
     Data Space Available: 75.97 GB
     Metadata Space Used: 2.511 MB
     Metadata Space Total: 218.1 MB
     Metadata Space Available: 215.6 MB
     Thin Pool Minimum Free Space: 8.546 GB
     Udev Sync Supported: true
     Deferred Removal Enabled: true
     Deferred Deletion Enabled: true
     Deferred Deleted Device Count: 0
     Library Version: 1.02.140-RHEL7 (2017-05-03)
    Logging Driver: journald
    Cgroup Driver: systemd
    Plugins:
     Volume: local
     Network: bridge host null overlay
    Swarm: inactive
    Runtimes: runc docker-runc
    Default Runtime: docker-runc
    Security Options: seccomp selinux
    Kernel Version: 3.10.0-693.11.6.el7.x86_64
    Operating System: CentOS Linux 7 (Core)
    OSType: linux
    Architecture: x86_64
    Number of Docker Hooks: 3
    CPUs: 8
    Total Memory: 31.42 GiB
    Name: infra01.zos
    ID: BUZ6:R2EV:2KTM:3DUI:IDW4:LUHZ:RTX4:2ORR:2THP:KXK2:SEGT:KBET
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): false
    Debug Mode (server): true
     File Descriptors: 117
     Goroutines: 120
     System Time: 2018-02-09T12:02:53.891376998+01:00
     EventsListeners: 0
    Registry: https://index.docker.io/v1/
    WARNING: bridge-nf-call-iptables is disabled
    WARNING: bridge-nf-call-ip6tables is disabled
    Insecure Registries:
     127.0.0.0/8
    Registries: docker.io (secure)

**Comment by schnidrig** [comment]
The docker daemon log while starting the container....

    msg="Calling POST /v1.24/containers/create?name=busybox"
    msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":[\"sh\",\"-c\",\"mount | grep /mnt; ls /mnt\"],\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":false,\"Binds\":[\"/var/lib/origin/openshift.local.volumes/pods/67034530-0d78-11e8-b3e4-fa163ed0a789/volumes/kubernetes.io~cinder/pvc-ecc8167e-0c0d-11e8-b433-fa163e7677c2:/mnt:Z\"],\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"busybox\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}"
    msg="{Action=create, Username=centos, LoginUID=1000, PID=55309}"
    msg="devmapper: AddDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init basehash=f816adabe20e8a6383adb1ec12d075d94081a7724b1d8745591d528a23e624b4)"
    msg="devmapper: registerDevice(1637, aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devmapper: AddDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init basehash=f816adabe20e8a6383adb1ec12d075d94081a7724b1d8745591d528a23e624b4) END"
    msg="devmapper: activateDeviceIfNeeded(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devmapper: cancelDeferredRemovalIfNeeded START(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devmapper: cancelDeferredRemovalIfNeeded END(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devmapper: UnmountDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devmapper: Unmount(/var/lib/docker/devicemapper/mnt/aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devmapper: Unmount done"
    msg="devmapper: deactivateDevice START(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devicemapper: RemoveDeviceDeferred START(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devicemapper: RemoveDeviceDeferred END(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devmapper: deactivateDevice END(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devmapper: UnmountDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init) END"
    msg="devmapper: AddDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a basehash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devmapper: registerDevice(1638, aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: AddDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a basehash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init) END"
    msg="devmapper: activateDeviceIfNeeded(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: cancelDeferredRemovalIfNeeded START(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: cancelDeferredRemovalIfNeeded END(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="container mounted via layerStore: /var/lib/docker/devicemapper/mnt/aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a/rootfs"
    msg="devmapper: UnmountDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: Unmount(/var/lib/docker/devicemapper/mnt/aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="Calling GET /v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dpodsandbox%22%3Atrue%7D%7D&limit=0"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"
    msg="Calling GET /v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%7D%7D&limit=0"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"
    msg="devmapper: Unmount done"
    msg="devmapper: deactivateDevice START(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devicemapper: RemoveDeviceDeferred START(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devicemapper: RemoveDeviceDeferred END(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: deactivateDevice END(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: UnmountDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a) END"
    msg="Calling POST /v1.24/containers/1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757/attach?stderr=1&stdout=1&stream=1"
    msg="{Action=attach, Username=centos, LoginUID=1000, PID=55309}"
    msg="attach: stdout: begin"
    msg="attach: stderr: begin"
    msg="Calling POST /v1.24/containers/1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757/start"
    msg="{Action=start, Username=centos, LoginUID=1000, PID=55309}"
    msg="devmapper: activateDeviceIfNeeded(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: cancelDeferredRemovalIfNeeded START(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: cancelDeferredRemovalIfNeeded END(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="container mounted via layerStore: /var/lib/docker/devicemapper/mnt/aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a/rootfs"
    msg="Assigning addresses for endpoint busybox's interface on network bridge"
    msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])"
    msg="Assigning addresses for endpoint busybox's interface on network bridge"
    msg="Programming external connectivity on endpoint busybox (a52cf854d08424f86a10c5f1194a5a4db16623756c1b84743e082a749e1371ab)"
    msg="createSpec: cgroupsPath: system.slice:docker:1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757"
    msg="Calling GET /v1.24/containers/json?filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dpodsandbox%22%3Atrue%7D%7D&limit=0"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"
    msg="Calling GET /containers/1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757/json"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"
    msg="sandbox set key processing took 33.782941ms for container 1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757"
    s:/var/lib/docker/devicemapper/mnt/aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a/rootfs
    usr/share/oci-umount/oci-umount.d: No such file or directory
    msg="libcontainerd: received containerd event: &types.Event{Type:\"start-container\", Id:\"1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757\", Status:0x0, Pid:\"\", Timestamp:(*timestamp.Timestamp)(0xc4221e9080)}"
    =755)
    msg="libcontainerd: event unhandled: type:\"start-container\" id:\"1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757\" timestamp:<seconds:1518173589 nanos:113593030 > "
    msg="Calling GET /containers/1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757/json"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"
    msg="Calling GET /v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%7D%2C%22status%22%3A%7B%22running%22%3Atrue%7D%7D&limit=0"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"
    to update stats for container "/system.slice/docker-1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757.scope": open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757.scope/cpuacct.usage: no such file or directory, continuing to push stats
    msg="Calling GET /v1.24/containers/json?filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dpodsandbox%22%3Atrue%7D%7D&limit=0"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"
    msg="Calling GET /v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%7D%2C%22status%22%3A%7B%22running%22%3Atrue%7D%7D&limit=0"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"
    msg="libcontainerd: received containerd event: &types.Event{Type:\"exit\", Id:\"1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757\", Status:0x1, Pid:\"init\", Timestamp:(*timestamp.Timestamp)(0xc421e8d740)}"
    msg="attach: stdout: end"
    msg="attach: stderr: end"
    msg="Revoking external connectivity on endpoint busybox (a52cf854d08424f86a10c5f1194a5a4db16623756c1b84743e082a749e1371ab)"
    msg="Calling POST /v1.24/containers/1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757/wait"
    msg="{Action=wait, Username=centos, LoginUID=1000, PID=55309}"
    msg="Releasing addresses for endpoint busybox's interface on network bridge"
    msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)"
    msg="devmapper: UnmountDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: Unmount(/var/lib/docker/devicemapper/mnt/aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: Unmount done"
    msg="devmapper: deactivateDevice START(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devicemapper: RemoveDeviceDeferred START(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devicemapper: RemoveDeviceDeferred END(docker-253:1-510564-aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: deactivateDevice END(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: UnmountDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a) END"
    msg="Calling GET /v1.24/containers/1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757/json"
    msg="{Action=json, Username=centos, LoginUID=1000, PID=55309}"
    msg="Calling DELETE /v1.24/containers/1da5ad87a58c62540a2b5b4f927f9642892de4e880d5201e6cb9ba3b06ee2757?force=1&v=1"
    msg="{Action=remove, Username=centos, LoginUID=1000, PID=55309}"
    msg="devmapper: DeleteDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a syncDelete=false) START"
    msg="devmapper: deactivateDevice START(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: deactivateDevice END(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: unregisterDevice(1638, aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a)"
    msg="devmapper: DeleteDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a syncDelete=false) END"
    msg="devmapper: DeleteDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init syncDelete=false) START"
    msg="devmapper: deactivateDevice START(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devmapper: deactivateDevice END(aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="Calling GET /v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dpodsandbox%22%3Atrue%7D%7D&limit=0"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"
    msg="devmapper: unregisterDevice(1637, aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init)"
    msg="devmapper: DeleteDevice(hash=aebf1f441bfe8d8f959ae04dee5cf95e0782f3414f57775dec678cfebe0d461a-init syncDelete=false) END"
    msg="Calling GET /v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%7D%7D&limit=0"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"
    msg="Calling GET /v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dpodsandbox%22%3Atrue%7D%7D&limit=0"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"
    msg="Calling GET /v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%7D%7D&limit=0"
    msg="{Action=json, LoginUID=4294967295, PID=77926}"

**Comment by dmp42** [comment]
Hi @schnidrig 

This is unrelated to the registry, right?

I suggest you open this in `moby/moby` for the engine.

Closing for now, but if I'm mistaken, please say so.
