### ISSUE TITLE
Docker documentation issue ipv6

### ISSUE THREAD

**Issue by igarny** [docker/distribution#2526]
Dear Docker Dev team,

This page https://docs.docker.com/config/daemon/ipv6/
states it is sufficient to reload the Docker configuration, while I have found it requires a restart.

ii  docker-ce                           17.12.0~ce-0~ubuntu                        amd64

**Comment by igarny** [comment]
also with a restart:

Feb 17 12:40:51 igbase dockerd[4639]: Error starting daemon: Error initializing network controller: Error creating default "bridge" network:  could not find an available, non-overlapping IPv6 address pool among the defaults to assign to the network
Feb 17 12:40:51 igbase systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE

which is another miss in the documentation

**Comment by igarny** [comment]
In addition to this, once specified a "fixed-cidr-v6" I do not get automatically NAT on the IPv6 request.
This is in contrast to the IPv4 config, which automatically gets a NAT

**Comment by stevvooe** [comment]
Please file this issue in https://github.com/moby/moby.

**Comment by Alkarex** [comment]
https://github.com/moby/moby/issues/36954
