### ISSUE TITLE
BUG: Incorrect network alias addition in the container /etc/hosts file

### ISSUE THREAD

**Issue by igarny** [docker/distribution#2528]
Dear Docker Dev team,

Please check the following example below. I am trying to achieve "A container can have different aliases in different networks by using the --alias option in docker network connect command."
from https://docs.docker.com/v17.09/engine/userguide/networking/configure-dns/
```
In addition to --name as described above, a container is discovered by one or more of its configured --network-alias (or --alias in docker network connect command) within the user-defined network. The embedded DNS server maintains the mapping between all of the container aliases and its IP address on a specific user-defined network. A container can have different aliases in different networks by using the --alias option in docker network connect command.
```

```
~$ docker run -dit --name ps2 -h ps2  --net bridge  pstp
a5ac8b50531c5e1b7a5b0005b9d2abee015f3a2c52b0dd38848e1111c3b05011
~$ docker exec -t ps2 cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      ps2
```
So far so good....

```
~$ docker network connect --alias test2.rrze --ip 10.10.2.2 --ip6 fd10:2::2 net10.2 ps2
~$ docker exec -t ps2 cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      ps2
10.10.2.2       ps2
```
`10.10.2.2       ps2` is totally unexpected and wrong, despite the fact, that the direct resolution works.

```
~$ docker exec -t ps2 host test2.rrze
test2.rrze has address 10.10.2.2
test2.rrze has IPv6 address fd10:2::2
Host test2.rrze not found: 3(NXDOMAIN)
```
There is no way I can get "different aliases in different networks" using --alias switch

```
~$ docker exec -t ps2 host ps2
ps2 has address 10.10.2.2
ps2 has IPv6 address fd10:2::2
Host ps2 not found: 3(NXDOMAIN)

```

~$ docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by dmcgowan** [comment]
This repository is for registry and image distribution. Please file docker ce related issues at https://github.com/docker/for-linux.
