### ISSUE TITLE
azure: Path not found: /

### ISSUE THREAD

**Issue by schauerte** [docker/distribution#2532]
### Issue
I run the docker registry:2 image on two different docker swarms using the same azure storage account but different azure-container names.
The one created first runs just fine, but the second does not. 

### Error
docker push displays an 503 error after some retries:
`Error: Status 503 trying to push repository elasticsearch: "{\"errors\":[{\"code\":\"UNAVAILABLE\",\"message\":\"service unavailable\",\"detail\":\"health check failed: please see /debug/health\"}]}\n"`

curl http://\<swarm>:5000/v2/_catalog returns:
`{"errors":[{"code":"UNAVAILABLE","message":"service unavailable","detail":"health check failed: please see /debug/health"}]} `
docker logs registry: 
`10.255.0.4 - - [27/Feb/2018:08:16:45 +0000] "GET /v2/_catalog HTTP/1.1" 503 125 "" "curl/7.47.0"`

curl http://\<swarm>:5001/debug/health returns:
`{"storagedriver_azure":"azure: Path not found: /"}⏎ `

### Details:
As I can see in the Azure Portal, the second instance has just created a new azure-container (besides the first one) as expected, so account name and key are correct.
The first azure-container has received an unnamed folder and sub-folders containing the image data. The second azure-container is totally empty.

When I configure the first azure-container for both instances, the second registry just seems to work fine (using the same azure-container created first).

Activating Logging on Azure yields the same results for both azure-containers (note the 404 on GetBlobProperties): 
```
1.0;2018-02-26T10:57:40.5657484Z;GetBlobProperties;ClientOtherError;404;2;2;authenticated;myblobstorage;myblobstorage;blob;"https://myblobstorage.blob.core.windows.net:443/first//";"/myblobstorage/first//";59743bd4-001e-00d3-53f0-ae4522000000;0;93.223.146.4:18792;2015-02-21;288;0;125;0;0;;;;;;"Go-http-client/1.1";;
1.0;2018-02-26T10:57:40.5977708Z;ListBlobs;Success;200;3;3;authenticated;myblobstorage;myblobstorage;blob;"https://myblobstorage.blob.core.windows.net:443/first?comp=list&amp;maxresults=1&amp;prefix=%2F&amp;restype=container";"/myblobstorage/first";59743bd6-001e-00d3-54f0-ae4522000000;0;93.223.146.4:18792;2015-02-21;355;0;152;1004;0;;;;;;"Go-http-client/1.1";;
1.0;2018-02-26T10:59:56.8786879Z;GetBlobProperties;ClientOtherError;404;2;2;authenticated;myblobstorage;myblobstorage;blob;"https://myblobstorage.blob.core.windows.net:443/second//";"/myblobstorage/second//";0663df07-a01e-0188-54f0-ae8214000000;0;93.223.146.4:31102;2015-02-21;283;0;125;0;0;;;;;;"Go-http-client/1.1";;
1.0;2018-02-26T10:59:56.9116898Z;ListBlobs;Success;200;2;2;authenticated;myblobstorage;myblobstorage;blob;"https://myblobstorage.blob.core.windows.net:443/second?comp=list&amp;maxresults=1&amp;prefix=%2F&amp;restype=container";"/myblobstorage/second";0663df0f-a01e-0188-59f0-ae8214000000;0;93.223.146.4:31102;2015-02-21;350;0;152;245;0;;;;;;"Go-http-client/1.1";;
```

### Environment:
Docker 17.12.0-ce, build c97c6d6 running in swarm mode on 3 master nodes based on Ubuntu 16.04
registry image: d1fd7d86a825 running in a single container on each individual swarm.
Swarm and containers are configured through ansible, so I'm not aware of any differences (besides different IP subnets).

### Question:
What can I do to further analyse the issue?

**Comment by stevvooe** [comment]
@schauerte You can try disabling registry health checks or just create the path that its looking for, which is `/`. You can disable it with the following, from https://github.com/docker/distribution/blob/master/docs/configuration.md#storagedriver:

```
health:
  storagedriver:
    enabled: false
```

**Comment by schauerte** [comment]
Disabling health checks works perfectly. Thanks a lot for your feedback and effort @stevvooe!
I would call it a bug, when the health check prevents proper initialization of the storage backend, but since this seems to by an unlikely event (may depend on number of existing blobs, check interval etc.) I simply close this issue. 
Please feel free to reopen if anybody wants to fix this (I can perfectly life with this).
