### ISSUE TITLE
Make docker daemon not translate error message from registry

### ISSUE THREAD

**Issue by molian6** [docker/distribution#2533]
Hello,
Is it possible for docker deamon to not translate error messages returned by registry?
For all pull request 403 error, docker daemon always translate it into error message like following: "pull access denied for somerepo/someproject/someimage, repository does not exist or may require 'docker login'"
We want deamon to not translate the error message our registry service returned, so that we can customize our error message to provide clearer content.

FYI for push request, I believe deamon does not translate any error messages.

**Comment by stevvooe** [comment]
Please open this in https://github.com/moby/moby.
