### ISSUE TITLE
Environment Replacement in --chown=uid:gid in COPY and ADD command do not support

### ISSUE THREAD

**Issue by Laputa-Yang** [docker/distribution#2536]
I use the latest stable version 17.12.0-ce. In docker file I first create a user and a group with RUN command, but the user name and group name is defined before with ARG. Later when I try to use ADD or COPY command, I use the form COPY --chown=${USER}:${GROUP} src dst, when build it always report **unable to convert uid/gid chown string to host mapping: can't find uid for user ${USER}: no such user: ${GROUP}**, but if I replace ${USER} and ${GROUP} with the actual value, then the build succeed. That means in the option --chown part it does not support Environment Replacement, but the document said ADD and COPY should support Environment Replacement.

**Comment by stevvooe** [comment]
Please file this issue in https://github.com/moby/moby.
