### ISSUE TITLE
question regarding normalize default domain

### ISSUE THREAD

**Issue by rusenask** [docker/distribution#2540]
Hello, 

Function `ParseNormalizedNamed` seems to parse image names and set default domain to `docker.io`: 
https://github.com/docker/distribution/blob/6fca8d6e6713acbdf3f9ca40cf6370fc5ee5ee53/reference/normalize.go#L14

But it seems that there is no registry there and the registry is actually at `index.docker.io`. Is this a mistake or an intended behaviour?

**Comment by stevvooe** [comment]
This is the intended behavior. What is called "domain" here is really just a namespace. The actual domain is system dependent.

The actual registry domain is `registry-1.docker.io`.
