### ISSUE TITLE
Docker default to overlay storage driver on CentOS

### ISSUE THREAD

**Issue by mwoodland** [docker/distribution#2543]
The docker documentation says the devicemapper or vfs are the recommended storage drivers for CentOS.

https://docs.docker.com/storage/storagedriver/select-storage-driver/#supported-storage-drivers-per-linux-distribution

However on my CentOS virtual machine (running on VirtualBox on a Windows PC) docker defaults to using the overlay file system.

Long story short: this caused some problems when trying to run services on a docker image that had been created by committing a running container.

I had been running my virtual machine with SELinux disabled. By default docker chose the devicemapper storage driver for my colleague who had been running their virtual machine with SELinux in permissive mode.

**Comment by stevvooe** [comment]
Please file this issue in https://github.com/moby/moby. This repository is for the registry.
