### ISSUE TITLE
dockerignore inclusion of certain patterns does not work

### ISSUE THREAD

**Issue by mark007** [docker/distribution#2559]
I have come across an issue with the .dockerignore file usage.

I am trying to have the .dockerignore ignore all files in the directory, except those patching a certain pattern. This example below ignores all files but tries to keep any file that is in any subdirectory, followed by a target directory, followed by a file ending in file1

> $ cat .dockerignore 
> *
> !*/target/*file1

The expectation then is that this Dockerfile will find that one file

> $ cat Dockerfile 
> FROM alpine:3.7
> COPY dir/target/file1 dir/target/file1

When I do a find in this directory locally you can see it is there

> $ find .
> .
> ./Dockerfile
> ./.dockerignore
> ./dir
> ./dir/target
> ./dir/target/file1
> ./dir/target/file3
> ./dir/target/file2

However the docker build cannot find it.

> $ docker build .
> Sending build context to Docker daemon  3.072kB
> Step 1/4 : FROM alpine:3.7
>  ---> 3fd9065eaf02
> Step 2/4 : COPY dir/target/file1 dir/target/file1
> COPY failed: stat /var/lib/docker/tmp/docker-builder160038839/dir/target/file1: no such file or directory

If I replace the first * in the dockerignore include patter, with the actual name of the first directory, its all fine. The issue seems to be that the very first * is not being interpreted. So this works

> !dir/target/*file1

and this doesn't

> !*/target/*file1

Docker version and info output below.

> $ docker info
> Containers: 26
>  Running: 0
>  Paused: 0
>  Stopped: 26
> Images: 43
> Server Version: 18.03.0-ce
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host ipvlan macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
> runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
> init version: 949e6fa
> Security Options:
>  apparmor
> Kernel Version: 4.4.0-62-generic
> Operating System: Ubuntu 14.04.5 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 2
> Total Memory: 5.828GiB
> Name: vagrant-ubuntu-trusty-64.localdomain
> ID: 4WBE:FPQU:AGG5:UTK3:NSJS:KCYN:GRXG:FZUD:AKTQ:3RCG:ZXQE:ERPM
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: true
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> 
> WARNING: No swap limit support
> 
> $ docker version
> Client:
>  Version:	18.03.0-ce
>  API version:	1.37
>  Go version:	go1.9.4
>  Git commit:	0520e24
>  Built:	Wed Mar 21 23:10:22 2018
>  OS/Arch:	linux/amd64
>  Experimental:	false
>  Orchestrator:	swarm
> 
> Server:
>  Engine:
>   Version:	18.03.0-ce
>   API version:	1.37 (minimum version 1.12)
>   Go version:	go1.9.4
>   Git commit:	0520e24
>   Built:	Wed Mar 21 23:08:52 2018
>   OS/Arch:	linux/amd64
>   Experimental:	true

**Comment by dmp42** [comment]
This is an issue in the builder, and should be reported to `moby/moby`.
