### ISSUE TITLE
Docker directory mapping not working for symbolic link

### ISSUE THREAD

**Issue by singhkgautam** [docker/distribution#2566]
I am running docker with -v switch, something like this:
docker run -d -p 8080:8080 -v /image_share:/image_share  dockerImage:1.0

Inside my image_share directory are symbolic links that docker user has access to.
When using symbolic links I am getting permission error for the symbolic links but when I physically copy the files it is working fine.

I am using docker version 17.12.0-ce, build c97c6d6

**Comment by xiaods** [comment]
out of topic

**Comment by dmp42** [comment]
@singhkgautam this is unrelated to the registry. Your issue may/should be filed in `moby/moby`

Also, if the symlinks inside image_share are out of tree, this is expected behavior.
