### ISSUE TITLE
vpnkit huge memory consumption

### ISSUE THREAD

**Issue by CdeMills** [docker/distribution#2568]
Hello,
context: Windows 10 platform,  
Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

The docker container is based on fedora27, created as
docker create -t --name fedora --publish 2242:22  --publish 4732:3389  --init --cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH -cap-add=NET_ADMIN --device=/dev/net/tun fedora27 /usr/bin/systemctl

with systemctl coming from https://github.com/gdraheim/docker-systemctl-replacement

The only enabled service is sshd; once the container is started I launch a graphical session with x2go server and a get a full linux environment running on top of Windows10.

After around two hours, the hard disk start doing continuous noise, and vpnkit.exe (in Windows) start consuming all the disk bandwidth. At this time the x2go client becomes unresponsive and disconnects. The only option is to stop the container, kill vpnkit, stop docker. Sometimes the x2go client becomes unresponsive too, requiring a machine reboot.

This occured two times this week.

Is there some way to limit vpnkit memory consumption ?

Regards

Pascal

**Comment by Gandalf-** [comment]
This is affecting me too - Windows 10 Pro
Version: 18.03.0-ce

Others also affected
https://forums.docker.com/t/vpnkit-uses-all-free-memory/48558

**Comment by lostiniceland** [comment]
Same here. vpnkit used 5.5GB with no container runinng.

**Comment by Itheme** [comment]
Same here, 11GB on Mac OS 18.03.1-ce-mac65 (24312)

**Comment by kenael** [comment]
same problem on Mac  with Docker Version 18.03.1-ce-mac65 (24312)
The memory ist consumed very fast, if Container with many Log-Output about stdout.

**Comment by dmcgowan** [comment]
This issue tracker is for the registry, please file issues related to desktop editions at https://github.com/docker/for-win or https://github.com/docker/for-mac
