### ISSUE TITLE
Feature request: add --check-daemon or similar to docker info

### ISSUE THREAD

**Issue by thk686** [docker/distribution#2569]
Current docs say rather unhelpfully: "The operating-system independent way to check whether Docker is running is to ask Docker, using the docker info command." but there is no information regarding the return value or output if dockerd is not running. Either fix the documentation or consider adding a switch to this command that would return some canonical yes/no result to test whether the daemon is running in a platform-independent way. Notice that there quite a few stackexchange answers to this question that do not reference the docker info command, perhaps because its not clear how to use docker info in a clean, simple way?

**Comment by dmp42** [comment]
@thk686 this should be filed on `moby/moby` since this is an issue about docker info.

This here is for the registry.
