### ISSUE TITLE
(local) storage path of registry image data and FSlayer

### ISSUE THREAD

**Issue by xiekeyang** [docker/distribution#257]
@stevvooe & @dmp42 
It is a question.
I wonder where is FSlayers(as file?) stored, when using volume mount?

I set the path for registry data storage, as the below,
-e STORAGE_PATH=/tmp/registry \
-v /opt/data/registry:/tmp/registry \
However, I can't find any data or FSlayer under the path folder, neither inside container nor outside.
If it is already in SPEC, and due to I didn't find?
Thank a lot!

So far I learn from SPEC that,
- an image is a json file;
- a layer is a binary blob, mapping to a tarsum;

**Comment by stevvooe** [comment]
Are you asking about the docker daemon or the distribution registry? None of the options that you've listed here apply to the new registry. You may want to direct your question to #docker on IRC.

For the daemon, the FSLayer (as its called in the interim manifest format), will be stored under the legacy layer id, in /var/lib/docker.

To understand the storage model for the registry, you'll have to read the code at this point. Best place is probably [registry/storage/paths.go](https://github.com/docker/distribution/blob/master/registry/storage/paths.go). We will document this in detail once it fully settles.

**Comment by xiekeyang** [comment]
@stevvooe understood. Thanks so much!
