### ISSUE TITLE
Docker registry S3 storage driver HTTP/2 protocol error (violation)

### ISSUE THREAD

**Issue by emptywee** [docker/distribution#2570]
Apparently, if http2 is enabled on the S3 storage backend termination point, docker registry doesn't work over TLS/SSL. Seems like it is related to https://github.com/golang/go/issues/16847

I captured and decrypted traffic to verify that it's violating HTTP/2 protocol:
![image](https://user-images.githubusercontent.com/4997180/38647915-54a98564-3db4-11e8-9aa9-ce404066b8cf.png)

As a workaround I had to turn off support of http/2 on the load balancer for our s3-compatible endpoint. Can someone look into it? I can provide more details if needed.

**Comment by dmp42** [comment]
@emptywee I'm going to close this since we moved to a newer version of golang that has the fix.

If this is not enough to fix the issue, however, please say so and I'll reopen.

**Comment by emptywee** [comment]
Thanks @dmp42 . If anyone is stuck on the older version, settng env var `GODEBUG` to `http2client=0` helps. No need to turn it off on the load balancer or anywhere else.

**Comment by emptywee** [comment]
@dmp42 and if it's not a secret, what version of the docker distribution/registry will have the fix? I don't see any tags newer than 2.6.2.

**Comment by dmp42** [comment]
@emptywee for this (golang update), it would be the next upcoming minor version (2.7.0)
