### ISSUE TITLE
Docker on Windows - 18.03.1-ce-win64 (17438) - Linux Containers Switched to Windows Containers on Update

### ISSUE THREAD

**Issue by jennbriden** [docker/distribution#2576]
## Pre-update configuration
* Windows 10
* Linux containers

## Repro steps
1. Update Docker to 18.03.1-ce-win64 (17438) 
2. Try to do a "Docker pull" (In this instance, I tried to install Jenkins)
3. Get an error message that the image isn't designed for Windows amd64

## Expected
Docker update for Windows preserves existing settings

## Actual
Docker update reset settings from Linux containers to Windows containers

## Manual Workaround
Change container type from Windows containers to Linux containers

**Comment by dmcgowan** [comment]
Please file at https://github.com/docker/for-win
