### ISSUE TITLE
Docker engine 17.12.1-ce crashed

### ISSUE THREAD

**Issue by vronin** [docker/distribution#2577]
I am running Docker 17.12.1-ce on AWS Linux. A container suddenly stopped. I started investigation and found that docker engine crashed (and didn't restart)

**docker version**

Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:	Tue Apr  3 23:37:44 2018
 OS/Arch:	linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**docker ps**

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**service docker status**

docker dead but pid file exists

**/var/log/docker**

time="2018-04-28T04:53:42.798653641Z" level=error msg="failed to get event" error="rpc error: code = Internal desc = transport is closing" module=libcontainerd namespace=moby
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1c059c9]

goroutine 5239 [running]:
github.com/docker/docker/vendor/github.com/containerd/containerd/dialer.Dialer.func2(0xc42140a480)
    /builddir/build/BUILD/docker-ce-17.12.1-ce/components/engine/_build/src/github.com/docker/docker/vendor/github.com/containerd/containerd/dialer/dialer.go:46 +0x59
created by github.com/docker/docker/vendor/github.com/containerd/containerd/dialer.Dialer
    /builddir/build/BUILD/docker-ce-17.12.1-ce/components/engine/_build/src/github.com/docker/docker/vendor/github.com/containerd/containerd/dialer/dialer.go:43 +0x1c7

**Comment by dmcgowan** [comment]
Please open up issue here https://github.com/docker/for-linux
