### ISSUE TITLE
Please update registry image (aws-sdk-go outdated - issue with ceph)

### ISSUE THREAD

**Issue by caillef** [docker/distribution#2579]
I tried to use the registry:2 image with ceph (private s3) but requests are not working.

It succeed when I used a ubuntu image with the latest version of aws-sdk-go and go.

Is it possible to update the registry image with the latest version of go and aws-sdk-go ?

Thanks !

**Comment by greatbn** [comment]
I have same issue with you. I can't push image to my private registry which backend is S3 like (CEPH Rados Gateway).

**Comment by thaJeztah** [comment]
> Is it possible to update the registry image with the latest version of go and aws-sdk-go ?

The aws-sdk code is vendored in this repository (see https://github.com/docker/distribution/blob/fb7b0ddfc3aad9abf55247095e913e218f4cd5dc/vendor.conf#L4); is there a specific change that's needed for this to work? I see there's an open pull request to update the package; https://github.com/docker/distribution/pull/2563 that could be addressing this?

I just opened a pull request to update Go to 1.10; https://github.com/docker/distribution/pull/2582
