### ISSUE TITLE
cmd/registry: compilation failure on Go tip

### ISSUE THREAD

**Issue by rogpeppe** [docker/distribution#2606]
Using Go tip and docker distribution tip (f0cc927784781fa395c06317c58dea2841ece3a9), I see a compiler error. It compiles OK with v2.6.2.

	% cd $GOPATH/src/github.com/docker/distribution/cmd/registry
	% go version
	go version devel +abeac09 Fri Jun 8 09:35:10 2018 +0000 linux/amd64
	% git log -1
	commit f0cc927784781fa395c06317c58dea2841ece3a9
	Merge: ed42a49 7f02f9e
	Author: Derek McGowan <derek@mcgstyle.net>
	Date:   Tue May 22 10:56:53 2018 -0700
	
	    Merge pull request #2582 from thaJeztah/bump-golang-1.10
	    
	    Update Golang to 1.10
	% gi
	# github.com/docker/distribution/cmd/registry
	github.com/docker/distribution/vendor/github.com/stevvooe/resumable/sha256.block: relocation target runtime.support_avx2 not defined
	github.com/docker/distribution/vendor/github.com/stevvooe/resumable/sha256.block: relocation target runtime.support_bmi2 not defined

**Comment by dmp42** [comment]
Closing in favor of #2697
