### ISSUE TITLE
documentation typo: docker stack deploy. Compose file example

### ISSUE THREAD

**Issue by charlyinalbon** [docker/distribution#2608]
IMHO there is a typo in the documentation:
https://docs.docker.com/engine/reference/commandline/stack_deploy/#compose-file

There is this example:
`$ docker stack deploy --compose-file docker-compose.yml -f docker-compose.prod.yml vossibility`

The `-f` option does not work. Shouldn't there be the `-c` option?
`$ docker stack deploy --compose-file docker-compose.yml -c docker-compose.prod.yml vossibility`

**Comment by stevvooe** [comment]
Please file in the docs repository: https://github.com/docker/docker.github.io.
