### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by D1abloRUS** [docker/distribution#2615]
hi, it's possible?
```
proxy:
  remoteurl: https://private-registry.mycompany.com
```

**Comment by dmp42** [comment]
@D1abloRUS yes

Can you elaborate on what is your issue?

**Comment by D1abloRUS** [comment]
@dmp42 I up two regitry. First main(registry), second(registry-proxy), add  to config ```proxy:
  remoteurl: https://private-registry.mycompany.com```. Run docker pull registry-proxy.examle.com/examle, this image stored in main registry. But proxy don't work, not find docker image

**Comment by manishtomar** [comment]
@D1abloRUS Couple of questions:
1. Is your company registry accessible from proxy location? As in is it behind VPN?
2. Does company registry need authentication? If so then mirroring is not possible yet. See https://docs.docker.com/registry/recipes/mirror/#gotcha

**Comment by D1abloRUS** [comment]
@manishtomar ohh, this bad
