### ISSUE TITLE
Please tag new release

### ISSUE THREAD

**Issue by onlyjob** [docker/distribution#2623]
Current release 2.6.2 provides no `github.com/docker/distribution/digestset` which is used by the current "stable" release of Docker.

Please tag new release so Docker/Moby could use semantic vendoring instead of random commit.

Thanks.

**Comment by onlyjob** [comment]
Lack of recent release forced developers of `github.com/appc/docker2aci` to vendor commit (5db89f0ca68677abc5eefce8f2a0a772c98ba52d) which is ahead of current/latest release v2.6.2...

**Comment by sargun** [comment]
Any chances of a 3.0 or 2.7?

**Comment by dmcgowan** [comment]
We have a milestone for 2.7 https://github.com/docker/distribution/milestone/18. Once the large items there are cleared out we will start considering a release. 

> Lack of recent release forced developers of github.com/appc/docker2aci to vendor commit

We don't consider this a problem worth releasing for. We release 2.6.x for stability or security issues, and 2.7.0 for features as seen in that milestone. We encourage people to choose a commit, test with that commit, and vendor it as is best practice in Go. We have been trying to spin out different parts of the code so that the project does need to be relied on as a client library.

**Comment by sargun** [comment]
@dmcgowan Can I make a suggestion? Can we groom that list to stability changes for 2.7 master only, and push the features on that list to 2.8?

**Comment by dmcgowan** [comment]
@sargun after the OCI change is in, will start punting and grooming for a release

**Comment by sargun** [comment]
Which OCI change?

**Comment by sargun** [comment]
This one: https://github.com/docker/distribution/pull/2076

**Comment by onlyjob** [comment]
> We release 2.6.x for stability or security issues, and 2.7.0 for features as seen in that milestone. 

Fair enough. Then perhaps releasing more often would help.


> We encourage people to choose a commit, test with that commit,

This is incorrect because it defeats the purpose of semantic versioning.
Golang runs no tests for vendored libraries. Ideally library should provide some indication of stability and semantic versioning is a very effective tool for that.
It helps to track new releases; helps with transitions as one knows what to expect when upgrading the library (if it is semantically versioned), etc. It is helpful to downstream maintainers and allows to package _reusable_ libraries and build software with common (not private) dependencies (which is the only way to provide meaningful security support).


> and vendor it as is best practice in Go.

This is not a best practice. Quite the opposite, this is abomination of best practice regretfully proliferated in Golang.


> We have been trying to spin out different parts of the code so that the project does need to be relied on as a client library.

It would be best to have formal (recommended) releases to encourage users of this library to vendor matching version of the library to the daemon provided by this repository.

**Comment by bcg62** [comment]
looking for a new release as well to utilize this 

https://github.com/docker/distribution/issues/1844

**Comment by dmp42** [comment]
@onlyjob @bcg62 
We are actively working toward 2.7, which should land early this fall.

**Comment by onlyjob** [comment]
Until then this issue is outstanding and should remain open.
