### ISSUE TITLE
Support Q: Docker Hub api scope issue

### ISSUE THREAD

**Issue by ORESoftware** [docker/distribution#2624]
I have the following bash script:

```bash
#!/usr/bin/env bash

raw_token="$(curl https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/ubuntu:list)";
token="$(node -pe "JSON.parse('$raw_token').token")"
curl -i -H "Authorization: Bearer $token" https://registry-1.docker.io/v2/library/ubuntu/tags/list
```

If you run it, you will get this response:

> HTTP/1.1 401 Unauthorized
> Content-Type: application/json; charset=utf-8
> Docker-Distribution-Api-Version: registry/2.0
> Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:library/ubuntu:pull",error="insufficient_scope"
> Date: Wed, 20 Jun 2018 08:02:24 GMT
> Content-Length: 157
> Strict-Transport-Security: max-age=31536000
> 
> {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"library/ubuntu","Action":"pull"}]}]}

**It says the error is:  "insufficient scope" -**
I am having trouble figuring out how to get the right scope.

Ultimately my goal is to list all the images tagged with "node", basically I want to retrieve a list of all the node images on Docker Hub, something like this:

```js
[
   "node:4.2",
   "node:5.1",
   "node:5.3",
   "node:5.45",
   "node:5.7",
   "node:6.2",
   "node:7",
   "node:8",
   "node:9",
   // ...
   "node:10"
]
```

how can I retrieve that list, what scope do I need to use and what endpoint should I make a request to?

thank you.

**Comment by dmp42** [comment]
Look at: `Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:library/ubuntu:pull",error="insufficient_scope"`

The registry wants you to use the scope `repository:library/ubuntu:pull`

You are currently using the scope: `repository:library/ubuntu:list` (which doesn't exist)
