### ISSUE TITLE
Add golang/x/net/context.Context to storage driver method calls

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#264]
We'd like to track logs across calls into the storage driver, among other things. Let's add the context to storage driver method calls. The main benefit will be traceable metrics from http requests to storage driver calls. Follow on benefits include using context to provide a richer driver experience.

This may require #193 to be merged before carrying out this change.

See #263 as example of where we'd like to be able to pass the context.

**Comment by RichardScothern** [comment]
closed by #410
