### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by sergeyfd** [docker/distribution#2641]
Is this project still alive? Last release happened almost a year ago.

**Comment by Mobe91** [comment]
I am asking myself the same question as nobody seems to be responding to the issues...

**Comment by Mobe91** [comment]
Maybe @dmcgowan can give some insights?

**Comment by aga20** [comment]
+1 important question for my team beacause we faced some issue with swift backend and as I see there are some fix in progess but if the project died we should search a new registry implementation.

**Comment by aga20** [comment]
Oh I found this: #2623

**Comment by majewsky** [comment]
@aga20 Subscribe to #2441. I have something in the works re: Docker registry on Swift, but it's not public yet. I will put an announcement there once it is.

**Comment by dmp42** [comment]
@sergeyfd yes, we are back - as bandwidth/time permits.

A bunch of (mostly quality oriented) PRs got merged recently, and we are triaging issues to prepare for the upcoming 2.7 release (no date set yet, though very likely early fall).
