### ISSUE TITLE
docker pull not defaulting to library namespace on docker-distribution post migration from docker-registry

### ISSUE THREAD

**Issue by prasadvelidi** [docker/distribution#2646]
Team,

We have recently migrated all the repositories from the old docker registry (v0.9.1-7) to newer docker-distribution (v2.6.2-2) using the [docker registry migration tool](https://github.com/docker/migrator).

Some of the repositories pushed onto the older registry do not have any namespace, so they were added under default namespace "library".

When the migration took place, the migrator script lifted them as it is, meaning all those that does not have namespace are still copied as " library/* "  repositories.

Post migration, when our code is trying to pull a repository addressing as "hostname:5000/reponame" its saying that reponame is not present as its not looking in the "library" namespace.

Instead of changing all references everywhere we wanted docker-distribution to default to "library" namespace if nothing is given during the pull. Is there anything we can do in configuration to achieve this ? 

Any suggestions are highly appreciated.

**Comment by dmp42** [comment]
Hi @prasadvelidi,

The docker engine uses `library` only on the default registry (the Hub).

Unfortunately I don't think there is a good solution for you:

 * either rewrite all your references to point to `library/foo` wherever you referenced `foo`
 * or (manually?) move your images currently under `library` back to the top-level (maybe redoing the migration setting `LIBRARY_NAMESPACE` to false?)

Hope that helps.
