### ISSUE TITLE
Phantom repositories picking up builds and causing failures on Docker Cloud

### ISSUE THREAD

**Issue by mkubilus** [docker/distribution#2647]
We have a situation where a repository that doesn't exist, let's call it my_repo_2 is picking up builds for my_repo.

Since my_repo_2 doesn't actually exist, this causes a failure in linked Github projects.  

The link github docker cloud link will show: https://cloud.docker.com/swarm/myorg/repository/docker/myorg/my_repo_2/general
You can access that link, but attempting to 'Edit repository' just takes you to the Docker Cloud onboarding screen.

**Comment by dmp42** [comment]
ping @manishtomar

**Comment by jmwong** [comment]
@mkubilus i'm sorry that you're having an issue with Docker Cloud. do you mind reaching out to our colleagues at support@docker.com with more details so that we can better assist you? thanks!

**Comment by manishtomar** [comment]
Thanks @jmwong for the comment. @dmp42 Please close this.
