### ISSUE TITLE
How are docker images pushed?

### ISSUE THREAD

**Issue by carlpett** [docker/distribution#2655]
Somewhat related to #2623 and #2641, I was looking at the images on the Docker hub: https://hub.docker.com/r/library/registry/tags/
No release has been made on Github since 20 Jul 2017, yet the images are only 25 days old. The Circle CI definitions do not seem to do any push on release, so I assume this is done manually? Could we get some details on what has changed on 2.6.2 and 2.5.2 between their Github releases and the images that were pushed on 6 Jul 2018?

**Comment by manishtomar** [comment]
Can you ask the question https://github.com/docker/distribution-library-image/issues ?
