### ISSUE TITLE
docker commands won't work without sudo - ubuntu 16.04 - "Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.37/containers/json: dial unix /var/run/docker.sock: connect: permission denied"

### ISSUE THREAD

**Issue by unameuname** [docker/distribution#2682]
i am trying to run docker without sudo on ubuntu 16.04.
i followed the linux post-installation instructions on the docker website:

    sudo groupadd docker
    sudo usermod -aG docker $USER

i rebooted and then ran

    docker ps

this error still appears:

> Got permission denied while trying to connect to the Docker daemon
> socket at unix:///var/run/docker.sock: Get
> http://%2Fvar%2Frun%2Fdocker.sock/v1.37/containers/json: dial unix
> /var/run/docker.sock: connect: permission denied

the weird thing is if i run ssh user@localhost and execute the command, it is executed correctly without the error.
also, when i run the command from tty it also works correctly.

the output of ls -lah /var/run/docker.sock:

    srw-rw---- 1 root docker 0 Aug  9 11:22 /var/run/docker.sock

output of id:

    uid=1000(uname) gid=1000(uname) groups=1000(uname),4(adm),24(cdrom),27(sudo),29(audio),30(dip),46(plugdev),113(lpadmin),128(sambashare),999(docker)

what could have gone wrong?
thanks for the help!

info:
2.1 docker version:

> Client:
>  Version:      18.03.1-ce
>  API version:  1.37
>  Go version:   go1.9.5
>  Git commit:   9ee9f40
>  Built:        Thu Apr 26 07:17:20 2018
>  OS/Arch:      linux/amd64
>  Experimental: false
>  Orchestrator: swarm
> 
> Server:
>  Engine:
>   Version:      18.03.1-ce
>   API version:  1.37 (minimum version 1.12)
>   Go version:   go1.9.5
>   Git commit:   9ee9f40
>   Built:        Thu Apr 26 07:15:30 2018
>   OS/Arch:      linux/amd64
>   Experimental: false
> 

2.2 docker info:

> Containers: 9
>  Running: 8
>  Paused: 0
>  Stopped: 1
> Images: 57
> Server Version: 18.03.1-ce
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local local-persist
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
> runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
> init version: 949e6fa
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.15.0-30-generic
> Operating System: Ubuntu 16.04.4 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 56
> Total Memory: 125.6GiB
> Name: mainpc4
> ID: AJL5:6E4I:IMQF:H5WG:6JJF:7INX:OCZH:6R4A:Q2AD:TRAW:AHWI:T7IT
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:docker exec <registry-container> registry --version
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> 
> WARNING: No swap limit support

3. launch docker command:
`docker-compose up`

**Comment by dmp42** [comment]
Hi @unameuname 

Thanks for the report.

It should be filed on https://github.com/moby/moby though, since your problem is with the engine.

This here is the tracker for the Registry.
