### ISSUE TITLE
docker exec does not obey --security-opt no-new-privileges

### ISSUE THREAD

**Issue by margana** [docker/distribution#2683]
`docker run` supports starting a container with `no new privileges` enabled, however this does not seem to work for processes spawned by `docker exec`

Steps to reproduce:
- Set up a test (suid root `id`)
```
$ sudo cp `which id` .
$ sudo chmod +s id
```
- Check that it is working (elevate privs inside container)
```
$ docker run --rm -ti -v `pwd`:/test -u 1000:1000 centos:7 /test/id
uid=1000 gid=1000 euid=0(root) egid=0(root) groups=0(root)
```

- Check that no-new-privs is working
```
$ docker run --rm -ti -v `pwd`:/test -u 1000:1000 --name nnp-test --security-opt no-new-privileges centos:7
bash-4.2$ /test/id
uid=1000 gid=1000 groups=1000
```

- Check that no-new-privs is working with `docker exec` (in another terminal, leaving the container from previous step running)
```
$ docker exec -ti -u 1000:1000 nnp-test /test/id
uid=1000 gid=1000 euid=0(root) egid=0(root) groups=0(root)
```

Expected result: no privilege elevation

```
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:12:52 2018
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Comment by dmp42** [comment]
Hi @margana 

Thanks for the report.
This seems to be an engine problem, and should be reported on github.com/moby/moby

This tracker here is for the docker registry.

**Comment by margana** [comment]
Thanks, done. https://github.com/moby/moby/issues/37667
