### ISSUE TITLE
Failing to download oracle image

### ISSUE THREAD

**Issue by justintanner** [docker/distribution#2684]
Hi There!

I'm trying to download this oracle image from the docker store, but I keep getting an error "unexpected EOF". I've attached a screenshot.

![docker_bug](https://user-images.githubusercontent.com/216203/44216705-8ae5d900-a143-11e8-9bff-38bfd3f6863b.jpg)

Thanks, Justin.

**Comment by manishtomar** [comment]
Issue moved to [docker/hub-feedback #1603](https://github.com/docker/hub-feedback/issues/1603) via [**ZenHub**](https://www.zenhub.com/)

**Comment by manishtomar** [comment]
@dmp42 Can you close this?

**Comment by manishtomar** [comment]
@justintanner Since this is Hub/Store issue I've moved it to https://github.com/docker/hub-feedback/issues/1603

**Comment by dmp42** [comment]
Thanks @manishtomar
