### ISSUE TITLE
Pending bug fixes have not been released

### ISSUE THREAD

**Issue by kennydaniel** [docker/distribution#2693]
I am hitting a bug that has already been fixed in master. But as far as I can tell, there has not been a new release since 2.6.2 in July 2017.

I can see that my bug was fixed in November 2017 in master.

Are there plans to publish a new release of docker distribution anytime soon? 2.7?

Thanks! Apologies if this is not the right venue for this issue.

**Comment by komuw** [comment]
I also have experienced problems related to the fact that there hasn't been any release of `docker/distribution` for over a year. 
here's the related issue on moby; https://github.com/moby/moby/issues/37683

I think `docker/distribution` should be released in lock-step with `github.com/docker/engine`

**Comment by dmp42** [comment]
@kennydaniel @komuw we are preparing for the next release, to happen early fall.
We need help with code review on pending PRs and unanswered issues.

It may be synchronized with other Docker products releases, though it will be hard to have everything at the same time.
