### ISSUE TITLE
Building private registry with go1.11 fails

### ISSUE THREAD

**Issue by snmed** [docker/distribution#2697]
Hi
I tried to build the registry with go1.11 installed and get this error:
```bash
➜  distribution git:(master) ✗ make build  
+ build
# github.com/docker/distribution/cmd/registry
github.com/docker/distribution/vendor/github.com/stevvooe/resumable/sha256.block: relocation target runtime.support_avx2 not defined
github.com/docker/distribution/vendor/github.com/stevvooe/resumable/sha256.block: relocation target runtime.support_bmi2 not defined
make: *** [Makefile:101: build] Fehler 2
```
Docker Version:
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   f150324782
 Built:        Wed May 16 22:27:45 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   f150324782
  Built:        Wed May 16 22:28:17 2018
  OS/Arch:      linux/amd64
  Experimental: false

```
Docker Info:
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 43
Server Version: 18.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 41
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.122-1-MANJARO
Operating System: Manjaro Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6GiB
Name: Carida
ID: Z34L:FUI5:J2JS:FPPW:YRKB:VPGK:ZODT:5VXQ:3XDL:RKV6:6A6W:YQQY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: snmed
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
It works fine with go 1.10.3, so there must be something with the new release. I can reproduce this issue on a different linux machine, as soon I have time I'll try the same on my macbook.

Cheers Sandro

**Comment by dmp42** [comment]
@snmed I have a tentative fix here: https://github.com/dmp42/resumable

You should be able to verify it works by replacing stevvooe's resumable with this one.

It's pending some internal testing for now.

If it checks out, we should be merging the change upstream ASAP.

Let me know if you get a chance to try it.

**Comment by snmed** [comment]
Hi @dmp42

It seems to work, but I had to change the import path `github.com/stevvooe/resumable`  to `github.com/dmp42/resumable` in two of your files.
```
github.com/dmp42/resumable/sha512block_amd64.go
github.com/dmp42/resumable/sha256block_amd64.go
```
Thanks, this fix will solve the problem for the moment.

**Comment by dmp42** [comment]
@snmed you do not have to change the import paths in the code.
Just change the `vndr` file to pull from dmp42 instead of stevvooe.

**Comment by manishtomar** [comment]
@dmp42 Doesn't that break the consistency? Shouldn't the paths match to avoid confusion for anyone looking at the code? I can imagine someone trying to look for implementation from the import and get confused when it is different.

**Comment by dmp42** [comment]
a concrete, existing example: https://github.com/docker/distribution/blob/master/vendor.conf#L49
