### ISSUE TITLE
Reset to defaults missing warning

### ISSUE THREAD

**Issue by jekil** [docker/distribution#2706]
Using docker for MacOS, when something goes wrong and Docker asks you to "reset to defaults" a warning should be in place to warn people that you are not only resetting the settings but also all data (dockers) will be lost.

**Comment by manishtomar** [comment]
Issue moved to [docker/for-mac #3217](https://github.com/docker/for-mac/issues/3217) via [**ZenHub**](https://www.zenhub.com/)
