### ISSUE TITLE
Container state seems to be preserved in the engine

### ISSUE THREAD

**Issue by srfrnk** [docker/distribution#2710]
While researching a bug with Kafka and node-kafka which is unrelated to docker - I've stumbled upon a problem with docker engine.

After running with Kafka 2.0.0 you cannot go back to use the working Kafka 1.1.0 version without restarting the Doccker Service.

Even removing all container, images and volumes and then doing a `docker system prune -a --volumes` doesn't help.

The only thing that does is running `service docker restart` - no need to 'prune' - just restart.

I would expect state to be restored w/o even pruning - just killing the container should be enough.

The complete source code and environment [can be found here](https://github.com/srfrnk/kafka-test)
The kafka/node-kafka bug [can be found here](https://github.com/SOHU-Co/kafka-node/issues/1073)

**Comment by manishtomar** [comment]
@srfrnk This tracker is for issues with open source registry implementation and not Docker Engine. Kindly file issues in https://github.com/moby/moby/issues/ for problems with Docker Engine. Thanks!

**Comment by srfrnk** [comment]
@manishtomar - [done](https://github.com/moby/moby/issues/37837)
Would be nice if this was mentioned in the docs.
Currently your [website](https://docs.docker.com/registry/help/) refers to this repo :)
![screenshot-docs docker com-2018 09 13-09-10-14](https://user-images.githubusercontent.com/1501654/45470087-ea300c80-b734-11e8-9cf1-a26f48883dc0.png)
