### ISSUE TITLE
Mounting single file breaks if file is edited through gedit or WebStorm

### ISSUE THREAD

**Issue by StasPiv** [docker/distribution#2714]
Pretty weird issue I've experienced on my local docker instance.

```
> docker -v
Docker version 18.06.1-ce, build e68fc7a
```

```
> docker-compose -v
docker-compose version 1.21.0, build 5920eb0
```

OS:
```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

Think this is problem of docker itself, however I mentioned version of docker compose as well.

1. Mount single file (test.txt in my simple example)
docker-compose.yml
```
...
volumes:
    - /path-to-project-on-host/test.txt:/usr/app/test.txt:rw
...
```
2. docker-compose up
3. docker inspect container_app

```
...
"Mounts": [
            {
                "Type": "bind",
                "Source": "/path-to-project-on-host/test.txt",
                "Destination": "/usr/app/test.txt",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ]
...
```

4. Trying to edit file through terminal like this

```
> echo "Hello container!" > test.txt
```
5. File seems to be changed inside container

```
> docker exec container_app cat test.txt
Hello container!
```

6. Try to edit file through editor gedit

I edit the test.txt through gedit and now I get on host machine
```
> cat test.txt 
Hello container!
Hello container from gedit!
```

7. But inside container this file haven't changed. I still see previous message

```
> docker exec container_app cat test.txt
Hello container!
```

8. Then I try to edit file like on fourth step
```
> echo "Another one hello, container!" > test.txt
```

9. Inside container I still see message from fifth step
```
> docker exec container_app cat test.txt
Hello container!
```

I assumed that file test.txt is blocked somehow after editing in **gedit**. Actually I tried IDE like **WebStorm** or **PhpStorm** as well with the same behaviour. File was just blocked on writing after editing in them... Although text is edited fine through **LibreOffice** for example.

File permissions are 777.. And I edit file under the same user.

I would like to notice that mounting entire folder doesn't cause such problems and I can edit files inside mounted folder through **gedit** or **WebStorm**. However right now I need to mount single file, not entire folder.

Are there some file blockers inside container or something else I am not familiar with?

**Comment by manishtomar** [comment]
This tracker is for problems with open source registry. You may want to check forums.docker.com or support.docker.com for general docker usage questions. If you find an issue in engine then please file an issue with github.com/moby/moby. Thanks.
