### ISSUE TITLE
remote storage question

### ISSUE THREAD

**Issue by phantooom** [docker/distribution#2717]
if i use remote storage driver  s3 oss etc, is docker client download image from s3 directly? or download from distribution , distribution download from s3?

**Comment by manishtomar** [comment]
If you use [middleware like cloudfront](https://docs.docker.com/registry/configuration/#middleware) then blobs are downloaded via that CDN. Otherwise from S3 or OSS directly.

**Comment by manishtomar** [comment]
Closing since this is not an issue.
