### ISSUE TITLE
Adding S3 Checker to health package

### ISSUE THREAD

**Issue by diogomonica** [docker/distribution#272]
**Summary**: The [health package](https://github.com/docker/distribution/pull/230) comes with a few pre-configured checkers. At the moment the only two existing Checkers are the [FileChecker](https://github.com/diogomonica/distribution/blob/adding-healthcheck/health/checks/checks.go) and the [HTTPChecker](https://github.com/diogomonica/distribution/blob/adding-healthcheck/health/checks/checks.go). Create an S3Checker that checks for the ability to read and/or write to an Amazon S3 bucket.

**Comment by stenwt** [comment]
#dibs

**Comment by dmp42** [comment]
@stevvooe's PR should cover this. To be closed once merged (pending Rados test bustage fix).
