### ISSUE TITLE
weird unlink() call in containerd

### ISSUE THREAD

**Issue by metux** [docker/distribution#2727]
8739  unlink("ed field or methodsystemd cgroup flag passed, but systemd support for managing cgroups is not available<container-id>\n\nWhere \"<container-id>\" is your name for the instance of the container.Pass N additional file descriptors to the container (stdio + $LISTEN_FDS + N in total)display container events such as OOM notifications, cpu, memory, and IO usage statisticsfailed to set %s, because either tasks have already joined this cgroup or it has children<container-id>\n\nWhere \"<container-id>\" is the name for the instance of the container to be\npaused. <container-id>\n\nWhere \"<container-id>\" is the name for the instance of the container to be\nresumed.<container-id>\n\nWhere \"<container-id>\" is the name for the instance of the container to be\nrestored.<container-id>\n\nWhere \"<container-id>\" is the name for the instance of the container to be\ncheckpointed.This is an error in the application.  Please contact the distributor of this application if this is not you.Setting back cgroup configs failed due to error: %v, your state.json and actual configs might be inconsistent.Restores the saved state of the container instance that was previously saved\nusing the runc checkpoint command.Setting back intelrdt configs failed due to error: %v, your state.json and actual configs might be inconsistent.do not use pivot root to jail process inside rootfs.  This should be used whenever the rootfs is on top of a ramdiskenable systemd cgroup support, expects cgroupsPath to be of form \"slice:prefix:name\" for e.g. \"system.slice:runc:434234\"path to an AF_UNIX socket which will receive a file descriptor referencing the master end of the console's pseudoterminalThe events command displays information about the container. By default the\ninformation is displayed once every 5 seconds.do not create a new session keyring for the container.  This will cause the container to inherit the calling processes session keyThe resume command resumes all processes in the instance of the container.\n\nUse runc list to identiy instances of containers and their current status.The pause command suspends all processes in the instance of the container.\n\nUse runc list to identiy instances of containers and their current status.<container-id>\n\nWhere \"<container-id>\" is your name for the instance of the container that you\nare starting. The name you provide for the container instance must be unique on\nyour host.00010203040506070809101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899Timestamp: {{.Timestamp}}\nCode: {{.ECode}}\n{{if .Message }}\nMessage: {{.Message}}\n{{end}}\nFrames:{{range $i, $frame := .Stack.Frames}}\n---\n{{$i}}: {{$frame.Function}}\nPackage: {{$frame.Package}}\nFile: {{$frame.File}}@{{$frame.Line}}{{end}}\n\n\nWhere the given root is specified via the global option \"--root\"\n(default: \"/run/runc\").\n\nEXAMPLE 1:\nTo list containers created via the default \"--root\":\n       # runc list\n\nEXAMPLE 2:\nTo list containers created using a non-default value for \"--root\":\n       # runc --root value list<container-id> [signal]\n\nWhere \"<container-id>\" is the name for the instance of the container and\n\"[signal]\" is the signal to be sent to the init process.\n\nEXAMPLE:\nFor example, if the container id is \"ubuntu01\" the following will send a \"KILL\"\nsignal to the init process of the \"ubuntu01\" container:\n\t \n       # runc kill ubuntu01 KILL<container-id>\n\nWhere \"<container-id>\" is the name for the instance of the container.\n\nEXAMPLE:\nFor example, if the container id is \"ubuntu01\" and runc list currently shows the\nstatus of \"ubuntu01\" as \"stopped\" the following will delete resources held for\n\"ubuntu01\" removing \"ubuntu01\" from the runc list of containers:\n\n       # runc delete ubuntu01NAME:\n   {{.HelpName}} - {{.Usage}}\n\nUSAGE:\n   {{.HelpName}}{{if .VisibleFlags}} [command options]{{end}} {{if .ArgsUsage}}{{.ArgsUsage}}{{else}}[arguments...]{{end}}{{if .Category}}\n\nCATEGORY:\n   {{.Category}}{{end}}{{if .Description}}\n\nDESCRIPTION:\n   {{.Description}}{{end}}{{if .VisibleFlags"...) = 0

**Comment by dmp42** [comment]
Thanks @metux 
Unless this issue is about the registry, you should open this on the moby or containerd repository instead.
