### ISSUE TITLE
Create ping Checker for the health package

### ISSUE THREAD

**Issue by diogomonica** [docker/distribution#273]
**Summary**: The [health package](https://github.com/docker/distribution/pull/230) comes with a few pre-configured checkers. At the moment the only two existing Checkers are the [FileChecker](https://github.com/diogomonica/distribution/blob/adding-healthcheck/health/checks/checks.go) and the [HTTPChecker](https://github.com/diogomonica/distribution/blob/adding-healthcheck/health/checks/checks.go). Create a PingChecker that checks for the reachability of a remote host. Have this PingChecker be configured with a maximum latency that is considered healthy.

**Comment by sthulb** [comment]
@diogomonica to be clear, this is an ICMP ping?

**Comment by diogomonica** [comment]
Yeah, "upstream route check". My first thought was to implement it with ICMP and/or UDP.

**Comment by stenwt** [comment]
#dibs

**Comment by noxiouz** [comment]
Seems ICMP  is not the best solution to health check. Properly configured firewall must allow ICMP traffic, but a TCP connection could be banned. So we could meet the situation, when this check shows a false positive result.
When it comes to UDP, there's no way to check if a UDP package was delivered.
Could I offer an idea about tcp check? For example, we can try to connect over tcp to a remote host:port to test the service.

**Comment by diogomonica** [comment]
@noxiouz we already have an [HTTPChecker](https://github.com/diogomonica/distribution/blob/adding-healthcheck/health/checks/checks.go). Does that fit your use-case? I can see the usefulness of a generic TCP-check though.

One idea that I also wanted to implement is a Latency checker that would use an exponential moving average to decide if some downstream service is taking too long to answer (avoiding thundering herds). This could be paired up with any check that returns RTT or latency (such as a TCP, HTTP or ICMP/UDP check).

**Comment by dmp42** [comment]
Closing (see PR for details). Aaron TCP check implements this.
