### ISSUE TITLE
Unable to install on Fedora 29

### ISSUE THREAD

**Issue by jg110** [docker/distribution#2751]
I'm not sure if this is the right place to file this issue, so if there's a better place, please direct me there.

Currently [the only repository available for Fedora 29](https://download.docker.com/linux/fedora/29/x86_64/nightly/Packages/) consists of nightly builds of docker-ce. When attempting to install any of these packages, dnf returns an error: `nothing provides containerd.io needed by docker-ce-3:0.0.0.20181104010403.904d4fe-0.fc29.x86_64`. The error is repeated for each package available in the repository. It seems that at least one build of containerd.io needs to be present in the repository for docker-ce to install correctly, unless an older version is already present on the system.

**Comment by manishtomar** [comment]
Issue moved to [docker/for-linux #472](https://github.com/docker/for-linux/issues/472) via [**ZenHub**](https://www.zenhub.com/)
