### ISSUE TITLE
docker client requests incorrect url from non-root registry

### ISSUE THREAD

**Issue by argh** [docker/distribution#2753]
I run the registry with `REGISTRY_HTTP_PREFIX=/docker` for the reasons cited in:
#https://github.com/docker/distribution/issues/29
It correctly hosts (behind a proxy) at `/docker/v2/`

However, when I do a "docker push myregistry.com/docker/whatever", it requests:
`GET /v2/` 
and
`POST /v2/docker/whatever/blobs/uploads/`

My expectation is that those requests would match the registry server.

Running freshly updated Mac Docker 18.06.1-ce-mac73 (26764)

**Comment by manishtomar** [comment]
I think you need to setup your proxy to route everything coming to `myregistry.com` to `regstryip_or_host/docker` for this to work. Docker CLI will always request URLs from the domain root.

**Comment by cinlloc** [comment]
@manishtomar does it mean that #202 was just done for API purposes and cannot be used in conjunction of Docker CLI?

**Comment by manishtomar** [comment]
@cinlloc I suspect so. Maybe there is a setting in dockerd config that allows a prefix. I am not aware.

**Comment by manishtomar** [comment]
Closing since this is not distribution issue.
