### ISSUE TITLE
containerd.io conflicts with runc during deb installation

### ISSUE THREAD

**Issue by aostapenko** [docker/distribution#2757]
$  sudo apt install containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  pigz runc
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  containerd
The following NEW packages will be installed:
  containerd.io
0 upgraded, 1 newly installed, 1 to remove and 0 not upgraded.
Need to get 19.9 MB of archives.
After this operation, 67.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://download.docker.com/linux/ubuntu xenial/stable amd64 containerd.io amd64 1.2.0-1 [19.9 MB]
Fetched 19.9 MB in 2s (7,115 kB/s)        
(Reading database ... 219823 files and directories currently installed.)
Removing containerd (0.2.5-0ubuntu1~16.04.1) ...
Selecting previously unselected package containerd.io.
(Reading database ... 219809 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.2.0-1_amd64.deb ...
Unpacking containerd.io (1.2.0-1) ...
dpkg: error processing archive /var/cache/apt/archives/containerd.io_1.2.0-1_amd64.deb (--unpack):
 trying to overwrite '/usr/sbin/runc', which is also in package runc 1.0.0~rc2+docker1.13.1-0ubuntu1~16.04.1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/containerd.io_1.2.0-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

From https://download.docker.com/linux/ubuntu/dists/xenial/stable/binary-amd64/Packages:
Package: containerd.io
Architecture: amd64
Version: 1.2.0-1
Priority: optional
Section: devel
Maintainer: Containerd team <help@containerd.io>
Installed-Size: 85588
Provides: containerd
Depends: libc6 (>= 2.14), libseccomp2 (>= 2.3.0)
Conflicts: containerd
Replaces: containerd
Filename: dists/xenial/pool/stable/amd64/containerd.io_1.2.0-1_amd64.deb
Size: 19885618
MD5sum: 496787d314fad9ccc399dd3ba18e30cf
SHA1: 7d63282524ccc087fd002046407196f9f1b9faae
SHA256: 1cf91d85e7a6c6d03225d9acfde8abd3d5fcca51a907c35146a6b5f90957e993
SHA512: e28157bfd4bc17016f616bfe49427ebc97323ed0f10126a0a7865ae06c1d54fe24770efca7acd2ae412e9b05ebda3565998d2f93df998142d89a8241c2d01570
Homepage: https://containerd.io
Description: An open and reliable container runtime

Expected:
> Replaces: containerd, runc

**Comment by manishtomar** [comment]
This belongs to https://github.com/containerd/containerd/ repo. However please do tell what made you open an issue here when you were explicitly installing containerd package.
