### ISSUE TITLE
Honoring proxy related env vars

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#277]
In the (admittedly messy) case where the registry needs to connect to S3 through a proxy, the dockerfile should ember traditional proxy env vars (eg: HTTP_PROXY, HTTPS_PROXY, NO_PROXY).

Registry go code should then honor these env vars when present.

(for reference https://github.com/docker/docker-registry/issues/970)

**Comment by stevvooe** [comment]
@dmp42 Could you give this a try with `http_proxy` env variables and see if it works? Does this need to be on the 2.1 milestone?

**Comment by dmp42** [comment]
This is ill-phrased, and duplicates another user report being unable to use a registry behind a proxy.
Either way we have no simple way to even debug this, so, I'm closing.
