### ISSUE TITLE
Add config to require client certs

### ISSUE THREAD

**Issue by tiborvass** [docker/distribution#278]
Please correct me if I'm wrong, but it seems like in the current configuration file, it is not possible to require a client cert.

**Comment by sthulb** [comment]
I'll have a go at this over next week, although if someone beats me to it, go ahead :)

**Comment by sthulb** [comment]
Certificate Revocation Lists would be a nice addition to this issue too. There's no point using client certs if you can't tell if they're revoked.

**Comment by stevvooe** [comment]
Closed by #283.
