### ISSUE TITLE
Docker Desktop runs on login when set not to (Windows)

### ISSUE THREAD

**Issue by JVimes** [docker/distribution#2783]
I unchecked "start Docker Desktop when you log in", but it still starts when I log out/in or reboot.

![image](https://user-images.githubusercontent.com/6148201/49674753-49e63d00-fa30-11e8-92e0-f571e43fe09d.png)

![image](https://user-images.githubusercontent.com/6148201/49674763-4eaaf100-fa30-11e8-908c-24ab79153bd8.png)

<details>
  <summary>Docker version (click):</summary>

> Client: Docker Engine - Community
>  Version:           18.09.0
>  API version:       1.39
>  Go version:        go1.10.4
>  Git commit:        4d60db4
>  Built:             Wed Nov  7 00:47:51 2018
>  OS/Arch:           windows/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          18.09.0
>   API version:      1.39 (minimum version 1.24)
>   Go version:       go1.10.4
>   Git commit:       4d60db4
>   Built:            Wed Nov  7 00:56:41 2018
>   OS/Arch:          windows/amd64
>   Experimental:     false

</details>

<details>
  <summary>Docker info (click):</summary>

> Containers: 0
>  Running: 0
>  Paused: 0
>  Stopped: 0
> Images: 1
> Server Version: 18.09.0
> Storage Driver: windowsfilter
>  Windows: 
> Logging Driver: json-file
> Plugins:
>  Volume: local
>  Network: ics l2bridge l2tunnel nat null overlay transparent
>  Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
> Swarm: inactive
> Default Isolation: hyperv
> Kernel Version: 10.0 18290 (18290.1000.amd64fre.rs_prerelease.181121-1501)
> Operating System: Windows 10 Pro Version 1809 (OS Build 18290.1000)
> OSType: windows
> Architecture: x86_64
> CPUs: 8
> Total Memory: 31.94GiB
> Name: MyComputerName
> ID: W3QT:5RFE:UX6W:KDDQ:QZR5:OLXG:YALK:JKTL:VKLQ:URZS:LJ5C:6RIR
> Docker Root Dir: C:\ProgramData\Docker
> Debug Mode (client): false
> Debug Mode (server): true
>  File Descriptors: -1
>  Goroutines: 26
>  System Time: 2018-12-07T14:57:22.2871952-07:00
>  EventsListeners: 1
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> Product License: Community Engine

</details>

**Comment by manishtomar** [comment]
Issue moved to [docker/for-win #3056](https://github.com/docker/for-win/issues/3056) via [**ZenHub**](https://www.zenhub.com/)
