### ISSUE TITLE
Official image with 2.7.0 missing

### ISSUE THREAD

**Issue by solsson** [docker/distribution#2784]
Maybe this was postponed for some good reason, but it would be great if https://hub.docker.com/r/library/registry/ got the 2.7.0 release.

**Comment by caervs** [comment]
Hi @solsson. There is a [PR](https://github.com/docker-library/official-images/pull/5141) for the official image. As soon as it's merged we can get the official image out as well.

**Comment by solsson** [comment]
Is there any schedule for when the architecture issue can be resolved? If not could the new version be published for the same archs as 2.6.x first?

**Comment by caervs** [comment]
@solsson official image is out. Thanks for you patience!
