### ISSUE TITLE
docker build command crashes Linux OS if the Dockerfile is kept at / directory.

### ISSUE THREAD

**Issue by tektutor** [docker/distribution#2787]
Place any simple Dockerfile at root folder ( / ) and attempt to build the image and docker will crash the Ubuntu/CentOS and maybe other Linux OS.

I believe docker client tool attempts to send the whole file system as a build context to docker engine in the process of building the image.  As a best practice I create a sub-folder and place the Dockerfile to avoid this problem, however Docker being such a popular tool it shouldn't lead to data loss or server crash or down-time just because someone attempted to build an image placing their Dockerfile in the root folder.

This behaviour is observed in almost all versions of Docker including the latest 18.x release.

**Comment by manishtomar** [comment]
This repo is for open source Docker Registry. Please consider opening this issue in https://github.com/moby/moby/
