### ISSUE TITLE
Application Layer Timeout/Freeze

### ISSUE THREAD

**Issue by bannsec** [docker/distribution#2792]
I've been noticing consistent application layer freezing when connecting remotely to a machine (`docker-machine`). In this case, I've been connecting to an azure instance and, generally within 5 minutes or less, the docker connection completely freezes and i have to kill docker and re-connect.

While initially i assumed this was a TCP issue (something timing out), performing a pcap showed that the TCP keep-alives seem to be getting responses, while the docker connection itself is still hung.

Steps to reproduce:
 - Setup docker-machine somewhere (Azure in my case)
 - docker run  -it --network=host ubuntu:bionic
 - do not type anything for a few minutes
 - now attempt to type something and notice that the connection is frozen.

For help, I've attached a pcap of one of the times when it froze up.
[dump.zip](https://github.com/docker/distribution/files/2708898/dump.zip)

**Comment by caervs** [comment]
Thanks @bannsec for filing this issue. However issues with docker itself (and not the registry) should be filed against https://github.com/moby/moby

**Comment by manishtomar** [comment]
Closing as non-registry issue.
