### ISSUE TITLE
docker ipv6 link-local address cannot be bound to for first 1-2 seconds

### ISSUE THREAD

**Issue by sethkoehler** [docker/distribution#2794]
When trying to bind to an ipv6 link-local address (fe80:...), for the first 1-2 seconds, the bind will fail.

See attached reproducer.  It's a 40 line C++ program that sleeps the specified number of seconds, then goes through IPv6 interfaces and tries to bind to a fixed port on each.  The other file is a simple test script that compiles the program and runs it in a basic docker container with IPv6 enabled.  You can run ./test.sh 0 to show the failing case, and ./test.sh 2 to show the successful case.

[cc_net.zip](https://github.com/docker/distribution/files/2715567/cc_net.zip)

On my machine, this binds to ::1 just fine in both cases, but fails to bind to the fe80:... address in the 0 second sleep case.  If you sleep for 1 second, it will sometimes pass and sometimes fail.

Output of docker version (though I've tried this on a few older docker versions and noticed the same, such as 17.09 and 17.12):

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by caervs** [comment]
Thanks for filing this @sethkoehler, but issues with the docker container engine should be filed with https://github.com/moby/moby

**Comment by sethkoehler** [comment]
Ah sorry about that, just filed https://github.com/moby/moby/issues/38491, closing this, thanks!
