### ISSUE TITLE
Running Service inside Container is not accessable On Windows 10

### ISSUE THREAD

**Issue by sunilkanjar** [docker/distribution#2797]
I was use Version 18.06.0-ce-win72 (19098) on my Windows system and then I get update for 2.0.0.0-win81 (29211).

After updating to that version sunning service inside Docker Container will not accessible after some time of starting docker service.
To solve this issue I need to restart the docker service and then again all services are available to access and same issue is there after some random amount of time.

- There are many spring application on my local system and docker is also on my local system it self. 
- There are multiple data base schema in MariaDB Container and Redis cache in Redis Container which used in outer application runs on my system
- After some random amount time database call will get timeout and the any of the service are not accessible on my system it will working fine inside running Container only we can't communication with that services.
- There are no specific scenario in which we can replicate this issue, but it will replicate each time I used this docker 2.0.0.0-win81 (29211)
- This issue not in Version 18.06.0-ce-win72 (19098).

[docker-compose.zip](https://github.com/docker/distribution/files/2723526/docker-compose.zip)

**Comment by caervs** [comment]
@sunilkanjar please clarify, are you trying to run the docker registry image and it's not accessible? If not this is an issue likely better filed with https://github.com/moby/moby

**Comment by sunilkanjar** [comment]
Update:  
This issue is not with specific image any service running inside Container will not accessible from the out side.  
And same issuer is there with mac OS.

**Comment by manishtomar** [comment]
This is not issue with registry. Closing.
