### ISSUE TITLE
How to upgrade from version 2.6 to 2.7?

### ISSUE THREAD

**Issue by minhdanh** [docker/distribution#2803]
Docker registry 2.7 is already out, but I cannot find a note regarding upgrading from registry version 2.6.
I'm using Docker registry 2.6 using the Docker image at https://hub.docker.com/_/registry?tab=tags, so is upgrading just a matter of pulling the new image (2.7) and restart the registry container?

**Comment by caervs** [comment]
>  so is upgrading just a matter of pulling the new image (2.7) and restart the registry container?

@minhdanh not quite. There are a few more steps. Tl;dr you have to create a new container to replace the old one. Some questions first:

* Are you running the container yourself or are you running as a service using Swarm?
* Are you using a local storage backend (filesystem which is default) or remote one (e.g. cloud provider)?
* Are you bind mounting anything in your current container (like a volume for storage backend or a config file)?

Marking issue as a docs one to fill in any gaps in our upgrade documentation.

**Comment by minhdanh** [comment]
@caervs :
> Are you running the container yourself or are you running as a service using Swarm?

I'm running the container user docker-compose. No Swrm or Kubernetes.

> Are you using a local storage backend (filesystem which is default) or remote one (e.g. cloud provider)?

I'm using a remote filesystem (self-hosted Minio).

> Are you bind mounting anything in your current container (like a volume for storage backend or a config file)?

Yes, there're two config files being mounted:

```
    volumes:
      - ./registry.yaml:/etc/docker/registry/config.yml:ro
      - ./auth.crt:/etc/docker/registry/auth.crt:ro
```

**Comment by manishtomar** [comment]
@minhdanh If your question is about any change in the way images are stored then no there is no change. 2.7 registry instance pointing to storage that was running with 2.6 should work without any issues. Please try it out and let us know if you face any issues.

**Comment by minhdanh** [comment]
@manishtomar Ok, how about the config. Will the old config file of 2.6 work with 2.7? Is there a sample of the config file for 2.7?

@caervs Can you share the steps that you were about to mention?

**Comment by bainsy88** [comment]
I have observed a problem whereby if 2.6.2 and 2.7.1 coexist this causes us to see the following errors for some pushes:

`unknown error completing upload: unexpected EOF`
`unknown error completing upload: crypto/sha256: invalid hash state identifier`

These occur in both the 2.6.2 and 2.7.1 instance. We are using the S3 driver

As we have a multicluster kube architecture there is always going to be a window where they will coexist within the same cluster as well as across AZ's. 

Is this something that is a known limitation?
