### ISSUE TITLE
Private registry with local s3 (Minio) can't push/pull

### ISSUE THREAD

**Issue by batreseau** [docker/distribution#2806]
Hello

I have somes troubles to set a local S3 storage with Docker Registry V2

Configuration:
     Minio local S3 (10.126.33.89:9001)
     Docker Registry V2 with certs (10.126.33.86:5000)

Problem:
     When i try to push an image on my private registry, i got an "Retrying in 5 second" and i can't push any image . For the storage, i use Minio. I can access to Minio interface and create bucket but Docker registry can't use it. When i check logs of Docker Registry, i see somes errors:

`time="2019-01-08T16:55:49Z" level=error msg="response completed with error" auth.user.name="registry_user" err.code=UNKNOWN err.detail="Put https://s3-external-1.amazonaws.com/registry/docker/registry/v2/repositories/weaveworks/weave-npc/_uploads/fa7a4f5b-f309-42a9-8edf-62d0905e0ffe/startedat: dial tcp: lookup s3-external-1.amazonaws.com: no such host" err.message="unknown error" go.version=go1.4.3 http.request.host="10.126.33.86:5000" http.request.id=72636208-260b-4f17-8bff-48c8d6b7feb3 http.request.method=POST http.request.remoteaddr="10.126.33.86:57744" http.request.uri="/v2/weaveworks/weave-npc/blobs/uploads/" http.request.useragent="docker/18.06.1-ce go/go1.10.3 git-commit/e68fc7a kernel/4.15.0-20-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.06.1-ce \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=20.021824718s http.response.status=500 http.response.written=382 instance.id=d8545380-6d54-420a-b59c-749f680ea5de vars.name="weaveworks/weave-npc" version=v2.2.0
`

I think the problem is Registry try to push image on AWS, not on my local S3:
dial tcp: lookup s3-external-1.amazonaws.com: no such host

My Registry image was build from official Registry V2 and a config file.

Docker Registry Config file:
`version: 0.1
log:
    fields:
        service: registry
http:
    addr: :5000
storage:
    cache:
        layerinfo: inmemory
    s3:
        accesskey: #MASKED#
        secretkey: #MASKED#
        region: us-east-1
        regionendpoint: http://10.126.33.89:9001/
        bucket: registry
        encrypt: false
        secure: true
        v4auth: true
        chunksize: 5242880
        rootdirectory: /
`

Docker Registry start command:
`docker run -v /registry:/var/lib/registry -v /certs:/certs -v /auth:/auth -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt -e REGISTRY_HTTP_TLS_KEY=/certs/registry.key -e REGISTRY_AUTH=htpasswd -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd --restart=always -p 5000:5000 -d --name=registry registrym`

If someone can help me :)

Thanks

**Comment by swetpand** [comment]
I have had the same issue and solved it by using port 443 instead of 5000. Looks like the issue RichardFoo referenced is still open and not fixed.

**Comment by swetpand** [comment]
This 443 does not have to be the host port. As long as the container port is 443, it should work. This is the command that got my stuff working - 
docker run -d -p 5000:443 --restart=always --name registry -v $(pwd)/auth:/auth -v $(pwd)/config.yml:/etc/doc
ker/registry/config.yml -e REGISTRY_AUTH=htpasswd -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH
=/auth/htpasswd -v $(pwd)/certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.
key -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 --net=host registry:2.6

**Comment by brzepka** [comment]
Hello , just back from my business trip. I try do make registry work . But it still try to push on amazon instead my local ip. Does anyone have news about this ? Thanks 😉

**Comment by batreseau** [comment]
Hello guys. So i found a workaround for this problem. In our project, we don't restart the docker register many times. Starting from this point, a simple action make the docker registry functional:

Run the fail container of registry.
Connect into container with "docker exec -it <IDCONTAINER> sh
Check configuration in /etc/docker/registry and update config.yml
Check registry process with "ps aux" then kill it with "kill <pid>"

You are normally ejected from the container

If you check "docker ps" command, you can see container id didn't change but new configuration is now apply. So test again and normally, all work well.

Thanks all.
