### ISSUE TITLE
Can't push to internal registry server

### ISSUE THREAD

**Issue by Steffen543** [docker/distribution#2810]
Hello,

i have an Ubuntu Server (16.04) with Docker installed:

### Server
Client:
  Version: 18.09.1
  API Version: 1.39
  Go Version: go1.10.6
  Git commit: 4c52b90
  Built: Wed Jan 9 19:35:23 2019
  OS/Arch: linux/amd64
  Experimental: false

Server:
  Version: 18.09.1
  API Version: 1.39
  Go Version: go1.10.6
  Git commit: 4c52b90
  Built: Wed Jan 9 19:35:23 2019
  OS/Arch: linux/amd64
  Experimental: false

### Working Station (Docker Toolbox)
Client:
  Version: 18.03.0-ce
  API Version: 1.37
  Go Version: go1.9.4
  Git commit: 0520e24302
  Built: Fri Mar 23 08:31:36 2018
  OS/Arch: windows/amd64
  Experimental: false
  Orchestrator: swarm

Server:
  Version: 18.09.0
  API Version: 1.39
  Go Version: go1.10.4
  Git commit: 4d60db4
  Built: Wed Nov 7 00:52:55 2018
  OS/Arch: linux/amd64
  Experimental: false

### Issue

This Server runs a docker registry on port 50000.
Locally on this server i can push images without problems to the registry.

But when i want to push images to this registry from my working station, i cant.
But i can access the registry via http, so i get the locally pushed repository shown:

  {"repositories":["test"]}

But when i want to push an image from my working station, i get the following error:

   The push refers to repository [<IP>:50000/test]
   Get http://<IP>:50000/v2/: net/http: request canceled <Client.Timeout exceeded while awaiting headers>

Its strange because i can access the server via http and i can also ping the server.
All issues i found with this errors refers to a wrong DNS Configuration, but i dont think thats the problem because i am accessing it via the IP.. 

I am a beginner at docker so sorry if this is a bad question :/

**Comment by manishtomar** [comment]
Can you list your `docker push` command? The below error shows that docker engine is not connecting to any host.
```
The push refers to repository [:50000/test]
Get http://:50000/v2/: net/http: request canceled <Client.Timeout exceeded while awaiting headers>
```

**Comment by Steffen543** [comment]
Hey,

i solved the problem.. was a bad mistake from me. I couldn't reach the registry because of the proxy i had set. Now all works fine! Sorry for the Issue. Can be closed.

Thanks!
