### ISSUE TITLE
Is there any way to improve GC performance?

### ISSUE THREAD

**Issue by mmpei** [docker/distribution#2812]
it is quite slow when i do GC in my regsitry which the backend storage reachs a huge size about 600GB and 600K objects.
it spends 8 hours to mark used objects, and more time to find objects that should be deleted.
this will make our image repository readonly for a long time and this time is not acceptable.
so is there any way to improve GC performance? or make a concurrent GC? or separate GC to some lightweight GCs? and make GC to bring less effect to image repository.

**Comment by caervs** [comment]
Hi @mmpei. Currently the OSS community has no plans to improve the scalability of GC. I would recommend going with a commercial offering designed for those use-cases such as Docker EE.
