### ISSUE TITLE
docker container ls --filter is not documented

### ISSUE THREAD

**Issue by x-yuri** [docker/distribution#2818]
I thought I could filter by column names (CONTAINER ID, IMAGE, COMMAND, CREATED, STATUS, PORTS, NAMES), but I tried `--filter image=...` and it didn't work.

**Comment by caervs** [comment]
Image filtering can be done using "ancestor"

```
$ docker ps --filter ancestor=sublimino/newsbeuter
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS               NAMES
c09932a22cbb        sublimino/newsbeuter   "/usr/local/bin/news…"   6 hours ago         Up 6 hours                              newsbeuter
```

See https://github.com/moby/moby/blob/master/daemon/list.go#L20 for the full list of supported filter fields.

Please submit general docker issues to the [moby/moby](https://github.com/moby/moby) repo. Thank you!
