### ISSUE TITLE
MANIFEST INVALID problem when pushing local packaged layer to docker hub

### ISSUE THREAD

**Issue by JasonYangShadow** [docker/distribution#2831]
https://docbase.io/posts/631411/sharing/8dd8720d-0e91-4446-97f7-f0c080064ff9

I hope anyone who is familiar with this issue could help me. 
Thanks!

**Comment by dgoo2308** [comment]
well you have 6 layers but only 5 history:v1Compatibility configs, if you add a layer, you need to add a history:v1Compatibility configs, with parent pointing to the previous layer id!

**Comment by JasonYangShadow** [comment]
> well you have 6 layers but only 5 history:v1Compatibility configs, if you add a layer, you need to add a history:v1Compatibility configs, with parent pointing to the previous layer id!

ohhh! thanks so much!

I've searched some documents on V1compatability creation
https://github.com/containers/buildah/blob/master/docker/types.go

it mentions that for non-top-level layer, we can create fake V1Compatibility strings, while what about for top-level layer? What do I need to create in order to mark it as runnable image?
// github.com/docker/distribution/manifest/schema1/config_builder.go
// For non-top-level layers, create fake V1Compatibility strings that
// fit the format and don't collide with anything else, but don't
// result in runnable images on their own.

**Comment by JasonYangShadow** [comment]
> 
> 
> @JasonYangShadow maybe this not the place to discuss this, nor is it a distribution issue, I would advice to close this issue.
> 
> I known and understand it's not so easy to find the docs and or solution, I worked a longtime on that and schemaversion 2..etc for pushing to registry with [odagrun](https://gitlab.com/gioxa/odagrun/odagrun) since no libs in c are available!
> 
> In short for the top history:v1Compatibility:
> 
>     1. remove image:xxx from top history:v1Compatibility
> 
>     2. remove container
> 
>     3. duplicate top and put it as the new history:v1Compatibility top.
> 
>     4. on the new previous, delete history:v1Compatibility:config,
> 
>     5. On the new top, detach `id`, name it `parent` and put it back in
> 
>     6. update the date fields on top history:v1Compatibility
> 
>     7. delete if present "throwaway":true since you add a new layer on top history:v1Compatibility
> 
>     8. update container_config: with your command to create this new layer.
> 
>     9. update your history:v1Compatibility:config as you wish
> 
>     10. calc a new id e.g. sha256 sum starting with this history:v1Compatibility and layer sha256.
> 
>     11. put that new id back in.
> 
> 
> the above should do the trick to get started,also make sure you've pushed that new layer before pushing the manifest.

Wow, great! thanks! yep, I also do not think this is the right place to discuss about this. I closed this issue and thank you so much for detailed explanation.
