### ISSUE TITLE
Process Accept header MIME types in case-insensitive way

### ISSUE THREAD

**Issue by yuwaMSFT2** [docker/distribution#2835]
The Accept header is processed case sensitively when user requests for manifest. So the following is not matching to manifest v2.
Accept: Application/vnd.docker.distribution.manifest.v2+json

But according to spec, media type should be case insensitive:
Both top-level type and  subtype names are case-insensitive.

https://tools.ietf.org/html/rfc6838

**Comment by manishtomar** [comment]
@yuwaMSFT2 Care to make a PR?

**Comment by yuwaMSFT2** [comment]
@manishtomar Sure. Will prepare a PR.
