### ISSUE TITLE
Add login scope for registry to token auth server

### ISSUE THREAD

**Issue by ekristen** [docker/distribution#285]
Without scope it is implicit that it is a login call, however everything else has a scope, I think for consistency sake it makes sense to send `scope=login` for the login.

**Comment by stevvooe** [comment]
What use case does this support over a token without scope? For example, what could one do with a "login" token that couldn't be done with an empty token?

Are there other systems that have a login scope that could demonstrate this necessity?

**Comment by ekristen** [comment]
That is a good question, I don't have a good example, I would just think it would be good for consistency sake. Essentially everything has a scope, whether it is for login, access to a repository, etc ... 

Just my $0.02

**Comment by stevvooe** [comment]
@ekristen I am neither for or against this, outright and I see you're point. Consistency-wise, it would make sense if a login "granted" the user some functionality, other than the delegation that access token confers. If nothing is actually "granted", there shouldn't be a scope.

Its also interesting to note that If the login scope would be equivalent to an empty scope, then requiring it would be a backwards incompatible change (but we could actually handle that).

**Comment by ekristen** [comment]
It really isn't a problem. Just something I noticed while messing around with the new registry and token auth system. If it is going to cause a backwards compatibility issue, I say just leave it. 

I would update the documentation to talk about the login process though, the current documentation only talks about requesting a token with respect to scopes for repository access.

**Comment by stevvooe** [comment]
@ekristen I'm going to mark this as a documentation issue. We should include information about the token grant model, using this case as a "demonstrable use case".

**Comment by kenjones-cisco** [comment]
Based on the existing documentation (https://docs.docker.com/registry/spec/auth/token/) it seems to imply that scope is a required input, and only account is considered optional for the GET /token/ API.

As such when I enabled token auth through a centeralized entity, then docker login fails because of a missing scope. If it is not required, just need to indicate that it is optional.

**Comment by stevvooe** [comment]
@kenjones-cisco This issue was more of a question around handling scope in the registry, as opposed to the token issuer. For the token issuers, scope may be a required argument. To support login, it doesn't make sense that it should be. @jlhawn 

Closing since this is a little old. I'm not sure that we will make a documentation change here.

**Comment by kenjones-cisco** [comment]
@stevvooe I'm not sure I understand your thought process on not updating the documentation. The spec does indicate that scope is provided but when performing a `docker login <registry:port>` the result is a call to the configured authorization service where `account` and `service` are provided but no scope. I don't personally care one way or another if scope is required or not for a login, but by virtue of the documentation for the registry referring to a spec for authorization via token, it should be made clear that scope is or is not a required value. 

I can choose to make scope required but if the registry will never send a scope then a 401 will always happen. 

I just think from a spec perspective that the documentation should reflect if it is required or not.

**Comment by stevvooe** [comment]
@kenjones-cisco My point was that you've reported an unrelated problem on an unrelated issue. If there is another bug you'd like to report, please open up a separate issue rather than hijacking this issue.
