### ISSUE TITLE
network rm can not delete config only network

### ISSUE THREAD

**Issue by sirdemios** [docker/distribution#2850]
using (filling in ... with network specific things)
docker network create --config-only --subnet... --ip-range... -o parent... macvlan-config
docker network create -d macvlan --scope swarm --config-from macvlan-config macnet

later when using
docker network rm macnet
docker network rm macvlan-config
I am told that macvlan-config is in use.
when I inspect it lists no attachments
this is an issue only solved by removing all docker folders from my hard-drive manually. Its not fixed by a reinstall and restart.

I would suggest that ANY removal command that CAN be rejected MUST be force-able.
ie add "-f" to all "rm" commands
also if its of interest I'm on RHEL 7

**Comment by sirdemios** [comment]
also using docker ce 3.18.09 1-3.el7

**Comment by sirdemios** [comment]
I had to reinstall docker 3 times today. I shouldn't be able to permanently break docker with a command that I got from its own docs https://docs.docker.com/network/macvlan/

**Comment by stmudie** [comment]
Sane issue here.  CentOS  7.6.1810, Docker 18.09.1 build 4c52b90

**Comment by donnib** [comment]
I have same issue, it's driving me nuts that i can't find a way to get rid of them. anyone have a work around ?

**Comment by jpelzer** [comment]
Docker version 18.09.8, build 2c0a67b

**Comment by miguelcostaUI** [comment]
Same issue here.. anyone found a solution for this?

Docker version 18.09.8, build bfed4f5

**Comment by dmcgowan** [comment]
File docker issues here https://github.com/docker/for-linux
