### ISSUE TITLE
Private registry push api fail : "BLOB_UPLOAD_INVALID"

### ISSUE THREAD

**Issue by bluefriday** [docker/distribution#2867]
I search how to push for using registry v2 api(https://docs.docker.com/registry/spec/api/#completed-upload).
I received 202 Accepted code about all 'Chunk Upload', but I get this error message in 'Completed Upload' step.

```
[root@user:/root/test] curl -X PUT -v \
>   http://localhost:5000/v2/redis/hello/blobs/uploads/4eac9236-d1eb-4048-8572-89b9371033ce?_state=Wi...J9?digest=sha256:e8f2305ed6ac0d5e2c79349c3129bca7ec32497bad23336e59f8ee3d793473db \
>   -H "Content-Type: application/octet-stream"


* About to connect() to localhost port 5000 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5000 (#0)

> PUT /v2/redis/hello/blobs/uploads/4eac9236-d1eb-4048-8572-89b9371033ce?_state=Wi...J9?digest=sha256:e8f2305ed6ac0d5e2c79349c3129bca7ec32497bad23336e59f8ee3d793473db HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:5000
> Accept: */*
> Content-Type: application/octet-stream
>
< HTTP/1.1 404 Not Found
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< Date: Tue, 26 Feb 2019 10:40:51 GMT
< Content-Length: 89
<
{"errors":[{"code":"BLOB_UPLOAD_INVALID","message":"blob upload invalid","detail":204}]}
* Connection #0 to host localhost left intact
```

What does the error code '204(sometimes code : 208)' mean?

And.. where can I get proper digest value in this case?

**Comment by alexisvisco** [comment]
After reading the documentation I think you forgot the header part:
```
Content-Length: <size of chunk>
Content-Range: <start of range>-<end of range>
```

Maybe I am wrong but in your curl command this part is missing.

**Comment by bluefriday** [comment]
I solved this problem.
That value is about URL parameter length. Maybe.. It is a problem about parameter length.
So I used '--data' and '-G' option in using PUT parrameter :D

**Comment by btsken** [comment]
hi @bluefriday 

I have the same problem.

here is my code
`curl -X PUT -v -H "Authorization: Bearer $token" -H "Content-Type: application/octet-stream" -H "Content-Length: $size" --data-binary @"50670****bfbe56/layer.tar" $location?digest=sha256:d2*******4675`

Can u share curl command for uploading layer?

**Comment by bluefriday** [comment]
hello @btsken 

My curl for the PUT action is:
```
curl -v -X PUT -G \
   -H "Content-Type: application/octet-stream" \
   -T 726*****f9e \
   --data "digest=sha256:726*****f9e" \
   --data "_state=koE***D%3D" \
   http://localhost:5000/v2/nginx/blobs/uploads/4****b18-****-****-****-1d31a84****0
```
I hope it helps.
If you need further sharing, please leave a comment.

**Comment by btsken** [comment]
It works.

Thank you very much!
