### ISSUE TITLE
Publish Trust Spec

### ISSUE THREAD

**Issue by endophage** [docker/distribution#287]
Need to get community feedback on trust ideas. Formalize a public specification and publish.

**Comment by vladimir-v-diaz** [comment]
We are available to help with the specification if needed.  You are welcome to join and ask questions on the [TUF mailing list](https://groups.google.com/forum/#!forum/theupdateframework) or over voice chat.

FYI: Jonathan Rudenberg is meeting with us in April.  We hope to make more progress on the Go implementation and discuss the docker trust specification.

**Comment by stevvooe** [comment]
This should be closed when we finish #654.

**Comment by stevvooe** [comment]
Covered by docker/notary project.
