### ISSUE TITLE
Resumable blob digests

### ISSUE THREAD

**Issue by jlhawn** [docker/distribution#290]
When finalizing a blob upload the client must verify the digest of the blob with the digest that was computed by the registry. Currently, the registry gets this digest by reading all of the blob content back from the storage backend and computing the digest on-demand. This can be very slow depending on the blob length and latency/bandwidth of the storage backend, creating a very noticeable lag on the client side.

One possible fix is to keep the state of the canonical digest during the upload process. When a blob upload begins the registry can save a snapshot of the digest state at the end of each upload chunk (the digest of the blob so far). When the client uploads the next chunk the registry can resume computation of the digest given the state of the digest at the offset where the new chunk begins. Finalizing the upload of the blob would then be relatively instantaneous given the state of the digest after the final chunk was uploaded.

**Comment by diogomonica** [comment]
@jlhawn as we talked about IRL, the concept seems ok. I believe there aren't any inherent crypto vulnerabilities from doing this. Any proposed architecture for the solution? Server-side?
