### ISSUE TITLE
API for removing image tag

### ISSUE THREAD

**Issue by kennoosh** [docker/distribution#2931]
I'm trying to remove image tags in dockerhub with the following API: 
curl 'https://hub.docker.com/v2/repositories/${ORGANIZATION}/${IMAGE}/tags/${TAG}' \
-X DELETE \
-H "Authorization: JWT ${TOKEN}"
but it never works, is this API still working? or is there any other API for this?

Regards!

**Comment by madushajg** [comment]
Have you tried,
 curl -X DELETE https://hub.docker.com/v2/${ORGANIZATION}/${IMAGE}/manifests/${DIGEST}
?

**Comment by manishtomar** [comment]
@kennoosh That should work. Moreover, that is hub API independent of distribution API  https://docs.docker.com/registry/spec/api/#overview . I am closing this.
