### ISSUE TITLE
Docker should not filter local DNS nameservers when using --network=host

### ISSUE THREAD

**Issue by eli-osherovich** [docker/distribution#2957]
My host uses some kind of local DNS server, hence, /etc/resolv.conf has only one line:

nameserver 127.0.1.1

When running docker with default network (bridge) it filters out the local DNS and add Google's public servers 8.8.8.8 and 8.8.4.4. However, when running with host network, it still filters the local DNS but does not add the Google ones. In my view, with host network, it should preserve local servers in /etc/resolv.conf.

**Comment by thaJeztah** [comment]
This doesn't look to be an issue with the open source registry (which is what is in this repository); could you open an issue in https://github.com/moby/moby/issues instead? When doing so, please add the information that's requested in the issue template there, thanks!
