### ISSUE TITLE
S3 fails to work when running under AWS ECS Fargate

### ISSUE THREAD

**Issue by daddyman** [docker/distribution#2960]
I am running the registry container under Amazon ECS Fargate. In a basic configuration (using file or memory storage) it works, but when I configure the storage to use S3 I get an error that no credentials were found in the chain. I am deploying it with a TaskRole that gives the needed access to the S3 Bucket. 

I am running `registry:latest` docker image. I also tried using `registry:2` and `registry:2.7.1`.
The Docker version is whatever version Amazon is using with Fargate.

After some digging I discovered the problem. The S3 storage driver code creates its own list of credential providers for AWS SDK which doesn't contain the checks needed for the ECS TaskRole to be used. These checks are in the AWS SDK default settings but the S3 storage driver doesn't include them.

## What AWS SDK Does

The AWS SDK for Go (aws-sdk-go) default credential setup has special code to check for the environment variable (AWS_CONTAINER_CREDENTIALS_RELATIVE_URI) used by ECS to allow the TaskRole to be used.  This code is in `aws/defaults/defaults.go`. The `RemoteCredProvider` function checks for the special environment variables and returns the correct provider. It defaults to the regular EC2 Role Provider if the special environment variables are not set.

```
// RemoteCredProvider returns a credentials provider for the default remote
// endpoints such as EC2 or ECS Roles.
func RemoteCredProvider(cfg aws.Config, handlers request.Handlers) credentials.Provider {
    if u := os.Getenv(httpProviderEnvVar); len(u) > 0 {
        return localHTTPCredProvider(cfg, handlers, u)
    }

    if uri := os.Getenv(ecsCredsProviderEnvVar); len(uri) > 0 {
        u := fmt.Sprintf("http://169.254.170.2%s", uri)
        return httpCredProvider(cfg, handlers, u)
    }

    return ec2RoleProvider(cfg, handlers)
}
```

## S3 Storage Driver Problem

The S3 storage driver creates its own credentials chain for AWS and misses the checks for the environment variables. I guess it does this to add a new entry to the specified access key/secret key in the configuration. The code in `registry/storage/driver/s3-aws` (in the New function) looks like this:

```
creds := credentials.NewChainCredentials([]credentials.Provider{
		&credentials.StaticProvider{
			Value: credentials.Value{
				AccessKeyID:     params.AccessKey,
				SecretAccessKey: params.SecretKey,
				SessionToken:    params.SessionToken,
			},
		},
		&credentials.EnvProvider{},
		&credentials.SharedCredentialsProvider{},
		&ec2rolecreds.EC2RoleProvider{Client: ec2metadata.New(sess)},
	})

awsConfig.WithCredentials(creds)
```
This falls back to the default EC2 role provider but does not have the extra checks for the ECS environment variables that allows the TaskRole to be used.

## My Workaround

My workaround was to add an check around setting up the AWS credentials. In the `New` function of the S3 storage driver file `s3.go` - if the access key in the configuration is empty then skip the custom credential setup and let the AWS SDK use its default credential configuration.

```
       if params.AccessKey != "" {
                creds := credentials.NewChainCredentials([]credentials.Provider{
                        &credentials.StaticProvider{
                                Value: credentials.Value{
                                        AccessKeyID:     params.AccessKey,
                                        SecretAccessKey: params.SecretKey,
                                        SessionToken:    params.SessionToken,
                                },
                        },
                        &credentials.EnvProvider{},
                        &credentials.SharedCredentialsProvider{},
                        &ec2rolecreds.EC2RoleProvider{Client: ec2metadata.New(sess)},
                })
                awsConfig.WithCredentials(creds)
        }
```
When I built and deployed the Docker image the S3 driver worked as expected.

## Resolution

The workaround does fix the problem when not using a specific access/secret. 

As a quick fix it works but it may be better long term to get the default config (maybe by called `aws.defaults.Get()` instead of `aws.NewConfig()`. The `aws.defaults.Get()` has a config that includes the default cerdentials chain. The extra static provider could be inserted into the chain if the access/secret key is configured.

For now we are using our custom build of the registry.

**Comment by abulford** [comment]
@daddyman I was having the same issue and put together a fix for it, when I thought to check for any existing reports I found your ticket so have submitted a PR against this, I hope you don't mind?  The solution is a little different from yours but seems to work.

I've tested this in EC2 and ECS but haven't checked the other auth scenarios (static, env and shared config).

**Comment by zfLQ2qx2** [comment]
I've run into the same issue, works fine on local using my AWS credentials but panics when deployed to the AWS Fargate environment. I'm going to try doing a custom build with PR 2973.
