### ISSUE TITLE
Reverse proxy IP support

### ISSUE THREAD

**Issue by BrianBland** [docker/distribution#298]
For notifications and request logging, the requester's IP address is recorded, but in the case of a registry behind a reverse proxy, this source IP is always the proxy's. I'm proposing we support the `X-Forwarded-For` header, as well as potentially the `X-Real-IP` and maybe others for resolving the requester's IP address.

**Comment by stevvooe** [comment]
@BrianBland Looks like we did this for the `urlBuilder` but not for creating the request record. This needs to be fixed here:

https://github.com/docker/distribution/blob/master/notifications/bridge.go#L46

Do you plan on submitting a PR or do you need us to do this? Either way, we should take care of this right away.

**Comment by stevvooe** [comment]
Looks like we also need to fix this in the contextual logging, as well:

https://github.com/docker/distribution/blob/master/context/http.go#L150
