### ISSUE TITLE
(Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by pedro2555** [docker/distribution#2980]
No joke, every single time I try to get a machine running docker, I fail. I quit, the problem can't be mine, every freaking time the same issue.

You guys get your sh*t together please. 5 hours wasted just today, hopeless looking for what the heck might been causing this.

You known what, I care no less, focker docker.

![image](https://user-images.githubusercontent.com/1645623/63202473-b61a4580-c081-11e9-976b-519189530af5.png)

It just **never** works.

I'm sorry, I haven't read any guidelines or any _how to bug report_ stuff. I have no idea how I can help you, but I'm willing. Yet tired of this crap. I'm sorry, I'm really tired.

**Comment by manishtomar** [comment]
The problem seems to be communicating to registry.gitlab.com. However I can get it to connect from my machine:
```
$ docker login -u abc -p abc registry.gitlab.com
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry.gitlab.com/v2/: unauthorized: HTTP Basic: Access denied
```
Please check your network settings. I am closing this since this not a registry project issue.
