### ISSUE TITLE
document s3 and cloudfront redirect middleware configuration

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#299]
We need to document the common use case of setting cloudfront or s3 redirect middleware for layer downloads. This could belong in either the s3 driver documentation or in the "deploying.md" under an s3 specific section.

**Comment by stevvooe** [comment]
@moxiegirl Do you have enough information to take on this task?

**Comment by RichardScothern** [comment]
Perfect timing.  I was just in the middle of setting this up..

**Comment by RichardScothern** [comment]
https://github.com/docker/distribution/pull/320

**Comment by moxiegirl** [comment]
@stevvooe @RichardScothern perfect! I'll pick that up in a rebase and fit it into what I'm doing.
