### ISSUE TITLE
"docker run" with -p flag is sensitive to order of parameters

### ISSUE THREAD

**Issue by ptype** [docker/distribution#2993]
"docker run" with the -p flag is sensitive to the order of parameters on MacOS 10.14.4 (Docker 2.1.0.1 (37199)). I have found a case where the -p flag appears to be ignored if specified as the last parameter. I have not found this behaviour documented anywhere.

Example:
"docker run -v /Users/x/y/z/.ssh:/root/.ssh q/i:dev -p 6565:6565" does **NOT** forward port 6565 -> 6565

"docker run -p 6565:6565 -v /Users/x/y/z/.ssh:/root/.ssh q/i:dev " **DOES** forward port 6565 -> 6565

**Comment by manishtomar** [comment]
Please open it in https://github.com/docker/for-win.
