### ISSUE TITLE
Support SIGV4 for S3

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#30]
We need to support AMZ authentication version 4 in order to use frankfurt (and we should use it as a default everywhere either way).

It should be possible to simply disable SIGV4, but this should not be documented.

**Comment by stevvooe** [comment]
@AndreyKostov @BrianBland Where are we on this? What PRs supported this issue?

**Comment by AndreyKostov** [comment]
https://github.com/crowdmob/goamz/pull/309
