### ISSUE TITLE
docker run: Misleading error message on mounting --volumes-from a container by a wrong name 

### ISSUE THREAD

**Issue by hugo4711** [docker/distribution#3006]
Docker gives a misleading error message that an image does not exist when really it cannot find a container from which I want to mount a volume.

Docker version 19.03.2, build 6a30dfc

```
[parallels@docker docker-bundler-cache]$ docker run -t auditify/backend:2d51115a5a60729327681bcddd70b740968767da
irb(main):001:0> ^C
[parallels@docker docker-bundler-cache]$ docker run -t --volumes-from DOESNOTEXIST auditify/backend:2d51115a5a60729327681bcddd70b740968767da
Unable to find image 'auditify/backend:2d51115a5a60729327681bcddd70b740968767da' locally
docker: Error response from daemon: pull access denied for auditify/backend, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
[parallels@docker docker-bundler-cache]$ 
```

**Comment by xiaohui-yan** [comment]
I also encountered this problem. Is there any solution

**Comment by thaJeztah** [comment]
This is not related to the code in this repository (which is for the open source image registry). https://github.com/docker/cli/issues/2594 reported this issue as well, and it's fixed on master through https://github.com/moby/moby/pull/41161, which will be in an upcoming release of the docker engine
