### ISSUE TITLE
Docker armhf unable to run arm64v8 containers

### ISSUE THREAD

**Issue by jdonald** [docker/distribution#3008]
I reported this on the forums some years ago: https://forums.docker.com/t/unable-to-run-aarch64-containers-from-armv7-docker/67187

The problem is still there, but it's easier to reproduce now that the Raspberry Pi Foundation provides an aarch64 kernel. To repro on Raspbian Buster:

1. Install Docker CE.

2. Run `sudo rpi-update` to download the latest 64-bit kernel.

3. Edit `/boot/config.txt` add the line `arm_64bit=1`, ideally under the [pi4] section if this is being tested on a Pi 4.

4. Reboot, and confirm `uname -m` shows you're now running an aarch64 kernel.

5.
```
pi@raspberrypi:~ $ docker run -it arm64v8/debian
pi@raspberrypi:~ $ echo $?
159
```
LXC, systemd-nspawn, or plain chroot do not have this problem. They are able to seamlessly jump from a 32-bit userland to a 64-bit container/chroot.

If there is a fundamental reason that this cannot work with Docker's design, it should be documented and the command should provide a more informative message than null output with return code 159.

64-bit Docker containers on Raspberry Pi have a number of use-cases. At this time it seems that it's only practical to run these on non-Raspbian distros that possess a native 64-bit userland.

**Comment by realPy** [comment]
Hello jdonald.
Want to do the same things and have same errors.
Except that work well with --privileged....

**Comment by guysoft** [comment]
@realPy 's solution does work. Anyone has an idea why?

**Comment by realPy** [comment]
@guysoft i think that need some privilege. I’ll try lots of capabilities option from docker to avoid the privileges flag and dont find the good one.
Privilege give all kernel host access  and i thinks the 64 launch need something more from kernel :)

**Comment by guysoft** [comment]
Ok, that got me digging, this also works;

```
sudo docker run -it --security-opt seccomp:unconfined  arm64v8/debian
```
Taken from: https://github.com/moby/moby/issues/20550

**Comment by realPy** [comment]
Good job
I thinks we can find the syscall that is need for that here https://docs.docker.com/engine/security/seccomp/
To restrict more :)

**Comment by guysoft** [comment]
I would say ``CAP_SYS_ADMIN`` Looks like a good candidate.

**Comment by volschin** [comment]
@guysoft  CAP_SYS_ADMIN doesn't seem to be the solution. I tried
`cap-add:
  -ALL`
and also 
`cap-add:
  -CAP_SYS_ADMIN`
and this didn't fix the problem.

**Comment by volschin** [comment]
The problem seem to be the archMap part of the default.json. Replacing this by
`	"architectures": [
		"SCMP_ARCH_AARCH64",
		"SCMP_ARCH_ARM"
	],`
all seem to work.

**Comment by guysoft** [comment]
@volschin What is the path of ``default.json`` when docker-ce is intalled? Can't seem to find it?

Do you mean there is a need to fix the source here?
https://github.com/docker/docker-ce/blob/master/components/engine/profiles/seccomp/default.json

**Comment by volschin** [comment]
I have used it with --security-opt seccomp:default.json for every arm64 container to run. So I have no idea, where a general file could be.
Yes, the source for the default.json to change ist right.

**Comment by guysoft** [comment]
@runcom You commited that default.json, any chance you could provide insight on this?

cc @dmcgowan who is ownter of this repo. We might have a PR bubbeling up here to https://github.com/docker/docker-ce

**Comment by volschin** [comment]
Problem is, that it's fine for running ready images, but you cannot build because own seccomp profile is not available in build command.
https://github.com/moby/moby/issues/21105

**Comment by volschin** [comment]
As it is sometimes I found a solution following some more links
https://github.com/moby/moby/issues/34454#issuecomment-321135510

Adding the parameter to the daemon fixes also the build problem for all containers.

**Comment by dmcgowan** [comment]
Please file Docker related issues at https://github.com/docker/for-linux

**Comment by guysoft** [comment]
@dmcgowan  Done https://github.com/docker/for-linux/issues/1008

**Comment by bonanza123** [comment]
@volschin could you tell me how to implement this work around? Which default.json file do I need to modify (I don't have any on my disc)

**Comment by guysoft** [comment]
I wrote a workaround here:
https://github.com/moby/moby/issues/41092#issue-636455908
I will note that I wrote this in Jun, in the issue tracker that was asked, and got no answer (not even wontfix). This is after being redirected twice to different github issue trackers.
