### ISSUE TITLE
Moby broken by data valdiation in unmarshaller

### ISSUE THREAD

**Issue by cpuguy83** [docker/distribution#3024]
Moby has some registration code to handle OCI manfiests here: https://github.com/moby/moby/blob/6f069f14e6a76f2a3cdf50a089e67429581d7cc8/distribution/oci.go#L15-L28

Notice that it is using `schema2.DeserializedManifest`.

This commit https://github.com/docker/distribution/commit/1d47ef7b801369dc2ca257732ea91d39089ecebc which performs validation of the media type field on unmarshal is breaking that logic.

We can come up with a means of updating Moby... however this code looks wrong to me.

1. Strictly as someone who doesn't spend much time on this codebase it seems like a bit of a smell to do data validation while converting formats (json bytes to go struct).
2. It also seems incorrect to assume that the value of the field is always a particular value this deep in the code.

**Comment by cpuguy83** [comment]
For reference, this is related to moby/moby#39727

**Comment by thaJeztah** [comment]
Interesting, I cannot find what pull request https://github.com/docker/distribution/commit/1d47ef7b801369dc2ca257732ea91d39089ecebc was made from (was it pushed directly to this repository?)

**Comment by thaJeztah** [comment]
Ah, I suspect the "squash and merge" "feature" was used; that's why I hate it; it munges the original commits (and possibly GPG signed commits), and makes it hard to trace-back what PR introduced things.

(I see @cpuguy83 already found the PR; https://github.com/docker/distribution/pull/2076)

**Comment by cpuguy83** [comment]
I actually did not find it just commented on the commit and it showed up in the PR :)
I see there is an ocischema package as part of that same PR so will just use that.

Just as a note, this silently broke moby, though we don't have any tests currently to check oci functionality which we should figure out.

I'm going to go ahead and close this as I don't see the package design changing anyway.
