### ISSUE TITLE
the regexp of digest format in registry api spec cannot match the examples

### ISSUE THREAD

**Issue by jerry-yuan** [docker/distribution#3031]

**Comment by jerry-yuan** [comment]
![image](https://user-images.githubusercontent.com/13380647/66796505-6f8a7f80-ef3a-11e9-8ed0-5521c07f2b86.png)
The regexp `[A-Fa-f0-9_+.-]+` cannot match the string `sha256`

**Comment by manishtomar** [comment]
`sha256` is the algorithm.

**Comment by jerry-yuan** [comment]
@manishtomar But the regexp `algorithm` is just tring to match the algorithm name. Maybe change with some distinct algorithms like `(sha256|md5|...) ` .
