### ISSUE TITLE
Memory leak? Nonpaged pool grows on docker ee on windows server 2019

### ISSUE THREAD

**Issue by veepee78** [docker/distribution#3075]
I'm running few .net core services on my small docker swarm. Some of those services crashes because of missing db. Swarm then tries to start them until db is back online. I have noticed that windows non paged pool memory grows every time while we are updating our development environment. 

It seems that if I run the service as a container, with restart: always, it behaves similar way, growing non paged pool.

![image](https://user-images.githubusercontent.com/3069770/70977564-d8b37e00-20b6-11ea-9413-090efab98bcf.png)

Visible in the graph, a boot, and then the issue. As I removed service from swarm and turned it to container, issue only affects the red computer in the end. Green computer is the node and red manager and node.

used image for the service:
mcr.microsoft.com/dotnet/core/aspnet:2.1

container listing looks like this:
CONTAINER ID NAMES                                                                                                             STATUS                                  PORTS
7809f8673fec PICR_service.41fxd8uz0dw8vw6013bri1vw8.iv5le28mtbay0pijjb0g4cazh                Created
2b61182ee001 PICR_service.41fxd8uz0dw8vw6013bri1vw8.0xv0p3uzo0w9n6d1lhsijx6q7                Exited (3762504530) 5 seconds ago
46583e1cc3ab PICR_service.41fxd8uz0dw8vw6013bri1vw8.pmgr4a5vd2q2yxn402wwak6ft                Exited (3762504530) 22 seconds ago
42c4b87c7dc8 PICR_service.41fxd8uz0dw8vw6013bri1vw8.r99g30m5jtz3z2eor2tt6a2mg                Exited (3762504530) 37 seconds ago
73d8754f6d98 PICR_service.41fxd8uz0dw8vw6013bri1vw8.judriyy00udn88b7h8m4jlak8                Exited (3762504530) 51 seconds ago

compose:
version: '3.6'

services:
  xxx_service:
    image: xxx:6000/xxxservice:latest
    isolation: process
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
    deploy:
      mode: global

PS C:\Docker\CustomerImportService> docker version
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false

PS C:\Docker\CustomerImportService> docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 23
  Running: 16
  Paused: 0
  Stopped: 7
 Images: 53
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: active
  NodeID: 41fxd8uz0dw8vw6013bri1vw8
  Is Manager: true
  ClusterID: j5fpxcb32aq3ywgxd6k2p85j6
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.21.124
  Manager Addresses:
   192.168.21.124:2377
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.914)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 8GiB
 Name: MDEVDOCKERW2
 ID: X3RG:T54V:DNA7:UUVE:7JJY:CC43:35F4:XL3K:2WBM:3JPU:GMLL:SB4X
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  xxx:6000
 xxx:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface

**Comment by dmcgowan** [comment]
This project is related to the open source registry. If you are having problems with Docker EE you should file a ticket with them.
