### ISSUE TITLE
need a way to disable proxy

### ISSUE THREAD

**Issue by jelmd** [docker/distribution#3077]
Took me about a day to find out, that `docker login remote.registry...` actually passes the command to the docker daemon started via systemd  and uses the proxy settings set via systemd env vars. Unfortunately the proxy is in a DMZ and thus cannot fetch any resources within the internal, i.e. private network. And thus one is not able to use any docker registry within the internal/private network.

Therefore an argument or env var is needed, which instructs docker to not use a proxy but directly talk to the related sites, similar to wget's `--no-proxy` option or `no_proxy` env var, or curl's `--noproxy` option or `NO_PROXY` env var.

**Comment by dmcgowan** [comment]
This needs to be filed with Moby or the Docker CLI
