### ISSUE TITLE
Email not sent in Docker Login to Auth Server

### ISSUE THREAD

**Issue by ekristen** [docker/distribution#308]
It appears that when performing a `docker login` against the registry v2, no email address is sent to the token auth server.  I believe this to be a bug.

This is a deviation from v1 and I believe it necessary to include the email address for account identification, password resets, etc.

Leaving the email address out is acceptable if the docker login process should no longer be allowed to create accounts, but I think would be bad user experience and according to the docker client documentation login should still register accounts.

/cc @stevvooe @jlhawn

**Comment by dmp42** [comment]
Creating accounts from the "login" command is a terrible idea in the first place IMO.

**Comment by ekristen** [comment]
@dmp42 perhaps, however it does provide for a nice user experience all from the command line.

If this is to change that is fine, but I believe there should be a `docker register` for example to handle this then. If we remove this functionality from the client entirely then it puts the burden on having a web based UI on the auth server to register accounts which I believe would be less than ideal for user experience.

**Comment by ekristen** [comment]
@dmp42 either way for feature parity and with the impending 1.6 release I think that this needs to be fixed to submit the email address somehow to the auth server.

**Comment by ekristen** [comment]
Seems like this needs to be done on the docker client side. Around here (https://github.com/docker/docker/blob/08b2f5b9415f566f5f80c3ff26ff35ed21035541/registry/token.go#L55) I would send email if the `scope` is empty.

**Comment by dmp42** [comment]
> @dmp42 perhaps, however it does provide for a nice user experience all from the command line.

I disagree, and I think this is very odd currently.
For example, git does *not* provide a way to create "accounts" on remote git repositories.
Furthermore, such a mechanism imposes undue constraints on the registry registration mechanism and is a security risk (not to mention questionable UX currently).

The functionality is not removed from the client, it is still present in the v1 code, so, I don't think we are loosing anything here (it's not part of the v2 protocol, though).

Would be happy to discuss this more, and if you still disagree, by all means bring this up for discussion as a proposal for the v2 protocol.

**Comment by ekristen** [comment]
> I disagree, and I think this is very odd currently.

I agree that the implementation could be a little better, perhaps a separate register command, or prompting to verify password, etc.

> For example, git does not provide a way to create "accounts" on remote git repositories.

I don't see this as a valid comparison. It all depends on implementation. Git was never design to be centralized with authentication, it has evolved over time. Solutions like Gitosis allows for management of repositories via git. GitHub has had to develop software specifically to manage permissions for git repos.

AFAIK Docker was designed from near day 1 to have a registry with authentication, it makes sense to have account creation in the command line client when the public registry is the primary place and by default the only place to get images. (especially for new users)

> Furthermore, such a mechanism imposes undue constraints on the registry registration mechanism and is a security risk (not to mention questionable UX currently).

How is it imposing undue constraints? How is it a security risk? 

There is nothing to say that the index (in v1) or the auth server (in v2) HAS to accept the user's information and create the account, that is entirely up to the implementation of the auth service. If you take a look at my index implementation for v1, there is an option to disable account creation via docker login, I plan to do the same for v2.

> The functionality is not removed from the client, it is still present in the v1 code, so, I don't think we are loosing anything here (it's not part of the v2 protocol, though).

You are correct that as long as v1 registry is being used, no functionality is lost. However as I understand it Docker internally is working on moving to the new token auth server and using registry version 2 with the public registry, this would be a loss in functionality, as the auth service would never be able to know the email address of new users.

> Would be happy to discuss this more, and if you still disagree, by all means bring this up for discussion as a proposal for the v2 protocol.

Just point me to where I can bring this up. I think it is the only logical step unless the docker login process is going to be changed for v2 and no longer allow users to register via the client.

**Comment by dmp42** [comment]
Thanks for your answer @ekristen

> it makes sense to have account creation in the command line client when the public registry is the primary place and by default the only place to get images. (especially for new users)

You don't need an account to consume public images.
You do need one to publish images, and to consume private images, true.

> I agree that the implementation could be a little better, perhaps a separate register command, or prompting to verify password, etc.
> [...]
> How is it imposing undue constraints? How is it a security risk?

The implementation *must* be better IMO.

UX and undue constraints: 

 * docker currently reports account activation is required on any registry (see for example: https://github.com/docker/docker/issues/7376) (causing quite some confusion)
 * implied account creation on a "login" command is (very) deceptive

Security risks:

 * registries without validation mechanisms: fat-fingering your account name will transparently create a new account on that registry, and then happily let you publish your (possibly private) content into public.
 * having an endpoint that would blindly create account without any sort of restriction opens the door for massive spam / dos

Other comparable systems: IIRC neither `npm`, nor `pip` (others?) let you create an account on the command line.

Either way, you probably need a UI to perform account validation, or let people manage/delete their account (unless you want to live without any of that, but then, what type of registry is it?).

> Just point me to where I can bring this up. I think it is the only logical step unless the docker login process is going to be changed for v2 and no longer allow users to register via the client.

To summarize:

 * I'm not inherently *opposed* to such a feature, and this is definitely an open-ended conversation
 * the current v1 implementation of this feature is ill-formed, and either require manual activation through an email + web browser (defeating the purpose), or is a dangerous feature
 * adding this to the v2 protocol is certainly open to discussion, in the form of a proposal (either here, or on docker/docker)
   * that proposal should detail the UX (probably a separate command, like you suggested with "register")
   * normative information on what an auth service should do if (not) implementing this must be documented extensively (handled error codes in different conditions, etc)
 * v2 is an open protocol, and we can certainly extend it by adding (any) new functionality - as long as they are properly thought about and documented (to avoid the kind of snafoos that v1 suffered from)


Also, I would definitely encourage you to reach out to @stevvooe or me on irc to kick this of.

Thanks again for caring, and for your ideas here - this discussion is certainly welcome!

Cheers.

**Comment by ekristen** [comment]
@dmp42 point taken with respect to pip, npm, etc ...

I'm all for moving it out of the client and into some other mechanism (ie. website)

My main question is this ...

With version 2 should account creation be allowed via the docker client? 

If no, then the client needs to have 2 workflows, one for v1 and one for v2 and the documentation needs to reflect this, both on the website and in the client itself.

If backwards compatibility is a concern then v2 would need to still send an email address.

Ultimately whether the index/auth system actually creates an account or not has nothing to do with the docker daemon or client.  There is nothing stopping me from using the basic auth creds, sent by the client to the auth service to receive a token, to create an account for the user.

**Comment by stevvooe** [comment]
@ekristen I'm not fully caught up on the back and forth at this point, but I think would be right to say that the v1 login architecture was really oriented towards getting up and running. While this is a valuable feature, overloading `docker login` with registration was an architectural mistake, probably made out of expediency. As a user, I would find it to be unexpected to register an account during a login process.

That said, the question arises, what features should the docker daemon provide? Should it have full user management in a `docker register` command? How does it work? What protocols does that support? User management all seems way outside of the scope of the docker project.

For your use case, where you are building an "index" that has login and registration, we do have to ask how one would do user management via the docker client, if at all. If this is as simple as sending a user email address with the token retrieval, we may want to explore that. Another option may be to have a cli that interacts with your system for user management. The latter approach would provide a lot more flexibility and security, at the cost of some convenience.

**Comment by ekristen** [comment]
I don't think this needs to be open anymore? email was completely deprecated.

Thanks for the hard work guys and girls. Cheers!
