### ISSUE TITLE
Synology Docker, "Open Docker Hub Page" links use the wrong url

### ISSUE THREAD

**Issue by lightmaster** [docker/distribution#3102]
I've noticed for a lot of the packages, the blue icon that opens the Docker Hub page for the package uses an invalid url. For instance, the button for Home Assistant opens to "https://registry.hub.docker.com/u/homeassistant/home-assistant/", whereas it should open to "https://registry.hub.docker.com/r/homeassistant/home-assistant/" (note the "u" vs "r" after ".com"). This seems to be an issue with any package that is listed as "xxxxxx/yyyyyy" but not an issue for packages like "nginx" that don't have the forward slash in their name.

**Comment by thaJeztah** [comment]
Please open a support ticket / bug report at Synology; this is a bug in their software, not this repository.

I'll close this ticket, but feel free to continue the conversation
