### ISSUE TITLE
containerd.io packages missing in docker-ce for Ubuntu eoan (19.10)

### ISSUE THREAD

**Issue by angelgruevski** [docker/distribution#3104]
While installing Docker-CE, following the instructions on the web site, I found out that containerd.io package is not available in the repo for Ubuntu eoan

This is the repo that I am using deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan stable
![docker](https://user-images.githubusercontent.com/57411081/75058844-0d3f1e00-54dc-11ea-8b1f-9585a630e1a9.png)

**Comment by manishtomar** [comment]
Please open this at https://github.com/docker/for-linux
