### ISSUE TITLE
Docker Registry "token signed by untrusted key with ID"

### ISSUE THREAD

**Issue by PascalKu** [docker/distribution#3149]
Hi there,

I am trying to spin up a private docker registry. Still found this library to create the kid given in your detailed implementation documentation: https://github.com/keycloak/keycloak/blob/master/services/src/test/java/org/keycloak/procotol/docker/installation/DockerKeyIdentifierTest.java
https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/protocol/docker/DockerKeyIdentifier.java

But whenever I am going to return a given token like this:

```java
        final File file = new File("auth.key");

        Security.addProvider(new BouncyCastleProvider());
        final PrivateKey privateKey = PemUtils.readPrivateKeyFromFile(file.getPath(), "RSA");
        final long time = System.currentTimeMillis() / 1000;

        final JWTCreator.Builder builder = JWT.create();
        final Map<String, Object> headerMap = new HashMap<>();
        headerMap.put("kid", new DockerKeyIdentifier(privateKey).toString());

        builder.withClaim("iss", "test");
        builder.withClaim("aud", "localhost:5000");
        builder.withClaim("sub", subject);
        builder.withClaim("nbf", time - 60);
        builder.withClaim("exp", time + 3600 * 2);
        builder.withClaim("iat", time);
        builder.withClaim("jti", UUID.randomUUID().toString());
        builder.withClaim("access", access);

        return builder
                .withHeader(headerMap)
                .sign(Algorithm.RSA256(null, (RSAPrivateKey) privateKey));
```

My docker registry says "`level=error msg="token signed by untrusted key with ID: \"XROC:JDIA:2AIC:OX2O:AP44:GC6V:N3AV:FAMT:N2VA:TAZN:AIW6:GGNO\""`"

And I am now wondering why. My token still looks like this: `eyJraWQiOiJYUk9DOkpESUE6MkFJQzpPWDJPOkFQNDQ6R0M2VjpOM0FWOkZBTVQ6TjJWQTpUQVpOOkFJVzY6R0dOTyIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJhdWQiOiJsb2NhbGhvc3Q6NTAwMCIsInN1YiI6ImFkbWluIiwibmJmIjoxNTg3NjAyOTY0LCJhY2Nlc3MiOlt7Im5hbWUiOiJzYW1hbGJhL215LWFwcCIsInR5cGUiOiJyZXBvc2l0b3J5IiwiYWN0aW9ucyI6WyJwdXNoIl19XSwiaXNzIjoidGVzdCIsImV4cCI6MTU4NzYxMDIyNCwiaWF0IjoxNTg3NjAzMDI0LCJqdGkiOiJlYjYxNTJhMi1kNzk3LTRiYmMtYTVjNS03OTE0YzY5M2RkMDYifQ.AsR1dRAUtDgYABVEf6WakcBZN_g0JJjvVQQ1-R15oD_7buLD6RDkC1HEOBEhK4Rzwc3GEvh3-ji5mQX7P_hB7rOZX1KBuPPkMHlq8gP_VuNcKZwLu4NwkGulr6MR0LJVt2zlYZ5-CFhG-5y6WttKdAwnHoED2OvsUt9xlHu19fFQEs331tr5BgYEMIZDxJyXaJ78_1e8ovbf5h40HdqsSEMTFdLTLcs0IsndUExaNgRl7qiD8EcUAe7GTccVo8Cu5FmzlRxFldXwehfltxO_3bseH32E-CyDRDZBQRN_VfX1x8uEthxzjT1ALm19pf7-e032x-FiN_wlt6FoueHO-v5wYNEV-l5alZAzP7xxUlA4Qxp9iGyfPhkuRp9bJEGuNAGnj1S_URmU2VTOEO2PpguiszwKR27Y-tYFpGHqMdv_kf6FTqwylFTNg8RVm8UdA7fmZHZgkxdym4SlvkexAKDBASqBm8_3fiIZwjbgrLTVKKVPj5p6yADSBo9aVyN1jEuRI2Y4zubHhysAhHovciZF76kiW2AR8NDQUp3RZ5jLjhk9HpHmfCyslF61MHNik_YEjThL2lrcTxSbg1TelvsUOtDYaun0_gK7dMqRwxtvbHJnWFDL-L6PP9IFtxkomGwEN7MUjrjd0MSDf0LkdrAJ_xs-mQPUyqKr57mkjTM`

**Comment by PascalKu** [comment]
I still checked the given token using my cert (stored in the registry config) and my private key (stored in the token creation app) and the page https://jwt.io/ still says that the token is valid?!

**Comment by dmcgowan** [comment]
I suggest requesting help on slack or from keycloak. It is hard to track down and debug an external tools generation. This likely an error on the generation or configuration side rather than a registry bug, feel free to re-open if you think this can be traced back to a bug. When opening the bug report, please include configuration, registry version, and sample token which produced the error.

**Comment by alexp1917** [comment]
running into this as well, what is key id _supposed_ to be?
