### ISSUE TITLE
Ingest/Import Manifests from S3

### ISSUE THREAD

**Issue by LunaticZorr** [docker/distribution#3152]
We had a harbor instance running with S3 as the storage backend. The instance failed and we've re-created it, but the images are gone. We still have them on S3 and would like to import them into Harbor again. Harbor does not support this natively and we want to create a separate Docker reigstry were to import the images, and then sync with harbor. Is there anyway of importing/ingesting docker images/manifests from S3? Or to run up a docker registry using the existing S3 storage backend?

Thanks!

**Comment by dmcgowan** [comment]
You should probably ask the Harbor team about this. I'm not sure what you mean by "the images are gone", but from this projects perspective, the images along with all the necessary metadata are stored in S3. Pointing at the same S3 storage shouldn't require any extra importing/ingesting. Making sure the S3 driver is configured the same is important.
