### ISSUE TITLE
Inconsistent CLI and Docker Engine on Centos

### ISSUE THREAD

**Issue by soemeier** [docker/distribution#3164]
When installing docker-ce version 18.09.9 via the yum repository the automatically installed docker-ce-cli is of version 19. When using the cli I get the following error message:

`Error response from daemon: client version 1.40 is too new `

I can manually fix this by first installing docker-cli in the proper version but it would be nice if this would work correctly out of the box.

**Comment by dmcgowan** [comment]
Please file Docker related issues at https://github.com/docker/for-linux
