### ISSUE TITLE
Certificate location for notification endpoints that use self-signed certificates

### ISSUE THREAD

**Issue by LuckyF** [docker/distribution#3182]
Hey,
in v2.6.0 the feature **"Enable notifications to endpoints that use self-signed certificates"** was added.
Does anyone know where I have to mount the certificates into my registry container?

Maybe _/usr/local/share/ca-certificates_?

**Comment by jtherin** [comment]
Same question, we have a custom CA and it would be nice if we could to avoid to build our own container :/

**Comment by jtherin** [comment]
https://github.com/docker/distribution/pull/1826 was incomplete, missing configuration part.

**Comment by jtherin** [comment]
Why closing it ? It still an issue :/
