### ISSUE TITLE
Registry doesn't use entrypoint for image

### ISSUE THREAD

**Issue by bfirsh** [docker/distribution#319]
I expected to be able to do this with the image:

```
$ docker run registry --help
exec: "--help": executable file not found in $PATH
FATA[0000] Error response from daemon: Cannot start container c0e8d6f152480ba6b7b97986f50431cfcf821099c1890dec033a2d6868e3525b: [8] System error: exec: "--help": executable file not found in $PATH
```

I have to run `docker run registry registry ...` if I want to pass any options to the registry, which seems a bit odd.

FWIW, Swarm also works with an entrypoint: `docker run swarm --help`.

Thoughts?

**Comment by stevvooe** [comment]
Please submit a PR with the desired fix.

**Comment by bfirsh** [comment]
Done!
