### ISSUE TITLE
Repo Name Format Forbids 3+ Consecutive Underscores, but Allows 3+ Consecutive Dashes

### ISSUE THREAD

**Issue by davidwarshaw** [docker/distribution#3194]
One or two underscores is ok:
```
$ docker build -t my__repo .
Sending build context to Docker daemon  35.84kB
...
```
Three or more underscores is not ok:
```
$ docker build -t my___repo .
invalid argument "my___repo" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
```
However, three or more dashes _is_ ok:
```
$ docker build -t my---repo .
Sending build context to Docker daemon  35.84kB
...
```

```
docker version
```

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.39
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:50 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Culprit appears to be this line:
https://github.com/docker/distribution/blob/master/reference/regexp.go#L13

**Comment by dmcgowan** [comment]
> 	// separatorRegexp defines the separators allowed to be embedded in name
	// components. This allow one period, one or two underscore and multiple
	// dashes.

Yeah, and it is commented as such. At some point years ago someone made an argument for this and it was accepted. At this point, changes to the regexp won't be made without strong arguments for the change and evidence of low impact.

**Comment by davidwarshaw** [comment]
It looks like you've been on this beat for a while!
https://github.com/dmcgowan/distribution/commit/6bd5b8c24e66ba67a54541d72f1ad8d5cc17e677

It's surprising and weird to treat dashes and underscores differently in this way, but I follow the backstory and understand your reluctance to change it now.

I suggest adding a little context to the comment, so people know this is not a mistake: https://github.com/docker/distribution/pull/3201
