### ISSUE TITLE
How to Get All Tags from Docker Hub as Shell Script

### ISSUE THREAD

**Issue by CloudNetwork** [docker/distribution#3199]
have one shell script when i execute it showing only 64 tags from 300 tags docker hub.

Here is the screenshot of it.

Below is the command which i'm executing in shell script through curl.

"IMAGE_TAGS=$(curl -s -H "Authorization: JWT ${HUB_TOKEN}" "https://hub.docker.com/v2/repositories/$username/issues/tags/?page_size=300" | jq --raw-output '.results[] | .name')"

Even after giving page_size also it is not showing my all tags

Please help me how can i solve it @docker-jenkins @docker-ci-scanner @docker-autobuild 
![tags](https://user-images.githubusercontent.com/7812871/86933265-fda53680-c157-11ea-8158-8227e2a8fcd1.png)

**Comment by thaJeztah** [comment]
I think Docker Hub has a hard limit for number of results that are returned at once, but you can use the `page` option to get the next set of results; 

https://hub.docker.com/v2/repositories/library/busybox/tags/?page_size=25&page=2

This is a question related to Docker Hub though, and not directly related to the open source registry maintained in this repository, so I'll close this issue here, but feel free to continue the conversation

**Comment by CloudNetwork** [comment]
@thaJeztah Thanks for your reply but after giving page size and page option in link its showing only 100 tags but i have more than 100 of tags in my repo.
I want to get all my image tags in one command 
![image](https://user-images.githubusercontent.com/7812871/87017353-7c987e80-c1ed-11ea-899a-1ba47b87cd4e.png)

This is my command above this  is screen shot of it.  Whatever im changing  page number its showing only 100 image tags.
IMAGE_TAGS=$(curl -s -H "Authorization: JWT ${HUB_TOKEN}" "https://hub.docker.com/v2/repositories/fxlabs/issues/tags/?page_size=3000&page=3" | jq '.results | .[] | .name') 

I want all my image tags to get in one in all command my total tags are 500 image tags that should show in above command which is not showing

**Comment by thaJeztah** [comment]
I don't think that'd be possible; docker hub limits the maximum number of results per page (which may have been done for security/DOS protection, but that's only my assumption), so if you want all tags, you'd have to make multiple API calls and combine the results.

**Comment by CloudNetwork** [comment]
@thaJeztah  Please tell me how i can combine and single API calls if u want i can share you my script.

**Comment by thaJeztah** [comment]
You'd have to create a loop, and append the results in a variable before returning.

I see the Docker Hub API returns a `next` field that shows if there's more results, and what URL to use to get the rest; 

https://hub.docker.com/v2/repositories/library/busybox/tags/?page=2&page_size=50

```json
{
  "count": 147,
  "next": "https://hub.docker.com/v2/repositories/library/busybox/tags/?page=3\u0026page_size=50",
  "previous": "https://hub.docker.com/v2/repositories/library/busybox/tags/?page=1\u0026page_size=50",
  "results": []
}
```

And that field is `null` if there's no more pages;

https://hub.docker.com/v2/repositories/library/busybox/tags/?page=3&page_size=50

```json
{
  "count": 147,
  "next": null,
  "previous": "https://hub.docker.com/v2/repositories/library/busybox/tags/?page=2\u0026page_size=50",
  "results": []
}
```

So you can either use that field and loop until the `next` field is `null`

Or just increment `page` in your loop until you get a response that has no results, e.g. here's what page 999 returns;

https://hub.docker.com/v2/repositories/library/busybox/tags/?page=999&page_size=50

```json
{
  "count": 0,
  "next": null,
  "previous": "https://hub.docker.com/v2/repositories/library/busybox/tags/?page=3\u0026page_size=50",
  "results": []
}
```

In that response, `count` is `0`, and `results` is empty, so you'll know that you reached the end of the results

**Comment by CloudNetwork** [comment]
@thaJeztah 
How can i delete private or public repository from docker hub 

i try with this command 
 curl -s -v -H "Authorization: JWT ${HUB_TOKEN}"  -X DELETE  "https://hub.docker.com/v2/repositories/mohd/test2/" 

got error
400 BAD REQUEST
Connection #0 to host hub.docker.com left intact
{"detail": "There was an error. The repository was not deleted."}


from UI also its not removing and i email to support@docker.com 4 times but no reply came.
