### ISSUE TITLE
Support secure on S3

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#32]
It should be possible to toggle on/off secure transport to the S3 backend driver (should be off by default if there is a huge perf impact).

Also needs documentation in the README about how to configure that.

**Comment by dmp42** [comment]
Thanks.
What's blocking v4 auth?

**Comment by AndreyKostov** [comment]
I hadn't finished fixing it with our s3 client (now done). I`ll have a pull request with v4 auth as a parameter shortly.

**Comment by BrianBland** [comment]
Fixed by #18
