### ISSUE TITLE
create official image for registry 2.0

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#322]
We need to provide an official image for the new registry. Let's make one.

https://github.com/docker-library/official-images/blob/master/library/registry

**Comment by dmcgowan** [comment]
Will this image need to serve both v1 and v2 or will we provide a Docker Compose script to run v1, v2, and a configured load balancer?

**Comment by dmp42** [comment]
@dmcgowan this one should be v2-only.
The old-one (registry), we should probably use to cram in v1+v2+nginx (or go the compose way?).

**Comment by dmcgowan** [comment]
Understood, #82 is related and should use this new official image

**Comment by stevvooe** [comment]
Done!
