### ISSUE TITLE
Manifest not found in registry pass-thru mode, not sure how to debug

### ISSUE THREAD

**Issue by zfLQ2qx2** [docker/distribution#3236]
I'm not sure how to debug this. I've set up the registry running is pass-thru mode and as a test I'm trying to pull alpine:latest:

My test command is -- curl -v -v -v http://127.0.0.1:5000/v2/alpine/manifests/latest

{"@timestamp":"2020-08-27T05:11:25.8813908Z","@version":"1","go.version":"go1.13.14","http.request.host":"127.0.0.1:5000","http.request.id":"66c7eaa8-979d-4529-a9e1-d3ebc42a7848","http.request.method":"GET","http.request.remoteaddr":"127.0.0.1:51170","http.request.uri":"/v2/alpine/manifests/latest","http.request.useragent":"curl/7.69.1","level":"info","message":"Challenge established with upstream : {https   registry-1.docker.io /v2/  %!s(bool=false)  } \u0026{{{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} map[https://registry-1.docker.io:443/v2/:[{bearer map[realm:https://auth.docker.io/token service:registry.docker.io]}]]}","vars.name":"alpine","vars.reference":"latest"}
{"@timestamp":"2020-08-27T05:11:26.1101883Z","@version":"1","err.code":"manifest unknown","err.detail":"unknown tag=latest","err.message":"manifest unknown","go.version":"go1.13.14","http.request.host":"127.0.0.1:5000","http.request.id":"66c7eaa8-979d-4529-a9e1-d3ebc42a7848","http.request.method":"GET","http.request.remoteaddr":"127.0.0.1:51170","http.request.uri":"/v2/alpine/manifests/latest","http.request.useragent":"curl/7.69.1","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"405.6718ms","http.response.status":404,"http.response.written":96,"level":"error","message":"response completed with error","vars.name":"alpine","vars.reference":"latest"}
127.0.0.1 - - [27/Aug/2020:05:11:25 +0000] "GET /v2/alpine/manifests/latest HTTP/1.1" 404 96 "" "curl/7.69.1"

I've tried both anonymous and with my dockerhub name/password. It looks like I'm hitting registry-1.docker.io. I've tried other tags with the same result.

**Comment by jferr** [comment]
I'm watching along on this issue.  I've having the identical issue. I get similar results as shown above via curl to "get" a manifest from dockerhub via my pass-through

If I try this via the docker client (setting the repository_mirror in my daemon config) I see
    error authorizing context: basic authentication challenge for realm "Registry Realm"
I've tried w/o creds and w. my dockerhub creds.

**Comment by zfLQ2qx2** [comment]
I bought a docker pro subscription and i've opened a support ticket there also, I'll update this issue when I get a response. We pull the same base images hundreds of times a day in our CI/CD, I think we're going to save significantly on our transit costs if I can get this working. I've followed all the online guides and blogs I could find but seem to be missing a detail someplace.

**Comment by zfLQ2qx2** [comment]
@jferr I gave up, canceled my Docker pro subscription and disputed the charge, did not receive a response to the support ticket. I'm not sure their master plan but I can be ignored for free.

**Comment by binman-docker** [comment]
Hi @zfLQ2qx2 - sorry to hear about your experience. While your support request shouldn't have fallen through the cracks, Docker Hub support can only help with requests related to Docker Hub and not the open-source registry project. However, I understand you are trying to run a mirror of Hub and I'd like to help.

I think in this case the error is simply an oversight in the URL structure. You are lacking the repository namespace, which for the alpine image I assume you are trying to pull, is actually "library" (all official images fall under this namespace). Docker Engine of course allows you to just run the shorthand "docker pull alpine:latest" because internally it recognizes the lack of a namespace and translates that to "docker pull library/alpine:latest". But when you directly issue a curl request without a namespace, registry itself has no such logic.

On a toy deployment of registry as a mirror, adding the namespace makes everything work just fine for me:

```
$ docker run -d -p 5000:5000 -e REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io" --na
me registry registry:2

$ curl http://localhost:5000/v2/library/alpine/manifests/latest   
{
   "schemaVersion": 1,
   "name": "library/alpine",
   "tag": "latest",
   "architecture": "amd64",
   "fsLayers": [
...
```

Hope that helps!

**Comment by zfLQ2qx2** [comment]
@binman-docker I just noticed your response tonight, I will give it a shot tomorrow! My goal is to be a good netizen and not hit Dockerhub every time a CI/CD job runs, if I can get this working it would be a much better solution then the alternative.

**Comment by zfLQ2qx2** [comment]
@binman-docker That worked! docker pull <proxy_address>:<port>/library/alpine:latest

**Comment by kpdecker** [comment]
In case this helps someone: Saw similar behaviors in my own environment. Due to a variety of factors around our network, the registry client was able to connect to registry-1.docker.io, but could not connect to auth.docker.io. There were no logs to affirm this theory, but upon adding the proper DNS entry for auth.docker.io, the proxy started working.

**Comment by joshcass** [comment]
Thanks @kpdecker my issue around this was also auth related and wasn't surfacing anywhere but your comment led me in the right direction

**Comment by Semmu** [comment]
😠 Goddamn, I faced the same issue and didn't know what the hell was wrong with my setup, and turns out `library/` was missing in my pull commands...

```
$ docker pull internal.registry.tld/alpine:latest
Error response from daemon: manifest for internal.registry.tld/alpine:latest not found: manifest unknown: manifest unknown
```

vs

```
$ docker pull internal.registry.tld/library/alpine:latest
latest: Pulling from library/alpine
Digest: sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
Status: Downloaded newer image for internal.registry.tld/library/alpine:latest
internal.registry.tld/library/alpine:latest

```

❓ Why the hell is this not mentioned anywhere in the official docs? https://docs.docker.com/registry/configuration/

**Comment by milosgajdos** [comment]
First things first @Semmu, your language is inappropriate, so please in the future restrain from the strong wording you used in your comment.

Second, beware, `distribution` project was donated to CNCF and `Docker` (the company) no longer owns it, however, it continues to maintain the documentation until CNCF puts up their own documentation pages, but that does not make them _official documentation_. 

As for the official images being stored in the `library` namespace. Every repository must live in its own namespace -- official images are not an exception to this rule. Whilst there are instances throughout the documentation I agree this should be highlighted in a better way to avoid confusion for the new adopters. Feel free to open a PR. We would be very accepting of it

**Comment by Semmu** [comment]
Hey @milosgajdos,

Sorry for my language, I edited my comment. I was just very frustrated after trying to debug this issue for literally hours.

Thanks for the explanation! I guess the main source of confusion is the implicit behavior of the docker pull CLI as it automatically prepends `library/` when no namespace is defined and we're pulling from the official Docker Hub.

**Comment by milosgajdos** [comment]
> I guess the main source of confusion is the implicit behavior of the docker pull CLI as it automatically prepends library/ when no namespace is defined and we're pulling from the official Docker Hub

yes, this is correct; this was hardcoded many moons ago and now millions of clients depend on its working as is. That being said, as you had discovered pulling with an explicit `library` namespace works like a charm. We must make this clearer somehow, I agree.
