### ISSUE TITLE
Prevent failing notifications from bringing the system down

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#324]
As discussed briefly yesterday.

Currently, the notifications system is *too reliable*.
In case of a failing delivery on a specific notification that would be triggered regularly, it would pile-up and consume memory on the system.
Ultimately, flushing the queue when the other system would be back online would probably trigger a massive blow to it.

Is there a simple way to specify a queue limit size? (0 would mean current behavior for people willing to take chances, anything else would drop on the floor oldest failed notifications).

WDYT?

**Comment by stevvooe** [comment]
Which messages should be dropped?
Should we just have an endpoint that can flush a notification queue?
A restart will clear the queue. Would it be okay to have a monitoring system restart the instance after a threshold has been reached?

If the endpoint can't follow the [monitoring and considerations section](https://github.com/docker/distribution/blob/master/docs/notifications.md#monitoring), should we be building workarounds?

**Comment by dmp42** [comment]
Agreed - compromising code / design is not the right approach.
Queue size monitoring by another system is the way to go.
