### ISSUE TITLE
CentOS repo is broken

### ISSUE THREAD

**Issue by bitva77** [docker/distribution#3262]
Following the directions here:  https://docs.docker.com/engine/install/centos/

When I go to install docker:  `sudo yum install docker-ce docker-ce-cli containerd.io`

I get the following error:

```
https://download.docker.com/linux/centos/7Server/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

and can verify that it certainly does not exist.

It looks like the new repo path is:  `https://download.docker.com/linux/centos/7/x86_64/stable/`

Can the repo be fixed?  Or can we update the documentation to say it won't work?  Anything to prevent other poor souls like me from spending time being all "wtf is wrong with my setup"  :) 

Thanks!

p.s. we can manually update the `/etc/yum.repos.d/docker-ce.repo` with the correct `baseurl` to move forward.  But maybe that could be added to the documentation as well?  or the repo fixed.  either way.

**Comment by techknowlogick** [comment]
This repo is for the docker registry software, the [docker forum](https://forums.docker.com/) may be better suited for reporting this issue.

**Comment by bitva77** [comment]
Looks like someone got it here:

https://github.com/docker/for-linux/issues/1111

What a shit show.  RIP Docker.
