### ISSUE TITLE
Blacklist 1.5

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#327]
1.5 will not be able to read sha layers, making it unable to consume late produced content (>=1.6), though it does speak the protocol.
In order to avoid confusion, and make things clear (and easier for v1 fallback mechanism), maybe we can refuse (404) to serve pings for 1.5 clients? (and also make it clear in the documentation that 1.6 is the first supported client).

**Comment by dmp42** [comment]
I guess only version 1.5 and up is able to use v2 protocol, so, technically, filtering on just (all) 1.5 should be enough. To the other point: I don't think we are going with a modified 1.5.X that can cope with sha.

On the other hand, I see no reason to allow for anything older, so, forbidding <=1.5 would certainly work as well.

Bottom-line: the simpler of the two solutions, the better.

**Comment by stevvooe** [comment]
@dmp42 Will this conflict with any other backwards compatibility efforts?

**Comment by dmp42** [comment]
I don't think it will.

**Comment by spesnova** [comment]
Hi, I'm testing docker/distribution v2.0.0-rc.4 to replace python-registry.
I got following error with docker client 1.5.0

```bash
$ docker -v
Docker version 1.5.0, build a8a31ef

$ docker run -d -p 5000:5000 --name registry registry
$ curl -I localhost:5000/v2/
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Date: Thu, 16 Apr 2015 09:24:53 GMT

$ docker pull debian:jessie
$ docker tag debian:jessie localhost:5000/debian:jessie

$ docker push localhost:5000/debian:jessie
511136ea3c5a: Image push failed
FATA[0000] Error pushing to registry: mux: variable "debian" doesn't match, expected "^(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/){1,4}[a-z0-9]+(?:[._-][a-z0-9]+)*$"
```

And it works with docker client 1.6.0 rc7

It looks new registry supports docker 1.5.0 as far as I know. 

> An implementation of the Docker Registry HTTP API V2 for use with docker 1.5+.
 [distribution/README.md at master · docker/distribution](https://github.com/docker/distribution/blob/master/README.md)

Should I wait for new registry has backwards compatibility, or should I wait for docker 1.6.0's release?

**Comment by dmp42** [comment]
@spesnova 1.5 is *not* supported.
Fixing the doc in #371

**Comment by spesnova** [comment]
> 1.5 is not supported.
> Fixing the doc in #371

OK. thanks!

**Comment by stevvooe** [comment]
@dmp42 Should we do this at the proxy-level?

**Comment by dmp42** [comment]
@stevvooe rather in the registry I think. WDYT?

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/distribution/issues/484, reading this now, that may be a (partial?) duplicate

**Comment by dmp42** [comment]
This here is about modifying code so we respond 404 to 1.5 clients.
#484 is about documenting the fact we support only 1.6 clients.

**Comment by thaJeztah** [comment]
@dmp42 the top description mentions;

> and also make it clear in the documentation that 1.6 is the first supported client

that's why I thought it was overlapping with this issue :)

**Comment by dmp42** [comment]
@thaJeztah agreed :)

**Comment by stevvooe** [comment]
Rather than introduce a regular expression that may cause future issues (please see [this](http://www.networkworld.com/article/2691814/software/why-did-microsoft-skip-windows-9-and-jump-to-windows-10.html)), let's just wait out the disappearance on 1.5. The support issues haven't been all that bad.

We can reopen if this gets worse.
