### ISSUE TITLE
Docker updates for macOS High Sierra

### ISSUE THREAD

**Issue by idontusenumbers** [docker/distribution#3274]
Despite turning off automatic updates
![image](https://user-images.githubusercontent.com/1175031/96170877-c7f7b280-0ee9-11eb-83a6-a3c856b49c22.png)

Docker keeps telling me updates aren't available. It sends these warnings in pairs, and they don't even mention they are for Docker.
![image](https://user-images.githubusercontent.com/1175031/96170814-b1e9f200-0ee9-11eb-8325-f7aa8ef374a1.png)

Can you make just one more update to fix the automatic updates feature so it doesn't check when the option is turned off? The pairs of system modal dialog boxes come up more than once a day.

**Comment by ingshtrom** [comment]
You should be reporting this in https://github.com/docker/for-mac/issues. This repository is for the open source registry and it's related spec as described [here](https://docs.docker.com/registry/)

**Comment by idontusenumbers** [comment]
Created https://github.com/docker/for-mac/issues/4996

I'll close this one.
