### ISSUE TITLE
Unable to set OomKillDisable via rest API

### ISSUE THREAD

**Issue by nfacha** [docker/distribution#3294]
Been playing around with the Docker REST API (https://docs.docker.com/engine/api/v1.40) 

More specifically with updating containers according to this endpoint (https://docs.docker.com/engine/api/v1.40/#operation/ContainerUpdate)
Im unable to modify the option `OomKillDisable`, that should be possible according to the endpoint provided above.

I'm trying to send the following payload to the endpoint `/containers/CONTAINER_HASH/update`:

```
{
    "OomKillDisable": true,
    "CpuShares": 1101,
    "Memory": 3221225472,
    "MemoryReservation": 10485760,
    "MemorySwap": 2147483648,
    "NanoCPUs": 1000000000
}
```

I get a status 200 with no warnings, but the option is not set, I'm able to set this option while creating the container thru this endpoint, but I'm never able to change it by updating the container, as it should be possible according to the documentation, I'm able to change other properties such as `Memory` tho, just that specific property won't change no matter what I do.

**Comment by justincormack** [comment]
Hi please open this issue on github.com/moby/moby not here. This is for the registry API.
