### ISSUE TITLE
Bad disign descision is `docker pull with tag+@hash`

### ISSUE THREAD

**Issue by s3rj1k** [docker/distribution#3299]
https://github.com/docker/distribution/blob/master/reference/normalize.go#L59-L64

Do you really think that sha256 collision is impossible?
I know that it is not proven in practice but why to design a flowed a code in the first place?

**Comment by thaJeztah** [comment]
In theory, yes, but in practice, this is not a realistic thing to happen; to quote https://crypto.stackexchange.com/a/47810, which has an excellent answer on this;

<img width="704" alt="Screenshot 2020-12-07 at 18 08 39" src="https://user-images.githubusercontent.com/1804568/101381665-51f34480-38b7-11eb-8a38-2f9b7976bf00.png">

**Comment by s3rj1k** [comment]
@thaJeztah That post is from 2017.

And that does not answer a question of bad design.

I would assume that specifying tag together with hash would return element with specified hash in a list of elements that has specified tag.

Currently this pattern is `let's just ignore tag and lookup all elements by it's hash`.

That just wrong.

**Comment by justincormack** [comment]
If sha256 is broken we will replace it.
