### ISSUE TITLE
version 2.7.1 DELETE call corrupts the repository?

### ISSUE THREAD

**Issue by tanvp112** [docker/distribution#3321]
After issued DELETE call to registry and list the repositories and tags; the deleted image tag was set to null. Follow by garbage collect and list again, noticed the image name still exist with tag equal to null. 

Push again for the deleted image report "Layer already exists", and pull will fail with "manifest unknown"

More info: https://gist.github.com/jaytaylor/86d5efaddda926a25fa68c263830dac1#gistcomment-3562816

Anyone to shade some lights here?

**Comment by ViSilver** [comment]
> After issued DELETE call to registry and list the repositories and tags; the deleted image tag was set to null. Follow by garbage collect and list again, noticed the image name still exist with tag equal to null.
> 
> Push again for the deleted image report "Layer already exists", and pull will fail with "manifest unknown"
> 
> More info: https://gist.github.com/jaytaylor/86d5efaddda926a25fa68c263830dac1#gistcomment-3562816
> 
> Anyone to shade some lights here?

I see you have closed the issue. 
Is it an expected behavior?
If not, what was your solution?

**Comment by gohmc** [comment]
There are orphan data in tags directory:

`sudo ls -l /var/lib/docker/volumes/registry_data/_data/docker/registry/v2/repositories/json-server/_manifests/tags/`

Clean up the directory will do. Here's a good [reference](https://github.com/ricardobranco777/clean_registry) to checkout.
