### ISSUE TITLE
Do we need to be able to explicitly specify a bucket region? 

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#34]
How does the driver behave?
If it's unable to use the bucket specific region, then we should have a configuration var for that.

cc @stevvooe

**Comment by AndreyKostov** [comment]
If you don't have read access to a bucket, then you will receive an error on initialization.
If you have read access and no write access, you can use the bucket to read data, but will receive errors on trying to upload.

Does this answer your question?

**Comment by dmp42** [comment]
The question is rather:

I have a bucket X in region eu-central-1.

 * what happens if I start without specifying the region?
 * what happens if I specify the wrong region?

**Comment by AndreyKostov** [comment]
The current behaviour is that you will error in both of those. We can in theory just go through all of the official regions and find the one that has a bucket with this name (which you hopefully have access to), but this breaks down as soon as we have custom regions (for something like CEPH in the future for example).

**Comment by stevvooe** [comment]
Closing as resolved. The current behavior will error out on missing region parameter.
