### ISSUE TITLE
Migration script

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#342]
Having a script letting people move away from v1 registries might be very nice.

The idea would be to walk the (v1) storage and generate manifests + sha layers on the v2 storage.

@dmcgowan would you give this a try?

**Comment by dmcgowan** [comment]
I would image there are two steps needed here.

Write a script to generate v1 storage to v2 manifests schema 1 + sha layers,
then later write a script that migrates v2 manifests from schema 1 to schema 2.

**Comment by dmp42** [comment]
cc @dave-tucker

**Comment by dmp42** [comment]
hey @dave-tucker

https://github.com/docker/migrator

**Comment by dave-tucker** [comment]
@dmp42 nice!
