### ISSUE TITLE
Check statements in existing cli in light of registry 2.0

### ISSUE THREAD

**Issue by moxiegirl** [docker/distribution#346]
We have this information in the docs.  If I understand y'all correctly the flag in question should never be used. I'd like to clean up this doc but wanted to get your technical review first -- may be none of it is good for 2.0

http://docs.docker.com/reference/commandline/cli/#insecure-registries

**Comment by stevvooe** [comment]
@moxiegirl I think that documentation is still valid. We just shouldn't be suggesting that users apply `--insecure-registry` when discussing best practices.
