### ISSUE TITLE
Support S3 delivery urls

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#37]
It should be possible to instruct the registry to offload layer delivery directly to S3 using the same mechanism as in v1.

cc @stevvooe

**Comment by dmp42** [comment]
This should be made in a way abstracted enough to be able to adapt this to other third-party systems without too much efforts.

**Comment by BrianBland** [comment]
@dmp42: this is superseded by #49

**Comment by dmp42** [comment]
Fair enough. Would that cover CloudFront urls as well?

**Comment by BrianBland** [comment]
Yeah, and it should all be fixed in #55
