### ISSUE TITLE
document commit signing in the contribution guidelines

### ISSUE THREAD

**Issue by nubs** [docker/distribution#377]
The CONTRIBUTING.md file for docker/distribution differs from docker/docker.  Should the differences be merged in (as appropriate)?  Specifically regarding signing commits.

**Comment by stevvooe** [comment]
To clarify, we need to add the [Sign your work](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work) section to CONTRIBUTING.md.
