### ISSUE TITLE
List images and tagging HTTP APIs

### ISSUE THREAD

**Issue by fxposter** [docker/distribution#382]
Along with a search functionality - is the v2 API going to have an endpoints for list of all images available and managing tags for them?

**Comment by stevvooe** [comment]
@fxposter The V2 API does include access to tag listings for each repository. We are current considering the correct approach for full repository listing. If you take a peak at #206, there is some discussion there.

The main issue this doesn't exist is that not all registry implementations may have complete knowledge of their contents.

**Comment by stevvooe** [comment]
@fxposter I've submitted #583 as a proposed fix. Please take a peak.

**Comment by marians** [comment]
Seems like this questions was answered and the issue could be closed, with #206 for further reference.

**Comment by stevvooe** [comment]
@marians We will close this out when the Catalog API is merged.

**Comment by rektide** [comment]
#583 is the link to the Catalog API @stevvooe mentioned. Can't wait, this makes operations -near impossible- significantly hard.

**Comment by dmp42** [comment]
#653 is the actual implementation.
