### ISSUE TITLE
Build instructions need to be in more prominent location

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#390]
Tucking the build instructions away in the docs hides them from developers. Developers are more likely to consume the project through the README. We should either add the building section back to the README or link to it from the README.

cc @moxiegirl

**Comment by stevvooe** [comment]
cc @wolfeidau

**Comment by moxiegirl** [comment]
@stevvooe I'll add a link. I need to go through and clean up some proper nouns this weekend. I'll add this into that work. (Hmm, can I get perms to assign myself stuff on this repo?)

**Comment by dmp42** [comment]
@moxiegirl unfortunately github perm granularity is terrible.
Just add a quick comment on any issue that you want to claim - we will assign you.

**Comment by moxiegirl** [comment]
Thanks for the assignment Olivier. The perms on `docker/docker `allow me to assign issues to myself and to merge. The team might be able to help y'all get yours to work as well.
