### ISSUE TITLE
Step 8 creates 404 errors. 

### ISSUE THREAD

**Issue by mikewootini** [docker/distribution#395]
I'm not entirely sure if there is an issue with the image config setup or if there may be a step or 2 missing in the documentation.  I'll go with the assumption that it is an Issue with the instructions:

https://github.com/docker/distribution/blob/master/docs/deploying.md

Here you can see the instance is running: 
```
[root@localhost ~]# docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                    NAMES
0f9eacee6995        registry:2.0        "registry cmd/regist   17 minutes ago      Up 17 minutes       0.0.0.0:5000->5000/tcp   hopeful_perlman
```

Step 7 and 8 give differing results. 

Step 7 output differs and indicates it may not be working. 

```
[root@localhost ~]# docker push localhost:5000/hello-mine:latest
The push refers to a repository [localhost:5000/hello-mine] (len: 1)
Sending image list
2015/04/19 10:26:00 [root@localhost ~]# 
```
Step 8 seems to be off when running the setup instructions. 
> Use the curl command and the Docker Registry Service API v2 to list your image in the registry:
```
$ curl -v -X GET http://localhost:5000/v2/hello-mine/tags/list
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /v2/hello-mine/tags/list HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:5000
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< Date: Sun, 12 Apr 2015 01:29:47 GMT
< Content-Length: 40
< 
{"name":"hello-mine","tags":["latest"]}
* Connection #0 to host localhost left intact
```

This doesn't seem to work.  The default example seems to give a 404 error. 

```
[root@localhost~]# curl -v -X GET http://localhost:5000/v2/hello-mine/tags/list
* About to connect() to localhost port 5000 (#0)
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /v2/hello-mine/tags/list HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:5000
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Docker-Distribution-Api-Version: registry/2.0
< Date: Sun, 19 Apr 2015 17:27:37 GMT
< Content-Length: 118
< Content-Type: text/plain; charset=utf-8
< 
{"errors":[{"code":"NAME_UNKNOWN","message":"repository name not known to registry","detail":{"name":"hello-mine"}}]}
* Connection #0 to host localhost left intact
* Closing connection #0

```

**Comment by stevvooe** [comment]
cc @moxiegirl

**Comment by moxiegirl** [comment]
@mikewootini Can you give me some details -- OS and `docker info` output? I'll try to recreate the problem.

**Comment by speicherville** [comment]
I am getting the same error on Ubuntu 14.04. Docker info output pasted below:

Containers: 13
Images: 56
Storage Driver: devicemapper
 Pool Name: docker-8:1-262381-pool
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1567.1 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 3.1 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.13.0-52-generic
WARNING: No swap limit support

**Comment by moxiegirl** [comment]
@speicherville Thanks!

**Comment by stevvooe** [comment]
@speicherville Does it work if you tag the image as "localhost:5000/foo/hello-mine"?

**Comment by speicherville** [comment]
@stevvooe it doesn't, I got this error: Invalid namespace name (foo), only [a-z0-9_] are allowed, size between 4 and 30

with the error in mind, I tried localhost:5000/foob/hello-mine and it tagged the image fine but the output was similar to the output above for Step 7.

**Comment by dmp42** [comment]
@speicherville what version of docker are you running? (`docker version`)

**Comment by speicherville** [comment]
@dmp42 a bit of a facepalm here, I can remember balking at the "wget link | sh" install instruction on the Docker page so I installed it from the apt repository and this is what I have. I will update accordingly and see if I still have my problems.

Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
Server version: 1.0.1
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 990021a

**Comment by dmp42** [comment]
@speicherville ok, happy you figured it out :)

FWIW, registry2 requires docker 1.6 or newer.

I'm closing this for now - feel free to reach out on irc (#docker-distribution) or open a new issue if you run into one.
