### ISSUE TITLE
Slack webhook

### ISSUE THREAD

**Issue by corradio** [docker/distribution#398]
Is there any plan to see registry events on Slack using the webhook?

**Comment by stevvooe** [comment]
@corradio No direct integration with slack is planned.

I'd recommend creating a bridge that can accept [notifications](https://github.com/docker/distribution/blob/master/docs/notifications.md) from the registry. This will provide a lot more control over how they work and what gets propagated.

**Comment by adamkdean** [comment]
It would be nice if the notifications allowed for generic webhooks.

**Comment by stevvooe** [comment]
@adamkdean What does that even mean? The notifications are quite generic and it is very easy to write a server to accept and dispatch them.

Here is a snippet I use to accept webhooks when testing:

```
package main

import (
	"net/http"
	"time"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(500 * time.Millisecond)
		w.WriteHeader(204)
	})

	http.ListenAndServe(":5003", nil)
}
```

The possibilities are literally endless.
