### ISSUE TITLE
email after registry webapp panic 

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#41]
See https://github.com/docker/docker-registry/blob/master/ADVANCED.md#email-exceptions for history

**Comment by dmp42** [comment]
That should be a simple package that catches exceptions and mail them (see how bugsnag does that).

**Comment by stevvooe** [comment]
> That should be a simple package that catches exceptions and mail them (see how bugsnag does that).

There are no exceptions in Go. Thus, the registry implementation already sends all exceptions. ;)

(Assume you mean panic)

**Comment by dmp42** [comment]
See? Too much python :)
Yeah, I meant panic.

**Comment by xiekeyang** [comment]
@stevvooe 
feature of *Email exceptions*, like docker-registry, seems not in V2 yet.
- email configuration;
- sending function;

If it is in any schedule or progress, or any conception?
Thanks a lot!

**Comment by dmp42** [comment]
@xiekeyang no progress so far. It's up for the take if someone wants to start working on it.

**Comment by stevvooe** [comment]
@xiekeyang This is the issue covering it. It is not currently on the roadmap.

If you would like the feature, please submit a proposal as an issue, referencing this one. Please cover how it will work, configuration, etc.

As an aside, it might be useful to integrate with the logging system, which has a lot of contextual information that may be useful for reporting.

**Comment by xiekeyang** [comment]
Got it, Thanks a lot! I would present the proposal.

**Comment by xiekeyang** [comment]
##Proposal
### Features
* The Exception Notification gem provides a set of notifiers for sending email notifications after webapp panic.
* EmailException is used as a `panic` response, or in the context you want it to run.
* The sending Emails includes information about the current session, error type, and inforamtion that developer defines.

###Implementation
* it depends on `net/smtp` package, which supports SMTP mailbox.
* The package methods as `PlainAuth`, and `SendMail` may be used.
* it may be configurated in `app` package, and run sending function after critical errors.

Neither `log` nor `github.com/Sirupsen/logrus` seems including sending mail functionality. As some other opening project like [github.com/cihub/seelog](https://github.com/cihub/seelog) can do. 

Therefore, The first patch realese may only support feature of mail sending manually. Then, research and set up full logging system with functionality of mail sending and local log file storage.

###Configuration
you can make it work by putting the following lines, in the file of [config.yml](../../cmd/registry/config.yml).
```bash
email_exceptions:
    smtp_host: _env:SMTP_HOST
    smtp_port: _env:SMTP_PORT:25
    smtp_login: _env:SMTP_LOGIN
    smtp_password: _env:SMTP_PASSWORD
    smtp_secure: _env:SMTP_SECURE:false
    from_addr: _env:SMTP_FROM_ADDR
    to_addr: _env:SMTP_TO_ADDR
```

**Comment by xiekeyang** [comment]
##Proposal
### Features
* The Exception Notification gem provides a set of notifiers for sending email notifications after webapp panic.
* EmailException is used as a `panic` response, or in the context you want it to run.
* The sending Emails includes information about the current session, error type, and inforamtion that developer defines.

###Implementation
* it depends on `net/smtp` package, which supports SMTP mailbox.
* The package methods as `PlainAuth`, and `SendMail` may be used.
* it may be configurated in `app` package, and run sending function after critical errors.

Neither `log` nor `github.com/Sirupsen/logrus` seems including sending mail functionality. As some other opening project like [github.com/cihub/seelog](https://github.com/cihub/seelog) can do. 

Therefore, The first patch realese may only support feature of mail sending manually. Then, research and set up full logging system with functionality of mail sending and local log file storage.

###Configuration
you can make it work by putting the following lines, in the file of [config.yml](../../cmd/registry/config.yml).
```bash
email_exceptions:
    smtp_host: _env:SMTP_HOST
    smtp_port: _env:SMTP_PORT:25
    smtp_login: _env:SMTP_LOGIN
    smtp_password: _env:SMTP_PASSWORD
    smtp_secure: _env:SMTP_SECURE:false
    from_addr: _env:SMTP_FROM_ADDR
    to_addr: _env:SMTP_TO_ADDR
```

**Comment by stevvooe** [comment]
@xiekeyang This proposal looks good. A few items:

- We will not be changing to logging package. `github.com/Sirupsen/logrus` does support hooks that can intercept log messages and send mail. This would be the best place to hook into errors.
- In addition to intercepting error logs, we'd need an http handler that intercepts panics and emits error level logs with the error information for use in logrus.
- The environment variables aren't necessary in the Go registry implementation. Environment variables are automatically generated in the form of `REGISTRY_EMAIL_EXCEPTIONS_SMTP_HOST` based on the yaml configuration path.
- As far as configuration goes, it might be better to position these as log handlers:

```yaml
log:
  level: debug
  fields:
    service: registry
    environment: development
  handlers:
    error:
      - type: email
        smtp_host: mail.example.com
        smtp_port: 25
        smtp_login: mailuser
        smtp_password: password
        smtp_secure: true
        from_addr: registry@$HOSTNAME # We may need to have special handling for hostname or test this
        to_addr: errors@example.com
```

This will allow use to add future extensions that can be a part of logging hooks.

As an aside, I noticed the sentence "The Exception Notification gem provides a set of notifiers for sending" is directly from https://github.com/smartinez87/exception_notification. It's okay to use such a project for inspiration or as an example but please make sure your work is your own or properly cited.

**Comment by xiekeyang** [comment]
@stevvooe Thanks a lot for your help!
I analyze and try `logrus/hooks` packages, and find that it can handle the panic (besides error, fatal).
Here I'm in progress.
### Question:
1. would you like to,
* add `recover()` before each `panic()`;
* or keep only `panic()` without `recover()` ?
Maybe `recover()` way is better?

2. for your proposal "http handle", may I use `httptest.NewServer` method in `app.go` ? I prefer it, because we needn't care listen port assignment. httptest can assign a free port, and httptest server can listen port during web app life.  Otherwise, would you propose to use `http.ListenAndServe` method, don't use httptest in app package?

**Comment by stevvooe** [comment]
1. Just use the standard panic/recover pattern. You can read about it [here](http://blog.golang.org/defer-panic-and-recover).
2. `httptest` should only be used for testing. I'm not sure why you'd need it `app.go`.

**Comment by xiekeyang** [comment]
Got it. 
I had liked add in `app.go`, for it is for reporting app web panic. But according to your proposal, I'd improve the design.
`main.go`:`configureReporting` is for reporting bugsnag handler. May I add the panic snag configuration, http handler(with mail sending) in it?

**Comment by stevvooe** [comment]
@xiekeyang Really, this reporting should not involve bugsnag. Bugsnag is already integrated. If you would like to modify the bugsnag configuration, just sumbit a PR with those changes. I don't think such a change would close this issue.
