### ISSUE TITLE
Error pushing to registry: Server error: 400 / 500

### ISSUE THREAD

**Issue by buckett** [docker/distribution#413]
Our CI server (Jenkins) is attempting to push builds to the docker hub and sometimes fails with:
```
[workspace] $ docker push oxit/weblearn:jenkins
The push refers to a repository [oxit/weblearn] (len: 1)
3881c0e6deb2: Buffering to Disk
3881c0e6deb2: Image successfully pushed
3881c0e6deb2: Image already exists
d7cff058e4a5: Buffering to Disk
d7cff058e4a5: Image successfully pushed
0c80302861c2: Buffering to Disk
0c80302861c2: Image successfully pushed
8552f56cc885: Buffering to Disk
8552f56cc885: Image successfully pushed
fd10a9c2e70a: Buffering to Disk
fd10a9c2e70a: Image push failed
time="2015-04-22T13:11:12+01:00" level=fatal msg="Error pushing to registry: Server error: 400 trying to push oxit/weblearn blob - sha256:10d3f451806505fab44b8bfde08806adeb91b451f63e9008b57060fefa4ca1d6" 
```

This wasn't happening with 1.5.0 and only seems to have started since 1.6.0. We've now downgraded to 1.5.0 and it's all working fine.

**Comment by buckett** [comment]
I think this is related to #405 but we have still been seeing these errors in the last few hours.

**Comment by dmp42** [comment]
Thanks @buckett 

We are tracking this down right now.

**Comment by stevvooe** [comment]
@buckett #405 does attempt to deal with this issue but only handles part of it. We are currently in the midst of an ongoing analysis.

**Comment by pbecotte** [comment]
I am seeing it repeatedly on a specific image now.  The layer in question is 179 mb, so a very large one (the same layer each push).  4 times in a row now.  I set the daemon to debug for the last run...

DEBU[0036] https://registry-1.docker.io/v2/bamx/elasticsearchbase/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-49-generic os/linux arch/amd64]] 
DEBU[0036] Using cached token for pbecotte              
DEBU[0036] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0037] Pushing layer: 8acbec06939ef347371c80560730e9c7ca2e4c515beb3297acebdb51a00f8b2f 
DEBU[0037] [registry] Calling "HEAD" https://registry-1.docker.io/v2/bamx/elasticsearchbase/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 
DEBU[0037] https://registry-1.docker.io/v2/bamx/elasticsearchbase/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-49-generic os/linux arch/amd64]] 
DEBU[0037] Using cached token for pbecotte              
DEBU[0037] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0038] Pushing layer: 86dfb138958427a5fb83ded7796d9c5119e0c8e8bc0b9c39a06018abd65c8fcf 
DEBU[0084] rendered layer for 86dfb138958427a5fb83ded7796d9c5119e0c8e8bc0b9c39a06018abd65c8fcf of [179847138] size 
DEBU[0084] [registry] Calling "POST" https://registry-1.docker.io/v2/bamx/elasticsearchbase/blobs/uploads/ 
DEBU[0084] https://registry-1.docker.io/v2/bamx/elasticsearchbase/blobs/uploads/ -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-49-generic os/linux arch/amd64]] 
DEBU[0084] Using cached token for pbecotte              
DEBU[0084] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0087] [registry] Calling "PUT" https://registry-1.docker.io/v2/bamx/elasticsearchbase/blobs/uploads/8a966f5c-87fd-419f-a00a-10a29dfbe21b?_state=K3aIx8BS7gxbPNcXZaMjDC_lzmqdaowvvkA-zw-LZ9V7Ik5hbWUiOiJiYW14L2VsYXN0aWNzZWFyY2hiYXNlIiwiVVVJRCI6IjhhOTY2ZjVjLTg3ZmQtNDE5Zi1hMDBhLTEwYTI5ZGZiZTIxYiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNS0wNC0yMlQxOTowMTowNi4wNDE0Mzc2MjRaIn0%3D 
DEBU[0087] https://registry-1.docker.io/v2/bamx/elasticsearchbase/blobs/uploads/8a966f5c-87fd-419f-a00a-10a29dfbe21b?_state=K3aIx8BS7gxbPNcXZaMjDC_lzmqdaowvvkA-zw-LZ9V7Ik5hbWUiOiJiYW14L2VsYXN0aWNzZWFyY2hiYXNlIiwiVVVJRCI6IjhhOTY2ZjVjLTg3ZmQtNDE5Zi1hMDBhLTEwYTI5ZGZiZTIxYiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNS0wNC0yMlQxOTowMTowNi4wNDE0Mzc2MjRaIn0%3D -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-49-generic os/linux arch/amd64]] 
DEBU[0087] Getting bearer token with map[realm:https://auth.docker.io/token service:registry.docker.io] for pbecotte 
DEBU[0087] https://auth.docker.io/token -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-49-generic os/linux arch/amd64]] 
DEBU[0088] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0344] Unexpected response from server: "{\"errors\":[{\"code\":\"DIGEST_INVALID\",\"message\":\"provided digest did not match uploaded content\",\"detail\":\"invalid digest for referenced layer: sha256:9adee689c8b02e790a95f61cccf3a4e09ba72a96d5808c681196c4b65779c6c2, content does not match digest\"}]}\n" http.Header{"Strict-Transport-Security":[]string{"max-age=31536000"}, "Docker-Distribution-Api-Version":[]string{"registry/2.0"}, "Date":[]string{"Wed, 22 Apr 2015 19:05:25 GMT"}, "Content-Length":[]string{"249"}, "Content-Type":[]string{"text/plain; charset=utf-8"}} 
Error pushing to registry: Server error: 400 trying to push bamx/elasticsearchbase blob - sha256:9adee689c8b02e790a95f61cccf3a4e09ba72a96d5808c681196c4b65779c6c2
INFO[0344] -job push(bamx/elasticsearchbase) = ERR (1)

**Comment by stevvooe** [comment]
I wanted to update everyone on this matter. We have been investigating and pushing a few fixes that should help with stability. The problem has been isolated to an issue with the s3 driver that results in starvation of sending data to s3, resulting in a RequestTimeout error. The root cause of this is still not known.

**Comment by wzymaster** [comment]
any link to quickly download Docker 1.5.0 ?

**Comment by dmp42** [comment]
@wzymaster the issue has been fixed in production.

As for direct binary downloads of older versions, have a look here: https://docs.docker.com/installation/binaries/

**Comment by skozin** [comment]
@dmp42, I am seeing this on almost every push with Docker 1.6.0 and self-hosted registry 2.0 pointing to an S3 bucket:

```text
$ docker push registry:5000/router:1.0.0
The push refers to a repository [registry:5000/router] (len: 1)
19350ad1c72b: Image already exists
acb11365802c: Image already exists
633d5ce99a50: Image already exists
6028b15645e3: Image already exists
416c4ad514bf: Image already exists
38235a39ef9e: Image successfully pushed
90d73bdc5f98: Image successfully pushed
bd6b6145abd2: Image successfully pushed
16476b474d17: Image successfully pushed
a02eeb845a78: Image successfully pushed
20aa6d2f7d53: Image successfully pushed
bdf9a212bca4: Image successfully pushed
2b9668bd04d4: Image push failed
FATA[0068] Error pushing to registry: Server error: 500 trying to push router blob - sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
```

From Registry log ([full debug log for this push](https://gist.github.com/skozin/814896267e822c2cc9f9)):

```text
10.0.42.1 - - [27/Apr/2015:23:46:06 +0000] "PUT /v2/router/blobs/uploads/a2a6dff5-095b-4290-a903-221c000571db?_state=3kvkXN2EFKiUddI2z-dl31bJPiHqA5W7XZhs8G2dESx7Ik5hbWUiOiJyb3V0ZXIiLCJVVUlEIjoiYTJhNmRmZjUtMDk1Yi00MjkwLWE5MDMtMjIxYzAwMDU3MWRiIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTA0LTI3VDIzOjQ2OjA1LjIzMzIzOTI4OVoifQ%3D%3D&digest=sha256%3Aa3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 500 342 "" "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-23-generic os/linux arch/amd64"
```

Docker and Registry versions:

```text
$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): darwin/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

$ docker images
REPOSITORY     TAG     IMAGE ID        CREATED       VIRTUAL SIZE
...
registry       2.0     d347c445a0a8    5 days ago    548.1 MB
```

Registry config:

```yaml
version: 0.1
log:
  level: debug
storage:
  cache:
    layerinfo: inmemory
  s3:
    accesskey: xxx
    secretkey: yyy
    region: eu-central-1
    bucket: docker.ficus.io
    encrypt: true
    secure: true
    v4auth: true
    rootdirectory: /
http:
    addr: :5000
    secret: zzz
    debug:
      addr: :5001
redis:
  addr: localhost:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
notifications:
    endpoints: []
```

**Comment by dmcgowan** [comment]
This was fixed in the distribution codebase but no update to the official docker image was made (@stevvooe @dmp42 correct me if I am wrong). @stevvooe should we tag a release fix just for this change?

**Comment by dmp42** [comment]
@dmcgowan @skozin a new release will be cut soon.
Meanwhile, I would recommend building from master.

**Comment by skozin** [comment]
@dmp42, @dmcgowan, thank you! I really need this fix as I am unable to successfully push any image, especially on a fast Internet connection. The first 2-5 not-yet-existent layers get pushed successfully, but the next layer reliably fails.

I'll try building from master, but I would really appreciate the bugfix release.

**Comment by dmp42** [comment]
@skozin you can checkout `git clone` it and `docker build .` - that should give you the image without difficulties.

**Comment by skozin** [comment]
@dmp42, I didn't expect that it is so easy =) Got it working, thanks a lot for your help!

**Comment by slabrador** [comment]
I pulled the latest code and I experience the exact same issue. My CoreOS is using Docker version 1.5.0. "Error pushing to registry: Server error: 400 trying to push <image name> blob". This is using the s3 driver.

**Comment by stevvooe** [comment]
@slabrador Simply getting a 400 error on push does not mean you're seeing this issue. The root cause is related to poor performance from s3. Are you seeing a `DIGEST_INVALID` in the error response from the registry in the docker daemon logs? If you pull the s3 access logs, do you see RequestTimeout errors? If the answer to those questions is yes, then this is the same issue.

Are you seeing the same issue with 1.6? Unfortunately, 1.5 is not supported with the V2 registry API.

**Comment by arcolombo** [comment]
Hi I am having this same error.



Hi.

here is my docker info
Containers: 0
Images: 200
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 200
Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-50-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 15.65 GiB
Name: ramsingh-iMac
ID: 4A35:NATD:PXQN:2YLC:57GR:SJTN:PIXK:PFXQ:MK4F:MYRE:4SNH:R4LC
Username: arcolombo
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

OS

Linux ramsingh-iMac 3.16.0-50-generic #67~14.04.1-Ubuntu SMP Fri Oct 2 22:07:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

So following this forum's post (https://forums.docker.com/t/how-to-flatten-an-image-with-127-parents/1600/4), i was able to successfully flatten a 39GB image that has been worked on over 4 months, into a 12GB image; and successfully exported / imported the docker image. I am receiving an error of 127 layer limit, and must reduce the docker image arcolombo/artemis:v156

I am receiving similar errors to
github.com/docker/distribution
Issue: Error pushing to registry: Server error: 400 / 500
opened by buckett on 2015-04-22
closed by dmp42 on 2015-04-24

for the docker registry, I do not have a custom registry but am just pushing to Docker hub. i'm not sure how to display this information.

Nb. I am able to docker run the unlayered/flattened import of the container. the import does work. I am just now trying to push the flattened container to the docker hub. and this is when I produce the error

ramsingh@ramsingh-iMac:/data$ sudo docker push arcolombo/artemisunlayer:v2
The push refers to a repository [arcolombo/artemisunlayer] (len: 1)
2b3ff30d9f78: Image already exists
8399b157cbee: Image successfully pushed
c1ae5b75d6b2: Image push failed
FATA[2418] Error pushing to registry: Server error: 500 trying to push arcolombo/artemisunlayer blob - sha256:11b33657d0a1478092f60e6bd8dd33e91ab95e7783f62044ccee0f0c353b6031

so here are my images, arcolombo/artemis has been pushed successfully, when I exported the container, and saved it as a .tar file, I then imported into arcolombo/artemisunlayer:v2 to remove the history and flatten the image, thus reducing the size

REPOSITORY TAG IMAGE ID CREATED VIRTUAL SIZE
arcolombo/artemisunlayer v2 2b3ff30d9f78 54 minutes ago 12.64 GB
arcolombo/artemisunlayer v1 c1ae5b75d6b2 About an hour ago 12.64 GB
arcolombo/artemis v156 de9bc789af1d 3 days ago 39.91 GB

Thank you very much.
Should I open a bug?

**Comment by connaryscott** [comment]
so this is dead, no resolution?

**Comment by pbecotte** [comment]
They fixed the bug that was causing this issue on April 22... if you are seeing something similar, it would be a new bug ticket.

**Comment by arcolombo** [comment]
I was able to fix my issue because I was making commits to my image using interactive container, thus bloating my commit history.  now I strictly work from a docker file, and limit my commits.

**Comment by stevvooe** [comment]
@arcolombo Please don't comment on closed issues. This is not likely your problem since we have been through several releases since.
