### ISSUE TITLE
Investigate rewriting/ditching goamz

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#433]
Rationale:

 - we use a very small subset of the library
 - it's an absolutely critical component for us

Maybe we can be happier by rewriting the small subset of things that we need, and enjoy better control over our destiny.

**Comment by dmcgowan** [comment]
We should just experiment with the newer and officially support go AWS SDK.  AWS has too many oddities to even own a small subset of its functionality.

https://github.com/awslabs/aws-sdk-go

**Comment by dmp42** [comment]
Related #122

**Comment by stevvooe** [comment]
@dmcgowan Just took a look through github.com/awslabs/aws-sdk-go. Seems to cover a lot of the issues with goamz.

**Comment by dalehamel** [comment]
FYI i threw together a PR that leverages S3gof3r for part of the s3 storage drive (IMHO the most complicated part). For performance reasons, i'm only using it for streamed reading/writing.

The remaining parts should be easily replaced with the aws-sdk-go library. Not sure where else goamz is used.

https://github.com/docker/distribution/pull/693

**Comment by dmp42** [comment]
Closing in favor of #122
