### ISSUE TITLE
Mount host directory

### ISSUE THREAD

**Issue by ssljivic** [docker/distribution#440]
I tried to mount volume like "-v /data:/tmp/registry-dev". Registry 2.0 started successfully, but when I try to push the image I am getting the following error:

Image push failed
FATA[0000] Error pushing to registry: Put ?digest=tarsum.v1%2Bsha256%3A1ecebf641f3e137af894012093c2f1a414fd6419dfacb538f775964179089aea: unsupported protocol scheme ""

**Comment by stevvooe** [comment]
Do you get the same error when you run the registry without the volume mount?

**Comment by ssljivic** [comment]
There is no error without volume mount.

**Comment by stevvooe** [comment]
@ssljivic Could you please provide registry and daemon logs from the failed PUT?

**Comment by dmp42** [comment]
`digest=tarsum.v1` means docker 1.5, which is not supported.

Can you test pushing with docker 1.6?

Thanks.

**Comment by zanella** [comment]
It's working fine for me here, docker info below, BUT, the docs are absurdly convoluted as of now, can this info be added to the registry hub page ? It's a bit useless to use a local registry that doesn't persist the images it receives...

====================
sudo docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

**Comment by dmp42** [comment]
@zanella attempt at making the docs better goes on here: https://github.com/docker/distribution/pull/553 - let me know if you feel this is better.

Now, the registry DOES PERSIST images.

If it's not working for you, please provide at least the registry logs.

Something like this should just work out of the box:

```
mkdir `pwd`/registry-data
docker run -d -p 5000:5000 \
        -v `pwd`/registry-data:/tmp/registry-dev \
        --name registry registry:2
```

**Comment by dmp42** [comment]
@ssljivic can you confirm what version of docker you are using?

Thanks.

**Comment by zanella** [comment]
@dmp42 Does the mounting works for the Python image as well? Realized now that on the docs PR above I forgot to specify ":2" on the command example

**Comment by dmp42** [comment]
@zanella depends on the configuration flavor you choose (see storage_path in https://github.com/docker/docker-registry/blob/master/config/config_sample.yml)

@ssljivic your last comment is from Apr 28 - I'm going to close this ticket for now, but if you have some additional feedback or still experiencing this problem, please say so and I'll reopen.
