### ISSUE TITLE
Wrong port specified in Dockerfile

### ISSUE THREAD

**Issue by pwaller** [docker/distribution#442]
[The `Dockerfile` has an `EXPOSE 5000`](https://github.com/docker/distribution/blob/4dde6b9d64db8393abec0d175eacb4ee7c77be4e/Dockerfile#L10), but it seems the real default internal port is port 80, if I run netstat inside the resulting container with `docker exec`.

**Comment by dmcgowan** [comment]
Are you running the container with a different configuration?  The default config in the container should be 5000

https://github.com/docker/distribution/blob/master/cmd/registry/config.yml#L13

```
# netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5001          0.0.0.0:*               LISTEN      1/registry      
tcp6       0      0 :::5000                 :::*                    LISTEN      1/registry      
Active UNIX domain sockets (only servers)

```

**Comment by pwaller** [comment]
Ah yes, I am, but I do not specify a port so it defaults to 80. Would be nice if it defaulted to the same thing :-)

On 27 April 2015 16:28:27 BST, Derek McGowan <notifications@github.com> wrote:
>Are you running the container with a different configuration?  The
>default config in the container should be 5000
>
>https://github.com/docker/distribution/blob/master/cmd/registry/config.yml#L13
>
>```
># netstat -nlp
>Active Internet connections (only servers)
>Proto Recv-Q Send-Q Local Address           Foreign Address        
>State       PID/Program name
>tcp        0      0 127.0.0.1:5001          0.0.0.0:*              
>LISTEN      1/registry      
>tcp6       0      0 :::5000                 :::*                   
>LISTEN      1/registry      
>Active UNIX domain sockets (only servers)
>
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/docker/distribution/issues/442#issuecomment-96708906

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stevvooe** [comment]
If you want to test it on port 80, you can run with the following arguments to map the port:

```console
$ docker run -p 80:5000 registry:2
```

This will expose port 5000 as port 80 on the host, allowing one to drop the port from the tag. Note that this will require you to run docker with "--insecure-registry <addr>", so it is not recommended for anything serious. It would be better to have a tls configuration setup and expose the registry as port 443, if this is desired.

While it is not strictly necessary for 2.0, Docker Registries are usually run behind a reverse proxy, such as nginx or apache. The inconvenience of binding to port 80 would out weigh the convenience of having ports match by default. The distributed `library/registry` image is setup for trying the registry out. For production deployments, its recommended that one adds configuration to the image using a Dockerfile with `FROM registry:2`, which would allow you to change it to whatever port you see fit.

**Comment by pwaller** [comment]
I think my point is missed. I have a file that looks like this:

```
      version: 0.1
      storage:
          cache:
              layerinfo: inmemory
          s3:
              region: {{aws_region}}
              bucket: {{registry_bucket}}
              encrypt: true
```

The EXPOSE instruction says port 5000, but if I do `-p 5000:5000`, I get connection reset by peer, because the process inside the docker container is actually listening on port 80!

**Comment by stevvooe** [comment]
@pwaller You need to specify the http configuration. Without it, you will get arbitrary defaults.

There may be a bug here in that a missing http configuration works.

**Comment by RichardScothern** [comment]
@pwaller . Did you get this working?

**Comment by pwaller** [comment]
Yes, I did. It's still confusing that it listens on a default port of 80 if you leave it unspecified though, and breaks `--publish-all`. I would have preferred it if it said EXPOSE 80 or listened on port 5000 by default, and then it would at least be self documenting.

**Comment by stevvooe** [comment]
Glad you were able to address the issue!

The `Dockerfile` is designed to be used with a default port of 5000. Your configuration needs a minimal `http` section or it will bind to port 80:

```
version: 0.1
http:
    addr: :5000
storage:
  cache:
    layerinfo: inmemory
  s3:
    region: {{aws_region}}
    bucket: {{registry_bucket}}
    encrypt: true
```

I'm going to close this issue. Let us know if you have further questions.
