### ISSUE TITLE
docker run  secure_registry:latest error

### ISSUE THREAD

**Issue by mingj** [docker/distribution#450]
in 'Configure TLS on a registry server' step
after build secure_registry. when i run 
"docker run -p 5000:5000 secure_registry:latest"
log for this error
"configuration error: error parsing cmd/registry/config.yml: yaml: line 20: found character that cannot start any token
usage: registry <config>
  -version=false: show the version and exit
"
what's the problem?

**Comment by mingj** [comment]
oooo，my fault，forget to switch branch。

**Comment by dmp42** [comment]
Ok, closing then :)

**Comment by sa-shukla** [comment]
what was the issue? How did you fix it? I downloaded the source available at  https://github.com/docker/distribution/archive/v2.0.0.tar.gz , extracted it and then compiled it using docker build command.

No issues were encountered during build process, but when I try to start registry contain, I also get above error.

I am not sure what you are talking about switch branch.

**Comment by dmp42** [comment]
@sa-shukla you should stick with the official image for the registry (see documentation).
There is almost no reason to build your own registry from source.

If you really, really want to compile from source still, please use the latest version and follow the build docs.

**Comment by stevvooe** [comment]
@sa-shukla That error message means there is a format problem with the configuration. If you examine the message carefully, you'll see it is a syntax error at line 20. With yaml this, is likely a problem with spacing.
