### ISSUE TITLE
unknown directive "more_set_headers" in /etc/nginx/conf.d/registry.conf:30

### ISSUE THREAD

**Issue by polym** [docker/distribution#452]
Ｉ used `contrib/compose/` to build up my private registry, but something wrong occured in compose_nginx container. I search for this problem, and find [HttpHeadersMoreModule](http://wiki.nginx.org/HttpHeadersMoreModule#Installation). So maybe just `FROM: nginx:1.7`  is not enough. We should add module to nginx and compile it.

**Comment by stevvooe** [comment]
@polym You can use `add_header` with the "always" parameter after 1.7.5 in nginx. We are a little annoyed with nginx, as well, since this is an odd restriction. I've file #460 to cover this.

Let me know how you'd like to proceed.

**Comment by polym** [comment]
Thanks. I'm new to docker-registry, and try it by using document. :)

**Comment by macsteps** [comment]
Comment out or remove more_set_headers line, and add
```
add_header 'Docker-Distribution-Api-Version:' 'registry/2.0' always;
```

**Comment by kentoj** [comment]
I hit this same error today. Is there a fork with a PR to fix this yet?

**Comment by stevvooe** [comment]
@kentoj How do you propose we fix a bug in nginx with a fork of distribution?

**Comment by kentoj** [comment]
@stevvooe it looks like I must have misunderstood the issue. If @macsteps suggestion is not a solution to this problem then I don't know how to fix this.

**Comment by stevvooe** [comment]
@kentoj We need to get the documentation in order on this. @macsteps solution is the right approach but requires nginx 1.7.5+.

**Comment by nhalm2** [comment]
If I switch to add_header as @macsteps suggests I get duplicate ```Docker-Distribution-Api-Version``` headers.

```
# curl -v -k https://localhost:5000/v2/
* About to connect() to localhost port 5000 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 5000 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_DHE_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
*      *certificate_stuff*
> GET /v2/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:5000
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.7.12
< Date: Fri, 15 May 2015 17:01:52 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 2
< Connection: keep-alive
< Docker-Distribution-Api-Version: registry/2.0
< Docker-Distribution-Api-Version: registry/2.0
<
* Connection #0 to host localhost left intact
{}
```

If I just take out the more_headers I am still seeing the header, but only once.

**Comment by thaJeztah** [comment]
@stevvooe for people using a containerised NGINX; 1.9 is now the only supported NGINX version on the registry; https://registry.hub.docker.com/_/nginx/

**Comment by stevvooe** [comment]
@thaJeztah Looks like we should move the documentation to fully embrace the `add_headers` directive. This will clean things up a bit. Thank you for the update.

cc @moxiegirl
