### ISSUE TITLE
Pushing images via ssh from host to host

### ISSUE THREAD

**Issue by tcurdt** [docker/distribution#454]
The new registry is great and all - but I would soooo love if I could just simply push from one docker host to another via ssh.

**Comment by stevvooe** [comment]
@tcurdt We are attempting to take the project in a more flexible direction. First, the goal is to make docker speak a content addressable protocol internally (v2 API, as you'll hear it called) then leverage that to make the distribution model more flexible and secure.

As far as using ssh goes, you could run a registry local to each docker host and push from registry to registry using an ssh tunnel. Such a setup would have a registry bound to localhost on each host. Create a tunnel from each host to the remote registry, tag the image with the local tunnel port then perform the push with the docker client. 

This probably isn't exactly what you want but could provide a close alternative.

**Comment by tcurdt** [comment]
@stevvooe yeah - I've got a tunnel setup working here. But it's a bit of a hassle.
Still probably worth a blog post if I find the time.

The content addressable protocol sounds interesting.
Is there an issue open where I can read up that? Searching the issues didn't yield a result for me.

**Comment by stevvooe** [comment]
@tcurdt Just read the [api spec](https://github.com/docker/distribution/blob/master/docs/spec/api.md).

**Comment by tcurdt** [comment]
thx!
