### ISSUE TITLE
Untagged images

### ISSUE THREAD

**Issue by corradio** [docker/distribution#467]
Are images that are untagged (for example because a new `docker push` has been done, thus untagging the previous image) automatically purged?

**Comment by RichardScothern** [comment]
Hi @corradio .  

The registry will only purge files which result in a failed or incomplete upload.  For any upload the succeeded, the images are not purged.  There is discussion around implementing delete for the registry in issue #422

**Comment by corradio** [comment]
Thanks for the clarification!
