### ISSUE TITLE
Fix downstream Dockerfile and add page elements to storagedrivers.md

### ISSUE THREAD

**Issue by moxiegirl** [docker/distribution#471]
The docker/docker:docs/Dockerfile on the engine repo has an additional sed script that was not in the downstream repos like distribution or compose.  This sed script is causing a problem in the output of the docs/storagedriver.md file.  

As a result, when I tested on the cherry-pick-branch everything looked good:
![image](https://cloud.githubusercontent.com/assets/1347209/7399039/d9c2730e-ee67-11e4-983f-1fdb8e5c1d11.png)

When I tested for publish it failed with a bad title and a borked nav:

![image](https://cloud.githubusercontent.com/assets/1347209/7399048/e12ed40c-ee67-11e4-8c06-3356d0ac7ddf.png)

**Comment by stevvooe** [comment]
@moxiegirl Is this addressed by #480?

**Comment by stevvooe** [comment]
Confirmed.
