### ISSUE TITLE
goroutine leak in net/http.(*persistConn).writeLoop

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#473]
A leak still exists in when using the registry in production. The key identifier of this problem is a goroutine dump (using http://localhost:5001/debug/pprof/goroutine?debug=2) with thousands of the following stack trace:

```
goroutine 1815561 [select, 155 minutes]:
net/http.(*persistConn).writeLoop(0xc2a8d3f760)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc
```

This seems to be caused by incorrect usage of the http library. The root cause may be related to the s3 library (AdRoll/goamz) creating a new transport on every request. Please see the following:

https://github.com/AdRoll/goamz/blob/master/s3/s3.go#L1133

The only other possible source of the could be the http notifications.

While we don't have a reproduction, the problem can be demonstrated with the following code, which is similar to how s3 uses the http client:

```
package main

import (
	"log"
	"net/http"
	_ "net/http/pprof"
)

func main() {
	for i := 0; i < 100; i++ {
		go func() {
			c := http.Client{
				Transport: &http.Transport{},
			}

			r, err := c.Get("http://google.com")
			if err != nil {
				log.Fatalln(err)
			}
			defer r.Body.Close()

			log.Println("status", r.Status)
		}()
	}

	http.ListenAndServe(":8080", nil)
}
```

If the above is run, a goroutine will contain the same blocked stack traces. Simple adding a call to `(*http.Transport).CloseIdleConnections`:

```
package main

import (
	"log"
	"net/http"
	_ "net/http/pprof"
)

func main() {

	for i := 0; i < 100; i++ {
		go func() {
			t := &http.Transport{}
			c := http.Client{
				Transport: t,
			}
			defer t.CloseIdleConnections()

			r, err := c.Get("http://google.com")
			if err != nil {
				log.Fatalln(err)
			}
			defer r.Body.Close()

			log.Println("status", r.Status)
		}()
	}

	http.ListenAndServe(":8080", nil)
}
```

The plan to mitigate this is the following:

- [x] Deploy version with fixes to notification library. If the leak still happens, we know by process of elimination that the leak is in the s3 library.
- [x] ~~If the leak still exists after patching notifications, close the connections in the s3 library and then test.~~ Leak isolated to notification library.

**Comment by noxiouz** [comment]
```http.Transport``` is not expected to be created on each request, I think. You see the leak of keep-alived connections, so if a transport is recreated on each request it means that KeepAlive should be disabled, as it doesn't work in this case :D. Otherwise, all of the connections must be closed as there's no finalizer attached to ```net.Conn``` in ```*http.persistConn```
 The code in the notification library uses the one instance of http.Transport, so the mistake is in s3 library.

**Comment by stevvooe** [comment]
@noxiouz Thanks for the analysis. While the s3 library doesn't use the transport correctly, we have isolated it to a missing close call in the notification library.
