### ISSUE TITLE
Listen and serve on a unix socket

### ISSUE THREAD

**Issue by irachex** [docker/distribution#477]
It would be great that distribution can serve on a unix socket.

**Comment by RichardScothern** [comment]
Hi @irachex  Thank you for the input. 

Could you write a brief proposal on why this is a desirable feature?  Also, would you be willing to contribute the feature?

**Comment by noxiouz** [comment]
For example, I want to use nginx for a SSL/TLS termination. Using unix socket as an upstream works faster and brings less overhead than IP

**Comment by RichardScothern** [comment]
Sounds good @noxiouz   I look forward to seeing it.

**Comment by dmp42** [comment]
Implemented.
