### ISSUE TITLE
Registry downgrades from HTTPS to HTTP when uploading layers

### ISSUE THREAD

**Issue by burke** [docker/distribution#479]
```
DEBU[0047] [registry] Calling "POST" https://registry3.ash.shopify.io/v2/deleteme/blobs/uploads/
DEBU[0047] https://registry3.ash.shopify.io/v2/deleteme/blobs/uploads/ -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.18.8-031808-generic os/linux arch/amd64] Authorization:[Basic Og==]]
DEBU[0047] hostDir: /etc/docker/certs.d/registry3.ash.shopify.io
DEBU[0047] [registry] Calling "PUT" http://registry3.ash.shopify.io/v2/deleteme/blobs/uploads/75ca4844-a94c-4b40-9cb3-8e21d7c16565?_state=eI9aAEqgMmRdGxWZA6-Kgqv98Zb224Grxt2610KKqZt7Ik5hbWUiOiJkZWxldGVtZSIsIlVVSUQiOiI3NWNhNDg0NC1hOTRjLTRiNDAtOWNiMy04ZTIxZDdjMTY1NjUiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTUtMDQtMjlUMjA6Mzg6MTYuMjE0MjYxNDg4WiJ9
DEBU[0047] http://registry3.ash.shopify.io/v2/deleteme/blobs/uploads/75ca4844-a94c-4b40-9cb3-8e21d7c16565?_state=eI9aAEqgMmRdGxWZA6-Kgqv98Zb224Grxt2610KKqZt7Ik5hbWUiOiJkZWxldGVtZSIsIlVVSUQiOiI3NWNhNDg0NC1hOTRjLTRiNDAtOWNiMy04ZTIxZDdjMTY1NjUiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTUtMDQtMjlUMjA6Mzg6MTYuMjE0MjYxNDg4WiJ9 -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.18.8-031808-generic os/linux arch/amd64] Authorization:[Basic Og==]]
```

The [docker-side code generating these messages](https://github.com/docker/docker/blob/master/registry/session_v2.go#L216-L222) is: 

```go
	location, err := r.initiateBlobUpload(ep, imageName, auth)
	if err != nil {
		return err
	}

	method := "PUT"
	logrus.Debugf("[registry] Calling %q %s", method, location)
```

`initiateBlobUpload` does the initial `POST` to `.../uploads/`, and the `Location` header is extracted from the response to use as the URL for the followup `PUT` request.

We're running our registry from behind a reverse proxy cache, where we terminate SSL. So the registry is serving up unauthenticated HTTP but docker is speaking TLS.

It appears that the registry, despite getting the hostname right, generates URLs using `http://` -- which, to some extent, makes sense -- that is what it's speaking.

I can fix this in my own usecase by adding `proxy_redirect http:// https://` to my nginx config, but I feel like this is a problem that should probably be prevented somehow.

**Comment by burke** [comment]
cc @dmp42

**Comment by dmp42** [comment]
`X-Forwarded-Proto` maybe?

cc @stevvooe @dmcgowan 

Thanks @burke for following-up with this.

**Comment by stevvooe** [comment]
@burke Set the `X-Forwarded-Proto` to "https" and the registry will make the correct redirects.

**Comment by stevvooe** [comment]
@moxiegirl We may need to add this to the documented setup.

**Comment by burke** [comment]
Yup, that works, thanks!

**Comment by stevvooe** [comment]
This is covered in the contrib section but seems to be missing from the examples. Should we call this out explicitly?

I'm kicking this down to the 2.0.2 milestone as an existing docs issue.

**Comment by stevvooe** [comment]
We added this in https://github.com/docker/distribution/blob/master/docs/authentication.md, so we can consider the documentation bug closed.

If more users hit this issue, we will add a specific load balancer section.

**Comment by zowers** [comment]
https://github.com/docker/distribution/blob/master/docs/authentication.md is a dead link

**Comment by BrianBland** [comment]
@zowers the file was since moved to [https://github.com/docker/distribution/blob/master/docs/nginx.md](https://github.com/docker/distribution/blob/master/docs/nginx.md)
