### ISSUE TITLE
Provide backwards compatibility with v1

### ISSUE THREAD

**Issue by eburnette** [docker/distribution#481]
When the v2 registry came out it was not compatible with v1. We thought perhaps docker client 1.5 would work with both but it doesn't (see #327). The solution of having both v1 and v2 servers running behind a proxy is awkward and you end up with different content in what appears from the outside to be one registry. This request is to do the "dull" work of implementing a v1 interface in the go registry.

Having the version strings (v1, v2) allows you to innovate and create new interfaces without breaking backward compatibility. At least it should. This contract was broken with the new release and let leaves users running both 1.5 and 1.6 in a lurch. You might ask why we can't just upgrade everybody to 1.6? It's not available yet for RHEL, and besides, we have deployed software using 1.5 and 1.4 and don't want to put those users through a forced upgrade.

**Comment by dmp42** [comment]
Hi,

Docker 1.6 (like all previous versions) is compatible with the v1 protocol (hence the python registry).
So, there is not *requirement* to migrate for people who are operating their own registry.

Indeed, the current recommandation in your case is to NOT migrate your registry yet, and keep running the python one.

If you *do really really want* to migrate, the current possibilities are indeed:

 * migrate all your users to 1.6
 * wait for the compatibility bridge to be release for registry

That second solution is what you are looking for I believe, but you will have to wait a bit more.

Hope that helps.

**Comment by eburnette** [comment]
Yes, we wanted to use the v2 registry to get the speed benefits for 1.6 clients but need backwards compatibility for the 1.4/1.5 users we can't upgrade yet.

**Comment by akaspin** [comment]
Docker is not alone. Registry UI, a lots of libs and utilites - all works with V1 API. You broke all of them.

**Comment by dmp42** [comment]
Hi @akaspin 
The Docker engine up to this day supports the v1 protocol fully.
We are still fixing security issues with the open-source v1, python registry.

Can you clarify what your concerns are?

Thanks.

**Comment by bitsofinfo** [comment]
Running 1.9, and trying to point shipyard to it (my private registry) I get 

`"GET /v1/search HTTP/1.1" 404`

Only the V2 uri's work, I think this is the kind of thing that @akaspin is referring to

**Comment by LukaszStem** [comment]
Are there any plans to have the v2 registry working with both v2/v1 calls? Is there any update on this?

**Comment by dmcgowan** [comment]
@LukaszStem the v1 API has been completely deprecated and will not be included in this project. Search is still using a `/v1/search` endpoint and we would like to update that in the future to use a new v2 endpoint. In the last year there has been many tooling built around the v2 API and external projects have rallied behind it.

Closing this issue since we view the v1 API as insecure and tooling for migrating data as outside the current scope of this project.
