### ISSUE TITLE
stop the registry return UNKNOWN ERROR

### ISSUE THREAD

**Issue by fthamura** [docker/distribution#482]
I success run the docker registry 2.0, and when i try to restart it again (also using docker stop containerid), return the UNKNOWN ERROR

{"errors":[{"code":"NAME_UNKNOWN","message":"repository name not known to registry","detail":{"name":"hello-mine"}}]}
* Connection #0 to host localhost left intact

fulll steps

mervo@rne:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                    NAMES
a015d1e2bdbe        registry:2.0        "registry cmd/regist   29 seconds ago      Up 29 seconds       0.0.0.0:5000->5000/tcp   naughty_kowalevski   
mervo@rne:~$ docker stop a015d1e2bdbe
a015d1e2bdbe
mervo@rne:~$ curl -v -X GET http://localhost:5000/v2/hello-mine/tags/list
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /v2/hello-mine/tags/list HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:5000
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Docker-Distribution-Api-Version: registry/2.0
< Date: Sat, 02 May 2015 13:09:06 GMT
< Content-Length: 118
< Content-Type: text/plain; charset=utf-8
< 
{"errors":[{"code":"NAME_UNKNOWN","message":"repository name not known to registry","detail":{"name":"hello-mine"}}]}
* Connection #0 to host localhost left intact

**Comment by dmp42** [comment]
The default storage configuration uses a folder inside the container: https://github.com/docker/distribution/blob/master/cmd/registry/config.yml#L11

Thus every time you stop/start the container, you start fresh.

If you want persistence, you need to choose a different storage (mount volume, or S3/Azure).

Check here: https://github.com/docker/distribution/blob/master/docs/configuration.md#override-configuration-options for info about how to override specific configuration variable from the env.
