### ISSUE TITLE
Docs: clarify minimum docker client version

### ISSUE THREAD

**Issue by thaJeztah** [docker/distribution#484]
I've seen a couple of reports that people were having trouble running a registry 2.0, but it turned out they were trying to connect using a docker 1.4.1 or 1.5.0 client (the latest being https://github.com/docker/docker/issues/12904).

Right now, only the [Configure Nginx with a v1 and v2 registry](https://docs.docker.com/registry/deploying/#configure-nginx-with-a-v1-and-v2-registry) mentions that Docker 1.6 or newer is required for registry V2.

I suggest to add a clear warning / minimum requirements to the [index](https://docs.docker.com/registry/) and [Deploying a registry server](https://docs.docker.com/registry/deploying/) pages (perhaps other sections)

**Comment by thaJeztah** [comment]
cc @moxiegirl (in case you're currently working on these docs)

**Comment by moxiegirl** [comment]
@thaJeztah I'm working on these docs when I can. Currently, I have a special project so these are back burner. Any contributor can fix this.

I agree the locations you mention make sense for this.  We are also producing a migration guide; hopefully out next release which would be a logical place for this mention too.

**Comment by thaJeztah** [comment]
@moxiegirl alright, wanted to prevent someone making a PR, only to discover you were already working on it. If you could add the right labels to this issue (don't have permissions here), that would be great. Perhaps someone picks it up :)

**Comment by moxiegirl** [comment]
@thaJeztah If only I could. @stevvooe --- if only. :-)

**Comment by stevvooe** [comment]
@thaJeztah @moxiegirl Which documentation issues are missing the appropriate label?

**Comment by thaJeztah** [comment]
@stevvooe I don't know if ther are other issues. I assumed Mary had permissions to set labels here.

Oh, based on the discussion above, @moxiegirl may be occupied with other docs, so not sure if it should be assigned to her. I'm not able to make a PR myself (away atm), but a simple note/warning should suffice for now (a better warning can always be added later)
