### ISSUE TITLE
Add a message regarding windows data volume

### ISSUE THREAD

**Issue by moxiegirl** [docker/distribution#485]
Should include a message to warn users about pull #456

**Comment by dmp42** [comment]
Something in the line of (to be adapted/modified/rewritten):

"If you are using the Registry on Windows, we strongly advise that you do NOT use a Windows volume mounted from the host. As alternatives, you can use a S3, or Azure, backing data-store. In case you would still want to use a windows volume, you have to make sure the mount point is as short as possible - failure to do so will result on the following error message: `mkdir /XXX protocol error` and your registry will not function properly."
