### ISSUE TITLE
Standalone mode in V2 registry

### ISSUE THREAD

**Issue by sourav82** [docker/distribution#488]
Is there anything like standalone mode to mimic index in docker registry 2.0?

In V1, the standalone mode was implemented in index.py which used to mimic docker index APIs. Anything similar in V2 registry?

**Comment by dmp42** [comment]
@sourav82 there is no "index" concept in registry2.
On the other hand, the registry provides an extensive notification API that lets you implement and integrate additional services consuming registry notifications.
