### ISSUE TITLE
Authentication with Registry 2.0

### ISSUE THREAD

**Issue by sourav82** [docker/distribution#489]
How does the authentication work with registry 2.0? I noticed some config file in documentation like below but the difference between "silly" and " token" not clear.

For "token", what should I provide in "realm" field? Is it a URL to a authentication service? Then what is "service"? Could you please provide some examples on how to use this configuration for setting up authentication? Will it work with self-signed certificates?

auth:
    silly:
        realm: silly-realm
        service: silly-service
    token:
        realm: token-realm
        service: token-service
        issuer: registry-token-issuer
        rootcertbundle: /root/certs/bundle

**Comment by RichardScothern** [comment]
Hi @sourav82 

The authorization options are documented [here](https://github.com/docker/distribution/blob/master/docs/configuration.md#auth)

In short: 'silly' should only used for testing/developing  

'token' is the correct way to do authentication and is documented in depth [here](https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md)

**Comment by dmp42** [comment]
@sourav82 you can also use a proxy pattern (nginx providing basic authentication, in front of the registry).

You will find sample nginx snippets over there: https://github.com/docker/distribution/tree/master/contrib/compose/nginx

**Comment by dmp42** [comment]
Hi @sourav82 

Does this answer your questions?
I'm closing this as answered for now, but let us know if this feels unaddressed.

**Comment by AngryHacker** [comment]
I also read the document about silly and token authentication, but still don't know how to use it.

For example, I use the silly options, but how does it work with my client 1.6. 

It reports a problem like this:

FATA[0014] Error response from daemon: no successful auth challenge for http://localhost:4000/v2/ - errors: [Get http://silly-realm?account=silly&service=silly-service: dial tcp: lookup silly-realm on 192.168.11.99:53: server misbehaving] 

How can I deal with it?

**Comment by dmp42** [comment]
@AngryHacker your log line tells you that your host uses DNS server 192.168.11.99 and that this DNS server is not working properly.
If you are using boot2docker, it's a known VirtualBox issue to not catch up with host DNS configuration changes, so please restart your VM.
Otherwise, check and fix your DNS config in your host.

**Comment by stevvooe** [comment]
@AngryHacker I am not sure that you did read the documentation:

> The `silly` auth is only for development purposes. It simply checks for the
existence of the `Authorization` header in the HTTP request. It has no regard for
the header's value. If the header does not exist, the `silly` auth responds with a
challenge response, echoing back the realm, service, and scope that access was
denied for.

**Comment by AngryHacker** [comment]
@stevvooe Sorry. I did read it, but I'm not quiet understand. But now I think I have figured out what the document mean. Thank you.

**Comment by stevvooe** [comment]
@AngryHacker Do you think there is a way to clarify the language to help people better understand?

We may be missing a documentation section on authorization that would help here.

**Comment by AngryHacker** [comment]
@stevvooe Maybe more detail? I don't have a good idea about that.

**Comment by AngryHacker** [comment]
@stevvooe Can you answer the question here:<a>http://stackoverflow.com/questions/30367803/what-does-the-declare-var-fileinfo-fileinfointernal-mean-in-golang</a> which make me confused? Thanks!

**Comment by dmp42** [comment]
@AngryHacker The blank identifier (_) ignores the right hand assignment, and this verifies that FileInfoInternal does implement the interface FileInfo.

**Comment by AngryHacker** [comment]
@dmp42  But why should check both FileInfoInternal and &FileInfoInternal?

**Comment by AngryHacker** [comment]
@dmp42 @stevvooe Could you explain what an image manifest is or just give me document I can read? I am confused about it but little people know it. Someone says it's a Dockerfile but I guess not?

**Comment by dmp42** [comment]
@AngryHacker 

A Dockerfile is what lets you build an image - each instruction in a Dockerfile generates a layer.
When then exchanging an image, you use a Manifest file that represents that image, and contains the list layers id. A manifest is a json simple representation of a builded image.

The format itself is documented here:
https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-1.md

**Comment by stevvooe** [comment]
@AngryHacker I put a comment on the top answer. I'm not sure why I did both other than defensive programming. If that answer is not enough, let me know.

A manifest simply describes how to build an image. docker/docker#8093 covers the original design for the provision v2 manifest. I did a talk the other day that covers the concepts which should be available in the next few days.

I know its easy to get a hold of us via github issues, but let's keep the issue discussion topical to the issue. If you have questions like this, the best avenue is distribution@dockerproject.org.

**Comment by AngryHacker** [comment]
Thank you! I will follow it.

**Comment by ashish235** [comment]
I can push and pull the images from my registry running over https using a self signed cert. 

However I can't apply a authentication to the registration, I don't want the nginx layer, so was using registry's native auth.

However, I 'm getting an error while login.
 
[root@client2 ~]# docker login myregistrydomain.com:5000
Username: testuser
Password:
Email: ashish.mishra@alepo.com
FATA[0013] Error response from daemon: no successful auth challenge for https://myregistrydomain.com:5000/v2/ - errors: []




The command to start my registry was

[root@localhost alepo]# docker run --entrypoint htpasswd registry:2 -Bbn testuser testpassword > auth/htpasswd

[root@localhost alepo]# docker run -d -p 5000:5000 --restart=always --name registry \
>   -v `pwd`/auth:/auth \
>   -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
>   -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
>   -v `pwd`/certs:/certs \
>   -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
>   -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
>   registry:2
a8a267f3e3fde75bec42d73120f7b7fda29af1b37769be49ff9974e0feb2e45b

**Comment by dmp42** [comment]
@ashish235 you are missing `-e REGISTRY_AUTH=htpasswd` in your launch command.

https://github.com/docker/distribution/blob/master/docs/deploying.md#native-basic-auth

The docs website is not up to date.

**Comment by ashish235** [comment]
@dmp42 , thanks mate. It's working now.

**Comment by dmp42** [comment]
Welcome.

**Comment by ndelitski** [comment]
please add `-e REGISTRY_AUTH` on website

**Comment by stevvooe** [comment]
@ndelitski Thank you for your feedback, but please do not comment on closed issues.
