### ISSUE TITLE
clientcas configuration for registry v2

### ISSUE THREAD

**Issue by wangzhezhe** [docker/distribution#498]
Hi, It seems that the clientcas section have been added into the config of docker registry v2 , how could I config it if I want to limit the client which could access to the registry service ? Any one could give me some suggestions? Thank you!

**Comment by dmp42** [comment]
This has not been merged yet, and is still being discussed / reviewed: #453

**Comment by stevvooe** [comment]
@dmp42 #453 actually deals with the root CAs passed to the client when presenting the server certificate.

@wangzhezhe Client certificates provide client authentication but aren't tied into the authorization system. You can control access by issuing client certificates to authorized clients but you cannot issue some certs that allow push and others that allow pull.

**Comment by stevvooe** [comment]
@wangzhezhe I think a similar feature request is a part of #107. Unless its wildly different, I'm going to close this ticket.
