### ISSUE TITLE
Compatibility of image data in S3 backends between old python docker-registry and registry 2.0

### ISSUE THREAD

**Issue by shichao-an** [docker/distribution#502]
I've been running the python docker-registry for a while with S3 storage and it already had some Docker images pushed to it. I was wondering if I new registry 2.0 will work with the old S3 bucket that stored old images. I mean, if I set up a new registry 2.0 with the same aws access key, bucket name and root directory path, will it work with the image data in the bucket (without re-building and re-pushing the old images)?

**Comment by dmp42** [comment]
@shichao-an see #481 
In a word: registry2 does not deliver v1 content, but you are able to run both simultaneously so that docker 1.6 can access both your new and old images from either registry.
