### ISSUE TITLE
Clarify requirement of Docker-Content-Digest

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#505]
The V2 API should be serviceable over static web servers. Requiring the `Docker-Content-Digest` header on requests will make these harder to accomplish. From the specification:

> The Docker-Content-Digest header returns the canonical digest of the uploaded blob which may differ from the provided digest. Most clients may ignore the value but if it is used, the client should verify the value against the uploaded blob data.

We need to ensure that the above applies to all uses of `Docker-Content-Digest`, not just the uploads.

Please see https://groups.google.com/forum/#!topic/docker-dev/zyKH0pnyWnI for discussion.

cc @dmcgowan

**Comment by dmcgowan** [comment]
We should validate this against #387 before merging.  Docker 1.6.x should happily accept pulling digests without this header.
