### ISSUE TITLE
Registry read-only mode

### ISSUE THREAD

**Issue by RichardScothern** [docker/distribution#510]
Inspired by #459 

Add support for registry read-only mode.  Milestone 1 will be functionality implementation while the config specifics are worked out.

**Comment by aaronlehmann** [comment]
My plan right now is to allow the read-only mode to be toggled on and off using an administrative API endpoint. When the registry is put in read-only mode, all API operations that mutate data will return errors. This means that in-progress pushes will fail, either while uploading the next layer, or pushing the manifest (returning a descriptive error explaining why). There is a small race window if a push is being finalized with a slow manifest upload at the moment the registry is switched into read-only mode. I don't expect this to be a problem in practice, but if we want to protect against it, we could add a second check verifying that the registry is not read-only when the manifest is fully received.

If there are multiple registries using the same backend storage, they will all need to be put into maintenance mode before it's safe to run a garbage collection pass. This will be documented as the administrator's responsibility.

I have some rough initial code here: https://github.com/aaronlehmann/distribution/commits/read-only-mode. This hasn't been tested yet, and would need further work on documentation, unit testing, etc. I wanted to circulate this for review before I refine it further, to make sure I'm on the right track. I'm particularly interested in knowing whether there are any races I'm not considering that are important here, and whether the new API endpoint is the right approach (and right design) vs. changing a config file and restarting. Also, is the authentication access record I added in appendAdminAccessRecord the right idea?

**Comment by dmp42** [comment]
cc @docker/distribution-maintainers and @BrianBland @donhcd @rajat-docker @AndreyKostov

**Comment by dmp42** [comment]
also cc @bcwalrus and @avinson

**Comment by aidanhs** [comment]
> There is a small race window if a push is being finalized with a slow manifest upload at the moment the registry is switched into read-only mode.

So the impact of this race is that a push may complete successfully when you don't expect it to? Seems like you could just document "In-progress layer or manifest uploads at the point of enabling read-only mode will complete successfully."

Of course, this also depends on whether it's controlled by config file - doing a hard-restart means, of course, that anything in-progress will just fail.

**Comment by noxiouz** [comment]
Swith on RO mode via HTTP could be dangerous without saving it in some persistent storage. In the proposal RO-mode status is saved only in memory of the registry, so if it restarts (or the server reboots), the mode will change back to RW. If we have only one instance it's not a problem as GC would stop too. But when it comes to a cluster installation one of RW-mode registry leads to data corruption, when GC is working.

**Comment by noxiouz** [comment]
I think we could move code, that checks if the maintaince mode on, into a decorator (I like python :)) and wrap all handlers which can modify content.

**Comment by aaronlehmann** [comment]
Good suggestion on the decorator. I'll make a new revision of this that wraps the handlers that modify content, instead of checking directly inside those handlers.

Any suggestions on a mechanism to persistently store the read-only flag?

**Comment by noxiouz** [comment]
> Any suggestions on a mechanism to persistently store the read-only flag?

@aaronlehmann  the first that comes to my mind is a file in ```/var/run/distribution/``` and start in RO if it exists. But it's inconvenient sometimes, I should think more about it.

**Comment by stevvooe** [comment]
@aaronlehmann It might be better to have a configuration value that is read on startup. Just bounce the registry and re-read the configuration. This ensures that any active connections are shutdown before moving into read-only mode.

Otherwise, we risk creating a challenging synchronization problem.

**Comment by aaronlehmann** [comment]
Okay, I'll redo this to use the configuration file instead of an API. I was originally reluctant to require a restart because that would interrupt all clients, including readers. But I see the argument that the setting needs to be made persistent.

Do we want to provide any automation around changing the configuration file and restarting the registry, or is it an acceptable UX to tell the admin to edit the config file, restart the service, and change the config file back?

**Comment by stevvooe** [comment]
@aaronlehmann Like the GC feature, we should provide documentation and guidance on how to use the feature. The actual tooling would likely be infrastructure specific. We may want a compose example to demonstrate this.

**Comment by aaronlehmann** [comment]
PR for configuration approach here: https://github.com/docker/distribution/pull/827
