### ISSUE TITLE
How to implement a registry/index server that can support multi-thread download image?

### ISSUE THREAD

**Issue by nkwangleiGIT** [docker/distribution#527]
Hi,
As I tried, the docker hub server can support multi-thread download for image layers, I'm also trying to do this in my private registry server, but not sure what's the correct approach.
Can someone shed me some light about how I should do this?
Thanks.

**Comment by nkwangleiGIT** [comment]
I'm using v1 registry server that was written in python, not sure if v2 registry server can support this better.

**Comment by dmp42** [comment]
Hi @nkwangleiGIT 

Can you clarify what you want to achieve?
Registry2 does support concurrent downloads from multiple clients AFAIK.

**Comment by nkwangleiGIT** [comment]
Hi dmp42, thanks for your reply.
I mean that I want to have each docker client to pull multiple layers simultaneously(like mutiple thread download), I think this is the current behavior of docker hub, and it's really helpful to shorten docker pull time. 
As I can see, Registry v2 seems support this feature looking at the code 'registry/client/pull.go', 

`// simultaneousLayerPullWindow is the size of the parallel layer pull window.`
`// A layer may not be pulled until the layer preceeding it by the length of the`
`// pull window has been successfully pulled.`

So I'm not sure if it's possbile to implement the similar featuer using Regisitry v1, thanks1

**Comment by dmp42** [comment]
Sorry for I still don't understand :(

Both registry1 and registry2 do support multiple pull layers simultaneously.

**Comment by nkwangleiGIT** [comment]
Hi dmp42, 
When I tried "docker pull wordpress", here is what I can see on the console:

<b>5cb92ead0b4f: Downloading [==>                                                ] 473.5 kB/8.718 MB</b>
<b>3ac8b4efedb1: Downloading [>                                                  ] 457.7 kB/44.42 MB</b>
11ccea069165: Download complete 
f9f9b5e629d1: Download complete 
<b>6d13231a6adc: Downloading [================>                                  ] 913.6 kB/2.842 MB</b>
a697bde01e1c: Download complete 
52973be1fee7: Download complete 
91bbc85fc4ae: Download complete 
d216961bb230: Download complete 
bcb42637a706: Download complete 
66a111fbcfb9: Download complete 
da244c4b78eb: Download complete 
504d3773dda6: Download complete 
d72463f0d44f: Download complete 
<b>81ab112649b0: Downloading [=>                                                 ] 629.7 kB/30.9 MB</b>
877e4c938f65: Download complete 
ced925523378: Download complete 
a8ed0be48606: Download complete 
648078ec9047: Download complete 
4ed8e8ef7419: Download complete 
f40db3c4ca11: Download complete 
<b>bec93986b1ea: Downloading [=========>                                         ] 554.4 kB/2.856 MB
23057fe22163: Downloading [==========================>                        ] 420.8 kB/802.6 kB</b>
ed0f02023b2a: Download complete 
48daf2b5f12a: Download complete 
7dfcd31e5ac1: Download complete 
cea713c16a60: Download complete 
559542a5820a: Downloading [===>                                  

So I think docker image layers can be downloaded in parallel, but if I pull from my private registry like "docker pull localhost:5000/ubuntu", image layer can only be downloaded in single thread like below:

cea713c16a60: Download complete 
<b>559542a5820a: Downloading [=============================================>     ]  5.57 MB/6.154 MB</b>

I want to know how I can make my priviate v1 registry work like docker hub without too much effort, thanks a lot!

**Comment by dmp42** [comment]
This is about the client.

Please use `registry:2` and not the old python registry.

**Comment by nkwangleiGIT** [comment]
Hi Olivier, thanks for your kindly help, it's helpful for me.
