### ISSUE TITLE
Alternative to searching in registry

### ISSUE THREAD

**Issue by sourav82** [docker/distribution#528]
Looks like Registry V2 does not provide search API to list images from registry. While executing "docker search" against V2 registry, it throws error 404.

Could you please let me know if there are any alternatives on searching images in V2 registry?

**Comment by chenjie901** [comment]
i have the same quesion

**Comment by stevvooe** [comment]
#441 and #206 cover this. We are proposing a catalog API.

Closing as a duplicate.
