### ISSUE TITLE
Unable to find image - calls to v1 but I am only running v2 and Docker 1.6.0

### ISSUE THREAD

**Issue by jbrook** [docker/distribution#536]
I am running Docker 1.6.0 and Registry 2.0 with S3 in a private network on EC2 with no SSL and no authentication. When I try to pull or run an image I get the following:

`docker run xxx.yyyyyy.com:5000/myorg/flask-signup:v_35
Unable to find image 'xxx.yyyyyy.com:5000/myorg/flask-signup:v_35' locally
Pulling repository xxx.yyyyyy.com:5000/myorg/flask-signup
FATA[0000] Error: image myorg/flask-signup:v_35 not found`

I see the following in the registry log. The manifest request (v2) succeeds but the images request (v1) fails with a 404:

`10.0.1.41 - - [20/May/2015:13:24:07 +0000] "GET /v2/myorg/flask-signup/manifests/v_35 HTTP/1.1" 200 44692 "" "docker/1.6.0 go/go1.3.3 kernel/3.14.35-28.38.amzn1.x86_64 os/linux arch/amd64"
time="2015-05-20T13:24:07.953149296Z" level=info msg="response completed" environment=zzzzzzzz http.request.host="xxx.yyyyyy.com:5000" http.request.id=ebae0571-ebde-4423-8611-71483494c34b http.request.method=GET http.request.remoteaddr="10.0.1.41:44210" http.request.uri="/v1/repositories/myorg/flask-signup/images" http.request.useragent="docker/1.6.0 go/go1.3.3 kernel/3.14.35-28.38.amzn1.x86_64 os/linux arch/amd64" http.response.contenttype="text/plain; charset=utf-8" http.response.duration="72.365µs" http.response.status=404 http.response.written=19 instance.id=64e1c991-bfdc-4528-96b5-bd9587608013 service=registry version=v2.0.1.m
10.0.1.41 - - [20/May/2015:13:24:07 +0000] "GET /v1/repositories/myorg/flask-signup/images HTTP/1.1" 404 19 "" "docker/1.6.0 go/go1.3.3 kernel/3.14.35-28.38.amzn1.x86_64 os/linux arch/amd64"`

Shouldn't I be able to run registry 2.0 alone?

**Comment by dmp42** [comment]
The engine falls back to v1 only if it fails to communicate with a v2 registry, or fails to find the image you are requesting.

Here, what this log says is: `myorg/flask-signup:v_35 is not found on xxx.yyyyyy.com:5000`.

Can you verify that you did push this image?

Can you copy the docker daemon logs when pushing this image?

Thanks.

**Comment by jbrook** [comment]
Same problem as #538
