### ISSUE TITLE
is there any instruction how to run registry not in docker container ?

### ISSUE THREAD

**Issue by pronix** [docker/distribution#537]
hello
I want start registry,but without docker container.
may be somebody wrote instruction early ?
thanks

**Comment by pronix** [comment]
just found it.
```
DISTRIBUTION_DIR=~/.go/src/github.com/docker/distribution \
GOPATH=$DISTRIBUTION_DIR/Godeps/_workspace:$GOPATH \
make PREFIX=~/.go clean binaries
```
and appear compiled app
```
~/.go/bin/registry
~/.go/bin/dist
~/.go/bin/registry-api-descriptor-template
```

**Comment by stevvooe** [comment]
@pronix This is also available in the documentation on [building](https://github.com/docker/distribution/blob/master/docs/building.md).
