### ISSUE TITLE
2.0: Simple example not working - distribution/docs/deploying.md

### ISSUE THREAD

**Issue by jbrook** [docker/distribution#538]
I followed the directions for pulling, retagging and pushing the hello-world image but I used my own registry 2.0 installation running on a different host.

Unlike in the example, after I tag the image I see that when I list my images the original and the retagged versions have identical image ids.

Then when I try to push the retagged image to my 2.0 registry I see the following:

`docker push reg.xxxx.com:5000/hello-mine:latest
The push refers to a repository [reg.xxxx.com:5000/hello-mine] (len: 1)
91c95931e552: Image already exists
a8219747be10: Image successfully pushed
FATA[0001] Error pushing to registry: Server error: 400 trying to push hello-mine:latest manifest`

Then when I list the images using the API I see the following:

`> GET /v2/hello-mine/tags/list HTTP/1.1
> User-Agent: curl/7.40.0
> Host: reg.xxxx.com:5000
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< Date: Wed, 20 May 2015 13:45:42 GMT
< Content-Length: 34
<
{"name":"hello-mine","tags":null}`

**Comment by dmp42** [comment]
Hi,

Can you copy your registry logs?

**Comment by dmp42** [comment]
Also, can you provide your docker daemon logs, preferably in debug mode?

The simple instructions direct you to install and run of localhost - if you don't, then you need to setup TLS, or add --insecure-registry to be able to access it.

**Comment by jbrook** [comment]
I solved it. It's caused by an outdated library on the Amazon Linux EC2 container services instances that I am using - golang-libtrust-devel

The docker daemon showed the following error:

`ERRO0050 Error from V2 registry: error verifying manifest: error parsing payload: error unmarshalling public key: JWK EC Public Key ID does not match: HX4C:4632:DIUC:LYE5:GKKZ:F6FA:5IUZ:WNT4:ZG2W:YCCD:Y4MA:2MJU`

It fails to fetch the image from the registry on this error but it only appears in the regular logging as a 404. Then it falls back to v1.

It seems you still need to update docker and the library on Amazon EC2 container service instances manually after you have launched them from their standard AMI, so I suspect this is catching a lot of people out.

https://forums.aws.amazon.com/thread.jspa?messageID=622774

**Comment by dmp42** [comment]
@jbrook thanks for the feedback.
May I ask that you reach out to Amazon to let them know this is still an issue?

Sorry about the inconvenience here.
