### ISSUE TITLE
docker login fails when disabling basic auth for /v2/

### ISSUE THREAD

**Issue by antonosmond** [docker/distribution#539]
As the v2 registry has no _ping endpoint (unless I've missed it) it looks like the equivalent is to check for a 200 OK status from /v2/. I have a registry setup using nginx for basic auth & ssl. I want to have a health check endpoint which doesn't require authentication so in my nginx config, `location = /v2/` has `auth_basic off;` and `location /v2/` has `auth_basic "Restricted";`

This works as expected when browsing directly to the endpoints e.g. 
`my_registry_ip/v2/` - does not require auth or prompt to login
`my_registry_ip/v2/some_repo/tags/list` - requires auth and prompts to login

The problem is when a client tries to login to the registry using `docker login my_registry_ip`.
The user is prompted for credentials and on providing valid credentials gets the error:
`FATA[0015] Error response from daemon: no successful auth challenge for https://my_registry_ip/v2/ - errors: []`

Maybe it's my setup / nginx config but seems strange that everything works when browsing directly to the endpoints. Also, I should add that my client trying to log in to the registry is docker 1.6.0 running in boot2docker on OS X. and yes I have enabled the insecure registry setting as I'm currently using a self signed certificate for ssl.

**Comment by dmp42** [comment]
Disabling auth on /v2 is what broke it.
I would recommend sticking with the nginx snippets in the contrib folder.

If you want a health check endpoint, I would suggest either using authentication for it, or maybe relying on the debug server (see doc).

Hope that helps.

**Comment by antonosmond** [comment]
So are there plans to include a simple ping endpoint that doesn't require auth? Otherwise, how would you setup a registry in AWS for example, behind a load balancer with a health check?

**Comment by dmp42** [comment]
If I remember correctly, the debug endpoint is meant for that, including specific health-check sub urls.

https://github.com/docker/distribution/blob/master/docs/configuration.md#debug

#230

**Comment by antonosmond** [comment]
Looks ok for dev but says:
"Docker recommends disabling it in production environments."
Personally I think a _ping endpoint like the old registry had would be great but thanks for your help anyway.

**Comment by stevvooe** [comment]
@antonosmond Docker does not recommend that @moxiegirl. The debug endpoint should not be exposed to the outside world. Monitoring the debug endpoint is critical to monitoring registry health.

**Comment by antonosmond** [comment]
Thanks for your help guys I'll use the debug endpoint as suggested.

**Comment by moxiegirl** [comment]
@stevvooe assign to me; I'll pick this one off shortly

**Comment by stevvooe** [comment]
@moxiegirl I already fixed it. Please see #541.
