### ISSUE TITLE
Define backend lifecycle behavior in registry webapp

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#54]
Currently, the lifecycle of a storagedriver is very adhoc. docker/docker-registry#354 described some desired behavior, indicating an instance should be able to start, even if the backend is down or inaccessible. We need to define what the behavior is and what failures are seen when the backend is down. This may require a health check endpoint.

This issue supersedes docker/docker-registry#354 and should take inspiration from the discussion there.

**Comment by tamsky** [comment]
@dmp42 Was any work done to define things - or has this been closed and WILL NOT FIX ?

**Comment by stevvooe** [comment]
@tamsky This issue has been closed due to it being fairly vague. The original complaint from docker/docker-registry#354 is not an issue we've seen in from the V2 registry.

If there was something specific that you wanted fixed, please file an issue.
