### ISSUE TITLE
Should the S3 library fallback on reading creds from .aws/credentials?

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#551]
If we want this, that probably could be documented.

See #550 for context.

**Comment by stevvooe** [comment]
@dmp42 I'm not sure. This is a fallback in the s3 library, which is surprising and little dangerous. I've added a better error message.

**Comment by dmp42** [comment]
K.

http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs

That should be it: 

https://github.com/AdRoll/goamz/pull/179/files

Specifically: https://github.com/AdRoll/goamz/pull/179/files#diff-de4572d7c0118f08948ab376e48525a3R377

I'm on the fence here about what to do with this.

**Comment by stevvooe** [comment]
@dmp42 It sounds like we should support but need to documentation to avoid surprise.

Generally, I prefer to avoid these kind of configuration "hidey holes", since it is very hard to debug when things go wrong.

**Comment by BrianBland** [comment]
Fixed by #1413, documentation issue filed at #1447
