### ISSUE TITLE
Release tarball doesn't build

### ISSUE THREAD

**Issue by xphoenix** [docker/distribution#554]
That is because .git/HEAD dep in AUTHORS rule. 

Tarball doesn't contain git files, so make command fails

**Comment by stevvooe** [comment]
@xphoenix There is no officially supported release tarball. If this is required, please submit a PR to address this.

**Comment by xphoenix** [comment]
Thanks, I didn't know

**Comment by stevvooe** [comment]
@xphoenix Would you like a release tarball? If you're just building, I'd recommend you checkout from source.

The main issue here is that the Makefile for this project is really a development tool.
