### ISSUE TITLE
How can I grab the HTTP request/response between client and registry with Wireshark?

### ISSUE THREAD

**Issue by AngryHacker** [docker/distribution#560]
Hi~
I'm trying using the wireshark to grab the HTTP request/response between the client and registry, but it  looks a little strange.

My private registry runs in localhost:5000 without tls, and I try to push a images to it.
When I use wireshark, I try to listen to 'docker0' interface or the 'lo' with 'tcp.port eq 5000', the captured packets appear in protocol only tcp and ipa, but without http. In some ipa packets, there are some data looks like http protocol but it's partical. 

This makes me confused, because according to my understanding, the data exchange between should be all using http protocol.
I want to ask why, and if it does't work, how can I analyze the data flow between the client and registry? Thank you!

**Comment by dmp42** [comment]
@AngryHacker I think this was suggested to you earlier already: please use either the mailing list or the irc channel for general questions.
Please do NOT use the bugtracker for random questions.

Furthermore, this is way unrelated to the registry, or even to Docker.
Before trying to use a tool like WireShark, please start with:

 * reading the API documentation
 * looking at the logs (both docker and registry)

I fail to see why you would want wireshark here.

I'm closing this for these reasons.

**Comment by AngryHacker** [comment]
Sorry. I will follow it next time. I didn't make clearly before.
