### ISSUE TITLE
Client Package: question about working mode

### ISSUE THREAD

**Issue by xiekeyang** [docker/distribution#561]
@dmcgowan @stevvooe 
I've some question on Client Package.
I read client package code, and partly understand.
However, I still want to learn some point:
Should it be called by which package? 
If it should work under Index Endpoint Mode (according to comments on #387)?
It looks like no Client Spec yet. Can you present a spec?
Appreciate!

**Comment by dmcgowan** [comment]
@xiekeyang what do you want to achieve with the client package?

Instantiating a client can be achieved through calling http://godoc.org/github.com/docker/distribution/registry/client#NewRepository, then the documentation for the distribution package should get you the rest of the way http://godoc.org/github.com/docker/distribution. The client is using the distribution API specification at https://github.com/docker/distribution/blob/master/docs/spec/api.md.

Let me know if the documentation for the client package is lacking or confusing. If you need to connect using basic auth then that can be achieved through creating an `http.RoundTripper` which the `github.com/docker/distribution/registry/client/transport` can help you with.

**Comment by dmp42** [comment]
@xiekeyang also, please use either the mailing list or irc for such questions.
