### ISSUE TITLE
Pushing existing images to docker-hub is very slow

### ISSUE THREAD

**Issue by andersjanmyr** [docker/distribution#563]
Hi,

Pushing images is very slow, for example pushing an image with 25 already existing layers takes
me about 3 minutes.

It seems to me that there are two problems with the current implementation.

* No caching of the the existing checksums leads to a redirect on every HEAD request.
* No bulk-check is implemented

The client knows all the checksums it want to send and it should be possible to implement a bulk check endpoint that can take a list of checksums and reply with the ones that the server needs.

Transferred from https://github.com/docker/docker/issues/13454

**Comment by andersjanmyr** [comment]
After reading the spec some more, it seems to me that all the required information is already available in the manifest. By sending the manifest to the server before starting to upload images, the server could reply with what images it needs and the client only needs to upload the missing images.

**Comment by stevvooe** [comment]
@andersjanmyr Let's keep this conversation in docker/docker#13454 until we've identified the root cause.
