### ISSUE TITLE
README.md is not rendered properly

### ISSUE THREAD

**Issue by l3iggs** [docker/distribution#571]
My README.md files taken from my GitHib projects and displayed on the project page in the registry are not rendered properly.

For example:
https://registry.hub.docker.com/u/l3iggs/owncloud/

The list numbering is messed up.

**Comment by dmp42** [comment]
This is a hub issue.
Please report it to Docker support: https://support.docker.com

(see https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#are-you-having-issues )

**Comment by l3iggs** [comment]
Ah. Sorry. Thanks. Navigating all these bits is hard!

**Comment by dmp42** [comment]
@l3iggs yeah, sorry about that :)
Will try to make the docs more friendly.
