### ISSUE TITLE
Docs for storage drivers versioned in external repositories

### ISSUE THREAD

**Issue by wking** [docker/distribution#577]
I'm looking to write an experimental storage driver based on [IPFS][], but I'm not sure how to build/install/deploy an [in-process driver][1] without forking docker/distribution and building my driver there.  Alternatively, I could try and get my driver landed in *this* repository, but I doubt I can commit to [the one-year maintenance requirement][2].  Since the storage-driver API is fairly stable, is there a way for me to easliy maintain my storage driver in an external repository and then build it into the most recent distribution release (ideally building on the [registry image][3]) without forcing me to maintain a fork of your registry core or you to maintain a fork of my storage driver?  This seems easier for everyone than building all of the storage drivers (or other pluggable parts) into this repository.

If there is no way to do this cleanly for in-process drivers (and, with Go's avoidance of dynamic linking, that might be the case), then maybe I have to use an [out-of-process driver][4].  In this case, there are a number of details that are unclear from the docs.  What do I call my compiled process?  How to I run a test suite based on `RegisterIPCSuite` from my external repository?

I imagine someone has thought these issues through and can quickly point me in the right direction.  I'm happy to write up and PR docs for anything folks can sketch out for me.  Otherwise I'll see what I can come up with by poking around in the source ;).

[IPFS]: http://ipfs.io/
[1]: https://github.com/docker/distribution/blob/master/docs/storagedrivers.md#in-process-drivers
[2]: https://github.com/docker/distribution/pull/493#issuecomment-99174009
[3]: https://github.com/docker/distribution/blob/master/docs/deploying.md
[4]: https://github.com/docker/distribution/blob/master/docs/storagedrivers.md#out-of-process-drivers

**Comment by wking** [comment]
Hmm, and maybe the IPC approach is still a work-in-progress, even for in-repository code.  For example, the IPC tests have been commented out since ab9570f8 (Migrate filesystem driver to new storagedriver calls, 2014-12-03, #1) which cited stability problems.

**Comment by dmp42** [comment]
This calls for a detailed answer (invoking @stevvooe for that)

IPC/out of process drivers, we pulled the plug - reliability issues.
I would love to see a good/better solution to achieve that, though.

For your immediate "desire", I would suggest you start an in-tree driver.
If it's worth merging but you cannot commit to maintenance, an intermediate solution would be to merge it but not build it by default (we should conditional compile all drivers).

Look at Ceph for a great driver (recent) example : #443

**Comment by stevvooe** [comment]
@wking To bring in external storage drivers at this time, you'll have to embed the distribution project with a dependency that registers the new storage driver and imports it in the main file. It's pretty straightforward but the structure of the main file makes this a little challenging. Alternatively, you can do this in a fork, then when you believe it is ready for inclusion, it can simply be PR'd back into master. We can have a discussion at that time about on-going maintenance.

IPC is as good as dead, at this point. We had a very bad experience with the RPC implementation and debugging was very problematic. We may want to remove the dead code.

For IPFS, rather implementing a storage driver directly, it might be worthwhile to experiment with implementing the distribution interface direction. IPFS provides content addressing and naming in the same vein as the design there. This would be a larger architectural change but might yield a better result.

**Comment by wking** [comment]
On Mon, Jun 01, 2015 at 01:31:19PM -0700, Stephen Day wrote:
> … you'll have to embed the distribution project with a dependency…
> It's pretty straightforward but the structure of the main file makes
> this a little challenging.

If this is a recommended approach it's probably worth documenting at
some point.  But keeping this embedding up to date sounds tricky.
Ideally, I guess I'd like something like:

  my-project$ cat main.go
  package main

  import (
    registry "github.com/docker/distribution/cmd/registry"
    ipfs "github.com/wking/ipfs-docker-registry-driver"
  )

  func main() {
    server = registry.NewServer()
    server.Storage.Register("ipfs", &ipfs.StorageDriverFactory{})
    server.serve()
  }

so I can just consume everything that's currently in
cmd/registry/main.go without needing to fork everything it contains.

> Alternatively, you can do this in a fork…

That sounds like the easiest path forward at the moment, so I'll go
this way for my driver.

> For IPFS, rather implementing a storage driver directly, it might be
> worthwhile to experiment with implementing the distribution
> interface direction. IPFS provides content addressing and naming in
> the same vein as the design there. This would be a larger
> architectural change but might yield a better result.

So write up something to serve the registry API, instead of something
to serve the storage-driver API?  Or do you mean something else by
“distribution interface”?

Personally, I think it makes more sense with IPFS to just drop the
layer approach entirely, and use IPFS to distribute the image
filesystems directly.  That would make a number of outstanding Docker
issues irrelevant (e.g. docker/docker#3156 and other issues with “how
do I not distribute my build tooling”, #462 and asynchronous garbage
collection).  It also means that there's no need for a Docker-specific
image spec beyond the metadata needed for launching an image from a
container (the stuff currently setup by EXPOSE, CMD, etc.).  But
before this approach is feasible we'll need better metadata tracking
in IPFS (e.g. file modes ipfs/go-ipfs#846) and better layer-vs.-image
decoupling in Docker (I'm currently playing with nsinit from
libcontainer).  But that's a bunch of things that need to happen, so
until we get there I'm looking at an IPFS storage driver ;).

**Comment by dmp42** [comment]
Hi @wking should this be closed?

**Comment by balboah** [comment]
@wking did you have any success in ipfs as a storage backend?

**Comment by wking** [comment]
> @wking did you have any success in ipfs as a storage backend?

I'd stubbed it out in dd20e16ee7 and 8d10627a2b.  There are some comments on the commits, but it's been a long time and I don't have time to push it further.  Feel free to use that early work (or not) if you want to tilt at this particular windmill ;).

I [still][1] think the best long-term approach would be to use IPFS for direct rootfs distribution without involving the image-spec abstractions, but for many use cases that's still blocked on ipfs/go-ipfs#612.

[1]: https://github.com/docker/distribution/issues/577#issuecomment-107733524

**Comment by balboah** [comment]
it sounds like a perfect match to me, when docker has layers with corresponding hashes and ipfs uses hashes to route to that content. Would be pretty awesome to have a distributed registry that caches by itself in each cloud provider cluster
