### ISSUE TITLE
How to verify images migration correctness

### ISSUE THREAD

**Issue by oilbeater** [docker/distribution#585]
Hi, I am trying to migrate images from registry V1 to V2 by a docker client pulling from V1 and pushing to V2. After migration, I want to make sure all the layers content are same in both registry. 

There is a Manifest api that can get layer blobsum in V2. Is the blobsum same with X-Docker-Checksum header returned by Get image layer api in V1. If not, is there a method to solve this problem?

**Comment by stevvooe** [comment]
I am unaware of `X-Docker-Checkusm`. You can experiment with it but there are no guarantees.

The V2 manifest includes the v1 layer json in the `v1compatibility` field. The safest way to check is to unpack that, then fetch those layers from the v1 registry, by their layer id, then verify that the manifest digest matches the digest of the content fetched by layer id.

**Comment by dmp42** [comment]
@oilbeater in theory that would work, but I don't think this does in practice.
The reason for that is the docker engine does not keep the unexpanded tarfiles - it does expand them, then pack them when it wants to push. In the meantime, white-out files used by graphdrivers are going to have their mtime modified, technically generating a different tarfile thus a different sha.

Furthermore, in the v1 world things are highly unverified.

If you are strongly concerned about integrity here, you may try to compare the tarfiles directly with your own tooling, disregarding data like X-Docker-Checksum.

Let me know if that helps.

**Comment by oilbeater** [comment]
@dmp42 Thanks for your advice, comparing the tarfiles directly seems make sense.

I am a little confused that if every push generates a different sha, what's the meaning of the blobsum field.

**Comment by dmp42** [comment]
@olibeater in the v2 world, every push (from the same build) will generate the same sha (likely not true in the v1 world though).

**Comment by oilbeater** [comment]
@dmp42 When image size is big, saving the tarballs and comparing them take lots time.

How the v2 generate the sha? If I can calculate the digest of tarball and compare it with V2 digest, things become mush faster.

**Comment by dmp42** [comment]
@oilbeater right.

@dmcgowan or @RichardScothern can probably answer you about that.

I assume we just do sha256(tarball_binary_stream)

**Comment by dmcgowan** [comment]
@oilbeater taking the sha256 of the tar stream is how the blob sum is calculated. Keep in mind though the sum may be compressed and recreating the tar and compressing may not produce the same blob sum even though the contents are the same. The tarsum utility was created to do such verifications, however it should only be used as a sanity check and not for security. Using tarsum would requiring pulling down the layers from v2 though.

**Comment by dmp42** [comment]
Considering this closed.
