### ISSUE TITLE
Label inspection & aggregation endpoint 

### ISSUE THREAD

**Issue by shaded-enmity** [docker/distribution#600]
Since we've gained the ability to store arbitrary metadata in the images in the form of labels, I think that it would be nice if we could query the labels without actually downloading neither the image nor the manifest.

```
/v2/library/repo/labels/?api_version&base
```
The endpoint would return aggregate label information from all the tags in the given repository:

```
[
{
     "tag": "latest",
     "digest": "......",
     "labels": {
         "api_version": "v159",
         "base": "centos"
     }
},
{
     "tag": "stable",
     "digest": "......",
     "labels": {
         "api_version": "v134",
         "base": "centos"
}
]
```

With that I can figure out which image I want to pull without downloading anything (disregarding the inherent race condition in `fetch tag list` x `fetch manifest N` ).
For example I can fetch all aggregate `VERSION` labels and figure out if my local image is up to date.

**Comment by stevvooe** [comment]
@shaded-enmity This is outside the scope of the registry API. The registry is a content store. One excellent property of scaling a content store is that it knows very little about its content. Following such a model allows one to shard, break up and encrypt content.

This feature is really a part of a search API, discussed in #206. While it may be part of a future registry, it makes more sense to provide semantic indexing at the places that understand the semantics of the content.

**Comment by shaded-enmity** [comment]
Encrypt ... what is your threat model? Why no disk/fs level encryption?

The current API has 2 shortcomings:

* The endpoint which returns the list of tags doesn't return the image digest

`t_0` = fetch tag list
`t_1` = new tag pushed into remote / old tag removed / common tag overridden
`t_2` = download Nth tag from the tag list

This may result in `:latest` and other alias tags clashes, since while the new image had already been pushed there's still outstanding tag job waiting for completion.

* Inspecting labels is a resource hog

Trying to inspect labels of semi-sized repository of *N* tags downloads a lot of cruft, needs *N+1* requests, and is inconsistent (above).
Here are my numbers for nodejs repository:

```
40 tags checked
1.1 MB of JSON manifests downloaded
1m43.277s runtime (sequential download)
```

The average size of the labels key/values was around 30 bytes per manifest, that's total 1.2KB, that's nearly ~ 1:1000 redundancy ratio. Imagine I need to check version labels of 5 different images, the stress put to both ends of the network during a routine check is very high.

You can check this for yourself:
https://github.com/shaded-enmity/docker-doug/tree/distv2

```
mkdir manifests/ && time doug-cli manifests -o manifests/ node && du -h manifests/
```

I do not see how this is handled by #206 - but yeah, I agree that it makes more sense implementing it as part of the search API, should I repost it there?

**Comment by stevvooe** [comment]
@shaded-enmity I am confused as to what you are trying to achieve. There are several aspects to your commentary that indicate some misunderstanding of how the registry stores and distributes content, as well as the future goals. The first confusion that catches people out is that the registry is a place to store content and not a database of the content. While there are vestiges of this in the V2 API, such as tags, committing to this registry model will pave the way for image distribution schemes that don't involve a registry API.

What you're not considering is that a monolithic architecture simply does not scale well and leads to tight integration. While a set of registries may store terrabytes of data, said data can be indexed on a single host. There is no need to have this functionality built into every registry. It also doesn't make sense to implement the intelligence required to understand that content. An example is that disk and fs level encryption would require the registry to have keys for content it must index and provide access. Currently, the architecture also requires too much trust in the registry. By minimizing the contact the registry has with the content that is distributed, we can distribute encrypted content that the registry has no knowledge of its structure.

The tags API has always had these limitations. Tags are mutable. Even if we returned a digest, which would make the API much less efficient, the actual value of the tag may be out of date. That is a property of such an API. We are working to provide trusted verification of tags but, if you need a higher level of guarantee, using digests will ensure that the manifest does not change between fetches.

Indeed, if you walk the content such a manner, indexing is inefficient. Backend access, notifications and other approaches can mitigate this. One can build a notification listener that receives updates to the manifests and indexes labels only when updated. These could also be pushed separately to an indexing service by a client.

The other aspect I am confused about is why you insist on using labels for versioning when the entire rest of the community uses tags. It sounds like by avoiding this, you're creating a lot of unnecessary headache.

As I stated before, #206 does indeed cover such a use case. If you believe you can provide constructive feedback, I look forward to your contribution.

**Comment by ncdc** [comment]
@shaded-enmity could you perhaps describe the ultimate goal of your feature request? Instead of thinking in terms of registry API, labels, and so on, what exactly are we trying to achieve? I think if we start there, we can work together with @stevvooe's team to come to an agreeable solution.

**Comment by ncdc** [comment]
I believe this is the problem statement:

As an image consumer, I want to be able to determine if any of the Docker images on my system based on some other Docker image X are out of date.

@shaded-enmity @rhatdan please confirm

**Comment by rhatdan** [comment]
Yes.

**Comment by ncdc** [comment]
Consider the following use case:

1. I have an image on my system called `andy/myapp`
    1. I got this image via `docker pull andy/myapp:latest`
    1. It is based on an older version of a RHEL 7 image
2. I have never `docker pull`ed the RHEL 7 image; I've only ever pulled my `andy/myapp`

The goal is to be able to somehow look at `andy/myapp` and determine that the RHEL image layer it's based on is now out of date.

It would be difficult to use only tags to identify the out of date RHEL layer. If I've only ever pulled `andy/myapp`, then the output of `docker images` won't ever show an image tagged `rhel7:1.2`. That's why we're looking at using labels, as an image inherits all of the labels from all of its layers.

@stevvooe

**Comment by stevvooe** [comment]
In the current API, the solution for this is to issue a HEAD request to the tagged image (ie `/v2/<name>/manifests/<tag>`). If the digest differs from what you have locally, it has been updated. A similar approach could be manufactured with the notification system. Such an approach could examine each update and decide if the tag or version is updated.

**Comment by ncdc** [comment]
@stevvooe that doesn't work in the scenario above where all you have is `andy/myapp` locally - you don't have `rhel7` pulled by either tag or digest.

**Comment by stevvooe** [comment]
@ncdc This use case is slightly specialized and I am not sure if it should be covered by the registry API, unless it was part of search. Perhaps, keeping an index of base images (ie rhel7:1.2, etc.) that can be looked up by digest would suffice. If one is out of date, the index could provide the "current version".

**Comment by ncdc** [comment]
@stevvooe perhaps not. I wonder if we could do something like this:

1. Determine the image's "base" (rhel7.1 or whatnot)
1. Check for a tag such as 1-latest in the rhel7 repo (i.e. to get the latest image for the rhel7.1 stream)
1. Pull the manifest associated with that tag
1. Compare the appropriate labels in `andy/myapp` against the labels from the manifest we just retrieved
1. If they differ, it means `andy/myapp` is out of date

@rhatdan @shaded-enmity what do you think about this - would it work?

**Comment by shaded-enmity** [comment]
@ncdc That would work except that with this approach you'd need to add alias tag for each image that was invalidated (the -latest suffix), which effectively doubles the amount of tags and puts additional burden on image maintainers.
Another thing is that even though '1-latest' has digest *X*, '1.1-2' now has digest *Y*, but both refer to the same thing, which should be taken care of in V2.1, but anyway it might cause confusion.

@stevvooe The list of base images would need to be up-to date too, besides that there's the question of what images should be on the list, as this would introduce discriminatory split between *image types*. Notifications work only when you're listening, and are generally fire & forget in nature; what we're looking for is on-demand solution.

**Comment by ncdc** [comment]
@shaded-enmity I'm not sure how this would double the amount of tags. It would add 1 tag per minor version:

1-latest for rhel7.1
2-latest for rhel7.2
etc

What I'm suggesting is you check the labels for the image in question (`andy/myapp`), find the value of the RHEL base image, which would be something like 1.1-2. You'd then get the image manifest for the tag `1-latest` from the rhel7 repo, check the label to see if it is newer than 1.1-2. If so, it's out of date.

**Comment by shaded-enmity** [comment]
@ncdc How about *Z* and *R*, as in X.Y.Z-R? This would work if we only cared about a single component in the version string. 

The information flow I really want to achieve is that neither the image creator, aside from properly versioning their builds, nor the image consumers need to do anything special in order to make the update tool function properly - anything "in-between" can cause friction and bad UX. 

Like with any versioned content, you ordinarily *install* the content once, but *update* it many times, as such, I believe that content creators should be more concerned about taking care of the content itself than how they'll deliver it.

**Comment by ncdc** [comment]
@shaded-enmity when you have RHEL installed, you're either going to get updates for the latest X (e.g. you're on the 7Server channel), or you lock to the latest Y (e.g. you want to stay on 7.1 and not move to 7.2 when it's out). I don't foresee needing to do anything else (locking on Z or R), and my proposal above supports this.

> I believe that content creators should be more concerned about taking care of the content itself than how they'll deliver it.

Sure, but a content creator still has to know "I need to set label xyz to 1.2.3". It doesn't seem like a burden to also know "I need to push 1-latest".

Having said that, however, I think the longer term better solution is to help work on the search/catalog spec #206 and help drive that forward.

@smarterclayton any thoughts?

**Comment by stevvooe** [comment]
@ncdc Catalog proposal is here: #583.
