### ISSUE TITLE
Remove or make-optional ModTime for registry/storage/driver FileInfo

### ISSUE THREAD

**Issue by wking** [docker/distribution#603]
This doesn't seem to be used outside some storage-driver tests:

    $ git grep ModTime
    Godeps/_workspace/src/github.com/codegangsta/cli/app.go:	return info.ModTime()
    Godeps/_workspace/src/github.com/docker/docker/pkg/tarsum/versioning.go:		{"mtime", strconv.Itoa(int(h.ModTime.UTC().Unix()))},
    Godeps/_workspace/src/github.com/noahdesu/go-ceph/rados/ioctx.go:	ModTime     time.Time
    Godeps/_workspace/src/github.com/noahdesu/go-ceph/rados/ioctx.go:			ModTime: time.Unix(int64(c_pmtime), 0),
    Godeps/_workspace/src/github.com/noahdesu/go-ceph/rados/rados_test.go:	assert.NotNil(t, stat.ModTime)
    registry/storage/driver/azure/azure.go:			ModTime: mtim,
    registry/storage/driver/fileinfo.go:	// ModTime returns the modification time for the file. For backends that
    registry/storage/driver/fileinfo.go:	ModTime() time.Time
    registry/storage/driver/fileinfo.go:	// ModTime returns the modification time for the file. For backends that
    registry/storage/driver/fileinfo.go:	ModTime time.Time
    registry/storage/driver/fileinfo.go:// ModTime returns the modification time for the file. For backends that
    registry/storage/driver/fileinfo.go:func (fi FileInfoInternal) ModTime() time.Time {
    registry/storage/driver/fileinfo.go:	return fi.FileInfoFields.ModTime
    registry/storage/driver/filesystem/driver.go:// ModTime returns the modification time for the file. For backends that
    registry/storage/driver/filesystem/driver.go:func (fi fileInfo) ModTime() time.Time {
    registry/storage/driver/filesystem/driver.go:	return fi.FileInfo.ModTime()
    registry/storage/driver/inmemory/driver.go:		ModTime: found.modtime(),
    registry/storage/driver/rados/rados.go:			ModTime: stat.ModTime,
    registry/storage/driver/s3/s3.go:			fi.ModTime = timestamp
    registry/storage/driver/testsuites/testsuites.go:	createdTime := fi.ModTime()
    registry/storage/driver/testsuites/testsuites.go:	modTime := fi.ModTime()
    registry/storage/driver/testsuites/testsuites.go:	// Call on directory (do not check ModTime as dirs don't need to support it)
    testutil/tarfile.go:		ModTime:    time.Now(),

The ModTime requirement landed with ac660e72 (Replace StorageLayer.CurrentSize interface call with Stat, 2014-12-02, #1), but I don't see an actual use for this metadata.  IPFS doesn't currently have a place to store creation or modification times.  We could add that information to IPFS (and at some point we probably will), but if the registry isn't using the information it seems better to make the storage-driver API more flexible and either drop the requirement or make it optional (via `ErrUnsupportedMethod`).

**Comment by stevvooe** [comment]
@wking We've relaxed the use of `ModTime` throughout the storage package. What are you trying to achieve here? This issue isn't really actionable. Please submit a proposal or PR.

**Comment by wking** [comment]
On Mon, Jun 08, 2015 at 01:46:21PM -0700, Stephen Day wrote:
> @wking We've relaxed the use of `ModTime` throughout the storage
> package. What are you trying to achieve here?

I'm trying to avoid implementing a ModTime endpoint in the IPFS
storage driver or using a stub that returns time.Now().

> This issue isn't really actionable. Please submit a proposal or PR.

If removal seems reasonable, then the patch will be:

  diff --git a/registry/storage/driver/fileinfo.go b/registry/storage/driver/fileinfo.go
  index e506402..7855b9d 100644
  --- a/registry/storage/driver/fileinfo.go
  +++ b/registry/storage/driver/fileinfo.go
  @@ -13,10 +13,6 @@ type FileInfo interface {
          // meaningless if IsDir returns true.
          Size() int64
   
  -       // ModTime returns the modification time for the file. For backends that
  -       // don't have a modification time, the creation time should be returned.
  -       ModTime() time.Time
  -
          // IsDir returns true if the path is a directory.
          IsDir() bool
   }
  @@ -37,10 +33,6 @@ type FileInfoFields struct {
          // meaningless if IsDir is set to true.
          Size int64
   
  -       // ModTime returns the modification time for the file. For backends that
  -       // don't have a modification time, the creation time should be returned.
  -       ModTime time.Time
  -
          // IsDir returns true if the path is a directory.
          IsDir bool
   }
  @@ -67,12 +59,6 @@ func (fi FileInfoInternal) Size() int64 {
          return fi.FileInfoFields.Size
   }
   
  -// ModTime returns the modification time for the file. For backends that
  -// don't have a modification time, the creation time should be returned.
  -func (fi FileInfoInternal) ModTime() time.Time {
  -       return fi.FileInfoFields.ModTime
  -}
  -
   // IsDir returns true if the path is a directory.
   func (fi FileInfoInternal) IsDir() bool {
          return fi.FileInfoFields.IsDir

plus the associated removals from the existing driver implementations
and the test suite.  But that's a bunch of work to do before getting
approval on the general idea, so I thought I'd open an issue to
discuss before wading into the implementation.

Alteratively, we could close this issue with a PR that makes that
method optional, or with a PR that documents why the method is
required.

**Comment by stevvooe** [comment]
@wking Implement the protocol and see what happens first. It may make more sense to simply use `time.Time{}` (zero-valued) rather than delete support.

**Comment by wking** [comment]
On Mon, Jun 08, 2015 at 07:22:24PM -0700, Stephen Day wrote:
> @wking Implement the protocol and see what happens first. It may
> make more sense to simply use `time.Time{}` (zero-valued) rather
> than delete support.

Ah, that's better than time.Now().  I still think that if the registry
runs fine with an implementation like this that we'll be better off if
we just cull the method, but if you want to keep it around it's your
maintenance burden ;).
