### ISSUE TITLE
Remove or make-optional Path for registry/storage/driver FileInfo

### ISSUE THREAD

**Issue by wking** [docker/distribution#604]
Why would you do this:

    fileInfo, err := storageDriver.Stat(ctx, path)
    …
    thatPathWePassedInEarlier = fileInfo.Path()

?  Grepping through the source for `Path()`, the only non-test hit looks like it's in `registry/storage/purgeuploads.go` to get the path back during a `Walk`.  I think we should either extend `WalkFn` to pass the path explicitly, or alter `getOutstandingUploads` to avoid consuming that path.  I'm not entirely clear on the current `getOutstandingUploads` implementation, but it seems like we can find a way to accomlsh resumable uploads without requiring a `Path()` function in the storage-driver's `FileInfo` API.

**Comment by stevvooe** [comment]
Why does this even matter? Do the files in storage driver not have a path? What are you trying to achieve?

**Comment by wking** [comment]
On Mon, Jun 08, 2015 at 01:47:24PM -0700, Stephen Day wrote:
> Why does this even matter? Do the files in storage driver not have a
> path? What are you trying to achieve?

I have access to the file size at Stat() time when I lookup path →
IPFS-hash to check for existence.  I'd like to record the size and
directory-ness in my internal fileInfo type there, and I see no use in
also recording the original path.  Obviously, recording the original
path isn't hard to do, but it makes me jumpy.  What if future changes
to the storage data remove that path?  What if they replace it with
different content?  What if they Move(…) the content?  Should future
calls to, for example, FileInfo.Path() return the path to that
resource at Stat() time or at Path() time?  If we drop FileInfo.Path()
it's a lot easier to be confident that the calling code is only
interested in Stat()-time values.  And it's one less attribute I have
to track in my internal fileInfo type.

**Comment by stevvooe** [comment]
@wking The stat data returned is only accurate at the time the file was statted. This is the case for every stat call made since the beginning of unix. In the case of storage drivers, the stat is associated with a path, rather than an inode, so it is even easier to use. If the content moves, it won't be available at that path. The only thing that may change is the size. For the most part, we only use this for immutable content, so not even that matters.

It may not make sense to directly map the fileinfo to the internal node structure in your implementation. It sounds like an unnecessary constraint has been added making the implementation harder. Basically, just record the path at the time of the stat call.

**Comment by wking** [comment]
On Mon, Jun 08, 2015 at 07:16:09PM -0700, Stephen Day wrote:
> The stat data returned is only accurate at the time the file was
> statted.

Ah, good.

> If the content moves, it won't be available at that path. The only
> thing that may change is the size.

Right, so what's the point of preserving the (possibly stale) path?
Maybe there's new content at that path that's also consuming whatever
path-specific information this is used for.

> For the most part, we only use this for immutable content, so not
> even that matters.

Yeah, this helps.  But content-addressability isn't part of the
storage-driver API, so it's hard to enforce strict requirements along
these lines.

> It may not make sense to directly map the fileinfo to the internal
> node structure in your implementation. It sounds like an unnecessary
> constraint has been added making the implementation harder.

All of the existing drivers store the Stat()-time information in a
FileInfo type at Stat-time (e.g. [1,2,3,4]).  Storing the path is just
one more tedious bit to track and test (e.g. [5,6,7,8]), for no
apparent gain (as far as I can tell).

> Basically, just record the path at the time of the stat call.

That's what I'll do.  This issue was just me saying that I don't think
we actually need to bother with the Path() bit in the future, which
makes life a bit easier for folks implementing future drivers, and
keeps the registry core from making unreliable assumptions about the
current path for a particular resource.

[1]: https://github.com/docker/distribution/blob/v2.0.1/registry/storage/driver/inmemory/driver.go#L181-L189
[2]: https://github.com/docker/distribution/blob/v2.0.1/registry/storage/driver/filesystem/driver.go#L179
[3]: https://github.com/docker/distribution/blob/v2.0.1/registry/storage/driver/s3/s3.go#L651-L665
[4]: https://github.com/docker/distribution/blob/v2.0.1/registry/storage/driver/azure/azure.go#L186-L188
[5]: https://github.com/docker/distribution/blob/v2.0.1/registry/storage/driver/inmemory/driver.go#L182
[6]: https://github.com/docker/distribution/blob/v2.0.1/registry/storage/driver/filesystem/driver.go#L178
[7]: https://github.com/docker/distribution/blob/v2.0.1/registry/storage/driver/s3/s3.go#L647-L649
[8]: https://github.com/docker/distribution/blob/v2.0.1/registry/storage/driver/azure/azure.go#L185

**Comment by dmp42** [comment]
Closing this as it seems answered.
