### ISSUE TITLE
Feature Request: Add latest tag to basic search

### ISSUE THREAD

**Issue by TeckniX** [docker/distribution#606]
It would be nice to have the most recent tag shown within the search results.
This would prevent a secondary query for each result to show the tag that could be used for an image.

**Comment by stevvooe** [comment]
We don't have a search API in the distribution repository. For search related discussion in relation to V2 api, please see #206.

This can be much more easily obtained by using the notification API, which will notify on new tag or manifest pushes.

**Comment by TeckniX** [comment]
Thanks for the quick reply, indeed this is the V2 api. Notification API means I already had the image bookmarked or created, I'm talking on initial search. 
I'll read up on #206 mentioned above
