### ISSUE TITLE
Potential eventual consistency race condition on layer upload

### ISSUE THREAD

**Issue by BrianBland** [docker/distribution#61]
When using an eventually-consistent storage backend (S3), it is possible to receive a 500 error when uploading a layer. The error that the registry returned to the http client was as follows, which happened after uploading the entire contents of the layer:

`UNKNOWN: [Path not found: /docker/registry/v2/repositories/test/mysql/uploads/9114e61d-093e-4d3e-aedd-f64c8850db8b/data]`

This indicates that this was a read-after-write consistency issue when trying to verify the spooled upload data before moving it to its final location on the backend storage. Even if we were to have pre-computed the checksum, this would fail to move for the same reason with this timing condition.

We should determine the proper semantics for handling this sort of case, as is happens rarely on S3, but often enough for me to have reproduced it several times in the last few days.

**Comment by stevvooe** [comment]
@BrianBland Thank you for characterizing this issue. We'll have to let the registry bake a bit in staging to understand the failure scenarios. We also need to identify at which layer in the stack to handle these kinds of inconsistencies. Can we create a `StorageDriver` that wraps others and makes them consistent?

It seems there is at least one superficial bug: this should return an unknown upload error, rather than a 500.

**Comment by stevvooe** [comment]
@BrianBland Could this have been resolved by #121? This race condition is possible but it is more likely you were trying to upload an empty layer. If you don't agree, we can leave this ticket open to keep an eye on this.

**Comment by BrianBland** [comment]
I really can't answer that with certainty, but I can tell you that I haven't encountered the recorded issue recently...
How about we close this if it doesn't crop up in the next couple of days.

**Comment by stevvooe** [comment]
@BrianBland Agreed. SGTM!

**Comment by endophage** [comment]
If this can't be closed already: not sure of goamz does it but in the past I've had to use backing off retries with S3. Boto does I think 5 retries by default...

**Comment by stevvooe** [comment]
@BrianBland Have we seen this since? I'm thinking we should close this bug.

**Comment by BrianBland** [comment]
Nope, I think we're fine here.
