### ISSUE TITLE
Get image ID with tag name

### ISSUE THREAD

**Issue by amancevice** [docker/distribution#628]
the `/v1/` registry response `/repositories/<repo>/tags` used to list the image ID along with the tag handle. `/v2/` only seems to give the handle. It would be useful to get the ID to compare to the ID found locally. The only place I can find the ID is in the v1Compat section of the manifest (which is overkill for the info I want)

**Comment by stevvooe** [comment]
@amancevice This property of the V1 API was very computationally expensive for the way images are stored on the backend. Only the tag names are enumerated to avoid a secondary lookup. In addition, the V2 API does not deal in Image IDs. Rather, it uses digests to identify layers, which can be calculated as property of the layer and are independently verifiable.

**Comment by kevinsimper** [comment]
@stevvooe What is the proper way to compare two docker images?

**Comment by RichardScothern** [comment]
@kevinsimper : please don't comment on closed issues.  If you have a question can you open a new issue and state your use case for comparing docker images?
