### ISSUE TITLE
Question: Is there a health check URL for Registry V2

### ISSUE THREAD

**Issue by diptanu** [docker/distribution#629]
The V1 Registry had /_ping for the purposes of health check. Is there something similar available in V2? This is needed for putting the servers behind ELBs etc.

**Comment by dmp42** [comment]
@diptanu go with the health check endpoints: https://github.com/docker/distribution/blob/master/docs/configuration.md#debug

**Comment by stevvooe** [comment]
@diptanu The standard "/v2/" endpoint should be sufficient. This requires authentication. If they respond with 401 or 200, you can safely assume the registry is up.

There is also the "/debug/health" endpoint. This is meant to be an internal health check endpoint running on a separate port and application. Note that there may some more work before this becomes a full recommended approach. It is not necessarily recommended to make this available over any unsecured network.

**Comment by dmp42** [comment]
@diptanu closing this for book keeping. Let us know if you need more here.

**Comment by yeungda-rea** [comment]
It would be great if there was an easy way to put a docker registry behind an AWS Elastic Load Balancer, when authentication is enabled.

The AWS ELB HTTP health check[1] is quite limited. It is only successful when a response code of 200 OK is returned. It does not support authentication for health check HTTP GET requests.

When authentication is enabled in the docker registry, there aren't any endpoints that respond with 200 OK from an anonymous HTTP GET. We then need to fall back to a proxy that does authentication, that can expose an anonymous endpoint for health, or a lower layer health check such as the ELB TCP health check.

We had a look at the debug server, but from looking at the source, it doesn't seem to give much confidence the registry itself is working.

It would be very helpful if there was an endpoint that gave a strong indication of health, that could be accessible from an anonymous HTTP/HTTPS GET, that would be available even when authentication is enabled.

[1] http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_HealthCheck.html

**Comment by stevvooe** [comment]
> We had a look at the debug server, but from looking at the source, it doesn't seem to give much confidence the registry itself is working.

Several items can be accessed, such as expvar, pprof and the health endpoint. The output of expvar is a great indication of registry health. Right now, unfortunately, `/debug/health` is not attached to much, so it only indicates whether or not the service is up. We don't recommend exposing this a load balancer, but it can be used as such.

Serving the debug endpoints to a load balancer presents a security risk and exposing an unauthenticated endpoint under registry APIs is a non-option (perhaps, we may consider a `/health` endpoint but the necessity is dubious). The right solution is to have the health checks gate the entire service and return a 503 on failure. Unfortunately, the AWS ELB design makes a very poor assumption in assuming that `200 OK` is the only indication of health. For a registry with authentication, a `401 Unauthorized` return code on an unauthenticated response is very healthy.

**Comment by yeungda-rea** [comment]
Thank you@stevvooe for PR #874. This will suit our load balancing needs nicely.

**Comment by otto-dev** [comment]
`401 Unauthorized` doesn't integrate well with tooling such as Hashicorp Consul which will interpret 401 as down. I also don't want to bake credentials into the health check definition, as it goes against the principle of least privilege.
