### ISSUE TITLE
Proposal: Cross repository push

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#634]
# Proposal: Support cross repository push

A common pattern for container creators today involves pulling images from a registry, renaming or re-tagging the image, possibly adding layers, then pushing the content back up to the same registry. From the engine perspective, this looks like `docker pull registry.example.com/imagea`, `docker tag registry.example.com/imagea registry.example.com/imageb` or `docker build -t registry.example.com/imagea .` (with `FROM registry.example.com/imageb` in the Dockerfile), then `docker push registry.example.com/imageb`.  Currently this common pattern involves pushing all content to the new repository, regardless of whether the registry already knows about the content address of the layers. There are both design considerations about security that enforce this behavior, and legacy design in the daemon that makes this difficult to change.

### Push performance expectations
Users have an expectation that when a layer is pulled from a registry, the content should not need to be sent back to the same registry if the original identifier is known. This leads to continuous integration work flows being built up around this expectation, and any addition content push can greatly slow down the ci pipeline.

### Layer security
In order to pull a layer by digest from a repository, content with the corresponding digest needs to be pushed to that repository. This prevents pulling content from one repository that was pushed to another and not intended to be shared. While some content is inherently private and others intended for wide public distribution, the registry is designed to treat all content as private and leave access control to individual repositories to an authentication server.  

### Engine design
The current Docker engine is designed to store layer content by a randomly generated identifier, rather than by a digest. In addition to storing by this random identifier, the data is stored unpacked, often preventing the original digest from being able to be derived from the content. This leads to a different digest being calculated every time layer is pushed to a registry. This makes it impossible for the registry to de-duplicate the content, as the content is different. Without referring to a known digest for a layer, an engine has no choice but to push content to the registry and use whatever digest is calculated for that push.

## Solution Proposal
While the engine design can be addressed over time, the security of the registry cannot be compromised. In ideal solution would both maintain the security and integrity of the registry, while at the same time allowing for the ideal push performance. Adding the ability to mount a blob from one repository to another, providing the necessary read ACL from the origin repository and write ACL to the destination repository would allow the registry to perform a shallow copy, only creating a reference to an existing blob. This will involve an addition to the upload API and require client side changes to make use of it.

#### Initiate Blob Upload
```
POST /v2/<name>/blobs/uploads/?mount=<digest>&from=<repo>
Host: <registry host>
Authorization: <scheme> <token>
Content-Length: 0
```

|Name|Kind|Description|
|----|----|-----------|
|`Host`|header|Standard HTTP Host Header. Should be set to the registry host.|
|`Authorization`|header|An RFC7235 compliant authorization header. The given token should have both pull access to the `from` repository, and push access to the `name` repository|
|`Content-Length`|header|The `Content-Length` header must be zero and the body must be empty.|
|`name`|path|Name of the target repository.|
|`from`|query|Name of the source repository.|
|`mount`|query|Blob reference to mount from source to target.|

Addresses https://github.com/docker/docker/issues/13883

**Comment by stevvooe** [comment]
I think this looks good. Let's make sure we cover these issues:

1. Does upload proceed if the _permissions_ fail or does the upload get created? If we are not careful, we have a dangerous situation where the request may have different levels of permissions without changing the URL.
2. By requesting a blob be mounted into the repository from another, are we operating on the right resource?

Alternatively, we may want `PUT /v2/<name>/blobs/<digest>?from=<source repo>`, since we are mounting to a blob from another repository. In the past, we've had problems overriding URLs. Sending an extra request shouldn't be a problem, especially when it has a very high likelihood to proceed.

**Comment by RichardScothern** [comment]
Is it possible for the daemon to maintain a mapping of layer digest to the random digest ID, and if it can ensure there is no change to layer locally before it is re-pushed, issue a HEAD or (better still) a conditional PUT?

If the daemon is pulling layers from the Registry, it will have the correct digests to fulfill the security requirement.

This is more work for the daemon, and it could lose this state if it's not persisted but adding a new endpoint to the registry is not insignificant either.

**Comment by ncdc** [comment]
@stevvooe 
> In the past, we've had problems overriding URLs

I think it's probably best to avoid overriding URLs. I like creating a new route for this.

> Does upload proceed if the permissions fail or does the upload get created?

If the permissions fail, the client would be required to push the layer, wouldn't it?

@RichardScothern 
> Is it possible for the daemon to maintain a mapping of layer digest to the random digest ID, and if it can ensure there is no change to layer locally before it is re-pushed, issue a HEAD or (better still) a conditional PUT?

A HEAD request isn't sufficient, is it, as that would check for the existence of the layer in the destination repo, which would return 404 in this scenario. I think you have to have a new route in the registry to be able to say "link repo1/blob1 into repo2; here are credentials that give me access to both repos"... right?

> This is more work for the daemon, and it could lose this state if it's not persisted

With this proposal, the state must be persisted. If it's lost, that just results in having to push the layer, which is where we are today.

**Comment by ncdc** [comment]
What about the following scenario:

1. docker pull openshift/ruby-20-centos7
2. build new image based on openshift/ruby-20-centos7
3. tag as registry.openshift.foo/andy/myapp
4. push
5. repeat hundreds of times, varying the project (andy) and/or repo name (myapp)

registry.openshift.foo may already have the layers from openshift/ruby-20-centos7, but the base image was pulled from 1 registry (the Hub in this example) and pushed to another (registry.openshift.foo). Is there any way you can think of to eliminate having to push all the layers to each new repo, other than possibly changing to scenario to this:

1. docker pull openshift/ruby-20-centos7
2. docker tag openshift/ruby-20-centos7 registry.openshift.foo/common/ruby-20-centos7
3. push
4. build new image based on registry.openshift.foo/common/ruby-20-centos7
5. tag as registry.openshift.foo/andy/myapp
6. push
7. repeat hundreds of times, varying the project (andy) and/or repo name (myapp)

@dmcgowan @stevvooe

**Comment by dmcgowan** [comment]
@ncdc I think this could be done client side by keeping track of all the registries a layer has been pushed to, and when attempting to push a layer, if it already exists in the same registry to attempt to "mount" it. I don't see how this would require a protocol change unless we wanted to expose raw mounting of a digest, but we have no way around the ACL model in that scenario. If the client is smart enough, retagging, pushing, then building shouldn't be necessary.

**Comment by dmcgowan** [comment]
@ncdc 
> If the permissions fail, the client would be required to push the layer, wouldn't it?

Yes

@RichardScothern 
>Is it possible for the daemon to maintain a mapping of layer digest to the random digest ID, and if it can ensure there is no change to layer locally before it is re-pushed, issue a HEAD or (better still) a conditional PUT?

Yes the daemon should keep this mapping. Today it only keeps one digest and it is possible that it will get overwritten. However it should store any digest that has ever been calculated for the random ID and likely the repository name which used that digest. In that case when pushing a layer, the daemon will be able to determine what repositories reference the layer and with what digest.

**Comment by stevvooe** [comment]
@ncdc I may be missing your point, but this proposal only covers cross-repository push. Cross-registry push, while an important consideration, is outside the scope.

Varying levels of optimization are possible. It will rely on the docker daemon to make the right decisions. A naive implementation would hit your scenario.

Do you see any problems with this proposal (or similar) as an API primitive? What changes do you suggest we make?

**Comment by ncdc** [comment]
@stevvooe no, you're correct, I'm pointing out another potential performance pain point, but it's separate from cross-repo push.

I'm happy with this proposal, as it allows the client to prove it has access to a blob w/o having to upload the entire blob itself. I think `PUT /v2/<name>/blobs/<digest>?from=<source repo>` looks like a good way to go.

**Comment by stevvooe** [comment]
@ncdc I register this as a "+1" from your side.

Perhaps, we need to provide some solid requirements to the implementation to make sure this stuff is covered.

**Comment by ncdc** [comment]
@stevvooe sgtm. Let's try to talk tomorrow?

**Comment by mattmoor** [comment]
@dmcgowan Can "<source repo>" be fully qualified (in the non-DockerHub case)?

e.g. gcr.io/foo/bar  vs. foo/bar?


@stevvooe @ncdc In addition, I think that there is a case to be made for a registry Nack'ing this when a source repo is on an unsupported registry.

e.g. while `gcr.io <--> DockerHub` is a lot of work to make fast, `us.gcr.io <--> eu.gcr.io` is not, and is a use case we definitely want to support efficiently.


So can we make the implementation always do this and have the registry fail the request and fallback on upload when unsupported?

**Comment by ncdc** [comment]
@mattmoor this particular proposal is only about cross repo mounting with a single registry. My assumption is that if you pull gcr.io/foo/bar and then try to push it to docker.io/foo/other, because these are 2 distinct registries, the daemon won't even attempt to invoke the cross repo mount api (unless a given layer was *also* previously also pulled from somewhere in docker.io).

And afaik the plan is for this just to be an optimization, and if it's unavailable, a full upload would take place.

**Comment by mattmoor** [comment]
@ncdc This makes sense cross-registry in two circumstances:
  1. The two registries share a credential space, and can optimize the cross-registry copy
  1. The source repo is public on its registry

I'm obviously more interested in the former, but the latter is doable and odds are that: `registry A <--> registry B` gets lower latency than `registry A <--> my laptop in starbucks <--> registry B`.  I also suspect the latter opens up the possibility for a clever registry to implement a cross-registry reverse index.

I don't think the latter should be a requirement (thus Nack'ing), but this simple tweak opens up a number of possibilities IMO.

**Comment by ncdc** [comment]
@mattmoor I wasn't saying that cross-registry doesn't make sense. It does. I want it. :smile: I'm just pointing out that this proposal is strictly about cross-repository within a single registry. (see https://github.com/docker/distribution/issues/634#issuecomment-115862868)

**Comment by mattmoor** [comment]
@ncdc I get what you are saying (and saw your comment), and Registry vs. Registry provider is a subtle distinction that I think should be in scope ;-)

**Comment by ncdc** [comment]
@mattmoor what do you mean by registry vs registry provider?

**Comment by dmcgowan** [comment]
@mattmoor this proposal does not prescribe whether the source repo is a fully qualified name or not. The registry is intended to handle repositories as both fully qualified and hostname truncated. Currently the limitation on the Docker client which does not send fully qualified repositories, I am trying to address this with the namespace proposal. Given a registry and client that supports fully qualified names, a registry implementation is certainly allowed transfer (not described here) instead of link (what is proposed here). The reason transfer is not described here is that this is intended to be an instantaneous action rather than starting a long running operation. The management of a long running operation is out of scope of this proposal. However I am willing to have that discussion, originally it was in scope, but I think you would have to agree the added complexity warrants separating out the specification.

**Comment by mattmoor** [comment]
Sorry for not being clearer, we're probably the only folks who offer a distinction with us.gcr.io vs. eu.gcr.io vs. asia.gcr.io

Frankly, Docker cannot distinguish between registries provided by the same provider and those provided by distinct providers.

We can implement us.gcr.io <=> eu.gcr.io <=> asia.gcr.io at rates that are basically impossible to beat with an intermediary.

So given the option to NACK a mount thereby forcing the upload (which must be supported for back-compat anyways), why not leave this door open?

**Comment by mattmoor** [comment]
@dmcgowan Sorry, you response materialized as I hit reply.

> this proposal does not prescribe whether the source repo is a fully qualified name or not.

Presumably this will evolve into an alteration of the specification, and the specification should certainly pick one.

> The reason transfer is not described here is that this is intended to be an instantaneous action rather than starting a long running operation

So long as the registry can perform the operation faster than the user could PUT the bits, I'm not sure I appreciate the need for this to be "instantaneous".  I feel as though you are letting implementation bleed through into the API spec.

> However I am willing to have that discussion, originally it was in scope, but I think you would have to agree the added complexity warrants separating out the specification.

I think what I'm asking for is a simplification.  Always fully-qualify source repo, and always attempt the mount.  As my previous post mentions, you need fallback anyways, so this isn't a simplification from a specification standpoint; I'd argue you are making things more complex.

That said, I'm absolutely 100% in agreement that limiting the scope of ACK'd vs. NACK'd mount requests to your target subset is a great first-step for the docker/distribution implementation of mount.

**Comment by ncdc** [comment]
@mattmoor are you saying you want a config flag to enable/disable mounting? Maybe I'm misunderstanding something... the plan is to have the daemon always attempt to cross-repo mount. If the registry doesn't support it, I would think any non-success response would result in the daemon falling back to a full upload.

**Comment by mattmoor** [comment]
@ncdc You are saying it will always do it *within a registry*, I'm saying that `source repo` should be fully-qualified and it should **ALWAYS** do it.

**Comment by ncdc** [comment]
@mattmoor ok, so you're saying that if I do this:

1. `docker pull us.gcr.io/foo/bar`
2. `docker tag us.gcr.io/foo/bar eu.gcr.io/some/repo`
3. `docker push eu.gcr.io/some/repo`

that in step 3, you want the daemon to issue `PUT /v2/some/repo/blobs/<digest>?from=us.gcr.io/foo/bar`?

I don't see any harm in that, as it would enable registries that are capable of performing that cross-registry mount to achieve better efficiency, and it would fallback to a full upload otherwise. Did I understand the scenario correctly?

**Comment by mattmoor** [comment]
@ncdc Exactly, sorry for poorly articulating.

The other half of this is that we support NACKing mount requests, so registries can implement whatever subset of requests they can do more efficiently than a PUT.

**Comment by dmcgowan** [comment]
Some notes from our discussion in the working group
 - "from" may have multiple sources, since it would be easier for the registry to decide which source is best, the client should be able to send up "from" as a list
 - Always providing "from" as a fully qualified name provides the best forward compatibility with the source name. Since the registry itself makes not determination on whether its stored repositories are fully qualified, the registry would need to be able to determine if a fully qualified repo name refers to a local image.
 - The "POST" request as described in the original proposal should be used instead of "PUT" or a new endpoint. The endpoint must return a different status code if the mount was successful. The client would then need to know how to proceed in the case of a successful mount.
 - The cross registry implementation will be different, but will also use the same "POST" endpoint. This specification and implementation should be designed in such a way to make that addition possible.

**Comment by stevvooe** [comment]
@mattmoor @ncdc The benefits of _cross-registry pull_ are immense but let's keep the conversation scoped to this particular proposal. The goal of this proposal is to prevent having to push data when a user has access to both repositories. If we solve other problems, that is fine, but we need to solve this problem in a timely manner.

That said, we should position this API proposal as an asynchronous operation (as described by @dmcgowan). This means that a mount operation may be instantaneous or can can allocate a new "upload" whose status can be queried. With the use of the POST request for upload creation, I think we meet this requirement.

**Comment by ncdc** [comment]
@stevvooe no objections. It would be nice if this API modification could provide the groundwork for cross-registry mounting (i.e. allow the source repo parameter to be fully qualified including the namespace), but it's probably not a strict requirement.

**Comment by mattmoor** [comment]
Yes, all I'm really looking for is for the source repo to be fully qualified (for DockerHub, nothing changes), which enables us to expand this in the future without ambiguity.

The client doesn't need to send everything out of the gate, and the registry never needs to accept this, but I'd like the spec to allow for future extensions that aren't limited by assumptions made now about the scope of the source repo.

Is that fair?  Happy to discuss more tomorrow.

**Comment by dmp42** [comment]
cc @aaronlehmann

**Comment by stevvooe** [comment]
Per discussion in Distribution Working Group, the proposal is ready to move to the specification phase.

**Comment by alecbenson** [comment]
Specification is being drawn out [here](https://github.com/docker/distribution/issues/908)

**Comment by dmp42** [comment]
@BrianBland @dmcgowan can this be closed?

**Comment by BrianBland** [comment]
Yes, the behavior is merged in both the registry and engine.
