### ISSUE TITLE
Role-based access control

### ISSUE THREAD

**Issue by jcmartins** [docker/distribution#635]
I would like to have a user rules access control to use in my internal network.

**Comment by stevvooe** [comment]
You can set this up with token authentication and a custom service. The token authentication system is designed to make this simple to do without modifying the registry internals. You can read about [token authentication](https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md). This will allow one to implement an whatever role-based access control is required, down to repo+operation granularity.

Check out [cesanta/docker_auth](https://github.com/cesanta/docker_auth) for an example using htpasswd files and user ACLs.

Note that registry 2.1 will release with native basic auth, which might be sufficient. However, no role-based access control is provided. Adding ACL support is realistic with some careful thought and a PR.

**Comment by stevvooe** [comment]
This is already covered by token auth. Closing for now. Let us know if you have questions via IRC or distribution@dockerproject.org.
