### ISSUE TITLE
Error from V2 registry: EOF

### ISSUE THREAD

**Issue by rafabene** [docker/distribution#639]
I have a registry:2.0.1 running on a docker-machine host (provider=virtualbox with port forwarding). 
On a remote host, When I run docker pull `<remote_host>:5000/<my_image>` I got the following output:

```
latest: Pulling from <remote_host>:5000/<my_image>
8ebbde154a62: Pulling fs layer 
c12da83ee7c1: Pulling fs layer 
a16207605ac6: Pulling fs layer 
ea994adb8f5e: Pulling fs layer 
b9a671861279: Pulling fs layer 
a58de78a6a7f: Pulling fs layer 
12724ce38086: Pulling fs layer 
6bafb24bd6c1: Pulling fs layer 
4d217892bcfe: Pulling fs layer 
b741ec2037b8: Pulling fs layer 
983765c3d97c: Pulling fs layer 
96f8e8f069ed: Pulling fs layer 
Pulling repository <remote_host>:5000/<my_image>
FATA[0000] Error: image <my_image> not found.
```

I checked the docker daemon log and found the following error message:

*`level=error msg="Error from V2 registry: Get http://<remote_host>:5000/v2/<my_image>/blobs/sha256:59ea07ffd330c17c154ca58866abd061a2a661cfe56fef997c5525e4d4ff50eb: EOF"`*

This is the output of my docker info:
```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 1
Total Memory: 998.1 MiB
Name: lab
ID: SQBO:NVC7:L2JS:4DQF:JFW3:SDLS:MXZM:UYHL:DD3X:D4ZE:22Q5:XRH2
Debug mode (server): true
Debug mode (client): false
Fds: 266
Goroutines: 422
System Time: Wed Jun 17 05:41:57 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Registry: [https://index.docker.io/v1/]
Labels:
 provider=virtualbox
```

**Comment by RichardScothern** [comment]
@rafabene thanks for reporting this.  We need a bit more information to debug this.

What is your registry storage backend?  S3/filesystem etc
Can you get the logs from the registry around the time the error happened and paste them here.

**Comment by rafabene** [comment]
I'm using filesystem. (default config file from registry:2.0.1).

Since the log (at the time of the error) is huge, I paste it to here: http://pastebin.com/8dCtBUps

**Comment by RichardScothern** [comment]
There is nothing in that log file that helps diagnose the problem.  I cannot see a reference to the digest from your error message, nor any lines relating to error conditions.

When the registry fails on an operation it prints a line with error details (err.code err.detail etc).  Can you look for those and paste them here?

**Comment by stevvooe** [comment]
@rafabene Does this happen every time on the same image?

**Comment by rafabene** [comment]
It happen's every time. and not on the same image. It doesn't happen locally. I can't find any error message in the registry's log but just on docker daemon's log. I was able once or twice to pull a image for the first time and then it started to fail on next images.

I'll try again now and paste the whole logs

**Comment by rafabene** [comment]
I pasted it to gist because it provides separated files information. I hope this helps:
https://gist.github.com/rafabene/969b087f41f7c5081dcb

**Comment by rafabene** [comment]
I tried with registry 0.9.1 and the issue doesn't happen.

**Comment by stevvooe** [comment]
@rafabene Are you sure the image is being pushed to the same registry instance? The daemon 404's on pulling "sha256:fdd04e6fcc43523cb5d1f8f09467d7b30925b7a2c06e86956fe0ba85a9dced6b" causing the pull to fallback to v1. From the registry logs and the daemon logs, this digest was never pushed or pulled.

How are you running the registry? Have you setup persistent storage?

**Comment by rafabene** [comment]
Indeed! That's really odd. I'm really sure the there's just a single registry instance running. My env at this moment is a isolated network with both hosts only (Titanium resolved as classroom.example.com and Colosus). The thing to consider is that I see the [registry log running] (https://gist.github.com/rafabene/969b087f41f7c5081dcb#file-registry-log) when I execute the docker pull from remote host.

I'm running it through the following [docker-compose.yml](https://github.com/javaee-samples/docker-java/blob/07c0bd497560073f37a435e015232302949ec6f9/instructor/docker-compose.yml)

````
registryv2:
  image: registry:2.0.1
  ports:
    - "5000:5000"
  environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    - REGISTRY_LOG_LEVEL=debug
  volumes:
    - /srv/docker/registry:/var/lib/registry
  restart: always
<other docker containers removed>
```

**Comment by stevvooe** [comment]
@rafabene The next step is to start poking around the backend and confirming the existence of the blobs. The path layout, which should be rooted at `/srv/docker/registry` with your configuration, is documented in [registry/storage/paths.go](https://github.com/docker/distribution/blob/master/registry/storage/paths.go). Check the primary blob store and see if you can confirm existence of the suspect digest. If it is there, validate the "data" file with a sha tool (`sha256sum` on most linux systems).

**Comment by rafabene** [comment]
Yeap.

The data file is there and the checksum matches: 
````
sha256sum data 
fdd04e6fcc43523cb5d1f8f09467d7b30925b7a2c06e86956fe0ba85a9dced6b  data
````

The funny part is that I can't see any reference to those blobs when pulling or pushing:
```
..v2/blobs/sha256$ ls
0b/ 46/ 63/ 6b/ 6e/ 8a/ 9f/ a3/ d9/ ef/ fd/
```

**Comment by stevvooe** [comment]
@rafabene V1 image IDs *are not* hashes. We should be seeing some the hashes in the registry storage in the logs.

Can you download `https://<reghost>/v2/mysql/blobs/sha256:fdd04e6fcc43523cb5d1f8f09467d7b30925b7a2c06e86956fe0ba85a9dced6b` directly with curl? (note you may need to disable or provide some authentication)

**Comment by rafabene** [comment]
It worked through direct download.

[rafael@Colosus ~]$ docker pull classroom.example.com:5000/mysql
latest: Pulling from classroom.example.com:5000/mysql

104de4492b99: Pulling fs layer 
065218d54d7d: Pulling fs layer 
9525a21bc96b: Pulling fs layer 
88b078de9380: Pulling fs layer 
857e8088dd20: Pulling fs layer 
02a18be0147e: Pulling fs layer 
02a18be0147e: Download complete 
7c0571f90444: Download complete 
8709a819fa6b: Download complete 
86a40114dce2: Pulling fs layer 
86a40114dce2: Download complete 
d7f9d4cf73af: Download complete 
b2f80b2caf89: Download complete 
3ce454bd8801: Download complete 
569ac853d7f5: Download complete 
d63d4723d715: Download complete 
FATA[0000] Error: image mysql:latest not found          
[rafael@Colosus ~]$ wget http://classroom.example.com:5000/v2/mysql/blobs/sha256:fdd04e6fcc43523cb5d1f8f09467d7b30925b7a2c06e86956fe0ba85a9dced6b
--2015-06-19 19:47:46--  http://classroom.example.com:5000/v2/mysql/blobs/sha256:fdd04e6fcc43523cb5d1f8f09467d7b30925b7a2c06e86956fe0ba85a9dced6b
Resolving classroom.example.com (classroom.example.com)... 192.168.0.11
Connecting to classroom.example.com (classroom.example.com)|192.168.0.11|:5000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 37211143 (35M) [application/x-gzip]
Saving to: 'sha256:fdd04e6fcc43523cb5d1f8f09467d7b30925b7a2c06e86956fe0ba85a9dced6b.2'

sha256:fdd04e6fcc43523cb5d1f8f09467 100%[==================================================================>]  35.49M  3.28MB/s   in 11s    

2015-06-19 19:47:57 (3.24 MB/s) - 'sha256:fdd04e6fcc43523cb5d1f8f09467d7b30925b7a2c06e86956fe0ba85a9dced6b.2' saved [37211143/37211143]

Now I'm updating my env to bootdocker/docker-machine/docker to 1.7 and see what happens.

**Comment by rafabene** [comment]
With Docker 1.7 the error persists but a more detailed error message is presented at docker daemon log:  https://gist.github.com/rafabene/64296e23cfd8ab572587

**Comment by stevvooe** [comment]
@rafabene Ah, now we've got some information. This is a problem we've been hunting down for some time in the daemon. Please file a bug in docker/docker and reference this issue. We will close this one when we find a workaround.

Are you running the registry behind a proxy, such as nginx?

**Comment by rafabene** [comment]
I tried to use nginx but it changed the expected result, so I'm not using nginx any more.

**Comment by stevvooe** [comment]
@rafabene Ok, so we've eliminated the possibility of a proxy timeout. Let's continue troubleshooting on the docker side.

I am going to close this issue. If that doesn't work for you, please let me know.
