### ISSUE TITLE
Question: how to write new blob format?

### ISSUE THREAD

**Issue by mboersma** [docker/distribution#640]
Currently the Deis open source PaaS relies on some clever/evil python hackery to [fabricate an image layer](https://github.com/deis/deis/blob/master/controller/registry/private.py#L57-L64) and upload it to the `/v1/images/{id}/json` old-registry endpoint. But in the [registry API v2](https://docs.docker.com/registry/spec/api/#pushing-an-image), there is no such JSON endpoint for blobs/layers, and their format is unspecified.

How could I take a Docker 1.6.2 image in registry:2.0.1 and programmatically add a final layer with the equivalent of an `ENV` Dockerfile instruction such as:
```Dockerfile
ENV foo=bar up=down
```

Any pointers or advice would be welcome.

**Comment by RichardScothern** [comment]
@mboersma : in the V2 registry images are stored as manifests.  They are documented here:
https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-1.md

Code for interacting with manifests can be found here:
https://github.com/docker/distribution/tree/master/manifest

**Comment by stevvooe** [comment]
@mboersma Read the entire specification and you will find how to push the image manifest: https://docs.docker.com/registry/spec/api/#pushing-an-image-manifest.

**Comment by stevvooe** [comment]
@mboersma Didn't mean to close. Let us know if you need help making this work.

**Comment by mboersma** [comment]
Of course the manifest format makes sense, and is well-documented. That's not what I asked.

How could I programmatically create a Docker layer (blob) with the equivalent of an ENV Dockerfile instruction?

**Comment by stevvooe** [comment]
@mboersma It should be pretty similar to V1, except without the amount of API interaction. Generate the V1 image format, add it to `v1Compatibility` with an empty tar layer. Add the empty tar layer digest to the `fsLayers` and you should be good.

**Comment by mboersma** [comment]
@stevvooe thanks, I'll give it a try.

**Comment by mboersma** [comment]
This looks like it will work. I'll open a new issue if I run into any specific problems. Thanks again for all the help!

**Comment by thaJeztah** [comment]
Good luck @mboersma!

**Comment by stevvooe** [comment]
@mboersma No problem. Let me know if you have questions.

**Comment by kevinsimper** [comment]
Is the `v1Compatibility` that will be kept around? The name sounds like it will be deprecated at some point.

**Comment by RichardScothern** [comment]
@kevinsimper : you are correct in your assumption.  Distribution will move to a new manifest format at some point.

Also, please don't comment on closed github issues.  You can post your questions to #docker-distribution and get an answer pretty quickly.
