### ISSUE TITLE
How to load yml registry configuration when using docker-compose

### ISSUE THREAD

**Issue by c0rnflex** [docker/distribution#643]
Hey,
I'm trying to figure out how to configure the registry configuration using yml syntax when running a container with docker-compose.

I understood one could use the environment fields in docker-compose.yml to override the container's environment variables, but this is terrible as it doesn't use the easy-to-use yml syntax.

Thanks.

**Comment by c0rnflex** [comment]
I ended up mounting the config.yml to /go/src/github.com/docker/distribution/cmd/registry/config.yml

hope this helps someone.

**Comment by dmp42** [comment]
@c0rnflex 

>  but this is terrible as it doesn't use the easy-to-use yml syntax.

A compose file **is** YML.

Furthermore, we are likely going to deprecate the use of config.yml for the registry, and allow only environment variables. YML is a terrible idea for config files, regularly tripping people over.

See for example http://12factor.net/config
