### ISSUE TITLE
v2 registry behind ELB w/SSL termination

### ISSUE THREAD

**Issue by c0rnflex** [docker/distribution#644]
I can't figure out how to make this work without defining insecure-registry.

Docker version 1.6.2, build 7c8fca2

ELB configuration:
Listener: HTTPS w/SSL termination
Forwarder: HTTP
Port for both: 5000

This works fine in localhost, but when trying to work via ELB:

> `FATA[0000] Error response from daemon: v1 ping attempt failed with error: Get https://<elb>:5000/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry <elb>:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/<elb>:5000/ca.crt`

I don't understand why it even tries to acess /v1/ - this is a v2 registry.

curl to https://ELB/v2/ works fine:

```
* Hostname was NOT found in DNS cache
*   Trying IP...
* Connected to HOSTNAME (IP) port 5000 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: OU=GT95455915; OU=See www.rapidssl.com/resources/cps (c)15; OU=Domain Control Validated - RapidSSL(R); CN=*.domain.io
* 	 start date: 2015-03-07 04:30:46 GMT
* 	 expire date: 2017-03-09 16:31:34 GMT
* 	 subjectAltName: HOSTNAME matched
* 	 issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
* 	 SSL certificate verify ok.
> GET /v2/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: HOSTNAME:5000
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Thu, 18 Jun 2015 15:47:10 GMT
< Docker-Distribution-Api-Version: registry/2.0
< Content-Length: 2
< Connection: keep-alive
<
* Connection #0 to host HOSTNAME left intact
```

**Comment by dmp42** [comment]
@c0rnflex have you tried the docs steps by steps? https://github.com/docker/distribution/blob/master/docs/deploying.md#making-your-registry-available ?

If you have, can you provide the minimal information requested? https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#if-you-have-not-found-an-existing-issue-that-describes-your-problem

At least: exact command you are running + docker daemon logs in debug mode.

Also, the engine tries v1 if your v2 registry is not working as expected.

From the fragment of log you copied, your docker daemon tries to access a registry on port 5000, while your curl command is on port 443. Are you sure your command is correct?

**Comment by c0rnflex** [comment]
@dmp42,
The steps you mentioned have nothing to say about running the registry behind an EC2 ELB.
That's where the SSL termination happens - and it's working correctly outside of docker.

The command I run (for example):
docker push <elb_hostname>:5000/<image>
Again, this works fine using localhost.

I guess you missed out  this part about the curl (port 5000):
SSL certificate verify ok. > GET /v2/ HTTP/1.1 > User-Agent: curl/7.35.0 > **Host: HOSTNAME:5000** > Accept: / > < HTTP/1.1 200 OK

HTTPS on port 5000 is the only one I have open on the ELB.

**Comment by dmp42** [comment]
@c0rnflex the steps mentioned cover how to configure TLS for the engine - it does not matter if you are using a proxy or using native TLS.

Either way, can you provide the requested info? (specifically the docker daemon logs ran in debug mode)

**Comment by c0rnflex** [comment]
Seems like restarting the docker daemon (after I added the debug mode parameter) fixed this issue.

Thanks.
