### ISSUE TITLE
Sync master > docs

### ISSUE THREAD

**Issue by moxiegirl** [docker/distribution#658]
Hi,

For the Dockercon  1.7 Eng and 2.0 Hub release, your project documentation was pulling from your master branch.

At this point, you must sync your  master branch files into the docs files BEFORE making changes for future releases in master.

This step allows Docker _as a whole_ to make incremental updates to the documentation website between releases.

After completing this work, please respond to this email with confirmation that it was completed.

Thanks

**Comment by stevvooe** [comment]
@moxiegirl Done:

```
git push -f upstream master:docs
```

Please confirm that worked.

**Comment by moxiegirl** [comment]
@stevvooe Looks good in test:

![image](https://cloud.githubusercontent.com/assets/1347209/8368897/9fdbb058-1b65-11e5-8550-992a5b9b47b9.png)
