### ISSUE TITLE
libceph dependencies are breaking automated PR testing

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#663]
We haven't had a successful build for a few days: https://circleci.com/gh/docker/distribution. We'll need to disable the rados drivers if we can't get this worked out today.

@gierschv @noahdesu @RyanDeng PTAL

**Comment by noahdesu** [comment]
Hm... this looks like it might be an issue with the upstream Ceph Debian packages.

**Comment by stevvooe** [comment]
@noahdesu Thank you for investigating. Let us know if you need more information.

**Comment by gierschv** [comment]
Hmm, I checked the log and the ceph packages now depend of boost 1.55, which is only available from utopic in the ubuntu distrib packages. And the librados-dev package which looks broken... I check if we can switch back to a functional install.

**Comment by gierschv** [comment]
In a fresh trusty container, no issue to install with the same commands. Package details:

```bash
root@e5fc9cb1b745:/# apt-cache policy librbd1
librbd1:
  Installed: 0.94.2-1trusty
  Candidate: 0.94.2-1trusty
  Version table:
 *** 0.94.2-1trusty 0
        999 http://ceph.com/debian-hammer/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.80.9-0ubuntu0.14.04.2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
     0.79-0ubuntu1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

root@e5fc9cb1b745:/# apt-cache show ceph | grep boost
Depends: binutils, ceph-common (>= 0.78-500), cryptsetup-bin | cryptsetup, gdisk, parted, python, python-argparse, sdparm | hdparm, uuid-runtime, xfsprogs, python-flask, libaio1 (>= 0.3.93), libboost-program-options1.54.0, libboost-system1.54.0, libboost-thread1.54.0, libbz2-1.0, libc6 (>= 2.16), libgcc1 (>= 1:4.1.1), libgoogle-perftools4, libleveldb1, liblttng-ust0, libnspr4 (>= 2:4.9-2~) | libnspr4-0d (>= 1.8.0.10), libnss3 (>= 2:3.13.4-2~) | libnss3-1d (>= 3.12.0~1.9b1), librados2, libsnappy1, libstdc++6 (>= 4.8), libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4)
```
@stevvooe Do you know if the distribution package in the circle container could have a higher pin priority? This is pretty weird since the boost required version is 1.54 in my container, not 1.55 like in circle . And this should be the same package....

```bash
[box242][DEBUG ]  ceph-common : Depends: librbd1 (= 0.94.2-1) but 0.80.1-0ubuntu1.1 is to be installed
```

**Comment by noahdesu** [comment]
Ahhh... I've seen this exact problem in Fedora before now that you mention
the priorities.

**Comment by stevvooe** [comment]
@gierschv I am not sure. I don't think we are installing any other packages that would affect this. My guess is that circle changed something under the hood. May want to try contacting their support.

**Comment by gierschv** [comment]
This looks now fixed.

FYI, Circle answered this morning: "The last image update was 10 days ago, so I don't think the installed packages are causing the issue. Your recent builds look ok now, but have you done workarounds?"

**Comment by stevvooe** [comment]
Looks like it worked itself out. I'll close this ticket for now and reopen if I see other issues.

**Comment by stevvooe** [comment]
@gierschv @noahdesu @RyanDeng We are having build problems again. This is blocking non-trivial PRs. Reopening this issue.

**Comment by noahdesu** [comment]
That is really weird. I can't tell exactly, but it seems as though the file descriptor error is coming from apt-get under the hood. I'll file a ticket with ceph-deploy devs and see if they know what is going on.

```
[box156][DEBUG ] Get:25 http://ceph.com/debian-hammer/ precise/main radosgw amd64 0.94.2-1precise [3,619 kB]
[box156][WARNIN] E: Could not open file descriptor -1
[box156][WARNIN] E: Prior errors apply to /var/cache/apt/archives/parted_2.3-19ubuntu1_amd64.deb
[box156][WARNIN] E: Prior errors apply to /var/cache/apt/archives/libboost-thread1.46.1_1.46.1-7ubuntu3_amd64.deb
[box156][WARNIN] E: Prior errors apply to /var/cache/apt/archives/librbd1_0.94.2-1precise_amd64.deb
```

**Comment by noahdesu** [comment]
Actually, it looks like maybe the ceph-deploy command syntax changed:

```
+ ceph-deploy mon create-initial box156
usage: ceph-deploy [-h] [-v | -q] [--version] [--username USERNAME]
                   [--overwrite-conf] [--cluster NAME] [--ceph-conf CEPH_CONF]
                   COMMAND ...
```

**Comment by stevvooe** [comment]
@noahdesu Thanks for taking a look. Let us know if there is anything you need.

**Comment by noahdesu** [comment]
I think that that create-initial has stopped accepting the host parameter at the end, and gets this information from ceph.conf that is created from `ceph-deploy new`.

I can't submit a PR right now, but I would suggest trying to change the command to be `ceph-deploy mon create-initial` (without the trailing hostname).

**Comment by stevvooe** [comment]
@noahdesu I've taken a crack at this, so we'll see if this works.
