### ISSUE TITLE
Implement Ali OSS storage driver

### ISSUE THREAD

**Issue by topikachu** [docker/distribution#669]
Ali OSS storage http://www.aliyun.com/product/oss/ is another key value blob storage similar as AMZ s3. However, OSS rest api is a little different from AMZ s3 and till now there's no offical golang sdk. 

I'd like to implement such docker storage driver

However, would you give me some suggestion? Is it better to put the low leve OSS rest api code together with the driver? Or shall I  introduce as Godep and keep in a separate repository?

**Comment by dmp42** [comment]
Hi @topikachu 

Have a look here: #514

**Comment by topikachu** [comment]
Hi, @dmp42 
I haven't seen any new activities of #514 and I'm not sure if the author is going to continue this PR.
Will docker accept that one or need a new one?

**Comment by stevvooe** [comment]
@topikachu Put together a proposal (in the description of this ticket) for how you will implement and how long you will be able to maintain it. We generally only accept drivers that will be actively maintained for at least a year.

**Comment by denverdino** [comment]
@topikachu 
We will continue maintain the OSS driver in Pull Request #514. and we have already used it in several internal projects in Aliyun of Alibaba inc. It is pretty solid now. Is there any feature you are requesting for which cannot be supported by that PR?

Thanks and your comments and suggestions are appreciated.

**Comment by stevvooe** [comment]
@denverdino Please compare with #514 with the comments in #443 and #493 for information on the storage driver concerns. The overview in #443 was extremely helpful in getting it merged. Since we don't have any access to these storage systems, we need to ensure that the build integrated with our CI system and there is a maintainer available to debug problems.

Hope that helps in moving this along!

**Comment by denverdino** [comment]
@stevvooe Thanks for your information and I will apply the account for you.

**Comment by aaronlehmann** [comment]
PR #514 was merged, so I'm closing this ticket.
