### ISSUE TITLE
Configuration page has broken links

### ISSUE THREAD

**Issue by moxiegirl** [docker/distribution#672]
![image](https://cloud.githubusercontent.com/assets/1347209/8421577/cce02d18-1e85-11e5-8a13-72f9702647d8.png)

And

![image](https://cloud.githubusercontent.com/assets/1347209/8421582/d91635dc-1e85-11e5-8693-362630af14d2.png)

**Comment by stevvooe** [comment]
Works fine in github: https://github.com/docker/distribution/blob/master/docs/configuration.md#loglevel.
https://github.com/docker/distribution/blob/master/docs/configuration.md#example-middleware-configuration.
