### ISSUE TITLE
Question: Problems pulling from a TLS enabled v2 registry with nginx proxy

### ISSUE THREAD

**Issue by noymn** [docker/distribution#674]
Hello,

I have been trying to setup a v2 registry with a Nginx proxy. To do so I have followed all the available guides with different success rate.

My problem is that, when I setup the proxy and try to access to it, docker registry rejects the connection due to a TLS problem. From the logs I think that the TLS connection gets finished at Nginx not being proxied to Docker with the failure.

Error:
```
root@docker-server:/etc/docker/certs.d/docker-registry.<fqdn>:5000# docker pull docker-registry.<fqdn>/kafka
Error response from daemon: invalid registry endpoint https://docker-registry.<fqdn>/v0/: unable to ping registry endpoint https://docker-registry.<fqdn>/v0/
v2 ping attempt failed with error: Get https://docker-registry.<fqdn>/v2/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
 v1 ping attempt failed with error: Get https://docker-registry.<fqdn>/v1/_ping: malformed HTTP response "\x15\x03\x01\x00\x02\x02". If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry docker-registry.<fqdn>` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/docker-registry.<fqdn>/ca.crt
```
Response:
```
 2015/06/30 16:07:26 http: TLS handshake error from 172.17.0.26:36222: tls: first record does not look like a TLS handshake
```

If I do a pull directly to the docker-registry it works...
```
root@docker-server:/etc/docker/certs.d/docker-registry.<fqdn>:5000# docker pull docker-registry.<fqdn>:5000/kafka
latest: Pulling from docker-registry.<fqdn>:5000/kafka
61b3964dfa70: Already exists
f5224fc54ad2: Already exists
25963d635584: Already exists
```

NOTE: The IP address is the one from the docker link

What's happening?

**Comment by noymn** [comment]
Ok, I had set up the TLS certificates on both endpoints: registry and nginx and that is incompatible.

I removed the certs from Docker registry and pull works as expected.

**Comment by dmcgowan** [comment]
@noymn The registry may be used to terminate SSL directly. Nginx is only suggested to be used when the registry setup is complex enough to warrant the addition complexity added by nginx (e.g. multi-registry load balancing).
