### ISSUE TITLE
Specify proposals from contributor summit

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#676]
During the DockerCon contributor summit, we discussed to ideas related to the registry:
1. [ ] An authentication framework for building token issuers for the registry and other docker services.
2. [ ] Distributed images through bittorrent.

I have some detailed notes and would like etch some proposals around these two topics. I know that @pushrax had a Google Doc sketching out some of these ideas.

Let's do the following:
1. Participants in the summit: Please email me directly. I don't have all of your contact emails.
2. Let's drop two proposals in the distribution project covering this work. We can work together or I can just provide an outline and we can work from there.

cc @pushrax @vaceletm  @arneluehrs

**Comment by pushrax** [comment]
Here's the doc referred to: https://docs.google.com/document/d/1rYDpSpJiQWmCQy8Cuiaa3NH-Co33oK_SC9HeXYo87QA

Feel free to start with some initial proposals – I don't think I have enough context to write a really solid migration roadmap. I will definitely comment and help flesh it out though.

cc @arneluehrs (I think that's the right account)

**Comment by arneluehrs** [comment]
@pusrax, thanks for the initial Strawman, will circle back to it in the upcoming days.

**Comment by vaceletm** [comment]
I'll draft the use case we discussed next week

**Comment by vaceletm** [comment]
Hi all,

Just yo keep you updated, I was quite busy the last month and it's very unlikely that I will have more time in the upcoming weeks. So I prefer to be honest, I will not add energy to dedicate to this anytime soon. Sorry for the over-commitement.

**Comment by stevvooe** [comment]
@vaceletm This one is going to take some time.

As glimpse of effort, https://gist.github.com/stevvooe/74b46521688d171495c9 shows my attempt at creating a tracker framework that integrate with the registry API smoothly.

My research showed a few things:

1. The registry works excellently as a webseed. We'll have to integrate our token authorization into a torrent client to make it work well. It seems we can make this work quite well without sacrificing any security.
2. We will need to store the infohashes for the raw blob, minus tracker configuration on the disk. The repository specific torrent file will have to be generated at request time. Trackers are organized by info hash (sort of) and we may need to join several info hashes to support updating torrent urls.
3. At this time, selecting a client has been problematic. Most are focused on on-disk files and supporting variations in the implementations hiding the protocol aggressively. I'll play with this further but we still need to find a pure Go client that can accomplish this, well.

Sorry I haven't been great on the updates, but there is some progress.

**Comment by scalp42** [comment]
@stevvooe do you have any kind of timeframe for the p2p push/pull registry? Trying to figure a way for intensive docker images pulling.

Thanks in advance!

**Comment by stevvooe** [comment]
@scalp42 My goal was to convince the docker project to properly store artifacts (layers + config). I've faced a lot of opposition to this but p2p cannot go forward without it. I cannot give you a timeframe for p2p.

The most approachable way to scale is probably readonly registry clones synced with a master using rsync. It will be a tricky setup but we've heard people have success with it.

**Comment by scalp42** [comment]
@stevvooe understood, thanks for answering so fast! :smiley:

**Comment by xiaods** [comment]
it out of date.

**Comment by stevvooe** [comment]
@xiaods Proposals here are still relevant. There are some novel ideas in p2p that we didn't consider at this summit, but the problems are still the same.

**Comment by xiaods** [comment]
@stevvooe thanks for your clarify. got it.

**Comment by stevvooe** [comment]
This issue is way out of date. Closing, as this effort probably needs to be based on current functionality.
