### ISSUE TITLE
Unclear you apparently need to set the option REGISTRY_STORAGE: s3 config var

### ISSUE THREAD

**Issue by astubbs** [docker/distribution#679]
Is it just me, or from this documentation is it quite unclear, and i haven't seen it demonstrated anywhere, that I had to set the REGISTRY_STORAGE: s3 environment variable to get the registry to look at my s3 config options? Without they appeared to be ignored. I got this clue from looking at the configuration source code. There didn't appear to be anything there to derive to driver mode simply from what config options had been specified? Am I wrong?

**Comment by RichardScothern** [comment]
Option overriding is documented here: https://docs.docker.com/registry/configuration/ with a note about changing a top-level option type.

I'm not sure what your configuration looks like,  but if you have s3 storage parameters to use, the storage type must also be set to s3

**Comment by astubbs** [comment]
Yes I read all that. I must be miss reading it because I can't see what to set exactly. There is no storage.type in the example config or storage: type?
I tried a few permutations but couldn't get it to pick up until I did as I mentioned above. 

"The storage option is required and defines which storage backend is in use. You must configure one backend; if you configure more, the registry returns an error."

Simply providing all the settings for s3 didn't work.

**Comment by astubbs** [comment]
I guess I would have expected to see in the reference config some thing like:

Storage: s3,azure,file system, etc...

As opposed to 

Storage:
            S3
                  Options

Seems very subtle to me but maybe it's just not a config system I'm used to.

**Comment by stevvooe** [comment]
@astubbs This configuration system has its defects. The handling of environment variables is one of many issues. The configuration documentation you're citing refers to the use of the yaml configuration. I filed #116 to cover these kinds of problems, but for this use case, I do recommend writing your own configuration file and adding it to a docker image.

**Comment by astubbs** [comment]
Glad I'm not completely crazy ;)
