### ISSUE TITLE
Separate authentication specification from JWT specific implementation

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#684]
Currently the authentication specification for the V2 API contains two main sections. The first describing the role of an authentication server and the second describing a JWT token specification which is used by the hub and integrated into the distribution project. These sections should be split out and the JWT token specification should be listed as one example of an authentication server with distribution server side support. The authentication server should be described more generally.  In the future a wider range of tokens should be accepted including macaroon based authentication.

cc @mattmoor raising this issue in the working group

**Comment by mattmoor** [comment]
In particular, I would word this as "tokens should be treated as opaque data by the Docker client".

It should be assumed that only the registry that provided a token can interpret it.

thanks for opening this.
