### ISSUE TITLE
User reports deploying documentation is incorrect

### ISSUE THREAD

**Issue by moxiegirl** [docker/distribution#718]
marshyon@gmail.com via docker.com 9:03 AM (7 minutes ago) to feedback 
at :

https://docs.docker.com/registry/deploying/

it says to run :

$ docker run -d -p 5000:5000 \
    -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry \
    -v /myregistrydata:/var/lib/registry \
    --restart=always --name registry registry:2

this is wrong, I figured it out as I have been playing around with docker for a bit now but it confused me a bit - it could put others off entirely

I ran

docker run -d -p 5000:5000 -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry -v /var/lib/registry:/var/lib/registry --restart=always --name registry registry:2

 then files started to appear in /var/lib/registry

I dont know where 'myregistrydata' comes from and the doc is unclear

JOn.

**Comment by dmp42** [comment]
What exactly is wrong?

**Comment by dmp42** [comment]
"/myregistrydata" is exactly where "[your]-registry-data" is going to live.
Though users familiar with docker volumes would figure that, maybe the doc could be made more explicit.

Either way, the information is both correct and what users should do.
Let me know if you feel this deserve a follow-up PR.

Closing for now.
