### ISSUE TITLE
Storage driver tests invalid offset boundary

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/distribution#72]
Storage driver test suite's `TestReadStreamWithOffset` method tries to make a ReadStream call with offset=size and expects to get a reader of size=0 and EOF. [[source]](https://github.com/docker/distribution/blob/10c9dfb5a63422e4f644cc8421581da8ad09b65e/storagedriver/testsuites/testsuites.go#L331)

This is not accurate. If a file is 10 bytes, there is no offset=10 for this path. Practically, asking for offset=10 and offset=20 are the same thing for a file of 10 bytes, it does not exist. Therefore `ReadStream(path, 10)` should be an `InvalidOffsetError`.

I can quickly fix in the storagedriver implementation with an if clause but that shouldn't be the fix as there's a semantic mistake with the boundaries here. We've discussed and fixed a similar bug in the past. https://github.com/docker/docker-registry/pull/787 

LMK if you agree and then I can send a PR. cc: @stevvooe @BrianBland

**Comment by stevvooe** [comment]
This is indeed correct behavior. By forcing the method to report the error as an `InvalidOffsetError`, you're creating an error condition that is already covered by the `io.Reader` interface. `InvalidOffsetError` should only be throw for offsets that are actually invalid, such a negative offsets.

In general, this makes client code much simpler and ensures that the readers provided by `ReadStream` are consistent with those in the Go standard library.
