### ISSUE TITLE
Private repository can't pull images

### ISSUE THREAD

**Issue by gwkunze** [docker/distribution#725]
I've set up a private (v2) repository on our intranet behind an ssl terminating haproxy. Pushing images to the repository seems to work. But when I try to pull I get the following output:

```
latest: Pulling from docker.intranet/test/image
64e5325c0d9d: Pulling fs layer
bf84c1d84a8f: Pulling fs layer
bcb3b20803be: Pulling fs layer
1eb32363a68b: Pulling fs layer
eea62da84039: Pulling fs layer
eca840e59a49: Pulling fs layer
1f123bffd1f8: Pulling fs layer
e6ddc260d581: Pulling fs layer
c30b18168228: Pulling fs layer
b1c705ec3fdd: Download complete
Pulling repository docker.intranet/test/image
FATA[0001] Error: image test/image:latest not found
```

So it seems to download the layers correctly but fails nonetheless.

Looking into the logs of the repository I see:

```
192.168.56.12 - - [22/Jul/2015:14:10:26 +0000] "GET /v1/repositories/test/image/images HTTP/1.1" 404 19 "" "docker/1.6.2 go/go1.3.3 kernel/3.14.35-28.38.amzn1.x86_64 os/linux arch/amd64"
```

So for some reason docker is requesting a v1 url (while all the other requests are to a v2 url).

Distribution version: v2.0.1
Docker client: 1.6.2
(update, added versions)

**Comment by dmp42** [comment]
Can you copy your docker daemon logs? (in debug)

Ideally: https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#if-you-have-not-found-an-existing-issue-that-describes-your-problem

**Comment by gwkunze** [comment]
Apologies for not reading that document. From the debug output I realised the issue was #426. So I've fixed it by adding the appropriate certificates to ca.crt.
