### ISSUE TITLE
Docker Registry to support AWS IAM roles for S3 storage

### ISSUE THREAD

**Issue by jhmartin** [docker/distribution#741]
The docker registry should support fetching temporary credentials via the AWS IAM instance-role function rather than requiring hardcoded credentials.

**Comment by stevvooe** [comment]
@jhmartin How would this work? Do you have links to documentation?

As far as I understand, this is handled on the aws package side, so it is really outside the scope of the registry. This may be already supported. Have you tried it?

**Comment by stevvooe** [comment]
Confirmed this is already supported: https://github.com/docker/distribution/blob/master/Godeps/_workspace/src/github.com/AdRoll/goamz/aws/aws.go#L319.

**Comment by jhmartin** [comment]
Oh! I saw 'required' in the documentation for the access/secret key fields and assumed I would get an error if I omitted them. Excellent.

**Comment by moshe0076** [comment]
I you are using IAM role just remove the:
 accesskey: awsaccesskey
 secretkey: awssecretkey
lines from the config.yml and it should work.

**Comment by rokka-n** [comment]
Can somebody fix the documentation, if it's already implemented?
It's still mentioned that keys required:
https://docs.docker.com/registry/storage-drivers/s3/

**Comment by stevvooe** [comment]
@mstanleyjones PTAL

**Comment by mstanleyjones** [comment]
https://github.com/docker/docker.github.io/pull/1711
