### ISSUE TITLE
Docker Registry support S3 server-side encryption

### ISSUE THREAD

**Issue by jhmartin** [docker/distribution#742]
The S3 backend should be able to trigger S3 to utilize server-side encryption as described at http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

**Comment by stevvooe** [comment]
@jhmartin Please read the documentation, consult the mailing list or ask on IRC before filing an issue.

This is already supported:

https://github.com/docker/distribution/blob/master/docs/configuration.md#s3
