### ISSUE TITLE
Stop-the-world GC

### ISSUE THREAD

**Issue by RichardScothern** [docker/distribution#743]
Enumerate the manifests and blobs of a registry to determine which blobs are no-longer referenced in a registry and delete them.

Depends on #677 and #510

**Comment by RichardScothern** [comment]
Intention is to use DHE implementation which is currently in review.

**Comment by dmp42** [comment]
Ping @docker/dhe-dev - what's the status on this?

**Comment by RichardScothern** [comment]
closed by #1386
