### ISSUE TITLE
Client response code acceptance is too narrow

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#748]
For example, the following code is not specification compliant:

```go
	switch resp.StatusCode {
	case http.StatusAccepted:
		// TODO(dmcgowan): make use of digest header
		return nil
	default:
		return handleErrorResponse(resp)
	}
```

In this case, the client should accept 2xx, 3xx as successful, unless otherwise called out in the specification (such as when different response codes mean different things).

This needs to be fixed an integrated into docker 1.8. @icecrime

**Comment by aaronlehmann** [comment]
Created a PR: https://github.com/docker/distribution/pull/750

**Comment by thaJeztah** [comment]
Is this resolved, now that https://github.com/docker/distribution/pull/750 was merged?

**Comment by aaronlehmann** [comment]
#750 should resolve it. I created a PR to update the vendored dependency in docker/docker here: https://github.com/docker/docker/pull/15034

**Comment by aaronlehmann** [comment]
Closing now that the vendored dependency was updated in docker/docker.

**Comment by thaJeztah** [comment]
Thanks!
