### ISSUE TITLE
Support for S3 Reduced Redundancy

### ISSUE THREAD

**Issue by sonicsnes** [docker/distribution#753]
Unlike many applications which need resilient storage, nearly all data in a docker registry can be easily re-created (assuming one has a proper centralized image build environment). This makes it a prime candidate for the cheaper cost of s3 reduced redundancy storage.

Right now, I'm using a cron job to scan and re-tag all the files in my registry bucket as RR, but it would be nice if we had the option to tag newly uploaded images as reduced redundancy from the start.

**Comment by dmp42** [comment]
ping @amitshukla - do you think this might make it for the release?

**Comment by RichardScothern** [comment]
closed by #1401
