### ISSUE TITLE
Token caching, and credentials saving options

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#759]
A frequently requested enterprise feature is for the engine to not have to save credentials locally.
Using garant, we could maybe cache tokens locally (details and strategy to be figured out).

**Comment by stevvooe** [comment]
Sounds like this belongs in docker/docker?

**Comment by dmp42** [comment]
I wish that code would live here :)

**Comment by stevvooe** [comment]
@dmp42 This is a much larger project and a huge part of the engine. Any way we slice this, we'd have to connect with a key store on the engine side, which would have to be passed into the registry client.

**Comment by dmp42** [comment]
This issue here is much more modest than that.

**Comment by dmp42** [comment]
Closing in favor of https://github.com/docker/docker/issues/10318 for now.

**Comment by HuKeping** [comment]
hi @stevvooe  what's the plan for this issue, is it possible to store the credentials just in RAM?

**Comment by stevvooe** [comment]
@HuKeping 

> Closing in favor of docker/docker#10318 for now.
