### ISSUE TITLE
Support resumable download

### ISSUE THREAD

**Issue by RichardScothern** [docker/distribution#762]
There is currently some code in the docker client to support HTTP range requests, but it isn't used in the docker daemon.  The use-case for this is resuming a partial download.

If the functionality is desired; we should support resumable download in the docker daemon, the registry and the registry-as-a-cache.

cc @dmp42 @dmcgowan

**Comment by dmp42** [comment]
This was working in the v1 world - I'm curious why it wouldn't in v2 as well, but we definitely need it if it does not.

**Comment by stevvooe** [comment]
@RichardScothern Resumable download is already supported in the registry through the use of `http.ServeContent` and `Range` requests. This is probably a daemon feature request. Arguably, we can provide a client library that manages this but it would have to control or have some way of taking the storage locations as an argument.

@dmp42 The resumable code for v1 is a little unintelligible and we avoided using it.

**Comment by dmp42** [comment]
cc @dmcgowan for tests @aaronlehmann for client implementation and Santa Claus for this to happen :)

**Comment by aaronlehmann** [comment]
On the engine side, I'm assuming we don't want to keep partial files around long-term, since they will consume disk space. I think a good compromise would be to attempt resuming a download if it fails due to a network issue and the engine needs to retry it. Does this sound good?

**Comment by dmp42** [comment]
Yes, this should really only be used as part of a hot-retry mechanism.

**Comment by dmp42** [comment]
@aaronlehmann can this be closed?

**Comment by aaronlehmann** [comment]
We don't support resumable downloads yet, so I don't think it should be.

**Comment by aaronlehmann** [comment]
I think we can close this issue. The engine already resumes downloads during a `docker pull` session, when the connection is interrupted. There is a PR at https://github.com/moby/moby/pull/28348 that persists the temporary files longer-term. This was very close to being ready for merge, but unfortunately has been sitting for awhile.

In any case, any further changes here would be entirely on the "moby" side, and don't affect the distribution repository.

**Comment by stevvooe** [comment]
@aaronlehmann Great! For the most part, we have all the pieces required (and it works in containerd!).
