### ISSUE TITLE
Alternative s3 host

### ISSUE THREAD

**Issue by FredrikNoren** [docker/distribution#767]
I'm trying to use https://github.com/jubos/fake-s3 with the docker registry, but from what I can tell there's no way to configure the s3 hostname? Would be awesome to be able to configure that so that I can bind it to a container running fake-s3 (using this for development purposes).

**Comment by lorieri** [comment]
Hi, could you test this ? 
https://github.com/docker/distribution/pull/808

cheers

**Comment by mboersma** [comment]
This should be closed by #808.

**Comment by BrianBland** [comment]
Closing as duplicate of #808
