### ISSUE TITLE
/v2/_catalog does not exist

### ISSUE THREAD

**Issue by FredrikNoren** [docker/distribution#768]
`curl mydocker/v2/_catalog` gives me a 404 (other endpoints work fine). It's referenced in the documentation but unclear to me if it exists yet?

**Comment by lsamayoa** [comment]
It currntly exists in master repo but it is planned to be released in v2.1 which has a due date of August 4

**Comment by RichardScothern** [comment]
Correct.

**Comment by FredrikNoren** [comment]
Thanks!
