### ISSUE TITLE
Private registry push failed: 500 error due to S3 "SlowDown" error

### ISSUE THREAD

**Issue by baldzern4** [docker/distribution#769]
Hi,
we are running the latest private registry 2.0.1 with AWS S3 as backend. 
While uploading images (~100-300 MB) we are getting from time to time http:503 "SlowDown" errors from S3.

This error can happen if hundreds of PUT request are done to one bucket (see [http://aws.amazon.com/articles/1904]())

So I think:
 
1. S3 Storage engine doesn't react on this error with exponational backoff strategy as AWS discribes in [http://aws.amazon.com/articles/1904]().
2. The error is not handled correctly, because no retry is done. Instead the error is forwared as http:500 to the client.

**Docker Registry Information**  
Docker version: docker/1.7.1 go/go1.4.2 git-commit/786b29d 
Storage backend: S3 

**Debug output:**  

```
time="2015-07-24T09:30:51.2516226Z" level=info msg="s3.WriteStream(\"/docker/registry/v2/repositories/company/n4servicebase_n4relp/_uploads/5892e837-1860-46a2-94cc-528223bacceb/data\", 0)" trace.duration=12.908167038s trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base
/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).WriteStream" trace.id=266b94bc-81c7-48ec-b2a8-f631fd33ba57 trace.line=95 


time="2015-07-24T09:30:51.251691872Z" level=debug msg="(*layerWriter).Finish" environment=development http.request.host=<REMOVED> http.request.id=543789a7-bc1c-470f-ac4f-4a189e615f5a http.request.method=PUT http.request.remoteaddr=10.0.2.158 http.request.uri="/v2/company/n4servicebase_
n4relp/blobs/uploads/5892e837-1860-46a2-94cc-528223bacceb?_state=<STATE>
%3D&digest=sha256%<DIGEST>" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-0.bpo.4-amd64 os/linux arch/amd64" instance.id=727f874c-b023-40df-b4d9-a36048868d9f service=registry vars.name="company/n4serviceb
ase_n4relp" vars.uuid=5892e837-1860-46a2-94cc-528223bacceb version=v2.0.1 

time="2015-07-24T09:30:51.295113566Z" level=info msg="s3.Stat(\"/docker/registry/v2/blobs/sha256/8a/8abb6c6a3c0a8b7d9ec837ddd87fd346a2a5b43b0dafcce6d5fac80984e14aaa/data\")" trace.duration=43.315054ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func
="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=1bd54ec7-64d2-4cdf-9de8-e42925262bcb trace.line=111 

time="2015-07-24T09:30:51.337778973Z" level=info msg="s3.Stat(\"/docker/registry/v2/repositories/company/n4servicebase_n4relp/_uploads/5892e837-1860-46a2-94cc-528223bacceb/data\")" trace.duration=42.560934ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" 
trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=9639bf50-1cd3-487e-a593-cfc985648e30 trace.line=111 

time="2015-07-24T09:30:51.354908062Z" level=info msg="s3.Move(\"/docker/registry/v2/repositories/company/n4servicebase_n4relp/_uploads/5892e837-1860-46a2-94cc-528223bacceb/data\", \"/docker/registry/v2/blobs/sha256/8a/8abb6c6a3c0a8b7d9ec837ddd87fd346a2a5b43b0dafcce6d5fac80984e14aaa/data\"" trace.
duration=17.031001ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Move" trace.id=c2deb7f7-2b47-44c1-872d-cccf0f4593d8 trace.line=135 

time="2015-07-24T09:30:51.354986724Z" level=error msg="unknown error completing upload: &s3.Error{StatusCode:503, Code:\"SlowDown\", Message:\"Please reduce your request rate.\", BucketName:\"\", RequestId:\"15498834E4967418\", HostId:\"88S6JEd1CNLl6w0O7kfoaKFAQzGcb/MRhZMQThNV4n4JGLKiTqYwCUSaDQ0hkwX/BL9SbmtSeXg=\"}" environment=development http.request.host=<REMOVED> http.request.id=543789a7-bc1c-470f-ac4f-4a189e615f5a http.request.method=PUT http.request.remoteaddr=10.0.2.158 http.request.uri="/v2/company/n4servicebase_n4relp/blobs/uploads/5892e837-1860-46a2-94cc-528223bacceb?_state=<STATE>%3D&digest=sha256%<DIGEST>" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-0.bpo.4-amd64 os/linux arch/amd64" instance.id=727f874c-b023-40df-b4d9-a36048868d9f service=registry vars.name="company/n4servicebase_n4relp" vars.uuid=5892e837-1860-46a2-94cc-528223bacceb version=v2.0.1 

time="2015-07-24T09:30:51.355054525Z" level=debug msg="(*layerWriter).Cancel" environment=development http.request.host=<REMOVED> http.request.id=543789a7-bc1c-470f-ac4f-4a189e615f5a http.request.method=PUT http.request.remoteaddr=10.0.2.158 http.request.uri="/v2/company/n4servicebase_n4relp/blobs/uploads/5892e837-1860-46a2-94cc-528223bacceb?_state=<STATE>%3D&digest=sha256%<DIGEST>" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-0.bpo.4-amd64 os/linux arch/amd64" instance.id=727f874c-b023-40df-b4d9-a36048868d9f service=registry vars.name="company/n4servicebase_n4relp" vars.uuid=5892e837-1860-46a2-94cc-528223bacceb version=v2.0.1 

time="2015-07-24T09:30:51.49266334Z" level=info msg="s3.Delete(\"/docker/registry/v2/repositories/company/n4servicebase_n4relp/_uploads/5892e837-1860-46a2-94cc-528223bacceb\")" trace.duration=137.54242ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Delete" trace.id=84ddcfeb-0afc-4ddf-a569-01597fd5fe80 trace.line=149 

time="2015-07-24T09:30:51.492750912Z" level=error msg="An error occured" environment=development err.code=UNKNOWN err.detail="Please reduce your request rate." err.message="unknown error" http.request.host=<REMOVED> http.request.id=543789a7-bc1c-470f-ac4f-4a189e615f5a http.request.method=PUT http.request.remoteaddr=10.0.2.158 http.request.uri="/v2/company/n4servicebase_n4relp/blobs/uploads/5892e837-1860-46a2-94cc-528223bacceb?_state=<STATE>%3D&digest=sha256%<DIGEST>" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-0.bpo.4-amd64 os/linux arch/amd64" instance.id=727f874c-b023-40df-b4d9-a36048868d9f service=registry vars.name="company/n4servicebase_n4relp" vars.uuid=5892e837-1860-46a2-94cc-528223bacceb version=v2.0.1 

time="2015-07-24T09:30:51.49284106Z" level=info msg="response completed" environment=development http.request.host=<REMOVED> http.request.id=543789a7-bc1c-470f-ac4f-4a189e615f5a http.request.method=PUT http.request.remoteaddr=10.0.2.158 http.request.uri="/v2/company/n4servicebase_n4relp/blobs/uploads/5892e837-1860-46a2-94cc-528223bacceb?_state=<STATE>%3D&digest=sha256%<DIGEST>" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-0.bpo.4-amd64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=13.190556546s http.response.status=500 http.response.written=102 instance.id=727f874c-b023-40df-b4d9-a36048868d9f service=registry version=v2.0.1 

172.31.8.163 - - [24/Jul/2015:09:30:38 +0000] "PUT /v2/company/n4servicebase_n4relp/blobs/uploads/5892e837-1860-46a2-94cc-528223bacceb?_state=<STATE>%3D&digest=sha256%<DIGEST> HTTP/1.1" 500 102 "" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-0.bpo.4-amd64 os/linux arch/amd64"
```
*Some content was replaced with tags to make the output readable. 

Br,  
Jörg Baldzer

**Comment by cknitt** [comment]
I am seeing the same issue since about a week.

**Comment by stevvooe** [comment]
@baldzern4 Retries are actually done by the s3 library, so most of your assertions are completely false. Retrying when an error message is "Please reduce your request rate" seems like it would only make things worse.

We haven't seen this error in production on the hub, so it is surprising that you would see them unless you're pushing a large volume of images.

What volume of images are pushing to this instance?

Is this the only service you are running against the s3 account? Are there others using the same credentials?

I would suggest you contact s3 support.

**Comment by baldzern4** [comment]
@stevvooe: I am in contact with S3 support. They are currently looking at our bucket. The strange thing is: 
- the bucket is only used by a single EC2 instance,
- no other service is using it or has access to the bucket,
- image size is around 300MB,
- only one image at a time was pushed,
- i could reproduce it with a second instance running on a different dedicated bucket.

We are seeing this only at S3 Frankfurt, so maybe S3 in Frankfurt is under heavy load. But this is not the issue I am talking about. If S3 is reporting a 5xx error the client has to react in compliance with the methods described in [http://aws.amazon.com/articles/1904](http://aws.amazon.com/articles/1904):

>Handling Errors

>Any code you write to call Amazon S3 APIs should expect to receive and handle errors from the service. A given error may be returned for multiple reasons, so it's a good idea to look at (and handle in code), the error messages returned with the error number.

>500-series errors indicate that a request didn't succeed, but may be retried. Though infrequent, these errors are to be expected as part of normal interaction with the service and should be explicitly handled with an exponential backoff algorithm (ideally one that utilizes jitter). One such algorithm can be found at http://en.wikipedia.org/wiki/Truncated_binary_exponential_backoff.

So I think the S3 backend implementation should implement the retry / backoff strategy else it can't be used as a trusted storage backend.  As far as I know the docker registry is currently not using the official AWS SDK for S3 access (https://github.com/AdRoll/goamz is used), maybe switching (like described in #122) would solve this issue, too.

**Comment by stevvooe** [comment]
@baldzern4 Thank you for the extra information. Please let us know how the interaction with S3 support goes.

As it stands, goamz actually [implements retries](https://github.com/AdRoll/goamz/blob/master/s3/s3.go#L1241). We also have some higher level retries where it [makes sense](https://github.com/docker/distribution/blob/master/registry/storage/driver/s3/s3.go#L429).

Looking at this, simply updating the goamz driver might be enough to fix this particular problem. Looking at our [vendored version](https://github.com/docker/distribution/blob/master/Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3.go#L1262), the extra retries for those particular response codes are missing.

**Comment by skozin** [comment]
I am seeng this too, on almost every push. The bucket is located in Frankfurt region, just like in @baldzern4's case. I've seen this error while pushing images as small as 20MB.

**Comment by stevvooe** [comment]
#812 to get some fixes from upstream that may help here.

@skozin I know this is annoying and we will try our best to paper over the problems with s3, but I suggest that you bring this up with AWS support. We've put a lot of effort into assuring that this works correctly with s3, but there seem to be undocumented regional differences contributing to this instability.

**Comment by baldzern4** [comment]
Since 07/30 the AWS S3 team is investigating this issue. But no feedback so far.

**Comment by RichardScothern** [comment]
@baldzern4 are you still experiencing difficulties?  Were you able to get a reply from AWS?

**Comment by baldzern4** [comment]
@RichardScothern I got feedback from AWS today: The S3 team found an internal issue within the REST.COPY.OBJECT feature in eu-central-1(FRANKFURT region). They were able to fix it. So S3 in Frankfurt should be ok right now. I will setup a test instance to verify this.

**Comment by baldzern4** [comment]
@RichardScothern I was able to push several images without any issues.

**Comment by RichardScothern** [comment]
Good to know.  Thanks @baldzern4

**Comment by skozin** [comment]
I am seeing this again with Registry 2.1.1. Most of pushes fail with HTTP 500 error.

For example, in the log below, 8 successive attempts to push the same image (about 60 MB total upload size) failed, and all these attempts together consumed _more than an hour_, which is unacceptable.

```
The push refers to a repository [registry:5000/static] (len: 1)
0c1027e97223: Image already exists
7d44c4b356ff: Image successfully pushed
79b6ea1da35c: Image successfully pushed
965bef77cf93: Image successfully pushed
ebe3389148d5: Image successfully pushed
548be9b8c184: Image successfully pushed
b6ae66438c4b: Image successfully pushed
3eab5865e899: Image successfully pushed
682d8b843fac: Image already exists
9c64edf746c9: Image already exists
f93f08f800a3: Image already exists
0b7e5f4c1559: Image already exists
dfe2f091348c: Image already exists
e1d460fb349c: Image already exists
736dfa84ed74: Image already exists
15abf35b937b: Image push failed
FATA[0825] Error pushing to registry: Server error: 500 trying to push static blob - sha256:687cf5fe0504de4a16e217add5a2e504a6ff3decfab80fbdc739b2962ebd23ff

Attempt 1 to push "registry:5000/static:latest" failed

The push refers to a repository [registry:5000/static] (len: 1)
0c1027e97223: Image already exists
7d44c4b356ff: Image already exists
79b6ea1da35c: Image already exists
965bef77cf93: Image already exists
ebe3389148d5: Image already exists
548be9b8c184: Image already exists
b6ae66438c4b: Image already exists
3eab5865e899: Image already exists
682d8b843fac: Image already exists
9c64edf746c9: Image already exists
f93f08f800a3: Image already exists
0b7e5f4c1559: Image already exists
dfe2f091348c: Image already exists
e1d460fb349c: Image already exists
736dfa84ed74: Image already exists
15abf35b937b: Image push failed
FATA[0321] Error pushing to registry: Server error: 500 trying to push static blob - sha256:84805bc65b79300143b6c4c09bbcac93d83cbbb1795a961a0277041b7d8c36b3

Attempt 2 to push "registry:5000/static:latest" failed

...

FATA[0296] Error pushing to registry: Server error: 500 trying to push static blob - sha256:687cf5fe0504de4a16e217add5a2e504a6ff3decfab80fbdc739b2962ebd23ff

Attempt 8 to push "registry:5000/static:latest" failed
```

There are lots of "Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed" errors and HTTP 500s (with codes `BLOB_UNKNOWN` and `UNKNOWN`) in Registry logs ([full output of the below command here](https://gist.github.com/skozin/51e1cd9243f16e6f824b)):

```
$ docker logs registry | grep -E '500 |error'

time="2015-09-21T21:25:30.019797063Z" level=error msg="error putting part, retrying after Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.: 300ms"
time="2015-09-21T21:27:11.3217593Z" level=error msg="error putting part, retrying after Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.: 100ms"
time="2015-09-21T21:28:06.357453834Z" level=error msg="error putting part, retrying after Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.: 200ms"
time="2015-09-21T21:28:55.39059582Z" level=error msg="response completed with error" err.code="BLOB_UNKNOWN" err.detail=sha256:687cf5fe0504de4a16e217add5a2e504a6ff3decfab80fbdc739b2962ebd23ff err.message="blob unknown to registry" http.request.host="registry:5000" http.request.id=cb056b79-e4ca-4669-a831-2681eb6025b5 http.request.method=HEAD http.request.remoteaddr="10.0.42.1:37744" http.request.uri="/v2/static/blobs/sha256:687cf5fe0504de4a16e217add5a2e504a6ff3decfab80fbdc739b2962ebd23ff" http.request.useragent="docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/3.16.0-23-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=813.533796ms http.response.status=404 http.response.written=157 instance.id=c689e6f1-8ffd-4a58-92c0-59b156780bbf vars.digest="sha256:687cf5fe0504de4a16e217add5a2e504a6ff3decfab80fbdc739b2962ebd23ff" vars.name=static version=v2.1.1

...

time="2015-09-21T21:33:55.187988089Z" level=error msg="response completed with error" err.code=UNKNOWN err.detail="Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed." err.message="unknown error" http.request.host="registry:5000" http.request.id=dd65ad33-b646-4d8a-bbae-a34d47d9d51b http.request.method=PUT http.request.remoteaddr="10.0.42.1:37840" http.request.uri="/v2/static/blobs/uploads/5acceb37-4245-4ecd-ae32-75f0a1c56c79?_state=zuFJ23khESySvQDmduLTdhrKG8NTsMFRZxBSJ8buLxB7Ik5hbWUiOiJzdGF0aWMiLCJVVUlEIjoiNWFjY2ViMzctNDI0NS00ZWNkLWFlMzItNzVmMGExYzU2Yzc5IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTA5LTIxVDIxOjI5OjEwLjM0MTcwNDcxOFoifQ%3D%3D&digest=sha256%3A687cf5fe0504de4a16e217add5a2e504a6ff3decfab80fbdc739b2962ebd23ff" http.request.useragent="docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/3.16.0-23-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=4m43.41993598s http.response.status=500 http.response.written=386 instance.id=c689e6f1-8ffd-4a58-92c0-59b156780bbf vars.name=static vars.uuid=5acceb37-4245-4ecd-ae32-75f0a1c56c79 version=v2.1.1
10.0.42.1 - - [21/Sep/2015:21:29:11 +0000] "PUT /v2/static/blobs/uploads/5acceb37-4245-4ecd-ae32-75f0a1c56c79?_state=zuFJ23khESySvQDmduLTdhrKG8NTsMFRZxBSJ8buLxB7Ik5hbWUiOiJzdGF0aWMiLCJVVUlEIjoiNWFjY2ViMzctNDI0NS00ZWNkLWFlMzItNzVmMGExYzU2Yzc5IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTA5LTIxVDIxOjI5OjEwLjM0MTcwNDcxOFoifQ%3D%3D&digest=sha256%3A687cf5fe0504de4a16e217add5a2e504a6ff3decfab80fbdc739b2962ebd23ff HTTP/1.1" 500 386 "" "docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/3.16.0-23-generic os/linux arch/amd64"
time="2015-09-21T21:34:05.961630194Z" level=error msg="response completed with error" err.code="BLOB_UNKNOWN" err.detail=sha256:687cf5fe0504de4a16e217add5a2e504a6ff3decfab80fbdc739b2962ebd23ff err.message="blob unknown to registry" http.request.host="registry:5000" http.request.id=65746095-d914-447f-aedd-e747dba9ef89 http.request.method=HEAD http.request.remoteaddr="10.0.42.1:39450" http.request.uri="/v2/static/blobs/sha256:687cf5fe0504de4a16e217add5a2e504a6ff3decfab80fbdc739b2962ebd23ff" http.request.useragent="docker/1.6.2 go/go1.4.2 git-commit/7c8fca2 kernel/3.16.0-23-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=501.18656ms http.response.status=404 http.response.written=157 instance.id=c689e6f1-8ffd-4a58-92c0-59b156780bbf vars.digest="sha256:687cf5fe0504de4a16e217add5a2e504a6ff3decfab80fbdc739b2962ebd23ff" vars.name=static version=v2.1.1
time="2015-09-21T21:35:31.742216273Z" level=error msg="error putting part, retrying after Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.: 100ms"
time="2015-09-21T21:36:27.274717511Z" level=error msg="error putting part, retrying after Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.: 200ms"
time="2015-09-21T21:37:24.237711728Z" level=error msg="error putting part, retrying after Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.: 300ms"
time="2015-09-21T21:38:20.113974704Z" level=error msg="error putting part, retrying after Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.: 400ms"
```

But, pushes kind of work from my dev machine when I enable "Network link conditioner" in OS X and limit my uplink to 33 Mbps (normally 80-90 Mbps).

Tested with different S3 regions, the issue remains regardless of whether it is Frankfurt of some other region.

**Comment by josdirksen** [comment]
We see this as well on the S3 Region oregon-west. Doesn't happen that often, though, but regularly enough to be annoying.

**Comment by RichardScothern** [comment]
@josdirksen : Would you be able to test with Registry 2.4 (when it's released?)  The S3 driver should now handle these cases correctly.

**Comment by josdirksen** [comment]
Yes, sure. No problem, I'll keep track of the releases and test with 2.4 once it comes out.

**Comment by jlandersen** [comment]
Hi, we had similar issues with S3 and changed to a different storage. Decided to try again with the 2.4 update, and we continue to receive the following errors on the registry (the client pushing is just retrying over and over), Is this relating to this issue?

`time="2016-04-14T07:02:23Z" level=error msg="response completed with error" err.code="blob unknown" err.detail=sha256:7e08aaf03003c3588cec2f424668f17f796085347c21712ec12abc56cddb439d err.message="blob unknown                                         to registry" go.version=go1.6.1 http.request.host="docker.dev.own.net:5000" http.reque                                            st.id=712f340e-9eee-45e2-a21b-288f364b4e2f http.request.method=HEAD http.request.remoteaddr="10.40.110.6                                            3:55369" http.request.uri="/v2/webgateway/blobs/sha256:7e08aaf03003c3588cec2f424668f17f796085347c21712ec                                            12abc56cddb439d" http.request.useragent="docker/1.11.0 go/go1.5.4 git-commit/4dc5990 kernel/3.13.0-48-ge                                            neric os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.0 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duation=31.393572ms http.response.status=404 http.response.written=157 instance.id=2263c3b0-d8a5-4d05-a2fc-d7bf8762a6e0 vars.digest="sha256:7e08aaf03003c3588cec2f424668f17f796085347c21712ec12abc56cddb439d" vars.name=webgateway version=v2.4.0`

**Comment by josdirksen** [comment]
@jlandersen I don't think it is related to this issue. The issues in this ticket seem to rise from some rate limit stuff from S3, which shows as an 500 in the registry logs.

**Comment by RichardScothern** [comment]
@jlandersen can you file a new issue for this - it's an entirely different situation.

**Comment by jlandersen** [comment]
@RichardScothern sure - I have registered it as #1636 
Thanks!

**Comment by baldzern4** [comment]
Hi,

we are now running Version 2.4 of the registry.
Due to the new S3 backend, the "Slow Down" errors are gone.
 :+1:
Issue can be closed. 
Thanks for the support.

**Comment by kubecto** [comment]
My current practice is to use this site, and then I sync the data to the minio cluster every night
```
mc cp --recursive /home/dockerstore/ shandong/docker-registry >> $LOG_FILE 2>&1

```
