### ISSUE TITLE
Returning 504: unknown error copying into upload: unexpected EOF

### ISSUE THREAD

**Issue by bkeroackdsc** [docker/distribution#775]
I'm running the distribution 2.0.1 image as part of a private Docker registry. The storage backend is S3.

Every push of our application container image is failing with ``FATA[0153] Error pushing to registry: Server error: 504 trying to push dsc_cd/main-site blob - sha256:07fb83b32a7b87c68b380f5298b638dc9546c02c9a2c9e74aef2f3a52a215d5a``.

The registry v2 application logs have these entries:
```
time="2015-07-28T22:03:29.444091882Z" level=error msg="unknown error copying into upload: unexpected EOF" environment=development http.request.host="dreg.shave.io:5000" http.request.id=404ceae5-44a9-4c0a-b735-823d112982a5 http.request.method=PUT http.request.remoteaddr=54.161.48.37 http.request.uri="/v2/dsc_cd/main-site/blobs/uploads/5a4d5478-074f-4f2d-bc34-54936ec67d3b?_state=xobRz50mFMGK2mhwM2IXgwKgC55XOxbkhehsRoWC-ul7Ik5hbWUiOiJkc2NfY2QvbWFpbi1zaXRlIiwiVVVJRCI6IjVhNGQ1NDc4LTA3NGYtNGYyZC1iYzM0LTU0OTM2ZWM2N2QzYiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNS0wNy0yOFQyMjowMjo0Ny4yNjk0OTkxMzNaIn0%3D&digest=sha256%3A871e3c06c4c0ae4dd390686323d000aa17ac3ec22ac3f47b63c61423ebce4b5f" http.request.useragent="docker/1.6.2-circleci go/go1.4.2 git-commit/2f3236d kernel/3.14.28-031428-generic os/linux arch/amd64" instance.id=53119d3e-3606-4ef5-828f-be19a32636cb service=registry vars.name="dsc_cd/main-site" vars.uuid=5a4d5478-074f-4f2d-bc34-54936ec67d3b version=v2.0.1
time="2015-07-28T22:03:29.49327148Z" level=error msg="An error occured" environment=development err.code=UNKNOWN err.detail="unexpected EOF" err.message="unknown error" http.request.host="dreg.shave.io:5000" http.request.id=404ceae5-44a9-4c0a-b735-823d112982a5 http.request.method=PUT http.request.remoteaddr=54.161.48.37 http.request.uri="/v2/dsc_cd/main-site/blobs/uploads/5a4d5478-074f-4f2d-bc34-54936ec67d3b?_state=xobRz50mFMGK2mhwM2IXgwKgC55XOxbkhehsRoWC-ul7Ik5hbWUiOiJkc2NfY2QvbWFpbi1zaXRlIiwiVVVJRCI6IjVhNGQ1NDc4LTA3NGYtNGYyZC1iYzM0LTU0OTM2ZWM2N2QzYiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAxNS0wNy0yOFQyMjowMjo0Ny4yNjk0OTkxMzNaIn0%3D&digest=sha256%3A871e3c06c4c0ae4dd390686323d000aa17ac3ec22ac3f47b63c61423ebce4b5f" http.request.useragent="docker/1.6.2-circleci go/go1.4.2 git-commit/2f3236d kernel/3.14.28-031428-generic os/linux arch/amd64" instance.id=53119d3e-3606-4ef5-828f-be19a32636cb service=registry vars.name="dsc_cd/main-site" vars.uuid=5a4d5478-074f-4f2d-bc34-54936ec67d3b version=v2.0.1
```

The SHA blobs change every time, but I have been unable to completely push any image, even when I implement 10 retries.

Any ideas how to address "unexpected EOF" errors with S3?

**Comment by dmp42** [comment]
@bkeroackdsc can you provide additional informations about your setup?

https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#if-you-have-not-found-an-existing-issue-that-describes-your-problem

Also, can you try pushing manually instead of form circleci?

**Comment by bkeroackdsc** [comment]
I can't reproduce locally via Vagrant. Could this be a Docker 1.6.2 vs 1.7.0 (what I'm running in Vagrant) issue?

**Comment by dmp42** [comment]
Top of the head: circleci might simply have agressive time outs.

Again, I need more infos than that to help you diagnose it (see above).

**Comment by stevvooe** [comment]
@bkeroackdsc Is your registry instance co-located to s3? Part of the problem is the s3 minimum chunk size on low bandwidth links. The default is 10MB. Reducing to 5MB can help with slow links, which typically manifest as this error.

**Comment by bkeroackdsc** [comment]
@stevvooe I tried decreasing the chunk size to 5MB but the errors were still occurring.

I ended up re-implementing our private registry and the backend S3 bucket to AWS us-east-1 (from us-west-2) which is the same region the CircleCI build containers run in. Although I'm still getting the occasional 504, we are now able to successfully push images.

Thanks for everybody's help on this!
