### ISSUE TITLE
Registry Storage uses filesystem although configured for S3

### ISSUE THREAD

**Issue by jtbcgdv** [docker/distribution#778]
I'm running registry:2 in a kubernetes cluster.

I pass these environment variables to the docker container
REGISTRY_LOG_LEVEL=debug
REGISTRY_STORAGE_S3_ACCESSKEY=**ommitted**
REGISTRY_STORAGE_S3_SECRETKEY=**ommitted**
REGISTRY_STORAGE_S3_REGION=eu-west-1
REGISTRY_STORAGE_S3_BUCKET=[bucketname]
REGISTRY_STORAGE_S3_ROOTDIRECTORY=/registry

These is the output of docker inspect

[{
    "AppArmorProfile": "",
    "Args": [
        "cmd/registry/config.yml"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "cmd/registry/config.yml"
        ],
        "CpuShares": 102,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": [
            "registry"
        ],
        "Env": [
            "REGISTRY_LOG_LEVEL=debug",
            "REGISTRY_STORAGE_S3_ACCESSKEY=
            "REGISTRY_STORAGE_S3_SECRETKEY=
            "REGISTRY_STORAGE_S3_REGION=eu-west-1",
            "REGISTRY_STORAGE_S3_BUCKET=
            "REGISTRY_STORAGE_S3_ROOTDIRECTORY=/registry",
            "PATH=/go/bin:/usr/src/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "GOLANG_VERSION=1.4.2",
            "GOPATH=/go/src/github.com/docker/distribution/Godeps/_workspace:/go",
            "DISTRIBUTION_DIR=/go/src/github.com/docker/distribution"
        ],
        "ExposedPorts": {
            "5000/tcp": {}
        },
        "Hostname": "docker-registry-8p5q9",
        "Image": "registry:2",
        "Labels": {
            "io.kubernetes.pod.name": "default/docker-registry-8p5q9"
        },
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": -1,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": null,
        "WorkingDir": "/go/src/github.com/docker/distribution"
    },
    "Created": "2015-07-29T10:43:26.041748128Z",
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "ExecIDs": [
        "b9399e3d0a0a16f6ecd109595edeff10aadc04e02ab8f009b303aec5bcf48142",
        "20df541df66fe237c3c9bcc81f353dcf4ee50e6bfa4b01fd82f3aeee7a99140b"
    ],
    "HostConfig": {
        "Binds": [
            "/var/lib/kubelet/pods/a42b55b6-35de-11e5-ba00-06fb2c2c6b3f/volumes/kubernetes.io~secret/default-token-fu6hf:/var/run/secrets/kubernetes.io/serviceaccount:ro",
            "/var/lib/kubelet/pods/a42b55b6-35de-11e5-ba00-06fb2c2c6b3f/containers/registry/11d6facaf63f5371d83a33f183663b97fa1778b591b99d37c282f0035fa8123d:/dev/termination-log"
        ],
        "CapAdd": null,
        "CapDrop": null,
        "CgroupParent": "docker",
        "ContainerIDFile": "",
        "CpuShares": 102,
        "CpusetCpus": "",
        "Devices": null,
        "Dns": [
            "10.0.0.10",
            "172.20.0.2"
        ],
        "DnsSearch": [
            "default.svc.cluster.local",
            "svc.cluster.local",
            "cluster.local",
            "eu-west-1.compute.internal"
        ],
        "ExtraHosts": null,
        "IpcMode": "container:fed6b8ba1ffd61160636a562795b85cd12b6748576b86796cdc17e7a402ad3a6",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": null,
        "Memory": 0,
        "MemorySwap": -1,
        "NetworkMode": "container:fed6b8ba1ffd61160636a562795b85cd12b6748576b86796cdc17e7a402ad3a6",
        "PidMode": "",
        "PortBindings": null,
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "SecurityOpt": null,
        "Ulimits": null,
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/fed6b8ba1ffd61160636a562795b85cd12b6748576b86796cdc17e7a402ad3a6/hostname",
    "HostsPath": "/var/lib/docker/containers/fed6b8ba1ffd61160636a562795b85cd12b6748576b86796cdc17e7a402ad3a6/hosts",
    "Id": "11d6facaf63f5371d83a33f183663b97fa1778b591b99d37c282f0035fa8123d",
    "Image": "b4ad0b763f116fa6ab967020acceaddcece76a67866bfebf50d624f42f310160",
    "LogPath": "/var/lib/docker/containers/11d6facaf63f5371d83a33f183663b97fa1778b591b99d37c282f0035fa8123d/11d6facaf63f5371d83a33f183663b97fa1778b591b99d37c282f0035fa8123d-json.log",
    "MountLabel": "",
    "Name": "/k8s_registry.ce3930e5_docker-registry-8p5q9_default_a42b55b6-35de-11e5-ba00-06fb2c2c6b3f_85c752b3",
    "NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "PortMapping": null,
        "Ports": null
    },
    "Path": "registry",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/fed6b8ba1ffd61160636a562795b85cd12b6748576b86796cdc17e7a402ad3a6/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 12458,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2015-07-29T10:43:26.12565458Z"
    },
    "Volumes": {
        "/dev/termination-log": "/var/lib/kubelet/pods/a42b55b6-35de-11e5-ba00-06fb2c2c6b3f/containers/registry/11d6facaf63f5371d83a33f183663b97fa1778b591b99d37c282f0035fa8123d",
        "/var/run/secrets/kubernetes.io/serviceaccount": "/var/lib/kubelet/pods/a42b55b6-35de-11e5-ba00-06fb2c2c6b3f/volumes/kubernetes.io~secret/default-token-fu6hf"
    },
    "VolumesRW": {
        "/dev/termination-log": true,
        "/var/run/secrets/kubernetes.io/serviceaccount": false
    }
}
]

**Comment by dmp42** [comment]
This is one of the limitations of our current configuration system IIRC: in that case, you have to feed it a configuration file and cannot define these through environment variables purely.

**Comment by jcderr** [comment]
This should be re-opened, either as a ticket to update the docs to remove references to overriding this via ENV, or as a request to implement this behavior as-documented.

**Comment by dmp42** [comment]
@jcderr shortcomings in the configuration mechanism have been fixed AFAIK.
You should be able to specify that through the ENV.
Furthermore, the doc has been updated already to present both approach (file and ENV).

**Comment by dmp42** [comment]
@jcderr let me know if you still have problem configuring through ENV.

**Comment by jcderr** [comment]
I've been fumbling at this for most of a day now. I'm in a kubernetes pod and here's my env:

    - name: REGISTRY_STORAGE
      value: s3
    - name: REGISTRY_STORAGE_S3_ACCESSKEY
      value: AK[...]
    - name: REGISTRY_STORAGE_S3_SECRETKEY
      value: [...]
    - name: REGISTRY_STORAGE_S3_REGION
      value: us-east-1
    - name: REGISTRY_STORAGE_S3_BUCKET
      value: my-bucket-name
    - name: REGISTRY_STORAGE_S3_ROOTDIRECTORY
      value: /docker

This actually worked just fine before today. We had a failover and the pod redeployed, and now it looks like it might be trying to use `/registry-v2docker` for rootdirectory, but even if i copy my whole repo into that (that path gets created for some reason), curling /v2/_catalog returns an empty set and pulling any of my repos returns 404.

**Comment by jcderr** [comment]
Also, `curl http://our-hostname/v2/_catalog` takes a very long time to return - 30+ seconds - but the registry console doesn't give any obvious errors.

**Comment by jcderr** [comment]
after a ton of troubleshooting and A/B testing, I think something else is up. I'll open another ticket.

**Comment by dmp42** [comment]
@jcderr what version of the registry are you running / were you running?

**Comment by jcderr** [comment]
2.1 -- after all this, i still don't know what's up. I thought maybe I had some IAM profile shenanigans going on, but all seems just fine there after some more testing.

Pulling any of our well-known registries renders 404. Pushing seems to work, the proper folders are created in the bucket, but at the end of pushing the first later, we get a 500 gateway error after a lengthy timeout (the first layer is only ~30kb).

**Comment by jcderr** [comment]
I stepped out for a burger. Steak N Shake took so long, I think they had to slaughter a whole new cow just for me. But when I got back ... everything was working. So ... whatever (╯°□°）╯︵ ┻━┻

**Comment by dmp42** [comment]
Burger vs. Software: 1-0

**Comment by stevvooe** [comment]
I think the (╯°□°）╯︵ ┻━┻ is a desk flip. Were any tables hurt in the fixing of this software?

**Comment by dmp42** [comment]
Let's find out: http://tableflipgifs.tumblr.com/

**Comment by marceldegraaf** [comment]
@dmp42 I'm having this exact same issue with Docker Registry v2.1.1, running the vanilla image with the default config file, adding overrides as `ENV` vars.

Relevant `docker inspect` output for my registry container:

```
"Config": {
    "Hostname": "c806e2bc6051",
    "Domainname": "",
    "User": "",
    "AttachStdin": false,
    "AttachStdout": false,
    "AttachStderr": false,
    "ExposedPorts": {
        "5000/tcp": {}
    },
    "PublishService": "",
    "Tty": false,
    "OpenStdin": false,
    "StdinOnce": false,
    "Env": [
        "REGISTRY_STORAGE_S3_BUCKET=[bucket]",
        "REGISTRY_STORAGE_S3_CHUNKSIZE=10485760",
        "REGISTRY_HTTP_ADDR=:5000",
        "REGISTRY_STORAGE_S3_ROOTDIRECTORY=/docker/registry",
        "REGISTRY_STORAGE_S3_SECURE=true",
        "SERVICE_5000_CHECK_HTTP=/v2/",
        "REGISTRY_LOG_FORMATTER=logstash",
        "REGISTRY_LOG_LEVEL=info",
        "REGISTRY_STORAGE_S3_ENCRYPT=true",
        "REGISTRY_STORAGE_S3_REGION=us-east-1",
        "SERVICE_TAGS=registry",
        "REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=inmemory",
        "REGISTRY_STORAGE_S3_V4AUTH=true",
        "SERVICE_NAME=docker-registry",
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ],
    "Cmd": [
        "/etc/docker/registry/config.yml"
    ],
    "Image": "registry:2",
    "Volumes": {
        "/var/lib/registry": {}
    },
...
```

The container is started without any persistent data volumes, so each time the container restarts I lose all my pushed container images. There are no messages in the logs related to S3.

Should I add my own `config.yml` file, explicitly configuring S3 storage there? Or am I doing something else wrong?

**Comment by dmp42** [comment]
@marceldegraaf `REGISTRY_STORAGE=s3` is likely missing

**Comment by marceldegraaf** [comment]
Ah, right, that was it. The documentation doesn't make it very clear that `REGISTRY_STORAGE` is needed to switch the storage driver.

Thanks!

**Comment by ffedoroff** [comment]
I had a problem when s3 bucket was empty. After I put sample /docker/sample.file into the bucket it starts works for me.
