### ISSUE TITLE
UUID generation in implicit init() causes issues if no /dev/urandom is available

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/distribution#782]
At https://github.com/docker/distribution/blob/b6ec2f2b1096d644be5602a253bb607ee9240c04/context/context.go#L30 a UUID is generated and that requires `/dev/urandom`.

I'm writing some code that runs in a context in which `/dev/urandom` does not exist.  I don't use the distribution code but I use Docker code that has a transitive dependency on this code.  Since /dev/urandom doesn't exist my program panics now even though I don't use the distribution code.  Is it possible to generate this UUID on demand or lazy initialize so that its not in the init() of the package?

**Comment by stevvooe** [comment]
@ibuildthecloud Actually, this only requires `crypto/rand.Reader`. This package goes through a resolution process before falling on `/dev/urandom`.

Unfortunately, adding a `sync.Once` would cause an atomic load on every access of the background context. We could hide this behind access of the ID, which may be read much less often. We may be able to accept a PR along these lines.

We may be looking at the face of a slightly larger problem. Why aren't the `crypto/rand` APIs correctly resolving at startup of a docker container? Why isn't `/dev/urandom` or the linux crypto APIs around? This is going to be more problematic as docker relies more on crypto. The code you're working with now may not rely on secure id generation but in the future this may be critical.

More succinctly, I'd like to better understand why `/dev/urandom` is not available before we start changing code to work around a problem we don't fully understand.

**Comment by ibuildthecloud** [comment]
@stevvooe This is RancherOS.  The init code is ran as PID 1 before anything has been mounted.  So this is the code that mounts `/dev` and makes urandom available or the Linux crypt API (not totally sure how those work.  syscalls?).  So it will be shortly available but not before the main() func is started.

The problem here is that RancherOS is implemented essentially busybox style with one multi-call binary.  So the init code is very small and simple, but it happens to be in a binary that can do a lot of other stuff and because of that other code it has some transitive dependency on `docker/distribution`

**Comment by stevvooe** [comment]
@ibuildthecloud Interesting.

Is there a udev like process running before docker gets PID 1 that could ensure the presence of `/dev/urandom`, or is that taken care of by the docker process?

I still think #786 is fine, but I'm curious.

**Comment by ibuildthecloud** [comment]
Docker launches udev.  I haven't confirmed but I believe devtmpfs creates urandom.  If it doesn't I can create it in the bootstrap code, but I assume it's already taken care of.

**Comment by tiborvass** [comment]
@ibuildthecloud regardless, I personally need your PR for our CI to work ;) would you mind updating it according to @stevvooe's comments?

**Comment by stevvooe** [comment]
@ibuildthecloud Are you seeing an EPERM error is there some other error, like "not found"?

**Comment by ibuildthecloud** [comment]
Sorry guys, I was not available to work on this today but thanks for quickly resolving it!

**Comment by stevvooe** [comment]
@ibuildthecloud No problem.

If you could let us know what the exact error was, it would be very helpful. We don't quite understand the EPERM error and want to see if it is a startup initialization issue or something else. It is possible that the rancher os issue is similar to what is being seen in our CI systems.
