### ISSUE TITLE
Large number of tags?

### ISSUE THREAD

**Issue by ejholmes** [docker/distribution#797]
Is there any technical hard limit on the number of tags? We have a build system that builds an image on every push to github, and tags it with the git commit sha and branch. We've started to notice a significant slowdown when trying to pull an image if the tag doesn't exist; it waits a couple minutes and then eventually fails with:

`FATA[0070] Get https://registry-1.docker.io/v1/repositories/remind101/r101-api/tags: read tcp 54.174.226.171:443: i/o timeout`.

Maybe this is actually a docker/docker issue? Odd that it would list all of the tags.

**Comment by dmp42** [comment]
@ejholmes you apparently are using the python registry:1 (available here: https://github.com/docker/docker-registry).

This here is the golang registry:2 (supporting protocol v2).

Inability to scale on the number of tags is a know defect of registry:1 - it should not be a problem with registry:2.

In summary, I would suggest you give registry:2 a try.

**Comment by ejholmes** [comment]
I should have been more clear. This is against docker hub. I was under the impression that docker hub would use the new docker registry for docker clients >= 1.6. We're seeing this behavior with docker 1.6.2, docker 1.7.0 and the images are been created and pushed with docker 1.6. It is strange that the error message above shows `registry-1.docker.io`.

**Comment by ejholmes** [comment]
Now that I'm looking into it this, does docker hub not actually support registry v2 yet? The docs for this are all over the place:

1. https://docs.docker.com/reference/api/docker-io_api/#repository-authorization suggests that `X-Docker-Endpoints` could contain `registry-2.docker.io`. https://registry-2.docker.io doesn't seem to have anything running.
2. https://docs.docker.com/reference/api/hub_registry_spec/ suggests that `X-Docker-Endpoints` might include `registry2.docker.io`, but again https://registry2.docker.io has nothing running on it.

A few quick tests of `curl -sI -X GET https://registry.hub.docker.com/v1/repositories/library/registry/images -H 'X-Docker-Token: true'` and I never saw `registry-2` or `registry2` in `X-Docker-Endpoints` for any repositories I tested, including private.

**Comment by ejholmes** [comment]
Ok, so I think I tracked down why this happens. Docker hub does indeed support v2 at /v2. The problem is that the docker client seems to fallback to v1 if the tag isn't found in the v2 registry:

```
time="2015-07-31T05:45:44Z" level=debug msg="image does not exist on v2 registry, falling back to v1"
```

I don't suppose there's a way to disable this behavior? It's not really desirable in instances like this.

**Comment by dmp42** [comment]
Correct:
Hub does definitely support both v2 and v1.
The engine will first try v2, then fallback to v1 if there is any error with v2 (including 404).

The urls are:
- https://registry-1.docker.io/v1
- https://registry-1.docker.io/v2

The solution to avoid v1 should be to push your images using docker>=1.6.0.
Would that work in your case?

**Comment by ejholmes** [comment]
We're actually already building these images with docker 1.6 but I think there was a period of time where they were being built with docker 1.4. Maybe the tags in the v1 registry for this repository are old tags during that time?

Either way, thanks for the help!

**Comment by dmp42** [comment]
@ejholmes we can discuss this further over irc (#docker-distribution) - github is not really convenient for fast chit chat - you will find the usual suspects over there (rscothern, aaronl, stevvooe).

Bottom-line: yeah, moving to v2 in your case likely means migrating older tags to avoid this problem. That should be as simple as docker pull foo:tag && docker push foo:tag. You could also look a bit into https://github.com/docker/migrator .
And/or manually delete old tags.
