### ISSUE TITLE
Redirect support in Swift driver

### ISSUE THREAD

**Issue by gschukin** [docker/distribution#800]
Currently registry is serving content directly in case SWIFT is used as storage.

It will be nice if Swift driver can utilize tempUrl functionaly to offload the download to Swift directly.

**Comment by RichardScothern** [comment]
@lebauce what do you think?

**Comment by lebauce** [comment]
Agreed. This was not part of the original pull request as I couldn't make it work on my setup.
I'm planning to make an other try soon, probably in the 1 or 2 weeks.

**Comment by RichardScothern** [comment]
@lebauce thanks.  Looking forward to it.

**Comment by lebauce** [comment]
@gschukin @RichardScothern I just pushed a branch that implements the features

Newer versions of Swift allow to set two extra secret keys per container when older versions only allowed to set secret keys per account. I couldn't find a way to detect if per container secret keys are supported, so only per account secret keys are supported.

What do you think ?

**Comment by gschukin** [comment]
@lebauce according to the Swift documentation there is no difference between account or container secret keys as signature is checked against all four keys.

**Comment by lebauce** [comment]
@gschukin Unfortunately, it was not the case in Icehouse and prior versions of Openstack

**Comment by gschukin** [comment]
@lebauce is it reasonable to fetch keys from account metadata? I think storing temp-URL-key in configuration file will give better flexibility.

What do you think?

**Comment by lebauce** [comment]
@gschukin One solution would be to set the account secret key with a POST request if it is specified in the configuration file or fetch it from account metadata otherwise

**Comment by stevvooe** [comment]
@gschukin @lebauce There is already an hmac secret shipped with each registry. We consider it a "cluster" secret, meaning all the registry instances operating in a cluster should share it. You may want to consider that as an option if all that is needed is an hmac.

**Comment by lebauce** [comment]
@stevvooe Yes, all that is needed is an hmac. I guess you are talking about the `Config.HTTP.Secret` key right ? However I couldn't find a way to use it from the driver

**Comment by stevvooe** [comment]
@lebauce `URLFor` takes a parameter map. We could consider adding `hmac` (or better yet, a `crypto.Signer`) as a parameter, as long as we can agree that this can be consistently used across drivers.

**Comment by lebauce** [comment]
@stevvooe That would be nice. For now, the library used by the Azure, S3 and Swift internally creates their own `hmac` object so they must be modified so that we can pass them an existing one.

@ahmetalpbalkan @AndreyKostov @BrianBland  What do you think ?

**Comment by ahmetalpbalkan** [comment]
@lebauce azure does not create an internal hmac object. The URL signing we have is based on url+date+storage service access key.

**Comment by dmp42** [comment]
@lebauce ping

**Comment by lebauce** [comment]
@dmp42 I pushed a new version of the branch. It tested it against a public Swift instance. It also includes compatibility with HP Cloud. It was also tested by @lcarstensen (see https://github.com/lebauce/distribution/pull/2).

I just created a pull request for it.
