### ISSUE TITLE
CI does not catch some vet errors

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#807]
See #803

**Comment by aaronlehmann** [comment]
We're hitting this issue: https://github.com/golang/go/issues/9439

    ubuntu@box27:~/.gvm/pkgsets/stable/global/src/github.com/docker/distribution$ go tool vet -v registry/storage/blob_test.go 
    vet: registry/storage/blob_test.go:12:2: could not import github.com/docker/distribution (can't find import: github.com/docker/distribution)
    Checking file registry/storage/blob_test.go
    ubuntu@box27:~/.gvm/pkgsets/stable/global/src/github.com/docker/distribution$ godep go install ./...
    ubuntu@box27:~/.gvm/pkgsets/stable/global/src/github.com/docker/distribution$ go tool vet -v registry/storage/blob_test.go 
    vet: registry/storage/blob_test.go:36:14: undeclared name: NewRegistryWithDriver
    Checking file registry/storage/blob_test.go

Let's add `godep go install ./...` before `go vet` to work around it.

**Comment by dmp42** [comment]
@aaronlehmann any idea if this is still true with go1.5/1.6 ?

**Comment by aaronlehmann** [comment]
@dmp42: I believe it is still true with Go 1.5. We hit the same issue in docker/docker, and I believe it was after that project upgraded to Go 1.5. Not sure about Go 1.6, but haven't heard anything about it being fixed.

**Comment by dmp42** [comment]
@dgageot see this thread ^
This is why I initially introduced a dependency on `build` for the `vet` task in machine's makefile.

We may want to check that what we have now does work as intended.
