### ISSUE TITLE
V1 and V2 compose configuration

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#82]
Create a fig configuration for running a v1 and v2 registry behind nginx.

- Nginx dockerfile and configuration (or use volume)
- V1 docker instance (registry:latest) and link
- V2 docker instance (??) and link

**Comment by stevvooe** [comment]
@dmcgowan Status?

**Comment by dmcgowan** [comment]
Going to switch it back to TODO, fixes for 1.5 took precedent

**Comment by stevvooe** [comment]
@dmcgowan Is this done?

**Comment by dmcgowan** [comment]
Yes this has been checked in, forgot to link the PR
