### ISSUE TITLE
Registry configuration options for mirror mode

### ISSUE THREAD

**Issue by koyadume** [docker/distribution#820]
[This](https://docs.docker.com/articles/registry_mirror/) page describes how one can use local registry as mirror. It says that one need to use ```STANDALONE```, ```MIRROR_SOURCE``` and ```MIRROR_SOURCE_INDEX``` options for this purpose.

```
docker run -p 5000:5000 \
    -e STANDALONE=false \
    -e MIRROR_SOURCE=https://registry-1.docker.io \
    -e MIRROR_SOURCE_INDEX=https://index.docker.io \
    registry
```

But on [this](https://docs.docker.com/registry/configuration/) page, it has been mentioned that a configuration option should be in ```REGISTRY_variable``` format and it does not mention anything about any of the three configuration options mentioned for local registry mirror.

**Comment by RichardScothern** [comment]
Hi @koyadume .  Your first link refers to the v1 registry, while the second is configuring a v2 registry.  I realize it's confusing as they are not actually labelled as such.

**Comment by koyadume** [comment]
Thank you @RichardScothern for clarification. In that case what are the configuration options for v2 registry for running it as mirror?

**Comment by emilsoman** [comment]
@RichardScothern I'm also confused by these 2 sources. Can you answer @koyadume 's question ? Thanks.

**Comment by emilsoman** [comment]
@koyadume I can confirm that https://github.com/docker/distribution/pull/779#issuecomment-130261795 works for running v2 registry as mirror.
