### ISSUE TITLE
Is docker search API implemented in 2.1.0-rc.0?

### ISSUE THREAD

**Issue by sourav82** [docker/distribution#825]
Could you please let me know if searching registry is implemented in 2.1.0-rc.0 release? Any references/documentation will be helpful.

**Comment by dmp42** [comment]
You will find information here: https://github.com/docker/distribution/blob/master/ROADMAP.md#indexing-search-and-discovery

If you want raw listing of content, use the catalog API.

If you want to implement search, you can do it on top of the notification and/or catalog API.

`docker search` itself is not part of v2 yet.
