### ISSUE TITLE
Document V1 and V2 setup

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#83]
Add documentation for setting up a V1 and V2 registry behind a proxy such as nginx.  In addition provide example configurations for nginx.

**Comment by stevvooe** [comment]
@dmcgowan Is this done?

**Comment by dmcgowan** [comment]
Documentation has been added to the deploying section for setting up nginx to proxy to both v1 and v2.  If further documentation is needed for different configurations, we should create a new issue.
