### ISSUE TITLE
Add mirror support to engine

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#84]
Add support for mirrors in the engine.  This would allow the engine to use a proxy-cache when contacting a v2 registry.

Connects to #19.

See https://github.com/docker/docker/pull/10201

**Comment by stevvooe** [comment]
Duplicates #19. Please re-open, if I'm wrong.

**Comment by stevvooe** [comment]
cc @RichardScothern

**Comment by stevvooe** [comment]
@RichardScothern What should we do with this issue? We are still missing mirror support for private registries, if I understand correctly. This may be covered be another issue in docker/docker.

**Comment by RichardScothern** [comment]
Let's close this in favor of a more specific PR enumerating what we need to fill in the missing functionality.
