### ISSUE TITLE
Need health check endpoint not protected by auth

### ISSUE THREAD

**Issue by ghaering** [docker/distribution#840]
When I tried the HEAD version with http basic auth support, I noticed that everything is protected by auth. When I want to deploy the Docker registry behind a load balanced like ELB, however, I need a health check URL that works without auth.

Could you please implement one before you release the http basic auth feature?

**Comment by dmp42** [comment]
You should look at the debug endpoint:

https://github.com/docker/distribution/blob/master/docs/configuration.md#debug

Now, it will expose possibly sensitive information, so you certainly want to restrict access it in some way. 

Let me know if that helps.

**Comment by ghaering** [comment]
Thanks, but that does not cut it. AWS Elastic Loadbalancers need to have the healthcheck URL on the balanced backend HTTP servers. They may not be on a different port. Also there is no way to not expose the health check URL to the internet, apart from security-by-obscurity.

**Comment by dmp42** [comment]
Thanks for the feedback @ghaering 
I'm reopening this and we will look into this.

**Comment by stevvooe** [comment]
@ghaering Unfortunately, ELBs assumptions are completely broken. A 401 is a very healthy response for a properly secured registry. If `/v2/` stops serving a 401 without authentication, the server should be removed from the pool, as may be compromised or misconfigured.

I've submitted https://github.com/docker/distribution/pull/874 to address this.
