### ISSUE TITLE
Not able to list repositories over TLS

### ISSUE THREAD

**Issue by sourav82** [docker/distribution#841]
After enabling TLS in registry v2.1, I'm not able to get list of repositories using catalog API.

I'm trying below request - 

 curl -k -u user:password https://10.242.138.105:6000/v2/_catalog

I'm getting below message -
```json
{"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":[{"Type":"registry","Name":"catalog","Action":"*"}]}]}
```
Without TLS, I'm getting proper response. Even I'm not getting any request to authorization service URL.

**Comment by dmp42** [comment]
@sourav82 are you using nginx for authentication?
Or the registry basic auth feature?
How did you generate the password file?

**Comment by sourav82** [comment]
@dmp42, I'm using token auth and started the registry service as below 

```bash
docker run --name registry-2.1.0 -d -v /EBS/registry-config/config.yml:/go/src/github.com/docker/distribution/cmd/registry/config.yml -v /EBS/registry-2.1.0:/var/lib/registry -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry -e REGISTRY_AUTH=token -e REGISTRY_AUTH_TOKEN_REALM=http://10.227.88.6:8080/oauth-0.0.1-SNAPSHOT -e REGISTRY_AUTH_TOKEN_SERVICE="registry-2.1.0" -e REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/server.crt -e REGISTRY_AUTH_TOKEN_ISSUER="10.227.88.6" -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -v /root/certs:/ssl -v /EBS/registry-2.1.0:/var/lib/registry -v /certs/v2:/certs -p 6000:5000 --restart=always distribution/registry:2.1.0-rc.0
```
The authentication endpoint authenticates user using basic ldap authentication. Pushing and pulling images working well. I'm getting below request in the authentication endpoint -

```bash
http://10.227.88.6:8080/oauth-0.0.1-SNAPSHOT?account=test&scope=repository%3Adistribution%2Fregistry%3Apull%2Cpush&service=registry-2.1.0
```

But catalog API fails as mentioned above.

**Comment by dmp42** [comment]
@sourav82 what token server are you using?

**Comment by sourav82** [comment]
@dmp42, it is a web service (jax-rs) which implements token generation using JWT framework (com.nimbusds.jwt). The API serving the token generation is as below -
```code
   @GET
    public Response getToken(@DefaultValue("")@QueryParam("account") String account, @QueryParam("scope") String scope, @QueryParam("service") String service, @Context HttpHeaders httpHeaders, @Context HttpServletRequest request) {...}
```
The context root is "/" for the REST invocation. I'm fetching the base64 encoded user credential from HTTP "Authorization" header of the request and generating the token if the user is authorized for the particular action (in scope parameter) on that resource (repository).

**Comment by dmp42** [comment]
@sourav82 the registry error message might suggest the token is not valid.
It's hard for me to debug on this without this token service (I'm not familiar with it).

It's bizarre that TLS would make any difference here...

@pdevine / @sday any idea?

**Comment by sourav82** [comment]
@dmp42, well, I could understand the problem. Actually I was using "curl" to the catalog API. It returns 401 unauthorized with HTTP header "WWW-Authenticate" having service and scope as parameter to auth service URL.

Now, I need to call the authentication service URL using scope and service parameter to get the token myself. Next, using that token in the HTTP "Authorization" header I need to call catalog API once again to list the repositories. In this step it is successful as it has valid token.

Docker client does all these in push/pull. But as it is manual (no docker search support), we need to do those steps ourselves. Also, I confirm it is not a TLS problem, same for without TLS. Thanks for the help.
