### ISSUE TITLE
Do we need a gotcha document?

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#844]
As far as I know, 2.1 introduces some possibly "breaking" changes for the users:

 * location of the config file inside the official image
 * shared secret generation
 * any other?

Should we have a document somewhere to keep track of that for users upgrading? Maybe as part of the changelog?

**Comment by dmp42** [comment]
After some discussion, it seems the release notes are a good place for that.

**Comment by dmp42** [comment]
+ some comment about the base image being different

**Comment by dmp42** [comment]
cc @bcwalrus @marcusmartins

**Comment by dmp42** [comment]
Might add notes about deprecation of the size field in notifications ( https://github.com/docker/distribution/commit/26b7fe4a9161bc99b43a398f275b1e460449ca34 )

**Comment by RichardScothern** [comment]
Added to release notes: https://docs.google.com/document/d/1ZrlatwhF8Bcy-1EXJwlYi7SqLKwx-J10wlMiG350hoQ/edit#

ping @dmp42

**Comment by RichardScothern** [comment]
Is there a better name than 'gotchas' for that section?

**Comment by RichardScothern** [comment]
Gotchas added to release notes.
