### ISSUE TITLE
Metadata endpoint support in engine

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#85]
Update the engine registry client to use the new metadata endpoint specification. This allows for simplifying the engine-side logic for configuring the registry endpoints.

See #80 for specification

**Comment by stevvooe** [comment]
@dmcgowan Are we still planning to do this?

**Comment by dmcgowan** [comment]
Yes, I plan on adding the specification to the namespace discovery conversation. I am holding up on further development until we have a more complete namespace specification.

**Comment by stevvooe** [comment]
We are probably going a very different direction here.
