### ISSUE TITLE
Provide Apache proxy working example 

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#855]
Lots of people want LDAP backends, and rely on a proxy design.
I wish we had a reference Apache config alongside the nginx example (in `nginx.md`) so we can get rid of the burden answering people in that setup.

**Comment by thaJeztah** [comment]
Think this one could be added to the list in https://github.com/docker/distribution/issues/879 ?

**Comment by RichardScothern** [comment]
+1 this could be a recipe
