### ISSUE TITLE
docker pull/push can work, but curl return 404. 

### ISSUE THREAD

**Issue by qq690388648** [docker/distribution#857]
Hello, I have built a docker registry following https://docs.docker.com/registry/deploying/ and the docker pull/push can work.
Now I need to query all of the images in the docker registry, and I found the  HTTP api in  https://docs.docker.com/registry/spec/api/
When I typed:<code>curl http://docker.registry:5000/v2/</code>(the docker.registry is the hostname of my docker registry), it just returned <code>{}</code>.
When I typed:<code>curl http://docker.registry:5000/v2/_catalog</code>, it returned <code>404 page not found</code>.
The docker registry version message is below:
```
kubernetes@docker:~$ docker exec 860d69cd9110 registry --version
registry github.com/docker/distribution v2.0.1
```
Is there anything wrong in my operation?

**Comment by Trefex** [comment]
@qq690388648 _catalog is only available on 2.1. That should be your problem.

**Comment by qq690388648** [comment]
Oh, thank you, I will try 2.1 now..
@Trefex

**Comment by qq690388648** [comment]
Thank you very much, I change the registry to 2.1 and everything works well.
@Trefex
