### ISSUE TITLE
Is the Catalog stateful in Docker Registry 2.1?

### ISSUE THREAD

**Issue by clemenko** [docker/distribution#859]
It appears that the catalog does update on restart of the registry container. 
Recreate : 
```
docker run -d -p 5000:5000 -v /tmp/docker-registry:/tmp/registry-dev -v /opt/docker-registry/:/var/lib/docker-registry/ registry:2.1
docker push localhost:5000/alpine
curl localhost:5000/v2/_catalog
docker stop ...

#restart the container
docker run -d -p 5000:5000 -v /tmp/docker-registry:/tmp/registry-dev -v /opt/docker-registry/:/var/lib/docker-registry/ registry:2.1
curl localhost:5000/v2/_catalog
#output : 
{"repositories":[]}
```
I can see that the image is there : 
```
ls -asl /opt/docker-registry/docker/registry/v2/repositories/alpine/
```
It appears that the images located in the directory are not loaded. 
Am I doing something wrong?

**Comment by dmp42** [comment]
ping @pdevine

**Comment by pdevine** [comment]
@clemenko there's no state with the catalog endpoint.  It walks each of the directories every time you hit it.  Is it possible for you to paste the output of ls -asl, preferably from inside the container where it's being served?  Also, what was the output of the initial time you hit the endpoint?

**Comment by clemenko** [comment]
@pdevine This appears to be related to #861 . I tested with 2.1.1 and it appears to be fixed.

**Comment by stevvooe** [comment]
@clemenko Partially, but it may also be due where the volumes are mounted. The config for 2.1 file writes to `/var/lib/registry` by default. Looking at the command, this is not mounted as a volume. When you restart the container, unless you use the container id, the data will be gone.
