### ISSUE TITLE
Auth error when trying to use Basic Native auth

### ISSUE THREAD

**Issue by jasonf20** [docker/distribution#860]
Hello, Im using docker version 1.7.1 and docker registry image 2.1.

I have set up Basic Native auth as the docs state but keep getting this at login: Error response from daemon: no successful auth challenge for https://localhost:5000/v2/ - errors: []

I have set up TLS and it works fine without the auth. But the auth does not seem to work

**Comment by Trefex** [comment]
From IRC: 

Docker compose file used: http://pastebin.com/KYaMa49E

docker logs registry http://pastebin.com/rxPN3BDr

**Comment by dmp42** [comment]
You are likely missing an entry in your compose file:

`REGISTRY_AUTH: htpasswd`

The documentation was faulty, and has now been fixed.

**Comment by jasonf20** [comment]
@dmp42 It works. Thanks.
