### ISSUE TITLE
Upgrading from registry 2.0 to 2.1

### ISSUE THREAD

**Issue by mariolameiras** [docker/distribution#861]
I've installed a new registry (v2.1) using the container available here: https://hub.docker.com/_/registry/

Pointing REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY to the same filesystem path where I previously had registry 2.0.

Now i can't pull the existing images even though they appear on /v2/_catalog listed.

I get the following error:

Pulling repository registry:5100/tomcat8-oraclejdk8-debian
Error: image tomcat8-oraclejdk8-debian:8.0.24 not found

If I push the image again, all the layers already exist in the registry, the image is updated and I can already pull it to my local machine.

Is there any way to update the images in the new registry version without having to push them all again ?

Thank you.

**Comment by dmp42** [comment]
Hi @mariolameiras 

There should be no migration needed.
I would need more information.

Can I ask for the following? 

https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#if-you-have-not-found-an-existing-issue-that-describes-your-problem

Specifically useful would be the registry logs at the moment you try to pull the image and get a 404 back.

Thanks.

**Comment by RichardScothern** [comment]
> If I push the image again, all the layers already exist in the registry, the image is updated and I can already pull it to my local machine.

When you repush these images do they appear in the same directory locations as they were originally?

**Comment by gizmonicus** [comment]
I am having the same issue with the registry. What's interesting is that using curl, I can query my registry and get results back, curl https://my.docker.host:5000/v2/_catalog returns a list of all my repositories.

The 404 error is returning MANIFEST_UNKNOWN. Here is the output of curl https://my.docker.host:5000/v2/gentoo/manifests/master:

{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Name":"gentoo","Revision":"sha256:1305cff6f889226e31078dda3e9afd7060ca1741b9a5ebaff7f52d76518b8b08"}}]}

Here is the paste from my error logs. I've censored domain name and IP (I think I got everything). Let me know if you would prefer a different format.
http://pastebin.com/g1BdU7NW

**Comment by dmp42** [comment]
@mariolameiras @gizmonicus Thanks a lot for the info.
We are looking into it.

**Comment by gizmonicus** [comment]
I am going to rebuild my registry so I can continue to push/pull from it. However, I am keeping the old directory around so I can test after this has been resolved.

**Comment by dmp42** [comment]
@gizmonicus we have a fix under review: #864

Short term workaround: downgrade to registry 2.0.1 and your data will be there.

**Comment by gizmonicus** [comment]
@dmp42 thank you for the workaround. I am OK with rebuilding my registry; I didn't have many images and I needed to do some cleanup anyway.

**Comment by dmp42** [comment]
There: we shipped a new registry (2.1.1).
Please upgrade ASAP to get that fix.

**Comment by mariolameiras** [comment]
Upgraded to 2.1.1 and it fixed my problem.

Thank you !

**Comment by RichardScothern** [comment]
:cake:

**Comment by davelesser** [comment]
I'm still running running into the `MANIFEST_UNKNOWN` issue when running registry 2.1.1 (using S3 for persistence).

I'm able to successfully pull an image using 2.0.1, but when running 2.1.1, I get the following:

```
$ docker pull <REDACTED>/hubot
Pulling repository <REDACTED>/hubot
Error: image hubot:latest not found
```

Here are logs from the registry (linked to the line with error message):
https://gist.github.com/davelesser/f9ef0e530d0e01d0e500#file-registry_2_1_1-log-L24

I'm not sure if this is the same issue that was meant to be fixed in #864, or if this is a different issue. Thoughts?

**Comment by dmp42** [comment]
@davelesser can you copy the registry debug logs for 2.0.1 when successfully pulling that image?

Thanks.

**Comment by stevvooe** [comment]
@davelesser This is unlikely to be the same issue. Please file another issue.

In the future, please err on the side of filing a new issue referencing another issue rather than commenting on closed issues.

**Comment by dmp42** [comment]
@davelesser also since this one is closed and others validated it, you should really open a new ticket

**Comment by davelesser** [comment]
@stevvooe, thank you for the guidance; I'll do that in the future.

@dmp42, I'm opening a new ticket now.

**Comment by deviscalio** [comment]
I have a docker registry version 2.0.1. When I upgrade lost images like people below. Is there a way to upgrade?
