### ISSUE TITLE
V2 mirror registry [private proxy] does not work properly

### ISSUE THREAD

**Issue by dalanlan** [docker/distribution#868]
###Use case
I own a cluster which cannot access the internet, in which case it wont be able to pull images directly.
Hence a mirror registry would help much here. 
The target private registry is https://gcr.io.

###Settings for the machine acting as the mirror registry
node IP: 10.10.105.113 here (Used lated. Just in case)
Set the configuration basically following [this comment](https://github.com/docker/distribution/pull/779#issuecomment-130261795). 

```
version: 0.1
log:
  level: info
storage:
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    secret:  *<removed>*
proxy:
  remoteurl: https://gcr.io
```
The secret is the correponding auth info when `docker login https://gcr.io`(located in $HOME/.docker/config.json)

###DOCKER_OPTS of the machine which does the pulling job
```
DOCKER_OPTS="-H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock --registry-mirror=http://10.10.105.113:5000 --bip=172.16.23.1/24 --mtu=1472 --insecure-registry localhost:5000"
```

###Problem
The working machine still pulls the image (gcr.io/google_containers/etcd:2.0.12, for example) from https://gcr.io instead of mirror registry. 
```
$ docker pull gcr.io/google_containers/etcd:2.0.12
Error response from daemon: invalid registry endpoint https://gcr.io/v0/: unable to ping registry endpoint https://gcr.io/v0/
v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp 74.125.200.82:443: i/o timeout
 v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp 74.125.68.82:443: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry gcr.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/gcr.io/ca.crt
 ```

Did I miss anything? /cc @RichardScothern

**Comment by nathanleiby** [comment]
@dalanlan what version of Docker are you running? And did you see this related issue: https://github.com/docker/distribution/issues/824

**Comment by RichardScothern** [comment]
hi @dalanlan  Right now, mirroring only supports the hub - not private registries

**Comment by stevvooe** [comment]
@RichardScothern @dalanlan Expanding on "only supports the hub" -- this is due to the way v1 supported mirroring.

I would also note that gcr only supports v1, which is not supported by v2 proxy caching.

**Comment by dalanlan** [comment]
lc.
Closing it for now.
