### ISSUE TITLE
Error on Check Registry Connection

### ISSUE THREAD

**Issue by xiekeyang** [docker/distribution#87]
I check Registry V2 API.
cmd: curl -X GET -k http://myregistry:port/v2/
response: {}
container logs: "GET /v2/ HTTP/1.1" 200 2 "" "curl/7.35.0"
I'm not sure if it is correct.

However, error response happens,
cmd: curl -X GET -k http://myregistry:port/v2/_ping
response: 404 page not found
container logs: "GET /v2/_ping HTTP/1.1" 404 19 "" "curl/7.35.0"

If I use wrong command, or I misunderstand API SPEC?
thanks a lot!

**Comment by dmp42** [comment]
The (on-going effort on the) documentation for v2 is here: https://github.com/docker/distribution/blob/master/doc/SPEC.md
Note that v2 is still work in progress.

If you want to use the documented, battle-tested registry, please stick with v1: https://github.com/docker/docker-registry/

**Comment by stevvooe** [comment]
@xiekeyang "/v2/_ping" is not a supported endpoint in the version 2 protocol. The "ping" endpoint, is now just "/v2/".
