### ISSUE TITLE
Publish RPMs to docker yum repo

### ISSUE THREAD

**Issue by mindscratch** [docker/distribution#871]
It would be great if other rpms could be published to the docker [yum repo](http://yum.dockerproject.org/), such as the registry.

**Comment by dmp42** [comment]
Hi @mindscratch 

I think this was discussed earlier with a CentOS maintainer but I couldn't find where now.

Bottom-line:

We are not committed to provide and maintain such distro specific packages, for a couple of reasons:
  * the recommended way to use the registry is as a docker image
  * maintaining compatibility for a bunch of distros / versions brings back a huge maintenance burden that the purpose of Docker itself is to relieve - thus somewhat defeat the purpose
  * we don't want to support too many different golang versions
  * we don't feel like we have the expertise or bandwidth to take it on us to maintain these packages

That being said:

 * we are more than willing to accept community contributions providing that, for example in the `contrib` folder
 * we want to make the life of distro maintainers as easy as possible, and if they have specific issues while building packages, we would absolutely try to fix them

So, while it's unlikely we will ever publish rpms packages for the registry ourselves, the door is not entirely closed here :)
