### ISSUE TITLE
Provide Access to /v2/_catalog without Auth

### ISSUE THREAD

**Issue by Telmo** [docker/distribution#877]
After enabling user auth for v2.1 I've noticed that all API calls now require an authorized user. Is it possible to exclude certain API methods from the auth? Specifically the one that list images/tags in the registry

```
[user@docker-as-1p registry]# curl http://localhost:5000/v2/_catalog
{"errors":
  [
    {
      "code":"UNAUTHORIZED",
      "message":"access to the requested resource is not authorized",
      "detail":[
        {
          "Type":"registry",
          "Name":"catalog",
          "Action":"*"
        }]
    }
  ]
}
[user@docker-as-1p registry]#

```

one with the headers:

```
[user@docker-as-1p registry]# curl -Is http://localhost:5000/v2/_catalog
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="http://registryauth:9000/authorize",service="Docker Registry",scope="registry:catalog:*"
Date: Fri, 14 Aug 2015 12:18:25 GMT
Content-Length: 161
```

**Comment by stevvooe** [comment]
@Telmo As a policy, all protected endpoints are protected by the authentication backend. There are no exceptions to this.

If you'd like to expose this freely, just have your authentication system issue a token without providing authentication credentials.
