### ISSUE TITLE
Support for layer federation

### ISSUE THREAD

**Issue by ncdc** [docker/distribution#88]
The registry should be able to serve some layers from a different server, if directed to do so. For example, an ISV builds on a Red Hat base image. The ISV layers are served from `cdn.isv.com` and the Red Hat layers are served from `cdn.redhat.com`.

Please see https://github.com/docker/docker-registry/issues/662 for some background information on this issue.

### Pull

When pulling the layers associated with an image manifest, there should be enough information in the manifest to indicate the specific URL for each layer. For example:

```
$ docker pull isv/app
bef54b8f8a2f <- served from cdn.redhat.com
8da983e1fdd5 <- served from cdn.isv.com
```

### Push

When pushing an image manifest, there should be some way to indicate different URLs for different layers. If you previously pulled a manifest with that information, it must be retained. It should also be possible to create a new manifest and alter the URL of certain layers. When pushing a layer whose URL differs from that of the registry, the registry should store the metadata about the layer, but the actual content of the layer would not be transmitted (it is assumed to already exist at the specified URL).

**Comment by kargakis** [comment]
Which may be the best place for this metadata to exist? We discussed yesterday with @miminar the possibility of having it as part of History for schema v1 manifests but that's a hack. 

Two naive question: 
1) Can we support optional fields in manifests?
2) If we can, I guess the **addition** of a new optional field in the schema (regardless of version) wouldn't be considered as a breaking change, right?

The discussion linked by @ncdc hints that the manifest is not the place for storing such info but I am not sure if it's still relevant as it is a bit old in internet years. :)

**Comment by runcom** [comment]
@aaronlehmann @stevvooe I think this can be closed now that the manifest has _urls_ - docker cli side is being worked on in the engine

**Comment by stevvooe** [comment]
@runcom LGTM
