### ISSUE TITLE
Docker 1.8.1 pull image failed from Registry 2.1.1 with auth service 

### ISSUE THREAD

**Issue by oilbeater** [docker/distribution#882]
Before upgrade to 2.1.1 I have a registry 2.0.1 with auth service and a lot of images has been pushed by engine 1.6.0.

Now I upgrade the registry to 2.1.1 with same s3 bucket as storage backend and upgrade engine to 1.8.1. Then I pulled an image already exists in registry 

    $ docker pull index.registry.io/library/ubuntu
    Using default tag: latest
    Pulling repository index.registry.io/library/debian 
    Error: image library/debian:latest not found

However when I changed engine to 1.7 and 1.6,  all works well.

The registry logs is here

    {"log":"time=\"2015-08-17T04:49:01.662509793Z\" level=debug msg=\"authorizing request\" environment=development http.request.host=index.alauda.io http.request.id=45bdfc33-9f57-4baa-8b68-77f90591123c http.request.method=GET http.request.remoteaddr=54.186.86.199 http.request.uri=\"/v2/\" http.request.useragent=\"docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-61-generic os/linux arch/amd64\" instance.id=d6001a7d-5591-4a3a-b92c-859cd0bff5e8 service=registry version=v2.1.1 \n","stream":"stdout","time":"2015-08-17T04:49:01.662602139Z"}
    {"log":"time=\"2015-08-17T04:49:01.662991156Z\" level=warning msg=\"error authorizing context: authorization token required\" environment=development http.request.host=index.alauda.io http.request.id=45bdfc33-9f57-4baa-8b68-77f90591123c http.request.method=GET http.request.remoteaddr=54.186.86.199 http.request.uri=\"/v2/\" http.request.useragent=\"docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-61-generic os/linux arch/amd64\" instance.id=d6001a7d-5591-4a3a-b92c-859cd0bff5e8 service=registry version=v2.1.1 \n","stream":"stdout","time":"2015-08-17T04:49:01.663031222Z"}
    {"log":"172.31.0.230 - - [17/Aug/2015:04:49:01 +0000] \"GET /v2/ HTTP/1.1\" 401 114 \"\" \"docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-61-generic os/linux arch/amd64\"\n","stream":"stdout","time":"2015-08-17T04:49:01.663259933Z"}
    {"log":"time=\"2015-08-17T04:49:01.929582117Z\" level=debug msg=\"authorizing request\" environment=development http.request.host=index.alauda.io http.request.id=cc6a18d0-7674-45d9-879f-49b383c9bf28 http.request.method=GET http.request.remoteaddr=54.186.86.199 http.request.uri=\"/v2/\" http.request.useragent=\"docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-61-generic os/linux arch/amd64\" instance.id=d6001a7d-5591-4a3a-b92c-859cd0bff5e8 service=registry version=v2.1.1 \n","stream":"stdout","time":"2015-08-17T04:49:01.929642181Z"}
    {"log":"time=\"2015-08-17T04:49:01.929947752Z\" level=warning msg=\"error authorizing context: authorization token required\" environment=development http.request.host=index.alauda.io http.request.id=cc6a18d0-7674-45d9-879f-49b383c9bf28 http.request.method=GET http.request.remoteaddr=54.186.86.199 http.request.uri=\"/v2/\" http.request.useragent=\"docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-61-generic os/linux arch/amd64\" instance.id=d6001a7d-5591-4a3a-b92c-859cd0bff5e8 service=registry version=v2.1.1 \n","stream":"stdout","time":"2015-08-17T04:49:01.929989833Z"}
    {"log":"172.31.43.0 - - [17/Aug/2015:04:49:01 +0000] \"GET /v2/ HTTP/1.1\" 401 114 \"\" \"docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-61-generic os/linux arch/amd64\"\n","stream":"stdout","time":"2015-08-17T04:49:01.930177444Z"}

Engine info is attached below. I wonder if there is some change in the auth mechanism implementation in engine side leads to this.

    $ docker version
    Client:
     Version:      1.8.1
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   d12ea79
     Built:        Thu Aug 13 02:35:49 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.8.1
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   d12ea79
     Built:        Thu Aug 13 02:35:49 UTC 2015
     OS/Arch:      linux/amd64

**Comment by dmp42** [comment]
What kind of "auth service" are you using?

**Comment by oilbeater** [comment]
@dmp42 We implement a  token serve to control the access of registry

**Comment by dmp42** [comment]
@oilbeater can you investigate that home grown service then?
Your registry logs are screaming about an error there.

**Comment by oilbeater** [comment]
@dmp42 I might find out the reason. As [#15640](https://github.com/docker/docker/issues/15640) mentioned, docker 1.8.1 will ask for both push and pull privilege when pulling an image. My auth server denied the access request, which cause the error not found. 

I will modify my auth server to check my guess. However I still wondering why a pull request will ask for push right.

**Comment by deitch** [comment]
@oilbeater thanks for referencing. I have been wondering if this was a change in 1.8.1 but didn't have the opportunity to check it out.

**Comment by dmp42** [comment]
@oilbeater @deitch quoting dmcg: "This is the intended behavior. It is the responsibility of the token server to return a token with at most the requested scope and possibly less."

Let me know if this can be fixed.

**Comment by oilbeater** [comment]
@dmp42 from the perspective of token server,it should do like this.However from the view of docker engine ask push privilege when pulling an image is not reasonable, I'm not sure if this behaviors has changed since 1.8.

My question has been resolved, feel free to close it.

**Comment by dmp42** [comment]
Thanks @oilbeater.
I'll make sure we look into why the engine behavior changed, and add more tests so that both the specs is clearer and unsuspected changes don't happen in the future.

Thanks all for your feedback on this.

**Comment by deitch** [comment]
I left more comments on the other issue https://github.com/docker/docker/issues/15640 but in short, I agree with @oilbeater that 

1. This is not the optimal implementation. The previous one made more sense.
2. Either way, though, the documentation needs to make it really clear, so token implementers have what to rely upon.

I did offer to make a PR for the documentation on the other issue, but I have some open questions. As soon as those are answered, I will make the documents and create a PR.

**Comment by dmp42** [comment]
@deitch agreed.
Looking forward to "fixing" this.
