### ISSUE TITLE
Docker run registry with swift storage times out behind proxy

### ISSUE THREAD

**Issue by npotter92** [docker/distribution#885]
I'm trying to run a registry with the following command from behind a corporate proxy:

docker run -d --name registry -p 5000:5000 -e "REGISTRY_STORAGE=swift" -e "REGISTRY_STORAGE_SWIFT_USERNAME=demo" -e "REGISTRY_STORAGE_SWIFT_PASSWORD=admin" -e "REGISTRY_STORAGE_SWIFT_AUTHURL=http://OpenstackControllerIP:5000/v3" -e "REGISTRY_STORAGE_SWIFT_CONTAINER=dockerimages" 
-e "HTTP_PROXY=myproxy:port" 
-e "HTTPS_PROXY=myproxy:port"
-e "NO_PROXY=10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16,172.16.0.0/20" registry:2

The registry runs for 60 seconds, then fails with the following error log: http://pastebin.com/AhvdC6Aq

I've also tried creating my own registry with this Dockerfile http://pastebin.com/4MVHnF3e and this config-dev.yml http://pastebin.com/pTVebCt1 and gotten the same result.

I'm running this on a machine that is on the same network as my OpenStack controller node that should be providing authentication services, so the container shouldn't have to go through the proxy to get to it.

**Comment by stevvooe** [comment]
@npotter92 This is happening during startup. The registry does a check to make sure the storage access is correctly configured. From the looks of the stacktrace, it seems the registry cannot connect to the storage backend. I'd recommend troubleshooting this connectivity.

**Comment by npotter92** [comment]
@stevvooe Do you think the connection issue could be related to the proxy? I know I'm able to ping the authurl from launched containers.

**Comment by npotter92** [comment]
@stevvooe If I launch the same registry with none of the proxy environment I get:

panic: Swift authentication failed: HTTP Error: 404: 404 Not Found

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7f0b574e7e50, 0xc2080f4b70, 0xc2080a8440, 0x3, 0x0, 0x0, 0x0, 0x0, 0xc2080f4000, 0x0, ...)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:95 +0x64a
main.main()
        /go/src/github.com/docker/distribution/cmd/registry/main.go:72 +0x523

goroutine 6 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 10 [runnable]:
net/http.(*persistConn).readLoop(0xc2080b62c0)
        /usr/src/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
        /usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc2080b62c0)
        /usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/src/go/src/net/http/transport.go:661 +0xcbc

**Comment by stevvooe** [comment]
@npotter92 The ticket is closed. Did you find the problem?

I would recommend investigate anything in the path from the registry machine to the backend.

**Comment by npotter92** [comment]
Yes - to make it work I had to remove all the proxy configuration as well as specify the tenant name and domain. The authurl that worked was http://myControllerIP:5000/v3/auth. Thanks for your replys.

**Comment by stevvooe** [comment]
@npotter92 Great to hear!
