### ISSUE TITLE
Pin dind dep

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#898]
@aaronlehmann can we pin https://github.com/docker/distribution/blob/master/contrib/docker-integration/Dockerfile#L28 to a fixed commit?
I don't like the smell of unbound master, specifically in light of https://github.com/docker/docker/pull/15596

**Comment by thaJeztah** [comment]
Not really into "dind", but according to https://github.com/docker/docker/pull/15596, dind is no longer needed when using Docker 1.8+, don't know if that applies for distribution, but may be worth checking :+1:

**Comment by aaronlehmann** [comment]
I think we can avoid using dind in this Dockerfile.
