### ISSUE TITLE
I would like to run a run a local registry mirror using Artifactory

### ISSUE THREAD

**Issue by jason-lanpher** [docker/distribution#900]
I would like to run a local registry mirror of the docker registry: https://registry-1.docker.io.  I believe I need some type of client credentials to do this and I am looking to you to help guide me.

**Comment by dmp42** [comment]
Hi. Artifactory is a third party implementation. If you plan on doing something with their software, I believe your best bet is to ask them, since we have no knowledge about it here...

Furthermore, last I checked artifactory was only implementing the v1 protocol, which is deprecated.

**Comment by jason-lanpher** [comment]
Artifactory is not really the point of this request.  It will be the remote repository.  Since you are not familiar with it's capabilities I will include a link to their documentation which specifically states they are v2 compatible.

What I am interested in doing is running a local remote repository mirror as stated in the original request.  This again is something which is support by Artifactory.  In their instructions they state that:
"Proxying the official Docker Hub
If you are proxying the official Docker Hub, use https://registry-1.docker.io/ as the URL, and make sure to check the Enable Token Authentication checkbox as well since the Docker Hub only supports token-based authentication."

What I am seeking assistance on is obtaining the authentication token so that I do not receive error responses when attempting to mirror https://registry-1.docker.io/

**Comment by jason-lanpher** [comment]
Sorry left out the links by accident

Artifactory Supported Versions:
http://www.jfrog.com/confluence/display/RTF/Docker+Repositories


Artifactory and how to setup a remote Docker Repository:
http://www.jfrog.com/confluence/display/RTF/Docker+Repositories#DockerRepositories-RemoteRepositories

**Comment by dmp42** [comment]
@jason-lanpher thanks for the links.

I really think you should ask Artifactory if you need assistance setting up a mirror using their solution, or with their documentation.

There is no such thing as "obtaining an authentication token" for the purpose of setting up a mirror.
