### ISSUE TITLE
Private registry with mirror

### ISSUE THREAD

**Issue by ddysher** [docker/distribution#903]
I'm using registry 2.1.1 for private registry, and also rely on some public services for dockerhub mirror (accessing docker hub is slow).

In this case, will the private images be cached in the mirror?

**Comment by RichardScothern** [comment]
All images which are pulled through from the hub will be stored in the mirror.  If you configure the mirror with your hub credentials and pull private images from the hub (e.g. ddysher/foo) they will also be cached.

Also, please don't file issues on github for questions like this.  You can ask questions on IRC (#docker-distribution)
