### ISSUE TITLE
Unexpected failure of registry:2

### ISSUE THREAD

**Issue by dalanlan** [docker/distribution#904]
###Startup params:
```
docker run -d -p 5000:5000 --restart=always --name registry -v /mnt:/var/lib/registry registry:2
```
###Failure
After running for a while (not sure how long it lasts), the registry fails with no logs & no exited code. Restart policy seems totally meaningless.
```
$ docker ps -a | grep registry
3a6ac78c2e62        registry:2                                       "/bin/registry /etc/   4 hours ago                                                                                                                                                                  
$ docker logs 3a6ac78c2e62
<no log here>
```
Noticed that the container name set previously is gone nowhere now.
It could be kinda hard to trace & reproduce, yet i have at least 3 nodes suffer this today. No unusual operation was conducted though (as far as i could remember).

**Comment by dmp42** [comment]
@dalanlan sounds rather like a docker bug.
Specifically, the total absence of any logs is worrying.
I know there is a syslog leak bug.
Do you experience high memory consumption on that host?

What version of docker is that?

**Comment by dalanlan** [comment]
docker 1.7.1

>Do you experience high memory consumption on that host?

Nope since i'm aware. It's kinda odd 'cause i have just turned to a brand-new release image of registry yesterday, while an older one (published about 3 months ago whose id is 0ff65644861b) functions quite well all along.
```
$ docker images | grep registry
registry                                  2                                  2f1ef7702586        6 days ago          220.6 MB
```

**Comment by dmp42** [comment]
@dalanlan yeah the non-sensical part is really the name "vanishing" from the docker ps, not restarting, and the total lack of any logs - which made me suspect a docker problem / host issue.

Unfortunately, there is little to do currently (but guessing) - if you hit it again, or manage to reproduce reliably, or get any other info, sure bring them forward.

**Comment by dalanlan** [comment]
Thank you for your time.
Closing it for now.
