### ISSUE TITLE
Push exactly same tag twice to V2 (2.1.1) is re-pushing some images

### ISSUE THREAD

**Issue by vehovmar** [docker/distribution#905]
Bug report

When pushing the exactly same tag multiple times, I'll get "Image already exists" with 70% of the images, but some are getting pushed over and over again!

    docker run -d -p 5000:5000 \
    -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry \
    -v "/home/docker_registry_v2:/var/lib/registry" \
    --restart=always \
    --name icm_registry \
    registry:2.1.1

First run:

    docker push <myrepo>:5000/myimage:latest
    ...
    e2ef2aead406: Image already exists
    4ab5d4422e2e: Image already exists
    acdf1f62cbe8: Image already exists
    c4fec2184b09: Image already exists
    24129e056427: Image already exists
    44e251925bc0: Image already exists
    a99ebe55e7ce: Buffering to Disk
    a99ebe55e7ce: Image successfully pushed

Second run:

    docker push <myrepo>:5000/myimage:latest
    ...
    e2ef2aead406: Image already exists
    4ab5d4422e2e: Image already exists
    acdf1f62cbe8: Image already exists
    c4fec2184b09: Image already exists
    24129e056427: Image already exists
    44e251925bc0: Image already exists
    a99ebe55e7ce: Buffering to Disk

These are examples of images that are being re-pushed every time:

    a99ebe55e7ce  6 days ago    442.8 MB
    4aefbd0d09dc  7 months ago  0 B
    533583df0f2f  7 months ago  1.319 GB
    45eb1a443e7f  7 months ago  1.771 kB
    a5482e21e044  7 months ago  1.801 kB

So it's not related to the size of the images.

**Comment by RichardScothern** [comment]
This is a known issue which is being worked on.
https://github.com/docker/docker/issues/13883

**Comment by stevvooe** [comment]
@RichardScothern @vehovmar This is more that just #634. There is a UI bug, as well. We've also added tar-split.

These issues are part of docker and covered in #14018.

**Comment by vehovmar** [comment]
You are closing issues, without reading them properly.

Many thanks to Aaron from Google mail group:
"If it's older than 1.8.1, can you please try upgrading? We've had a few reports of this behavior, and think the new method of tar reconstruction in Docker 1.8 may address it."

And upgrading to Docker Engine 1.8.1 actually fixed the issue.

**Comment by stevvooe** [comment]
@vehovmar The issue is that this is more of a duplicate of docker/docker#14018 or https://github.com/docker/docker/issues/15177. In addition, the complaint here is about the behavior of docker, rather than the registry.

Sorry if we closed too early. We thought there was enough existing bugs covering this behavior.
