### ISSUE TITLE
Mirrroring Docker Registry

### ISSUE THREAD

**Issue by jcontreras000** [docker/distribution#914]
Hi!
I'm keen to set a registry mirror... i want across the documentation and it led me to request support as you indicate... can you help me with this?

Cheers!

**Comment by cognition** [comment]
+1

**Comment by stevvooe** [comment]
@jcontreras000 @cognition We'll need more information to help you. Please use IRC or the mailing list.

**Comment by jglick** [comment]
Researching how to set up https://github.com/jenkinsci/docker-workflow-plugin/pull/8, possibly upgrading an old registry along the way, and am baffled. [This page](https://docs.docker.com/articles/registry_mirror/) links to [1.x documentation](https://docs.docker.com/v1.6/articles/registry_mirror/), then says (insofar as I get it right) that for 2.x documentation you should file a request here. So someone did so, and is now asked for more information? Seems clear to me: there should be documentation for running the 2.x registry with a local registry mirror.

**Comment by stevvooe** [comment]
@jglick > So someone did so, and is now asked for more information?

Thank you for the investigation into a possible documentation issue but the user, @jcontreras000, is asking for direct help ("can you help me with this?"). The documentation for V2 mirroring is available [here](https://github.com/docker/distribution/blob/master/docs/mirror.md).

I understand there may be confusing or frustrating aspects to the documentation, but, in the future, please keep your tone cordial and constructive.
