### ISSUE TITLE
AWS STS?

### ISSUE THREAD

**Issue by lcc2207** [docker/distribution#917]
Can distribution connect to S3 via STS credentials?

**Comment by stevvooe** [comment]
@lcc2207 Could you be more specific about what this is? What did you try that did not work?

**Comment by lcc2207** [comment]
Can distribution be given an IAM account with no real rights to S3 and then assume ROLE via STS to be able to read/write to a given S3 bucket

**Comment by stevvooe** [comment]
It looks like there is support in the [aws library](https://github.com/AdRoll/goamz/blob/master/sts/sts.go). I don't think this is accessible via regular configuration.

Do you have documentation on using STS?
Do you have examples of other applications that integrate STS? This will help us to understand what it might look like.
How would you expect it to work?

Instance credentials should be supported, if you are looking for more automated configuration.

@AndreyKostov @BrianBland Any ideas?

**Comment by lcc2207** [comment]
I don't have examples, just and ask from our risk team to use STS.

**Comment by stevvooe** [comment]
@lcc2207 We'll look into getting this supported.

As an alternative, it might be reasonable to setup a script that can hit STS and inject the resulting tokens into the registries environment. Based on this [document](http://docs.aws.amazon.com/STS/latest/UsingSTS/using-temp-creds.html), it should be trivial to write a script that can do this on startup.

**Comment by tobstarr** [comment]
It is mentioned here https://github.com/docker/distribution/blob/0b3b55e723b5362f68c449a37ac8cff1327c1478/docs/storage-drivers/s3.md that `You can provide empty strings for your access and secret keys if you plan on running the driver on an ec2 instance and will handle authentication with the instance's credentials.`

Is that just not true?

**Comment by tobstarr** [comment]
It actually just works as documented (I just had an issue the lack of policies)

**Comment by stevvooe** [comment]
@tobstarr Great to hear.

I'm closing this issue. Let us know if you need something else.
