### ISSUE TITLE
Env Search backend 

### ISSUE THREAD

**Issue by berrywira** [docker/distribution#919]
Hi,

On old docker-registry have config search backend, what the name config on new docker-registry?

**Comment by lmesz** [comment]
Hello,

Currently no search backend just catalog https://github.com/docker/distribution/blob/master/docs/spec/api.md#listing-repositories
which can be used instead of search. This SO question worth a read about the topic
http://stackoverflow.com/questions/30113726/docker-registry-2-0-api-v2

**Comment by berrywira** [comment]
Thanks for your explain
