### ISSUE TITLE
Docker Registry - Namespaces

### ISSUE THREAD

**Issue by plamer** [docker/distribution#920]
Hello,

I'm testing a private repository at the moment and I need to separate the users namespaces - when user test1 is logged to be able to see/download only his images and when user test2 is logged to be able to see only his images. I can't find information about this in the documentation, and googling didn't give me better results. Is it possible? I've stumbled on Portus - http://suse.github.io/Portus/ and it's able to do this private/public namespacing thing, but I really need only the registry. Any ideas/suggestions?

Thanks in advance!

**Comment by stevvooe** [comment]
@plamer You could setup nginx (or other proxy) basic auth with different htpasswd files for different routes. For example, you might have /v2/test1/ be authenticated against test1.htpasswd and /v2/test2/ authenticated against test2.htpassed.

The routing layout is actually setup to make this use case straightforward. Let us know how it goes.

**Comment by plamer** [comment]
Hey @stevvooe - thanks. I'm currently looking into it.
