### ISSUE TITLE
Missing code for Registry's "Native basic auth" documentation

### ISSUE THREAD

**Issue by kenny1986** [docker/distribution#921]
In the documentation for [Deploying Registry](https://docs.docker.com/registry/deploying/), at the **Restricting Access - Native basic auth** section, the sample code:

    docker run -d -p 5000:5000 --restart=always --name registry \
      -v `pwd`/auth:/auth \
      -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
      -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
      -v `pwd`/certs:/certs \
      -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
      -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
      registry:2

has a missing line: - ```  -e "REGISTRY_AUTH=htpasswd" \```

User will not be authenticated without that missing line.

The block of code is correct at the GitHub [page](https://github.com/docker/distribution/blob/master/docs/deploying.md) but not at the Docs page.

**Comment by neumino** [comment]
Just a quick note to confirm the issue.

**Comment by dmp42** [comment]
doc has been fixed quite some time ago here: https://github.com/docker/distribution/blob/master/docs/deploying.md#native-basic-auth

**Comment by neumino** [comment]
I think the issue is with https://docs.docker.com/registry/deploying/ but I'm not sure how that page is generated so it may not be relevant to this repo.

**Comment by thaJeztah** [comment]
Looks like the documentation was updated; https://docs.docker.com/registry/deploying/#native-basic-auth

@kenny1986 @dmp42 I think this one can be closed?
