### ISSUE TITLE
GOMAXPROCS for registry container

### ISSUE THREAD

**Issue by akerekes** [docker/distribution#923]
I'm running registry v2, version 2.1.1, in docker container and noticed, that it uses only one vCPU (EC2) from the available 2. I tried to set GOMAXPROCS=2 in the environment of the container, but it did not help. Do I miss something? Is it possible to make the container use both vCPUs?

**Comment by stevvooe** [comment]
@akerekes How are you evaluating the usage of CPUs? `GOMAXPROCS` should work. What are you seeing that indicate it is using only a single cpu?

**Comment by akerekes** [comment]
Sorry, it was a false alarm, it indeed works!

**Comment by stevvooe** [comment]
@akerekes Great. Was a bit worried there...
