### ISSUE TITLE
add api to support *delete tag* *get tag info* via http request

### ISSUE THREAD

**Issue by ChenLingPeng** [docker/distribution#924]
When there is a docker hub for private registry, I think some baisc function should be support: 
1. Delete tag via http request like `DELETE /v2/<name>/tag/<tag-name>` and user can manipulate the delete action from frontend like docker hub.
2. Show detail information of image(tag) like create time, author, description and docker inspect info. RESTful api should be support like `GET /v2/<name>/tag/<tag>/detail`. 
3. List tags through namespace. For now distribution only support list tags from namespace/repository.

**Comment by ChenLingPeng** [comment]
To implement the first requirement, could I just delete the tag fold(path: `registry/v2/repositories/<name>/_manifests/tags/<tag-name>`)?

**Comment by kwk** [comment]
I'm also missing some more information about a tag when requesting information about tags . The old V1 API had this nice `/v1/images/:imageId/json` method which told you a lot.

The only API entrypoint that seems to be somewhat comparable to `/v1/images/IMAGEID/json` is  `/v2/NAMESPACE/REPOSITORY/manifests/TAG`. The latter only gives you a `history` element for backwards v1 compatibility but I guess this isn't going to be supported for very long, is it?

**Comment by dmp42** [comment]
@ChenLingPeng 

for 1. I believe the DELETE endpoint is supported.

https://github.com/docker/distribution/blob/master/docs/spec/api.md#deleting-an-image

for 2. the registry architecture supports extensive notifications, that let you build secondary systems to present any kind of additional information you would want.
Specifically, you can leverage this notifications API + the catalog API to implement advanced search. Modularity was a choice here, to give more extensibility to users, and not bloating the core itself. I would encourage you to explore this path.

for 3. listing tags in a namespace: I assume you are speaking about listing all images and tags for a given "user", correct? There again, I would suggest looking into a registry extension consuming notifications and building an index. Other projects like DTR or Portus are providing such added functionality, using that pipeline.

@kwk ah - easier here than on twitter :)
History should go away, yes.
Overall, I believe the answer to your concerns would be the same: the encouraged design is to write a very simple additional service that builds an index from notifications and serve whatever information you want.
I understand you would want this to be a core feature, but the focus here really is on extensibility, and some choices have to be made.

**Comment by kwk** [comment]
I understand the concept of notifications and I find it useful as well. BUT if have been running a registry for some time and then want to write a front end for it, then all those notifications for the images that already exist in your registry can no longer be consumed.
Especially something like a created_at flag is so extremely important to probably everyone, isn't it?

For instance we have automatic build scripts that can flood your registry if you don't pay attention and remove old artifacts from the registry.

I'm trying to understand why this information is no longer available but reading through the docs I couldn't find something except for the attempt to focus on content addressability. Is that the main goal then?

For security purposes I might understand why this is important. Let's say you push a signed artifact to registry A. If you push the same image to registry B you probably want it to be verifiably the same there, right? This wouldn't be possible if the push-date was included in some way or the other. But what about the image creation date which is separate from the push date?

Looks like I'll probably keep missing good old v1 ;).

I hope you don't mind asking if there's an HTTP API for tagging an image. I haven't seen it yet.

**Comment by ChenLingPeng** [comment]
Thx @dmp42 & @kwk for the comment.
In the company I work for, we use the private registry v1 for now, but we would like to upgrade to v2.
After deep dig the spec and the source code, I have solved the above needs
1. [here](https://github.com/docker/distribution/pull/933) is a PR I have mad to solve the first problem. For now I think it's enough though not accepted for some deep consideration.
2. As mentioned by __kwk__, distribution have the restful api `/v2/NAMESPACE/REPOSITORY/manifests/TAG` to get the detail info
3. List tags in a namespace(I think this is the right [glossary](https://github.com/docker/distribution/blob/master/docs/glossary.md#namespace) even though for most time it maps to a user?) is very convenient  because what we need is just list list related directories.

**Comment by stevvooe** [comment]
@kwk You can read more about V2 design goals in the [road map](https://github.com/docker/distribution/blob/master/ROADMAP.md). Security goals aside, the short of it is that the V2 API is a content storage and distribution endpoint, rather than a REST content management endpoint. You're welcome to reach out via IRC or the mailing list if you'd like to understand this distinction better or help us to communicate it.

There is a lot of work in the area of registry GC that will alleviate the problems you've identified. Success has also been found with simple scripts that can scan an apply policies to backend data that may work for the constraints of a particular environment.

Alternative approaches, such as `created_at` are problematic when leveraging a content-addressable model. One must somewhat trust the creator of a given piece of content. Many systems may not have synchronized clocks or could leverage this to nefarious purposes.

The Catalog API is built specifically to re-sync for missed notifications. Lots of projects are already using this methodology with great success. There are issues with it, but please give it a try before dismissing the approach.

**Comment by kwk** [comment]
Thank you Stephen. I already begun writing an event receiver today (with express JS and MongoDB) and it works quite smoothly. Thank you for being so supportive though. Really appreciated.

**Comment by stevvooe** [comment]
@kwk No problem. Let us know how your experience goes.
