### ISSUE TITLE
proxy config key not documented in configuration.md

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/distribution#927]
https://github.com/docker/distribution/blob/master/docs/mirror.md this shows the proxy configuration key (along with `config-cache.yml`) but `configuration.md` (https://github.com/docker/distribution/blob/b78a858b5d61795ad548b501cf4a62841da625a5/docs/configuration.md) does not have it.

**Comment by dmp42** [comment]
Closed by #929
