### ISSUE TITLE
Docker registry running on localhost:5000 is crashing when I am trying to push an image into it

### ISSUE THREAD

**Issue by mathewkoshy493** [docker/distribution#935]
I was trying to build a docker registry using the instructions given in https://github.com/docker/distribution/blob/master/docs/building.md.

 I got the registry using the command :  go get github.com/docker/distribution/cmd/registry(my go lang version is 1.5)

Then I created the directory for registry data using mkdir -p /var/lib/registry

The command $GOPATH/bin/registry -version is working and giving the following output
 $GOPATH/bin/registry github.com/docker/distribution v2.0.0-alpha.1+unknown

Then i installed both godep andgolint using the following instruction
go get github.com/tools/godep github.com/golang/lint/golint

Then i restored godep inside the directory in which distribution is located by the following command
/home/mat/golang/gopath/bin/godep restore

Then I compiled the distribution code using make command

I got the registry inside $GOPATH/bin which i ran using default configuration
$GOPATH/bin/registry GOPATH/src/github.com/docker/distribution/cmd/registry/config-dev.yml
and the registry was up and running at ports localhost:5000 and localhost:5001

I started my docker daemon in another tab
Output for docker version is 
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   aacb47d-dirty
 Built:        Wed Aug 19 04:29:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   aacb47d-dirty
 Built:        Wed Aug 19 04:29:08 UTC 2015
 OS/Arch:      linux/amd64

I used git clone https://github.com/docker/docker.git        to get the docker source code and then used make build to build it (Please note that while I compiled the Docker client my go version was 1.4 . I dont know whether this has caused the problem or not).

Till now the registry and docker daemon are running fine

Now i just tagged the hello-world image available in my system with the command 
docker tag hello-world localhost:5000/myhelloworld

Now as I am pushing my hello-world to the docker registry using the command
dokcer push localhost:5000/myhelloworld
Suddently the docker registry is getting stopped and the following error is coming(I have checked the logs of  Docker Daemon and i have found out that it is pushing properly,the problem should be with the registry)

Following is the error message that I am getting from the registry

INFO[0000] using redis blob descriptor cache environment=development instance.id=7f280da6-5863-48e3-b153-9fb4211e98cc service=registry version=v2.1.0+unknown
INFO[0000] listening on [::]:5000 environment=development instance.id=7f280da6-5863-48e3-b153-9fb4211e98cc service=registry version=v2.1.0+unknown
INFO[0000] debug server listening localhost:5001        
runtime: bad pointer in frame github.com/docker/distribution/context.(*instanceContext).Value at 0xc82003b2c0: 0x10
fatal error: invalid stack pointer

runtime stack:
runtime.throw(0xc0cf00, 0x15)
	/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0x7f9e38160990 sp=0x7f9e38160978
runtime.adjustpointers(0xc82003b2b0, 0x7f9e38160b08, 0x7f9e38160cf8, 0xda7d18)
	/usr/local/go/src/runtime/stack1.go:438 +0x2d4 fp=0x7f9e38160a88 sp=0x7f9e38160990
runtime.adjustframe(0x7f9e38160c18, 0x7f9e38160cf8, 0x1)
	/usr/local/go/src/runtime/stack1.go:505 +0x1b5 fp=0x7f9e38160b40 sp=0x7f9e38160a88
runtime.gentraceback(0x413170, 0xc82003b280, 0x0, 0xc820001200, 0x0, 0x0, 0x7fffffff, 0xcdad48, 0x7f9e38160cf8, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:336 +0xa69 fp=0x7f9e38160c70 sp=0x7f9e38160b40
runtime.copystack(0xc820001200, 0x2000)
	/usr/local/go/src/runtime/stack1.go:616 +0x1a7 fp=0x7f9e38160d60 sp=0x7f9e38160c70
runtime.newstack()
	/usr/local/go/src/runtime/stack1.go:801 +0xb53 fp=0x7f9e38160ed8 sp=0x7f9e38160d60
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:330 +0x7f fp=0x7f9e38160ee0 sp=0x7f9e38160ed8
goroutine 14 [copystack]:
runtime.assertE2T2(0x988120, 0x988120, 0xc820252aa0, 0xc82004d2b0, 0x0)
	/usr/local/go/src/runtime/iface.go:233 fp=0xc82003b288 sp=0xc82003b280
github.com/docker/distribution/context.(*instanceContext).Value(0xf314e0, 0x988120, 0xc820252aa0, 0x0, 0x0)
	/home/mat/golang/gopath/src/github.com/docker/distribution/context/context.go:24 +0x54 fp=0xc82003b2e8 sp=0xc82003b288
golang.org/x/net/context.(*valueCtx).Value(0xc82017e840, 0x988120, 0xc820252aa0, 0x0, 0x0)
	/home/mat/golang/gopath/src/golang.org/x/net/context/context.go:431 +0xd0 fp=0xc82003b338 sp=0xc82003b2e8
golang.org/x/net/context.(*valueCtx).Value(0xc8201da390, 0x988120, 0xc820252aa0, 0x0, 0x0)
	/home/mat/golang/gopath/src/golang.org/x/net/context/context.go:431 +0xd0 fp=0xc82003b388 sp=0xc82003b338
github.com/docker/distribution/context.stringMapContext.Value(0x7f9e38f6b018, 0xc8201da390, 0xc8201da3c0, 0x988120, 0xc820252aa0, 0x0, 0x0)
	/home/mat/golang/gopath/src/github.com/docker/distribution/context/context.go:84 +0x13b fp=0xc82003b410 sp=0xc82003b388
github.com/docker/distribution/context.(*stringMapContext).Value(0xc8201bfde0, 0x988120, 0xc820252aa0, 0x0, 0x0)
	<autogenerated>:14 +0xc1 fp=0xc82003b450 sp=0xc82003b410
golang.org/x/net/context.(*valueCtx).Value(0xc8201da450, 0x988120, 0xc820252aa0, 0x0, 0x0)
	/home/mat/golang/gopath/src/golang.org/x/net/context/context.go:431 +0xd0 fp=0xc82003b4a0 sp=0xc82003b450
golang.org/x/net/context.(*valueCtx).Value(0xc820226db0, 0x988120, 0xc820252aa0, 0x0, 0x0)
	/home/mat/golang/gopath/src/golang.org/x/net/context/context.go:431 +0xd0 fp=0xc82003b4f0 sp=0xc82003b4a0
github.com/docker/distribution/registry/handlers.(*App).Value(0xc8201cc900, 0x988120, 0xc820252aa0, 0x0, 0x0)
	<autogenerated>:4 +0x6f fp=0xc82003b530 sp=0xc82003b4f0
github.com/docker/distribution/context.WithRequest(0x7f9e38f6f4d8, 0xc8201cc900, 0xc8200d3420, 0x0, 0x0)
	/home/mat/golang/gopath/src/github.com/docker/distribution/context/http.go:72 +0x9b fp=0xc82003b5c0 sp=0xc82003b530
github.com/docker/distribution/registry/handlers.(*contextManager).context(0xc820178c80, 0x7f9e38f6f5f8, 0xc8201cc900, 0x7f9e38f70e70, 0xc820227b60, 0xc8200d3420, 0x0, 0x0)
	/home/mat/golang/gopath/src/github.com/docker/distribution/registry/handlers/context.go:132 +0x1e6 fp=0xc82003b810 sp=0xc82003b5c0
github.com/docker/distribution/registry/handlers.(*App).ServeHTTP(0xc8201cc900, 0x7f9e38f70e70, 0xc820227b60, 0xc8200d3420)
	/home/mat/golang/gopath/src/github.com/docker/distribution/registry/handlers/app.go:503 +0xe2 fp=0xc82003b8b0 sp=0xc82003b810
main.alive.func1(0x7f9e38f70e70, 0xc820227b60, 0xc8200d3420)
	/home/mat/golang/gopath/src/github.com/docker/distribution/cmd/registry/main.go:331 +0x131 fp=0xc82003b910 sp=0xc82003b8b0
net/http.HandlerFunc.ServeHTTP(0xc820227290, 0x7f9e38f70e70, 0xc820227b60, 0xc8200d3420)
	/usr/local/go/src/net/http/server.go:1422 +0x3a fp=0xc82003b930 sp=0xc82003b910
github.com/docker/distribution/health.Handler.func1(0x7f9e38f70e70, 0xc820227b60, 0xc8200d3420)
	/home/mat/golang/gopath/src/github.com/docker/distribution/health/health.go:271 +0x19a fp=0xc82003b9c0 sp=0xc82003b930
net/http.HandlerFunc.ServeHTTP(0xc82024a5a0, 0x7f9e38f70e70, 0xc820227b60, 0xc8200d3420)
	/usr/local/go/src/net/http/server.go:1422 +0x3a fp=0xc82003b9e0 sp=0xc82003b9c0
main.panicHandler.func1(0x7f9e38f70e70, 0xc820227b60, 0xc8200d3420)
	/home/mat/golang/gopath/src/github.com/docker/distribution/cmd/registry/main.go:314 +0x77 fp=0xc82003ba18 sp=0xc82003b9e0
net/http.HandlerFunc.ServeHTTP(0xc82024a5c0, 0x7f9e38f70e70, 0xc820227b60, 0xc8200d3420)
	/usr/local/go/src/net/http/server.go:1422 +0x3a fp=0xc82003ba38 sp=0xc82003ba18
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7f9e38f6a358, 0xc82002a010, 0x7f9e38f6a558, 0xc82024a5c0, 0x7f9e38f70cd0, 0xc8200b7c30, 0xc8200d3420)
	/home/mat/golang/gopath/src/github.com/gorilla/handlers/handlers.go:75 +0x11f fp=0xc82003bbb0 sp=0xc82003ba38
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc82024a5e0, 0x7f9e38f70cd0, 0xc8200b7c30, 0xc8200d3420)
	<autogenerated>:12 +0xb4 fp=0xc82003bbf0 sp=0xc82003bbb0
net/http.serverHandler.ServeHTTP(0xc8202364e0, 0x7f9e38f70cd0, 0xc8200b7c30, 0xc8200d3420)
	/usr/local/go/src/net/http/server.go:1862 +0x19e fp=0xc82003bc50 sp=0xc82003bbf0
net/http.(*conn).serve(0xc8200b7b80)
	/usr/local/go/src/net/http/server.go:1361 +0xbee fp=0xc82003bfa8 sp=0xc82003bc50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82003bfb0 sp=0xc82003bfa8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 1 [IO wait]:
runtime.gopark(0xcdaf88, 0x7f9e38f708d0, 0xb8d4a8, 0x7, 0x1b, 0x5)
	/usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc820169528 sp=0xc820169500
runtime.netpollblock(0x7f9e38f708a8, 0x72, 0x7f9e38f66168)
	/usr/local/go/src/runtime/netpoll.go:338 +0x15e fp=0xc820169570 sp=0xc820169528
net.runtime_pollWait(0x7f9e38f708a8, 0x72, 0xc82000e270)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60 fp=0xc820169590 sp=0xc820169570
net.(*pollDesc).Wait(0xc820248d10, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a fp=0xc8201695b0 sp=0xc820169590
net.(*pollDesc).WaitRead(0xc820248d10, 0x0, 0x0)
/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36 fp=0xc8201695d8 sp=0xc8201695b0
net.(*netFD).accept(0xc820248cb0, 0x0, 0x7f9e38f70a18, 0xc82024aa60)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c fp=0xc8201696d8 sp=0xc8201695d8
net.(*TCPListener).AcceptTCP(0xc82002a2f8, 0x458c50, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d fp=0xc820169738 sp=0xc8201696d8
github.com/docker/distribution/registry/listener.tcpKeepAliveListener.Accept(0xc82002a2f8, 0x0, 0x0, 0x0, 0x0)
	/home/mat/golang/gopath/src/github.com/docker/distribution/registry/listener/listener.go:20 +0x41 fp=0xc820169770 sp=0xc820169738
net/http.(*Server).Serve(0xc8202364e0, 0x7f9e38f70968, 0xc82002a2f8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3 fp=0xc820169858 sp=0xc820169770
main.main()
	/home/mat/golang/gopath/src/github.com/docker/distribution/cmd/registry/main.go:146 +0x1ae1 fp=0xc820169f00 sp=0xc820169858
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820169f50 sp=0xc820169f00
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820169f58 sp=0xc820169f50

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82003afb8 sp=0xc82003afb0

goroutine 2 [force gc (idle)]:
runtime.gopark(0xcdafc8, 0xf312a0, 0xba5610, 0xf, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc820026758 sp=0xc820026730
runtime.goparkunlock(0xf312a0, 0xba5610, 0xf, 0xc820000114, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc820026790 sp=0xc820026758
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:152 +0xb8 fp=0xc8200267c0 sp=0xc820026790
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200267c8 sp=0xc8200267c0
created by runtime.init.4
	/usr/local/go/src/runtime/proc.go:141 +0x2b
goroutine 3 [GC sweep wait]:
runtime.gopark(0xcdafc8, 0xf314c0, 0xb9b7c0, 0xd, 0x423414, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc820026f48 sp=0xc820026f20
runtime.goparkunlock(0xf314c0, 0xb9b7c0, 0xd, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc820026f80 sp=0xc820026f48
runtime.bgsweep(0xc820014070)
	/usr/local/go/src/runtime/mgcsweep.go:51 +0xb1 fp=0xc820026fb8 sp=0xc820026f80
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820026fc0 sp=0xc820026fb8
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:205 +0x53

goroutine 4 [finalizer wait]:
runtime.gopark(0xcdafc8, 0xf576a0, 0xba5180, 0xe, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc820027718 sp=0xc8200276f0
runtime.goparkunlock(0xf576a0, 0xba5180, 0xe, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc820027750 sp=0xc820027718
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:154 +0xaa fp=0xc8200277c0 sp=0xc820027750
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200277c8 sp=0xc8200277c0
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:135 +0x60

goroutine 6 [syscall]:
runtime.notetsleepg(0xf57c00, 0xffffffffffffffff, 0x1)
	/usr/local/go/src/runtime/lock_futex.go:202 +0x4e fp=0xc820028740 sp=0xc820028718
runtime.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:111 +0x132 fp=0xc820028778 sp=0xc820028740
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18 fp=0xc8200287c0 sp=0xc820028778
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200287c8 sp=0xc8200287c0
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
goroutine 7 [syscall]:
runtime.notetsleepg(0xf31578, 0x12a0198e8, 0x0)
	/usr/local/go/src/runtime/lock_futex.go:202 +0x4e fp=0xc820028f38 sp=0xc820028f10
runtime.timerproc()
	/usr/local/go/src/runtime/time.go:209 +0xde fp=0xc820028fc0 sp=0xc820028f38
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820028fc8 sp=0xc820028fc0
created by runtime.addtimerLocked
	/usr/local/go/src/runtime/time.go:116 +0x11f

goroutine 8 [select]:
runtime.gopark(0xcdb000, 0xc820029720, 0xb94380, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc8200293f0 sp=0xc8200293c8
runtime.selectgoImpl(0xc820029720, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64 fp=0xc820029598 sp=0xc8200293f0
runtime.selectgo(0xc820029720)
	/usr/local/go/src/runtime/select.go:212 +0x12 fp=0xc8200295b8 sp=0xc820029598
github.com/docker/distribution/notifications.(*Broadcaster).run(0xc820227050)
	/home/mat/golang/gopath/src/github.com/docker/distribution/notifications/sinks.go:80 +0x66c fp=0xc8200297b8 sp=0xc8200295b8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200297c0 sp=0xc8200297b8
created by github.com/docker/distribution/notifications.NewBroadcaster
	/home/mat/golang/gopath/src/github.com/docker/distribution/notifications/sinks.go:39 +0x100

goroutine 9 [chan receive]:
runtime.gopark(0xcdafc8, 0xc8202365f8, 0xba2dd0, 0xc, 0x17, 0x3)
	/usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc820029e38 sp=0xc820029e10
runtime.goparkunlock(0xc8202365f8, 0xba2dd0, 0xc, 0x17, 0x3)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc820029e70 sp=0xc820029e38
runtime.chanrecv(0x972ca0, 0xc8202365a0, 0x0, 0x1, 0x0)
	/usr/local/go/src/runtime/chan.go:505 +0x901 fp=0xc820029f30 sp=0xc820029e70
runtime.chanrecv1(0x972ca0, 0xc8202365a0, 0x0)
	/usr/local/go/src/runtime/chan.go:349 +0x2b fp=0xc820029f60 sp=0xc820029f30
github.com/docker/distribution/health.PeriodicThresholdChecker.func1(0x2540be400, 0x7f9e38f6f850, 0xc820227260, 0x7f9e38f6f828, 0xc8202523a0)
	/home/mat/golang/gopath/src/github.com/docker/distribution/health/health.go:154 +0x55 fp=0xc820029f98 
sp=0xc820029f60
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820029fa0 sp=0xc820029f98
created by github.com/docker/distribution/health.PeriodicThresholdChecker
	/home/mat/golang/gopath/src/github.com/docker/distribution/health/health.go:157 +0xfa

goroutine 10 [IO wait]:
runtime.gopark(0xcdaf88, 0x7f9e38f70810, 0xb8d4a8, 0x7, 0x1b, 0x5)
	/usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc82004bb08 sp=0xc82004bae0
runtime.netpollblock(0x7f9e38f707e8, 0x72, 0x7f9e38f66168)
	/usr/local/go/src/runtime/netpoll.go:338 +0x15e fp=0xc82004bb50 sp=0xc82004bb08
net.runtime_pollWait(0x7f9e38f707e8, 0x72, 0xc82000e270)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60 fp=0xc82004bb70 sp=0xc82004bb50
net.(*pollDesc).Wait(0xc820248f40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a fp=0xc82004bb90 sp=0xc82004bb70
net.(*pollDesc).WaitRead(0xc820248f40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36 fp=0xc82004bbb8 sp=0xc82004bb90
net.(*netFD).accept(0xc820248ee0, 0x0, 0x7f9e38f70a18, 0xc82024a840)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c fp=0xc82004bcb8 sp=0xc82004bbb8
net.(*TCPListener).AcceptTCP(0xc82002a318, 0xc82004bd50, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d fp=0xc82004bd18 sp=0xc82004bcb8
net/http.tcpKeepAliveListener.Accept(0xc82002a318, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2135 +0x41 fp=0xc82004bd50 sp=0xc82004bd18
net/http.(*Server).Serve(0xc820236540, 0x7f9e38f70a90, 0xc82002a318, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3 fp=0xc82004be38 sp=0xc82004bd50
net/http.(*Server).ListenAndServe(0xc820236540, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1877 +0x136 fp=0xc82004bec8 sp=0xc82004be38
net/http.ListenAndServe(0xc8201b69a0, 0xe, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1967 +0x8f fp=0xc82004bef0 sp=0xc82004bec8
main.debugServer(0xc8201b69a0, 0xe)
	/home/mat/golang/gopath/src/github.com/docker/distribution/cmd/registry/main.go:299 +0x131 fp=0xc82004bf90 sp=0xc82004bef0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82004bf98 sp=0xc82004bf90
created by main.main
	/home/mat/golang/gopath/src/github.com/docker/distribution/cmd/registry/main.go:81 +0x920

**Comment by noxiouz** [comment]
Seems it's a golang 1.5 issue

**Comment by mathewkoshy493** [comment]
this registry was working well before i updated to golang 1.5

**Comment by dmp42** [comment]
@mathewkoshy493 support for golang 1.5 is not ready, and this already an issue opened for that.

I really encourage you to use the official image (`pull registry:2`) instead of building from source.

**Comment by dmp42** [comment]
Related: #913 #887

**Comment by mathewkoshy493** [comment]
@dmp42 I want to experiment with the source code of the registry that is y I am trying to build a registry by compiling it

**Comment by mathewkoshy493** [comment]
While trying to use  go get github.com/docker/distribution/cmd/registry I am facing the following issue
 https://github.com/stevvooe/resumable/issues/3.

**Comment by mathewkoshy493** [comment]
I want to do some experimentation with registry source code that is the reason why I want to compile my own registry
    I have tried to compile registry using go1.4 ,and I am getting the following error on exeucting go get github.com/docker/distribution/cmd/registry

# github.com/stevvooe/resumable/sha512
gopath/src/github.com/stevvooe/resumable/sha512/resume.go:56: undefined: crypto.SHA512_224
gopath/src/github.com/stevvooe/resumable/sha512/resume.go:56: undefined: crypto.SHA512_256
gopath/src/github.com/stevvooe/resumable/sha512/sha512.go:17: undefined: crypto.SHA512_224
gopath/src/github.com/stevvooe/resumable/sha512/sha512.go:18: undefined: crypto.SHA512_256
gopath/src/github.com/stevvooe/resumable/sha512/sha512.go:95: undefined: crypto.SHA512_224
gopath/src/github.com/stevvooe/resumable/sha512/sha512.go:104: undefined: crypto.SHA512_256
gopath/src/github.com/stevvooe/resumable/sha512/sha512.go:136: undefined: crypto.SHA512_224
gopath/src/github.com/stevvooe/resumable/sha512/sha512.go:143: undefined: crypto.SHA512_256
gopath/src/github.com/stevvooe/resumable/sha512/sha512.go:157: undefined: crypto.SHA512_224
gopath/src/github.com/stevvooe/resumable/sha512/sha512.go:159: undefined: crypto.SHA512_256

I was facing the issue yesterday,So I was adviced to install go1.5 and try but with go1.5,I am facing the current error.I am trying these comands from a virtual machine that has fedora22 loaded in it,

**Comment by RichardScothern** [comment]
@mathewkoshy493 : regarding point 2 (undefined crypto package), be sure to run 
`godep restore` before building.  That should pull in all the dependencies.

**Comment by mathewkoshy493** [comment]
I did godep restore also,but still it is not working

**Comment by RichardScothern** [comment]
What is the output of `echo $GOROOT`?

**Comment by mathewkoshy493** [comment]
Home/mat/golang/go

**Comment by cooljiansir** [comment]
I'm going to the same trouble......
`
gopath/src/github.com/stevvooe/resumable/sha512/resume.go:56: undefined: crypto.SHA512_224
.....
`

**Comment by stevvooe** [comment]
@mathewkoshy493 @cooljiansir The current version of that package only works for go1.5 and later. I guess I can tag an old version for go1.4 but YMMV. Go 1.5 is out and stable now. There is no reason to still be on Go 1.4.

@mathewkoshy493 @cooljiansir And I just realized this was a completely unrelated issue. Please do not hijack issues for unrelated problems.
