### ISSUE TITLE
Support Go 1.5

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#937]
There are many benefits to using Go 1.5, including the new pause-less GC. However, we have run into several issues using Go 1.5 to build the registry, both at compile time and runtime. Let's collect them here and burn down towards getting there for the next registry release.

- [x] #887
- [ ] #910
- [x] #913

cc @RichardScothern

**Comment by RichardScothern** [comment]
[ ] #1124 

Leaving #910 until after the release.

**Comment by stevvooe** [comment]
Any reason we are holding this up? We shouldn't have released 2.2 without the upgrade. There are going to be massive performance benefits.

**Comment by RichardScothern** [comment]
Nope.  I'll put it on the list.

**Comment by stevvooe** [comment]
Wicked!

**Comment by tpounds** [comment]
Any plans to build a 2.2.x point release to include this change?
