### ISSUE TITLE
Manifest deletes need to cleanup tag index entry

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#938]
Manifest deletion is not properly cleaning the relevant tag index entries in the backend driver. Only the revision is removed, leaving the tag entry alone. Instead, it should remove the index entry by digest.

**Comment by dongmx** [comment]
How can I work around this bug ? Can I cleanup tag index by myself ?

**Comment by RichardScothern** [comment]
@dongmx : we will have a fix for this soon if you can wait for a couple of days.

**Comment by stevvooe** [comment]
@dongmx The tag index is just to track all manifests that were actually linked into the repository. It is more historical than functional. This is more of a cleanup issue.

 Is this affecting you?

**Comment by dongmx** [comment]
@RichardScothern  @stevvooe  Thank you.

**Comment by bartebor** [comment]
@stevvooe Leaving dangling index entries is happening quite often. Mutable tags such as `latest` may end up having hundreds of entries pointing to the missing revisions. It is common on CI environments, when immutable tags (version) are created together with mutable `latest` tag. When version is replaced and no longer needed previous ones are deleted via digest, `latest` tag is left with corrupted index.

This may not be important issue for operation of registry like you said above, but it consumes storage, inodes and make storage traversals (GC) longer. It also alerts our consistency checking tool we use to monitor out registry.

I personally think we should delete such index links. It would be great to do it while deleting revision, but I understand it makes it computationally expensive, so maybe we could at least add this to GC process?

I'm thinking of implementing it in my fork, but I do not want to diverge from upstream too much, as for now I have only my year-old PR #2644 merged in. What do you think?
