### ISSUE TITLE
v2.1 call "DELETE /v2/<name>/manifests/<reference>" return "UNSUPPORTED"

### ISSUE THREAD

**Issue by dotNetDR** [docker/distribution#940]
I'm call the [delete image API](http://docs.docker.com/registry/spec/api/#deleting-an-image), it return `{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}`

how can i fix it?

registry version: registry:2.1
```
# curl -v -X DELETE http://xxx/v2/hawkular/hawkular/manifests/latest
> DELETE /v2/hawkular/hawkular/manifests/latest HTTP/1.1
> User-Agent: curl/7.29.0
> Host: xxx
> Accept: */*
>
< HTTP/1.1 405 Method Not Allowed
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< Date: Thu, 20 Aug 2015 08:52:15 GMT
< Content-Length: 78
<
{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}
* Connection #0 to host xxx left intact
```

**Comment by mssola** [comment]
In the configuration, on the section of `storage` are you setting `delete` to true ? See the [documentation](https://github.com/docker/distribution/blob/master/docs/configuration.md#delete).

**Comment by younkim** [comment]
@mssola sorry, a bit off topic. I've spent quite some time trying to figure out where to configure the registry to absolutely no avail. Where do you place the yml file? I'm using Docker for Mac, and have a local registry that I want to enable the delete option.

**Comment by tylermzeller** [comment]
As well as above, you may also check `/etc/docker-distribution/registry/config.yml` if it applies.
