### ISSUE TITLE
remove s3 region requirement in config.yml

### ISSUE THREAD

**Issue by dtmistry** [docker/distribution#943]
Registry server fails to start if s3 is defined as storage and a region is not specified. 

Amazon does not require a region to be selected for s3 buckets. 

Any reason why s3 region is required in registry 2.0?

**Comment by BrianBland** [comment]
The S3 region is a hard requirement for v4 authentication, as it is part of the credential scope string (see http://docs.aws.amazon.com/general/latest/gr/sigv4-create-string-to-sign.html).

Given that AWS is pushing v4 authentication hard by requiring it for their newer regions (Frankfurt and Seoul so far) and for [their go sdk](https://github.com/aws/aws-sdk-go) (which we're very likely to switch to), I'm going to leave this region requirement unless there's a compelling reason to run a registry using S3 without knowing the value of this parameter.
