### ISSUE TITLE
Documentation: authentication with a registry:2

### ISSUE THREAD

**Issue by BradleyA** [docker/distribution#951]
Unable to get authentication with a registry:2 to work by following the docker instructions, under Restricting access; Native basic auth;   https://docs.docker.com/registry/deploying/.  Documentation is miss the line;
        -e “REGISTRY_AUTH=htpasswd” \
in the box starting with docker run -d -p 5000:5000 ...

Was able to get authentication with registry:2 to work when a web search found http://github.com/docker/distribution/blob/master/docs/deploying.md 
which had the missing line.
![screenshot from 2015-09-03 01 55 20](https://cloud.githubusercontent.com/assets/12129046/9652216/ea0099c8-51de-11e5-8533-e3dd225175c1.png)

Another incident with getting authentication with a registry:2 to work on same page; Restricting access;   Managing with Compose  https://docs.docker.com/registry/deploying/.  Documentation has the wrong the line;
       REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
in the box starting with registry: ...

The http://github.com/docker/distribution/blob/master/docs/deploying.md 
which has the correct line for authentication with a registry:2 and not the REGISTRY_STORAGE.. line.  Was not able to test this with compose at this time.
   REGISTRY_AUTH: htpasswd
![screenshot from 2015-09-03 00 51 12](https://cloud.githubusercontent.com/assets/12129046/9652232/17d663c8-51df-11e5-8883-9cefa61d395d.png)

**Comment by RichardScothern** [comment]
hi @BradleyA 

Just to be clear about what you are saying: the docs at  `http://github.com/docker/distribution/docs` are correct but the ones on `http://docs.docker.com` are not?

@dmp42 : can we promote these docs to the website?

**Comment by BradleyA** [comment]
yes, that is correct

**Comment by joerg** [comment]
I just lost a full day because of the missing REGISTRY_AUTH=htpasswd. Please fix!

**Comment by dmp42** [comment]
@joerg it's fixed here in the repo: https://github.com/docker/distribution/blob/master/docs/deploying.md

Promoting them to the docs site will happen with the next release apparently.

Sorry for the inconvenience.

**Comment by joerg** [comment]
Well, since the official docs at https://docs.docker.com/registry/ point to the latest release of the docker registry image I think it would be a good idea to also mention in the docs that the latest doc version can be found on Github.
Sorry for being annoying, but this really cost me a lot of time and all just because I assumed that the official docs would be correct. In the end it really did not strengthen my faith in Docker being enterprise ready...

**Comment by thaJeztah** [comment]
Looks like the online documentation is now updated, so I think this can be closed.

@joerg please note that this documentation is for the open source registry. If you're looking for commercially supported solutions, please have a look at, for example, Docker Trusted Registry;

- [Docker Trusted Registry](https://www.docker.com/docker-trusted-registry)
- [Docker Trusted Registry - Account and Repository Management](https://docs.docker.com/docker-trusted-registry/accounts/)
