### ISSUE TITLE
impossible to cleanup S3 storage 

### ISSUE THREAD

**Issue by agsmorodin** [docker/distribution#952]
I am using docker registry 2.1 with S3 backend and I need to remove some images from registry.  as I see it's not possible currently to remove them using API (https://github.com/docker/distribution/issues/422).
Example of request:
curl -X DELETE  my_registry_domain/v2/repositories/test-image/tags/latest
{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}

but is it possible and safe to remove images manually from S3?  as I see there are two directories on S3:  blobs and repositories. So what happens if I will just remove directory /repositories/test-image ?

**Comment by RichardScothern** [comment]
You can remove `repositories/test-image` manually without any problems, but you won't reclaim much disk space as this is dominated by the layers stored in the `blobs` directory.  You can manually delete files from the `blobs` directory, _if and only if you can be sure that no other repository is accessing them_

I know this isn't ideal, and there will be more functionality to help with this in the near future.
