### ISSUE TITLE
Toggling REGISTRY_AUTH on causes a certificate error with registry:2

### ISSUE THREAD

**Issue by jbaviat** [docker/distribution#954]
# TL;DR
Turning REGISTRY_AUTH on a working docker daemon with self a signed certificate and `--insecure-registry 10.7.7.7:5000` causes SSL errors.

# Details 

My registry is setup with a self-signed certificate. On the client, the docker daemon runs with `--insecure-registry 10.7.7.7:5000`.
Everything works fine:
```shell
$ docker pull 10.7.7.7:5000/ubuntu
Pulling repository 10.7.7.7:5000/ubuntu
Error: image ubuntu:latest not found
```
If I add the following lines to the `docker-compose` file `registry.yml`:
```
REGISTRY_AUTH: htpasswd
REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
```
I restart the registry, the following happens:
```
FATA[0009] Error response from daemon: v1 ping attempt failed with error:
Get https://10.7.7.7:5000/v1/_ping: x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "myregistry.com").
If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 10.7.7.7:5000` to the daemon's arguments.
In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/10.7.7.7:5000/ca.crt
```
Therefore I can successfully authenticate using:
```shell
$ curl -u user -k https://10.7.7.7:5000/v2/_catalog
```

# Using
Tested on two clients:
```
Docker version 1.7.0, build 0baf609
Docker version 1.6.2, build 7c8fca2/1.6.2
```
And on today's (2015-09-04) Docker hub `registry:2`.

**Any clue**?

**Comment by dmp42** [comment]
Hi @jbaviat 

This is likely your answer: https://github.com/docker/distribution/blob/master/docs/insecure.md#docker-still-complains-about-the-certificate-when-using-authentication

Let me know if this doesn't fix your problem and this needs to be reopened.

**Comment by jbaviat** [comment]
Hi @dmp42, 

Thanks for the link, byt it did not fix my issue. After authorizing the self-signed certificate system wide, the following command runs smoothly (without certificate warning):
```shell
$ curl https://10.7.7.7:5000/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":null}]}
```
But docker still complains on `docker login`.

**Comment by dmp42** [comment]
Your curl indicate that you must use authentication to access your registry, and that's all.

For the other part: you need to restart the docker daemon after trusting the certificates.
