### ISSUE TITLE
Manifest Deletion

### ISSUE THREAD

**Issue by xiekeyang** [docker/distribution#956]
@stevvooe ,
Now distribution support Manifest Deletion, via DELETE /v2/<name>/manifests/<reference>.
However, user must input manifest digest which is hard to get. (As I know, no V2  API can retrieve manifest digest.)
i think we can improve implementation, to support deleting manifest by its tag. Do you agree?

**Comment by oilbeater** [comment]
+1 

Deleting image by digest is really hard, no api can return a digest for a given tag.

**Comment by dongmx** [comment]
GET /v2/<name>/manifests/<tag> . This can return a header named Docker-Content-Digest which is digest

**Comment by stevvooe** [comment]
@dongmx Thank you. That is indeed the correct way to resolve the manifest revision.

Unfortunately, if we allow deletion by tag, there is the risk of race conditions and data loss. Allowing deletion by manifest ensures that only the specified item is deleted. Making a call to `GET /v2/<name>/manifests/<tag>` effectively selects the current revision for deletion, ensuring you don't stop on a concurrent writer.

**Comment by xiekeyang** [comment]
@stevvooe  @dongmx It is OK. Thanks so much!
