### ISSUE TITLE
Issue running docker registry on coreos

### ISSUE THREAD

**Issue by madhurranjan** [docker/distribution#958]
Hi,
Below is the docker version I'm running:
$ docker --version
Docker version 1.6.2, build 7c8fca2-dirty

The only time I'm able to get docker registry(registry:2) to run is when I run the following command:
docker run -d -p 80:5000 --restart=always --name registry \
  -v `pwd`/certs:/certs \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key 

When I try running it with a 'config.yaml' for the exact same options, it doesn't work. 

```
$ cat config.yaml
version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
log:
  level: debug
http:
  addr: 0.0.0.0:80
  tls:
    certificate: /certs/domain.crt
    key: /certs/domain.key
  debug:
    addr: localhost:5001
```

I use the following command to start it:

```
$ docker run -d -p 80:5000 --restart=always --name registry -v `pwd`/config.yml:/etc/docker/registry/config.yml -v `pwd`/certs:/certs registry:2
```

When I try to push an image, I see 
 Error response from daemon: v1 ping attempt failed with error: Get https://< >:80/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry <>:80` to the daemon's arguments. 

$docker logs registry 
time="2015-09-07T10:40:22.574469683Z" level=debug msg="filesystem.List(\"/\")" instance.id=75ce54a3-909e-4fbc-ae2c-a2f68209de26 trace.duration=74.425µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=00860c8e-fb4a-4ead-95fc-4c697c1860bf trace.line=123 version=v2.1.1 

I have the right ssl certificates in place so not sure why its not working. Eventual goal is to get it working with S3 but even that is not working , when I provide values via command line ( REGISTRY_STORAGE_S3_REGION, REGISTRY_STORAGE_S3_BUCKET and REGISTRY_STORAGE_S3_ROOTDIRECTORY) or when I provide S3 values in the yaml. 

Can someone help me out here please?

**Comment by dmcgowan** [comment]
Can you send debug logs from your docker daemon. The v2 registry was not able to be contacted and then attempted v1, giving the error you see. The daemon logs should include more information as to what is wrong with the setup. 

Just add the `-D` flag to your docker daemon command `docker -D -d`

**Comment by stevvooe** [comment]
@madhurranjan The issue is that the registry is bound to a clear text port, when the config is setup for tls. Change `addr: 0.0.0.0:80` to `addr: 0.0.0.0:443` and this will work.

**Comment by madhurranjan** [comment]
Thanks @dmcgowan   

Running it in debug helped me understand what was happening. 

@stevvooe  I had to then make sure I have the same port in the yaml and the docker run command got it up and running.  Thanks for pointing it out.

To summarize:
$ docker run -d  -p 80:5000  --restart=always --name registry -v `pwd`/config.yml:/etc/docker/registry/config.yml -v `pwd`/certs:/certs registry:2  - worked
or ( docker run -d -p 80:443 ... also worked)
and in config.yaml, you have to have the same port for the addr key (addr: 0.0.0.0:5000 or addr: 0.0.0.0:443 ) depending on what port you want your container to run. Quite a stupid mistake but it just didn't hit me previously.
