### ISSUE TITLE
Use custom media types for request and responses

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#96]
Custom media types will make it easier for us to iterate on request and response formats for API methods. It will also make migrating to new formats and maintaining backward compatibility much more straightforward.

Implementation plan:
1. Experiment with media types in webhook implementation #42. For this, we'll try to use `application/vnd.docker.distribution.events.v1+json` for the event format.
2. Set baseline use of `application/json` to refer to the current specification.
3. Define custom media types for other formats (manifest, layers, etc.). Here are some possible examples:
   - _Layer_: `application/vnd.docker.distribution.layer+tar`
   - _Manifest_: `application/vnd.docker.distribution.manifest.v1+json`
   - _Signed Manifest_: `application/vnd.docker.distribution.manifest.v1+prettyjws`

**Comment by dmcgowan** [comment]
Discussion now a part of OCI artifacts spec
