### ISSUE TITLE
/etc/docker/certs.d/ SAN certificates are ignored

### ISSUE THREAD

**Issue by jbaviat** [docker/distribution#961]
My server has no DNS record. 
I generated a self signed certificate with Subject Alternate Name IP:
```
subjectAltName=IP:<myIP>
```
I placed my self signed certificate there:
```
/etc/docker/certs.d/<myIP>:5000/ca.crt
```
Therefore such a certificate is ignore by Docker.

**Comment by dmcgowan** [comment]
If you found a bug related to these certificates it should be filed with the Docker daemon at https://github.com/docker/docker/issues. However not sure this would be a Docker bug, you need to ensure that your certificate configuration is supported with the standard Go `x509` library.
