### ISSUE TITLE
registry -version states 2.1.0 version while it should be 2.1.1

### ISSUE THREAD

**Issue by jordimassaguerpla** [docker/distribution#962]
I've compiled registry from source by running

make clean
make binaries

and I run 

bin/registry -version

and it returns 2.1.0+unknown

I would expect 2.1.1+unknown

I've tried chaning 2.1.0 by 2.1.1 in version/version.go but that didn't fixed it.

**Comment by stevvooe** [comment]
The version number is set using the git source and the Makefile. Please make sure you are correctly following [the build instructions](https://github.com/docker/distribution/blob/master/docs/building.md).

When I do the same locally, I get the following:

```
$ bin/registry -version
bin/registry github.com/docker/distribution v2.1.1-51-g7c5a9ae
```

The value `2.1.0+unknown` is just a default value we rev every minor release (not patch release). When we see this value, it means the linker is not having the correct version number set.

What system are you on (ie `uname -a`)?
What is the output of `go version`?
What is the output of `make --version` of make do you have?
Inside of your git checkout, what is the output of `git describe --match 'v[0-9]*' --dirty='.m' --always`?
If you run `go build -o ./registry-handbuilt -ldflags "-X $(go list ./version).Version v2.1.1-handbuilt-test"   ./cmd/registry`, then run `./registry-handbuilt -version`, what is the output of the commands?

**Comment by jordimassaguerpla** [comment]
On 09/08/2015 08:33 PM, Stephen Day wrote:
>
> The version number is set using the git source and the Makefile. 
> Please make sure you are correctly following the build instructions 
> <https://github.com/docker/distribution/blob/master/docs/building.md>.
>

I did a "git clone" of this project

> When I do the same locally, I get the following:
>
> |$ bin/registry -version
> bin/registry github.com/docker/distribution v2.1.1-51-g7c5a9ae
> |
>
> The value |2.1.0+unknown| is just a default value we rev every minor 
> release (not patch release). When we see this value, it means the 
> linker is not having the correct version number set.
>
> What system are you on (ie |uname -a|)?
>

Linux linux-k9jw.site 3.16.7-21-desktop
openSUSE 13.2

> What is the output of |go version|?
>

go version go1.5 linux/amd64

> What is the output of |make --version| of make do you have?
>


GNU Make 4.0
Built for x86_64-unknown-linux-gnu

> Inside of your git checkout, what is the output of |git describe 
> --match 'v[0-9]*' --dirty='.m' --always|?
>

v2.1.1-49-gdbbafe9


> If you run |go build -o ./registry-handbuilt -ldflags "-X $(go list 
> ./version).Version v2.1.1-handbuilt-test" ./cmd/registry|, then run 
> |./registry-handbuilt -version|, what is the output of the commands?
>

./registry-handbuilt github.com/docker/distribution v2.1.0+unknown


If I run "make clean;make binaries" this is the output


+ /home/jordi/work/docker-distribution/bin/registry
# _/home/jordi/work/docker-distribution/cmd/registry
link: warning: option -X 
_/home/jordi/work/docker-distribution/version.Version v2.1.1-49-gdbbafe9 
may not work in future releases; use -X 
_/home/jordi/work/docker-distribution/version.Version=v2.1.1-49-gdbbafe9
+ /home/jordi/work/docker-distribution/bin/digest
# _/home/jordi/work/docker-distribution/cmd/digest
link: warning: option -X 
_/home/jordi/work/docker-distribution/version.Version v2.1.1-49-gdbbafe9 
may not work in future releases; use -X 
_/home/jordi/work/docker-distribution/version.Version=v2.1.1-49-gdbbafe9
+ /home/jordi/work/docker-distribution/bin/registry-api-descriptor-template
# _/home/jordi/work/docker-distribution/cmd/registry-api-descriptor-template
link: warning: option -X 
_/home/jordi/work/docker-distribution/version.Version v2.1.1-49-gdbbafe9 
may not work in future releases; use -X 
_/home/jordi/work/docker-distribution/version.Version=v2.1.1-49-gdbbafe9
+ binaries

note the "v2.1.1-49-gdbbafe9"

and then I run ./bin/registry -version and I still get v2.1.0+unknown

I've also tried this as in the building instructions:

|go get github.com/docker/distribution/cmd/registry
/home/jordi/go/bin/registry -version

and the outputs is
go/bin/registry github.com/docker/distribution v2.1.0+unknown

ls -l /home/jordi/bo/bin/registry
(...) Sep  9 10:14 (<- which is now)


Then I tried following the instructions on the building.md
|
||go get github.com/tools/godep github.com/golang/lint/golint
cd /home/jordi/go/src/github.com/docker/distribution/
GOPATH=`/home/jordi/go/bin/godep path`:$GOPATH make

and I get the error

vet: import failed: reading export data: /usr/lib64/go/pkg/linux_amd64/fmt.a: go archive is missing __.PKGDEF


||

**Comment by jordimassaguerpla** [comment]
Hi! I think the problem is on my side . Wrong configuration of the GO_PATH.

**Comment by jordimassaguerpla** [comment]
Hi! You can reproduce the issue if you install registry with go get.

**Comment by stevvooe** [comment]
@jordimassaguerpla `go get` does not support correctly setting the version number. We may be able to fix this with `go generate` somehow.

In general, we only support correctly setting the version number when built with the `Makefile` with a correctly setup build environment. Looking at the output from above, we can tell the project is not checked out in `GOPATH` because the package names are prefixed with _/home/jordi/work/docker-distribution/`.
