### ISSUE TITLE
Backwards incompatible change on webhook notifications from 2.0 to 2.1

### ISSUE THREAD

**Issue by mssola** [docker/distribution#966]
Using Docker 1.8.1, I pushed a new tag to my private registry that is configured to send notifications. If this registry is Distribution v2.0.1, I get the following JSON response:

```
{"events"=>[{"id"=>"3fccdb28-8db0-4323-8b16-c5d65229dc2b", "timestamp"=>"2015-09-09T10:08:09.384689416Z", "action"=>"push", "target"=>{"mediaType"=>"application/vnd.docker.distribution.manifest.v1+json", "length"=>5059, "digest"=>"sha256:1977980aad73e19f918c676de1860b0ee56167b07c20641ecda3f9d74b69627d", "repository"=>"mssola/busybox", "url"=>"http://registry.test.lan/v2/mssola/busybox/manifests/latest"}, "request"=>{"id"=>"c53734bd-9aac-47d8-952f-2f787d633aa9", "addr"=>"192.168.1.4:44883", "host"=>"registry.test.lan", "method"=>"PUT", "useragent"=>"docker/1.8.1 go/go1.4.2 git-commit/786b29d kernel/3.16.6-2-default os/linux arch/amd64"}, "actor"=>{"name"=>"mssola"}, "source"=>{"addr"=>"registry.test.lan:80", "instanceID"=>"506e2835-275d-459b-8a7e-16181f484b41"}}]}
```

As you can see, both the digest and the tag are specified (the tag being embedded in the URL). However, Distribution 2.1 changed this, and in the URL the digest is specified instead of the tag. Therefore, the same event in v2.1.1 is as follows:

```
{"events"=>[{"id"=>"a560cc74-0a49-4f9b-87f8-00c954a4f270", "timestamp"=>"2015-09-09T09:29:53.970030734Z", "action"=>"push", "target"=>{"mediaType"=>"application/vnd.docker.distribution.manifest.v1+json", "size"=>5059, "digest"=>"sha256:1977980aad73e19f918c676de1860b0ee56167b07c20641ecda3f9d74b69627d", "length"=>5059, "repository"=>"mssola/busybox", "url"=>"http://registry.test.lan/v2/mssola/busybox/manifests/sha256:1977980aad73e19f918c676de1860b0ee56167b07c20641ecda3f9d74b69627d"}, "request"=>{"id"=>"c4a972b9-11c3-4967-b6e1-2773951a796a", "addr"=>"192.168.1.4:44866", "host"=>"registry.test.lan", "method"=>"PUT", "useragent"=>"docker/1.8.1 go/go1.4.2 git-commit/786b29d kernel/3.16.6-2-default os/linux arch/amd64"}, "actor"=>{"name"=>"mssola"}, "source"=>{"addr"=>"registry.test.lan:80", "instanceID"=>"9310f328-b887-44b7-a7af-8242051d3a6b"}}]}
```

Which leads to the unfortunate situation in which now we get the same digest twice but we don't get the tag that has been pushed anymore. Of course, with this digest one can fetch the image manifest to get the tag, but I think that it defeats a bit the purpose of this mechanism if we have to perform a request anyways for each notification that we get.

There are two ways to fix this in my opinion:

1. Do as it was done in v2.0.1 and specify the tag in the URL instead of the digest.
2. Provide an extra key `tag` that specifies the tag that has just been pushed.

The first option is not desirable (see commit https://github.com/docker/distribution/commit/a2d4f51aa41cdf43de5cdde1653e704725921e18). Therefore, what's your opinion of adding a `tag` key inside of the `target` (I can write the patch myself ;) ) ?

**Comment by stevvooe** [comment]
@mssola Sending a `tag` as part of the canonical URL for the manifest resource was a bug, as it does not uniquely identify the manifest. Either way, the URL field is the URL of the target resource and has no specified format. Relying on the structure of the URL is effectively not supported.

For V2 schema1 manifests, the supported method of accessing the tag is to fetch the resource and read the tag field.

**Comment by mssola** [comment]
I agree that relying on the URL field in order to fetch the tag is a bad idea (since as you say, that was a bug). That being said, it was really convenient that the notification response included the tag that was being pushed. Otherwise, whenever a notification comes in, the listener has to perform a call to get the manifest.

That's why I mentioned the second option. Because it would be really convenient that the notification response also had the tag included inside of the `target`.

**Comment by stevvooe** [comment]
@mssola The fact that manifests have tags is a side-effect of an incomplete data model. When tags become a first class citizen, they will have a separate notification. The fact that a notification event target is a manifest or tag is not of a concern to the notification system. It is just pointing to a resource within the repository that has a content address. This allows us to appropriately decouple the data models, avoiding us having to update the event notification system when we change the docker data model. We also get the benefit that the contents of the resource are fully protected by the same access policies as if fetched via the API.

The future proof method of implementing this functionality is to fetch the resource and attempt to resolve the tag. Be it a schema1 manifest or some new type, such as a tag, you'll be able to update that function to handle new formats as added without changing the architecture of the notification endpoint.

While I understand it is inconvenient to fetch the resource upon receiving a notification, keeping this data model simple and normalized will ensure it can handle future manifestations of docker resources.

**Comment by mssola** [comment]
Sounds good. I didn't know that you were planning about adding a separate notification. I cannot see it in your PR #173. Is it somewhere else ?

**Comment by stevvooe** [comment]
@mssola There is lot of work to be done in this area. #173 was a proposal and request for commentary but is pretty incomplete.

Let me know if you have more questions or feedback that we should incorporate.

**Comment by RichardScothern** [comment]
@toli
