### ISSUE TITLE
Comparing images

### ISSUE THREAD

**Issue by kevinsimper** [docker/distribution#969]
In issue #628 there was a question on how to get the image id, but it was said `V2 API does not deal in Image ID`.

But if you do a `docker ps`, you still see the image id.

- I have a registry running. 
- A user push an image to the registry 

How can i determine if the image was updated, or i was just the same as before?

eg. What is the proper way to compare two docker images?

**Comment by RichardScothern** [comment]
`docker ps` gives the container ID.

If you want to see which image a tag is pointing to you can fetch it from the registry and read the `Docker-Content-Digest` header.  If you want to know if an image has been re-pushed you can use the registry notification system.

**Comment by kevinsimper** [comment]
@RichardScothern Thanks for your reply.

> docker ps gives the container ID.

Correct, i meant `docker images`, my mistake!

> If you want to see which image a tag is pointing to you can fetch it from the registry and read the Docker-Content-Digest header.

Okay, but why aren't that part of the api json response?

Just to clarify,  if you were going to traverse the registry to build up the information, you would first

`GET /v2/_catalog`

Then you would have to request each individual image

`GET /v2/<name>/tags/list``

And then get for each image and its tags, fetch them individually:

`GET /v2/<name>/manifests/<reference>`

And now you have all the `Image Id`'s, correct?

**Comment by RichardScothern** [comment]
The ID is metadata about the response, and is included in the header with other metadata.

Your steps to get all image IDs are correct.  As I mentioned before, you can collect image IDs changes by observing registry notifications.

**Comment by kevinsimper** [comment]
@RichardScothern I worked with it today and even images that is the same, but is tagged different has different id's.

I have nginx, and i can get that id by doing `docker images --no-trunc`.
That id is not the same in Docker-Content-Digest, nor is image made with `docker tag nginx something/else-nginx`, which if you again look, would have the same id.

`

**Comment by RichardScothern** [comment]
The IDs in `docker images` cannot be used for image comparison.  You have to do one of the steps above.

**Comment by kevinsimper** [comment]
@RichardScothern Thank you, I understand it now :+1:
