### ISSUE TITLE
Error response from daemon: Unexpected status code [503]

### ISSUE THREAD

**Issue by plamer** [docker/distribution#972]
Hello there,

I'm trying to run a private docker registry, but with 2.1.1 I see this when I try to login from another docker:

    Error response from daemon: Unexpected status code [503] : {"errors":[{"code":"UNAVAILABLE","message":"service unavailable","detail":"health check failed: please see /debug/health"}]}

This is the log from the container:

    <IP> - - [10/Sep/2015:17:37:46 +0000] "GET /v2/ HTTP/1.1" 503 125 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-123.20.1.el7.onapp.x86_64 os/linux arch/amd64"
    <IP> - - [10/Sep/2015:17:37:46 +0000] "GET /v1/_ping HTTP/1.1" 503 125 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-123.20.1.el7.onapp.x86_64 os/linux arch/amd64"
    <IP> - - [10/Sep/2015:17:37:46 +0000] "POST /v1/users/ HTTP/1.1" 503 125 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-123.20.1.el7.onapp.x86_64 os/linux arch/amd64"

docker version:
   
    Client version: 1.7.1
    Client API version: 1.19
    Package Version (client): docker-1.7.1-108.el7.centos.x86_64
    Go version (client): go1.4.2
    Git commit (client): 3043001/1.7.1
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Package Version (server): docker-1.7.1-108.el7.centos.x86_64
    Go version (server): go1.4.2
    Git commit (server): 3043001/1.7.1
    OS/Arch (server): linux/amd64

**Comment by stevvooe** [comment]
@plamer It looks like the backend health check failed and the registry service disabled itself. Did you check `/debug/health` on the debug interface as error message suggested ("health check failed: please see /debug/health")? The cause should be called out there.

Do you have the full registry logs? They may also provide a hint to the problem.

**Comment by RichardScothern** [comment]
@plamer any update this.  Did `/debug/health` help?

**Comment by plamer** [comment]
Hey @RichardScothern , sorry for the delay, I was away. I ended up rebuilding the machine and everything worked fine now. No idea what happened..

**Comment by ffedoroff** [comment]
I had that problem when s3 bucket was empty. After I put sample /docker/sample.file into the bucket it starts works for me. Maybe it is better to reopen the issue?

**Comment by micahstubbs** [comment]
I saw this error, then visited https://status.docker.com/

🤦‍♂️ 

![screen shot 2018-08-25 at 11 11 54 am](https://user-images.githubusercontent.com/2119400/44621260-b9f0fe80-a857-11e8-9407-07d06f76a0af.png)
