### ISSUE TITLE
docker search returns 404

### ISSUE THREAD

**Issue by dmilltech** [docker/distribution#975]
docker search :5000/centos
Error response from daemon: Unexpected status code 404

curl -k -s -X GET https://@:5000/v2/centos/tags/list
{"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":[{"Type":"repository","Name":"centos","Action":"pull"}]}]}

**Comment by stevvooe** [comment]
@dmilltech Docker search is not yet supported with the V2 registry. Please see the [road map](https://github.com/docker/distribution/blob/master/ROADMAP.md#indexing-search-and-discovery) for details.
