### ISSUE TITLE
secure access to an insecure mode registry

### ISSUE THREAD

**Issue by jhicks-camgian** [docker/distribution#984]
Another convenient way to access a local repository from another machine is to simply use an SSH tunnel.

From one terminal window:
````
$ ssh -L5000:localhost:5000 user@localregistryhost
````
Then from another terminal window:
````
$ docker pull localhost:5000/foo/bar:image
````
Voila!

Seems to work quite sufficiently for casual development use without worrying over setting up certificates or opening up an actually insecure can-o-worms.

Cheers,

Jerry Hicks.

**Comment by stevvooe** [comment]
In the future, the mailing list or an addition to the documentation might be a better venue for this.

Thank you for the tip.

**Comment by jhicks-camgian** [comment]
Yeah, I'm saturated busy and don't have time for a mailing list (or even eating breakfast these days <grin>)

Just wanted to park it somewhere quick before I forgot to tell someone.

**Comment by stevvooe** [comment]
@jhicks-camgian Thanks!
