### ISSUE TITLE
Docker push as tutorial says.

### ISSUE THREAD

**Issue by bweston92** [docker/distribution#985]
I've logged in with success to my docker registry, however Docker push isn't working due to this error:

```
5b8a22941c82: Buffering to Disk
The push refers to a repository [{hidden}] (len: 1)
5b8a22941c82: Pushing [==================================================>]
unauthorized: access to the requested resource is not authorized
```

Docker info
```
C:\Program Files\Docker Toolbox> docker info
Containers: 9
Images: 186
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 204
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: PVUJ:2VNG:2AIG:POY7:KYBT:4FDG:BMLO:OES5:V3IZ:XLLZ:TO7O:KXJW
Debug mode (server): true
File Descriptors: 23
Goroutines: 50
System Time: 2015-09-15T11:24:19.551609411Z
EventsListeners: 1
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: {hidden}
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

Docker registry is version `2`. The tutorial I am following is [here](https://blog.docker.com/2013/07/how-to-use-your-own-registry/) from 2013 I know but the commands are still the same.

![image](https://cloud.githubusercontent.com/assets/1764057/9900231/490e8e7a-5c57-11e5-80be-7037d000cdb1.png)

**Comment by RichardScothern** [comment]
@bweston92 we will more information to debug this.

Can you follow the instructions here: https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#reporting-an-issue-properly

**Comment by bweston92** [comment]
Added an image; Marlow is the server with the registry and Chance is the test server trying to push the new tag. Chance has successfully logged in to the registry via the `docker login` command.

**Comment by RichardScothern** [comment]
I've just noticed the link you posted - those instructions are very likely out of date.

Please have a look at this:
https://github.com/docker/distribution/blob/master/docs/deploying.md

**Comment by bweston92** [comment]
I used that initially and to setup my registry but didn't work either. Still produces what is up top.



—

**Comment by RichardScothern** [comment]
Can you try again, following the link above.  If you are getting the same result, please post your registry logs, and daemon logs in text format.

The error you are seeing refers to authorization; did you configure that independently?

**Comment by schmunk42** [comment]
I had a similar issue when running a push from a Gitlab runner container (`/var/sock/docker.sock` linked into the container) and user names did not match.

Somehow the initial login and push were made in the container, but an action at the end (digest?) was run exclusively on the host, which did not have the credentials (`/root/.docker/config.json`) in the right place.

**Comment by schmunk42** [comment]
I was able to fix my issue by manually logging in via CLI to DockerHub.
There was the `https://index.docker.io/v1/` part added.

```
"auths": {
		"https://index.docker.io/v1/": {
			"auth": "XXXXXXXX==",
			"email": "x@y.z"
		},
		"index.docker.io": {
			"auth": "XXXXXXXXXXXX==",
			"email": "x@y.z"
		},
	}
````

**Comment by dinhtrung** [comment]
@schmunk42 Your fix save me an entire night! :+1:

**Comment by cuixin** [comment]
@schmunk42 solved my problem. Tkx!

**Comment by bweston92** [comment]
@schmunk42 so this is a bug that needs fixing?

**Comment by dmp42** [comment]
All: this issue unfortunately is not actionable:

 * the instructions used originally are completely out of date and no longer current or supported
 * people comment with completely unrelated concerns

I'm going to close this issue for that reason.

If you still have an issue, please open a new, specific one and make sure you read https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#reporting-an-issue-properly and provide at least basic information about your setup version, configuration, and logs.
