### ISSUE TITLE
app.RegisterRoute is removed from v2.1.1

### ISSUE THREAD

**Issue by AdoHe** [docker/distribution#986]
FYI. I want to know why? and if this method is remove how can we add custom route if we want to deploy our own docker registry based on distribution?

**Comment by RichardScothern** [comment]
@AdoHe : handlers are statically registered in the App on initialization.

What are you trying to achieve?

**Comment by AdoHe** [comment]
@RichardScothern I just want to add extra handlers after I called `app := handlers.NewApp(ctx, config)`, now it seems impossible.

**Comment by RichardScothern** [comment]
That is not really the way the Registry is designed for. 

You can embed a registry object in your own application, otherwise the registry supports extensibility via the middleware configurations.

**Comment by AdoHe** [comment]
@RichardScothern , I decided to use the middleware, thanks anyway.

**Comment by stevvooe** [comment]
@AdoHe I am not sure that this method ever existed. Is there a specific revision you were using? The app itself is just a handler, so you can just assemble it in a larger web application.

Remember that the packages are considered unstable and the interfaces may change at any time.
