### ISSUE TITLE
notifications filter

### ISSUE THREAD

**Issue by AdoHe** [docker/distribution#987]
FYI. is there any way to filter the notifications? for example, when I push an image, I will get a lot of notifications, how can I filter this notifications? I just want to get the last one notification. I can't find the configuration related to this.

**Comment by RichardScothern** [comment]
Please do not use github issues to ask questions.  If you have a question, you can post it to #docker-distribution-dev.

If you only want to get specific events you should filter them in whichever service is receiving the notifications.

**Comment by AdoHe** [comment]
@RichardScothern Ok, sorry about that, I will post this to #docker-distribution-dev
